### ISSUE TITLE
full length transcripts

### ISSUE THREAD

**Issue by rojinsafavi** [lh3/minimap2#100]
Hi,
I have a question about how minimap2 detects isoforms in (ONT direct RNA reads + transcriptom given as the reference). 
Is there anyway to see how many exons were able to be detected? Ex. if minimap2 says your read is aligned to transcript X1, can I be sure that the first and last exon are in the read? or that all exons that were detected are in consecutive order?
Thanks in advance!

**Comment by lh3** [comment]
I would map to the reference. In general, if you see the polyA tail on the read, you know where the 3'-end starts. You often don't know for sure if it reaches the 5'-end.
