### ISSUE TITLE
Gap extension penalty

### ISSUE THREAD

**Issue by xtan1221** [lh3/minimap2#1000]
Hi there, 

I found that the parameters for gap extension penalty is linear to the length of the gap in v2.24:
```
-O INT[,INT] gap open penalty [4,24]
-E INT[,INT] gap extension penalty; a k-long gap costs min{O1+k*E1,O2+k*E2} [2,1]
```
which is different from the strategy described in the 2021 paper:
```
log2(1+k)
```
Could you please confirm this is the case or I misunderstood it?

Thanks!

**Comment by lh3** [comment]
log is used for rescoring only
