### ISSUE TITLE
Mapping ONT long reads to short references

### ISSUE THREAD

**Issue by Davood-Norouzi** [lh3/minimap2#1001]
Hi,

Thanks for the great tool! I hope this is the right place to ask these kind of questions:

I am working on a technology that inserts a piece of ~50bp DNA in a region of ~6kb. There are 100 specific sites for the insertion. We use long read sequencing for the entire region. Hence, one set of primers rather than 100. Much simpler.

Now all my reads are ~6kb from the ONT sequencing. I want to find the exact location of the inserts in these amplicons/reads. 

One idea is to add ~30 bp from each side of the insert locations (plus the 50 bp insert and without it as WT). Therefore, I will have 2*100 reference sequences.

These 200 rather short sequences are my reference now.

Is minimap2 effective at mapping long reads to short references? Are there any parameters, I need to tweak, in this case when running minimap2?

Thank you in advance,
-Dave

**Comment by lh3** [comment]
The default may work.

**Comment by jnkoberstein** [comment]
@Davood-Norouzi I am facing a similar problem of aligning long reads to identify insertion positions. Did you end up using default parameters or did you find any changes that improve alignments?
