### ISSUE TITLE
Problem comparing to sequenced genomes

### ISSUE THREAD

**Issue by scottcain** [lh3/minimap2#1002]
Hello,

I am trying to use minimap2 to compare the assembled genomes of two fairly closely related C. elegans genomes:
```
$ minimap2  c_elegans.PRJNA13758.WS282.genomic.fa.gz c_elegans.PRJNA275000.WS287.genomic.fa > c_elegans_PRJNA13758.c_elegans_PRJNA275000.paf
[M::mm_idx_gen::0.000*4.27] collected minimizers
[M::mm_idx_gen::0.001*3.34] sorted minimizers
[M::main::0.001*3.31] loaded/built the index for 0 target sequence(s)
[M::mm_mapopt_update::0.001*3.24] mid_occ = 1000000
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 0
[M::mm_idx_stat::0.001*3.17] distinct minimizers: 0 (-nan% are singletons); average occurrences: -nan; average spacing: -nan; total length: 0
[M::worker_pipeline::1.586*2.39] mapped 7 sequences
[M::main] Version: 2.24-r1122
[M::main] CMD: minimap2 c_elegans.PRJNA13758.WS282.genomic.fa.gz c_elegans.PRJNA275000.WS287.genomic.fa
[M::main] Real time: 1.588 sec; CPU: 3.786 sec; Peak RSS: 0.607 GB
```
It completes very quickly with no output. Things that seem a little odd about this is the part that says `0 target sequence(s)` and then the references to `-nan`.  The sequences I'm using are here:

https://downloads.wormbase.org/releases/WS287/species/c_elegans/PRJNA13758/c_elegans.PRJNA13758.WS287.genomic.fa.gz

and

https://downloads.wormbase.org/releases/WS287/species/c_elegans/PRJNA275000/c_elegans.PRJNA275000.WS287.genomic.fa.gz

Any ideas?

**Comment by scottcain** [comment]
As an aside, I also tried `-c -x asm5` options and that failed in the same way.

This is with version 2.24-r1122

**Comment by lh3** [comment]
> [M::main::0.001*3.31] loaded/built the index for 0 target sequence(s)

Almost certainly errors on your side.
