### ISSUE TITLE
fermikit and mag file 

### ISSUE THREAD

**Issue by wyim-pgl** [lh3/minimap2#1005]
Hi Li,
I know this is not related to minimap2 but I wonder that you could answer this question.
Can I consider mag file from Fermikit to FASTQ file?
I want to reconstruct some loci in rice, I want to used Fermikit for preassembly and use it for phased assembler.
I know it will lose the Illumina reads count but we only have Illumina reads.

**Comment by lh3** [comment]
Sorry for the late response.

> Can I consider mag file from Fermikit to FASTQ file?

Yes
