### ISSUE TITLE
PAF unique-mapped output

### ISSUE THREAD

**Issue by kcasctivcr** [lh3/minimap2#1006]
Hello,

I use minimap2 to map ONT long reads against transcript sequences
I was hoping to get a single transcript best hit for each reads
The parameters I use are -x map-ont, -c and --secondary=no
However, in the output PAF file, there is still multiple rows for a single read even if I removed multi-mapping reads (mapq = 0)
How can I keep the best hit only?

Thanks in advance

**Comment by lh3** [comment]
See [FAQ](https://github.com/lh3/minimap2/blob/master/FAQ.md#5-how-to-output-one-alignment-per-read).
