### ISSUE TITLE
paftools.js error  can't find the length of contig 

### ISSUE THREAD

**Issue by theo-allnutt-bioinformatics** [lh3/minimap2#1009]
paftools.js sam2paf brass.sam > brass.paf
/g/data/nm31/bin/minimap2/misc/paftools.js:1732: Error: at line 6: can't find the length of contig MT726210.1 Brassica rapa chloroplast, complete genome
                if (tlen == null) throw Error("at line " + lineno + ": can't find the length
                          ^
Error: at line 6: can't find the length of contig MT726210.1 Brassica rapa chloroplast, complete genome
    at Error (<anonymous>)
    at paf_sam2paf (/g/data/nm31/bin/minimap2/misc/paftools.js:1732:27)
    at main (/g/data/nm31/bin/minimap2/misc/paftools.js:3189:29)
    at /g/data/nm31/bin/minimap2/misc/paftools.js:3215:1

[brass.sam.txt](https://github.com/lh3/minimap2/files/10430323/brass.sam.txt)

**Comment by theo-allnutt-bioinformatics** [comment]
Seems it can't handle spaces in the fasta headers.

**Comment by lh3** [comment]
Well, there should not be spaces in SAM headers because everything after a space is not part of sequence names.

**Comment by theo-allnutt-bioinformatics** [comment]
Well, sometimes sam headers do have spaces because the mapping tool put them there from the corresponding fasta header. So I think it is worth pointing out.

**Comment by lh3** [comment]
I know that, but I am not obliged to support tools that break the fasta convention.
