### ISSUE TITLE
More than 1 best mapping

### ISSUE THREAD

**Issue by aderzelle** [lh3/minimap2#101]
Hello,

I have a set of contigs that I map against themselves. minimap2 correctly identifies the trivial self alignment but doesn't report other alignments. 
What I mean is that, the contig 1 matches with contig 1, which is both correct and trivial, but it should also matches with contig 4 (as reported by lastz and last, for example). However, minimap2 omits those matchings. 

The command I used is
`minimap2 -t 8 -x asm5 contigs.fa contigs.fa > contigs.paf `

Is it the expected behaviour? 

Thank you

**Comment by lh3** [comment]
The default setting is not intended for self mapping. You may try to add option `-X`.

**Comment by aderzelle** [comment]
Thank you, that kind of worked, in the sense that it reports other mapping that the self mapping. But the self mapping is still reported anyway. 
But for what I wanted, that's enough. 

Thanks a lot

**Comment by lh3** [comment]
With `-X`, minimap2 should not report the identical self-mapping (i.e. full chr1 matches itself exactly). Is that right? With `-X`, minimap2 could report, for example, chr1:1000-2000 matches chr1:5000-6000.
