### ISSUE TITLE
Segmentation fault with -x asm20 full options.

### ISSUE THREAD

**Issue by theo-allnutt-bioinformatics** [lh3/minimap2#1010]
Using the full options for preset -x asm20 causes segmentation fault.

 minimap2 -x asm20 -t 48 brassica_chloroplast.fasta brassica_chloroplast.fasta > brassica.paf
[M::mm_idx_gen::0.034*1.02] collected minimizers
[M::mm_idx_gen::0.047*8.96] sorted minimizers
[M::main::0.047*8.96] loaded/built the index for 3 target sequence(s)
[M::mm_mapopt_update::0.049*8.63] mid_occ = 50
[M::mm_idx_stat] kmer size: 19; skip: 10; is_hpc: 0; #seq: 3
[M::mm_idx_stat::0.050*8.40] distinct minimizers: 23298 (0.10% are singletons); average occurrences: 3.605; average spacing: 5.482; total length: 460460
[M::worker_pipeline::0.205*4.28] mapped 3 sequences
[M::main] Version: 2.24-r1122
[M::main] CMD: minimap2 -x asm20 -t 48 brassica_chloroplast.fasta brassica_chloroplast.fasta
[M::main] Real time: 0.210 sec; CPU: 0.881 sec; Peak RSS: 0.030 GB

minimap2 -k19 -w10 -U50,500 --rmq -r100k -g10k -A1 -B4 -O6,26 -E2,1 -s200 -z200 -N50 -t 48 brassica_chloroplast.fasta brassica_chloroplast.fasta > brassica.paf
Segmentation fault

[brassica_chloroplast.fasta.txt](https://github.com/lh3/minimap2/files/10430633/brassica_chloroplast.fasta.txt)

**Comment by lh3** [comment]
minimap2 is done. The segfault is caused by other things.

**Comment by theo-allnutt-bioinformatics** [comment]
Are you saying minimap2 completes for you? I have tried on two different systems with the same segfault.

**Comment by lh3** [comment]
I see what you mean now. You can change "--rmq" to "--rmq=yes".
