### ISSUE TITLE
Question - internal unaligned sequence in read -- what happens?

### ISSUE THREAD

**Issue by itslittman** [lh3/minimap2#1011]
So, I know that "clipped" sequences lie on the ends of a read (both hard and soft) - what happens if there is a completely unaligned sequence in the interior of a read that is otherwise aligned to the genome? Is that read discarded by Minimap2?
I am looking at transcripts of a mouse knockout-first allele, containing a neomycin resistance cassette inserted in an exon of the target gene to put it out of frame (obviously not in refseq).
When viewing my BAM files in IGV, I see truncated transcripts from both "halves" of the gene (transcripts starting with the cassette as a right-soft-clipped seq in addition to transcripts ending with a left-clipped cassette seq), but I'm not seeing any transcripts of the entire gene with the cassette in the middle. 
Is Minimap2 discarding these sequences?

Noah

**Comment by lh3** [comment]
> When viewing my BAM files in IGV, I see truncated transcripts from both "halves" of the gene, but I'm not seeing any transcripts of the entire gene with the cassette in the middle.

This is the expectation. If the middle part is not aligned well, minimap2 will report two chimeric alignments.

**Comment by itslittman** [comment]
@lh3 So you’re saying I should see two separated tracks that look like different reads, but have the same read ID? The tracks I’m talking about have unique read IDs and are thus different reads (and they both only have soft clipping, no hard clipping). I’m a little confused as to what you mean

**Comment by lh3** [comment]
> So you’re saying I should see two separated tracks that look like different reads, but have the same read ID?

Yes

> The tracks I’m talking about have unique read IDs and are thus different reads (and they both only have soft clipping , no hard clipping).

Check the original bam on command line, not in igv. If there are no hard clippings, your data probably don't have them.
