### ISSUE TITLE
Doubt about inversion tag meaning

### ISSUE THREAD

**Issue by V-JJ** [lh3/minimap2#1012]
Hello! 

We'd like to know what's the difference between "I" and "i" for inversion tag.
```
Tag | Type | Description
tp  | A | Type of aln: P/primary, S/secondary and I,i/inversion
```
Many thanks,

**Comment by lh3** [comment]
`I` for inversion on the primary alignment and `i` for inversion on the secondary alignment. Need to document that...

**Comment by V-JJ** [comment]
Understood. Many thanks!
