### ISSUE TITLE
Quality Question

### ISSUE THREAD

**Issue by rmormando** [lh3/minimap2#1013]
I have an alignment that resulted in a MAPQ=0 but an AS:i:122 and I'm trying to understand what that means for my alignment. For context, I am mapping raw long-reads sequences from Oxford Nanopore technologies to a small 61bp section of a gene target I am searching for using this command: `./minimap2 -c raw_LR.fastq.gz tag1.fasta > results.paf`

Here is the PAF file I got from the alignment:

```
tag1 | 61 | 0 | 61 | + | 875e5fd9-10b8-47f6-84b2-9c9bbee6e901 | 36809 | 14197 | 14258 | 61 | 61 | 0 | NM:i:0 | ms:i:122 | AS:i:122 | nn:i:0 | tp:A:P | cm:i:10 | s1:i:51 | s2:i:51 | de:f:0 | rl:i:0 | cg:Z:61M
tag1 | 61 | 0 | 61 | - | ff3ef1fb-6557-4ebd-8ce4-a7cd9ee1a202 | 26240 | 18705 | 18766 | 61 | 61 | 0 | NM:i:0 | ms:i:122 | AS:i:122 | nn:i:0 | tp:A:S | cm:i:10 | s1:i:51 | de:f:0 | rl:i:0 | cg:Z:61M |  
tag1 | 61 | 0 | 61 | + | 02d92f34-22c3-4b5f-9206-0329c6c7a752 | 37453 | 9056 | 9117 | 61 | 61 | 0 | NM:i:0 | ms:i:122 | AS:i:122 | nn:i:0 | tp:A:S | cm:i:10 | s1:i:51 | de:f:0 | rl:i:0 | cg:Z:61M |  
tag1 | 61 | 0 | 61 | + | 6fdd6a9b-610b-4c1f-9b56-d29e8887fe4c | 21870 | 7982 | 8043 | 61 | 61 | 0 | NM:i:0 | ms:i:122 | AS:i:122 | nn:i:0 | tp:A:S | cm:i:10 | s1:i:51 | de:f:0 | rl:i:0 | cg:Z:61M |  
tag1 | 61 | 0 | 61 | + | 51e4cfb5-0fb9-43eb-b2e8-636f1fe0e3d5 | 9086 | 7240 | 7301 | 61 | 61 | 0 | NM:i:0 | ms:i:122 | AS:i:122 | nn:i:0 | tp:A:S | cm:i:10 | s1:i:51 | de:f:0 | rl:i:0 | cg:Z:61M |  
tag1 | 61 | 0 | 61 | - | 33381b62-72d7-4363-849d-489bb45640f2 | 38963 | 24101 | 24162 | 61 | 61 | 0 | NM:i:0 | ms:i:122 | AS:i:122 | nn:i:0 | tp:A:S | cm:i:10 | s1:i:51 | de:f:0 | rl:i:0 | cg:Z:61M |  
```

Following the logic that I saw here https://github.com/lh3/minimap2/issues/223 I believe that since the sequence tag I am mapping to is found in multiple sequences the MAPQ will be 0 and that's to be expected. From there, I should look at the AS tag to consider the quality further and with a value of 122 for every hit I believe that means it's consistent and that it's a good alignment. However, that is a total guess so I wanted to post an issue to see if that assumption is correct, the mapping alignment looks good, and if there was anything else this alignment may be telling me. 

Thanks!!

**Comment by lh3** [comment]
> I'm trying to understand what that means for my alignment.

These lines suggest there are 6 exact hits.
