### ISSUE TITLE
Error: corrupted double-linked list Aborted (core dumped)

### ISSUE THREAD

**Issue by Numbahs84** [lh3/minimap2#1014]
I am trying to run minimap2 on a ChIP-seq SRR.fastq file which I have previously ran trim-galore to remove adapter sequences on. Below is the first command I ran and the error. 
`(base) bigboi@pop-os:/media/bigboi/Seagate Desktop Drive/Shao_Chipseq_Data_Analysis$ minimap2 -a Mus_musculus.GRCm39.dna.primary_assembly.fa PPARg_ChIP-seq/Trimmed_Input/SRR14667380_trimmed.fq.gz > SRR14667380_trimmed.sam
[M::mm_idx_gen::45.216*1.40] collected minimizers
[M::mm_idx_gen::55.620*1.70] sorted minimizers
[M::main::55.620*1.70] loaded/built the index for 61 target sequence(s)
[M::mm_mapopt_update::56.935*1.68] mid_occ = 598
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 61
[M::mm_idx_stat::57.715*1.67] distinct minimizers: 97791702 (39.85% are singletons); average occurrences: 5.142; average spacing: 5.426
[M::worker_pipeline::316.636*2.80] mapped 6637889 sequences
[M::worker_pipeline::517.818*2.93] mapped 6637979 sequences
[M::worker_pipeline::718.307*2.99] mapped 6638390 sequences
[M::worker_pipeline::919.302*3.02] mapped 6638280 sequences
[M::worker_pipeline::1120.192*3.04] mapped 6638543 sequences
[M::worker_pipeline::1320.411*3.06] mapped 6637991 sequences
corrupted double-linked list
Aborted (core dumped)`

I thought maybe something went wrong with trimming so I went back to the original untrimmed SRR.fastq file and ran the command again and now get a different error. Can you help interpret what is happening here? 

`      
(base) bigboi@pop-os:/media/bigboi/Seagate Desktop Drive/Shao_Chipseq_Data_Analysis$ minimap2 -a Mus_musculus.GRCm39.dna.primary_assembly.fa PPARg_ChIP-seq/Input/SRR14667380.fastq.gz > SRR14667380_not_trimmed.sam
[M::mm_idx_gen::38.566*1.51] collected minimizers
[M::mm_idx_gen::48.838*1.82] sorted minimizers
[M::main::48.838*1.82] loaded/built the index for 61 target sequence(s)
[M::mm_mapopt_update::50.126*1.80] mid_occ = 598
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 61
[M::mm_idx_stat::50.880*1.79] distinct minimizers: 97791701 (39.85% are singletons); average occurrences: 5.142; average spacing: 5.426
[M::worker_pipeline::308.111*2.84] mapped 6578948 sequences
[M::worker_pipeline::509.443*2.96] mapped 6578948 sequences
[M::worker_pipeline::711.726*3.01] mapped 6578948 sequences
[M::worker_pipeline::927.327*3.04] mapped 6578948 sequences
[M::worker_pipeline::1173.038*3.06] mapped 6578948 sequences
[M::worker_pipeline::1384.087*3.07] mapped 6578948 sequences
[M::worker_pipeline::1533.348*3.08] mapped 6578948 sequences
[M::worker_pipeline::1733.565*3.09] mapped 6578948 sequences
[M::worker_pipeline::1932.141*3.10] mapped 6578948 sequences
[WARNING] wrong FASTA/FASTQ record. Continue anyway.
[M::worker_pipeline::2128.898*3.04] mapped 6578948 sequences
[M::worker_pipeline::2132.225*3.04] mapped 357655 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -a Mus_musculus.GRCm39.dna.primary_assembly.fa PPARg_ChIP-seq/Input/SRR14667380.fastq.gz
[M::main] Real time: 2132.968 sec; CPU: 6482.989 sec; Peak RSS: 17.890 GB
`

**Comment by lh3** [comment]
> `corrupted double-linked`

Minimap2 doesn't report such an error. It comes from other tools.

**Comment by jmarshall** [comment]
The “corrupted double-linked list” message comes from glibc's malloc/free implementation. So this likely indicates memory corruption within minimap2 for the data in this file.
