### ISSUE TITLE
Cannot generate vcf files from minimap2 produced alignment of two reference genomes using paftools

### ISSUE THREAD

**Issue by mw-toure** [lh3/minimap2#1015]
I'm trying to generate a vcf file that will contain all variants identified by the alignment of two reference genomes from two closely related species of mammal. The way I have been attempting to do this is 

```sh

# run minimap2 to align the two reference genomes
minimap2 -ax asm5 species1_reference.fasta species2_reference.fasta > alignments.paf
```

followed by 

```sh
paftools.js call -f species1_reference.fasta alignments.paf > output.vcf
```

however this only ever generates an empty vcf file. This workflow is what I believe I should be doing based on the documentation but perhaps I'm wrong? Is anything explicitly wrong with the workflow I've outlined above?

**Comment by lh3** [comment]
See the Usage line of paftools.js call:
```
Usage: sort -k6,6 -k8,8n <with-cs.paf> | paftools.js call [options] -
```

**Comment by lh3** [comment]
Also see cookbook and the README in misc
