### ISSUE TITLE
Insertion versus supplementary

### ISSUE THREAD

**Issue by nh13** [lh3/minimap2#1018]
I am trying to understand when `minimap2` prefers to call an insertion in an alignment versus having supplementary alignments.  

I have a reference with two contigs:
1. `wildtype` is a long sequence (ignore that it's repetitive, it's that way since it was easier to generate)
2. `insertion` is a sequence not matching (1)

I then have a query that is the `insertion` contig above inserted in the middle of the `wildtype` contig above.

I align the query to the reference/target as follows:

```console
$ minimap2 -d ref.mmi ref.fa
$ minimap2 -Y -x map-ont -a ref.mmi query.fa  > output.sam
```

I see a single alignment with cigar `256M35I256M`, which shows the insertion.  But I was hoping since the 35I matches the `insertion` contig exactly that I would get a split-read alignment (primary with two supplementary alignments):
1. `wildtype:1:256M291S`
2. `insertion:1:256S35M256S`
3. `wildtype:257:291S256M`

I also see this if there is an accompanying deletion of the wildtype sequence right before the insertion (e.g. additional 50bp deletion of wildtype).

Is it the case that the `256M35I256M` alignment score is so much larger than any one of the three putative split-read alignments, the latter are never reported? 
Thank-you for you help in advance!

Below are the inputs:

<details>

<summary>ref.fa</summary>

```
>wildtype
TACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACG
ATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGC
>insertion
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
```

</details>

<details>

<summary>query.fa</summary>

```
>wildtype_with_insertion
TACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGC
```

</details>

<details>

<summary>output.sam</summary>

```
@SQ	SN:wildtype	LN:512
@SQ	SN:insertion	LN:35
@PG	ID:minimap2	PN:minimap2	VN:2.24-r1122	CL:minimap2 -Y -x map-ont -a ref.mmi query.fa
wildtype_with_insertion	0	wildtype	1	60	256M35I256M	*	0	0	TACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGCATGC	*	NM:i:35	ms:i:1010	AS:i:965	nn:i:0	tp:A:P	cm:i:242	s1:i:504	s2:i:254	de:f:0.0019	rl:i:0
```

</details>

**Comment by lh3** [comment]
Minimap2 prefers one contiguous alignment. You only see a supplementary alignment when minimap2 can't find one contiguous alignment due to 1) the insertion is too long or 2) sequences around the insertion is too short. You may see a secondary alignment if you reduce `-p`. Nonetheless, a 35bp hit may be too short for nanopore reads to report unless you change other parameters.
