### ISSUE TITLE
Different alignments returned with cigar string is requested

### ISSUE THREAD

**Issue by biorover** [lh3/minimap2#102]
Hello, I was playing around with some test data to see the different output options for minimap2 and I found something a bit off. Essentially, I get different alignment starts and stops when I run the program with the cigar string requested (option -c) compared to when I do not.

So for the same input data,
"tools/minimap/minimap2-2.7_x64-linux/minimap2 -x map-pb ref.fa query.fa"
gets me:
tempread        1797    83      1599    +       dummySeq1       3372    1006    2380    465     1516    58 etc.

while
"tools/minimap/minimap2-2.7_x64-linux/minimap2 -x map-pb -c ref.fa query.fa"
gets me:
tempread        1797    18      1607    +       dummySeq1       3372    947     2388    1384    1620    55 etc.

Asking for a sam-format alignment (-a) gives the same alignment as the alignment with cigar string (-c).

Why is there a different alignment when different output fields are requested? Is one more accurate than another?

ref sequence:
>dummySeq1
AACCGAGATGGCGGACCGAAAACTTCGAGAAGTAAAAGTCAAGAAGTTGGTTAACGCCGATAATTTTCCAATGTGAAAGAAGACGTTATCGGTATTATTAAGAGCGTAGGAACTCATGAACATTGTAGAAGGTAAGGAACAGAAGCCAGCAGAGGCCAACGAGATGAAGAAATGATAAAACGCGATAGTCAGGTTATGTTGAAAATCATTTACTCGGTTGATTCATTGCTGTTAAAATGATTGTTTAATTGCAGTACAGCAACAGAATATTGGTCTGAAATCATGGGTATGTTTGAGAAGAAGTGGAATGCGTAAGGTATAGTTACAGCACGAATTATTGAACTGTAAGCTTGAGAGTGGTCAGAATGTACTTGACTACATCACTGATGTCTCAAATATCAGGACCTCCTTTGAAACAGTAGGAGTGAAATTTGAGGATGACTTCATTATTGCGAAGATCGTGAACGGGCTCCCTGCGAGAAAGTCAGTACCTTCATTACTGTCTGGAATAGCAAGAAACCGACGAAGCAGATGATCGAGAATCTGGCTAATGAACTAGCTGGACACGAAGAAGTTCTGAACAAGGCCGATAATGAACTTGAGGTATTAGTCGTCAAGTCGCGCAAAGATATAAGTAAAGGCAATGACAAGAAGAAGTCCAACAAGAAGATCAAAGCAGAACGAAGAGAGTTTTCGAGCAAGTGTTATAACTGTGGCATGGAAGATCACATAATGCATGACTGCACAGAGCCGAAGAAGAACAAGAAAAGTCAGAATAAGAATATGAAGAACATGAAACTGAAACGAAGTTGGATTATGGTTTCATAGCTGAAGCATTCATGATTAACTCGGTTGAAAGTTCATGGCTTGGAGATAGTGGTACCAATTGTCACATGACATACGACAGGAGTTGTTTTGAGATGTTCGAAGAGGTTTTCAACCATCCAGGAATCGGCACAGCAAATAAAGTGGCAGTTCTAATGAAATGGCGAGGAACAGTTCGCGTCTTTTGCAAGCGGCCGATAGTGGAATGGTAAGCTGTATGAGGTAATGTACGTACCTGACTTGCACAAGAACTTGTTCTCGCTGACGAAATGTGCAGAGGCTGACTGTAAAATAATATGGAGAAACTTAAGGTTTTAATCAAGAAGCTAAATGAACAAGTGATCATGACTGGCGTGATTGATAATGGACTGTGGTGAATGCTGATTGAGAAATGATTAGGCGCACGTCGTTGAAGAATCATCCTTTCGTGAGATTCATGAGAAGCTTGGTCATGTAAGTATTGACACAATCCGAAAGATGGTCAGAGAAAATAATACACTCAGCATGAATATTGGCGATGATATGAACTTCACATGCAAAGCTTGCAACTACGGCAAGCAAAAGCATTTGACGCACAAAACACAACCACCAAAGAATATTCAATCTGACAAATTTATTCACTCAGATCTGTGTAGACCGTTCGAAAAACTCGGCTTGAATGGGGAAAAATATTTTGTGCTATTCAAAGATGATGCGATGGGAGTCATGACGAAGAGAGTGGCAACGAATCATCTGTCAACGGATCATCATTAGAAAATCAACATGTCAGATATCGAAGAAACCTAAGATCAGCATCTTCAAAATCCAATTCTCCTGCACGAAATTTCGCAAACCATTTCTGGCACAATTGTTGGCTAACAACATCACTTTTCCATACACGATGTATATCTTTTGATTTGTTTTTCTTGAATTTTTTACCTTTACGGTAGTAAAATAAGCTTTATACACCGAAAAATATATATTATTTTCTTCTACTTTGAAACTGCTGTTAAAACACTTTACCCGATTGCAGTTACTTTACTCAAAGAATATGTCACCTTTTTGAGCGACAGATTGTACTGAATACTTGACAGAAACTTGTACTGAAACTTAACGCATATTCGGTTGAAGTGAACGACACCTTTTTGGAAATCCTCACGAACTTTCTAGTCATCCTTCGATTTACAGATGTTACATACAACGATCTTTTTATCTACACATTATATACTTGCTAAGATATGATATACGTATTAAATATGCAAACACAATTAACTTAAATGTTACTTAAAGAGACTATATCACAGAAAACTACGTGGACTATAAACTAACATCAAAAAATTCCCCTTTTAAAAATATCAAACTTTAACAATAGTTACGTAAAATTCTGTATTTAGAAAGAATATTCAATCTATGCGGTTTTTTTGTCATTATACAGTCACATCGAGTTATATTCGAATTATAGAAAAAATAAGCATCTGCTAATTTTAGATATTAGTGGTCCATTGTTCCGTTGTAAACCTCTTTCTCGAGTCTTTTGAAAGGTACATTGACAGGTGTATTCATTCTTAGCTTGTGAGCGTAAATTGAAAGAATAATATGATACATGCTTTTTTATATCACTAAATATTTTTCGACAATGATGTATTTACGTACATAAAATATTAAAATAAAATATAACAGTTTCAATAAAAAGATTAAAAGAACAAGCTAAGTATTACGTATTACGGATTATTTGAATCTGTGTTTTACAAAATAATATCAGAAATTTACATCAAATGAAAAAGTACCAAATATGAAAATGCTGTTAGGCAAACTAATATGTTAATCGGTACAAGTAACTAATTTTGCTGGTTAAATAATTCTTTAATTTTTTGTTTTCTTTTCCTATTTTCTCTCTTCCTCTCTCTATCCTATCCCCGTCCTTCCTCTCTCTCTATCTCTCTCTTTTCCTCTCCCTCTCTCTCTCGCTATCTTGTATTACTTTTGTATTACTGTATGAGACATTTGAGAGTAATAGCAACAAGTCTTTTGCCAAGTCCACTAAACACCTTTTAATTTGGCGTAAAGTTTTGACATCAACTTTTTTATGGGAAAATAGATTTAAATAACCAGCATCGGGTGTACTTGACGATTTTTGTACCTTTTTTGAAATTATTTTTTAGAAGTACCTTGATTAGTCACTGATGTGTACAGTTAATGAAATGAATCGAATCGTTGTAATGTTGGCTTATTGGTATCGATATGTTCCTTACCGACCAATATACTAAATAAGTTTTTTATTATATGTTGGTATTTAAATATTGAATGATATTATAAATGAAAATATACCTAAACATAACAGATTCTGAACGTACATGCATAGGGCATTATCGATACAGCATGTTGACAACATTAACAATCTGTATTTTGTATATTGCTCCGTAATTGTATGTGTGTGTGAACTATCAACACGAATAAACTGACATTACTATTATTATTACCATAATGTCGGTAATATTAATATACATTTCATCTCACTGTACAATGACATTTTTTCTTAATGAATTTGTGCATTTACATTGAACAGTA

query sequence:
>tempread
CGCAGTGGACCTACAGTTGGAATCGCACAGCAAAGTGAAAGTGGCAGTTTCTAATGAATTTGGCGAGATGAACAGTAACGCGTCTTTTGCAAGCGGCCGATAGTGGAATGGTAAGCGTATGAGGTAATGTACGTACCTGACTTTGCACAGAAACTTGTTCATCGCTGACGTTAAAGGTGTGCATTGTATTAGTTTCTGAACTGTAAAATAATTATGGAGAAACTTAAGTTTTAATTCAAGACAGCAAAATGAACAGTGATCATGACTGGGCGTGAAATTGATAATTGGATTCTGTGAGTGGAATGCTGAGGTTATGGAGAAATGATTAGGGCGCACGTCGTTGAAGAATCATCCTTTCGTGAAGATTCATGAGAAGCTTGGTCATGTAAGTATATTATGACATCATATTCTGAGGAAGATGGATACAGTTAGAATTTTATAGTATACCTAATGCGCATGAATATTTTGCGGACTGATAATGAATTCATTCATGCAAAGCATTGGCAACTTACGGCAAGCAAAAGCATATTGAACGCAATACAAAAACAAACCACCTAAAGAATATTCAATCTGACAAATTTATTCCTCAGAATCGCGGTATCGAAAAACTCGGCTTCAGAATGGGGAAAAATATTTTGTGCCTATTCATTACCAGATGATGCGATGTGGAGTCAATGACGGGTTTAAGGAGAGTGGCAAACGAACTACATCTGTCAAACGGAATCATCATTAGAAAATCAAACATGTCGATATCGCAAGATAATACCGTAAGATCAGCATCTTCAAATCCCAAGTTCTCCTGCCAACGAAATTTCGCAAACAACATTTCCTTGGCAACAATTGTTTTGCGGTAACAACATTATCACTTAAATACACCGATGTATAGTCTTTTGATTTGTTTTTTTGAATTTTTACCTTTACGGTAGTAAAATAAGCTTTATAACACCCGAAAAATGAGGAGGTATTAGTTTTATTCTACTTTGAAACTGCTGTTAATATCAACACTTTACCCCGATTGCAGTTACTTGTTAAATCAAAGAAATATTGTCAACCTTTTTTGGAGCGACAGATTGTACTGAATACTTTGACAGAAATTGTACTGAAACTTAACGCATATTCGGTTTGAAGTGAACGACACCTTTTTTTGAAAATCACTCACGAACTTTCTAGTCATCACTTCGATTTACAGATGTATTACATACAAGCTTTTATCTAACACATTATATATCTTGCTAAGATATGAATATGACGTATGTAAAATTGGCAACAACAAATTAACGTTAATGTTGACTTAAAGGAGACTATATCACAGAAACTACGTGGCACTATAAACTAACATCAAAAAATTCCCCTTATTAAAAATAATCCAAACTTTAAACAATAGTTACGTAAACTCTGTATTATAGAAAGAATATTAATCTATGCGGTTTTTTTGTCATTATAGCAGTCACATCAGAGTTATATTCGAATTATAGAAAAAATAAGCATTCTGCTAATTTTTAGATATTAGTGGTCGCATTGTTCGCCGTTGTAAACCTTTTCTCGAGTCTTTTGAAAGGTAACATTTTGCCCACAGTGTATTCATTCTTAGCTTGTGAAGCGTAAATGGGTGGGAAAGAAATGAGATAGGTGATACAGGTGAATTGATTTATAAGGGTAATTTACGGGACATAAATATCCTATTTTACCGGACAATCGATGTAGGTTGAGGAAATGACGGACTACAGGGTAAAATGATTAAATAAAATAATAACAGAATTTCAAAATAAAGGGAGAAGAGTTAAAGGAAGAACATAG

**Comment by biorover** [comment]
By the way, the query is a real PacBio read and the reference is the bit of the genome it aligned too plus ~2kbp on either side.

**Comment by lh3** [comment]
`-a` or `-c` is much more than one more field. When doing alignment, minimap2 often extends chains, and may split chains and identify new optimal chains.
