### ISSUE TITLE
Directly query kmer locations from minimap index

### ISSUE THREAD

**Issue by Adamtaranto** [lh3/minimap2#1020]
Hi Heng and co.,

This is more of a feature request. I'd like to be able to query an existing mm index for all genomic locations of a given kmer. I guess that this is happening when minimap looks for alignment seeds. I've been experimenting with writing my own indexing methods but  am nowhere near beating minimap for speed and efficiency.

Would it be possible to get a stand alone module to retrieve kmer locations from a mm index?

**Comment by lh3** [comment]
Are you using C or Python? If in C, you can read index.c about how minimap2 read k-mers. If in Python, sorry, no plan to support that.
