### ISSUE TITLE
Misrecognization of introns

### ISSUE THREAD

**Issue by sunriseTM** [lh3/minimap2#1023]
Something wrong happened when minimap was used to align full length transcripts generated from Pacbio to genome, introns were taken as deletions, just as below:
![image](https://user-images.githubusercontent.com/70903661/221563710-9953bcc3-a8ae-4fb9-ac60-80c5b4ec5fcf.png)

**Comment by lh3** [comment]
Minimap2 is not good at small introns unfortunately.

**Comment by sunriseTM** [comment]
**Complementary comment:**
May be because of its mathcing mothods, minimap2 will also make mistakes on the GT-AG splicing signal of small introns, and that makes it take some introns as deletions just as below:
![image](https://user-images.githubusercontent.com/70903661/222060960-6d9524f3-67e3-4aa6-98da-51667a84a092.png)

**Comment by lh3** [comment]
This is aligned as a deletion, not as an intron. GT-AG is not considered for deletions.

By the way, you could try to apply `-O2,22` to reduce intron penalty. It may introduce errors elsewhere.
