### ISSUE TITLE
minimap2 doesn't detect or fail if output destination runs out of space

### ISSUE THREAD

**Issue by unode** [lh3/minimap2#103]
Using version 2.7-r654 and running with:

`minimap2 -t 8 -ax sr index input.fq > /location/output.sam`

even if the destination runs out of space and the output is truncated, minimap2 continues to run happily.

**Comment by lh3** [comment]
I am not sure it is possible to check disk full when writing to a pipe.

**Comment by unode** [comment]
Shouldn't at least exit with a failure?

**Comment by lh3** [comment]
I don't think it is technically achievable.

**Comment by unode** [comment]
I find this surprising. Every other software I use will fail in one way or another when a disk is full or bytes cannot be flushed to destination.

Maybe I was not clear in explaining the problem and you understood something else.
The problem is that the output of minimap fills the disk but this doesn't result in a failure.
When using minimap in a pipeline, the only way to know if minimap succeeded is to check if the output isn't corrupted which is very unreliable.

As for technically achievable, even plain `cat` does it:
```
# cat /dev/zero > file ; rm -f file
cat: write error: No space left on device
```

**Comment by lh3** [comment]
I was wrong then. But I don't know how cat achieves that. I might come back to this later.

Generally though, not having enough space is a user error. You can't expect minimap2 to protect against all user errors. Minimap2 only strives to give correct output when there are no user errors.

**Comment by lh3** [comment]
I was wrong. Sorry. "Disk full" can be checked by evaluating the return code. 623b5d9 should fix this.
