### ISSUE TITLE
Segmentation Fault using -a option

### ISSUE THREAD

**Issue by eprdz** [lh3/minimap2#1031]
I am trying to map PacBio reads using Minimap2-2.24. Having in mind that I do not want to use any preset, I am using the -d option to first do a index:
```
minimap2 -d /tmp/index.mmi /data/input/GRCh38_no_alt_analysis_set_GCA_000001405.15.fasta.gz -k 15 -w 10 -t 3
```
Then, I do the mapping with the index and the -a option to make a SAM:
```
minimap2 -a -f 0.0002 -U 10,1000000 --q-occ-frac 0.01 -e 500 -g 10000 -r 500,200000 -n 3 -m 40 -P --secondary=yes -M 0.5 -p 0.8 -N 10 --splice -G 200000 -C 5 --splice-flank=yes --frag=no -A 2 -B 4 -O 4 -E 5 --end-bonus 0 --score-N 1 -t 4 /data/input/index.mmi /data/input/read2.fastq.gz -o /data/output/read2.sam
```

Then, the segmentation fault appears:
```
[M::main::0.199*1.01] loaded/built the index for 100000 target sequence(s)
[M::mm_mapopt_update::0.256*1.00] mid_occ = 271
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 100000
[M::mm_idx_stat::0.295*1.00] distinct minimizers: 4335240 (86.04% are singletons); average occurrences: 2.150; average spacing: 9.593; total length: 89412705
Segmentation fault (core dumped)
```
Do you know what should I do?
Thanks in advance.

**Comment by eprdz** [comment]
I have revised other issues, and I think that it has to do with the fact that --idx-no-seq is automatically set in the index step. Is it possible to avoid the usage of --idx-no-seq? I do not mind using more memory,

**Comment by lh3** [comment]
--idx-no-seq is not applied by default
