### ISSUE TITLE
failed to parse the first FASTA/FASTQ record

### ISSUE THREAD

**Issue by lunky-zao** [lh3/minimap2#1035]
[WARNING]ESC[1;31m failed to parse the FASTA/FASTQ record next to '8c8881e1-880a-4030-a270-c497b1f68c2d'. Continue anyway.ESC[0m
[M::worker_pipeline::1517.333*18.59] mapped 54690 sequences
[WARNING]ESC[1;31m failed to parse the first FASTA/FASTQ record. Continue anyway.ESC[0m
[M::worker_pipeline::1797.153*17.43] mapped 48449 sequences
[WARNING]ESC[1;31m failed to parse the first FASTA/FASTQ record. Continue anyway.ESC[0m
[M::main] Version: 2.24-r1122
[M::main] CMD: minimap2 -a -t 48 -x map-ont -o Z.fasta ONT-7_clean.fq.gz
[M::main] Real time: 1798.159 sec; CPU: 31329.798 sec; Peak RSS: 36.367 GB

**Comment by lh3** [comment]
FASTQ is malformatted.
