### ISSUE TITLE
Erroneously formed paf file

### ISSUE THREAD

**Issue by sanyalab** [lh3/minimap2#1039]
Hi,

I performed a genome to genome alignment using minimap2 using the following command

`minimap2 -cx asm10 --cs -t 14 <Target.fa> <Reference.fa> > Target_Reference.paf`

The PAF file has some entries like below

`Gm20    47846026        15177793        15178270        +       Chr20   51086977        17701974        17702450        461     485     60      NM:i:24 ms:i:353    AS:i:332        nn:i:0  tp:A:P  cm:i:23 s1:i:234        s2:i:417927     de:f:0.0191     zd:i:3  rl:i:6244572    cg:Z:79M9I1M8D388M    cs:Z::31*tc:4*ct:42+ccccgcccc:1-atggtcat:70*tc:61*ct:113*tc:69*tc:5*ag:6[M::worker_pipeline::1520.420*3.60] mapped 9 sequences`

This is causing issues with downstream processing as the error returned is `Incorrect Alignment Format`

Is there a way to check and correct if the PAF file was formed correctly?
Is `[M::worker_pipeline::1520.420*3.60] mapped 9 sequences` part of stderr? Then maybe I can send that to a separate file.
Is the `--cs` flag necessary for genome to genome alignment?

Thanks
Abhijit

**Comment by lh3** [comment]
You need to separate stdout and stderr.

**Comment by sanyalab** [comment]
Yes!! That's what I did. It worked.

Thank you sir
