### ISSUE TITLE
Suboptimal (incorrect) alignment

### ISSUE THREAD

**Issue by sjackman** [lh3/minimap2#104]
Hi, Heng. I'm aligning a sequence composed of 4,306 nucleotides, a thousand Ns, and 792 nucleotides to GRCh38. The expected alignment is near perfect, one mismatch and a 1-bp insertion in the first chunk, and no mismatches in the second chunk. The second chunk instead aligns somewhere else in the genome with 10 mismatches and a mapping quality of 60. When I increase the gap from 1,000 Ns to 10,000 Ns, I see the expected alignment with a mapping quality of 58, as well as a second alignment with 10 mismatches and a mapping quality of 0.

Incorrect alignment (1k Ns)
```
❯❯❯ minimap2 -c GRCh38.fa abyss2.n1k.10690428.fa
10690428	6098	0	4306	-	CM000664.2	242193529	97142461	97146766	4305	4306	28	NM:i:1	ms:i:8604	AS:i:8604	nn:i:0	tp:A:P	cm:i:945	s1:i:5003	s2:i:716	dv:f:0.0001	cg:Z:3812M1I493M
10690428	6098	5306	6098	+	CM000664.2	242193529	95962726	95963518	782	792	60	NM:i:10	ms:i:1524	AS:i:1524	nn:i:0	tp:A:P	cm:i:114	s1:i:716	s2:i:0	dv:f:0.0183	cg:Z:792M
```

Correct alignment (10k Ns)
```
❯❯❯ minimap2 -c GRCh38.fa abyss2.n10k.10690428.fa
10690428	15098	0	4306	-	CM000664.2	242193529	97142461	97146766	4305	4306	60	NM:i:1	ms:i:8604	AS:i:8604	nn:i:0	tp:A:P	cm:i:797	s1:i:4218	s2:i:2582	dv:f:0.0001	cg:Z:3812M1I493M
10690428	15098	14306	15098	-	CM000664.2	242193529	97141668	97142460	792	792	58	NM:i:0	ms:i:1584	AS:i:1584	nn:i:0	tp:A:P	cm:i:148	s1:i:785	s2:i:716	dv:f:0.0009	cg:Z:792M
10690428	15098	14306	15098	+	CM000664.2	242193529	95962726	95963518	782	792	0	NM:i:10	ms:i:1524	AS:i:1524	nn:i:0	tp:A:S	cm:i:114	s1:i:716	dv:f:0.0183	cg:Z:792M
```

Here's a gist of the sequence that does not align correctly:
https://gist.githubusercontent.com/sjackman/1eb5ab217e6836163853cc64179e158c/raw/cc80cd7bff02197d611ffb684d450c79a83a7618/abyss2.n1k.10690428.fa

https://gist.github.com/sjackman/1eb5ab217e6836163853cc64179e158c

```
minimap2 --version
2.8-r672
```
I see the same behaviour with `2.3-r531` and `2.7-r654`. The reference genome is the 24 chromosomes of GRCh38.

**Comment by sjackman** [comment]
Unrelated issue: should the score `4305 4306` be instead `4304 4306`? The query has 4306 nucleotides, and there's one mismatch `NM:i:1` and one insertion `cg:Z:3812M1I493M`. That seems to me like the `Number of residue matches` is 4304.

**Comment by sjackman** [comment]
More unexpected results with this same query sequence.

- `-c -r50` aligns right through the gap of 1000 Ns
- `-c -r500` reports the suboptimal alignment of the short chunk of query
- `-c -r5000` does not report any alignments for the short chunk of query
- `-c -r50 --no-long-join` and `-c -r500 --no-long-join` correctly report all three alignment blocks (the two correct, and one suboptimal)
- `-c -r5000 --no-long-join` does not report any alignments for the short chunk of query

```
❯❯❯ minimap2 -c -r 50 GRCh38.fa.mmi eg/abyss2.n1k.10690428.fa
10690428	6098	0	6098	-	CM000664.2	242193529	97141668	97146766	5097	5098	60	NM:i:1001	ms:i:8604	AS:i:9164	nn:i:1000	tp:A:P	cm:i:504	s1:i:4939	s2:i:64dv:f:0.0005	cg:Z:792M999I3813M1I493M
❯❯❯ minimap2 -c -r 500 GRCh38.fa.mmi eg/abyss2.n1k.10690428.fa
10690428	6098	0	4306	-	CM000664.2	242193529	97142461	97146766	4305	4306	53	NM:i:1	ms:i:8604	AS:i:8604	nn:i:0	tp:A:P	cm:i:504	s1:i:4939	s2:i:647	dv:f:0.0005	cg:Z:3812M1I493M
10690428	6098	5306	6098	+	CM000664.2	242193529	95962726	95963518	782	792	60	NM:i:10	ms:i:1524	AS:i:1524	nn:i:0	tp:A:P	cm:i:53	s1:i:647	s2:i:0	dv:f:0.0203	cg:Z:792M
❯❯❯ minimap2 -c -r 5000 GRCh38.fa.mmi eg/abyss2.n1k.10690428.fa
10690428	6098	0	4306	-	CM000664.2	242193529	97142461	97146766	4305	4306	60	NM:i:1	ms:i:8604	AS:i:8604	nn:i:0	tp:A:P	cm:i:504	s1:i:4746	s2:i:2671	dv:f:0.0005	cg:Z:3812M1I493M
❯❯❯ minimap2 -c -r 50 --no-long-join GRCh38.fa.mmi eg/abyss2.n1k.10690428.fa
10690428	6098	0	4306	-	CM000664.2	242193529	97142461	97146766	4305	4306	60	NM:i:1	ms:i:8604	AS:i:8604	nn:i:0	tp:A:P	cm:i:428	s1:i:4165	s2:i:1859	dv:f:0.0006	cg:Z:3812M1I493M
10690428	6098	5306	6098	-	CM000664.2	242193529	97141668	97142460	792	792	60	NM:i:0	ms:i:1584	AS:i:1584	nn:i:0	tp:A:P	cm:i:76	s1:i:774	s2:i:647	dv:f:0.0014	cg:Z:792M
❯❯❯ minimap2 -c -r 500 --no-long-join GRCh38.fa.mmi eg/abyss2.n1k.10690428.fa
10690428	6098	0	4306	-	CM000664.2	242193529	97142461	97146766	4305	4306	60	NM:i:1	ms:i:8604	AS:i:8604	nn:i:0	tp:A:P	cm:i:428	s1:i:4165	s2:i:1859	dv:f:0.0006	cg:Z:3812M1I493M
10690428	6098	5306	6098	-	CM000664.2	242193529	97141668	97142460	792	792	60	NM:i:0	ms:i:1584	AS:i:1584	nn:i:0	tp:A:P	cm:i:76	s1:i:774	s2:i:647	dv:f:0.0014	cg:Z:792M
10690428	6098	5306	6098	+	CM000664.2	242193529	95962726	95963518	782	792	0	NM:i:10	ms:i:1524	AS:i:1524	nn:i:0	tp:A:S	cm:i:53	s1:i:647	dv:f:0.0203	cg:Z:792M
❯❯❯ minimap2 -c -r 5000 --no-long-join GRCh38.fa.mmi eg/abyss2.n1k.10690428.fa
10690428	6098	0	4306	-	CM000664.2	242193529	97142461	97146766	4305	4306	60	NM:i:1	ms:i:8604	AS:i:8604	nn:i:0	tp:A:P	cm:i:504	s1:i:4746	s2:i:2671	dv:f:0.0005	cg:Z:3812M1I493M
```

**Comment by lh3** [comment]
It is an oversight. 35d3e06 should much alleviate this issue.

**Comment by lh3** [comment]
Thanks a lot for this example.

**Comment by sjackman** [comment]
No worries, Heng. Thanks for the quick fix!
