### ISSUE TITLE
de:f, dv:f and rl:i tags

### ISSUE THREAD

**Issue by tijyojwad** [lh3/minimap2#1040]
Hello Heng,

I had a question about the `de:f`, `dv:f` and `rl:i` tags that are output by minimap2. I wasn't able to find documentation for what those represented. Could you help me understand that, or point to any help/FAQs?

Thank you!

**Comment by lh3** [comment]
See manpage

**Comment by lh3** [comment]
https://lh3.github.io/minimap2/minimap2.html#10

**Comment by tijyojwad** [comment]
Thank you!!
