### ISSUE TITLE
Large deletion (>1kb) identification issue

### ISSUE THREAD

**Issue by sarahszaffich** [lh3/minimap2#1049]
Hi, when pulling CIGAR strings from (ONT) bam files and analyzing those, some deletions (larger than 1kb) are not identified with the CIGAR string approach, whereas cuteSV identifies those accurately. Is minimap2 saving large deletions differently than smaller ones? If yes, is there a way to save deletions of all sizes in the CIGAR string?

The expected deletion size is up to 2kb. Thanks!

**Comment by lh3** [comment]
minimap2 requires long enough flanking regions to bracket a long indels. Without this requirement, there will be more false positives. If the deletion is close to the edge of a read, it may not be aligned. I believe this is well known to SV developers. Modern SV callers can call long indels from split alignment.

**Comment by cherryamme** [comment]
minimap2 requires long enough flanking regions to bracket a long indels. Without this requirement, there will be more false positives. If the deletion is close to the edge of a read, it may not be aligned. I believe this is well known to SV developers. Modern SV callers can call long indels from split alignment.
——————
@lh3 hey Heng, My reads are from  PCR ampify, If the deletion is close to the edge of a read ( which is close to primer ),how can i align these reads with short clip to correct position ( close to primer).  i noticed -x splice mode can correctly place these reads but  call out  intron.
