### ISSUE TITLE
Clipping penalty [feature request]

### ISSUE THREAD

**Issue by sjackman** [lh3/minimap2#105]
Could the clipping penalty similar to `bwa mem -L` be applied at the ends of sequences, and possibly also at the ends of scaffolds gaps (a run of nucleotides before a gap of `N`s)?

**Comment by lh3** [comment]
Have you tried the `--end-bonus` option (see [here](https://lh3.github.io/minimap2/minimap2.html#6))?

**Comment by sjackman** [comment]
No, I hadn't seen that. Thanks, Heng! Would you suggest `-x asm10 --end-bonus=5` to mimic the behaviour of `bwa mem -x intractg`?

**Comment by lh3** [comment]
> Would you suggest minimap2 -x asm10 --end-bonus=5 to achieve similar behaviour as bwa mem -x intractg?

should be close.
