### ISSUE TITLE
Mapping direct RNA seq nanopore sequenced reads to DNA

### ISSUE THREAD

**Issue by kaltinel** [lh3/minimap2#1055]
Hi,

I kindly would like to ask a question: I would like to map my direct RNA-seq reads (generated by nanopore sequencing) to genome (DNA). I am somewhat confused if minimap2 supports this, as normal way would be to map cDNA reads to genome, or mapping direct RNA to RNA.

If minimap2 supports this type of direct RNA (without cDNA) to DNA mapping, can you suggest optimal parameters for it?

Thank you very much,
Best,

**Comment by lh3** [comment]
Yes. See the first section in README.

**Comment by keenhl** [comment]
From the readme:

"There are different long-read RNA-seq technologies, including tranditional full-length cDNA, EST, PacBio Iso-seq, Nanopore 2D cDNA-seq and Direct RNA-seq. They produce data of varying quality and properties. By default, -x splice assumes the read orientation relative to the transcript strand is unknown. It tries two rounds of alignment to infer the orientation and write the strand to the ts SAM/PAF tag if possible. For Iso-seq, Direct RNA-seq and tranditional full-length cDNAs, it would be desired to apply -u f to force minimap2 to consider the forward transcript strand only. This speeds up alignment with slight improvement to accuracy. For noisy Nanopore Direct RNA-seq reads, it is recommended to use a smaller k-mer size for increased sensitivity to the first or the last exons."
