### ISSUE TITLE
Not a single of my reads is aligned 

### ISSUE THREAD

**Issue by matjack2000** [lh3/minimap2#1066]
Hi, 
I'm trying to use minimap2 in order to map miR (very short sequences (20-30n)). We added poly(A) tails to the sequences so that they could be detected by the nanopore device. As a reference, I use a fasta file that I obtained on the miRBase website. However, when I try to align my data and the reference, I get no results. I used R functions to directly match some of the sequences with the reference and It found some match, some are even identical (the miR sequence can be exactly found in the sequence). 
I was wondering why. 
Thanks in advance for your answer.

**Comment by lh3** [comment]
You can tune minimap2 for short query sequences with smaller `-k`, `-s`, `-m` and `-n`. Nonetheless, I would recommend bwa-aln or bowtie1 for this purpose.
