### ISSUE TITLE
Remove noisy reads in --splice:hq 

### ISSUE THREAD

**Issue by Radek91** [lh3/minimap2#1071]
Hi! 

I performed some single-cell RNA-seq (10x genomics) and sequenced the reads with nanopore (R10.4 flowcells). To assess the pipeline demultiplexing accuracy I mixed some human and hamster cells. My goal is to analyse the percentage of reads mapping to human vs hamster genes in each cell.
However, I am having some troubles with minimap2 when it comes to aligning these reads on different species:

![Screenshot 2023-06-05 at 15 23 37](https://github.com/lh3/minimap2/assets/129386883/a3fb679a-f25a-4583-92fb-4d143e25bc51)

Both cells depicted here are mapped to the hamster genome. Top panel is a hamster cells. Bottom panel is a human cell. The issue is that minimap2 is too good at mapping noisy reads and aligns confidently the human reads to the hamster genome. 

Command:

`BED="/hamster_v109/Cricetulus_griseus_chok1gshd.CHOK1GS_HDv1.109.bed"
REF="/hamster_v109/Cricetulus_griseus_chok1gshd.CHOK1GS_HDv1.dna.toplevel.fa"
`

`minimap2 -ax splice:hq -uf -t 12 --junc-bed $BED $REF $file | samtools view -F 260 -b | samtools sort -@ 12 -o "$file"_sorted.hamster.bam`

I would like to get rid of the noisy reads and to eliminate as much human reads mapping to the hamster genome as possible. To do so I already explored:

- splice vs splice:hq ==> no difference
- Variable -B values (1 to 6) associated with varying -A values (1 to 4). After -B > 6 I start loosing reads most/all reads both with hamster and human cells.

1) What can I do to fine-tune the pipeline ? 

2) I would have expected that splice:hq would remove more as it is optimised for PacBio reads. Is this behaviour expected ?  

version tested: 2.26-r1175 &  2.24-r1155-dirty

**Comment by lh3** [comment]
I would recommend to set a filter on the `de:f` tag.
