### ISSUE TITLE
Best Practices for v2.26 with --secondary flag being depricated

### ISSUE THREAD

**Issue by Michal-Babins** [lh3/minimap2#1072]
Description:
When running minimap2 with v2.26, we replaced “--secondary=no -N1” with “-N0". During runtime, we are seeing this warning level logging

```
`[WARNING] ‘-N 0’ reduces mapping accuracy. Please use ‘--secondary=no’ instead.
[WARNING] changed ‘-N 0’ to ‘-N 20 --secondary=no’.`
```

Expected:
We expect `--secondary=no` to be replaced in favor of another option. 

Question:
Using version 2.26, what should be the proper solution for replacing `--secondary=no` to achieve expected behavior.

**Comment by lh3** [comment]
Never ever use `-N0`. Just use `--secondary=no`.

**Comment by lh3** [comment]
`--secondary` is not deprecated
