### ISSUE TITLE
 How call Genotype with "0/0" rather than "./."?

### ISSUE THREAD

**Issue by maruiqi0710** [lh3/minimap2#1074]
Using the following command for asm-to-asm alignment and generate a VCF file, most loci are "./." rather than "0/0". How can we align and call them "0/0" rather than "./."?

minimap2 -c --cs -t 5 \
	{mmi_path} \
	{Fasta_input_dir}/{File} \
	| sort -k6,6 -k8,8n \
	| k8 {paftools_path} call -f {ref_path} -L 1000 -s {Sample} - > {out_dir}/{Sample}.vcf

**Comment by lh3** [comment]
`./.` means genotype uncertain. It should not be changed to '0/0'.
