### ISSUE TITLE
paftools.js /usr/bin/env: 'k8': No such file or directory

### ISSUE THREAD

**Issue by GianlucaMattei** [lh3/minimap2#1077]
Hello, 
I am trying to run paftools to get annotation file for the junctions to use in RNAseq but I get this error:

```
paftools.js:1664: Error: No transcript_id
                if (id == null) throw Error("No transcript_id");
                        ^
Error: No transcript_id
    at Error (<anonymous>)
    at paf_gff2bed (/home/gmattei/.conda/pkgs/minimap2-2.24-h7132678_1/bin/paftools.js:1664:25)
    at main (/home/gmattei/.conda/pkgs/minimap2-2.24-h7132678_1/bin/paftools.js:3126:29)
    at /home/gmattei/.conda/pkgs/minimap2-2.24-h7132678_1/bin/paftools.js:3148:1
```
I downloaded the hg19 gff3 from ensembl
 
Is it a bug or I missed something ?

**Comment by lh3** [comment]
try GTF

**Comment by madzafv** [comment]
Hi I'm trying to use the following recipe from the cookbook

```
minimap2 -c --cs ref.fa query.fa > query.paf
sort -k6,6 -k8,8n query.paf | paftools.js call -f ref.fa -L10000 -l1000 - > out.vcf
```
but when running 

`sort -k6,6 -k8,8n query.paf | paftools.js call -f ref.fa -L10000 -l1000 - > out.vcf`

I run into
`/usr/bin/env: ‘k8’: No such file or directory`

What could be wrong here?
Let me know if you need more info.
Thank you

**Comment by madzafv** [comment]
My bad. There was an issue pointing to my k8 in PATH. I fixed. Thank you

**Comment by KaushikPanda1** [comment]
Hello, can you please let me know where do I find k8? I can't find this binary anywhere - not with Minimap2, or independently.
