### ISSUE TITLE
MiniMap2 and splice site detection

### ISSUE THREAD

**Issue by dandepledge** [lh3/minimap2#108]
Hi Heng,

I'm not clear how minimap2 is functioning in terms of identifying splice sites. Given that the sequence reads may contain base miscall and/or indel type errors, it seems likely that splice acceptor and donor recognition may be compromised in some positions? 

I then started wondering whether minimap2 looks at the reference genome/transcriptome or the sequence read itself to determine whether a splice donor/acceptor is utilised in a given situation (and indeed whether it favours a canonical or non-canonical donor/acceptor sequence)?

**Comment by lh3** [comment]
If there are no errors or ambiguity, naive alignment directly gives you splice junctions. In more complex cases, minimap2 as well as most other RNA-seq mappers prefers canonical signals. See the minimap2 preprint for details.
