### ISSUE TITLE
CIGAR doesnt have letter "X" to indicate mismatches

### ISSUE THREAD

**Issue by kaltinel** [lh3/minimap2#1080]
Hi,

I hope you are well. I am kindly writing to you regarding the CIGAR strings. I have direct RNA seq (nanopore) data where I can see mismatches on IGV, however their CIGARs string only have `M,D,I` and `S` as letters which should indicate `match, deletion, insertion and clipping`, however no `X `to indicate `mismatches`.
I tried to find out whether I am missing knowledge but seems like `mismatches` should be indicated with `X`.
In this case, do you know why I don't have them in the CIGAR but in IGV? Or, do I parse CIGAR wrong?

Thanks for your help!

**Comment by lh3** [comment]
You may add option `--eqx`.
