### ISSUE TITLE
Advice, getting small and divergent hits

### ISSUE THREAD

**Issue by vpymerel** [lh3/minimap2#1087]
Hello, 

Thank you again for the great tool,

Do you have an advice to get small (100-200bp) and quite divergent (~20%) secondary alignments, when mapping one assembly to another ?

Here is the command line I am using so far (and that work well for hits long enough):

```bash
minimap2 --cs \
        -cx asm20 \
        -t {threads} \
        -P \
        {input.assembly} \
        {input.cut_assembly}
```

Thank you,
V

**Comment by lh3** [comment]
That will be challenging with minimap2. The default (without `-x asm20`) may work better.
