### ISSUE TITLE
Params for nanopore dRNAseq reference transcriptome

### ISSUE THREAD

**Issue by kenneditodd** [lh3/minimap2#1091]
Hello,

I see in issue #788 you mentioned a reference genome should be used for `ref.fa` in the dRNAseq parameters.
`minimap2 -ax splice -uf -k14 ref.fa direct-rna.fq > aln.sam  # Nanopore Direct RNA-seq`

How would these parameters change if I want to align to a reference transcriptome?

Additionally, is the `-uf` param the `-u` flag with f as the argument? Or the the `-u` and `-f` (for float) flag?

**Comment by lh3** [comment]
Just use `-x map-ont`, not `-x splice`.
