### ISSUE TITLE
Why does CIGAR ''I'' sequence  > 500bp include N ambiguous base?

### ISSUE THREAD

**Issue by LichengXX** [lh3/minimap2#1093]
I used parameter -x asm5 to align  an tomato genome to the reference genome SL4.0. The output is a sam file. And I used the python script to extract insertion sequence(> 500bp) according to the "I" CIGAR character. And used IGV to verify my results(shown as follow figure).
![insertion_500_list](https://github.com/lh3/minimap2/assets/113669137/e38e2770-4395-402f-a68b-e307b027fa9a)
![igv](https://github.com/lh3/minimap2/assets/113669137/6ecd8c7f-315e-4ddc-ab3a-6ee72ccb8a9a)

But when I used blastn to align the insertion sequence to the nt database , it occurred an error:
Warning: [blastn] Query_3020 NRDK01035080.1.. : Could not calculate ungapped Karlin-Altschul parameters due to an invalid query sequence or its translation. Please verify the query sequence(s) and/or filtering options

Then I used samtools to extract this query from the query genome.I found that all the bases in this query are N(shown as follow).
![samtools_out](https://github.com/lh3/minimap2/assets/113669137/9cbb8b30-590b-4740-a8a8-195468eba979)

There are 16 sequences in the blastn log that report the same error(shown as follow), and all of them show up as N in IGV except for the one I listed above, which shows up as a normal sequence in IGV.
![blastn_log_error](https://github.com/lh3/minimap2/assets/113669137/5d59dfdf-4861-4046-8716-90719a58d994)

For example,
 I checked the query "NRDK01036496.1:6311-6952" in the blastn log error.
The sequence extracted by the python script is consistent with igv, and the sequence of that insertion interval in igv is all "N"(shown as follow).
![NRDK01036496 1_insertion_out](https://github.com/lh3/minimap2/assets/113669137/227d9b19-ee24-4ae2-9dc1-7cb3b1be7187)
![igv_out](https://github.com/lh3/minimap2/assets/113669137/48018d28-0cf7-4cae-a7c2-25b43c964617)
The samtools faidx's result is the same as igv(the command line: samtools faidx LA0480.fasta NRDK01036496.1:6311-6952 > 2.fa, shown as follow).
![samtools](https://github.com/lh3/minimap2/assets/113669137/375bd4f9-b677-4c26-9bba-9612818b60ff)

I don't know why the minimap2 comparison includes N (which in theory should be ignored).
Can you help how to deal with this problem?
I would be grateful for any help you can provide.

**Comment by lh3** [comment]
this is expected
