### ISSUE TITLE
BAM format as output

### ISSUE THREAD

**Issue by nicolo-tellini** [lh3/minimap2#1095]
Hello @lh3 ,

I have a really naive question. 
Is there a reason because minimap2, with the short read mapping, returns a SAM file instead of a BAM file?
Is it  possible to directly generate a BAM file as output?

best,

nicolò

**Comment by hasindu2008** [comment]
you can pipe the output through samtools sort, something like:
minimap2 ... | samtools sort - -o a.bam

**Comment by nicolo-tellini** [comment]
Hi @hasindu2008 ,

yeah it is possible to convert it. 

My point is a bit different, why do I need to pipe samtools and convert from a SAM to BAM when can be directly generated a BAM (if it is the case) ?
