### ISSUE TITLE
Error with SAM TO BAM

### ISSUE THREAD

**Issue by kiranpatil222** [lh3/minimap2#1097]
Hi,

I have generated SAM file using below command, data i downloaded from GIAB
`singularity exec minimap2_v2.17.sif minimap2 -ax map-ont -t 40 -L /data/shared/clinical/LongRead/Data/resources/Homo_sapiens_assembly38.mmi HG002_ONT-UL_GIAB_20200122.fastq > HG002_ONT-UL_GIAB_20200122.sam`

when i am trying convert SAM to BAM for ONT Variant analysis i am getting below error
`[E::hts_hopen] Failed to open file HG002_ONT-UL_GIAB_20200122.sam
  [E::hts_open_format] Failed to open file "HG002_ONT-UL_GIAB_20200122.sam" : Exec format error
  samtools view: failed to open "HG002_ONT-UL_GIAB_20200122.sam" for reading: Exec format error`

**Comment by jmarshall** [comment]
Your output file has not been recognised as valid SAM format because singularity has logged some output that has been captured by your `>` redirection.

Use `minimap2 … -o HG002_ONT-UL_GIAB_20200122.sam …` instead of redirecting its output.

**Comment by kiranpatil222** [comment]
Thanks a lot it did work

**Comment by lh3** [comment]
Thank you, @jmarshall!
