### ISSUE TITLE
Provide Error if reference missing

### ISSUE THREAD

**Issue by ebioman** [lh3/minimap2#11]
Hi
Just a quick suggestion as I doubted seriously my sanity today generating constantly empty SAM or PAF files.
If reads are provided but no reference (or the 2nd pairs of reads to map onto) provide a warning or error message.  
To me it looked as it succeeded 

    minimap2 -x ava-pb subreads.fasta -t 10 -a > overlaps.sam

    [M::mm_idx_gen::133.043*1.66] collected minimizers
    [M::mm_idx_gen::142.990*2.23] sorted minimizers
    [M::main::142.990*2.23] loaded/built the index for 292447 target sequence(s)
    [M::mm_idx_stat] kmer size: 19; skip: 5; is_HPC: 1; #seq: 292447
    [M::mm_idx_stat::145.867*2.20] distinct minimizers: 196522811 (45.73% are singletons); average occurrences: 3.898; average spacing: 4.220
    [M::main] Version: 2.0rc1-r232

But then the files were obviously empty 
It may help people who dont know what to expect ;)
Cheers

**Comment by lh3** [comment]
That is fair. I will address the issue at some point. Thanks.

**Comment by lh3** [comment]
Fixed via 9e1125e

**Comment by lh3** [comment]
This fix is not part v2.0, but will appear in future releases.
