### ISSUE TITLE
PacBio Read Mapping Segmentation Fault

### ISSUE THREAD

**Issue by pjedge** [lh3/minimap2#110]
I'm experiencing a segmentation fault trying to align PacBio reads to hg19 (from UCSC).
I reduced the fastq file to a small example (test.fastq) with just 2 reads and I still get the error.

```
./minimap2 -ax map-pb hg19.fa test.fastq > test.sam
```
[test.fastq.zip](https://github.com/lh3/minimap2/files/1718446/test.fastq.zip)

I get the same result if I used gzipped fastq input.

**Comment by lh3** [comment]
I can't reproduce the problem. What minimap2 version are you using? If you are using the latest, could you upload "hg19.fa"?

**Comment by pjedge** [comment]
Hmmm. The issue persisted with both source-built and downloaded binary. But, the same command worked perfectly fine on a different cluster node. I'm not sure yet what's the cause but I think it's a machine specific issue. I'll close the issue unless I uncover something new.

**Comment by lh3** [comment]
A correct program should not segfault depending on the machine it runs on. Could you download [this following binary](https://github.com/lh3/minimap2/releases/download/v2.6/minimap2-2.6_x64-linux.tar.bz2), and try `minimap2-2.6_x64-linux/minimap2-asan`? This binary is slower but it does extra check, which might help to identify hidden bugs. Or if you are familiar with C/C++ programming – could you run the command-line within gdb or valgrind? Thanks.

**Comment by pjedge** [comment]
Yeah I can run it through valgrind

**Comment by lh3** [comment]
Thanks a lot! Forgot to say: when you run valgrind, it is sometimes useful to add `--no-kalloc` like
```sh
valgrind ./minimap2 -ax map-pb --no-kalloc hg19.fa test.fq
```
The memory allocator minimap2 uses by default may hide some memory errors.
