### ISSUE TITLE
Install  error:cannot find -lz: No such file or directory

### ISSUE THREAD

**Issue by isunshine-cc** [lh3/minimap2#1100]
/miniconda3/bin/../lib/gcc/x86_64-conda-linux-gnu/11.2.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find -lz: No such file or directory  Can you tell me how to deal it?

**Comment by lh3** [comment]
Install zlib

**Comment by isunshine-cc** [comment]
Thank you!

**Comment by isunshine-cc** [comment]
conda install -c anaconda zlib  
 I use this command to install zlib, however when I run "cd minimap2 && make", it still error lib/gcc/x86_64-conda-linux-gnu/11.2.0/../../../../x86_64-conda-linux-gnu/bin/ld: cannot find -lz: No such file or directory. And I try to install zlib.tar.gz, at the same time I set the environment (export PATH =$PATH:$HOME/Softwares/library/Zlib/zlib-1.2.11/) , and then I run the command "cd minimap2 && make",  It still error ld: cannot find -lz: No such file or directory. So How can I to deal with it?
