### ISSUE TITLE
Secondary mappings reported

### ISSUE THREAD

**Issue by apredeus** [lh3/minimap2#1103]
Dear Heng, 

Thank you for writing this great tool - it really is amazing. 

I was wondering if you could comment on a problem I'm having. I'm trying to get `minimap2` (version 2.26-r1175) to report secondary alignments only when their alignment score is the same. From the manual it seems that it should be controlled with the `-p` option. However, when I run 

`minimap2 -t16 -Y -I 16G -ax sr -N 10000 --secondary=yes -p 1.0 <ref> <fastq>`

I clearly obtain some sub-optimal mappings. For example, for one read, the distributions of mapping scores is as follows:

```
      2 AS:i:164
      4 AS:i:166
      3 AS:i:168
      1 AS:i:170
      8 AS:i:174
    282 AS:i:180
```

How can I make sure the output would only contain the 282 reads that have the best alignment score? 

Thank you very much in advance!

**Comment by lh3** [comment]
Secondary alignments are filtered based on the chaining score, not the SW score. In addition, I wouldn't recommend `-p1.0` as this will lower alignment accuracy. You have to filter output alignments with a postprocessing step.
