### ISSUE TITLE
A question about map-ont

### ISSUE THREAD

**Issue by Leo152** [lh3/minimap2#1109]
I found that a sequence (378-530) of a read in the PAF file did not match the reference genome, but when I extracted this unmatched sequence and used minimap2, it matched the reference genome with high alignment quality. What could be the reason for this?

The command you ran using minimap2 v2.26 is as follows:
`minimap2 -cx map-ont --secondary=no -t 32 GRCh38.p12.genome.fa sample.fastq -o mapping.paf
`

![微信图片_20230828102704](https://github.com/lh3/minimap2/assets/93251349/a8be538a-d87c-4bed-9d2c-ba3dabcb6cea)
![微信图片_20230828102847](https://github.com/lh3/minimap2/assets/93251349/9489af53-ae32-4fc3-8220-94e3dec6367f)

My data consists of sequences amplified by rolling circle amplification. I believe the matched region represents a complete unit. I extracted all the matched units on the genome, as well as the unmatched 378-530 region, and performed alignment using Mega. The results showed high similarity.

![微信图片_20230828095938](https://github.com/lh3/minimap2/assets/93251349/03b93ac7-2788-45b3-a739-619d23079289)

**Comment by lh3** [comment]
6.58% at the de tag is quite high for a 150bp sequence. It is worse than other parts and more likely to fail the minimap2 algorithm. Generally, don't expect minimap2 to align everything. Even if you can tune parameters to fix this case, you will other failing examples.

**Comment by Leo152** [comment]
I have another question. This segment (378-530) is indeed worse than other units, but why can it match the reference genome when extracted from the sequence, while it cannot match the reference genome in the complete sequence?

**Comment by lh3** [comment]
Poor matches interfere with other parts.
