### ISSUE TITLE
Compare 2 wheat genome.

### ISSUE THREAD

**Issue by mfruzan** [lh3/minimap2#1114]
I mapped 3Gbp human genome using minimap2 successfully and using 32 CPUs very quickly. Now i want to compare 2 wheat genome that are around 14Gbp, Minimap2 runs very slowly and seems not using whole 32 CPUs and only uses 1 CPU. I used below command:
 
minimap2  -f100 -x asm5 --cs=long -t 32 --secondary=no   iwgsc_refseqv2.1_assembly.fa    arinalr_sm.fa | paftools.js view -f maf - >cs_arina.maf;

what could be the reason that Minimap2 does not use all 32 CPUs?

Thanks,
Mario

**Comment by lh3** [comment]
Add `-K4g`

**Comment by mfruzan** [comment]
I used -K4g and now it uses 6 CPUs, after sometime it generated 7gbyte of maf file (up to chromosome 2). 

minimap2 -f100 -K4g -x asm5 --cs=long -t 32 --secondary=no  iwgsc_refseqv2.1_assembly.fa  arinalr_sm.fa | paftools.js view -f maf - >cs_arina.maf;

Is there any other way to speed up, such as increasing k-mer size or changing -f, or even align each chromosome of query genome one by one?

Thanks ,
Mario
