### ISSUE TITLE
How to free memory successfully after using mm_gen_cs

### ISSUE THREAD

**Issue by mleysens** [lh3/minimap2#1117]
Heng
  I am wrapping core mm API calls in a custom C program. I call mm_gen_cs to get at the PAF string and then process the string within the code. I rely heavily on the PAF string. But after I call mm_gen_cs and trying to free the memory allocated I am clearly seeing a memory leak. Also the API to this function is a bit confusing. It asks for a list of strings (char **buf), but in the code it treats the buf as kstring_t. 
  Since mm uses kalloc for its own memory management, I am having trouble knowing what level down within what gets returned into buf for how to properly free things up (i.e as a list of strings or as kstring_t). 

thanks for any insights

.maury

int mm_gen_cs(void *km, char **buf, int *max_len, const mm_idx_t *mi, const mm_reg1_t *r, const char *seq, int no_iden)

**Comment by mleysens** [comment]
by the way, here is how I am trying to use it:
// early in main, I call
            mm_dbg_flag |= MM_DBG_NO_KALLOC;
...
            kstring_t *pstr;
            mm_gen_cs(km, (char **) &pstr, &max_len, mi, r, ks->seq.s, 0);  // this generates the paf string
            printf("%s", pstr->s);
            free(pstr->s);

**Comment by lh3** [comment]
Should be
```c
char *buf = 0;
int max_buf_len = 0;
mm_gen_cs(0, &buf, &max_buf_len, ...);
free(buf);
```
This API is similar to [GNU getline](https://man7.org/linux/man-pages/man3/getline.3.html).

**Comment by mleysens** [comment]
the readline ref helps. testing now. 

thanks

: )

**Comment by lh3** [comment]
If you don't want to use kalloc, always pass `NULL` for `km`. `kfree(0, ptr)` is the same as `free(ptr)`.
