### ISSUE TITLE
Support for zero gap extension penalty?

### ISSUE THREAD

**Issue by ymcki** [lh3/minimap2#1119]
I am trying to align ultra long ONT reads to CHM13v2 to diagnose FSHD cases.

To do that, I need to align reads to the highly repetitive macro satellite D4Z4 which has 33 consecutive copies of 3.3kb repeat in chr4 of CHM13v2. Typically, diseased people has 1-10 copies and normal people has 11-150 copies. 

I found that with default -ax map-ont, there are quite many reads that can only align to only one side of the repeat instead creating huge gap/insertion such that it can align to both ends of the D4Z4 repeat.

I believe this might be due to the heavy penalty incurred in opening huge gaps/insertions. So I tried -E 0 but it told me it must be positive. Then I tried "-A 200 -B 400 -O 400 -E 1" but then it complains O1+E1+O2+E2 must be <= 127. So the best I can do is "-A 50 -B 100 -O 100 -E 1", The alignments I got are better than default but perhaps it can be even better if I can set gap extension penalty to zero?

Is it possible for future to allow zero gap extension penalty? If not, what is the best way to deal with a situation like mine? Thanks a lot in advance.

**Comment by lh3** [comment]
For the time being, you may try the splice mode without recognizing splicing signals `-cx splice -un`. Not sure if it works.
