### ISSUE TITLE
paftools.js pbsim2fq outputs NaN coordinates

### ISSUE THREAD

**Issue by pesho-ivanov** [lh3/minimap2#1121]
I am trying to annotate .fa reads with reference coordinates for evaluation purposes. I succeed to do this using  `mason_simulator` + `mason2fq` or using 'pbsim2' + 'pbsim2fq'. Nevertheless, using `pbsim` v1 ([link](https://github.com/pfaucon/PBSIM-PacBio-Simulator)) and `pbsim2fq` (minimap2-2.26_x64-linux/paftools.js) produced fasta comments with broken coordinates (`>S1_1!chr1!NaN!NaN!+`). Seems like pbsim2fq works only for pbsim2. 

```
ref=chm13.genome.fa  # downloaded from https://www.ncbi.nlm.nih.gov/datasets/genome/GCF_009914755.1/
samtools faidx $ref                                            # generated .fai looks good: >chr1    248387328   57  80  81 ...

pbsim \
        $ref \
        --model_qc  ../example/model_qc_clr \
        --accuracy-mean 0.99\
        --accuracy-sd 0\
        --depth 0.1\
        --prefix reads\
        --length-mean 24000                                    # generated .maf starts with: a\n s chr1 CP068277.2 Homo sapiens isolate CHM13 chromosome 1 108244074 21403 + 248387328
paftools.js pbsim2fq $ref.fai reads_*.maf > reads_pbsim.fa     # broken: >S1_1!chr1!NaN!NaN!+

pbsim2 \
         --accuracy-mean 0.99\
         --depth 0.1\
         --prefix reads2\
         --length-mean 24000\
         --hmm_model data/R95.model
         $ref                                                  # .maf starts differently: a\n s ref 222585329 35741 + 248387328 -GTTATTTTG---AAAT [...and keeps going with the alignment]
paftools.js pbsim2fq $ref.fai reads2_*.maf > reads_pbsim2.fa   

mason_simulator -ir $ref -n 100 -o reads_tmp.fa -oa mason.sam
paftools.js mason2fq mason.sam > reads_mason.fa                #  looks good: @1!chr15!92837446!92837546!- 1:0:0
```

**Comment by pesho-ivanov** [comment]
I just checked `chm13.genome.fa` and it correctly has ">chr1", ">chr2", etc.

Sorry for the inaccuracy when reporting the issue: I forgot the ">" character. Added it now.

So, the issue persists.

**Comment by rchikhi** [comment]
then where does "chr1 CP068277.2 Homo sapiens isolate CHM13 chromosome 1" in your maf file come from?

**Comment by pesho-ivanov** [comment]
I see now. Thank you, Rayan. It worked.

**Comment by pesho-ivanov** [comment]
Thank you, Rayan. Stripping the name to "chr1" and removing the additional information worked.
