### ISSUE TITLE
Parameters for the search of inter-chromosome translocations

### ISSUE THREAD

**Issue by weishwu** [lh3/minimap2#1126]
I ran minimap2 with the `map-ont` preset to align the reads against a reference with mouse genome and a transgene contig (~5kb in one data and ~200kb in the other). The purpose is to find out the reads that were mapped to both a mouse chromosome and the transgene contig in order to locate the insertion position. However, many of these cross-chromosome multimapped reads were missed by minimap2. They could be better captured by Blast. It seems minimap2 likes to drop the unmapped ends in the reads as hard/soft clipping instead of trying to figure out where they could be mapped. Should I use the `splice` preset for this purpose? Is there any other parameter I should tune? Thanks.

**Comment by lh3** [comment]
> It seems minimap2 likes to drop the unmapped ends in the reads as hard/soft clipping instead of trying to figure out where they could be mapped.

You should look at other alignment, not just the primary alignment.

**Comment by weishwu** [comment]
I did look at all alignments.
