### ISSUE TITLE
Alignment marked as supplementary rather than secondary due to strand

### ISSUE THREAD

**Issue by martin-cusack** [lh3/minimap2#1128]
According to my understanding of the paper and the manual: a chain is marked as secondary if it overlaps with a better chain by 50% or more of the shorter chain [-M 0.5 default]; otherwise it will be primary.

Does this overlap take into account the strand to which the query aligns to?

For example I have here two alignments from the same read (marked as supplementary's of each other):

0695eddd-24b6-4dc2-a7b9-96e119769035	2048	p625	3620	60	329H4M1I10M2D5M1D33M1D27M1D10M3I29M1I17M1D7M2I1M4D36M1I40M1D1M1D69M1I19M1I14M1D6M1D1M1D12M	*	0	0	GTGATCCGGCGGCGGTCACTTCGGCATGGACGAGCTGTACAAGTAGTGAGGATCCCACAAAGTGACCTAGAGCTGGCAGCAAATAAAATATCTTCTTTATTTTCATTACATCTGTGTGCTGGTTTTTTTGTGTGGGCTTCGGGGCCCGGCAAGAGTAACATAACTGCTGGAGTAGATGAAGATGGAGGGGCGCCCTTGCTGGCTCTTCTAGGAACCCCTAGTGATGGGTGGCCACTCCCTCTCTGCGCGCTCGCTCGCTCACTGAGGCCGGGCGACCAAAGGTCGCCCGACGCCCGGAGCTTTGCCCGGGCAGCCTCGAGTGAGCGAACGTGGCGCAGGGGGGGTGGCCAA	/238765-2301214,667;<?=<;;=>??=)((((>>+***///+,/04947<;7;;<>AE=?>?A?>=;::;@??>000084.--4:<<;//--.6677947****,28@=0-1-/(''*/6=5;5.,+(%%&%%$'/)(&'%&,,$###%(''&(((*(&&&'152,,,+/10011'&*,,,*)''%&'*'$#$&&((--,('((&%&&(*++-56/99==73,**('++,/02802<:Bd:<9dH;@?@?@@00./45990.-++,8789<==55),...9:;:978653/,,'&&&668959;;5;-,,,58'''+1//''+&&%%%%%&'%$'+((,,)())*-.	NM:i:40	ms:i:477	AS:i:470	nn:i:0	tp:A:P	cm:i:29	s1:i:190	s2:i:59	de:f:0.0919	SA:Z:p625,3620,-,332S347M9D1S,60,40;	rl:i:0

0695eddd-24b6-4dc2-a7b9-96e119769035	16	p625	3620	60	332S12M1D75M1D60M1I84M4D4M1I8M5D1M3D26M4D14M4I4M4I4M2D2M1I42M1S	*	0	0	TTGGCCACCCCCCCTGCGCCACGTTCGCTCACTCGAGGCTGCCCGGGCAAAGCTCCGGGCGTCGGGCGACCTTTGGTCGCCCGGCCTCAGTGAGCGAGCGAGCGCGCAGAGAGGGAGTGGCCACCCATCACTAGGGGTTCCTAGAAGAGCCAGCAAGGGCGCCCCTCCATCTTCATCTACTCCAGCAGTTATGTTACTCTTGCCGGGCCCCGAAGCCCACACAAAAAAACCAGCACACAGATGTAATGAAAATAAAGAAGATATTTTATTTGCTGCCAGCTCTAGGTCACTTTGTGGGATCCTCACTACTTGTACAGCTCGTCCATGCCGAAGTGACCGCCGCCGGATCACTCTCGGCATGGACGAGCTGTACAAGTAGTGAGGATCCCCACAAAGTGACCTAGAGCTGGCAGCAAAATAAATATCTTTATTTTCATTACATCTGTGTGTTGGTTTTTTGTGTGAACTTCAGGAACCCCTTTTTAAGAGTAACATAACTGCTGGAGTAGATGAAGATGGAGGGCCACTTTACTGGCTCTTCTAGGAACCCCTAGTGATGGAGTTACTCACCCCTCAGTTCGCTCACTGAGGCCGCCCGGGCAAAGCCCGGCAGCCGGGCGACCTTTGGTCGCCCGCTGGCCTCAGTGAGCGAGCGAGCGCGCAGAGAGGGAGTGGCCAAA	.-*))(),,((+'$%'&%%%%%&&+''//1+'''85,,,-;5;;959866&&&',,/356879:;:9...,)55==<9878,++-.09954/.00@@?@?@;Hd9<:dB:<20820/,++'(**,37==99/65-++*(&&%&(('(,--((&&$#$'*'&%'')*,,,*&'11001/+,,,251'&&&(*(((&''(%###$,,&%'&()/'$%%&%%(+,.5;5=6/*''(/-1-0=@82,****7497766.--//;<<:4--.480000>??@;::;=>?A?>?=EA><;;7;<74940/,+///***+>>(((()=??>=;;<=?<;766,4121032-567832/.---.)***:=?>??;;>?@ABB>=::99:895342+*+237=>><:::<?;;:9;<=;869854211*(((::A?BBEGF===?><<44558dd@=>;;;<>;<<Cdd??>>?;=8:0./511341,/A@@C@?@=???>?>>>=?A<<<;<;:;<=>>A?>?>;=<=;98876532213?99===><><<;988=84488;;<<9=:9-,+'')((*+)%%$$%%%&(05////8.4444854565/../.**&$%&&'%%&)012=<=9665673/---''((4457:::;:?<=AA@>>>=+++*BCdd;>:1.:888=:<<BB8	NM:i:40	ms:i:529	AS:i:508	nn:i:0	tp:A:P	cm:i:42	s1:i:239	s2:i:95	de:f:0.0603	SA:Z:p625,3620,+,329S351M5D,60,40;	rl:i:0

The same section of the query (from ~330 onwards) aligns to the same region of the reference (from 3620 onwards) but on different strands. I suspect this happens due to an inverted tandem repeat. I do not understand why these are both primary alignments.

Is there anyway to set minimap2 to recognise one of the alignments as secondary rather than supplementary?

**Comment by lh3** [comment]
Supplementary/secondary is determined by the overlap on the query sequence, not by the overlap on the reference sequence.
