### ISSUE TITLE
A 2kb sequence cannot be snp_calling with paftools call

### ISSUE THREAD

**Issue by yuxizhang01** [lh3/minimap2#1130]
I randomly generated a 2 kb  base sequence, and then artificially generated a sequence containing INDEL and two sequences containing SNPs , and after double sequence alignment by minimap2, I obtained the result as shown in the attachment result.paf.
After that, use "**sort -k6,6 -k8,8n result.paf| paftools.js call -f 2kb -l 1 -L 1 -q 1 -**", the output result is no SNP and INDEL.
I'd like to ask if paftools itself can't do short sequences snp_calling or if I'm having a problem with my operation
THANKS!!!
[data.zip](https://github.com/lh3/minimap2/files/13554012/data.zip)

**Comment by lh3** [comment]
Paftools.js only calls a variant if the reference position is covered by one query sequence. In your example, the reference is covered by three sequences.

**Comment by lh3** [comment]
You can see output if you only take the first sequence.
