### ISSUE TITLE
impact of limiting abundant minimizers?

### ISSUE THREAD

**Issue by jvolkening** [lh3/minimap2#1131]
Hello, 

We are using the minimap2/miniasm/medaka workflow for de novo assembly of nanopore data. These are metagenomic RNA field samples where the final library fragments are short, typically with median length < 1000 bp. On these samples, I have found m/m/m to perform more reliably on our typical datasets even than the latest nanopore assemblers we have tested, at least in terms of recall.

The composition of the samples run in this pipeline vary widely and cannot be predicted in advance. After host removal, some are composed of many low-abundance taxa and some have one or two highly abundant taxa with very high coverage. I have found in the latter case that the all-vs-all mapping step with minimap2 takes a long time, a lot of memory, and often runs out of memory even on a 128 GB instance. The reported `mid_occ` for these samples can be in the 10s of thousands.

I saw in another thread the suggestion to use `-f 1000` to ignore highly abundant minimizers. Indeed, in initial testing this has a remarkable impact on the most troublesome samples, allowing the a-v-a mapping to finish in minutes. However, I'm wondering what impact this will have on the quality and correctness of the downstream assembly. I noticed that the output PAF is considerably smaller with this setting, presumably because fewer overlaps are found. I'm benchmarking right now on some older data to compare resulting assemblies. At the same time, I was just wondering from a theoretical point of view if you see major issues with using this setting in the context of the application. We'd be willing to accept a modest decrease in assembly quality if it meant a pipeline that was more robust to these types of samples.

Thanks for any feedback you might have time for.

**Comment by lh3** [comment]
I wouldn't use minimap2 for metagenome read overlapping. It is not the right tool. I would highly recommend metaflye for nanopore data.

**Comment by jvolkening** [comment]
Thank you for your reply. I've tested metaflye, including the latest version, relatively extensively and it does not perform well on our typical dataset, keeping in mind that these are not gDNA reads but RNA=>cDNA libraries from field samples often with median read lengths < 1000 nt and widely varying compositions. All other assemblers we have tested either have poor sensitivity (missing many RNA viruses completely) or have hard-coded presets and do not work with our data. Minimap2/miniasm with fine-tuned parameters is still the best overall option we have benchmarked, even in late 2023.

I will continue to test use of the `-f` parameter on our datasets -- so far it is working well for what we need.

**Comment by lh3** [comment]
For more recent nanopore data of higher accuracy, you can increase `-k` and/or `-w` to sample fewer minimizers. This may be more effective than reducing `-f`.

**Comment by jvolkening** [comment]
Many thanks, I will test with these parameters as well. Accuracy has gotten much better with the latest basecallers but most of the data we receive is still from 9.4.1 flowcells, so I am hesitant to increase `-k` too much.

**Comment by lh3** [comment]
More recent basecallers can get higher accuracy. Maybe worth re-basecalling?
