### ISSUE TITLE
Understanding and Fixing Errors in ONT Read Mapping with Minimap2

### ISSUE THREAD

**Issue by OZTaekOppa** [lh3/minimap2#1132]
Thank you for the excellent program. I have a few questions to better understand Minimap2.

In my recent experience with ONT read mapping of an organelle's reference genome, I observed significant counts of indels (~400), mismatches (~470), and NM (~1300) in the SAM file. How should I interpret and address these values?

**map-ont option:**
The documentation states that Minimap2 aligns noisy long reads with an approximate 10% error rate to a reference genome. How does the program handle indels and homopolymers? Specifically, is there an effective method, perhaps utilizing the SAM MD tag, to distinguish between genuine variants and technical errors in ONT reads?

**NM information:**
The documentation mentions that NM represents the total number of mismatches and gaps in the alignment. Does this count include indels, homopolymers, and variants, both genuine and technical errors?

**Increasing ONT Read Mapping Accuracy:**
Are there effective strategies to enhance ONT read mapping accuracy, particularly concerning indels, mismatches, and NM values in the SAM file?

Any insights or ideas on these questions would be highly appreciated.

**Comment by lh3** [comment]
An aligner doesn't know about variants or errors. It only does alignment.
