### ISSUE TITLE
strategy for soft clipping

### ISSUE THREAD

**Issue by kamimrcht** [lh3/minimap2#1133]
Hi Heng,

Could you describe your strategy for soft-clipping? Does it solely involve being under a certain score threshold? If that's the case, what is the threshold?

Many thanks!
Best.

**Comment by lh3** [comment]
In most cases, soft-clipping is produced by standard extension alignment whereby you choose the position that maximizes the smith-waterman score. There is not a threshold. Minimap2 implements additional heuristics including end bonus (see the bwa-mem paper) and Z-drop (see bwa-mem or minimap2) that may affect clipping.
