### ISSUE TITLE
Alignment differences between default run and run with CIGAR generation flag?

### ISSUE THREAD

**Issue by Gawain00** [lh3/minimap2#1134]
**Please see the issue described in full on the [Bioinformatics StackExchange question](https://bioinformatics.stackexchange.com/q/21946).**

Essentially, I am using Minimap2 (v2.26-r1175) to generate a sequence alignment between two chromosomes. When testing the inclusion and adjustment of different parameters, I noticed that including the CIGAR generation flag `-c` changed the coordinates of the alignments when comparing to a run where the flag is not included and even had five _less_ alignments than the default run (_i.e._, `minimap2 -k15 -w10` _vs._ `minimap2 -c -k15 -w10`).

Comparing the PAF files after sorting (`sort -k3,3 -k4,4`) using `vimdiff` revealed that the alignments computed between the default and CIGAR setting runs are largely _similar_, but not identical:

[![vimdiff_of_default_and_cigar_minimap2_output_files][1]][1]

I expected the alignments between these two sequences to be identical between these runs, but they aren't. Is there a simple explanation for the differences observed?

  [1]: https://i.stack.imgur.com/bGQze.png

**Comment by lh3** [comment]
See FAQ
