### ISSUE TITLE
BAM not binary file and missing header

### ISSUE THREAD

**Issue by dmjask** [lh3/minimap2#1136]
I'm attempting to map ONT reads to reference but have recently encountered the issue of bam not being binary as well as missing headers.
Both target and query are in fasta format.
I have used tried these commands:
minimap2 -a -x map-ont [REF] [QUERY] > [QUERY_bam]
minimap2 -x map-ont [REF] [QUERY] > [QUERY_bam]
minimap2 [REF] [QUERY] > [QUERY_bam]
The issue becomes evident when attempting to sort and index using samtools. I have previously successfully ran these commands without this issue.

Oddly enough I have not had the same issue for neither of these:
minimap2 -ax asm5 [REF] [QUERY] > [QUERY_bam]
minimap2 -x map-ont [REF] [QUERY] > [QUERY_paf]

I have attempted outputting an intermediate SAM, but the issue persists.
The version in use: 2.18-r1015, as a module on a SLURM HPC. To my knowledge there haven't been any updates which could have created the issue.

Thanks in advance for any suggestions and advice!

**Comment by lh3** [comment]
Minimap2 doesn't output bam.
