### ISSUE TITLE
Issue with Minimap2 Alignment to chr19:54768874-54778874 in hg38 Ref Genome

### ISSUE THREAD

**Issue by yueyaog** [lh3/minimap2#1138]
I am currently using Minimap2 to align sequences of intervals from the hg38 reference genome. In general, Minimap2 works well for most intervals I have tested. However, I have encountered an issue specifically with the interval `chr19:54768874-54778874`.

For some reason, Minimap2 is aligning this interval to multiple alternative contigs instead of the expected primary assembly `chr19:54768874-54778874`. 

To reproduce this error, you can use Minimap2 to align sequences from the interval `chr19:54768874-54778874` against the hg38 reference genome.

I have successfully aligned other intervals using Minimap2, and this issue seems to be specific to the mentioned interval. I suspect there might be a bug in Minimap2 causing this unexpected behavior. 

<img width="749" alt="Screenshot 2023-12-18 at 8 48 59 AM" src="https://github.com/lh3/minimap2/assets/46796757/b45d5f88-64e7-41bd-b6f3-b4e571651cee">

**Comment by lh3** [comment]
That is caused by multiple identical alignment, not an error.

**Comment by yueyaog** [comment]
I understand multiple identical alignments from alt contig. However, I don't understand why the primary assembly/ chr19:54768874-54778874 was not identified by minimap2.

**Comment by lh3** [comment]
Because there are too many identical alignments. Minimap2 only outputs 6 of them, randomly.

**Comment by yueyaog** [comment]
I see. Is there any way to let minimap2 output all of the alignments? Or I have to remove those alt contig from the fasta file in order to see the alignment from the primary assembly?

**Comment by lh3** [comment]
`-N`

**Comment by yueyaog** [comment]
Thx! I switched to primary-assembly fasta and this issue is gone now.
