### ISSUE TITLE
Discrepancy between single and multi part index results: is there a real final merge when using multi-part index with --split-prefix ?

### ISSUE THREAD

**Issue by cglambert** [lh3/minimap2#1139]
Dears,

I am using minimap2 with multi-part index and --split-prefix option. I tested different versions up to v2.26
When requesting, for example maximum 25 secondary hits, or a score difference of zero compared to maximum score, the final output file contains only 5 hits maximum (as the default) per read, not looking at the score difference.

Looking at intermediate output per index, the above behavior seems implemented correctly, the expected behavior is also observed when using single part index.

Is there any real merge performed after all indexes on the final intermediate results, considering options provided by the user ?
If not, can it be implemented/can this be corrected ?

Currently, there is indeed a difference between multi-part index and single part index outputs for the exact same reference sequence file and read files.

Thanks,
Christophe

**Comment by lh3** [comment]
> Is there any real merge performed after all indexes on the final intermediate results?

Yes, hits are properly merged. However, due to k-mer occurrences cut-offs and other threshold, you won't get identical output with --split-prefix anyway.
