### ISSUE TITLE
Alignment and using  output format sam

### ISSUE THREAD

**Issue by rehab-fouad** [lh3/minimap2#114]
Hi, 
I had a problem when repeating alignment in sam output. 
[rehab@iria N006-minimap]$ ~/minimap2/minimap2 -a human-refseq.fa N006_merge.fixed.fa > N006_sam_alignment.sam
[M::mm_idx_gen::27.333*1.62] collected minimizers
[M::mm_idx_gen::32.598*1.83] sorted minimizers
[M::main::32.697*1.82] loaded/built the index for 154045 target sequence(s)
[M::mm_mapopt_update::34.141*1.79] mid_occ = 133
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 154045
[M::mm_idx_stat::34.507*1.78] distinct minimizers: 17642700 (32.52% are singletons); average occurrences: 5.693; average spacing: 5.363
[M::worker_pipeline::65.967*2.30] mapped 36263 sequences
[M::main] Version: 2.8-r706-dirty
[M::main] CMD: /home/rehab/minimap2/minimap2 -a human-refseq.fa N006_merge.fixed.fa
[M::main] Real time: 66.684 sec; CPU: 152.470 sec
[rehab@iria N006-minimap]$

@SQ | SN:NM_000014.4 | LN:4678
-- | -- | --
@SQ | SN:NM_000015.2 | LN:1317
@SQ | SN:NM_000016.5 | LN:2623
@SQ | SN:NM_000017.3 | LN:1964
@SQ | SN:NM_000018.3 | LN:2296
@SQ | SN:NM_000019.3 | LN:2149
@SQ | SN:NM_000020.2 | LN:4263
@SQ | SN:NM_000021.3 | LN:6107
@SQ | SN:NM_000022.3 | LN:1574
@SQ | SN:NM_000023.3 | LN:1461
@SQ | SN:NM_000024.5 | LN:2058
@SQ | SN:NM_000025.2 | LN:2660

The SAM output file contains only three columns with no start or end point or munmber of matches and missmaches. Is this what expect?

**Comment by lh3** [comment]
Check the end of the sam file. You are looking at the header only.

**Comment by rehab-fouad** [comment]
Thank you, that is right.
There other two issues;
1- The alignment in bam and cigar in paf out but are empty files. 
2- the approximate alignment is paf output formate produces 17 columns instead of only 10. Do you have the meaning of other columns?

tp:A:P | cm:i:60 | s1:i:429 | s2:i:258 | cd mini
-- | -- | -- | -- | --
tp:A:P | cm:i:27 | s1:i:254 | s2:i:0 | dv:f:0.1111

**Comment by lh3** [comment]
You can find more info about PAF [here](https://lh3.github.io/minimap2/minimap2.html#10). Generally, it is recommended to use the SAM output, though.

**Comment by rehab-fouad** [comment]
what about the cause of the empty output file of cigar output command?

*************************************

*Rehab Fouad Abdelhamid, Ph.D.*

*モハメド レハブ*

*RIKEN, CLST*

*Biosystem Dynamics Group, Phyloinformatics Unit*

**Comment by lh3** [comment]
Sorry. I am not sure what you mean.

**Comment by rehab-fouad** [comment]
The command to produce cigar went fine without an error message but the output files that were generated are empty. 
I have tried both paf and bam output formate.

**Comment by lh3** [comment]
Use redirection:
```sh
minimap2 -axmap-pb ref.fa reads.fa > output.sam
```

**Comment by rehab-fouad** [comment]
Is this to generate cigar?

**Comment by rehab-fouad** [comment]
is this the header? it means only I am geting header in the genrated file.
@SQ | SN:XR_953175.2 | LN:1230 |   |  
-- | -- | -- | -- | --
@SQ | SN:XR_953178.2 | LN:950 |   |  
@SQ | SN:XR_953179.2 | LN:684 |   |  
@SQ | SN:XR_953180.2 | LN:559 |   |  
@SQ | SN:XR_953197.2 | LN:888 |   |  
@SQ | SN:XR_953198.2 | LN:840 |   |  
@SQ | SN:XR_953199.2 | LN:847 |   |  
@SQ | SN:XR_953201.2 | LN:391 |   |  
@SQ | SN:XR_953202.2 | LN:1572 |   |  
@SQ | SN:XR_953203.2 | LN:369 |   |  
@SQ | SN:XR_953204.2 | LN:610 |   |  
@SQ | SN:XR_953209.2 | LN:600 |   |  
@SQ | SN:XR_953222.2 | LN:2858 |   |  
@SQ | SN:XR_953225.2 | LN:2787 |   |

**Comment by lh3** [comment]
You are probably using a wrong file.

**Comment by rehab-fouad** [comment]
I used the same files that we used and worked before in the
approximate mapping.

**Comment by lh3** [comment]
I mean your file path is wrong. Show me the screenshot.

**Comment by rehab-fouad** [comment]
[image: Inline image 1]

*************************************

*Rehab Fouad Abdelhamid, Ph.D.*

*モハメド レハブ*

*RIKEN, CLST*

*Biosystem Dynamics Group, Phyloinformatics Unit*
