### ISSUE TITLE
Multi-part index and the use of mapping scores 

### ISSUE THREAD

**Issue by Pstege** [lh3/minimap2#1140]
Dear authors,

Thank you for this very nice tool and my apologies for asking a very similar question as discussed in topic # 301. 

My goal is to use nanopore data and align it to a database like NCBI refseq. I will thus use settings _minimap2 -x map-ont_. I will preferably report a coverage-like score, like col 10 matching bases of the of the PAF file. In addition, I would like to apply some sort of identity cut-off like col 12, the mapping score

Could you please check the statements below, to see if I understand these settings correctly?

-	Since I perform reference mapping, I should additionally apply _--split-prefix_

-	An alternative to _--split-prefix_ is using something like _-I64g_.
 
-	When using either _--split-prefix_ or _-I_, I am working with a multi-part index and therefore the output of the mapping score cannot be used. 

Are these statements correct? Or can I for instance run the alignment without applying _--split-prefix_ and _-I_ and still use the mapping score?

**Comment by lh3** [comment]
It is preferred to use a `-I` large enough to hold all your reference sequences in memory. In this case, minimap2 won't generate a multi-part index. Use `--split-prefix` only when you don't have enough memory.

**Comment by Pstege** [comment]
Thank you very much for the rapid reply! Two follow up questions;
(1) Does this mean that when I use `-I`, I can still use the mapping score? 
(2) And what determines the size that should be used to hold all reference sequences in memory? The size of the .mmi file or for instance the fasta file size.. ?
