### ISSUE TITLE
match problem using anno.bed12

### ISSUE THREAD

**Issue by Gracebio** [lh3/minimap2#1142]
Fristly, no bug here.  

Since I want to consider the junction, I use this command   `./minimap2 -ax splice --junc-bed anno.bed12 ref.fa query.fa > aln.sam`  
But I am not sure about the anno.bed12 file will be used, because id of anno.bed12 and id of ref.fa are not match.  

```  
# anno.bed  
hr1    11868   14409   ENST00000456328.2|lncRNA|DDX11L2        1000    +       11868   14409   196,196,196     3       359,109,1189,   0,744,1352,
chr1    12009   13670   ENST00000450305.2|transcribed_unprocessed_pseudogene|DDX11L1    1000    +       12009   13670   196,196,196     6       48,49,85,78,154,218,    0,169,603,965,1211,1443,
chr1    14403   29570   ENST00000488147.1|unprocessed_pseudogene|WASH7P 1000    -       14403   29570   196,196,196     11      98,34,152,159,198,136,137,147,99,154,37,        0,601,1392,2203,2454,2829,3202,3511,3864,10334,15130,
chr1    17368   17436   ENST00000619216.1|miRNA|MIR6859-1       1000    -       17368   17436   0,192,0 1       68,     0,  
  
# query.fa is sample.fasta
  
# gencode.v44.pc_transcripts.fa # yes, transcripts as reference, from gencode. **Every sequence is transcript, id format seems not exectly match anno.bed id** 
   >ENST00000641515.2|ENSG00000186092.7|OTTHUMG00000001094.4|OTTHUMT00000003223.4|OR4F5-201|OR4F5|2618|UTR5:1-60|CDS:61-1041|UTR3:1042-2618|  
CCCAGATCTCTTCAGTTTTTATGCCTCATTCTGTGAAAATTGCTGTAGTCTCTTCCAGTT
ATGAAGAAGGTAACTGCAGAGGCTATTTCCTGGAATGAATCAACGAGTGAAACGAATAAC
```  
In other words, the format of these three files is ok to get a required aln.sam which considered junction information? Thanks for your brillant minimap2 and your time!

**Comment by lh3** [comment]
The ID field (4th column) is ignored.

**Comment by Gracebio** [comment]
Thanks! Based on these, I think for my command and files here, this anno.bed will not be used if **reference data is transcript** (gencode.v44.pc_**transcripts**.fa).  Since `chr1    11868   14409 - - +` in bed is the level of chromosome and the position is for a certain chromosome, not for a transcript. So if I decide to choose this reference,  I cannot make `--junc-bed` workable. Is it right...?
