### ISSUE TITLE
Minimap2 alignment behavior for close splice sites

### ISSUE THREAD

**Issue by Tidesun** [lh3/minimap2#1143]
We are running Minimap2 for aligning SIRV spike-in data. However, I found there is a great discrepancy of results between Minimap2 v2.24 (which we have been using for reproducibility consideration) and Minimap2 v2.26 (see attached “IGV.pdf”). 

There are two transcripts (SIRV506, SIRV511) with very close splice sites (6bp difference) and identical sequence (both are GG…CA) for the splicing signals. Minimap2 v2.24 in fact maps all reads from these two transcripts to SIRV506 with 6bp deletion instead of SIRV511 without the deletion, while Minimap2 2.26 maps some reads to SIRV511 as well. 

I wonder why this is the case for Minimap2 v2.24 since we also provide annotation of the junction sites by --junc-bed, and I assume there is certain score penalty for alignments with deletion.

A small subset of the reads, reference and script are uploaded here (https://www.dropbox.com/scl/fi/bqbmho1sye90owxlvmebn/test_mm2_SIRV.zip?rlkey=vmnnq1tpbytlf0v18xxwqtyb2&dl=0) and the data is derived from (https://www.encodeproject.org/files/ENCFF023EXJ)
[IGV.pdf](https://github.com/lh3/minimap2/files/13745037/IGV.pdf)

**Comment by lh3** [comment]
It is very rare for mammals and other species to have GG-CA splicing. More recent minimap2 puts a higher penalty on such unlikely events. You can use `-J0` to use the older model.

Generally, SIRV is not good ground truth as it disregards evolutionarily conserved splicing signals.
