### ISSUE TITLE
10X Genomics 5'GEX followed by ONT Kit14 or later

### ISSUE THREAD

**Issue by avilella** [lh3/minimap2#1144]
Hi all,

What would be a good parameter/filter set for 10X Genomics / ONT Kit14 datasets?

I am particularly interested in 10X Genomics 5'GEX datasets, which have the reverse orientation to the more common 3'GEX. See a screenshot of the data that comes out of dorado basecalling (SUP) with the reverse complement of the poly-A tail at the beginning of the read, just after the ONT adaptor (CAGTGGTATCAACGCAGAGTAC).

![image](https://github.com/lh3/minimap2/assets/158007/cefc6832-b403-4502-863f-3bddbad96cd5)

I wouldn't want the poly-T to be misaligned to upstream/downstream of the exons.

**Comment by avilella** [comment]
I aligned a 5'GEX dataset with the following command:

```
samtools bam2fq sup.bam | minimap2 -t 20 --sam-hit-only -a -x splice --junc-bed mammalian.bed mammalian.fa -
```

The distribution of `de:f:' values splits as shown below when facetted by `rl` and `AS` (there are lots of very short reads, presumably from not cleaning 10X TSO artifacts):

![image](https://github.com/lh3/minimap2/assets/158007/0dbcb311-b809-4901-99b4-12961ea67adf)

**Comment by lh3** [comment]
You may preprocess the reads by cutting adapters and poly-T.
