### ISSUE TITLE
Missing Apple Silicon build of Minimap2 in Bioconda

### ISSUE THREAD

**Issue by Adamtaranto** [lh3/minimap2#1148]
Can't install [Minimap2 from Bioconda](https://anaconda.org/bioconda/minimap2) on an M1+ Mac as the osx-arm64 build is not included (only linux-64 and osx-64).

Installing from the [nanoporetech](https://anaconda.org/nanoporetech/minimap2/files) channel works but hasn't been updated in a while. 

i.e. `conda install minimap2 -c nanoporetech`

Could you please include an osx-arm64 build in the bioconda releases?

**Comment by jmarshall** [comment]
This is a bioconda problem, not a minimap2 problem. See bioconda/bioconda-recipes#23454.

**Comment by Adamtaranto** [comment]
Thanks for the clarification. 

It looks like support for osx-arm64 bioconda builds is in the works: https://github.com/bioconda/bioconda-docs/pull/16

**Comment by lh3** [comment]
Thank you, @jmarshall. Good to know bioconda is working on an Apple M1 build.
