### ISSUE TITLE
A-line in gfa as ground truth

### ISSUE THREAD

**Issue by Wenfei-Xian** [lh3/minimap2#1149]
Hello,
         Recently, I try to evalue the long reads mappers.
         For ground truth, I used the A-lines in GFA. The mapping method I employed involved self HiFi reads to the p_ctg.gfa.fa generated by hifiasm. 
          The criterion for a correct mapping is that the starting position of the mapping in the SAM file matches the position in the A-line; if they are the same, the mapping is considered correct. 
          In my data, there are 146,480 reads in the GFA's A-lines. The best performing mapper results are as follows: 
          Winnowmap2: 143,503, pbmm2: 141,071, Minimap2: 141,056, Blend: 140,615, and LRA: 132,981. 
          Is this result somewhat unexpected? Below is the code I ran:
```
#@1)winnowmap2
echo "Time start winnowmap2 $(date)";
meryl count k=15 output merylDB Oak.bp.p_ctg.gfa.fa
meryl print greater-than distinct=0.9998 merylDB > repetitive_k15.txt
time -p winnowmap -W repetitive_k15.txt -ax map-pb Oak.bp.p_ctg.gfa.fa reads.fastq.gz | samtools sort -@12 -o Oak.bp.p_ctg.gfa.fa.winnowmap2.sorted.bam -
echo "Time end winnowmap2 $(date)";

echo "Time start minimap2 $(date)";
#@2)minimap2
time -p minimap2 -ax map-hifi -t 128 Oak.bp.p_ctg.gfa.fa reads.fastq.gz | samtools sort -@12 -o Oak.bp.p_ctg.gfa.fa.minimap2.sorted.bam -
echo "Time end minimap2 $(date)";
minimap2 --version
2.24-r1122

#@3)pbmm2
echo "Time start pbmm2 $(date)";
pbmm2 align -j 128 Oak.bp.p_ctg.gfa.fa reads.fastq.gz Oak.bp.p_ctg.gfa.fa.pbmm2.sorted.bam --sort
echo "Time end pbmm2 $(date)";

#@4)LRA
echo "Time start LRA $(date)";
lra index -CCS Oak.bp.p_ctg.gfa.fa
zcat reads.fastq.gz | lra align -p s -t 128 -CCS Oak.bp.p_ctg.gfa.fa /dev/stdin | samtools sort -@12 -o Oak.bp.p_ctg.gfa.fa.lra.sorted.bam -
echo "Time end LRA $(date)";

#@5)blend
echo "Time start blend $(date)";
blend -ax map-hifi -t 128 Oak.bp.p_ctg.gfa.fa reads.fastq.gz | samtools sort -@12 -o Oak.bp.p_ctg.gfa.fa.blend.sorted.bam -
echo "Time end blend $(date)";

grep "^A" Oak.bp.p_ctg.gfa | awk '{print $5"_"$2"_"$3}' > Oak.bp.p_ctg.gfa.reads.location.txt
for i in `ls | grep "bam$"`;do samtools view -F 0x100 -F 0x800 $i | awk '{print $1"_"$3"_"$4-1}' > $i.reads.location.txt ;done

for i in `ls | grep "bam" | grep "reads.location.txt"`;do echo $i; sort $i Oak.bp.p_ctg.gfa.reads.location.txt | uniq -d | wc -l ;done
```
Best,
Wenfei

**Comment by Wenfei-Xian** [comment]
The context of the evaluation is: possessing a personal HiFi genome and identifying somatic mutations through HiFi reads.

**Comment by lh3** [comment]
Is it an oak genome or human? If human, 2% error rate (1-143503/146480) is too high. Hifiasm may wrongly correct reads. It is not ground truth. Simulating reads may give you more convincing results.

**Comment by Wenfei-Xian** [comment]
It is an Oak genome - Quercus robur

**Comment by Wenfei-Xian** [comment]
I use hifiasm-0.19.8 + CHM13 24kb hifi reads to test.
Total reads number in gfa is 1065318.
```
CHM13.bp.p_ctg.gfa.fa.blend.sorted.bam.reads.location.txt 999780
CHM13.bp.p_ctg.gfa.fa.lra.sorted.bam.reads.location.txt 940873
CHM13.bp.p_ctg.gfa.fa.minimap2.sorted.bam.reads.location.txt 1000339
CHM13.bp.p_ctg.gfa.fa.pbmm2.sorted.bam.reads.location.txt 1000347
CHM13.bp.p_ctg.gfa.fa.winnowmap2.sorted.bam.reads.location.txt 1022880
```
the error rate is about 4% in CHM13, even worser in human data.

**Comment by lh3** [comment]
Thanks. This is interesting and is worth digging further, but I guess it seems more of a hifiasm evaluation than a mapper evaluation.
