### ISSUE TITLE
transcriptom

### ISSUE THREAD

**Issue by rojinsafavi** [lh3/minimap2#115]
Do you suggest using 

./minimap2 -ax splice -k14 -uf transcriptom.fa reads.fa > aln.sam

If instead of reference sequence we are aligning to the transcriptom?

Thanks!

**Comment by lh3** [comment]
You can use `-x map-pb` or `-x map-ont`. I am not sure about downstream processing, though. What do you want to achieve?

**Comment by rojinsafavi** [comment]
I just want to look at the ONT direct RNA reads that align to transcriptom
