### ISSUE TITLE
minimap2 has no results while blast has

### ISSUE THREAD

**Issue by ShannonDaddy** [lh3/minimap2#1150]
Hi, I use minimap2 2.24-r1122 to align an ont read against a reference genome, but it has no results.  But the on-line ncbi blastn has alignment results for the same read and reference genome.

Here is the commands I used.
minimap2 -d db.mmi db.fa
minimap2 -cx map-ont db.mmi test.fastq.gz -o test.paf

the blast out:
![image](https://github.com/lh3/minimap2/assets/6656888/c3fd188c-da47-44a6-9a87-6aeaf336cc2d)
![image](https://github.com/lh3/minimap2/assets/6656888/b6f2bfb1-b1ef-45f2-ae7b-43575e5bbd3a)

the source files are attached. 
[source_files.tar.gz](https://github.com/lh3/minimap2/files/13973244/source_files.tar.gz)

please help me out, thanks!

**Comment by lh3** [comment]
The identity is too low for this 115bp sequence. There may be a chance if you use shorter and/or denser k-mers.

**Comment by ShannonDaddy** [comment]
> The identity is too low for this 115bp sequence. There may be a chance if you use shorter and/or denser k-mers.

Thanks， I‘ll try it.
