### ISSUE TITLE
How to extract reads that mapped to both forward and reverse strand

### ISSUE THREAD

**Issue by MSQ-123** [lh3/minimap2#1151]
Hi, I'm interested in quantifying non-canonical reads in RNA-seq long-reads. Is there any way to extract reads that can map to both forward and reverse strand? (e.g., long chimeric reads that may be caused by DNA inversion). I mean, these reads look like junction reads but the splitted two locate in different strand. I consider it possible to manipulate the bam file to filter these reads.
![截屏2024-01-21 22 05 29](https://github.com/lh3/minimap2/assets/54383785/50d308d6-e3f4-4448-bb66-64a61d9b2daf)

**Comment by lh3** [comment]
You may write a program to extract that.
