### ISSUE TITLE
Long chromosome comparison did not yield results

### ISSUE THREAD

**Issue by QAU2326** [lh3/minimap2#1152]
Dear professor Li，
  I’m trying to map one genome assembly to another using minimap2 (2.26-r1175), the longest chromosome length is 1.7 Gb.
  I have tried to adjust the relevant parameters and execute the following commands, but the content of the error file displayed on the relevant command line is the same as the attached image error message.
![run err](https://github.com/lh3/minimap2/assets/155932119/76b6079c-2d90-49ad-bada-ac608d863233)

  minimap2 -x asm10 -f 0.002 -a -t 60 --eqx $ref $qry > ${spe} 
  minimap2 -t 60 -xasm5 -a -f 0.002 $ref $qry > ${spe} 
  minimap2 -a -t 20 -xasm10 -f 0.002 $ref $qry > ${spe} 
  minimap2 -x asm10 -k 27 -a -t 20 -f 0.002 $ref $qry > ${spe} 
  If I want to get a result file in .sam format, how do I solve this error.
  Can you help me please?
  Thank you.

**Comment by lh3** [comment]
You may find a machine with more RAM.
