### ISSUE TITLE
Minimap2 parameters for compatibility with 10X cDNA and multimapping reads

### ISSUE THREAD

**Issue by Prakrithi-P** [lh3/minimap2#1153]
Hi !
I used scNanoGPS to analyze Nanopore data with 10X Visium cDNA. The results looked good However I have a few questions about the Minimap2 aligner and what parameter to use
The scNanoGPS pipeline by default uses --ax splice in minimap2. However when I use that, some transcripts identified by 10X Visium as primary alignments seem to be secondary alignments/multimapping with minimap2 (although I would expect more confident mapping with long reads)
For some transcripts, the strandedness does not seem to be consistent between 10X Visium and Minimap2
- I tried using --ax map-ont as well. But here some important transcripts I found with Visium and --ax splice are not found.
- We also did qPCR for some transcripts and the expression seems more consistent with that of 10X Visium and alignments from --ax splice. The primers designed were very specific to the transcripts with no off-targets elsewhere but don't understand why minimap does not interpret them as primary alignments.

I also read that splice is more suitable for RNA-seq data while map-ont for genomic data. However, if I use --ax splice I am not sure how to justify/interpret the multimapping and strand inconsistency. Could you please advise on these?

Thanks and regards,
Prakrithi

**Comment by lh3** [comment]
If you map cDNA reads to genome, use `-x splice`.

**Comment by Prakrithi-P** [comment]
Thank you ! How can I justify/interpret the multimapping and strand inconsistency? Is it fine to use counts in the expression matrix that come from the secondary alignments at a given region? (considering that the reads from that region were primary alignments with short read data).
