### ISSUE TITLE
Suppressing secondary and supplementary chains

### ISSUE THREAD

**Issue by pesho-ivanov** [lh3/minimap2#1155]
I am failing to get at most 1 mapping per read.

I saw a bunch of similar issues so here I try to summarize my understanding of `minimap2`'s terms and control flags. I end up with several questions so I will be happy if someone can answer them. Since some terms are undefined or unclear, I believe Prof. Li could ideally fill the documentation gaps.

Questions:
1. Is it possible to ask `minimap2` to always output 0 or 1 mapping per read in the output .paf? (1 if sure about the best mapping; 0 otherwise) I fail to produce this using `--secondary=no` and `samtool` (it breaks with `[main_samview] fail to read the header from "-".`)
2. Can a supplementary alignment be a multiple alignment? In minimap2's FAQ it is defined only as a "[split or chimeric alignment](https://github.com/lh3/minimap2/blob/f3e59fc2a09e89fdb2c166b6d02281e98288c326/FAQ.md?plain=1#L40)".
3. What is the definition of a _split alignment_? By the SAMv1 example it looks like an alignment with a long deletion but how long should it be to be considered long, how to control that in `minimap2`?

Here is the context to my questions:

**Primary chains** -- According to [minimap2's paper](https://academic.oup.com/bioinformatics/article/34/18/3094/4994778), these are chains of higher score than all their secondary chains. In contrast, [SAMv1](https://samtools.github.io/hts-specs/SAMv1.pdf) implies that there is a single primary alignment.

**Secondary chains** -- such that ["overlap with a [primary] chain >=50%"](https://academic.oup.com/bioinformatics/article/34/18/3094/4994778?login=false#393786986):
1. `-N INT` -- this flag is included in `minimap2 -h` as "retain at most INT secondary alignments [5]" but [Prof. Li strongly discourages from using `-N=0` or `-N=1`](https://github.com/lh3/minimap2/issues/603) and `minimap2` warns and changes it to '-N 5 --secondary=no'. related: [Issue 98](https://github.com/lh3/minimap2/issues/98)

2. `--secondary=no` -- this flag is not included in `minimap2 -h`. it suppress the output of secondary chains but not the additional "supplementary alignments"
 
**Supplementary alignments** = "[split or chimeric alignment](https://github.com/lh3/minimap2/blob/f3e59fc2a09e89fdb2c166b6d02281e98288c326/FAQ.md?plain=1#L40)" -- this term is not used in the [minimap2 paper](https://academic.oup.com/bioinformatics/article/34/18/3094/4994778) but is used in `man minimap2`. which by the [FAQ](https://github.com/lh3/minimap2/blob/master/FAQ.md#5-how-to-output-one-alignment-per-read):
3. `minimap2 -ax map-out ref | samtools view -F0x900` -- Prof. Li proposes this command (while discouraging ignoring the supplementary alignments) to filter out supplementary alignments but I fail to get it working with `samtools` returning `[main_samview] fail to read the header from "-".`

[SAMv1](https://samtools.github.io/hts-specs/SAMv1.pdf) definitions (click to expand):
<details>
<summary>Chimeric alignment</summary>
An alignment of a read that cannot be represented as a linear alignment. A chimeric
alignment is represented as a set of linear alignments that do not have large overlaps. Typically, one
of the linear alignments in a chimeric alignment is considered the “representative” alignment, and the
others are called “supplementary” and are distinguished by the supplementary alignment flag. All the
SAM records in a chimeric alignment have the same QNAME and the same values for 0x40 and 0x80
flags (see Section 1.4). The decision regarding which linear alignment is representative is arbitrary.
</details>
<details>
<summary>Split alignment</summary>
I don't find a definition of this term but SAMv1 gives an example::
```
ref AGCATGTTAGATAA**GATAGCTGTGCTAGTAGGCAGTCAGCGCCAT
+r004 ATAGCT..............TCAGC
```
</details>
<details>
<summary>Multiple mapping -- SAMv1 definition (click to expand)</summary>
The correct placement of a read may be ambiguous, e.g., due to repeats. In this case,
there may be multiple read alignments for the same read. One of these alignments is considered
primary. All the other alignments have the secondary alignment flag set in the SAM records that
represent them. All the SAM records have the same QNAME and the same values for 0x40 and 0x80
flags. Typically the alignment designated primary is the best alignment, but the decision may be
arbitrary.
</details>

**Comment by lh3** [comment]
> Is it possible to ask minimap2 to always output 0 or 1 mapping per read in the output .paf?

No, not possible

> Can a supplementary alignment be a multiple alignment?

No

> What is the definition of a split alignment?

Chimeric alignment. SAM tries to make a distinction but in practice the two often mean the same.
