### ISSUE TITLE
R10.4.1 Nanopore preset 

### ISSUE THREAD

**Issue by mbhall88** [lh3/minimap2#1156]
I was wondering whether you feel the `map-ont` preset is still the best option for the latest (R10.4.1) nanopore data basecalled with super high accuracy (sup) models? For example, the manpage says this preset of for noisy long reads of ~10% error rate. Some recent nanopore samples I am working with are showing a median (gap-compressed) identity of 99.3%.

I noticed there is the PacBio presets (specifically hifi), but it doesn't mention what error rate those are targeted at and I am not sure if they would be appropriate?

**Comment by Axze-rgb** [comment]
Hello, did you figure this out? I am wondering the same. I  have noticed that the assembler Flye uses an adjusted -k to -k17 instead of the default value 15 that comes with the ont preset.

**Comment by mbhall88** [comment]
Ah I missed #1127. No I haven’t tested out any changed settings sorry. I’ll close this in favour of #1127
