### ISSUE TITLE
Minimap2 custom 16S rRNA database

### ISSUE THREAD

**Issue by EsbergA** [lh3/minimap2#1160]
Hi all, 
We are working with Minimap2 within the EPI2me lab platform and trying to build a custom database based on the 1,500 full-length 16S rRNA sequences present in the [HOMD](https://github.com/lh3/minimap2/issues/homd.org/download#refseq) database. As I understand the information, this database should contain two files, (i) a RefSeq file with all sequences and (ii) a Taxonomic file with all taxa levels for each RefSeq. I have tried many different formats, but all stop with an error, so if anyone has an example or can guide me in how a custom database for Minimap2 should be configured, it would be greatly appreciated.
Anders

**Comment by lh3** [comment]
What is the error message? Note that minimap2 only works with FASTA/FASTQ.

**Comment by EsbergA** [comment]
Thank you for the reply, I attached a file with the error message. I also attached the pasta and taxonomy file
/ Anders 
[N E X T F L O W.docx](https://github.com/lh3/minimap2/files/14222077/N.E.X.T.F.L.O.W.docx)
[ref2taxid.txt](https://github.com/lh3/minimap2/files/14222122/ref2taxid.txt)
[reference.txt](https://github.com/lh3/minimap2/files/14222123/reference.txt)

**Comment by lh3** [comment]
FASTA looks ok. You need to ask someone else about what to do.
