### ISSUE TITLE
minimap2 alignment only loaded/built the index for 1 target sequence(s) in file of thousands of ONT reads

### ISSUE THREAD

**Issue by mgurbano** [lh3/minimap2#1162]
Hi,
I have been attempting to align some ONT-generated HCV sequences to reference sequence using minimap2. The issue I am having is that no matter which command I run with minimap2 alignment, I always result in the 3rd output line saying the following:
[M::main::0.004*0.00] loaded/built the index for 1 target sequence(s)

For context, we have performed a cDNA amplification into a secondary sequencing primer amplification, so I assumed I should be using this alignment command version:
$minimap2 -ax splice:hq -uf ref.fa query.fa > aln.sam

but I have also tried the following:
$minimap2 -ax map-ont ref.fa ont.fq.gz > aln.sam
$minimap2 -a ref.fa ont.fq.gz > aln.sam
$minimap2 -ax splice:hq ref.fa query.fa > aln.sam
^for all versions of the commands listed, I have tried both gzipped fastqs and decompressed fastqs, so every command with a ".fq.gz" has also been tried with just a ".fq" file. I have also tried multiple different HCV genotype alignment files of different genotypes and different regions of the genome in case there was an issue with my alignment file. I have tested this alignment file using ONT HCV reads previously and it worked as expected, so I doubted it was that issue to begin with.

From my notes, I have run this exact command on test files (still ONT HCV reads, but from plasmid) and got the exact expected output, not what I am describing above:
$minimap2 -ax splice:hq ref.fa seq.fq > aln.sam
(did not use -uf when I ran it previously)

Copy and Paste results from my terminal (with real file names removed for clarity):
$minimap2 -ax splice:hq -uf ref.fa query.fa > aln.sam
[M::mm_idx_gen::0.003*0.00] collected minimizers
[M::mm_idx_gen::0.004*0.00] sorted minimizers
**[M::main::0.005*0.00] loaded/built the index for 1 target sequence(s)**
[M::mm_mapopt_update::0.005*0.00] mid_occ = 10
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.006*0.00] distinct minimizers: 3210 (99.97% are singletons); average occurrences: 1.002; average spacing: 2.941; total length: 9456
**[M::worker_pipeline::2.314*0.95] mapped 1 sequences**
[M::main] Version: 2.24-r1122
[M::main] CMD: minimap2 -ax splice:hq -uf HCV-GT-3-Ref.fasta combined-barcode86.fastq.gz
[M::main] Real time: 2.323 sec; CPU: 2.203 sec; Peak RSS: 0.383 GB

$minimap2 -ax splice:hq ref.fa query.fa > aln.sam
[M::mm_idx_gen::0.003*0.00] collected minimizers
[M::mm_idx_gen::0.004*0.00] sorted minimizers
**[M::main::0.005*0.00] loaded/built the index for 1 target sequence(s)**
[M::mm_mapopt_update::0.005*0.00] mid_occ = 10
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.006*0.00] distinct minimizers: 3210 (99.97% are singletons); average occurrences: 1.002; average spacing: 2.941; total length: 9456
**[M::worker_pipeline::2.362*0.95] mapped 1 sequences**
[M::main] Version: 2.24-r1122
[M::main] CMD: minimap2 -ax splice HCV-GT-3-Ref.fasta combined-barcode86.fastq.gz
[M::main] Real time: 2.372 sec; CPU: 2.234 sec; Peak RSS: 0.383 GB

$minimap2 -ax map-ont ref.fa ont.fq.gz > aln.sam
[M::mm_idx_gen::0.003*0.00] collected minimizers
[M::mm_idx_gen::0.005*0.00] sorted minimizers
**[M::main::0.005*0.00] loaded/built the index for 1 target sequence(s)**
[M::mm_mapopt_update::0.006*0.00] mid_occ = 10
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.006*0.00] distinct minimizers: 1771 (100.00% are singletons); average occurrences: 1.000; average spacing: 5.339; total length: 9456
**[M::worker_pipeline::1.045*0.96] mapped 1 sequences**
[M::main] Version: 2.24-r1122
[M::main] CMD: minimap2 -ax map-ont HCV-GT-3-Ref.fasta combined-barcode86.fastq
[M::main] Real time: 1.059 sec; CPU: 1.000 sec; Peak RSS: 0.299 GB

$minimap2 -a ref.fa ont.fq.gz > aln.sam
[M::mm_idx_gen::0.003*0.00] collected minimizers
[M::mm_idx_gen::0.005*0.00] sorted minimizers
**[M::main::0.005*0.00] loaded/built the index for 1 target sequence(s)**
[M::mm_mapopt_update::0.005*0.00] mid_occ = 38
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.006*0.00] distinct minimizers: 1780 (99.72% are singletons); average occurrences: 1.022; average spacing: 5.300; total length: 9646
**[M::worker_pipeline::7.464*0.95] mapped 1 sequences**
[M::main] Version: 2.24-r1122
[M::main] CMD: minimap2 -a HCV-GT-1A-RefSeq.fasta combined-barcode86.fastq
[M::main] Real time: 7.473 sec; CPU: 7.109 sec; Peak RSS: 0.300 GB

Any help or guidance would be very much appreciated!
Thank you for your time, and I hope for a response!

**Comment by lh3** [comment]
> I always result in the 3rd output line saying the following:

Because you only have one reference

> [M::worker_pipeline::2.314*0.95] mapped 1 sequences

Check if the input is correctly formatted.

**Comment by mgurbano** [comment]
Thank you for your quick response!

I completely forgot to add the result of the output file to my post. The .sam file outputs basically nothing. There is only 1 read that is analyzed in the .sam file, and it is missing it's header/readname. 

It's clear that something must be wrong with my fastq input. I have looked through the manual, github page, and the source material for minimap2 and I can't find a section about fastq formatting for the input. My fastq file is manipulatable and visually appears that nothing is wrong with it. I have checked multiple sources and cannot find anything wrong with my fastq formatting. I concatenated many reads into one fastq file using a python interleave script, but I have used this on ONT reads with this reference sequence before without issue. The script did not affect formatting in a way that prevented minimap2 from functioning last time.
Do you have any idea of what I should look into next to try to validate/fix my fastq?
