### ISSUE TITLE
Minimap2 in EPI2me issue

### ISSUE THREAD

**Issue by EsbergA** [lh3/minimap2#1163]
I am using ONT sequencing and would like to construct a custom database using sequences from the HOMD home page. 
But it terminates my run by: Error: The reference 712237 is not found in your ref2taxid file. Please make sure that the ref2taxid matches the reference.

As I understand Minimap2, it requires a FASTA file and a ref2taxid: 

My FASTA file has the structure of this: 
>712237
GAGTTTGATCCTGGCTCAGAGCGAACGCTGGCGGCAG..........

My ref2taxid file as this: 
>712237	k_Bacteria;p_Proteobacteria;c_Alphaproteobacteria;o_Caulobacterales;f_Caulobacteraceae;g_Caulobacter;s_Caulobacter_sp._HMT_002

I have tried many different combinations but never get it to run, help is greatly appreciated 
/ AE

**Comment by lh3** [comment]
This seems not a minimap2 issue?
