### ISSUE TITLE
paftools.js view - MAF requires 'cs' tag

### ISSUE THREAD

**Issue by erika-r-moore** [lh3/minimap2#1164]
Hello,

I am receiving this error, `WARNING: converting to MAF requires the 'cs' tag, which is absent on line 1` when trying to use `paftools.js view` though I generated the paf files through minimap2. 

Here is an example command to generate the paf files:
`~/minimap2-2.26_x64-linux/minimap2 -t26 -ax asm20 -k 21 --cs ./Helianthus_decontaminated.fasta.SOFTmasked ./acicarphahap1decontaminated.fasta.SOFTmasked > Helianthus_Acicarpha-cs.paf`
I tried with the --cs flag and without, but get the same error.

Here is the command I used to generate the maf file:
`k8 ~/minimap2-2.26_x64-linux/paftools.js view -f maf -> asterales8.maf`

Below are the first few lines of one of my paf files:
```
head -n 20 Helianthus_Acicarpha.paf
@HD     VN:1.6  SO:unsorted     GO:query
@SQ     SN:Ha412HOChr01 LN:159217232
@SQ     SN:Ha412HOChr02 LN:184765313
@SQ     SN:Ha412HOChr03 LN:182121094
@SQ     SN:Ha412HOChr04 LN:221926752
@SQ     SN:Ha412HOChr05 LN:187413619
@SQ     SN:Ha412HOChr06 LN:157516673
@SQ     SN:Ha412HOChr07 LN:162054088
@SQ     SN:Ha412HOChr08 LN:177936428
@SQ     SN:Ha412HOChr09 LN:200254352
@SQ     SN:Ha412HOChr10 LN:190919061
@SQ     SN:Ha412HOChr11 LN:199477616
@SQ     SN:Ha412HOChr12 LN:179008902
@SQ     SN:Ha412HOChr13 LN:175682153
@SQ     SN:Ha412HOChr14 LN:189916084
@SQ     SN:Ha412HOChr15 LN:186609792
@SQ     SN:Ha412HOChr16 LN:218409126
@SQ     SN:Ha412HOChr17 LN:205797941
@PG     ID:minimap2     PN:minimap2     VN:2.26-r1175   CL:minimap2 -t26 -ax asm20 -k 21 ./Helianthus_decontaminated.fasta.SOFTmasked ./acicarphahap1decontaminated.fasta.SOFTmasked
scaffold_1      0       Ha412HOChr11    194203897       12      182120944S801M1D160M498D1522M5D397M5D115M47447616S      *     00       CCCAaaaccctaaaccctaaaccctaaccctaaaccctaaaccctaaaccctaaacccta
```

Do you know why this may be happening? Please let me know if you need any additional information!

Thanks!
Erika

_Originally posted by @erika-r-moore in https://github.com/lh3/minimap2/issues/653#issuecomment-1944668466_

**Comment by lh3** [comment]
> `CL:minimap2 -t26 -ax asm20 -k 21 ./Helianthus_decontaminated.fasta.SOFTmasked ./acicarphahap1decontaminated.fasta.SOFTmasked`

You didn't use cs

**Comment by erika-r-moore** [comment]
I tried with the --cs flag and without, but get the same error.

**Comment by lh3** [comment]
The input should be PAF generated with `--cs=long`

**Comment by erika-r-moore** [comment]
Hello,

Using `--cs=long` finally worked in getting some sort of maf output!!

I am still getting some 'cs' tag errors though, and the maf file seems small considering the sizes of the paf files.
paf files and their sizes:
```
-rw-r--r-- 1 ermoore3 users 2.5G Mar 14 12:19 Arabidopsis_Acicarpha.paf
-rw-r--r-- 1 ermoore3 users 1.6G Mar 14 12:20 Arabidopsis_Arctium.paf
-rw-r--r-- 1 ermoore3 users 2.5G Mar 14 12:25 Arabidopsis_Chrysanthemum.paf
-rw-r--r-- 1 ermoore3 users 2.2G Mar 14 12:27 Arabidopsis_Lactuca.paf
-rw-r--r-- 1 ermoore3 users 477M Mar 14 12:27 Arabidopsis_Nymphoides.paf
-rw-r--r-- 1 ermoore3 users 628M Mar 14 12:28 Arabidopsis_Platycodon.paf
-rw-r--r-- 1 ermoore3 users 3.0G Mar 14 12:29 Arabidopsis_Helianthus.paf
-rw-r--r-- 1 ermoore3 users 1.2G Mar 14 12:30 Arabidopsis_Scaevola.paf
```

maf file size:
`-rw-r--r-- 1 ermoore3 users  14M Mar 14 12:34 asterales8_Arabidopsis.maf`

My questions then become:
**1)** Is this normal and expected? I am having a hard time finding an answer online.
**2)** If it is not normal, do you notice any errors in my code/results that may be causing this?

Here is an example command that I used to generate the paf files:
`~/minimap2-2.26_x64-linux/minimap2 -t26 -ax asm20 -k 21 --cs=long ./GCA_000001735.2_TAIR10.1_genomic.fna.masked ./Arctium_decontaminated.fasta.SOFTmasked > Arabidopsis_Arctium.paf`

Here is the command that I used to generate the maf file:
`~/minimap2-2.26_x64-linux/paftools.js view -f maf *.paf -> asterales8_Arabidopsis.maf`

k8 is in my path:
```
echo $PATH
/home/ermoore3/miniconda2/bin/k8
```

I attached my error files from generating the paf files (minimap-1697.txt) and from generating the maf file (minimap-1698.txt). I also attached the resulting maf file so you can see the output.

Any help is appreciated!

Best,
Erika 

[asterales8_Arabidopsis.maf.gz](https://github.com/lh3/minimap2/files/14606144/asterales8_Arabidopsis.maf.gz)
[minimap-1697.txt](https://github.com/lh3/minimap2/files/14606145/minimap-1697.txt)
[minimap-1698.txt](https://github.com/lh3/minimap2/files/14606146/minimap-1698.txt)
