### ISSUE TITLE
How does "-s" parameter affect the alignment results?

### ISSUE THREAD

**Issue by kerenzhou062** [lh3/minimap2#1165]
Dear Heng,

I'm currently using minimap2 to align Nanopore cDNA reads to the human genome using following parameters:
`minimap2 -ax splice -Y -s 40 --secondary=no --junc-bed`

I noticed that, the supplementary alignments will increase when changing `-s 40` to `-s 0`. I'm curious about how `-s` affect the alignment results, especially the supplementary alignments. And do you have any suggestions on how to improve the supplementary alignments for short clipping reads (soft clip length < 40nt)?

Thanks,

Keren

**Comment by lh3** [comment]
> how -s affect the alignment results

Drop alignments if scores lower than -s

> any suggestions on how to improve the supplementary alignments for short clipping reads (soft clip length < 40nt)

Adding -n2 -m20 might help, but generally minimap2 is not the right tool.
