### ISSUE TITLE
CIGAR with 72833 operators at the CG tag

### ISSUE THREAD

**Issue by JinShuo0101** [lh3/minimap2#1169]
Hi!

I use minimap2 to map the fastq format to the reference genome, and use samtools view to extract the sam result, the command is 2 to map the fastq format to the reference genome, and use samtools view to extract the sam result, the 
`minimap2 --MD -L -t $nthreads -ax map-ont -o $samfile $reffile $fqfile`

`samtools view -h -F 4069 --threads $nthreads -o $uniq_samfile $samfile`

But the following error occurred :  

![minimap2_samtools_error](https://github.com/lh3/minimap2/assets/158452973/1e7295ed-9950-4c08-a607-1515edfdc113)

Actually, minimap2(v2.26) and samtools(samtools 1.19.2-11-g15d6538 Using htslib 1.19.1-19-g5d2c3f72) are both latest version installed from source, and both x86 and ARM have the above problem.

Why is there this error? And how should I solve it?

Thank you for your time,  any help would be greatly appreciated!

**Comment by lh3** [comment]
What is the minimap2 output for that read?

**Comment by JinShuo0101** [comment]
Here is the minimap2 output for that read : 
[error_read.TXT](https://github.com/lh3/minimap2/files/14548480/error_read.TXT)

**Comment by lh3** [comment]
It seems just a warning. BAM is still generated. If you have questions, please create an issue at the samtools repo.
