### ISSUE TITLE
Python mappy Aligner doesn't handle best_n properly

### ISSUE THREAD

**Issue by wukevin** [lh3/minimap2#117]
When attempting to create an Aligner object in Python using the invocation:
```
minimap = mappy.Aligner(GENOME_MMI, preset="splice", best_n=5)
```

The following error is produced:
```    
File "python/mappy.pyx", line 114, in mappy.Aligner.__cinit__
AttributeError: 'mappy.Aligner' object has no attribute 'best_n'
```

Mappy version 2.8, Python 2.7.11

**Comment by lh3** [comment]
That's a typo. I have changed the code, but haven't tested it yet. See the master.
