### ISSUE TITLE
PCR-cDNA sequence from MinION not alligned

### ISSUE THREAD

**Issue by Macdot3** [lh3/minimap2#1170]
Hello everyone, in my initial experiment, I aligned my cDNA sequence from ONT MinION using the following parameters: 
`./minimap2 -ax map-ont /home/my_reference_PCR.fasta /home/input_pcr_PI4K.fastq > output_PI4K_aligned.sam. ` Then I built the bam file.
I noticed that the alignment focused only on a specific region of the reference with a 10X coverage. To examine other regions, I extracted the reads of maximum length from the fastq file using the following command: 
`seqkit seq -m $(seqkit stats -T /home/input_pcr_PI4K.fastq | tail -n1 | cut -f 8) /home/input_pcr_PI4K.fastq -o /home/output_PI4K.fastq`
However, when aligning this new file using both the `-ax map-ont` and `-x splice `commands (since it's a cDNA sequence), I get 0% mapping according to samtools flagstats. I can't figure out why. Is there something wrong with the extraction or do I need to adjust the alignment parameters further? I hope you can help me. 
Thanks a lot.

**Comment by lh3** [comment]
Could you provide the sequences?

**Comment by Macdot3** [comment]
Here are the sequences: 
[sequences.zip](https://github.com/lh3/minimap2/files/14549914/sequences.zip)
the fasta file is the reference, output_50 is the extracted reads and the other fastq file is the original file

**Comment by lh3** [comment]
I don't know the purpose of your command line, but as long as the original sequences can be aligned, this is not a minimap2 issue. Also, the reads have introns. Please use splice.

**Comment by dudududu12138** [comment]
> I don't know the purpose of your command line, but as long as the original sequences can be aligned, this is not a minimap2 issue. Also, the reads have introns. Please use splice.

Hello, I browsed to this issue and wondered about your expression. Why do cDNA sequences have introns?
