### ISSUE TITLE
empty output from paftools.js call on alignment with 1110 mapped bases ( 398M6I706M ) 

### ISSUE THREAD

**Issue by tpshea2** [lh3/minimap2#1171]
Even with setting -L to 0 and -l to 0 the output from paftools.js call is empty on the following input PAF file (see below).  I see from the README that "By default, when calling variants, "paftools.js call" ignores alignments 50kb or shorter; when deriving callable regions, it ignores alignments 10kb or shorter." but in changing -L and -l to 0 does it bypass these defaults of 50kb and 10kb ?  Can paftools.js be used for an alignment of this type where the reference is a gene of about 1kb and the query is a sequence of about 1kb?

@HD	VN:1.6	SO:unsorted	GO:query
@SQ	SN:OmpK36	LN:1104
LECOID_12970	0	OmpK36	1	60	398M6I706M	*	0	0	ATGAAAGTTAAAGTACTGTCCCTTTTGGTACCGGCTCTGCTGGTAGCAGGCGCAGCAAATGCGGCTGAAATTTATAACAAAGACGGCAACAAATTAGACCTGTACGGTAAAATTGACGGTCTGCACTACTTCTCTGACGACAAGAGCGTCGACGGCGACCAGACCTACATGCGTGTAGGCGTGAAAGGCGAAACCCAGATCAACGACCAGCTGACCGGTTACGGCCAGTGGGAATACAACGTTCAGGCGAACAACACTGAAAGCTCCAGCGATCAGGCATGGACTCGTCTGGCATTCGCAGGCCTGAAATTTGGCGACGCGGGCTCTTTCGACTACGGTCGTAACTACGGCGTAGTATACGACGTAACGTCCTGGACCGACGTTCTGCCGGAATTCGGCGGCGACGGCGACACCTACGGTTCTGACAACTTCCTGCAGTCCCGTGCTAACGGCGTTGCAACCTACCGTAACTCTGATTTCTTCGGTCTGGTTGACGGCCTGAACTTTGCTCTGCAGTATCAGGGTAAAAACGGCAGCGTCAGCGGCGAAGGCGCTCTGTCTCCTACCAACAACGGTCGTACCGCCTTGAAACAGAACGGCGACGGTTACGGTACTTCTCTGACCTATGACATCTATGATGGCATCAGCGCTGGTTTCGCATACTCTAACTCCAAACGTCTTGGCGACCAGAACAGCAAGCTGGCACTGGGTCGTGGCGACAACGCTGAAACCTACACCGGCGGTCTGAAATACGACGCGAACAACATCTACCTGGCCACTCAGTACACCCAGACCTACAACGCGACCCGCGCCGGTTCCCTGGGCTTTGCTAACAAAGCGCAGAACTTCGAAGTGGTTGCTCAGTACCAGTTCGACTTCGGTCTGCGTCCGTCCGTGGCTTACCTGCAGTCTAAAGGTAAGGATCTGGAAGGCTACGGCGACCAGGACATCCTGAAATATGTTGACGTTGGCGCGACCTACTACTTCAACAAAAACATGTCCACCTATGTTGACTACAAAATCAACCTGCTGGACGACAATAGCTTCACCCACAACGCCGGTATCTCTACCGACGACGTGGTTGCACTGGGCCTGGTTTACCAGTTCTAA	*	NM:i:12	ms:i:1062	AS:i:1056	nn:i:0	tp:A:P	cm:i:186	s1:i:1063	s2:i:0	de:f:0.0063	cs:Z::23*ct*ct:373+cggcga:408*tc:5*tc:221*ct:10*ga:58	rl:i:0
@PG	ID:minimap2	PN:minimap2	VN:2.26-r1175	CL:minimap2 -ax asm20 --cs OmpK36.fasta LECOID_12970.fasta

**Comment by lh3** [comment]
Could you provide both reference and query sequences?

**Comment by tpshea2** [comment]
Here are the sequences for reference and query:
>OmpK36
atgaaagttaaagtactgtccctcctggtaccggctctgctggtagcaggcgcagcaaat
gcggctgaaatttataacaaagacggcaacaaattagacctgtacggtaaaattgacggt
ctgcactacttctctgacgacaagagcgtcgacggcgaccagacctacatgcgtgtaggc
gtgaaaggcgaaacccagatcaacgaccagctgaccggttacggccagtgggaatacaac
gttcaggcgaacaacactgaaagctccagcgatcaggcatggactcgtctggcattcgca
ggcctgaaatttggcgacgcgggctctttcgactacggtcgtaactacggcgtagtatac
gacgtaacgtcctggaccgacgttctgccggaattcggcggcgacacctacggttctgac
aacttcctgcagtcccgtgctaacggcgttgcaacctaccgtaactctgatttcttcggt
ctggttgacggcctgaactttgctctgcagtatcagggtaaaaacggcagcgtcagcggc
gaaggcgctctgtctcctaccaacaacggtcgtaccgccttgaaacagaacggcgacggt
tacggtacttctctgacctatgacatctatgatggcatcagcgctggtttcgcatactct
aactccaaacgtcttggcgaccagaacagcaagctggcactgggtcgtggcgacaacgct
gaaacctacaccggcggtctgaaatacgacgcgaacaacatctacctggccactcagtac
acccagacctacaacgcgacccgcgctggttctctgggctttgctaacaaagcgcagaac
ttcgaagtggttgctcagtaccagttcgacttcggtctgcgtccgtccgtggcttacctg
cagtctaaaggtaaggatctggaaggctacggcgaccaggacatcctgaaatatgttgac
gttggcgcgacctactacttcaacaaaaacatgtccacctatgttgactacaaaatcaac
ctgctggacgacaacagcttcacccgcaacgccggtatctctaccgacgacgtggttgca
ctgggcctggtttaccagttctaa
>LECOID_12970 Outer membrane porin OmpC/OmpF/PhoE
ATGAAAGTTAAAGTACTGTCCCTTTTGGTACCGGCTCTGCTGGTAGCAGGCGCAGCAAAT
GCGGCTGAAATTTATAACAAAGACGGCAACAAATTAGACCTGTACGGTAAAATTGACGGT
CTGCACTACTTCTCTGACGACAAGAGCGTCGACGGCGACCAGACCTACATGCGTGTAGGC
GTGAAAGGCGAAACCCAGATCAACGACCAGCTGACCGGTTACGGCCAGTGGGAATACAAC
GTTCAGGCGAACAACACTGAAAGCTCCAGCGATCAGGCATGGACTCGTCTGGCATTCGCA
GGCCTGAAATTTGGCGACGCGGGCTCTTTCGACTACGGTCGTAACTACGGCGTAGTATAC
GACGTAACGTCCTGGACCGACGTTCTGCCGGAATTCGGCGGCGACGGCGACACCTACGGT
TCTGACAACTTCCTGCAGTCCCGTGCTAACGGCGTTGCAACCTACCGTAACTCTGATTTC
TTCGGTCTGGTTGACGGCCTGAACTTTGCTCTGCAGTATCAGGGTAAAAACGGCAGCGTC
AGCGGCGAAGGCGCTCTGTCTCCTACCAACAACGGTCGTACCGCCTTGAAACAGAACGGC
GACGGTTACGGTACTTCTCTGACCTATGACATCTATGATGGCATCAGCGCTGGTTTCGCA
TACTCTAACTCCAAACGTCTTGGCGACCAGAACAGCAAGCTGGCACTGGGTCGTGGCGAC
AACGCTGAAACCTACACCGGCGGTCTGAAATACGACGCGAACAACATCTACCTGGCCACT
CAGTACACCCAGACCTACAACGCGACCCGCGCCGGTTCCCTGGGCTTTGCTAACAAAGCG
CAGAACTTCGAAGTGGTTGCTCAGTACCAGTTCGACTTCGGTCTGCGTCCGTCCGTGGCT
TACCTGCAGTCTAAAGGTAAGGATCTGGAAGGCTACGGCGACCAGGACATCCTGAAATAT
GTTGACGTTGGCGCGACCTACTACTTCAACAAAAACATGTCCACCTATGTTGACTACAAA
ATCAACCTGCTGGACGACAATAGCTTCACCCACAACGCCGGTATCTCTACCGACGACGTG
GTTGCACTGGGCCTGGTTTACCAGTTCTAA

**Comment by lh3** [comment]
`paftools.js call` only takes PAF as input. It silently skips lines that are not PAF.
