### ISSUE TITLE
multithreads not used?

### ISSUE THREAD

**Issue by Jeltje** [lh3/minimap2#1172]
Version: 2.26-r1175 (conda install)

This is basically the same question as #763, which was closed by the submitter without further comment, so I have the feeling I'm missing something blindingly obvious. 
Here's my command:
`minimap2 -a -t 4 -N 4 flair.collapse.firstpass.fa human.ONT.simulated.fq > out.sam`
I never see it use more than 1 CPU:
```
hgwdev@~:$ ps -ef | grep 240223
jeltje   240223 360748 99 10:16 pts/75   00:22:12 minimap2 -a -t 4 -N 4 flair.collapse.firstpass.fa human.ONT.simulated.fq
jeltje   265228 262531  0 10:22 pts/97   00:00:00 grep --color=auto 240223
```
stderr:
```
[M::mm_idx_gen::5.920*1.53] collected minimizers
[M::mm_idx_gen::6.796*1.84] sorted minimizers
[M::main::6.832*1.84] loaded/built the index for 291003 target sequence(s)
[M::mm_mapopt_update::7.019*1.81] mid_occ = 205
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 291003
[M::mm_idx_stat::7.136*1.80] distinct minimizers: 10592380 (24.05% are singletons); average occurrences: 4.346; average spacing: 5.452; total length: 250980987
[M::worker_pipeline::153.129*3.88] mapped 481314 sequences
[M::worker_pipeline::285.189*3.96] mapped 480826 sequences
[M::worker_pipeline::415.860*4.00] mapped 480895 sequences
```
I imagine the worker pipeline is supposed to run on multiple threads?

**Comment by lh3** [comment]
> 415.860*4.00

Already multiple thread.

**Comment by Jeltje** [comment]
But as what should I see this on my system then? Threads are supposed to be created by the main program, so I should see the PID (here 240223) pop up when running `ps -ef`, right?
