### ISSUE TITLE
installation not possible from bioconda

### ISSUE THREAD

**Issue by mocherry** [lh3/minimap2#1174]
Dear all,

another attempt to install minimap2 is unsuccessful again:

using conda install bioconda::minimap2
conda install bioconda/label/cf201901::minimap2

PackagesNotFoundError: The following packages are not available from current channels:
  - bioconda::minimap2

mind: I am working with Windows and have Miniconda installed.

Thanks and best,
Matthias

**Comment by lh3** [comment]
Thank you for the explanation, @rob-p.

Others told me that minimap2 could be compiled on Windows using either MinGW or Visual C++. I haven't tried. As Rob said, minimap2 is available on Bioconda but Bioconda doesn't support windows.
