### ISSUE TITLE
paftools.js gff2junc or gff2bed for junc-bed?

### ISSUE THREAD

**Issue by felixradtke** [lh3/minimap2#1175]
Hi,

I noticed that the minimap2 manual mentions "BED12 file can be converted from GTF/GFF3 with ‘paftools.js gff2bed anno.gtf’" whereas the newest version of paftools.js has both a gff2bed and a gff2junc option. Which one should be used to prepare for the minimap2 -junc-bed flag?

Or is `gff2bed -j anno.gtf` identical to `gff2junc anno.gtf`?

Thank you!

**Comment by lh3** [comment]
Both should work. I am using gff2bed during testing.
