### ISSUE TITLE
Increasing alignment sensitivity 

### ISSUE THREAD

**Issue by jsromanowski** [lh3/minimap2#1176]
Hello,

I am currently trying to increase the sensitivity of my alignments using minimap2. I am exploring this by decreasing the seed length with option -k. 

After running the following command:

$ minimap2 -k 10 --secondary=no 230629_AniI-P5-F2_WR_sig2.fas AniI_WR_master_500.fastq -o AniI_WR_master_500_k8_nosec.sam

where 230629_AniI-P5-F2_WR_sig2.fas is my reference .fas and AniI_WR_master_500.fastq is my input .fastq,

I receive the following error:

[main_samview] fail to read the header from "AniI_WR_master_500_k10_nosec.sam".

After viewing the .sam file output from the alignment, the header does seem to be altered/missing from the .sam file. How can I overcome this issue?

Additionally - I am wondering, what other ways can I increase the sensitivity of the alignment?

Thanks

**Comment by jsromanowski** [comment]
Update: Resolved. This issue required a trivial solution. I needed to add option -a to output in .sam format. After correcting the command and adding this argument, the resulting .sam file retained the proper header.

**Comment by jsromanowski** [comment]
Update: I resolved the alignment issue, I needed to include option -a to output alignment in .sam format. 

I am leaving the thread open to see how I can increase alignment sensitivity.

Thanks

**Comment by lh3** [comment]
Thank you. Without -a, minimap2 wouldn't output sam.
