### ISSUE TITLE
How to map to combinatorial plasmid libraries

### ISSUE THREAD

**Issue by c-ruprecht** [lh3/minimap2#1178]
Hi,
I am using golden gate assemblies to create modular plasmid libraries. I currently am looking at potentially a 80 combinations of plasmids that are quite similar. (4 Promoters x 8 Gene A x 8 Gene B )
backbone---PromoterRBS1---GeneA1---GeneB1---Barcode
backbone---PromoterRBS2---GeneA1---GeneB1---Barcode
...
backbone---PromoterRBS4---GeneA4---GeneB4---Barcode

I sequence the multiplexed plasmids using and demultiplex using the barcode. I want to identify the corresponding plasmids using the demultiplexed reads. Currently I am using: 

minimap2 -x map-ont --secondary=no 

I then take the mapping with the highest score for each read and assign the plasmid by the highest abundance of a mapping. This works somewhat ok with a control experiment but I want to work on my minimap settings and I am wondering what the right minimap settings are for my situation.
Thanks for the help!

**Comment by lh3** [comment]
You may consider to add `-f 100` in case minimap2's automatic heuristic chooses an inappropriate k-mer threshold. As to other options, you have to try by yourself as I haven't worked with such data.
