### ISSUE TITLE
Single query vs. Multiple queries

### ISSUE THREAD

**Issue by dnnguy23** [lh3/minimap2#1179]
Hi,
I am using minimap2 to map multiple amplicons to a reference sequence with 2 different mapping schemes.
1st scheme:
     Combine all queries into a single FASTQ file, then align all to the reference.
2nd scheme:
     Map each query to the reference, then combine the results.

Will these 2 mapping schemes yield very different results?

**Comment by lh3** [comment]
> Will these 2 mapping schemes yield very different results?

No
