### ISSUE TITLE
alignments in sam output not sorted by query

### ISSUE THREAD

**Issue by vkkodali** [lh3/minimap2#1184]
This is similar to the issue reported in #530
I have a small set of 1000 reads that I am aligning to an index created for [GCA_015104395.2](https://ncbi.nlm.nih.gov/datasets/genome/GCA_015104395.2/) as shown below. 
```
$ minimap2 --version
2.26-r1175
## create index
$ minimap2 -k 15 -w 5 -d GCA_015104395.2.mmi GCA_015104395.2.fa
## align reads 
$ minimap2 -x splice --eqx --MD --cs -Y --sam-hit-only -M 0.9 -p 0.1 -N 25 -G 600000 -a \
  -o output.sam GCA_015104395.2.mmi reads.fa
## check if reads are sorted by query
$ grep -v '^@' miniprot.output.sam | cut -f1 | uniq | wc -l 
949
$ grep -v '^@' miniprot.output.sam | cut -f1 | sort -u | wc -l 
922
```
I expected the alignments in the SAM output to all be grouped by query but that does not seem to be the case. I tried the `--split-prefix foo` workaround mentioned in #530 but it does not work in my case because I am using `--cs --MD` options. Is there a way to produce query-sorted SAM output file?

**Comment by lh3** [comment]
Increase -I

**Comment by lh3** [comment]
Also, you were probably generating the index using an old version

**Comment by vkkodali** [comment]
Thanks, updating to the newest version did the trick without having to increase `-I`.

**Comment by lh3** [comment]
Good! Thanks for the confirmation.
