### ISSUE TITLE
Alignment circular sequences 

### ISSUE THREAD

**Issue by Macdot3** [lh3/minimap2#1187]
Hello everyone,
I wanted to ask a question about alignment. I'm analyzing circular mtDNA sequences and I was wondering if it's possible for minimap2 to recognize such sequences as circular without any issues of read shifting at the end and beginning once aligned, or even worse, loss of information. It would be very helpful for us working with these sequences. Alternatively, is there a way to overcome this? Thank you very much for any advice.

**Comment by lh3** [comment]
Minimap2 will give two alignments. I am not sure what you mean by loss of information. No plan to support circular sequences.
