### ISSUE TITLE
Inconsistence description about asm5/asm10/asm20

### ISSUE THREAD

**Issue by baozg** [lh3/minimap2#1188]
Hi, 

I just want to confirm which statement about `asm5/asm10/asm20` is true in the help and manual page? `asm5/asm10/asm20` represents the `5/10/20%` divergence estimation or `~0.1/1/5%`.

In the `mminimap2 -h`, the `asm5/asm10/asm20` description is 
```
asm5/asm10/asm20 - asm-to-ref mapping, for ~0.1/1/5% sequence divergence
```

But in the `man ./minimap2.1` or in the https://lh3.github.io/minimap2/minimap2.html, the `asm5/asm10/asm20` description is 
```
asm5	Long assembly to reference mapping (-k19 -w19 -U50,500 --rmq -r100k -g10k -A1 -B19 -O39,81 -E3,1 -s200 -z200 -N50). Typically, the alignment will not extend to regions with 5% or higher sequence divergence. Only use this preset if the average divergence is far below 5%.
asm10	Long assembly to reference mapping (-k19 -w19 -U50,500 --rmq -r100k -g10k -A1 -B9 -O16,41 -E2,1 -s200 -z200 -N50). Up to 10% sequence divergence.
asm20	Long assembly to reference mapping (-k19 -w10 -U50,500 --rmq -r100k -g10k -A1 -B4 -O6,26 -E2,1 -s200 -z200 -N50). Up to 20% sequence divergence.
```

**Comment by lh3** [comment]
See #225

**Comment by baozg** [comment]
Thanks so much! Sorry for the duplicate question. Then I misinterpreted the parameters for long time
