### ISSUE TITLE
Mapping of post-polyA region

### ISSUE THREAD

**Issue by hrun214** [lh3/minimap2#1189]
Hi,

I've been using minimap2 for quite some time now, however I recently ran into a problem with it. We used Oxford Nanopore to sequence a PCR amplicon, which has a polyA-region, followed by ~30 bp at the 3' end of the reference.

A well-known limitation of the sequencing technology is that long homopolymers get shortened, which results in a deletion when aligning against the reference. 

What I've noticed is that the minimap2 preset "map-ont" (and lr:hq) softclips the 30 bp after the "deletion". When using the splice:hq preset, the post-polyA region aligns just fine.

So I wanted to ask if there are parameters for the "map-ont" preset one could adjust to help with the alignment of this region? Alternatively, what are the downsides of using the "splice:hq" preset instead of the "map-ont" one for normal DNA?

Thank you very much.

**Comment by lh3** [comment]
Don't quite understand the problem. Could you provide an example?

**Comment by hrun214** [comment]
Unfortunately I can't share too much, hope this helps.
The amplicon has on it's 3' end a polyA region and is followed by the primer 3' of it. The polyA region is often, by the basecaller, shortened, which creates deletions in the alignment near the 3' end. Because of those deletions, the "map-ont" preset seems to softclip the primer region, although it is clearly in the read. However, the "splice:hq" preset aligns the primer region.

This is how the molecules look like.
5' - [Gene]-[PolyA]-[Primer] - 3'

Below is a coverage plot of the issue. It shows that the alignment stops after the deletion with "map-ont" and with "splice:hq" minimap2 also aligns the primer region after the deletion.
![image](https://github.com/lh3/minimap2/assets/166118974/a01b6de9-d4d1-45e8-add8-995710c9811c)

For downstream analysis, we would like the primer region to not be soft clipped. Is there a downside of using "splice:hq" instead of the "map-ont" preset? Or are there maybe parameters we can adjust to also align the primer region with "map-ont"?

**Comment by lh3** [comment]
Thanks. I understand now. The splice mode doesn't greatly penalize long gaps. It is probably taking the long polyA as an intron. The splice mode may cause false "introns" elsewhere, so it is generally discouraged for genomic alignment. Nonetheless, if you know where your reads should be mapped to. It may be ok to use splice:hq. You might also try `-x lr:hq --end-bonus=30` and see what happens. It probably won't work, though.

**Comment by hrun214** [comment]
Thank you. I have tried modifying the end-bonus, but I'm getting similar results. I think using splice:hq and being aware that it might introduce false "introns" elsewhere, might be the best solution for these kind of samples.
