### ISSUE TITLE
Settings for all-vs-all mapping of Illumina reads

### ISSUE THREAD

**Issue by Marleen1** [lh3/minimap2#119]
Hi,

I am using minimap2 for mapping all-vs-all short paired-end reads (though they could also be considered singles). For this I ran minimap using a variety of settings, and usually each read was mapped with (on average) 4 or 5 other reads for which I can get an overlap score from the paf output file. However, I would like to have overlap scores of many more combinations of reads (even though the scores are low). Setting a lower -s already helps a lot, but I would like to try and get overlap scores for even more pairs if possible. Do you have any experience with what settings would be appropriate in this case?

Thank you!

Marleen

**Comment by lh3** [comment]
Unfortunately, minimap2 doesn't with short read overlapping. Please use dedicated short-read assemblers like sga and fermi instead.
