### ISSUE TITLE
Why -Y parameter makes bam size pretty larger

### ISSUE THREAD

**Issue by leon945945** [lh3/minimap2#1190]
Hi, I aligned two genomes to compare their difference with `minimap2`.

At first, I didn't use `-Y` parameter, and `pbsv` errored with no supporting hard clip reads alignment, the bam file was ~300Mb.
Then, I added the `-Y` parameter, but the bam file changed to ~40Gb, `pbsv` was killed due to the large memory usage.

Why `-Y` parameter makes bam size pretty large? It is interesting.
Thanks very much.

To obtaion the variation information between the two genomes, I prepare to generate paf file with `minimap2` and use paftools to call variation.

**Comment by lh3** [comment]
As the command line help said – it uses soft clippings.
