### ISSUE TITLE
minimap2 crashes w/o informative debugging information

### ISSUE THREAD

**Issue by twang15** [lh3/minimap2#1197]
A related issue: https://github.com/lh3/minimap2/issues/452

I came across a similar situation. The error message is not informative to triage the issue. Any idea how to make it work is appreciated.

Sequencing read dataset: ~700GB.
Minimap2 version: 2.24-r1122

Error message:
[M::worker_pipeline::34878.11423.93] mapped 163343 sequences
[M::worker_pipeline::34926.84823.93] mapped 163089 sequences
[M::worker_pipeline::34976.94623.93] mapped 163340 sequences
[M::worker_pipeline::35023.44423.93] mapped 165103 sequences
[M::worker_pipeline::35040.902*23.93] mapped 70784 sequences
[ERROR] failed to write the results: Input/output error

**Comment by lh3** [comment]
This is a system error (EIO). Probably ask your sysadmin.
