### ISSUE TITLE
ONT cDNA reads with polyA were not aligned to reference

### ISSUE THREAD

**Issue by dudududu12138** [lh3/minimap2#1198]
Hello, I have a ONT cDNA sequenced reads. I trimmed the adapter firstly and then mapped the trimmed reads to hg38 with minimap2. But I saw a very low mapping rate(about 30%). Then I checked the bam file. I noticed that almost all the unmapping reads had large percentage of "A". Just like the print screen below:
![1713776291390](https://github.com/lh3/minimap2/assets/125525648/7b873a61-45cd-46c0-9977-a5e4ae197c19)
So do I need to care about these polyA-rich reads? Thanks!

**Comment by lh3** [comment]
> So do I need to care about these polyA-rich reads?

No

> I saw a very low mapping rate(about 30%)

What matters is the number of bases mapped, not the number of reads mapped.
