### ISSUE TITLE
Question about parameter -uf

### ISSUE THREAD

**Issue by dudududu12138** [lh3/minimap2#1199]
Hello, now I have a Nanopore cDNA sequencing data. And I detected the strands of every reads from the raw data. Then I mapped the reads to hg38 with `minimap2 -ax splice -uf -t 8 $ref $reads >result.sam`. But the strand of some reads are not matched with my detection. For example, this is a read that detected as '-' : `@100:1591|SRR25723945.21919894 9167ca31-862e-4ff7-900e-b2e4da99787b length=1668 strand=-`. But the mapping result reported it as a '+':
![1713788898647](https://github.com/lh3/minimap2/assets/125525648/9b7b00e6-09f2-42f8-ace8-3b0c945dd199)
So which one should I choose from the 3 sets below? My data is neither a direct RNA nor an unknown strand data.
![1713789009557](https://github.com/lh3/minimap2/assets/125525648/240d51cb-2cfb-49ab-93d2-51b819f5686f)

**Comment by lh3** [comment]
The alignment is on the forward strand and the RNA strand is also +. Minimap2 is doing the right thing here.

**Comment by lh3** [comment]
If the strand is unknown, don't use -u
