### ISSUE TITLE
Issue using samtools 1.7 in combination with minimap

### ISSUE THREAD

**Issue by AnjuniPeiris** [lh3/minimap2#120]
Thanks for the great piece of software. We ran into an issue after mapping ONT reads to a reference using the -ax map-ont settings with minimap2 version 2.8-r707-dirty. When using samtools (e.g. sort, stats) on these output files we always get the error [E::sam_parse1] unrecognised CIGAR operator. Not sure why? Any insight?

**Comment by AnjuniPeiris** [comment]
We also checked out tag v2.7 which gives a version 2.8-r711-dirty and this works just fine.

**Comment by lh3** [comment]
r707 is buggy. Sorry for that. "2.8-r711-dirty" is the master, not v2.7. It should work.
