### ISSUE TITLE
just changing from paf to sam causes different alignment

### ISSUE THREAD

**Issue by dgordon562** [lh3/minimap2#1203]
With no other changes than just adding a "-a", the alignment output changes from a single long alignments (in paf format) to 2 alignments with a discrepant region in between (in sam format).

This indicates that different internal code paths are being taken based on the output format.

If someone is maintaining minimap2 and is interested in fixing this, I could supply sample input.

**Comment by lh3** [comment]
See FAQ

**Comment by dgordon562** [comment]
thanks, Heng!
