### ISSUE TITLE
unrecognized type ':' from alignment tags

### ISSUE THREAD

**Issue by chilampoon** [lh3/minimap2#1204]
Hi, following the issue I opened in samtools repo: https://github.com/samtools/samtools/issues/2041#issue-2265995978 

There's a tag from Illumina's CASAVA barcode (e.g. `1:N:0:TAAGATTA+AGCCTGCG`), if it's passed from fastq to sam, it will raise an error `[E::aux_parse] unrecognized type ':'` when I use samtools. 
As James mentioned this could be a minimap2 issue, is it possible to add support to this kind of tag? thank you.

**Comment by lh3** [comment]
Don't use -y.
