### ISSUE TITLE
 difference between plice and splice:hq

### ISSUE THREAD

**Issue by baigal628** [lh3/minimap2#1206]
Hi,

I am trying to know more details of difference between splice and splice:hq mode. What is the criteria of defining high quality long-read? Or it means I can only use this mode for pacbio data. If I have a nanopore data which I think has a better quality. Can I still use splice:hq mode?

Thanks for all the feedback!
Gali

**Comment by lh3** [comment]
You will get better alignment with the right setting. You have to try.
