### ISSUE TITLE
Multiple Primary alignment in PAF

### ISSUE THREAD

**Issue by yanyew** [lh3/minimap2#1208]
Hi!
When I do the mapping between the assembly and reference, it seems that one region from the assembly got multiple primary alignment in the reference. And there were lots of mismatch or gaps in the alignment. Is this normal?
![image](https://github.com/lh3/minimap2/assets/90335707/41902210-8b10-4d8e-a42e-66477fb98868)

**Comment by lh3** [comment]
See FAQ
