### ISSUE TITLE
Unexpected assignment of secondary and supplementary alignments

### ISSUE THREAD

**Issue by zengxiaofei** [lh3/minimap2#1209]
Hi Professor Li, 

I'm using minimap2 to align ONT Pore-C reads to the haplotype-resolved assembly of HG002. But I have observed that some supplementary alignments overlap with the primary alignments (on the read coordinates), while some secondary alignments do not, which is contrary to my expectation. Below is an example, where the primary, secondary, and supplementary alignments are highlighted with yellow, red, and blue rectangles, respectively.

<img width="694" alt="0d69c4c7fa40982b4d16ad6d82b341a" src="https://github.com/lh3/minimap2/assets/22426230/c084f486-86c7-4fe1-9e8d-2cf68eaf44e6">

I'm not sure whether my confusion stems from a misinterpretation of the definitions of supplementary and secondary alignments, or this is an issue related to minimap2.

Minimap2 version: 2.26-r1175

Minimap2 command: `minimap2 -x map-ont HG002.v2.1.fa SRR11589414.fastq.gz SRR11589415.fastq.gz -t 28 -a`

The code for displaying the information for each alignment:

```python
import argparse
import pysam


def parse_bam(bam, threads):

    with pysam.AlignmentFile(bam, mode='rb', threads=threads) as f:
        for aln in f:
            print(aln.query_name, aln.flag, aln.mapq, aln.reference_name, aln.reference_start, aln.query_alignment_start, aln.query_alignment_end)

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('bam', help='input bam file')
    parser.add_argument('--threads', type=int, default=8, help='threads for reading bam, default: %(default)s')
    args = parser.parse_args()

    parse_bam(args.bam, args.threads)

if __name__ == '__main__':
    main()

```

Best regards,
Xiaofei

**Comment by lh3** [comment]
I am not familiar with pysam. Please redo alignment for these few reads and output in the PAF format.

**Comment by zengxiaofei** [comment]
I have found my mistake after outputting alignments in the PAF format.
I forgot to recalculate the coordinates when the reads are reversely mapped. Sorry for taking up your time.
Best,
Xiaofei

**Comment by zengxiaofei** [comment]
Thank you for you suggestion, I'm also trying out that tool.
