### ISSUE TITLE
Scaffolding contigs with ONT reads !

### ISSUE THREAD

**Issue by jnarayan81** [lh3/minimap2#121]
Hi, 
I am working on a scaffolder, and planning to use Minimap2 for alignment/mapping. I used to following command line for alignment:

> minimap2 -x map-ont -k15 -t 10 contigs.fa ONTreads.fq > MMAP2_results.paf

Is there any way to get the "score" for alignments ...   ?

**Comment by lh3** [comment]
Better add `-a` for SAM output:
```sh
minimap2 -ax map-ont -t 10 contigs.fa ONTreads.fq > MMAP2_results.paf
```

> Is there any way to get the "score" for alignments ... ?

I am not sure what score the scaffolder needs. If it is Smith-Waterman alignment score, see the `AS:i:` SAM tag.

**Comment by lh3** [comment]
Just notice that you are "working on a scaffolder". In that case, the [PAF](https://github.com/lh3/miniasm/blob/master/PAF.md) output format is probably preferred because it is smaller and easy to check for long reads. To get PAF with alignment, use `-c` (instead of `-a`) like
```sh
minimap2 -cx map-ont -t 10 contigs.fa ONTreads.fq > MMAP2_results.paf
```

**Comment by jnarayan81** [comment]
I am just wondering, is this possible to keep 'only' ONT reads information in MMAP2_results.paf file that overlaps/connect two or more contigs? I am thinking of this to speed up the scaffolding, and ignore other reads mapped to single contig. Is this feasible?

**Comment by lh3** [comment]
Not possible. What's the size of the genome? How long does it take to map and how long does it take to scaffold?

**Comment by andreaswallberg** [comment]
Hi all!

Did anything come of these efforts?

I've seen quite a bit of useful information in my supplementary alignments of edge reads against multiple contigs, which is consistent with independent evidence such as exon mappings from RNA transcripts. Would be very nice to be able to extract such information from minimap2 mappings and join it with other evidence for scaffolding and maybe even gap filling.

Cheers!
