### ISSUE TITLE
kmst.n_blocks == kmst.n_cores异常

### ISSUE THREAD

**Issue by zhangbaomu** [lh3/minimap2#1210]
您好，我在我的read比对函数中，在一个read精确另一个read非精确时调用了您的collect_minimizers函数和collect_seed_hit函数。在该read比对函数中，我这样声明了km：void *km = my_km_init();，在调用了collect_minimizers和collect_seed_hit后，销毁的时候出现了错误。先前我没有加入断言，而是直接destory，但是在执行几十万条read后会发生段错误。在检验bug时，发现了内存泄露，请问我应该如何解决，谢谢您。销毁km代码如下：
if (km) {
				km_stat(km, &kmst);
				assert(kmst.n_blocks == kmst.n_cores); // otherwise, there is a memory leak
				if (kmst.largest > 1U<<28 ) {
				        km_destroy(km);
				}
			}

**Comment by lh3** [comment]
You need to free up memory allocated via km_malloc()
