### ISSUE TITLE
Minimap2 truncating the alignments if there is a SNP at the start of the gene

### ISSUE THREAD

**Issue by Marysteph** [lh3/minimap2#1211]
Hi Minimap team,

I am using Minimap to align genomes against reference sequence with options: `minimap2 --eqx -c -x `. 
It seems that minimap misses aligning the first codon if there is a SNP at the start position of the gene (ie in the start codon), which gets called as a truncation when it shouldn’t

For example:
391__StrA_AGly__strA.v1__2409:3-804(+), 51:3608-4409 (99.875%).

Any ideas on how I can solve this?

Thanks in advance

**Comment by lh3** [comment]
Try to add --end-bonus=10
