### ISSUE TITLE
different mapping results based on index composition

### ISSUE THREAD

**Issue by tijyojwad** [lh3/minimap2#1218]
Hi,

I'm running the following mm2 command using 2 different indices - 
```
minimap2 -t 96 -K8g -cx ava-ont -k25 -w17 -e200 -r150 -m4000 -z200 --dual=yes index.fastq reads.fastq -Y 
```

case 1 - `index.fastq` has only one read from `reads.fastq` (say `read_1`)
case 2 - `index.fastq` is the same as `reads.fastq` (so `read_1` + many other reads)

I would expect that the generated PAF file would have the same sequences mapped to `read_1` in both scenarios. But I see that in case 1, there are ~140k mappings whereas in case 2, there are _no_ mappings. I check number of mappings by looking at the 6th column in the PAF.

Is this the expected behavior of mm2?

**Comment by lh3** [comment]
Yes, expected. When you have more reads, some k-mers may be dropped due to high occurrence.
