### ISSUE TITLE
[main_samview] fail to read the header from "111.sam".

### ISSUE THREAD

**Issue by Anees-caas** [lh3/minimap2#1220]
I have aligned the Nanopore reads to reference genome command: 
minimap2 -ax map-ont -t 8 /ref ./111.fastq.gz >111.sam
This command generated Sam files. but when I am converting sam to bam 
samtools view -bS 111.sam > 111.bam
I am getting error: fail to read the header from "111.sam".
Please assist to solve this issue, Thanks!

**Comment by Siadjeu** [comment]
Hey, instead of >111.sam, try to run your line code like this: minimap2 -ax map-ont -t 8 /ref ./111.fastq.gz -o 111.sam

**Comment by Anees-caas** [comment]
Hi, idk why I was getting that error, recently I am using this command it worked 
minimap2 -ax map-ont -t 8 /ref/genome.fasta ./fastq.gz | samtools sort -o /sorted.bam

**Comment by Siadjeu** [comment]
Great that you solved it!

**Comment by lh3** [comment]
Thank you for the help, @Siadjeu! I am closing the issue.
