### ISSUE TITLE
minimap2 stuck at Aligning environmental fastq.gz files...step

### ISSUE THREAD

**Issue by lucyintheskyzzz** [lh3/minimap2#1221]
Hi!,
I am using minimap2 to align and exclude my blank sample reads from my environmental samples and it has been running for 16 hours on HPC which has Common Features RedHat Enterprise Linux 8 Operating System 200 Gb/sec (NDR200) InfiniBand
480 CPU Compute Nodes, each with: Two 32-core Intel Ice Lake (Intel® Xeon® Platinum 8358 Processor) CPUs. 256 GB memory
My samples are stuck at aligning the environmental sample to the blank read reference file. 

Attached is my .out file. 
Listing contents of the blank directory:
total 425273472
-rw-r--r-- 1 kvigil tulaneusers 30128269574 Jun  7 12:56 01_dolphin_feces_SQK-NBD114-24_barcode15.fastq
-rw-r--r-- 1 kvigil tulaneusers  9818207302 Jun  7 12:57 02_sealion_feces_SQK-NBD114-24_barcode16.fastq
-rw-r--r-- 1 kvigil tulaneusers   472517966 Jun  7 12:57 03_dolphin_serum_SQK-NBD114-24_barcode17.fastq
-rw-r--r-- 1 kvigil tulaneusers   870899248 Jun  7 12:57 04_sealion_serum_SQK-NBD114-24_barcode18.fastq
-rw-r--r-- 1 kvigil tulaneusers  1395551040 Jun  7 11:59 S02_SQK-NBD114-24_barcode01.fastq
-rw-r--r-- 1 kvigil tulaneusers  2871306588 Jun  7 11:59 S07_SQK-NBD114-24_barcode02.fastq
-rw-r--r-- 1 kvigil tulaneusers  1527857634 Jun  7 12:00 S09_SQK-NBD114-24_barcode03.fastq
-rw-r--r-- 1 kvigil tulaneusers   904021508 Jun  7 12:00 S14_SQK-NBD114-24_barcode04.fastq
-rw-r--r-- 1 kvigil tulaneusers   116304122 Jun  7 12:00 S17_SQK-NBD114-24_barcode05.fastq
-rw-r--r-- 1 kvigil tulaneusers  3423963942 Jun  7 12:00 S19_SQK-NBD114-24_barcode06.fastq
-rw-r--r-- 1 kvigil tulaneusers  5106017216 Jun  7 12:00 S20_SQK-NBD114-24_barcode07.fastq
-rw-r--r-- 1 kvigil tulaneusers    73566748 Jun  5 11:58 S20_d_EXP-NBD104_barcode04.fastq
-rw-r--r-- 1 kvigil tulaneusers    17898242 Jun  5 11:58 S20_r_EXP-NBD104_barcode03.fastq
-rw-r--r-- 1 kvigil tulaneusers   357995464 Jun  7 12:00 S26_SQK-NBD114-24_barcode08.fastq
-rw-r--r-- 1 kvigil tulaneusers   813784636 Jun  7 12:00 S31_SQK-NBD114-24_barcode09.fastq
-rw-r--r-- 1 kvigil tulaneusers   522226160 Jun  7 12:00 S32_SQK-NBD114-24_barcode10.fastq
drwxr-xr-x 2 kvigil tulaneusers       12288 Jun  6 13:24 aligned_sam
drwxr-xr-x 2 kvigil tulaneusers        4096 Jun  9 16:22 blanks
-rw-r--r-- 1 kvigil tulaneusers 52028260162 Jun  9 16:21 blanks_concatenated.fastq
drwxr-xr-x 2 kvigil tulaneusers        4096 Jun  5 14:57 index_reference
drwxr-xr-x 2 kvigil tulaneusers        4096 Jun  6 11:26 logs
-rw-r--r-- 1 kvigil tulaneusers   189704824 Jun  9 13:59 m02_SQK-NBD114-24_barcode01.fastq
-rw-r--r-- 1 kvigil tulaneusers   286204588 Jun  9 13:59 m03_SQK-NBD114-24_barcode02.fastq
-rw-r--r-- 1 kvigil tulaneusers   407889724 Jun  9 13:59 m04_SQK-NBD114-24_barcode03.fastq
-rw-r--r-- 1 kvigil tulaneusers   600796304 Jun  9 13:59 m05_SQK-NBD114-24_barcode04.fastq
-rw-r--r-- 1 kvigil tulaneusers   865651248 Jun  9 13:59 m06_SQK-NBD114-24_barcode05.fastq
-rw-r--r-- 1 kvigil tulaneusers  3076179920 Jun  9 14:00 m07_SQK-NBD114-24_barcode06.fastq
-rw-r--r-- 1 kvigil tulaneusers  2071702556 Jun  9 14:00 m08_SQK-NBD114-24_barcode07.fastq
-rw-r--r-- 1 kvigil tulaneusers   240544194 Jun  9 14:00 m09_SQK-NBD114-24_barcode08.fastq
-rw-r--r-- 1 kvigil tulaneusers   575834572 Jun  9 14:00 m10_SQK-NBD114-24_barcode09.fastq
-rw-r--r-- 1 kvigil tulaneusers  1099928804 Jun  9 14:00 m11_SQK-NBD114-24_barcode10.fastq
-rw-r--r-- 1 kvigil tulaneusers  1817978914 Jun  9 14:00 m12_SQK-NBD114-24_barcode11.fastq
-rw-r--r-- 1 kvigil tulaneusers   462670876 Jun  9 14:00 m13_SQK-NBD114-24_barcode12.fastq
-rw-r--r-- 1 kvigil tulaneusers   993204338 Jun  9 14:00 m14_SQK-NBD114-24_barcode13.fastq
-rw-r--r-- 1 kvigil tulaneusers  1095516076 Jun  9 14:00 m15_SQK-NBD114-24_barcode14.fastq
-rw-r--r-- 1 kvigil tulaneusers   310735300 Jun  9 14:00 m16_SQK-NBD114-24_barcode15.fastq
-rw-r--r-- 1 kvigil tulaneusers  1207132398 Jun  9 14:00 m17_SQK-NBD114-24_barcode16.fastq
-rw-r--r-- 1 kvigil tulaneusers   208062392 Jun  9 14:00 m18_SQK-NBD114-24_barcode17.fastq
-rw-r--r-- 1 kvigil tulaneusers  1770995698 Jun  9 14:00 m19_SQK-NBD114-24_barcode18.fastq
-rw-r--r-- 1 kvigil tulaneusers     7803064 Jun  9 14:00 m20_SQK-NBD114-24_barcode19.fastq
-rw-r--r-- 1 kvigil tulaneusers    11012262 Jun  9 14:00 m21_SQK-NBD114-24_barcode20.fastq
-rw-r--r-- 1 kvigil tulaneusers 10342005798 Jun  7 13:00 m24_SQK-NBD114-24_barcode02.fastq
-rw-r--r-- 1 kvigil tulaneusers  8521889102 Jun  7 13:00 m25_SQK-NBD114-24_barcode03.fastq
-rw-r--r-- 1 kvigil tulaneusers  9098975292 Jun  7 13:01 m26_SQK-NBD114-24_barcode04.fastq
-rw-r--r-- 1 kvigil tulaneusers  5126306450 Jun  7 13:02 m27_SQK-NBD114-24_barcode05.fastq
-rw-r--r-- 1 kvigil tulaneusers  9654490320 Jun  7 13:02 m28_SQK-NBD114-24_barcode06.fastq
-rw-r--r-- 1 kvigil tulaneusers  8682918950 Jun  7 13:03 m29_SQK-NBD114-24_barcode07.fastq
-rw-r--r-- 1 kvigil tulaneusers  2427603982 Jun  7 13:03 m30_SQK-NBD114-24_barcode08.fastq
-rw-r--r-- 1 kvigil tulaneusers 10906868140 Jun  7 13:04 m31_SQK-NBD114-24_barcode09.fastq
-rw-r--r-- 1 kvigil tulaneusers 10592690064 Jun  7 13:05 m32_SQK-NBD114-24_barcode10.fastq
-rw-r--r-- 1 kvigil tulaneusers  9131252116 Jun  7 13:06 m33_SQK-NBD114-24_barcode11.fastq
-rw-r--r-- 1 kvigil tulaneusers  6712465888 Jun  7 13:06 m34_SQK-NBD114-24_barcode12.fastq
-rw-r--r-- 1 kvigil tulaneusers  8232479234 Jun  7 13:07 m35_SQK-NBD114-24_barcode13.fastq
-rw-r--r-- 1 kvigil tulaneusers  2604607294 Jun  7 13:07 m36_SQK-NBD114-24_barcode14.fastq
drwxr-xr-x 2 kvigil tulaneusers       12288 Jun  9 16:33 nanoplot_results
drwxr-xr-x 2 kvigil tulaneusers       16384 Jun  7 07:01 new_fastq
-rw-r--r-- 1 kvigil tulaneusers  3811550484 Jun  9 12:32 oy09_SQK-NBD114-24_barcode01.fastq
-rw-r--r-- 1 kvigil tulaneusers  6425091916 Jun  9 12:32 oy10_SQK-NBD114-24_barcode02.fastq
-rw-r--r-- 1 kvigil tulaneusers  4307035560 Jun  9 12:33 oy11_SQK-NBD114-24_barcode03.fastq
-rw-r--r-- 1 kvigil tulaneusers  5685218792 Jun  9 12:33 oy12_SQK-NBD114-24_barcode04.fastq
-rw-r--r-- 1 kvigil tulaneusers  7357366414 Jun  9 12:33 oy13_SQK-NBD114-24_barcode05.fastq
-rw-r--r-- 1 kvigil tulaneusers   122718020 Jun  9 12:33 oy14_SQK-NBD114-24_barcode06.fastq
-rw-r--r-- 1 kvigil tulaneusers  4230164658 Jun  9 12:33 oy15_SQK-NBD114-24_barcode07.fastq
-rw-r--r-- 1 kvigil tulaneusers    58225140 Jun  9 12:33 oy16_SQK-NBD114-24_barcode08.fastq
-rw-r--r-- 1 kvigil tulaneusers  3441904666 Jun  9 12:33 oy20_SQK-NBD114-24_barcode09.fastq
-rw-r--r-- 1 kvigil tulaneusers  5318802142 Jun  9 12:33 oy21_SQK-NBD114-24_barcode10.fastq
-rw-r--r-- 1 kvigil tulaneusers  6381726040 Jun  9 12:33 oy22_SQK-NBD114-24_barcode11.fastq
-rw-r--r-- 1 kvigil tulaneusers  4313283572 Jun  9 12:33 oy23_SQK-NBD114-24_barcode12.fastq
-rw-r--r-- 1 kvigil tulaneusers  5665357730 Jun  9 12:34 oy24_SQK-NBD114-24_barcode13.fastq
-rw-r--r-- 1 kvigil tulaneusers  5294686412 Jun  9 12:34 oy25_SQK-NBD114-24_barcode14.fastq
-rw-r--r-- 1 kvigil tulaneusers  4123084522 Jun  9 12:34 oy26_SQK-NBD114-24_barcode15.fastq
-rw-r--r-- 1 kvigil tulaneusers  3528760104 Jun  9 12:34 oy27_SQK-NBD114-24_barcode16.fastq
-rw-r--r-- 1 kvigil tulaneusers  1794831530 Jun  9 12:34 oy31_SQK-NBD114-24_barcode17.fastq
-rw-r--r-- 1 kvigil tulaneusers  3627762318 Jun  9 12:34 oy32_SQK-NBD114-24_barcode18.fastq
-rw-r--r-- 1 kvigil tulaneusers  7240912460 Jun  9 12:34 oy33_SQK-NBD114-24_barcode19.fastq
-rw-r--r-- 1 kvigil tulaneusers  8390860864 Jun  9 12:34 oy34_SQK-NBD114-24_barcode20.fastq
-rw-r--r-- 1 kvigil tulaneusers  8219989748 Jun  9 12:35 oy35_SQK-NBD114-24_barcode21.fastq
-rw-r--r-- 1 kvigil tulaneusers  9394862366 Jun  9 12:35 oy36_SQK-NBD114-24_barcode22.fastq
-rw-r--r-- 1 kvigil tulaneusers  9402834734 Jun  9 12:35 oy37_SQK-NBD114-24_barcode23.fastq
-rw-r--r-- 1 kvigil tulaneusers  2803867492 Jun  9 12:35 oy38_SQK-NBD114-24_barcode24.fastq
-rw-r--r-- 1 kvigil tulaneusers  5703555838 Jun  9 12:32 oy41_SQK-NBD114-24_barcode01.fastq
-rw-r--r-- 1 kvigil tulaneusers  4762818800 Jun  9 12:32 oy42_SQK-NBD114-24_barcode02.fastq
-rw-r--r-- 1 kvigil tulaneusers  1353724262 Jun  9 12:32 oy43_SQK-NBD114-24_barcode03.fastq
-rw-r--r-- 1 kvigil tulaneusers  1338356786 Jun  9 12:32 oy44_SQK-NBD114-24_barcode04.fastq
-rw-r--r-- 1 kvigil tulaneusers  4397433960 Jun  9 12:33 oy45_SQK-NBD114-24_barcode05.fastq
-rw-r--r-- 1 kvigil tulaneusers  1209362478 Jun  9 12:33 oy46_SQK-NBD114-24_barcode06.fastq
-rw-r--r-- 1 kvigil tulaneusers  2031801934 Jun  9 12:33 oy47_SQK-NBD114-24_barcode07.fastq
-rw-r--r-- 1 kvigil tulaneusers    53030968 Jun  9 12:33 oy49_SQK-NBD114-24_barcode08.fastq
-rw-r--r-- 1 kvigil tulaneusers  4316599776 Jun  9 12:33 oy50_SQK-NBD114-24_barcode09.fastq
-rw-r--r-- 1 kvigil tulaneusers  2809970864 Jun  9 12:33 oy51_SQK-NBD114-24_barcode10.fastq
-rw-r--r-- 1 kvigil tulaneusers  3517008870 Jun  9 12:34 oy52_SQK-NBD114-24_barcode11.fastq
-rw-r--r-- 1 kvigil tulaneusers  2977249104 Jun  9 12:34 oy53_SQK-NBD114-24_barcode12.fastq
-rw-r--r-- 1 kvigil tulaneusers  2203664334 Jun  9 12:34 oy54_SQK-NBD114-24_barcode13.fastq
-rw-r--r-- 1 kvigil tulaneusers  3346609298 Jun  9 12:34 oy55_SQK-NBD114-24_barcode14.fastq
-rw-r--r-- 1 kvigil tulaneusers  1835134494 Jun  9 12:35 oy56_SQK-NBD114-24_barcode15.fastq
-rw-r--r-- 1 kvigil tulaneusers  1639621382 Jun  9 12:35 oy58_SQK-NBD114-24_barcode16.fastq
-rw-r--r-- 1 kvigil tulaneusers  2597320916 Jun  9 12:35 oy59_SQK-NBD114-24_barcode17.fastq
-rw-r--r-- 1 kvigil tulaneusers  1504602404 Jun  9 12:35 oy60_SQK-NBD114-24_barcode18.fastq
-rw-r--r-- 1 kvigil tulaneusers  1452573310 Jun  9 12:35 oy61_SQK-NBD114-24_barcode19.fastq
-rw-r--r-- 1 kvigil tulaneusers  4745460366 Jun  9 12:36 oy62_SQK-NBD114-24_barcode20.fastq
-rw-r--r-- 1 kvigil tulaneusers  6490086140 Jun  9 12:36 oy63_SQK-NBD114-24_barcode21.fastq
-rw-r--r-- 1 kvigil tulaneusers  6489622796 Jun  9 12:37 oy64_SQK-NBD114-24_barcode22.fastq
-rw-r--r-- 1 kvigil tulaneusers  4972334978 Jun  7 13:07 sd1_SQK-NBD114-24_barcode16.fastq
-rw-r--r-- 1 kvigil tulaneusers  5769429638 Jun  7 13:08 sd2_SQK-NBD114-24_barcode17.fastq
-rw-r--r-- 1 kvigil tulaneusers   533350164 Jun  7 13:08 sd3_SQK-NBD114-24_barcode18.fastq
-rw-r--r-- 1 kvigil tulaneusers  6089660246 Jun  7 13:08 sd4_SQK-NBD114-24_barcode19.fastq
-rw-r--r-- 1 kvigil tulaneusers   249081704 Jun  7 13:09 sd5_SQK-NBD114-24_barcode20.fastq
-rw-r--r-- 1 kvigil tulaneusers   366271152 Jun  7 13:09 sd6_SQK-NBD114-24_barcode21.fastq
drwxr-xr-x 2 kvigil tulaneusers        4096 Jun  5 14:12 tmp
Creating index reference file...
Aligning environmental fastq.gz files...

Below is my code:
#!/bin/bash
#SBATCH --job-name=blankfilter_onr.test
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=64
#SBATCH --mem=128G  # Adjust this based on available resources and your system's capabilities
#SBATCH --time=1-00:00:00
#SBATCH --output=slurm-%j.out-%N
#SBATCH --error=slurm-%j.err-%N
#SBATCH -A loni_admintest0    ### Allocation name
#SBATCH --partition=single           # the partition

# Path to minimap2 executable
MINIMAP2=/work/kvigil/Programs/minimap2/minimap2

# Path to your blank fastq files directory
BLANK_DIR=/ddnB/work/kvigil/onr.raw.data.sup.trim

# Path to your environmental fastq files directory
ENVIRONMENTAL_DIR=/ddnB/work/kvigil/onr.raw.data.sup.trim

# Path to store index reference file
INDEX_REF=/ddnB/work/kvigil/onr.raw.data.sup/index_reference

# Path to store aligned sam files
ALIGNED_SAM_DIR=/ddnB/work/kvigil/onr.raw.data.sup/aligned_sam/

# Path to store new fastq.gz files without sequences aligned with blank
NEW_FASTQ_DIR=/ddnB/work/kvigil/onr.raw.data.sup/new_fastq/

# Path to store temporary files
TMP_DIR=/ddnB/work/kvigil/onr.raw.data.sup/tmp

# Path to store minimap2 log files
LOG_DIR=/ddnB/work/kvigil/onr.raw.data.sup/logs

# Create necessary directories if they don't exist
mkdir -p $ALIGNED_SAM_DIR $NEW_FASTQ_DIR $TMP_DIR $LOG_DIR

# Print the directory content for debugging
echo "Listing contents of the blank directory:"
ls -l $BLANK_DIR

# Checkpoint 1: Check if index reference file exists
if [ ! -f "${INDEX_REF}.idx" ]; then
    echo "Creating index reference file..."
    $MINIMAP2 -d $INDEX_REF --split-prefix $INDEX_REF.idx $BLANK_DIR/blanks_concatenated.fastq 2> $LOG_DIR/index_reference.log
    if [ $? -ne 0 ]; then
        echo "Error: Failed to create index reference file. Check $LOG_DIR/index_reference.log for details."
        exit 1
    fi
else
    echo "Index reference file already exists."
fi

# Checkpoint 2: Check if aligned sam files exist
if [ ! -f "${ALIGNED_SAM_DIR}merged_aligned.sam" ]; then
    echo "Aligning environmental fastq.gz files..."
    for file in $ENVIRONMENTAL_DIR/*.fastq; do
        filename=$(basename "$file" .fastq)
        $MINIMAP2 -a $INDEX_REF $file > "${ALIGNED_SAM_DIR}${filename}_aligned.sam" 2> "${LOG_DIR}${filename}_alignment.log"
        if [ $? -ne 0 ]; then
            echo "Error: Alignment failed for $file. Check ${LOG_DIR}${filename}_alignment.log for details."
            exit 1
        fi
    done

    echo "Combining aligned sam files..."
    cat ${ALIGNED_SAM_DIR}*_aligned.sam > ${ALIGNED_SAM_DIR}merged_aligned.sam
else
    echo "Aligned sam files already exist."
fi

# Checkpoint 3: Check if new fastq.gz files without blank exist
if [ ! -f "${NEW_FASTQ_DIR}merged_without_blank.fastq" ]; then
    echo "Extracting read IDs aligned with blank..."
    awk '{if($3=="*")print$1}' ${ALIGNED_SAM_DIR}merged_aligned.sam > ${ALIGNED_SAM_DIR}aligned_with_blank.txt

    echo "Excluding sequences aligned with blank from environmental fastq.gz files..."
    for file in $ENVIRONMENTAL_DIR/*.fastq; do
        filename=$(basename "$file" .fastq)
        grep -Fvf ${ALIGNED_SAM_DIR}aligned_with_blank.txt $file > "${NEW_FASTQ_DIR}${filename}_without_blank.fastq"
    done

    echo "Combining new fastq files into a single file..."
    cat ${NEW_FASTQ_DIR}*_without_blank.fastq > ${NEW_FASTQ_DIR}merged_without_blank.fastq

    echo "Compressing the new combined fastq file..."
    gzip ${NEW_FASTQ_DIR}merged_without_blank.fastq

    echo "Cleaning up temporary files..."
    rm ${ALIGNED_SAM_DIR}merged_aligned.sam ${ALIGNED_SAM_DIR}aligned_with_blank.txt
else
    echo "New fastq files without blank already exist."
fi

# Verification step: Ensure blank sequences are excluded
echo "Verifying exclusion of blank sequences..."
verification_log="${NEW_FASTQ_DIR}verification_log.txt"
touch $verification_log

for file in ${NEW_FASTQ_DIR}*_without_blank.fastq; do
    grep -F "$(cat ${ALIGNED_SAM_DIR}aligned_with_blank.txt)" $file > ${TMP_DIR}sequences_from_blank.txt

    if [ -s ${TMP_DIR}sequences_from_blank.txt ]; then
        echo "Error: Sequences from blank found in $file" >> $verification_log
    else
        echo "No sequences from blank found in $file" >> $verification_log
    fi
done

echo "Verification log:"
cat $verification_log

echo "Script completed successfully."

**Comment by lh3** [comment]
Please narrow the problem to a specific step.

**Comment by lucyintheskyzzz** [comment]
Hi, It looks like minimap2 is asking for allot of memory and crashes. Attached are my logs.

.out log
Memory usage before starting the job:
              total        used        free      shared  buff/cache   available
Mem:          2.0Ti       6.2Gi       1.9Ti       1.0Gi        25Gi       2.0Ti
Swap:         2.2Ti       2.0Mi       2.2Ti
Listing contents of the blank directory:
total 38365368
-rw-r--r-- 1 kvigil tulaneusers 39286127302 Jun 20 11:32 blanks_concatenated.fastq
Creating index reference file...
Aligned sam files already exist.
New fastq files without blank already exist.
Verifying exclusion of blank sequences...

error log:
/var/spool/slurm/d/job16163/slurm_script: xrealloc: cannot allocate 18446744071562067968 bytes

Below is my script:

#!/bin/bash
#SBATCH -J blankfilter_onr.test
#SBATCH -N 1
#SBATCH -n 1
#SBATCH -c 64
#SBATCH --mem-per-cpu=27G # Adjust based on observed memory usage (866 GB / 32 cores = 27 GB per core)
#SBATCH -t 3-00:00:00
#SBATCH -o slurm-%j.out-%N
#SBATCH -e slurm-%j.err-%N
#SBATCH -A loni_admintest0
#SBATCH -p bigmem

echo "Memory usage before starting the job:"
free -h

# Load required modules
#module load minimap2

# Define paths
MINIMAP2=/work/kvigil/Programs/minimap2/minimap2
BLANK_DIR=/ddnB/work/kvigil/onr.raw.data.sup.trim/rawdata/results/trimmed/blanks
ENVIRONMENTAL_DIR=/ddnB/work/kvigil/onr.raw.data.sup.trim/rawdata/results/trimmed/sd_marinemammal
INDEX_REF=/ddnB/work/kvigil/onr.raw.data.sup.trim/rawdata/index_reference
ALIGNED_SAM_DIR=/ddnB/work/kvigil/onr.raw.data.sup.trim/rawdata/aligned_sam/
NEW_FASTQ_DIR=/ddnB/work/kvigil/onr.raw.data.sup.trim/rawdata/minimap2_fastq/
TMP_DIR=/ddnB/work/kvigil/onr.raw.data.sup.trim/rawdata/tmp
LOG_DIR=/ddnB/work/kvigil/onr.raw.data.sup.trim/rawdata/logs

# Create necessary directories if they don't exist
mkdir -p $ALIGNED_SAM_DIR $NEW_FASTQ_DIR $TMP_DIR $LOG_DIR

echo "Listing contents of the blank directory:"
ls -l $BLANK_DIR

# Function to check command success and log errors
check_command() {
    if [ $? -ne 0 ]; then
        echo "Error: $1"
        exit 1
    fi
}

# Step 1: Create index reference if it doesn't exist
if [ ! -f "${INDEX_REF}.idx" ]; then
    echo "Creating index reference file..."
    $MINIMAP2 -d $INDEX_REF -x map-ont --split-prefix $INDEX_REF.idx $BLANK_DIR/blanks_concatenated.fastq 2> $LOG_DIR/index_reference.log
    check_command "Failed to create index reference file. Check $LOG_DIR/index_reference.log for details."
else
    echo "Index reference file already exists."
fi

# Step 2: Align environmental fastq.gz files if merged_aligned.sam doesn't exist
if [ ! -f "${ALIGNED_SAM_DIR}merged_aligned.sam" ]; then
    echo "Aligning environmental fastq.gz files..."
    for file in $ENVIRONMENTAL_DIR/*.fastq; do
        filename=$(basename "$file" .fastq)
        aligned_sam="${ALIGNED_SAM_DIR}${filename}_aligned.sam"

        if [ -f "$aligned_sam" ]; then
            echo "Skipping $file as $aligned_sam already exists."
            continue
        fi

        $MINIMAP2 -t 4 -K 5M -a $INDEX_REF $file > "$aligned_sam" 2> "${LOG_DIR}${filename}_alignment.log"
        check_command "Alignment failed for $file. Check ${LOG_DIR}${filename}_alignment.log for details."
    done

    echo "Combining aligned sam files..."
    cat ${ALIGNED_SAM_DIR}*_aligned.sam > ${ALIGNED_SAM_DIR}merged_aligned.sam
else
    echo "Aligned sam files already exist."
fi

# Step 3: Extract and filter reads without blank sequences if merged_without_blank.fastq.gz doesn't exist
if [ ! -f "${NEW_FASTQ_DIR}merged_without_blank.fastq.gz" ]; then
    echo "Extracting read IDs aligned with blank..."
    awk '{if($3=="*")print$1}' ${ALIGNED_SAM_DIR}merged_aligned.sam > ${ALIGNED_SAM_DIR}aligned_with_blank.txt

    echo "Excluding sequences aligned with blank from environmental fastq.gz files..."
    for file in $ENVIRONMENTAL_DIR/*.fastq; do
        filename=$(basename "$file" .fastq)
        output_file="${NEW_FASTQ_DIR}${filename}_without_blank.fastq"

        if [ -f "$output_file" ]; then
            echo "Skipping $file as $output_file already exists."
            continue
        fi

        grep -Fvf ${ALIGNED_SAM_DIR}aligned_with_blank.txt $file > "$output_file"
    done

    echo "Combining new fastq files into a single file..."
    cat ${NEW_FASTQ_DIR}*_without_blank.fastq > ${NEW_FASTQ_DIR}merged_without_blank.fastq

    echo "Compressing the new combined fastq file..."
    gzip ${NEW_FASTQ_DIR}merged_without_blank.fastq

    echo "Cleaning up temporary files..."
    rm ${ALIGNED_SAM_DIR}merged_aligned.sam ${ALIGNED_SAM_DIR}aligned_with_blank.txt
else
    echo "New fastq files without blank already exist."
fi

# Step 4: Verify exclusion of blank sequences
echo "Verifying exclusion of blank sequences..."
verification_log="${NEW_FASTQ_DIR}verification_log.txt"
touch $verification_log

for file in ${NEW_FASTQ_DIR}*_without_blank.fastq; do
    grep -F "$(cat ${ALIGNED_SAM_DIR}aligned_with_blank.txt)" $file > ${TMP_DIR}sequences_from_blank.txt

    if [ -s ${TMP_DIR}sequences_from_blank.txt ]; then
        echo "Error: Sequences from blank found in $file" >> $verification_log
    else
        echo "No sequences from blank found in $file" >> $verification_log
    fi
done

echo "Verification log:"
cat $verification_log

echo "Script completed successfully."

echo "Memory usage after completing the job:"
free -h

**Comment by lucyintheskyzzz** [comment]
[verification_log.txt](https://github.com/user-attachments/files/15941952/verification_log.txt)
[index_reference.log](https://github.com/user-attachments/files/15941953/index_reference.log)
