### ISSUE TITLE
How to classify hifi reads into haplotype genomes? minimap2 did not work well

### ISSUE THREAD

**Issue by DayTimeMouse** [lh3/minimap2#1222]
Hi,

I used HiFi + ONT + HiC reads to assemble haplotype genomes, then I want to classfiy hifi reads into haplotype genomes separately.

I have tried to use minimap2, due to the similar haplotype genomes, it did not work well.

I cat hap1 and hap2 into hap1_hap2.fa, use "minimap2(2.27-r1193) -c --secondary=no hap1_hap2.fa hifi.fastq.gz >aln.paf",
then use reads ID from paf file to calculate the precision, only ~0.56. The HiFi reads were simulated, so I know the reads ID real belong to which haplotype.

Do you have ideas for this?

Best wishes.

**Comment by lh3** [comment]
Either the assembly is highly homozygous or the simulation is problematic.
