### ISSUE TITLE
Alternative gap introduced when comparing insertion/deletion results between minimap2 and STAR2

### ISSUE THREAD

**Issue by huangyizR** [lh3/minimap2#1224]
Hi,
When I tried to match the insertion/deletion (INDEL) events between 1) RNA-seq reads aligned by STAR2 against human reference genome hg38. 2) RNA-seq reads aligned by minimap against transcript sequences (gencode v36), I noticed that it's hard to match those indel events by genomic position. After inspected the aligned reads, I noticed that STAR2 and minimap2 introduced the gap for INDEL at different positions:

```
#Alignment: (by minimap2)
#Reference:  GCTACATGGC-TTTTTTGACGTATGACGAAGTGAAAGC
#Query:      GCTACATGGCTTTTTTTGACGTATGACGAAGTGAAAGC

#Alignment: (by STAR2)
#Reference:  GCTACATGGCTTTTTT-GACGTATGACGAAGTGAAAGC 
#Query:      GCTACATGGCTTTTTTTGACGTATGACGAAGTGAAAGC
```

The results affect the downstream analysis, for example, after called the variants follower by annotation, it would report different positions of the INDEL:
![Screen Shot 2024-06-18 at 5 31 47 PM](https://github.com/lh3/minimap2/assets/34176128/a97f5ae6-3ba1-4e47-9913-db9b986be0fb)

Are there any parameters in minimap2 that I can tweak to solve this issue? Thanks!

**Comment by huangyizR** [comment]
@lh3 Hi Dr. Li, I noticed that ksw2 library "supports fixed banding and optionally produces alignment paths (i.e. CIGARs) with gaps either left- or right-aligned. ". This maybe what I am looking for. Are there such flag in minimap2 that allow user to force the placement of INDEL to left or right? Thanks!

**Comment by lh3** [comment]
No, that sentence means initiating alignment from right to left. Gaps are always left aligned, which is the de facto standard in variant calling.
