### ISSUE TITLE
lr:hq for Dorado SUP?

### ISSUE THREAD

**Issue by weishwu** [lh3/minimap2#1225]
I basecalled my ONT sequencing data using Dorado v0.7 with the latest SUP model. However, the average base quality is below 20. I wonder whether I should use the `lr:hq` or the `map-ont` preset. Thanks.

**Comment by lh3** [comment]
Usually map-ont doesn't hurt except performance.

**Comment by weishwu** [comment]
@lh3 Thanks! I'll stick with `map-ont` then.

**Comment by lucyintheskyzzz** [comment]
@weishwu how are you running your sup fastq files on minimap? I am running into memory issues did you experience this as well?

**Comment by lucyintheskyzzz** [comment]
Hi! I ended up fixing my memory issue and updated my script. 
[minimap2_blankfilter.v3.txt](https://github.com/user-attachments/files/16014615/minimap2_blankfilter.v3.txt)

I was trying to align my blank (negative control) samples to all my environmental samples then filtering out the blanks.
