### ISSUE TITLE
wrong .fastq file output format

### ISSUE THREAD

**Issue by lucyintheskyzzz** [lh3/minimap2#1227]
Hi I was able to align my samples using Minimap2, but all my output .fastq files are in the wrong format now and will not run on Diamond. I basically sequenced some blank samples and aligned them against my environmental samples using minimap2 then my output was supposed to be a new .fastq file without any of the blank contamination reads in my samples, but the .fastq files are now in the incorrect format.

[minimap2_blankfilter.v3.txt](https://github.com/user-attachments/files/16167887/minimap2_blankfilter.v3.txt)

Attached is my minimap2 code. 

It looks like minimap chopped away the read "@" name @ad22310b-780e-45ca-ad73-3d8fec2f55c6

See below an example of one of my .fastq files:

fastq file before minimap2 filter:

(nanoplot-env) [kvigil@qbd2 sd_seawater]$ head sd6_SQK-NBD114-24_barcode21.fastq
@ad22310b-780e-45ca-ad73-3d8fec2f55c6
TGTTACTGGTTCGTTACGTATTGCTAAGGTTAAGAGCCTCTCATTGTCTAGGTACCAGCACCTGTTTCCCAGTCACGATCATTCTGTTTCTATATCAAATACTAACTGCATTAAAATAATTCATCTAAGGTTTCATCAAATTCTATATCTTTATCAGATACTTCAGACAGTCTACCTGTTTCTGAATCATATACAACACTACATGCCATTCCAACATCGCCTGTATATCTCGATTTAAGAACACGTAGTCTAGTTGTCCTTGCTTCTTCAGCATCATCTGATTGTTGGTTTCTTTCTAATGCTATGACACAATCACTAAGTTGTCCGATACTATTAGAACCTCTAAGATGAGATAGAGAAACCTCTATACCATTCTCATGTCCTTTGTTACCATCAACTCTACGTAAGTGTGAAACTAAAATGATACCTGCACCTGTTTCTTCTACTAAACTTTTAAGCCTAGTCATAATAGAATCAATAGCTCTTCTCTCATCTCCTTCATGGACAGCACTAACTAACATATGTAAATGGTCTACTATCACCCACTTGCAGTCGCACCCTATAATCATAAAGCGAAGCTTAGTAAAGATATCATCTATGTCATTGGATCCAAAGATCGTGACTGGGAAACAGGTGCTGTAAAGCAGCAATGAGAGGCTCTTAACCTTAGCAATACG
+
$$'(((),''''6?BACEGEHSMLJJLD@@AAAACCB>;<;<?74,'&$$%%%''(+,/1-'(&'-001,,,,.43///004--ABCEGKSPMKRSRSPJPNISIGIKJL<<?C..422346=??@?AF=<<<;@>==@@GKSPJKSOSLNMMMSKNOOSKSILPSKSMQIGSPISGFGGEEJ::9.((()DFFGLSJKEHKJSNSLPOOOSOLLPJMSOJPS<;;<<HKKQHJSILLLMLHJSJSSLKSNJMPJHEEEGIIDAAABFFDEJMILSNSOSOSROMKMSMSRONRSLNKLNSJSNSJSRJJMSSJONNMSSRSSQMSLMSQOPORKOQISCHMHIA@@::9:;LPKNSSQLJJIJKBF9:AABPIMPKPSSSLONNLMECCCDEKLOMLNMMOKOOPSONSHKLLPNNSSSSKMMSKKKSNSSSLRPLKMLMSQNG:,+++,GEDEFDDBCA@C;999:98760///**)())0/00AJLHHQKKHHIKHJHKJJQSSSJMSLMKSSSSKSOSKOJSOPSLKJKRHIJFFHFABDGHFDEEGNIEBCCEEJNMKNMSSOIIJSSS???@AGMIIJIFLIIFEGFC=><>??@PKJHMKIIJFAA?BCDEGDEFE:97678?@@?)&&&.///---&%%%%%%&&'(&'/22('((((+(
@7854a4c8-5e7c-48f4-87c6-c1dfde4641f6
TATGTTTTATTTTATTCGTTCAGTTACGTATTGCTAAGGTTAAGAGCCTCTCATTGTCCGTTCTCTACAGCACCTGTTTCCCAGTCACGATCCACGTTGTGGATCTGGGCGAGATTCTGACTTAGAGGCGTTCAGTCATAATCCCTGCGGATCGGTAGCTTCGCACCATTGGCTTATGAGCCAAGCACATAAACCAAATGTCTGAACCTGCGGTTCCTCTCGTACTGAGCAGGATTACCGTTGCAACGACTGCAGTCATCAGTAGGGTAAAACTAACCTGTCTCACGACGGTCTAAACCCAGCTCACGTTCCCTATTACGATCGTGACTGGGAAACAGGTGCTGTAGAGAACGGACAATGAGAGGCTCTTAACCTTAGCGATACG
+
%$$$###$##$&&%+++/9:https://github.com/abb@A@@=??>>?BCBFHGGHFGHLIPQLJMKJNIRMKLHNLSSIFFIIMKIIQPILMSPIIKIJRMNHLQJSLKKRONKJKONKG?88><9?A?B>>>>??>??JQJMPGHKMKSMKGKDE96'&%%%&)1112:>>?BCFIGGNNLJKIEJLS77778LNRSJIJNHJIHGDILQMJLRNRMLKSSOLSSLSKPLLKHPMSPFNGGFIFDCACBDCEDCEGGGEE@@@@@SGMIOJIGGIHHLIMGQNSSOHKIHLMHKNLSSSLJJLSHPIHHJHISPSPIJGIHJHJNGINIFFIGJGFHGGFIMGGMJLISGFEFJHJJKFEDECDDFEEIJJGFFDDDHFEGEDFGDC877.--++)
@4c2947d0-5cec-4fa0-bdc3-3ab10f7522d9
GTGTTATGTCTTAACCTACTCGTTCAGTTACGTATTGCTAAGGTTAAGAGCCTCTCATTGTCCGTTCTCTACAGCACCTGTTTCCCAGTCACGATCAAGATCGCAATTAAGCAGACAAATCACTCCACCAACTAAGAACGGCCATGCACCACCACCCACAAAATCAAGAAAGAGCTCTCAATCTGTCAATCCTACTTGTGTCTGGACCTGGTGAGTTTCCCCGTGTTGGGTCAAATTAAGCCGCGGGCTCCACGCCTGGTGGTGCCCTTCCGTCAATTTCTTTAAGTTTCAGCCTTGCGACCATACTCCCCCCAGAACCCAAAAACTTTGATTTCTCGTAAGGTGCCGATGGGGTCAAAACAATAACACCCACCGATCCCTAGTCGGCATAGTTTATGGTTAAGACTACGACGGTATCTGACCGTCTTCGATTCCCTAACTTTCGTTCACTGATTAATGAAAACATCCTTGGCAAATGCTTTCGCAGTAGTTTGTCTTCAATAAATCAGTGAACGAATCTCGGGGATGATAGGACTGGGAAACAGGTGCTGTAGAGAACGGACAATGAGAGGCTCTTAACCTTAGCAATTGGTA

fastq file after minimap2 filter:
(nanoplot-env) [kvigil@qbd2 minimap2_fastq]$ head sd6_SQK-NBD114-24_barcode21_without_blank.fastq
TGTTACTGGTTCGTTACGTATTGCTAAGGTTAAGAGCCTCTCATTGTCTAGGTACCAGCACCTGTTTCCCAGTCACGATCATTCTGTTTCTATATCAAATACTAACTGCATTAAAATAATTCATCTAAGGTTTCATCAAATTCTATATCTTTATCAGATACTTCAGACAGTCTACCTGTTTCTGAATCATATACAACACTACATGCCATTCCAACATCGCCTGTATATCTCGATTTAAGAACACGTAGTCTAGTTGTCCTTGCTTCTTCAGCATCATCTGATTGTTGGTTTCTTTCTAATGCTATGACACAATCACTAAGTTGTCCGATACTATTAGAACCTCTAAGATGAGATAGAGAAACCTCTATACCATTCTCATGTCCTTTGTTACCATCAACTCTACGTAAGTGTGAAACTAAAATGATACCTGCACCTGTTTCTTCTACTAAACTTTTAAGCCTAGTCATAATAGAATCAATAGCTCTTCTCTCATCTCCTTCATGGACAGCACTAACTAACATATGTAAATGGTCTACTATCACCCACTTGCAGTCGCACCCTATAATCATAAAGCGAAGCTTAGTAAAGATATCATCTATGTCATTGGATCCAAAGATCGTGACTGGGAAACAGGTGCTGTAAAGCAGCAATGAGAGGCTCTTAACCTTAGCAATACG
+
$$'(((),''''6?BACEGEHSMLJJLD@@AAAACCB>;<;==@@GKSPJKSOSLNMMMSKNOOSKSILPSKSMQIGSPISGFGGEEJ::9.((()DFFGLSJKEHKJSNSLPOOOSOLLPJMSOJPS<;;<<>??@PKJHMKIIJFAA?BCDEGDEFE:97678?@@?)&&&.///---&%%%%%%&&'(&'*/22('((((+*( TATGTTTTATTTTATTCGTTCAGTTACGTATTGCTAAGGTTAAGAGCCTCTCATTGTCCGTTCTCTACAGCACCTGTTTCCCAGTCACGATCCACGTTGTGGATCTGGGCGAGATTCTGACTTAGAGGCGTTCAGTCATAATCCCTGCGGATCGGTAGCTTCGCACCATTGGCTTATGAGCCAAGCACATAAACCAAATGTCTGAACCTGCGGTTCCTCTCGTACTGAGCAGGATTACCGTTGCAACGACTGCAGTCATCAGTAGGGTAAAACTAACCTGTCTCACGACGGTCTAAACCCAGCTCACGTTCCCTATTACGATCGTGACTGGGAAACAGGTGCTGTAGAGAACGGACAATGAGAGGCTCTTAACCTTAGCGATACG + %$$$###$##$&&%*+++/9:https://github.com/abb@A@@=??>>?BCBFHGGHFGHLIPQLJMKJNIRMKLHNLSSIFFIIMKIIQPILMSPIIKIJRMNHLQJSLKKRONKJKONKG?88><9?A?B>>>>??>??JQJMPGHKMKSMKGKDE96'&%%%&)1112:>>?BCFIGGNNLJKIEJLS77778LNRSJIJNHJIHGDILQMJLRNRMLKSSOLSSLSKPLLKHPMSPFNGGFIFDCACBDCEDCEGGGEE@@@@@SGMIOJIGGIHHLIMGQNSSOHKIHLMHKNLSSSLJJLSHPIHHJHISPSPIJGIHJHJNGINIFFIGJGFHGGFIMGGMJLISGFEFJHJJKFEDECDDFEEIJJGFFDDDHFEGEDFGDC877.--++) GTGTTATGTCTTAACCTACTCGTTCAGTTACGTATTGCTAAGGTTAAGAGCCTCTCATTGTCCGTTCTCTACAGCACCTGTTTCCCAGTCACGATCAAGATCGCAATTAAGCAGACAAATCACTCCACCAACTAAGAACGGCCATGCACCACCACCCACAAAATCAAGAAAGAGCTCTCAATCTGTCAATCCTACTTGTGTCTGGACCTGGTGAGTTTCCCCGTGTTGGGTCAAATTAAGCCGCGGGCTCCACGCCTGGTGGTGCCCTTCCGTCAATTTCTTTAAGTTTCAGCCTTGCGACCATACTCCCCCCAGAACCCAAAAACTTTGATTTCTCGTAAGGTGCCGATGGGGTCAAAACAATAACACCCACCGATCCCTAGTCGGCATAGTTTATGGTTAAGACTACGACGGTATCTGACCGTCTTCGATTCCCTAACTTTCGTTCACTGATTAATGAAAACATCCTTGGCAAATGCTTTCGCAGTAGTTTGTCTTCAATAAATCAGTGAACGAATCTCGGGGATGATAGGACTGGGAAACAGGTGCTGTAGAGAACGGACAATGAGAGGCTCTTAACCTTAGCAATTGGTA + ###$&&'&%$$$###$$%&*&&'0/3222...//3444A>=>ACIFEHGFHHKIIHEGGHSCB;;<8998456<<====:;96/56);B?@ABEHB@@@@BGED000018721125=<<=D9888978SHIHKDECCFHSMNJPSOIJNILIMJSG?>IJIGJIGIISLSKNJIRSNQMKHMRKIPSSLJJLLMJEDFELLOSMLLNKPLSSLPSSKJHKSH?SJMO?????65556CEBCE@@IOHJOMSSMSOOOSNLLLJKSRSJSHMLLJHJISKKLKKPOKMIIH@@@ADSIICBCGEE:8888<?>CCEHKILMHMRLLPRSPJILINPKOLNOJRNOKPSGGJGJIMMIHNSPSSSJJMIKKSRLSIISJLSSSLSJSOSLIIJHHISSQMSKLIIIKJLHJHEEFHSNOSHKHKPHHJJH98<<0//=/ADEFRMMRHSJLLSIMSLIIJGLOPKSNIKMOOIOQKIKSSLPSKLQQJHMJJIHKJLIHHJIISILIJ87787>>=.+**&'&&&(,20(('%%%%%'336;FLFIGGJFFHHSFHGFGKLJRJOGGIDGMKJIEIGFFEBGGBA897676'&&&$
GTGTATGTACTGTACTTCGTTCAGTTACGTATTGCTAAGGTTAAGAGCCTCTCATTGTCCGTTCTCTACAGCACCTGTTTCCCAGTCACGATCTTCGCTTTAATACTGTCTTCCTTTACTATTGTTGGGGAACCTACTCTAAAGGAAGACAGTATTAAGAGAAGATCTTGGATATACCCAATAGTTGAAGATGGCTATACGAAAATTCAATATAAAACTCAAGGAATGCTGAAACCAATAGAATAATGAAGCACATAGTTCCATGCCCAAAATGTGAATCTCTTTCTATCGAGGTTGTTTGTATTAAATATGATGAAGAAAATTGTGCTGTAAGAAGGAAATTATGTGCGTGATTGTGAACATAGGTTTTACACGCTGCAATACCCCGAAGCCATTGTATCTAATAGGGAAATTAAATATACAAAAGGTGGAAGAACAGTTATTGTTTTAGATTTATAAAGAAAACGTTAAGCAACTCAGGAGAGTGTAAAATAAAGTTCTGAAACCCTAACATTCATGACTCACGAACACGGCACAATCAAATGCAGAATTATTAGCGACTGTAAGAGAGGTCTCGAAGCTATAATGATCGATCTAGCTGATCGTGACTGGGAAACAGGTGCTGTAGAGAACGGACAATGAGAGGCTCTTAACCTTAGCAATACG

**Comment by lh3** [comment]
Minimap2 doesn't output fastq. This is probably unrelated to minimap2 question. Also, please don't show us your long script to save everyone's time.

**Comment by lucyintheskyzzz** [comment]
I was just showing an example of the .fastq file before alignment and after alignment. I think this is beneficial for people to see.

**Comment by lh3** [comment]
I understand you are eager to get an answer as you have been posting multiple times about the issue. However, if you want to resolve it, you *have to* isolate the problem to a specific command line. Process the data step by step and see which line goes wrong. It is your job to read and debug your long script, not mine.

Also, I reiterate that minimap2 doesn't output fastq. The problem probably lies in other steps, not in minimap2.
