### ISSUE TITLE
minimap2 still run without warning or error when anno.bed is not present

### ISSUE THREAD

**Issue by alexyfyf** [lh3/minimap2#1229]
Hi Heng,

I have noticed an issue when I tried to use `-junc-bed` to improve small exon alignments. 
I noticed when I run `minimap2 -ax splice -I 1000G -t $num_cores --junc-bed anno.bed $genome $raw_reads > test.sam` Even the `anno.bed` file is not present in the current folder, the command still runs without any issue. I think it will be ignored in the default `map-ont` mode, but not in `splice` mode.
```
[M::mm_idx_gen::69.718*1.52] collected minimizers
[M::mm_idx_gen::148.442*1.66] sorted minimizers
[M::main::148.442*1.66] loaded/built the index for 1566 target sequence(s)
[M::mm_mapopt_update::151.000*1.65] mid_occ = 4082
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 1566
[M::mm_idx_stat::152.764*1.64] distinct minimizers: 111438932 (43.54% are singletons); average occurrences: 11.631; average spacing: 2.929; total length: 3796066963
[M::worker_pipeline::152.928*1.64] mapped 250 sequences
[M::main] Version: 2.26-r1175
[M::main] CMD: minimap2 -ax splice -I 1000G -t 48 --junc-bed anno.bed genomic.fna test.fq
[M::main] Real time: 153.724 sec; CPU: 251.648 sec; Peak RSS: 25.293 GB
```
Is this something wrong? 
I'm running `minimap2 2.26-r1175`, but I did not this issue been mentioned in the 2 recent release.

Thank you.

**Comment by micans** [comment]
I am currently trying to get minimap2 in a very specific case to correctly align intron/exon boundaries - a small exterior part (8 bases) at the 5' end of the exon is instead aligned to the 5' start of the neighbouring/previous intron. Using `--junc-bed` does not seem to help here, but I experience the same behaviour that a non-existent bed file is silently ignored (version `2.24-r1155-dirty`). This creates some doubt whether the `--junc-bed` file is doing anything at all. Could some diagnostics be introduced, e.g.
- one line summary of number of intron coordinate pairs read if successful
- exit with error if file not existing or not conforming
