### ISSUE TITLE
Minimap2 on 1D2 data 

### ISSUE THREAD

**Issue by kanchanhole** [lh3/minimap2#123]
Hello,

Can we use minimap2 on 1D2 data from albacore?

**Comment by lh3** [comment]
Is this 1D2 the same as 2D? If so, yes.

**Comment by kanchanhole** [comment]
1D2 contains sequence from the linear strand and complimentary strand.

**Comment by lh3** [comment]
I am not familiar with 1D^2. Would you expect to merge them into 2D reads?

Either way, minimap2 will work with 1D^2 and outputting one alignment for each part.

**Comment by kanchanhole** [comment]
I will look into merging them. What should the command look like for the reverse compliment fastq file?

**Comment by lh3** [comment]
I am not familiar with nanopore pipelines. I thought they would provide tools for this task. I think you'd better ask more experienced nanopore users. As I said, even if you don't merge them, you can still get reasonable output with minimap2.

**Comment by kanchanhole** [comment]
Would the minimap2 command look similar for linear and complementary strand?
this is what I am using 

minimap2 -ax splice -uf -k14 -a human_gen_ref.mmi 1D.fastq > albacore1D

**Comment by lh3** [comment]
I have not worked with such data, so I don't know. You can play with `-uf` and `-ur` and see which one works. If you are unsure, don't use `-u` at all and let minimap2 figure this out.
```sh
minimap2 -ax splice -k14 -a human_gen_ref.mmi 1D.fastq > albacore1D
```

**Comment by lh3** [comment]
How did you get this 58% number? What are the nominator and denominator?

**Comment by kanchanhole** [comment]
It is coming from samtools flagstat

**Comment by lh3** [comment]
I haven't used flagstat for a while. Could you show me a screenshot? Also, how can you know 1D^2 has better accuracy? In general, I don't think the lower mapping ratio is minimap2's problem. It is more likely to be issues in your data.

**Comment by kanchanhole** [comment]
-bash-4.1$  /scratch/kanchan/samtools-1.3.1/samtools flagstat input.bam
714604 + 0 in total (QC-passed reads + QC-failed reads)
109551 + 0 secondary
4811 + 0 supplementary
0 + 0 duplicates
420316 + 0 mapped (58.82% : N/A)
0 + 0 paired in sequencing
0 + 0 read1
0 + 0 read2
0 + 0 properly paired (N/A : N/A)
0 + 0 with itself and mate mapped
0 + 0 singletons (N/A : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)



Nanopore realeased 1D^2 and they claim it has better accuracy over 1D

**Comment by kanchanhole** [comment]
To figure out if my data is wrong or the command I am giving I made a temporary file in which I had known sequence from ncbi (forward strand). After using -uf -k14/ -ur -k14/ no u at all the % mapping was same 99%. I am unable to understand how those parameters are working.

**Comment by lh3** [comment]
-u has nothing to do with mapping ratio. It only affects splice junctions.

**Comment by kanchanhole** [comment]
How about -r or -f?

**Comment by lh3** [comment]
r and f are -u's argument. You haven't used -f or -r.

Anyway, I don't think this is a minimap2 issue. I am closing now.

**Comment by kanchanhole** [comment]
Thanks! I have tried using -f and -r (forward strand and reverse strand as per my understanding).It did not change the results. and hence I was curious what difference it makes when I use -r or -f if it is not changing the result?

**Comment by lh3** [comment]
Minimap2 command line help directly tells you what `-f` and `-r` mean. Why do you think they mean forward and reverse strand?

Also, minimap2 command-line help also tells you:
```
-u CHAR      how to find GT-AG. f:transcript strand, b:both strands, n:don't match GT-AG [n]
```
Here, -u takes an argument. Therefore, `"-uf" == "-u f"`, but `"-uf" != "-u -f"`.
