### ISSUE TITLE
Bug Report:   Got 0 hits  to use same sequence from reference fasta  

### ISSUE THREAD

**Issue by lidd77** [lh3/minimap2#1230]
hello, Heng, 

       I  extract a sequence from  reverse strand of ref.txt  ,and  use this sequence to map to ref.txt , but got  0 hit .
       however , when  I  use  blastn to align  this sequence and ref.txt ,  I got perfect match : 
     
![image](https://github.com/user-attachments/assets/0020bad3-102d-42c8-b4df-31f21dd9d91e)

      
       my  command is :  minimap2 -t 15 -x map-ont -a ref.txt  nr166.fasta
       minimap2 version:  2.17-r941
       ref.txt  has uploaded .  
[ref.txt](https://github.com/user-attachments/files/16327231/ref.txt)
      nr166.fasta sequence is as the below :   
       >nr166
         GGCCGATCAGTGGCCGGCGGCGGCGCCCCACGAGGCGGTGCCGGGTTCGGTCCCA

     the mapping result is : 
       nr166  	4	*	0	0	*	*	0	0	GGCCGATCAGTGGCCGGCGGCGGCGCCCCACGAGGCGGTGCCGGGTTCGGTCCCA	*	rl:i:0

    so maybe  this is caused by  a bug of minimap2  ?

   Expecting your reply !

Best

**Comment by lidd77** [comment]
[ref.txt](https://github.com/user-attachments/files/16327261/ref.txt)

**Comment by lh3** [comment]
map-ont is for long reads. Use the sr preset
