### ISSUE TITLE
Does minimap2 consider base qualities?

### ISSUE THREAD

**Issue by ezherman** [lh3/minimap2#1231]
I understand from this 2019 issue (#353) that minimap2 ignores base qualities. However the man page lists the `-Q` option: "Ignore base quality in the input file." Does minimap2 consider base qualities these days? And what is the effect of the `-Q` option? 

Thanks!

**Comment by lubitelpospat** [comment]
> I understand from this 2019 issue (#353) that minimap2 ignores base qualities. However the man page lists the `-Q` option: "Ignore base quality in the input file." Does minimap2 consider base qualities these days? And what is the effect of the `-Q` option?
> 
> Thanks!

Hi @ezherman, any chance you've figured out this?

**Comment by lh3** [comment]
Minimap2 doesn't consider base quality. -Q doesn't output qualities in output SAM. It has no effect to alignment.
