### ISSUE TITLE
kinetics signals in the output bam file of minimap2

### ISSUE THREAD

**Issue by ywzhang071394** [lh3/minimap2#1232]
Hi Heng,

We are recently using pacbio HiFi data to call methylation levels, which requires kinetics signals (i.e. fi, fp, ri, rp, fn, rn tags). Is it possible that minimap2 outputs these tags? 

Thanks

**Comment by hasindu2008** [comment]
An example commandline that I have been using for this:
```
samtools fastq -T'*' m84088_230609_030819_s1.hifi_reads.default.bam  | minimap2 -ax map-hifi -y -Y hg38noAlt_hifi.idx - -t12 --secondary=no | samtools sort - -o 
```

**Comment by ywzhang071394** [comment]
It works! Thankie!!
