### ISSUE TITLE
No secondary reads in 193 metagenomes

### ISSUE THREAD

**Issue by bhagavadgitadu22** [lh3/minimap2#1236]
I mapped reads from 193 metagenomes on high-quality MAGs assembled in those metagenomes using minimap2:
`minimap2 -ax sr -t {threads} {input.assembly} {input.reads1} {input.reads2}`

The very strange thing is I never get secondary reads. I cannot believe that not a single read map to 2 different positions: there are genes that are very well conserved...

A typical output from samtools flagstat looks like:
> 145137762       0       total (QC-passed reads + QC-failed reads)
> 144811414       0       primary
> 0       0       secondary
> 326348  0       supplementary
> 0       0       duplicates
> 0       0       primary duplicates
> 770392  0       mapped
> 0.53%   N/A     mapped %
> 444044  0       primary mapped
> 0.31%   N/A     primary mapped %
> 144811414       0       paired in sequencing
> 72405707        0       read1
> 72405707        0       read2
> 100930  0       properly paired
> 0.07%   N/A     properly paired %
> 247086  0       with itself and mate mapped
> 196958  0       singletons
> 0.14%   N/A     singletons %
> 10240   0       with mate mapped to a different chr
> 4211    0       with mate mapped to a different chr (mapQ>=5)

Should I believe that there are no secondary reads indeed? Or is there a problem with my mapping?

**Comment by lh3** [comment]
No secondary alignment in the sr mode

**Comment by bhagavadgitadu22** [comment]
Ok I understand. But is it a normal behavior though? Would it introduce more false negatives than additional true positives to run the sr mode with secondary=yes:
`-k21 -w11 --sr --frag=yes -A2 -B8 -O12,32 -E2,1 -b0 -r100 -p.5 -N20 -f1000,5000 -n2 -m20 -s40 -g100 -2K50m --heap-sort=yes --secondary=yes`

**Comment by lh3** [comment]
> is it a normal behavior though?

Yes. Nearly all short-read mappers do this. You just have a different application in mind.

**Comment by bhagavadgitadu22** [comment]
I understand. But how is the primary read selected though in case two mapping positions of the read are equally likely? I assume it will be a random process?

**Comment by bhagavadgitadu22** [comment]
In case two alignments are equally likely based on the score and mapping quality, how is minimap2 deciding which one is gonna the primary read though? 

I feel like it should be random to avoid a bias. For instance if the first performed alignment is systematically picked it would mean the contigs at the beginning of the fasta file are more likely to get primary reads than contigs at the end of the file.
