### ISSUE TITLE
minimap2: Error in CIGAR strings

### ISSUE THREAD

**Issue by Adele-Mangelinck** [lh3/minimap2#1238]
Hello,

I am encountering an issue concerning the generation of CIGAR strings with minimap2. My command line is:
minimap2 -ax splice --MD --eqx reference.fa sequences.fastq.gz > alignment.sam
Then, when running another tool on the sam file, I get the following error message:
Error: MD tag does not match CIGAR string at explicit match operator ('=').

Does anyone have any idea?
Thank you in advance for your help.

**Comment by lh3** [comment]
What is "another tool"? Does samtools report an error?
