### ISSUE TITLE
SAM X/= instead of M

### ISSUE THREAD

**Issue by armintoepfer** [lh3/minimap2#124]
Would it be possible to generate X/= instead of M cigars?

**Comment by lh3** [comment]
Minimap2 won't output X/= in CIGAR. Sorry.

**Comment by armintoepfer** [comment]
And what it I provide the patch to optionally generate X/=? I do understand your reasoning against X/= and just want to make sure that you won't even add an optional feature when it comes for free ;)

**Comment by lh3** [comment]
If you already have the code, just send a PR. I will have a look. If not and pacbio really needs that feature, I would prefer to implement in my way.
