### ISSUE TITLE
Why mapq=60 when the read is actually from X-Y 100% homologous region

### ISSUE THREAD

**Issue by weishwu** [lh3/minimap2#1242]
I aligned my ONT reads sequenced from a male sample to the hg38 reference genome. I noticed that some reads were mapped to the region that is 100% identical between chrX and chrY, with mapq=60 and no supplementary alignment. Blatting the sequence of one of these reads on UCSCgb confirms that it maps to chrX and chrY equally well. Why doesn't minimap2 capture this read as multimapping?

My minimap2 (version 2.26-r1175) command-line:
`minimap2 -t 17 -ax map-ont -y {input.genome_index} {input.reads}`

Thanks.

**Comment by lh3** [comment]
What is the coordinate of the alignment? And what is the exact reference genome you are using (e.g. the URL)?

**Comment by weishwu** [comment]
Hi @lh3. Never mind. I see that this region is hard-masked in the reference file I use. It's the hg38 reference from the GATK bundle. Sorry that I should've checked this earlier.
