### ISSUE TITLE
minimap2 and tiledbvcf

### ISSUE THREAD

**Issue by lynnjo** [lh3/minimap2#1243]
We have a larger pipeline that includes both minimap2 and tiledbvcf (and other tools).  Our original yml file specified these programs and versions:

name: phgv2-conda
channels:
  - conda-forge
  - bioconda
  - tiledb
dependencies:
  - python=3.8
  - tiledb-py=0.22
  - tiledbvcf-py=0.25
  - anchorwave=1.2.3
  - bcftools
  - samtools
  - agc=3.1
  
  This works fine, conda/mamba will pull in minimap2=2.28 and all is compatible.
  
 I need to update the tiledb versions to pull newer code which requires python 3.10, so my updated yml file looks like:
 
 name: phgv2-conda
channels:
  - conda-forge
  - bioconda
  - tiledb
dependencies:
  - python=3.10
  - tiledb-py=0.32.0
  - tiledbvcf-py=0.35.0
  - anchorwave=1.2.3
  - bcftools
  - samtools
  - agc=3.1
  - minimap2
 
This is incompatible with minimap2 requirements.  With the above dependencies, minimap2 version 2.1.1 is loaded with a build id of "0" and minimap2 will not run.

I tried updating the yml file and specifying a dependency on "minimap2=2.28".  When I run that conda/mamba says python 3.10 and tiledbvcf-py 0.35.0 cannot be installed due to conflicts relating to libsqlite -> libzlib and python_abi 3.10.

I then set python to 3.8, but tiledbvcf will not install without python 3.10 or later.

Is there a minimap2 version that is compatible with python 3.10?  Any suggestions?

**Comment by lh3** [comment]
Minimap2 doesn't depend on python. Only mappy does but it works with all python3 versions (and even python2.7). As such, this is not a minimap2 question. I don't know bioconda good enough to answer. You need to ask bioconda developers.
