### ISSUE TITLE
-P and -D options are not working

### ISSUE THREAD

**Issue by Jokendo-collab** [lh3/minimap2#1244]
I wanted to do all-vs-all alignment but it's not recognizing `-P and -D` flags. I am using minimap2 version 2.28. Is there a reason why these flags are non working but if I run `man ./minimap2.1` I can see those flags. Could you advise on how to solve this?

**Comment by lh3** [comment]
I am sure it works. What is your command line?

**Comment by Jokendo-collab** [comment]
here is my command
`minimap2 -x asm20 -c -t 16 --eqx -D -P  -–dual=no assembly.fasta`

**Comment by lh3** [comment]
You need two files. Provide the fasta twice
