### ISSUE TITLE
error on splice:hq

### ISSUE THREAD

**Issue by Sung-hub** [lh3/minimap2#1249]
I was trying to align Isoseq data to asssembly and I got Error on "Splice:hq".  I works without error when I used just "splice".

[sung.shin@arsnecla0ap2 Protist2027099]$ nohup singularity exec https://depot.galaxyproject.org/singularity/minimap2:2.9--1 minimap2 -ax splice:hq -uf /home/sung.shin/Protist2027099/LIB121406/LIB121406_hifiasmmeta_tangled10042024.fasta /home
/sung.shin/Protist2027099/LIB118322/analysis-Protist_IsoSeq-5410-m54337U_221209_184012.hifi_reads.fastq > Tangle_isoseq_splice_align.sam 2>asm.log &
[ERROR] unknown preset 'splice:hq'

Could you give me an advice on this? is it ok to use without ";hq"?

**Comment by lh3** [comment]
Use the latest version.
