### ISSUE TITLE
unrecognized option: MD eqx and cs

### ISSUE THREAD

**Issue by Mo7ammedFarahat** [lh3/minimap2#1250]
[M::main] CMD: /minimap2/minimap2-2.28_x64-linux/minimap2 -k 17 -I 8G -d verkko_trio_diploid.fa.mmi verkko_trio_diploid.fa
[M::main] Real time: 168.063 sec; CPU: 296.253 sec; Peak RSS: 22.192 GB
minimap2: unrecognized option: MD
minimap2: unrecognized option: eqx
minimap2: unrecognized option: cs

here is the command:
#Create minimap2 index of our diploid assembly
minimap2 \
    -k 17 \
    -I 8G \
    -d verkko_trio_diploid.fa.mmi \
    verkko_trio_diploid.fa

#minimap parameters appropriate for nanopore
in_args="-y -x map-ont --MD --eqx --cs -Y -L -p0.1 -a -k 17 -K 10g"

#do the mapping with methylation tags by dumping the Mm/Ml tags to the fastq headers
samtools fastq \
    -TMm,Ml /nesi/nobackup/nesi02659/LRA/resources/ont_ul/03_08_22_R941_HG002_2_Guppy_6.1.2_5mc_cg_prom_sup.bam \
    | minimap2 -t 24 ${in_args} verkko_trio_diploid.fa.mmi - \
    | samtools view -@ 24 -bh - \
    | samtools sort -@ 24 - > \
    verkko_trio_diploid.mm2.5mC.bam

**Comment by lh3** [comment]
```
minimap2: unrecognized option: MD
minimap2: unrecognized option: eqx
minimap2: unrecognized option: cs
```
These are not minimap2 errors. If you want to report an issue, run minimap2 on command line and see if you can reproduce it.
