### ISSUE TITLE
Map mission killed

### ISSUE THREAD

**Issue by handesome** [lh3/minimap2#1252]
Hi!when I run the code`minimap2 -ax splice -uf --secondary=no -C5 -t 30 --MD /data/work/SRR17180608_subreads.fastq /data/work/GRCh38.primary_assembly.genome.fa`,then comes
`[M::mm_idx_gen::13.850*1.84] collected minimizers
[M::mm_idx_gen::14.737*3.13] sorted minimizers
[M::main::14.807*3.12] loaded/built the index for 287888 target sequence(s)
[M::mm_mapopt_update::15.124*3.07] mid_occ = 5177
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 287888
[M::mm_idx_stat::15.298*3.05] distinct minimizers: 10663799 (48.90% are singletons); average occurrences: 11.853; average spacing: 2.973
Killed`,so could anyone give some advice?
Thanks!!!!!

**Comment by lh3** [comment]
Probably insufficient memory. Also, you probably want to put the reference first.
