### ISSUE TITLE
Clarification on Strand-Specificity in Minimap2 for Long-Read RNA Sequencing

### ISSUE THREAD

**Issue by xianyu0623** [lh3/minimap2#1253]
Hi,

I'm currently working with long-read RNA sequencing and encountering issues related to strand directionality. I noticed that Minimap2 appears to consider only the positive strand for transcript alignment for PacBio and ONT. Could you please explain the rationale behind this design choice, or provide any references that address this?

Thank you very much for your help!

**Comment by lh3** [comment]
It by default aligns both strands. Read README carefully.

**Comment by lh3** [comment]
Determined by their protocols
