### ISSUE TITLE
Aligning Nanopore DRS reads with genome

### ISSUE THREAD

**Issue by baibhav-bioinfo** [lh3/minimap2#1254]
Hello,
we are working with nanopore DRS reads and trying to find out the APA between samples.
for better alignment with the genome trying to trim off the polyA tails from DRS reads, but DRS reads have very inconsistent polyA tails (due to inaccurate basecalling) and we are trying to trim them.

I was wondering if do align my DRS reads with genome using minimap2, what will be the last base in read aligned to genome?
will it be the last base of read or it will exclude the tail part automatically?

also is there any way we can know the default percentage of similarity between reads and genome required to be called a hit?

**Comment by lh3** [comment]
> what will be the last base in read aligned to genome?

The base that can be aligned

> is there any way we can know the default percentage of similarity between reads and genome required to be called a hit?

Write a script and analyze the alignment
