### ISSUE TITLE
How to maximise minimap alignment without errors?

### ISSUE THREAD

**Issue by lauren220200** [lh3/minimap2#1256]
Good afternoon,
I've had a few problems lately with minimap2. Initially, I was using the default settings:
minimap2 -cx map-ont ref.fa fastq > file.paf

However, I realised that at times (often) I had multiple primary alignments (see attachment).

As a result, I decided to change my command line to try and maximise the alignment :
minimap2 -cx map-ont --secondary=no --sam-hit-only -A 3 -B 2 -t 3 ref.fa fastq > file.paf

For a set of reads, this greatly improved the alignment (see attachment). However, there is another problem with this solution: minimap2 has created alignments for me for several reads, which are effectively maximised because the alignment starts at the beginning and ends at the end of the read, but these alignments contain artefactual structural variants (insertion/deletion) (see dotter in attachment).

I therefore preferred to return to this command line:
minimap2 -cx map-ont --secondary=no --sam-hit-only ref.fa fastq > file.paf

My question is: how can I maximise the alignment to: 1) take into account large deletions as in my example (12kb deletion here but there are some that are bigger) and 2) take into account neo insertions as in the other example (insertion from another chromosome here)?

![Capture d’écran du 2024-11-05 16-36-49](https://github.com/user-attachments/assets/16c3bec1-fb65-43df-9233-da209b7c89d8)
![Capture d’écran du 2024-11-05 16-44-07](https://github.com/user-attachments/assets/3e812c35-8b1d-436e-a7a8-04cfc6b3fb1e)

![Capture d’écran du 2024-11-05 16-36-49](https://github.com/user-attachments/assets/f26a8933-d93b-41f4-96bf-892382c35288)
![Capture d’écran du 2024-11-05 16-44-07](https://github.com/user-attachments/assets/eb09bf1a-fc73-41b7-a933-caec461f9ec5)

**Comment by lh3** [comment]
I don't understand what each figure corresponds to. Anyway, you can't expect a single linear alignment when you have alignments on different strands or chromosomes. Don't use "-A3 -B2". Minimap2 should probably throw an error given this setting.

**Comment by lauren220200** [comment]
Hello,
First of all, forgive me for not being clear with my screenshots...

Thank you for your reply! I have another question though: I'm interested in
structural variations (I work at the Plant Genome and Development
Laboratory in Perpignan, France). Does this mean that minimap2 will never
be able to correctly place retrotransposon neo-insertions (because the
identity is too close to its region of origin)?


Kind regards,
Lauren CLEMENT.

Translated with DeepL.com (free version)

**Comment by lh3** [comment]
Could you show examples? I am still not sure what you mean.

**Comment by lauren220200** [comment]
Hi,
I'm attaching an example of a paf for which I have 4 reads whose alignment
splits towards the middle because there is the presence of an insertion (in
this case a 5kb retrotransposon).

My question is: how can I change the minimap2 parameters so that, instead
of having 3 lines for a read, I only have one with this 5kb insertion noted
in the cigar?

Best regards,
Lauren CLEMENT.
