### ISSUE TITLE
Different results depending on the output format

### ISSUE THREAD

**Issue by mpovidlov1** [lh3/minimap2#1259]
I am aligning short 200 nt reads. If I use the default PAF output format, I get this result:
tg1B18_22       200     7       197     +       6956    59641292        2519227 2519417 190     190     60      tp:A:P  cm:i:31 s1:i:190        s2:i:0  dv:f:0.0021     rl:i:0

Note that the match start on the query is 7, while actually the read is 100% identical on the full length. 
If I run with -a to produce SAM output, the result is what it should be with cigar 200M:
tg1B18_22       0       6956    2519221 60      200M    *       0       0   ...

Why are the results so different depending on the output format??

Thanks

**Comment by lh3** [comment]
See FAQ
