### ISSUE TITLE
1-4 nt shit in exome boundary in  aligned bam  from isoseq subread data   

### ISSUE THREAD

**Issue by wzhang42** [lh3/minimap2#1261]
Hi, Heng, 
   I have some isoseq subread.bam data.   I followed the isoseq workflow and did the ccs calling, isoseq lima , isoseq refine and generated the flnc.bam.   I use   "minimap2 -ax splice:hq -uf --secondary=no -C5" to do the mapping both for the subread.bam and flnc.bam.     The aligned bam from flnc.bam look ok, but we found there are 1-4 nt shift at the exome boundary in the aligned bam from subread.bam.  Not sure whether this is normal or a  bug.  Use the aligned bam from flnc.bam look ok, but the coverage is only 10-20% of the subread case.  
![Screenshot (3878)](https://github.com/user-attachments/assets/ca47496b-3a40-4db8-8d83-c892ff9a3f8e)

**Comment by lh3** [comment]
Subreads are low-quality, so you should use `-x splice` instead. They will be harder to align correctly anyway due to more errors.

In addition, as I remember – I could be wrong on this – subreads are duplicated. You probably don't want to use them in the first place.
