### ISSUE TITLE
Default treatment for long-ish (~2kb) insertions

### ISSUE THREAD

**Issue by katlavigneflug** [lh3/minimap2#1262]
I am using minimap2 to align ONT reads, some of which will contain an insertion of up to 1800 bp, with the following command:

`minimap2-2.28_x64-linux/minimap2 -ay -Y --MD ref.mmi input.fastq > output.sam`

When manually parsing sample reads, I am able to identify insertions at the expected location that seem to be tolerated in the alignments (ie do not stop chain elongation). This was surprising to me given that the default for --frag is no, so I figured that I must be misinterpreting something in the manual documentation.

I am thus wondering:
1) When using default --frag settings, is there a penalty for insertions, similar to deletions/gaps? 
2) What is the effect of setting fragment size? Is this meant to remove a penalty for insertions under that size?

Thank you.

**Comment by lh3** [comment]
> What is the effect of setting fragment size? 

--frag is for paired-end reads. It has nothing to do with indel sizes

> is there a penalty for insertions, similar to deletions/gaps?

insertions are treated the same way as deletions

**Comment by katlavigneflug** [comment]
Thanks for clarifying!
