### ISSUE TITLE
For similar reads, some show multi-part alignments 

### ISSUE THREAD

**Issue by yzhang-github-pub** [lh3/minimap2#1263]
Dear Dr. Li,

I have reads with large deletions. When they are aligned to ref, two alignments are produced for some reads, but not for others:

![image](https://github.com/user-attachments/assets/9bb63ef4-4982-4706-849b-3d4af12fde70)

Above show 5 reads. All of them are expected to produce two alignments/read, one end of the read should map to ref up to base 334, and the rest should map to ref starting from 2163 in ref, with a few bp noises at the junctions. This is confirmed with blast local alignment. Minimap2 only generated two alignments for read5. 

I tested minimap2 2.26 and current version (2.28-r1209). Command : minimap2 -c -x map-ont. 

Please advice. Thanks!

**Comment by lh3** [comment]
You probably need shorter seed length, denser seeds and/or lower score thresholds.
