### ISSUE TITLE
Lower alignment rates when performing transcriptome mapping on scrnaseq data

### ISSUE THREAD

**Issue by atrull314** [lh3/minimap2#1267]
Hi,

We are currently using minimap2 for aligning single-cell RNA data as part of an nf-core pipeline. We are currently testing out aligning to the transcriptome in order to integrate OARFISH into the pipeline, but have noticed a major drop in alignment rates for some of our samples using the 3’ 10X kit when aligning to the transcriptome. We’ve seen this happen in a number of samples, but I’ll focus on one sample for this message. The sample is a PBMC sample available for download via the 10X website and reads have the single cell data stripped from the read (i.e. the barcode, umi, etc.) as part of standard processing, so it would be largely identical to a read from bulk-RNAseq during the alignment step.

When we align this sample to the genome, we see around 106.8 million reads aligned with a mapping rate around 99.8%. However, for the transcriptome we only see about 81.9 million reads aligned with a mapping rate of 76.5%. We used the below command in order to execute minimap:

``` bash
minimap2 \
        --MD -ax splice -un -k14 --secondary=no \
        -t 12 \
        gencode.v32.transcripts.fa \
        $FASTQ_IN \
        -a
```

Based on previous tickets, we also replaced `-x splice` with the `-x map-ont` parameter, however we still only received about 85.5 million reads, which while an improvement is still significantly lower than the genome alignment. We wanted to ask if you had any thoughts that might be able to explain this or any insights to help with alignment to the transcriptome?

Thanks for your help!

**Comment by lh3** [comment]
Check where reads unmapped to transcriptome are aligned to the genome

**Comment by rob-p** [comment]
It may also be worth noting that, when aligning to the transcriptomr you probably want to allow more multimapping. This is not likely to change your mapping rate itself, but is important for quantification. We suggest

```
--eqx -N 100
```

For a complex eukaryotic transcriptome.

**Comment by lianov** [comment]
@rob-p : Thanks for this feedback! We are currently implementing your method in our nf-core/scnanoseq pipeline, so indeed, any feedback you have from your experience with the upstream processing will allows us to set sensitive parameters in the pipeline for oarfish quantification.
