### ISSUE TITLE
Overlapping alignments from long-read RNA-seq

### ISSUE THREAD

**Issue by andyjslee** [lh3/minimap2#1268]
Below are two alignment records from minimap2 (v2.28) using long-read RNA-seq data (PacBio) with supplementary alignments. For context, the following command was used: `minimap2 -ax splice:hq -uf --cs --eqx -Y -L reference.fasta reads.fastq > output.sam` 

```
read_1	0	chr11	26337180	60	1S131=10435N59=1844N61=3612N57=4169N101=14759N97=11927N69=25185N151=8498N84=564S	SA:Z:chr11,26715841,-,565M810S,60,1;
read_1	2064	chr11	26715841	60	61=1X503=810S		SA:Z:chr11,26337180,+,1S810M80429D564S,60,0;
```

When I trace the alignments back to the original read sequence, the two aligned sequences shared a nucleotide in the read (i.e. they overlap in the read).

* Read length: 1375
* First alignment (CIGAR without the skips): `1S810M564S`
* Second alignment (CIGAR): `61=1X503=810S` (aligned to the reverse strand)

The above CIGAR strings indicate that there is an overlap in the query (read) sequence of 1 nucleotide.

Here is a simpler example:

Read: `AAGCTAGC`

Current (overlapping) alignments:
`read_A	chrB	pos1	5=3S	(AAGCT-softclipped)`
`read_A	chrB	pos2	3S5=	(softclipped-CTAGC)`

Desired (non-overlapping) alignments:
`read_A	chrB	pos1	4=4S	(AAGC-softclipped)`
`read_A	chrB	pos3	4S4=	(softclipped-TAGC)`

What minimap2 parameters should I pass so that alignments do not overlap the query (read) sequence?

Thank you.

**Comment by lh3** [comment]
These alignments may be biologically meaningful or indicative of sequencing artifacts. If you want to filter them, write a script. -p1 is not the intended use of this parameter and will hurt alignment accuracy.
