### ISSUE TITLE
-p flag not reporting expected alignments

### ISSUE THREAD

**Issue by CarlosBlancoGo** [lh3/minimap2#1269]
Hi,
I'm using minimap2 on pacbio RNA long reads and I'm having an issue with the parameter "-p". So what I was trying to achieve was to filter secondary alignments so I end with secondary alignments that have the same score ms as their respective primary alignment. From what I understood, the parameter -p when set to 1.0 would achieve this, however, the primary and secondary alignments obtained not only do not have the same ms, but also the primary alignment assigned is different from the primary alignment selected when minimap2 is run with the parameter -p 1.0. Here's an example:

When running without the -p flag:
minimap2 -ax splice:hq --secondary=yes -C5 -uf -t {args.mapping_cpus} {args.genome} {fastq_file} -o {file_acc}.sam
I get these alignments for this molecule:
molecule/101	16	18	49488494	60	73M792N192M903N99M240N135M477N41M86N53M873N22M	*	0	0	AATTACATTTATTTTAATGCTGAATTTACTCCCGTGCCATAAGTTTTTGTTTCTTCAGTTTCTTCTGGGATATCTTTTTCTTCTGGGCAACCTCCTCTTCTGGTTTAGGAACAATCTGTTCCTTTTCCGTAAGGATCATCTCAATGTGGCAGGGAGAGCTCATGTATGGGTTAATCCGACCATGAGCTCTGTAGGTCCGGCGGCGCATCTTAGGTGCTTTGTTCACTTGGATATGCTCAATGACCAGAGAATCTACATCTAAACCCTTAAGTTCAGCATTACTCTCTGCGTTTTTAAGCATGTGCAGCAAAAATTCAGCACTCTTTTTGGGCCACCGACCTTGTGTCCAGCCCCATTGCTTGGCCTGCGCACACCTGCCAACTCCACCATTGTAACGTCGGAATGGTACACACTGTTTCTGTAAAGTGACATCTTTCAGATACTTCGTGGCTTTTCGTATATGCATACCCTTGATGGCCTGAGCAGTTTCACGAGTGTTCTTAAAGTGAACACGAAGATTGGAACCTCTTGATTTGCATGATTTCGTGGGGTTCTCCGGGTCAAGTGAATAGCGAACCATTTTCACAGATCACCTCAGGCTGCTTAGGGAAAGAG	BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB	NM:i:0	ms:i:615	AS:i:471	nn:i:0	ts:A:+	tp:A:P	cm:i:175	s1:i:558	s2:i:594	de:f:0	rl:i:0
molecule/101	256	1	77129079	0	615M	*	0	0	*	*	NM:i:5	ms:i:590	AS:i:590	nn:i:0	ts:A:+	tp:A:S	cm:i:169	s1:i:594	de:f:0.0081	rl:i:0
molecule/101	256	1	108992257	0	10S605M	*	0	0	*	*	NM:i:5	ms:i:580	AS:i:580	nn:i:0	ts:A:+	tp:A:S	cm:i:171	s1:i:578	de:f:0.0083	rl:i:0
molecule/101	272	15	71341133	0	615M	*	0	0	*	*	NM:i:8	ms:i:575	AS:i:575	nn:i:0	ts:A:+	tp:A:S	cm:i:163	s1:i:562	de:f:0.0130	rl:i:0
molecule/101	272	3	197850375	0	579M1D36M	*	0	0	*	*	NM:i:16	ms:i:533	AS:i:533	nn:i:0	ts:A:+	tp:A:S	cm:i:126	s1:i:520	de:f:0.0260	rl:i:0
molecule/101	256	1	86784878	0	615M	*	0	0	*	*	NM:i:20	ms:i:515	AS:i:515	nn:i:0	ts:A:+	tp:A:S	cm:i:109	s1:i:527	de:f:0.0325	rl:i:0

And when running with the -p 1.0 flag:
minimap2 -ax splice:hq --secondary=yes -C5 -p 1.0 -uf -t {args.mapping_cpus} {args.genome} {fastq_file} -o {file_acc}.sam
I get these alignments for the same molecule:
molecule/101	0	1	77129079	16	615M	*	0	0	CTCTTTCCCTAAGCAGCCTGAGGTGATCTGTGAAAATGGTTCGCTATTCACTTGACCCGGAGAACCCCACGAAATCATGCAAATCAAGAGGTTCCAATCTTCGTGTTCACTTTAAGAACACTCGTGAAACTGCTCAGGCCATCAAGGGTATGCATATACGAAAAGCCACGAAGTATCTGAAAGATGTCACTTTACAGAAACAGTGTGTACCATTCCGACGTTACAATGGTGGAGTTGGCAGGTGTGCGCAGGCCAAGCAATGGGGCTGGACACAAGGTCGGTGGCCCAAAAAGAGTGCTGAATTTTTGCTGCACATGCTTAAAAACGCAGAGAGTAATGCTGAACTTAAGGGTTTAGATGTAGATTCTCTGGTCATTGAGCATATCCAAGTGAACAAAGCACCTAAGATGCGCCGCCGGACCTACAGAGCTCATGGTCGGATTAACCCATACATGAGCTCTCCCTGCCACATTGAGATGATCCTTACGGAAAAGGAACAGATTGTTCCTAAACCAGAAGAGGAGGTTGCCCAGAAGAAAAAGATATCCCAGAAGAAACTGAAGAAACAAAAACTTATGGCACGGGAGTAAATTCAGCATTAAAATAAATGTAATT	BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB	NM:i:5	ms:i:590	AS:i:590	nn:i:0	ts:A:+	tp:A:P	cm:i:169	s1:i:594	s2:i:578	de:f:0.0081	rl:i:0
molecule/101	256	1	108992257	0	10S605M	*	0	0	*	*	NM:i:5	ms:i:580	AS:i:580	nn:i:0	ts:A:+	tp:A:S	cm:i:171	s1:i:578	de:f:0.0083	rl:i:0

As you can see, the primary alignment when running -p 1.0 is the first secondary alignment when not running -p 1.0. 
As I saw from #1103 , -p 1.0 can lower alignment accuracy. I was wondering if you could elaborate a little bit more on this, as I'm not sure I'm understanding the -p parameter correctly, because I assumed the filtering of the alignments would be done after establishing which were the primary and secondary alignments.

Best,

Carlos

**Comment by lh3** [comment]
Don't use -p1.0. Filter alignment with a script if you have to (I actually don't understand why you have to do all these)

**Comment by lh3** [comment]
> if you could elaborate a little bit more on this

-p also controls how many suboptimal chains are considered for base alignment. -p is a Mapping parameter, not an Input/Output parameter. Generally, try not to twist minimap2 algorithm parameters, which often results in worse alignment unless you know the algorithm well; instead, do alignment normally and filter later.
