### ISSUE TITLE
Compilation issue related to SSE instructions

### ISSUE THREAD

**Issue by alexeigurevich** [lh3/minimap2#127]
Hi Heng,

I've just tested minimap2 compilation in various settings and found a small issue on Ubuntu 32bit virtual machine with GCC 5.2.1.
Initially, I got a bunch of errors like:
```
In file included from ksw2_ll_sse.c:4:0:
/usr/lib/gcc/i686-linux-gnu/5/include/emmintrin.h:1180:1: error: inlining failed in call to always_inline ‘_mm_srli_si128’: target specific option mismatch
 _mm_srli_si128 (__m128i __A, const int __N)
 ^
```

First, I tried the suggested solution from README file and ran `make sse2only=1`. However, this did not help. Note that the errors are occurring during `ksw2_ll_sse.o` compilation which is required independently from `sse2only` value. 

The solution which helped me was to update `Makefile` first line
`CFLAGS=         -g -Wall -O2 -Wc++-compat`
with one more option: `-msse2` (it also works with some other alternatives, e.g. `-msse4.1`).

Do you think it make sense to add this or similar option to `Makefile` permanently?

**Comment by lh3** [comment]
Thanks! I haven't used 32-bit machines (virtual or not) for some years and haven't paid attention to this issue. I have made some changes to Makefile via a22ebb9. Let me know if that works.

**Comment by alexeigurevich** [comment]
Now it working, thanks!
