### ISSUE TITLE
Segfault Indexing Very Long Sequence

### ISSUE THREAD

**Issue by skovaka** [lh3/minimap2#129]
I am trying to index a fasta file containing a single ~3 gigabase sequence generated by concatenating all chromosomes in hg38 (not including alt loci, and also removing removing all 'N's). When I run the command `minimap2 -d hg38_concat_minimap2.idx hg38_concat.fa`, it hangs for about 4 seconds and then returns "Segmentation fault". If I split this fasta file into 600 5 megabase sequences, I can index it without issue. I would understand if there were a maximum length for a single sequence, but I don't see this documented anywhere. You can download the file I'm trying to index [here](http://cs.jhu.edu/~skovaka/hg38_concat.fa.zip).

**Comment by lh3** [comment]
Before I go to download the file - a quick question: what's the length of the longest sequence? Minimap2 does not work with a sequence longer than ~2Gbp. The sum of lengths can be >100Gbp.

**Comment by skovaka** [comment]
Thank you for the quick response! The file contains one ~3Gbp sequence, so that would explain it. Is this documented anywhere? It's an easy limit to work around, but I couldn't find it in the preprint or README.

**Comment by lh3** [comment]
Sorry that I was looking the message on my phone and overlooked that you had mentioned the length. I will add this limit to the "Limitations" section in README. Thanks!

**Comment by lh3** [comment]
Added via 0238caa. Thanks.
