### ISSUE TITLE
minimap2 gDNA stress test

### ISSUE THREAD

**Issue by gringer** [lh3/minimap2#13]
Here are three assembled contigs (generated from nanopore reads from a rodent parasite, _Nippostrongylus brasiliensis_) that have a highly repetitive structure:

[16.fa.gz](https://github.com/lh3/minimap2/files/1221426/16.fa.gz)

doing an all-vs-all mapping of these sequences (1.38Mb total) takes about 20 seconds:

```
$ time ~/install/minimap2/minimap2 -X -x ava-ont 16.fa 16.fa > /dev/null
[M::mm_idx_gen::0.101*0.99] collected minimizers
[M::mm_idx_gen::0.132*1.45] sorted minimizers
[M::main::0.132*1.45] loaded/built the index for 3 target sequence(s)
[M::mm_mapopt_update::0.158*1.39] mid_occ = 246; max_occ = 674
[M::mm_idx_stat] kmer size: 15; skip: 5; is_HPC: 0; #seq: 3
[M::mm_idx_stat::0.168*1.36] distinct minimizers: 392121 (96.73% are singletons); average occurrences: 1.205; average spacing: 2.919
[M::worker_pipeline::18.873*1.26] mapped 3 sequences
[M::main] Version: 2.0rc1-r274-dirty
[M::main] CMD: /home/gringer/install/minimap2/minimap2 -X -x ava-ont 16.fa 16.fa
[M::main] Real time: 18.883 sec; CPU: 23.788 sec

real    0m18.889s
user    0m23.732s
sys     0m0.064s
```

I'm not completely sure about the PAF file output, so don't know if what I'm seeing matches what I'm thinking, but this line seems to suggest a match at 16% identity (19567 / 122212), which seems a bit low:

    16_tig00006776  116440  410     115255  +       16_tig00006776  116440  1786    116430  19567   122212  0       tp:A:S  cm:i:4232       s1:i:21043

I leave this file here for further exploration.

**Comment by gringer** [comment]
LAST mapping of the same sequences as a dotplot (takes about half a minute to run):

![out](https://user-images.githubusercontent.com/856314/29262032-ce8a6646-8126-11e7-83d1-07ea9c50b504.png)

**Comment by lh3** [comment]
I am not sure what is your purpose. Generally, you can only get a good estimate of sequence divergence when you generate cigar. In addition, minimap2 is tuned for mapping by default. You need to change quite a few parameters for dotter plot.

**Comment by gringer** [comment]
To clarify, these are three contigs that Canu identified as having shared sequence, with some support for being present within the same region of a single chromosome. I'm not suggesting that minimap2 should be used for dotplots, just that these sequences cause problems with the overlapper.

I would love it if I could put the sequences into an overlapper and have it identify the single best overlaps between the sequences, glossing over all those pesky repetitive elements. At the moment, the output seems useless to me, with thousands of identified overlap regions and very low identities.

**Comment by lh3** [comment]
> thousands of identified overlap regions and very low identities.

To be precise, these are just local hits. Most of them are not dove-tail overlaps.

> I would love it if I could put the sequences into an overlapper and have it identify the single best overlaps between the sequences

I don't see dove-tail overlaps in your dotter plot.
