### ISSUE TITLE
Aligning short illumina reads with Pacbio

### ISSUE THREAD

**Issue by srbehera11** [lh3/minimap2#131]
What options need to be used for  aligning short illumina reads with Pacbio reads? 
Can I still use the following by replacing ref.fa with pacbio ?
./minimap2 -ax map-pb <Pacbio Reads>  <illumina Reads> > aln.sam

**Comment by lh3** [comment]
See #90 and #45. Minimap2 probably won't work well in this case. If you have high enough coverage, please assemble first and then map.

**Comment by srbehera11** [comment]
Thanks !!
