### ISSUE TITLE
Behaviour of the "--no-self" option

### ISSUE THREAD

**Issue by aderzelle** [lh3/minimap2#133]
Hello,
my question is simple. I am calling minimap2 like this 
`minimap2 -k15 -w5 -p0 -g10000 --no-self splitted.fa splitted.fa`
 Here is sample output
```
contig1125_size18652167_part_329	5000	19	4488	+	contig1125_size18652167_part_329	5000	227	4666	77	4469	0	tp:A:P	cm:i:13	s1:i:71	s2:i:71
contig1125_size18652167_part_329	5000	227	4666	+	contig1125_size18652167_part_329	5000	19	4488	77	4469	0	tp:A:S	cm:i:13	s1:i:71
contig1125_size18652167_part_329	5000	219	283	+	contig1125_size18652167_part_328	5000	3555	3619	53	64	0	tp:A:S	cm:i:10	s1:i:53
contig1125_size18652167_part_329	5000	4001	4074	-	contig1125_size18652167_part_3024	5000	1885	1957	50	73	0	tp:A:S	cm:i:4	s1:i:50
contig1125_size18652167_part_3024	5000	1885	1957	-	contig1125_size18652167_part_329	5000	4001	4074	50	73	12	tp:A:P	cm:i:4	s1:i:50	s2:i:0

```
Why is the first line reported, since it's a self-alignment? Is it because the alignment doesn't strictly span the 5000 bp of the contig?
Thank you

**Comment by lh3** [comment]
No, it is not, because coordinates are different. BTW, you should update to more recent versions. "--no-self" is now an alias of "-D". The man page gives a better explanation.

**Comment by lh3** [comment]
PS: see option"-D" [here](https://lh3.github.io/minimap2/minimap2.html#5).
