### ISSUE TITLE
Short error-prone alignment

### ISSUE THREAD

**Issue by armintoepfer** [lh3/minimap2#135]
I'm trying to use minimap2 to cluster short pacbio insertions from raw subreads. I've had no success in finding the right parameter combination to get the alignment of those two fragments:

```
ATGACCCCCCACAGCTTTACCCACGCCACACACAGATCAGATCTGACTCAGGCTCTTTACTGAATCAGC
ACCCCCCACAGCTGTACCCAGCGCCACACACAGAGCAGACGCTGGAACACTGTTATTGAAGGAATCAGCAATGGGGTA
```

A naive SW gives me following result:
```
ATGACCCCCCACAGCTTTACCCA-CGCCACACACAGATCAGAT-CTGACTCAGGC-TCTTTACTGAATCAGC---------  81
   ||||||||||||| |||||| ||||||||||||| ||||  |||   ||    | || |  ||||||||         
---ACCCCCCACAGCTGTACCCAGCGCCACACACAGAGCAGACGCTGGAACACTGTTATTGAAGGAATCAGCAATGGGGTA  81
```

Btw, I'm using the C API, so internal hacks are possible :)

**Comment by lh3** [comment]
I wouldn't recommend to use minimap2 for short noisy matches, but if you would like to do that anyway (reduce -k if you want even higher sensitivity):
```sh
./minimap2 -c -k11 -w1 -n2 -m10 -s20 first.fa second.fa
```

**Comment by lh3** [comment]
The command line above truncates the second half of the alignment. You may reduce the mismatch penalty to save that:
```sh
./minimap2 -c -k11 -w1 -n2 -m10 -s20 -B2 first.fa second.fa
```
