### ISSUE TITLE
Append FASTA/FASTQ comment to SAM output [feature request]

### ISSUE THREAD

**Issue by sjackman** [lh3/minimap2#136]
`bwa mem` has the `-C` option to append the FASTA/FASTQ comment to SAM output. I use this feature with 10x Genomics Chromium linked reads to output the barcode `BX:Z` tag of each read. I'd find this feature useful for `minimap2 -a -xsr`.

**Comment by lh3** [comment]
Have been thinking about this for a while. As you mentioned, now added. Option -y.

Closing via 08bd212.

**Comment by sjackman** [comment]
Thanks for the quick response, Heng!

Here's a more involved idea… do you think minimap2 could chain through alignments of reads in the same barcode, to create an alignment of the full molecule? For CIGAR alignments, perhaps `N` could be used to indicate the gaps between reads.

**Comment by lh3** [comment]
That would amount to a 10x mapper, which is distinct from typical short-read mapping. The complication lies in that different genomic regions may be associated with the same barcode. You have to identify these "read cloud" first and then do mapping. Reads in these cloud have no specific order, either.

In general, the 10x mapper has room for improvement. One particular problem is that it uses bwa-mem, which is not good at all mappings. Minimap2 has the potential, but it will take significant efforts to implement. I think someone from the Bonnie Berger group has a better mapper. I thought it was on bioRxiv but could not find it.

**Comment by mcshane** [comment]
http://cb.csail.mit.edu/cb/ema/

**Comment by lh3** [comment]
Thanks, @mcshane. This is what I was talking about. The first author gave a talk at Broad. I think it is quite good, though I haven't used it personally.

**Comment by mcshane** [comment]
Yeah, I haven't tried yet either, but it does look interesting.

**Comment by sjackman** [comment]
Thanks for the pointer to EMerAld (EMA). I'm not familiar with this aligner. I'll check it out.

**Comment by sjackman** [comment]
Back to `minimap2 -y`. Is the FASTQ comment copied to the SAM tag when it's not formatted in a valid SAM tag format? In particular, when the comment is in Illumina bcl2fastq format (`1:N:0:ATCACG`), it'd be good not to copy it to the output and create an invalid SAM file.

I'm writing a pipeline where the reads may either be in `bcl2fastq` format or Longranger basic format, and it'd a nice bonus for the pipeline to be able to use `minimap2 -y` with both, and not have to detect which format the reads are in.

**Comment by lh3** [comment]
I am afraid that you have to do this on your side.

**Comment by sjackman** [comment]
Okay. Thanks, Heng. If I were to implement this feature, would you accept a pull request?

**Comment by lh3** [comment]
Thanks. I will surely consider. Please don't introduce new dependencies, though.
