### ISSUE TITLE
MD FLAG

### ISSUE THREAD

**Issue by tambua81** [lh3/minimap2#137]
Hello,
we have noticed that in minimap2 output there is no MD TAG. We need it for using our pacbio alignment output with pysam module.
Is there possibility to implement this feature in minimap2?
There is also the possibility to filter out chimeras?

Thanx in advance,
Claudio

**Comment by wdecoster** [comment]
The MD flag is optionally added in the GitHub version (but not released yet). See https://github.com/lh3/minimap2/issues/118#issuecomment-375407846

**Comment by lh3** [comment]
Thanks, @wdecoster. Yes, `--MD` is available on github master.
