### ISSUE TITLE
--MD tag log failure

### ISSUE THREAD

**Issue by clalogiudice** [lh3/minimap2#139]
Hello everybody,
I am trying to map my Pacbio reads with minimap2.
Tryiing to add the flag --MD causes a failure in the minimap alignment log...

[M::mm_idx_gen::859.870*0.51] collected minimizers
[M::mm_idx_gen::882.231*0.83] sorted minimizers
[M::main::882.231*0.83] loaded/built the index for 93 target sequence(s)
[M::mm_mapopt_update::886.515*0.83] mid_occ = 663
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 93
[M::mm_idx_stat::889.631*0.83] distinct minimizers: 167026627 (35.39% are singletons); average occurrences: 5.939; average spacing: 3.163
minimap2: forminimap2: format.c:190: write_MD_core: Assertion `op >= 0 && op <= 2' failed.

**Comment by lh3** [comment]
--MD doesn't work with splice alignment because I don't know how to encode introns in MD.

**Comment by tambua** [comment]
Thank you, just another question....
Does the "samtools calmd " command consider introns as indels?

**Comment by lh3** [comment]
I don't know. Although I implemented the initial calmd, I have forgotten the details and the samtools team may have made significant improvements to it. You have to ask the samtools team unfortunately.

**Comment by tambua** [comment]
Thank you for your quick answer, I'll ask them!

**Comment by lh3** [comment]
I have seen your question at samtools/samtools#809. Do you prefer MD to include introns or not to include introns? What's the use case in your mind? Thank you.

**Comment by kehey** [comment]
I get the same error with the `--MD` tag, which is now clear of course. But on the comment above by @SaberHQ: I do get the cs tags when running a spliced alignment with `--cs`

**Comment by lh3** [comment]
@SaberHQ `--cs` has been working for a long time. If it doesn't, please send me an example.

3a119d6 enables --MD to work with spliced alignment. I am closing this issue. If the new code has bugs, please create a new issue.
