### ISSUE TITLE
Adding Read Group Information

### ISSUE THREAD

**Issue by dantaki** [lh3/minimap2#14]
Maybe I missed it in the manual, is there an argument for adding a Read Group tag to reads during alignment? This could be useful because some phasing software that leverages long reads require a read group tag. 

I realize samtools has this capability to add in read group information to a sam/bam file, but it's one step less to include it in the aligning step. 

bwa has this option `-R STR        read group header line such as '@RG\tID:foo\tSM:bar' [null]`, which makes adding read group information easy. 

Thanks!

**Comment by lh3** [comment]
Noted. Will add it at some point. Thanks.

**Comment by lh3** [comment]
Via bbb37d9. Not thoroughly tested, though.

**Comment by dantaki** [comment]
Thank you so much for the quick response
