### ISSUE TITLE
Do you have a recommendation for downstream SV calling, Do it work with Sniffles?

### ISSUE THREAD

**Issue by yongfeng-zhou** [lh3/minimap2#142]
I am interested in calling SVs based on minimap2 mapping. Do you have a recommendation for downstream SV calling? I am using Sniffles (https://github.com/fritzsedlazeck/Sniffles) to call SVs based on ngmlr mapping (https://github.com/philres/ngmlr), but it doesn't work for genome alignment. The curent bam files from minimap2 doesn't work in Sniffles. Do you will have a SV caller for minimap 2  or do you have recommendation what SV caller should I use? 

Thank you!

**Comment by lh3** [comment]
See #137, #118 and fritzsedlazeck/Sniffles#51. Please update to the latest version v2.10 and run minimap2 with "--MD". Let me know if that works. Thanks.

**Comment by yongfeng-zhou** [comment]
Hi Heng

We generated two reference genome fragments with 1m.fa containing a 1Mb
deletion from 500K to 1500K. We observed the DEL using ngmlr + sniffles,
but minimap + sniffles doesn't work. Can you please try? Thank you!

Cheers,
Yongfeng


minimap2 --MD -ax asm5 2m.fa 1m.fa >t.sam
samtools view -ubS t.sam >t.bam
sniffles -m t.bam -v t.vcf --skip_parameter_estimation --min_support 1

**Comment by yongfeng-zhou** [comment]
We sent the fasta file to your email: lh3@me.com, Thank you!

**Comment by yongfeng-zhou** [comment]
My colleague compared ngmlr and minimap2 and found that the XS tag is missing in minimap2 sam files, which lead to the disconnect between minimap2 and Sniffles. Can you please check? Thank you!

**Comment by lh3** [comment]
Could you have a look at fritzsedlazeck/Sniffles#58 and try the latest sniffles?

**Comment by yongfeng-zhou** [comment]
Great! The most recent Minimap2 + the newest sniffles worked! Thank you!

**Comment by lh3** [comment]
It is difficult to ask minimap2 to output the XS tag. Unlike bwa-mem, minimap2 doesn't compute XS for most of alignments. It is possible to emulate XS, but that would be "hacky". It is good to know that the latest sniffles works. Thanks for the confirmation!

**Comment by armintoepfer** [comment]
I believe this can be closed.
