### ISSUE TITLE
Can minimap2 really do glocal alignment ?

### ISSUE THREAD

**Issue by tseemann** [lh3/minimap2#143]
@lh3 In your recent blog post you stated `minimap2` does global alignment.

How can I force this? 
Like `bowtie2 --end-to-end`?
I'm currently using `minimap2 -x sr -a` and still getting soft-clipping *eg.* `16S53M31S`
I can't seem to see anything in the `-h` or the `README.md`.

Any help appreciated!

See also https://github.com/lh3/bwa/issues/64

**Comment by lh3** [comment]
Bwa-mem uses global alignment in aligned regions to reconstruct CIGAR at the end. It doesn't support glocal alignment.

Minimap2 implements a similar but not identical algorithm, but this difference might emulate glocal alignment to some extent. To try that, you may use a large "--end-bonus" like
```sh
minimap2 -axsr --end-bonus=100
```
It worked on a toy example I tried. Please beware that you often need to filter out poor glocal alignments as they may be not real.

**Comment by tseemann** [comment]
Thanks @lh3 I'll see how it goes.

**Comment by sdwfrost** [comment]
Dear @tseemann, how did it go?

**Comment by tseemann** [comment]
@sdwfrost i never really got back to it. in fact i completely lost track of this. thanks for the reminder!
