### ISSUE TITLE
help with complete cigar output

### ISSUE THREAD

**Issue by PGonzo** [lh3/minimap2#149]
I am attempting to find the locations of indels between two human MTDNA sequences. I would like to use the cigar from minimap2 for this purpose. For testing, I downloaded the reference fasta for MTDNA from ensembl and made a copy of it for comparison. When I use the full genome assembly alignment on the two identical reference fastas I get the following cigar: `cg:Z:16569M`. Which is what I expect. When I make a deletion (6NT) and insertion (1NT) a couple hundred nucleotides into my  comparison fasta I get `cg:Z:310M6D1053M3I15200M`. Again, what I expect. 

However, when I make a deletion (4th NT in)  in the beginning of the fasta I get: `cg:Z:16565M`. So the three nucleotides before the deletion are not accounted for in the cigar. I was expecting, perhaps naively `cg:Z:3M1D16565M`.  This behavior occurs when I delete or insert nucleotides at the end of the comparison fasta as well. I downloaded the most recent version of minimap2  and my commands are:`minimap2 -c -x asm5 reference.fasta reference2.fa > aln.paf` . Is there a parameter I should set to enable the ends to align and the cigar to capture everthing from start to finish? 

Thank you for your time. 
Patrick

**Comment by lh3** [comment]
Minimap2 generally does local alignment. A gap towards the end will lead to a lower alignment score, so it is clipped. You can use
```
minimap2 -c -x asm5 --end-bonus=20
```
to ask minimap2 to prefer end-to-end alignment.

**Comment by lh3** [comment]
Just curious: does option --end-bonus solve your problem? Thanks.

**Comment by PGonzo** [comment]
It didn't. I just added 50 nt's to the beginning and end of my reference
and toy reference as a workaround.
Thanks for checking.

**Comment by lh3** [comment]
If that is not working, it should be a bug. Could you send me your sequences? Thanks.

**Comment by PGonzo** [comment]
Ive attached the reference fasta sequence for human MTDNA.  Ive been making
a copy of the attached reference fasta and deleting or inserting
nucleotides from the beginning or end of the fasta copy and then running
minimap2 to see if it captures INDELS in the CIGAR. So far, I cannot get it
to give me the completer CIGAR from end to end.
Thanks for taking a look at this,
Patrick.

**Comment by lh3** [comment]
I have not seen the sequences. Could you send via email to lh3@me.com? Thanks.

**Comment by lh3** [comment]
Stalled. Closing. Please feel free to reopen it if you have followups. Thanks.
