### ISSUE TITLE
use of --secondary option coud be improved

### ISSUE THREAD

**Issue by jeanlain** [lh3/minimap2#150]
Hello,

In my view one usually do not want to output secondary alignments when mapping to reference. However:
- the `--secondary` argument is not listed in `minimap2 -h`. So users will not easily see how this could be controlled and may use `-N 0` instead (though minimap2 now warns they should use the `--secondary` argument).
- It seems the `-x map-pb` and `-x map-ont` presets implicitly use `--secondary=yes`. In my view, they should use` --secondary=no`.  The `-x sr` preset uses ` --secondary=no`. Why should this defer in the long-read presets?
- It seems to me that `--secondary=yes` and `--secondary=no` are somewhat redondant.
They could be replaced by simply `--secondary` (taking no value), whose presence in the command tells secondary alignments will be reported. 

Best,

Jean

**Comment by lh3** [comment]
For short reads, there will often be too many secondary hits to look at. For long reads, there are much fewer. And these alignments are often informative to downstream processing. In my view, we should get used to working with secondary alignments. The default behavior will stay.

> It seems to me that --secondary=yes and --secondary=no are somewhat redondant.
They could be replaced by simply --secondary (taking no value), whose presence in the command tells secondary alignments will be reported.

They are not redundant. With --secondary taking no value, you wouldn't be able to turn on secondary output for short reads.
