### ISSUE TITLE
Is paftools version just r755 ?

### ISSUE THREAD

**Issue by tseemann** [lh3/minimap2#152]
```
paftools.js version
r755
```

Can you confirm this is what you desire?

(i'm updating brew packages to allow `paftools.js` to work out of the box with k8 etc)

**Comment by lh3** [comment]
I would prefer to use the version tagged with [v2.10](https://github.com/lh3/minimap2/tree/v2.10) and so on. I will try to remember to update paftools to something like "2.10-r761" at each release in future.
