### ISSUE TITLE
Suspicious alignments of regions with Ns stretches

### ISSUE THREAD

**Issue by alexeigurevich** [lh3/minimap2#155]
We noticed suspicious alignments of the [attached scaffolded fragment](https://github.com/lh3/minimap2/files/1951322/NM_064705.3_score0.25_extractedTargets.fa.zip) against the C. elegans reference genome (downloaded from here: ftp://ftp.ensemblgenomes.org/pub/metazoa/release-39/fasta/caenorhabditis_elegans/dna/Caenorhabditis_elegans.WBcel235.dna.toplevel.fa.gz).

The running command was: 
`./minimap2 -c -x asm5 -B5 -r 50 --no-long-join -N 50 -s 65 -z 200 --mask-level 0.9 -f 200 --cs Caenorhabditis_elegans.WBcel235.dna.toplevel.fa scaffold.fa`

The fragment includes two stretches of 200 Ns. We expect minimap2 to break the alignment at this stretches since we use `-r 50` and 200 >> 50. However, we get:
`94676_SeqID_1.0_Cov_1.0    40534    0    14850    -    II_dna_chromosome_chromosome_WBcel235_II_1_15279421_1_REF    15279421    15096376    15111253    14366    14577    60    NM:i:611    ms:i:13459    AS:i:13375    nn:i:400    tp:A:P    cm:i:1284    s1:i:12921    s2:i:1163    dv:f:0.0048    cg:Z:268M30I10135M57D1287M70I70D3060M    cs:Z::11*tg:10*cg:1*ag:62*ct:4*cg:2*at:34*at:6*ga:13*tg:5*tc:4*gc:1*ga:23*cg:3*tc:75+nnnnnnnnnnnnnnnnnnnnnnnnnnnnnn*gn*gn*an*an*tn*tn*tn*tn*cn*an*an*tn*tn*cn*cn*gn*gn*cn*an*an*tn*tn*tn*tn*cn*cn*an*an*cn*tn*tn*gn*cn*cn*cn*gn*an*an*an*tn*tn*tn*tn*cn*an*an*cn*tn*cn*cn*gn*gn*cn*an*an*tn*tn*tn*tn*cn*cn*an*an*cn*tn*tn*gn*cn*cn*cn*gn*an*an*an*tn*tn*tn*tn*cn*an*an*tn*tn*cn*cn*gn*gn*cn*an*an*tn*tn*tn*gn*cn*cn*an*an*cn*cn*tn*gn*cn*cn*gn*gn*an*an*an*tn*tn*tn*tn*cn*an*an*tn*cn*cn*cn*gn*gn*cn*an*an*tn*tn*tn*gn*cn*cn*an*an*cn*tn*tn*gn*cn*cn*cn*gn*an*an*an*tn*tn*tn*tn*cn*an*an*tn*tn*cn*cn*gn*gn*cn*an*an*tn*tn*tn*gn*cn*cn*an*an*cn*tn:9965-gaattttgtgtatttcatcaatagaaaggcataatttaagagaaataacaaaaattt*cn*an*an*tn*an*tn*an*an*an*an*cn*an*gn*cn*gn*an*an*an*an*an*an*tn*gn*an*gn*an*an*an*an*an*tn*cn*gn*an*cn*gn*an*an*an*an*tn*cn*gn*gn*tn*an*tn*an*an*an*an*tn*cn*an*an*an*tn*an*an*an*an*an*tn*gn*gn*an*an*gn*gn*an*an*an*an*tn*an*tn*tn*cn*an*tn*cn*tn*cn*gn*tn*an*an*an*cn*cn*cn*an*cn*an*cn*tn*tn*gn*cn*gn*gn*cn*an*cn*gn*gn*tn*tn*tn*cn*gn*tn*gn*gn*gn*cn*gn*gn*gn*gn*cn*gn*tn*cn*tn*cn*tn*gn*gn*cn*gn*gn*gn*an*an*an*an*tn*tn*cn*an*gn*cn*gn*tn*tn*tn*gn*an*an*an*an*cn*tn*cn*an*cn*an*tn*an*tn*an*gn*gn*cn*an*tn*cn*cn*an*an*tn*gn*an*an*tn*tn*tn*tn*cn*gn*gn*an*tn*tn*tn*tn*an*an*an*an*an*tn*tn*an*an*tn*an*tn*an:1087+tgccggaatttataatttccggcaaatcggcaaattgccgaaattaagaatttccggcaaataagcaaat-tgccggaatttataatttccggcaaatcggcaaattgccgaaattaagaatttccggcaaataagcaaat:3060`

The second question is about the last sequences in the end of `cs tag`:
`+tgccggaatttataatttccggcaaatcggcaaattgccgaaattaagaatttccggcaaataagcaaat`
and
`-tgccggaatttataatttccggcaaatcggcaaattgccgaaattaagaatttccggcaaataagcaaat`
look equivalent. Why minimap2 reported them as insertion (+) and deletion (-)?

**Comment by lh3** [comment]
Thanks for the offline example. I have fixed this bug. Along this line, I have added a new option `--score-N` that sets the score involving ambiguous "N" bases. If you prefer to truncate the alignment at shorter N stretches, you can increase this option.

By the way, with recent minimap2, it is recommended to use `--min-occ-floor=200` instead of `-f 200`. This option effectively sets a minimal `-f`. For details, see the [manpage](https://lh3.github.io/minimap2/minimap2.html#5).

**Comment by alexeigurevich** [comment]
Thanks for the new option! It works properly on the example we initially reported (with `--score-N 1` or even better with `--score-N 2` ). 

However, we further investigated this case and found a new related issue. In the original example, there was a stretch of 200 Ns. Since our tool (QUAST) usually breaks contigs at stretches of Ns of length 10 or more, we tried to reduce the stretch in the original sequence from 200 to 20 and to 10 (the  [modified files](https://github.com/lh3/minimap2/files/1970512/examples_10N_20N.zip) are attached; note: the original sequence has 2 stretches of 200 Ns but we are talking here about the first stretch only).
The example with 20 Ns works perfectly, the resulting alignment of length 4217 is:
```
94676    40354    0    4217    -    II_dna_chromosome_chromosome_WBcel235_II_1_15279421_1_REF    15279421    15107036    15111253    4217    4217    60    NM:i:0    ms:i:4217    AS:i:4217    nn:i:0    tp:A:P    cm:i:422    s1:i:4173    s2:i:70    dv:f:0.0621    zd:i:2    cg:Z:4217M    cs:Z::4217
```

At the same time, the example with 10 Ns gives us the strange short alignment of length 143:
```
94676    40345    0    143       -    II_dna_chromosome_chromosome_WBcel235_II_1_15279421_1_REF    15279421    15111215    15111358    140    143    1    NM:i:3    ms:i:125    AS:i:125    nn:i:0    tp:A:P    cm:i:5    s1:i:41    s2:i:0    dv:f:0.2182    cg:Z:143M    cs:Z::40*tg*tg:21*tc:79
```

The running commands were:
`minimap2 -c -x asm5 --score-N 2 -B5 -O4,16 --no-long-join -r 50 -N 50 -s 65 -z 200 --mask-level 0.9 --min-occ-floor 200 --cs Caenorhabditis_elegans.WBcel235.dna.toplevel.fa  example_20N.fa`
and
`minimap2 -c -x asm5 --score-N 2 -B5 -O4,16 --no-long-join -r 50 -N 50 -s 65 -z 200 --mask-level 0.9 --min-occ-floor 200 --cs Caenorhabditis_elegans.WBcel235.dna.toplevel.fa  example_10N.fa`

Use of scores higher than 2 does not fix the issue. Anyway, the fragment of length 4217 (the first alignment) does not include Ns.

**Comment by lh3** [comment]
Thanks again for the example. That tiny alignment is caused by false chaining. Minimap2 finds the main chain, but then extends it into ~4kb regions containing only a few anchors.

A way to fix this is to use a smaller `-g`, such as `-g 1000`. By default, `-g` is 5000. Minimap2 will extend a chain even if there are no anchors in 4999bp. Because you are working with highly similar sequences, it is unlikely (though not impossible due to repetitive k-mers) that an alignment you want contains no anchors in 5kb. Using a small -g gives you tighter but occasionally fragmented alignments.

**Comment by alexeigurevich** [comment]
Thanks for the explanation! It works correctly with `-g 1000`. You are right about our use case with highly similar sequences, so we will probably use this or similar threshold in our tool.
