### ISSUE TITLE
Cigars of secondary alignments are always set to the primary one

### ISSUE THREAD

**Issue by ilya-kolpakov** [lh3/minimap2#157]
I have noticed that the secondary alignments do not have informative cigars:
```python
# Realign a sequence from human chrM from hg19
In [72]: q = a.seq('chrM', 2500, 2600)

# Secondary alignments have mismatches but their cigar strings do not reflect that
In [73]: print('\n'.join(map(str, a.map(q))))
0       100     +       chrM    16571   2500    2600    100     100     54      tp:A:P  ts:A:.  cg:Z:100M
0       100     +       chr6    171115067       62284098        62284198        97      100     0       tp:A:S  ts:A:.  cg:Z:100M
0       100     -       chr3    198022430       96336151        96336251        96      100     0       tp:A:S  ts:A:.  cg:Z:100M
```
Is it a bug or by design? Is there a way to get informative cigars for all alignments?

**Comment by lh3** [comment]
What do you mean by "informative cigars"? "100M" is the right CIGAR for all three alignments.

**Comment by ilya-kolpakov** [comment]
I see there is a PR https://github.com/lh3/minimap2/pull/156actually

**Comment by ilya-kolpakov** [comment]
Thanks for the explanations.

Exposing `cs` to mappy is not a priority for me as well, but I would be interested in having access to `cs` tags when using minimap from C/C++. What is your opinion on changing the current code so that instead of `cs` tag being rendered into a string one would create an array of c structs first?

This intermediate representation could be used by library users and it would make it easier to expose to Python in meaningful way.

**Comment by lh3** [comment]
With #156 effectively merged (with small changes), I am closing this issue. Thanks a lot for participating the discussions, which has helped the decision making.
