### ISSUE TITLE
Support for new PacBio BAM format?

### ISSUE THREAD

**Issue by Adamtaranto** [lh3/minimap2#159]
Hi Heng,

Do you have any plans to support the new [PB unaligned BAM](http://pacbiofileformats.readthedocs.io/en/5.0/BAM.html) format as a MiniMap2 input? 

The old .h5 format is being phased out and all Sequel Subreads are now given as PB BAM. This new format does not contain quality scores for individual subreads (All Phred scores default to 0 when converted to FASTQ) but does contain tags with per base pulse information that is used by Arrow for genome polishing.

It would be great if MiniMap2 could map Subreads from PB BAM and add the pulse tag data back to the final SAM alignment.

Thanks,
Adam

**Comment by lh3** [comment]
Minimap2 won't support pbbam. Nonetheless, various pacbio developers are using minimap2 internally. I am not sure if they have any plan to use minimap2 with Arrow – blasr alignment is quite slow for mammalian genomes. There is also [pbmm2](https://github.com/nlhepler/pbmm2), though there is no recent development.

I am pinging @armintoepfer to see if he has insider information ;-).

On a technical note, the multi-threading model of minimap2 is rather primitive. If vendors want to use minimap2, it may be a better idea to call minimap2 C APIs. Doing this way can be more efficient and flexible.

**Comment by armintoepfer** [comment]
Once we have extended cigars, there's a possibility to wrap stock mm2 in C++ and allow PacBio BAM I/O.

**Comment by lh3** [comment]
While I haven't run pbmm2, I have heard successful stories by other users. I am closing this. Please feel free to reopen it or create new issues if you have further concerns.
