### ISSUE TITLE
-O and -E

### ISSUE THREAD

**Issue by meyermj** [lh3/minimap2#160]
What are the two, comma-separated parameters after each of these flags (gap-open and gap-extend)? Is one for deletions and one for insertions? I notice these are not altered from their defaults in `ava-pb` and `ava-ont`. Are they tuned for these long-read platforms, even taking into account the different error profiles of PB and ONT?

**Comment by lh3** [comment]
See the command line help:
```
    -O INT[,INT] gap open penalty [4,24]
    -E INT[,INT] gap extension penalty; a k-long gap costs min{O1+k*E1,O2+k*E2} [2,1]
```
The [minimap2 preprint](https://arxiv.org/abs/1708.01492) gives more information. These are not for deletions/insertions.
