### ISSUE TITLE
different result with/without -c option

### ISSUE THREAD

**Issue by asdcid** [lh3/minimap2#161]
Hi, 

It seems that the result (paf format) seems to be different if I use -c (output CIGAR in PAF) or not?

with -c
9f7fe1f6-8587-4ca1-a822-ac6e240697c1    32512   1219    32496   +   lsc1ir0ssc1ir1lsc1  248725  138220  171175  26704   34623   0   NM:i:7919   ms:i:20036  AS:i:20036  nn:i:0  tp:A:P  cm:i:417    s1:i:4001   s2:i:4001

without -c
9f7fe1f6-8587-4ca1-a822-ac6e240697c1    32512   1293    32478   +   lsc1ir0ssc1ir1lsc1  248725  138295  171154  4376    33026   0   tp:A:P  cm:i:417    s1:i:4001   s2:i:4001

command I used:
'''
minimap2 \
    -x map-ont \
    --secondary=no \
    -t $threads \
    -L \
    -c \
    $ref \
    $inputFile > $outputFile
'''

Cheers,
Raymond

**Comment by lh3** [comment]
I thought someone has asked this before, but I couldn't find it. Anyway, option `-c` does a whole lot more operations. Using `-c` or not always leads to different results.
