### ISSUE TITLE
Option C5 in PacBio Iso-seq/traditional cDNA alignment

### ISSUE THREAD

**Issue by machalen** [lh3/minimap2#162]
Hi

Could you explain what the option -C5 means in the call recommended for PacBio Iso-seq/traditional cDNA:

`minimap2 -ax splice -uf -C5 ref.fa iso-seq.fq > aln.sam`

I didn't find in --help any option -C ,  I am using minimap2 v.2.10.

Thank you,

**Comment by lh3** [comment]
See [here](https://lh3.github.io/minimap2/minimap2.html#6).

**Comment by machalen** [comment]
Thanks! Sorry.. now I see there is a full manual. Could you explain why it is set with 5?

**Comment by lh3** [comment]
Based on evaluation.

**Comment by lh3** [comment]
I am closing this issue. Thank you.
