### ISSUE TITLE
How to keep unmapped reads

### ISSUE THREAD

**Issue by ssilva1** [lh3/minimap2#163]
Hi! I want to subtract the PacBio reads that map to a given genome and keep only the unmapped reads for subsequent assembly. Can this be done? 

Thanks

**Comment by lh3** [comment]
Output in the SAM format (option "-a"). You can get unmapped records in SAM.

**Comment by tseemann** [comment]
@ssilva1 `minimap2 -a REF R1 R2 | samtools sort | samtools view -f 4 | samtools fastq -s R0' -1 R1' -2 R2'` or something similar

**Comment by ssilva1** [comment]
Thanks all, output to sam and then samtools view -f 4  worked well.

**Comment by tseemann** [comment]
@ssilva1 can you close this issue now? thanks!

**Comment by rbutleriii** [comment]
I am trying to use minimap2 to filter contaminant nanopore reads with a contaminant fasta. I tried the above, plus several similar syntaxes, but I cannot get the samtools fastq command to work. 
`minimap2 -ax map-ont contaminant.fasta nanopore.fastq.gz | samtools sort | samtools view -f 4 | samtools fastq -1 clean.fastq.gz`

**Comment by rbutleriii** [comment]
It looks like from some checking, the samtools fastq cannot accept a piped input. In v1.9 it lets you know no input specified. I was able to pipe it through samtools view, but then no further. However, newer versions of samtools allow you to specify the -f 4 or -F 4 flags for unmapped and mapped, respectively. So I ended up with:
```
minimap2 -ax map-ont contaminant.fasta nanopore.fastq.gz > nano.contam.sam
samtools fastq -n -f 4 nano.contam.sam | pigz > nano_clean.fastq.gz
```

**Comment by lh3** [comment]
Samtools fastq can accept a piped input. Use `-` or `/dev/stdin` as the file name like:
```sh
some_tools | samtools fastq - > output.fq
```
I am always hesitant to skip file names because most tools don't automatically test if stdin is available.

**Comment by rbutleriii** [comment]
Excellent, thanks for the help. So then minimap2 contaminant filtering becomes:
`minimap2 -ax map-ont contaminant.fasta nanopore.fastq.gz | samtools fastq -n -f 4 - > nano_clean.fastq.gz`

**Comment by tayabsoomro** [comment]
Could anybody please explain what the `4` in `samtools -n -f 4` means?

**Comment by PanZiwei** [comment]
> Could anybody please explain what the `4` in `samtools -n -f 4` means?

"4" means unmapped reads, see more details at https://www.samformat.info/sam-format-flag

**Comment by clmattson** [comment]
Hi, so I'm a bit confused. I am also trying to decontaminate Oxford Nanopore (and therefore long, unpaired) reads. It seems like the above command(s) filter out singleton reads from the BAM file, not unmapped. From examining my BAM files, it seems like a significant % of reads (~10%) map to my contaminant reference genomes, but when I reun the above the command the output says " discarded 0 singletons" and no reads are filtered out. Any ideas? I used `-f 4` with `samtools fasta`

**Comment by cement-head** [comment]
@rbutleriii Is there a way to filter the unmapped reads _and_ keep the R1 and R2 information?
