### ISSUE TITLE
`__version__` for `__mappy__`

### ISSUE THREAD

**Issue by jbloom** [lh3/minimap2#165]
Would it be possible to add a `__version__` string (e.g., `mappy.__version__`)? This is the standard way of accessing version numbers for Python modules / packages:
https://www.python.org/dev/peps/pep-0396/

This would facilitate writing larger Python packages that use `mappy` as a dependency.

**Comment by lh3** [comment]
Could you send a pull request? Thanks.

**Comment by ilya-kolpakov** [comment]
I can expose a version from here
https://github.com/lh3/minimap2/blob/154d2caf5bb682b8030229a7eba8f2500316460f/main.c#L13
as a `LooseVersion` as per [PEP-386](https://www.python.org/dev/peps/pep-0386/).

I am not sure how well this versioning scheme would integrate with the Python packaging ecosystem though.
