### ISSUE TITLE
single strand mapping --for-only option

### ISSUE THREAD

**Issue by dandepledge** [lh3/minimap2#166]
The MiniMap 2.1 documentation makes mention of a --for-only option which is super helpful in mapping to transcriptomes. However, this option does not appear to be recognised by any recent versions of minimap2. 

Can you reinstate it?

**Comment by lh3** [comment]
Thanks a lot for the example. I believe the bug has been fixed. It was introduced by a faster merging algorithm specific to short reads. For v2.10, you can add option `--heap-sort=no` to use the default merging algorithm. It is not affected by this bug.

**Comment by yupenghe** [comment]
Thanks! It is solved.
