### ISSUE TITLE
problem aligning query with long gap relative to target

### ISSUE THREAD

**Issue by jbloom** [lh3/minimap2#167]
I am trying to align queries that sometimes have large gaps (e.g., several hundred nucleotides) relative to the target. These are not due to splicing, they're due to deletions in the query relative to the target.

But ather than getting one alignment back with the large gap, I get two slightly overlapping alignments in the PAF file that each cover part of the query.

For instance, below is what happens if I align a query that should cover nt 0-94 and nt 654-1000 of the target, with a gap of 560 nt in between. Instead, I get two lines in the PAF file, each covering a different part (see below). This happens no matter how much I play around with the options, including doing things such as using `--secondary=no` to avoid secondary alignments, using `-O6,40 -E1,0` to avoid penalizing large gaps, or using large values for `-g` or `-r`.

I don't understand this behavior. Just looking at the two PAF alignments visually it's obvious that they should be one perfect alignment with a large gap in the middle:

```
query47 440 94  440 +   target  1000    654 1000    346 346 60  NM:i:0  ms:i:346    AS:i:346    nn:i:0  tp:A:P  cm:i:71 s1:i:338    s2:i:0  dv:f:0.0009 cg:Z:346M   cs:Z:=TGTATGCTACAGTTAAATAGAAAGGCCGCATTGTCGTTCTCGCCCTGTTTTCCTCATACACGACCGAGGTTATTTGTCGGAAACGAGACATCTCTCGAAGGTGGAACGACGCCGGGTGTGCAGAATTTATTTTAAACACTCTATTACCTCCGGGTAGCGTTGGCAAACTCCGATAATGAGCGCCAGGCGTGCCAGGACTCCACCTCCCCTGCTAAGTTGACCTTGAGCTCGGTACAGCGTCGGCGAGACGATAACAACGAAGTCCTTCGGCGTTATGTAATTCACCAGCCCACCATATCAGGTAATAGGCTCGCTGGTTAGGTAGATTATGTAAGAGGCGTGCAGC
query47 440 0   98  +   target  1000    0   98  97  98  60  NM:i:1  ms:i:95 AS:i:95 nn:i:0  tp:A:P  cm:i:13 s1:i:85 s2:i:0  dv:f:0.0049 cg:Z:98M    cs:Z:=TTAGTTGTGCCGCAGCGAAGTAGTGCTTGAAATATGCGACCCCTAAGTAGGAGCGTATGCGCCCAGTAACCAATGCCTGTTGAGATGCCAGACG*ct=GTA
```

**Comment by lh3** [comment]
It is theoretically possible to tune parameters to give one alignment. However, I wouldn't recommend that. When aligning against a whole genome, you will get many false indels when you force aligner to align a 550bp deletion with only 98bp flanking. You should get used to such multi-part alignments. You need to deal with such alignment anyway when calling long indels.

**Comment by KyleStiers** [comment]
I would like to follow up on this. I am trying to detect potentially long deletions (anywhere from 10-10kb+) from amplicon sequencing data. I've found that the splice preset detects things pretty accurately, but I am using Illumina reads - so this is obviously not the right way to go about it.

I understand that for whole genome applications this may cause many false indels, but in amplicon sequencing that isn't a concern. Is there a way to tune minimap2 to this scenario? If you'd still recommend handling of this by multi-part alignments is there a best-practice method for doing so? Perhaps that's in the realm of de-novo assembly from short reads for variant calling?
