### ISSUE TITLE
Unusual behaviour using kseq.h

### ISSUE THREAD

**Issue by ralowe** [lh3/minimap2#169]
I am working on incorporating minimap2 using the C API. I have come across an unusual issue when loading multiple sequences using kseq.h

As soon as I declare a function to load a secondary file

```
void load_in_sequence(char *argv[]){
    gzFile f1 = gzopen(argv[1], "r");
    assert(f1);
    kseq_t *kseq1 = kseq_init(f1);
    while (kseq_read(kseq1) >= 0) {
    }
}
```

but still use the below code to read in the query data:

```
    gzFile f2 = gzopen(argv[2], "r");
    assert(f2);
    kseq_t *query = kseq_init(f2);
```

The mapping function no longer provides a hit. Note I do not even run the function above but just include in the code. As soon as I comment out the function my code returns to giving me a correct hit for my alignment. I have a small reproducible example if needed.

**Comment by lh3** [comment]
> I have a small reproducible example if needed.

That would be great. Thank you.

**Comment by ralowe** [comment]
Hey,

Please find attached. This is the commented out version and as soon as you include the function (even when it is not run). No hit is found.

Including ref.fa but it isn’t actually needed as nothing is done with it at present. Compile instructions:

curl -L https://github.com/lh3/minimap2/archive/v2.10.zip > minimap2.zip
unzip minimap2.zip
cd minimap2-2.10
make libminimap2.a
cd ..
gcc -g -O2 main.c minimap2-2.10/libminimap2.a -lz -I minimap2-2.10/

Then run:

./a.out ref.fa query.fa

Output should be (when function removed):

query1 60 0 60 + FOO 180 60 120 60 60 32 cg:Z:60M

No output when function included.

Thanks,
Rob




On 30 May 2018, at 16:22, Heng Li <notifications@github.com<mailto:notifications@github.com>> wrote:


I have a small reproducible example if needed.

That would be great. Thank you.

**Comment by lh3** [comment]
Apparently you haven't put your "main.c" here?

**Comment by ralowe** [comment]
Sorry replied via email. Hopefully this works.

[togithub.zip](https://github.com/lh3/minimap2/files/2055570/togithub.zip)

**Comment by lh3** [comment]
Your main.c doesn't show where `load_in_sequence()` is called. At my hand, everything seems ok so far.

**Comment by ralowe** [comment]
Doesn’t need to be called. Do you get the same output when commented and uncommented? The version I gave produces output until method is uncommented

**Comment by ralowe** [comment]
e.g.

[main_nohit.c.zip](https://github.com/lh3/minimap2/files/2055626/main_nohit.c.zip)

**Comment by lh3** [comment]
I see. You need to set the default first and then apply a preset. For example:
```c
mm_set_opt(0, &iopt, &mopt);
mm_set_opt("sr", &iopt, &mopt);
```
When you see errors like this, try valgrind or address sanitizer.

**Comment by ralowe** [comment]
Doesn't seem to fix it for me?

[main_nohit.c.zip](https://github.com/lh3/minimap2/files/2057061/main_nohit.c.zip)

**Comment by lh3** [comment]
Show me valgrind output.
