### ISSUE TITLE
Multimapping reads: no sequence and quality scores for all but first alignment

### ISSUE THREAD

**Issue by wdecoster** [lh3/minimap2#17]
Hi,

I'm not sure if it's a bug, but for me, this was for sure unexpected behaviour.

I just installed minimap2, so I'm using version `2.0-r301-dirty`
I noticed that for a multimapping read (in my example mapping to 6 locations) only the first aligned read gets the sequence and quality in the bam/sam output. The remaining 5 have the CIGAR, followed by the tags. I am using the NA12878 ONT dataset downloaded from [here](https://github.com/nanopore-wgs-consortium/NA12878).

A single read provoking this can be found [here in my dropbox](https://www.dropbox.com/s/kom4wdsy10u3eq8/provokingread.fastq.gz?dl=0).

The bam file obtained from this read can be found [here in my dropbox](https://www.dropbox.com/s/qthlu11ns8mynyq/provokingread.bam?dl=0).

The command I used was:
`minimap2 -ax map10k -t 48 Homo_sapiens.GRCh38.dna.primary_assembly.fa provokingread.fastq.gz > provokingread.sam`

Cheers,
Wouter

**Comment by wdecoster** [comment]
Should have looked earlier in the closed issues, my issue is probably the same as in https://github.com/lh3/minimap2/issues/4

If this is then as expected, I'll have to adapt my script for extracting features from bam file.

**Comment by lh3** [comment]
This is the default behavior of BWA-MEM to avoid large output when many reads have many multi-mappings. In future, I may add an option to output SEQ and QUAL for multi-mappings, too.

**Comment by wdecoster** [comment]
Okay then, thanks for your quick reply!

**Comment by lh3** [comment]
> This is the default behavior of BWA-MEM

Well, this sentence is not exactly right. BWA-MEM does not output multi-mappings by default. When you ask it to output them with `bwa mem -a`, bwa-mem write SEQ and QUAL as `*`. Minimap2 outputs multi-mappings by default (and you can't switch the feature off for now without losing accuracy). The quoted sentence only means that minimap2 multi-mappings are formatted the same way as bwa-mem multi-mappings.

**Comment by wdecoster** [comment]
Thanks for clarifying, that explains why I haven't encountered this when using bwa mem -x ont2d alignments.
