### ISSUE TITLE
Info multimapping reads

### ISSUE THREAD

**Issue by KristinaGagalova** [lh3/minimap2#170]
Hi
I cannot find this info anywhere: How does Minimap2 deal with multimapping reads?
Thank you in advance for the reply

**Comment by lh3** [comment]
What do you mean by "deal with"?

**Comment by KristinaGagalova** [comment]
I am sorry for the "poor" explanation. 

My question is, all referring to short reads alignments: 
1) Is there an option to output multimapping reads i minimap2?
2) How does minimap2 behave at default mode with multimapping reads?

**Comment by lh3** [comment]
> Is there an option to output multimapping reads i minimap2?

Option `--secondary=yes`.

> How does minimap2 behave at default mode with multimapping reads?

No multimapping by default.

**Comment by KristinaGagalova** [comment]
Do you mean "secondary==multimapping"? 
Multimapping is when the alignment scores are identical for 2 alignments; secondary is when there is a secondary alignment that has a lower score than the primary, the sequence is still very alike. 

What do you exactly mean by secondary in minimap?

**Comment by lh3** [comment]
> Do you mean "secondary==multimapping"?

Yes, see the SAM spec. Your definition is not right.

**Comment by lh3** [comment]
Actually, SAM secondary flag is not exactly multimapping, but either way, minimap2 just follows the SAM spec.
