### ISSUE TITLE
Minimap2 ONT parameters

### ISSUE THREAD

**Issue by npavlovikj** [lh3/minimap2#172]
Hi,

I am comparing few nanopore aligners on ONT 1D and ONT 2D data, so I would like to verify if the general command below is correct for those types of reads
**minimap2 -ax map-ont --MD ref.fasta input.fasta > output.sam**
or I need to specify some other parameters as well.

I would highly appreciate your input on this.

Thank you,
Natasha

**Comment by tseemann** [comment]
Are 2D ONT reads still "a thing" ?  
I recall there was some patent issue with Pacbio?

I looked at a competing ONT aligner tool:
https://github.com/isovic/graphmap
and it doesn't seem to use different settings for 1D or 2D.
I don't think people are using 1D^2 much either.

**Comment by npavlovikj** [comment]
Thanks @tseemann !
From R9.5 chemistry I think the 2D reads are completely replaced with 1D^2 ones (not sure if this is because of the dispute with PacBio, or because of improved accuracy).
R9.5 is new chemistry though, so I agree that 1D^2 are not that common yet.
I am working with simulated data, so I do have both 1D and 2D reads generated from older chemistries.
I find these 2 read types most frequently used in recent publications as well.
As far as I know, minialign is the only nanopore aligner that has different flags for 1D and 2D reads (-x ont.r9.1d, ont.r9.2d).
I just wanted to verify my command in case there are certain parameters I might be missing that can change the results for 1D and 2D reads.

**Comment by tseemann** [comment]
Many of the parameters from `minialign` will have corresponding parameters in `minimap2`, so you could theoretically compare the preset value for `map-ont` with those.

**Comment by lh3** [comment]
As @tseemann said. Thanks!
