### ISSUE TITLE
 mm_idx_reader_read indexes only the first sequence in a FASTA file

### ISSUE THREAD

**Issue by ilya-kolpakov** [lh3/minimap2#173]
When I call
```C
mm_idx_reader_t *r = mm_idx_reader_open(fname, iopt, 0);
mm_idx_t *idx = mm_idx_reader_read(r, n_indexing_threads);
```
on FASTA file with multiple sequences (e.g. [test/q-inv.fa](../blob/734ac379bb942da8118cd404d133f4305835721c/test/q-inv.fa)) I get `idx->n_seq == 1` meaning that only the first sequence is indexed.

Is it a bug or as intended?

P.S. On 734ac379bb942da8118cd404d133f4305835721c
EDIT: meant [test/q-inv.fa](../blob/734ac379bb942da8118cd404d133f4305835721c/test/q-inv.fa) not `t-inv.fa`

**Comment by lh3** [comment]
Is this still an issue? If so, have you initialized `iopt`?

**Comment by lh3** [comment]
Staled. You can reopen the issue if you still have the issue.
