### ISSUE TITLE
Unused reads

### ISSUE THREAD

**Issue by Cbdinh** [lh3/minimap2#178]
Is there a way to retrieve the reads used or unused by minimap2/miniasm that resulted in the contigs?
I want to take a look at the difference between these groups of reads.

I am using the standard minimap for long reads (-Sw5 -L100 -m0) or minimap2 with the standard/ONT settings and standard miniasm. It would be interesting if I could get a more verbose output with miniasm to see the reads included at the crude vs fine read selection stages.

Thank you for any help and sorry if I'm missing something in the documentation.

**Comment by lh3** [comment]
Sorry. That is not possible. It is technically difficult to say what reads are used due to their redundancies.
