### ISSUE TITLE
Suitable parameters for -x asm1 ?

### ISSUE THREAD

**Issue by tseemann** [lh3/minimap2#179]
I am wishing to do self-alignment to find repeats within a single genome at ~ 1% divergence level.

The current 5% and 10% divergence presets are:
```
asm5: -k19 -w19 -A1 -B19 -O39,81 -E3,1 -s200 -z200 (asm to ref mapping; break at 5% div.)
asm10: -k19 -w19 -A1 -B9 -O16,41 -E2,1 -s200 -z200 (asm to ref mapping; break at 10% div.)
```
My guess for a 1% preset is to use `-A1 -B99` but I am unsure, and the gap penalties I'm not sure what the modelling is there.

Any suggestions welcomed!

**Comment by lh3** [comment]
Use asm5.
