### ISSUE TITLE
multiple secondary hits with tp:A:P tag

### ISSUE THREAD

**Issue by colinbrislawn** [lh3/minimap2#181]
Good morning,

I'm aligning nanopore reads using this command:
```
minimap2 -x map-ont ref.fasta pass_barcodes.fastq.gz \
-t 4 --secondary=no > mapminimap2.paf
```

In my output file, I'm seeing multiple entries for some queries, like this query what has 19 lines in the PAF file. 

```
2e7199cf-7da9-41ab-a2f7-7338a15dc113	152401	43586	79486	-	NZ_CP007799	5441200	3307774	3344847	7156	37455	60	tp:A:P	cm:i:737	s1:i:6825	s2:i:385	dv:f:0.1473
2e7199cf-7da9-41ab-a2f7-7338a15dc113	152401	79678	112874	+	NZ_CP007799	5441200	3307656	3344404	6347	36857	60	tp:A:P	cm:i:617	s1:i:5635	s2:i:97	dv:f:0.1548
2e7199cf-7da9-41ab-a2f7-7338a15dc113	152401	17958	31850	+	NZ_CP007799	5441200	3363762	3377955	3610	14380	60	tp:A:P	cm:i:348	s1:i:3502	s2:i:0	dv:f:0.1335
2e7199cf-7da9-41ab-a2f7-7338a15dc113	152401	123533	136449	-	NZ_CP007799	5441200	3363713	3377989	2365	14314	60	tp:A:P	cm:i:231	s1:i:2094	s2:i:0	dv:f:0.1572
2e7199cf-7da9-41ab-a2f7-7338a15dc113	152401	4776	10748	-	NZ_CP007799	5441200	3356808	3362956	1452	6204	60	tp:A:P	cm:i:158	s1:i:1402	s2:i:246	dv:f:0.1307
```

How should I interpret multiple entries when using `--secondary=no`?

**Comment by lh3** [comment]
These are chimeric alignments. Please see the [SAM spec](https://samtools.github.io/hts-specs/SAMv1.pdf) section 1.2 for details. It is not rare to see a 100kb read having a few alignments.

**Comment by colinbrislawn** [comment]
OK! We have added a plasmid to these microbes, so we expect parts of reads to not align to the reference.

How does minimap2 differentiate between a 'chimeric' alignment and a 'secondary' alignment? Do you have recommendations for dealing with duplicates?

**Comment by lh3** [comment]
> How does minimap2 differentiate between a 'chimeric' alignment and a 'secondary' alignment?

Whether two alignments have large overlaps on the query. The exact details can be messy.

> Do you have recommendations for dealing with duplicates?

What do you mean by "duplicates"?

**Comment by colinbrislawn** [comment]
OK, so when different parts of the query align to the same part of the target, the sequence could be considered chimeric. Got it. Thank you for explaining all of this to me. 

I guess saying duplicates is confusing. I was thinking of the reads that report multiple mapping locations or possible chimeras, but these are all different (not duplicates). Do you have any recommendations for managing multiple mapping locations? Do you pick the longest alignment, or greatest residue matches, or only use the reads that map to a single location?

Thank you for all your help. I really appreciate your guidance!
