### ISSUE TITLE
meaning of -u n

### ISSUE THREAD

**Issue by phiweger** [lh3/minimap2#182]
Setting the `-un` flag, does that mean that minimap2 will not consider canonical splice sites at all? I.e. ist it possible to detect non canonical splice site w/ this option?

Thank you!

**Comment by lh3** [comment]
> Setting the -un flag, does that mean that minimap2 will not consider canonical splice sites at all?

Correct.

> ist it possible to detect non canonical splice site w/ this option?

Minimap2 doesn't require canonical sites; it just prefers it. I would recommend to reduce option `-C` instead. With something like `-C5` or even smaller, you will see more non-canonical splice sites.

**Comment by phiweger** [comment]
Thank you very much for your quick answer. I will test setting different values for `-C`.

**Comment by zhenLiuExplr** [comment]
I have question about the `-u` and `-C`. Would I get two identical alignment results if I set one with `-un` and another with `-C0`? I test some nanopore reads with one set parameters `-x splice -un -C9` and another `-x splice -ub -C0`. They get similar alignment results but not identical. What cause the difference?
