### ISSUE TITLE
cs-string support for mappy

### ISSUE THREAD

**Issue by cvdelannoy** [lh3/minimap2#183]
I like the cs-string optionally generated by minimap2 to assess mismatches. Can we get the option to generate cs-strings in mappy as well?

**Comment by lh3** [comment]
It is hard to expose the cs tag to mappy due to the internal data structure of minimap2/mappy. I will think about it but can't make promise.

**Comment by lh3** [comment]
Done on the master branch. To enable the cs output, you need to add `cs=True` when calling `Aligner.map()`. Mappy doesn't write cs by default.

```python
a = mp.Aligner("ref.fa")
for hit in a.map(seq, cs=True):
    print("{}\t{}\t{}\t{}".format(hit.ctg, hit.r_st, hit.r_en, hit.cigar_str))
```

I am closing this issue. If you see bugs, please create a new issue. Thank you.
