### ISSUE TITLE
Comparison of int vs. u_int has different results under different compilers

### ISSUE THREAD

**Issue by CptApature** [lh3/minimap2#184]
I've been running minimap2 on different machines and getting different results, which I've been able to narrow down to an inconsistent comparison between signed and unsigned ints; in particular in `ksw2_extd2_sse.c:393 ... (int)ez->mqe + (int)end_bonus > (uint)ez->max` 

If the left-hand side is a negative value:
- Under GCC the right-hand side is implicitly cast to `int` and so `-2 < +1`
- Under MSVC the left-hand side is implicitly cast to `uint` and so `2 > 1`

I believe the GCC result to be the one you intended? This can be trivially fixed by explicitly casting to `int` to make the operation safe, I can put in a pull request if you'd like?

There are a couple of other places in the code where this occurs (throwing a compiler warning) but doesn't cause me any problems in results. The majority of these seem fine (comparing to `i` in for loop, comparing seq_lens, explicitly checked to be >0) but there are two others that might be worth casting an eye over as I'm not 100% certain of the intended behaviour:
```
ksw2.h:170
pe.c: 162, 163, 167
```

-----------------------------------------------------------
I've made a small(ish) test to reproduce the behaviour
```
# file: ref.fasta
>Ecoli_short
TTTCCCGGGTCATAGTGTTCATCGTTATCAGATGATTCCACCCAGCCGCTGTATTTAAATGTGCCACCGAGTTCAAAATCTTCATAACGATAACTTCCAGTCAAGCCAATGTAGGGCATTTTAAAACGTTGTTTGTAGCCGATTGCTCTTTCTCCATTCGGGAAGGAGCCGATATCATCTCTGAATCCCTCCTCAGAACTGTAGATATAGGAACCACCTCTGGCTGTAAAGCTATAACGGCTTTCCTGATATCCGGCCATGAGTCCCAGGCGGTAATTGGGTTCGTTGAGGAGCCAGCCTTTGATATTCAGATCAAATTCGTTGGCATAATTGAGTTGTGTATCAGGGTGTCTACTTTCATCCGTCCAGGTTCCGGGGTTACTGGAATCCATCCAGTCCTGATCGACCATATTGCCACCTCGGCTGCCGAGAGTTGTCCAGCCAGCAGCCCCGATAGATATCTGGGGCATCAAATCCCAATTAATTGCACCTTTAATAA
```
```
# file: query.fasta
>query_sequence
AAAGATGTATCCCTTTTTGACTGGTTGACTCATACACCCTCGATGTACTTTTGCCTCTGGGGTAATATAAACCGGCATTAACTGCAGCAAGAGATAAGTAATTCTGGTTTATTACTTTAACTTCGGAATGTAGTTTGTCTTACCTAATGCTCATCATTATCAGATTTCGTGACCCACCCGCTGTATTTAAATGCACCACCAAACTCAAATTATCGTAACGGTAGTTTCCTGTCAGACCGACACCTGAGGGAATTTTAAAATGTTGTTTATAACCAATCACTTTTATTTTATCAAGGTAACGCTCCCGTTTCATTCGGAAACCACCATTCTCACTATAAGTATAAGTTCCTCCTGTAGCATTAAAACTGTAACGGCTTTCCTGATAACCTGCCATAATAGCAAGGCGATAATCAGATTCTTTTAAAAACCAGCCTTTAACGTTCAAATCCAAATTCGTTGGCATAATTAGGAGCGTGTATCAGGATGCACTGCT
```
`./minimap2 -a ref.fasta query.fasta`

In the first pass
```
mqe = -134, end_bonus = -1, max = 30
mqw + end_bonus > max
> True (using MSVC)
> False (using GCC)
```
This results in the following different CIGAR strings:
```
GCC:           150S 15M 2D 3M
MSVC: 4M 1I 3M 142I 15M 2D 3M ...
```
It looks like the GCC implementation is doing something more sensible.

**Comment by lh3** [comment]
Thanks. Please let me know if 7e6e8ca has issues.

**Comment by CptApature** [comment]
Just doing some testing, looks like `ssize_t` is not implemented by the MSVC compiler as it's not C-standard, but it can be imported by:
```
//sdust.cL.9
#if defined(_MSC_VER)
#include <BaseTsd.h>
typedef SSIZE_T ssize_t;
#endif
```

Following that fix I can confirm that r794 now gives the same results on windows and linux. 

It gives different results to v2.10-r761, however, is that expected due to other changes? I haven't dug into the details of the differences.

**Comment by lh3** [comment]
I have got rid of `ssize_t`. It is not necessary. r794 occasionally produces different results from r761, hopefully for good. The overall alignment statistics remain similar.

**Comment by CptApature** [comment]
Great - thanks. Small size test shows that works.
I'll do some testing of v2.11 with a bit more data and let you know if I have any further issues
