### ISSUE TITLE
mapping cDNA for genotyping: options recommendation

### ISSUE THREAD

**Issue by wheaton5** [lh3/minimap2#185]
Hello. I'm mapping single cell RNA seq data which I am then genotyping. Doing this from the STAR aligned bam has several issues causing false positives (not appropriate soft clipping, poor mapq calculations, etc). BWA does much better actually but it would be better to use something that is splice aware so I wanted to try minimap2 but there are not presets for short read alignment with splicing.

Thanks!

**Comment by wdecoster** [comment]
The manual states:

> Minimap2 does not work well with short spliced reads. There are many capable RNA-seq mappers for short reads.

**Comment by wheaton5** [comment]
Well I am having trouble with the output of some RNA-seq mappers for short reads. If you can suggest a better one for my purposes I would appreciate it. My purposes involve genotyping scRNAseq data without having tons of false positive variants called. BWA already out performs STAR for this purpose. And I took a guess at parameters (basically turning on splice mode and otherwise using the short read paramters)  and minimap2 out performs bwa (not that surprising as it at least has a spliced mode).

**Comment by lh3** [comment]
Minimap2 doesn't work well with short RNA-seq reads. If you want to give it a try anyway, you can mix the `splice` and `sr` presets like:
```sh
-a --splice -G200k -ub -C5 --sr -k21 -w6 -A2 -B8 -O12,32 -E2,1 -r50 -p.5 -N20 -f1000,5000 -n2 -m20 -s40 -g200 -2K50m --heap-sort=yes
```
Note that minimap2 won't work with paired-end RNA-seq reads. This is a hard limitation in its algorithm.

Another strategy is to use two mappers, call variants and then take the intersection. You will lose some sensitivity, but you will get low sensitivity anyway with scRNA-seq.

**Comment by lh3** [comment]
I am closing this. You may reopen the issue or add another comment if you have further questions. I will be notified by email. Thanks.
