### ISSUE TITLE
Output from Minimap2 Loaded into IGV - Blank?

### ISSUE THREAD

**Issue by MerillaM** [lh3/minimap2#187]
Hello everyone, I'm having trouble visualizing my PacBio data in IGV, as it looks like there is no coverage / the .bam files as input are blank.

Starting with subreads.bam data, I went through CCS, Classify, Cluster, Minimap2, Conversion to .bam, sort, and index, before loading into IGV. My command line prompts for each of these steps are below. Can anyone tell me why my coverage in IGV would be blank? The files aren't empty, but nothing shows up. I'm wondering if I made a mistake somewhere in the middle that would have corrupted the future .bam files, or something like that. No error messages were produced during any of these steps. Thanks in advance!

CCS Step:
`ccs --noPolish --minLength=300 --minPasses=1 --minZScore=-9999 --maxDropFraction:0.8 --minPredictedAccuracy=0.9 --minSnr=4 180938.subreads.bam CCS_180938.bam`

`dataset create --type ConsensusReadSet CCS_180938.xml CCS_180938.bam`

Classify Step:
`pbtranscript classify CCS_180938.xml 180938_isoseq_draft.fasta --flnc=180938_isoseq_flnc.fasta --nfl=180938_isoseq_nfl.fasta`

Cluster Step:
`pbtranscript cluster 180938_isoseq_flnc.fasta 180938_polished_clustered.fasta --quiver --nfl_fa=180938_isoseq_nfl.fasta --bas_fofn=scratch/PACBIO/Merilla_PACBIO/working/consensus_reads/xml/subreadsets/180938.subreadset.xml`

Minimap2 Step:
`minimap2 -t 5 -ax map-pb hg38.fasta ./cluster_out/all_quivered_hq.100_30_0.99.fasta > 180938.fasta.sam`

Convert to BAM, Sort, and Index Step:
`samtools view -Sb 180938.fasta.sam > 180938.fasta.bam`
`samtools sort 180938.fasta.bam > 180938.fasta.sorted.bam`
`samtools index 180938.fasta.sorted.bam`

**Comment by lh3** [comment]
Is your final bam `180938.fasta.sorted.bam` empty? If not, you should ask IGV developers.

**Comment by MerillaM** [comment]
@lh3 It isn't empty. I will do that, thank you!

**Comment by wdecoster** [comment]
@MerillaM apologies if you already checked this, but have you tried zooming?

**Comment by MerillaM** [comment]
@wdecoster I did zoom in and it's the correct genome. I checked `samtools view`, and that did the trick! There isn't a lot of data, but I was also not looking in the right spot. Thanks so much!

**Comment by qzhaojing** [comment]
@MerillaM 
the question is the .sam file the minimap generated. it is not a `.sam/bam` file similar to `bwa.` so the solution is to use `.paf` file. when use minimap2, you can first export `.paf` file , and use 
`paftools.js splice2bed convert spliced alignment in PAF/SAM to BED12` 
in minimap2 convert `paf` file to `.bed.`
and now, u can import the .bed to IGV
