### ISSUE TITLE
Concatenate fastq files first and then align using minimap2 vs. align using minimap2 first and then merge bam files

### ISSUE THREAD

**Issue by lauraht** [lh3/minimap2#191]
Hi Heng,

I have a quick question regarding using minimap2 for RNA-seq alignment and would appreciate your advice.

I have multiple fastq files (PacBio long reads) each from a different library (from a different SRA Run), but they all belong to the same BioSample. I would like to align them to the human reference genome using minimap2.

I have two ways to do this:
1.	Concatenate all fastq files first, and then align the merged fastq file to the reference genome using minimap2;
2.	Align each fastq file to the reference genome using minimap2 first, and then merge the multiple BAM files using “samtools merge”.

I was wondering if there is any difference in the final alignment results using these two methods? Or are the results of the two methods essentially the same?

Thank you very much!

**Comment by tseemann** [comment]
I don't think there would be any difference.  If you do it separately, you should pre-index the reference using `-d` option, and use `-x map-pb` option. One reason for doing it separately might be to give each one a separate read group (`-R`) so you can trace which cell/library each read came from. 

Given how fast `minimap2` is, you could probably try both methods and report back any issues?

**Comment by lh3** [comment]
As @tseemann said, merging before or after alignment should give you very similar (probably identical) results. The performance should be close, too. There is actually a third way:
```sh
minimap2 -ax map-pb ref.fa read1.fa read2.fa read3.fa > merged.sam
```
This is undocumented.

**Comment by tseemann** [comment]
@lh3 i have used minimap2 with multiple read files, and it is semi-documented with the `[...]` below:
```
% minimap2 --help

minimap2 [options] <target.fa>|<target.idx> [query.fa] [...]
```

**Comment by lauraht** [comment]
Hi Heng and Torsten,

Thank you very much for your advice!

I tried these two different ways and then ran StringTie on the alignments, and the results of StringTie are the same. So I think the alignment results of these two ways are indeed essentially the same.

Pre-indexing the reference using “-d” option is to save the computational cost so that the reference is not repeatedly indexed when aligning multiple fastq files, right? 

The “map-pb” option in the third way Heng listed here is for aligning genomic data, and for RNA-seq data, we should still use the “splice” option, right?

Another question is about the “-C5” option which I just saw in the latest README file. What difference does using “-C5” option (or not) make in aligning the Iso-Seq data?

The third way Heng listed is most convenient.

Thank you so much for the help!

**Comment by tseemann** [comment]
Yes, the `-d` is to pre-index the reference which is quite expensive for large genomes.

Aligning pacbio RNA-seq reads is discussed in the Cookbook here:
https://github.com/lh3/minimap2/blob/master/cookbook.md#map-iso-seq

**Comment by armintoepfer** [comment]
Or try bash magic `<(cat f1.fastq f2.fastq)` as input argument for minimap2

**Comment by lauraht** [comment]
One thing I noticed is that after using “samtools merge” to merge 3 BAM files into the final merged BAM file, the size of the final merged BAM file is smaller than the sum of the sizes of the original 3 BAM files (105739039 vs. 106760936). All these BAM files are sorted. I wonder if this is expected for “samtools merge”?

Also, the size of the final merged BAM file is also smaller than the size of the sorted BAM file produced by aligning the concatenated 3 fastq files (105739039 vs. 106020795). I wonder if this is as expected?

Thank you very much!

**Comment by tseemann** [comment]
Yes, compression will be better as a single file, as they will share a compression dictionary.

Please close this issue if everything is working now - cheers!

**Comment by lauraht** [comment]
Thank you so much Torsten!

This makes sense! But I was wondering why the size of the final merged BAM file is also smaller than the size of the single sorted BAM file produced by aligning the concatenated 3 fastq files (105739039 vs. 106020795)? Is this also expected?

I was wondering if you could also possibly help out my question regarding the -C5 option? If we align intermediate reads of the Iso-seq pipeline such as ccs reads, we should not use the -C5 option, right?

Thank you very much for all the help!

**Comment by lh3** [comment]
I realized that I have not replied to this:

> So the -C5 option is used for data with low error rate such as for the final Iso-seq reads of PacBio's Iso-seq pipeline, right?

Yes, based on evaluation on real data, -C5 is better for accurate mRNA sequences, including the final iso-seq sequences.
