### ISSUE TITLE
minimap2-2.11_x64-linux.tar.bz2 contain minimap2-2.10_x64-linux ？

### ISSUE THREAD

**Issue by orangeSi** [lh3/minimap2#193]
Hi~
   when I download minimap2-2.11_x64-linux.tar.bz2 from https://github.com/lh3/minimap2/releases, that inlcude minimap2-2.10_x64-linux, maybe you can check it~

Si
Thanks~

**Comment by lh3** [comment]
Thanks a lot. Fixed.
