### ISSUE TITLE
when map self to self, cannot get 0->fulllenght alignment in paf

### ISSUE THREAD

**Issue by orangeSi** [lh3/minimap2#194]
Hi~
  When I use `minimap2-2.11/minimap2 -x asm5 list.fa list.fa >list.fa.toself.asm5.paf`
get this:
EU090187_S001020547	1847	16	1847	+	EU090187_S001020547	1847	16	1847	1831	1831	0	
EU090187_S001020547	1847	16	1842	+	EU090187_S001020542	1844	16	1842	1826	1826	0	
EU090187_S001020542	1844	16	1842	+	EU090187_S001020542	1844	16	1842	1826	1826	0	
EU090187_S001020542	1844	16	1842	+	EU090187_S001020547	1847	16	1842	1826	1826	0	

When I use `minimap2-2.11/minimap2 -x asm20 list.fa list.fa >list.fa.toself.asm20.paf`
get this:
EU090187_S001020547	1847	2	1847	+	EU090187_S001020547	1847	2	1847	1845	1845	0	
EU090187_S001020547	1847	2	1842	+	EU090187_S001020542	1844	2	1842	1840	1840	0	
EU090187_S001020542	1844	2	1842	+	EU090187_S001020547	1847	2	1842	1840	1840	0	
EU090187_S001020542	1844	2	1842	+	EU090187_S001020542	1844	2	1842	1840	1840	0	

the list.fa is as attachment~
[list.zip](https://github.com/lh3/minimap2/files/2135504/list.zip)

 Why not get like this: 
 ` EU090187_S001020542	1844	0	1844	+	EU090187_S001020542	1844	0	1844	1844	1844	0 ` ?
and why the mapQ is 0?
I use the lastest minimap2-2.11.tar.bz2~

thanks~
Si

**Comment by lh3** [comment]
You need to use option `-c` or `-a`. Without these options, minimap2 only finds approximate locations. You get mapQ=0 because the alignment scores are close.

**Comment by orangeSi** [comment]
it works, thanks~
