### ISSUE TITLE
Question : Breaking of paired-end chains

### ISSUE THREAD

**Issue by rob-p** [lh3/minimap2#198]
Hi @lh3,

  I am very intrigued by the way minimap2 handles paired-end short reads --- the solution seems quite elegant.  According to the paper:

>  During chaining, minimap2 takes a pair of reads as one fragment with a gap of unknown length in the middle. It applies a normal gap cost between seeds on the same read but is a more permissive gap cost between seeds on different reads. ... After identifying primary chains (Section 2.1.3), we split each fragment chain into two read chains and perform alignment for each read as in Section 2.2. 

I am curious if there is a place I can find more details about how the resulting chain is split into 2 read chains.  I believe the code to do that is [here](https://github.com/lh3/minimap2/blob/master/hit.c#L348), but I'm not certain.  In most cases, one would imagine that there is only one "transition" from the read1 chain to the read 2 chain.  However, if the paired-end reads are overlapping, then there might be multiple transitions between the hits for the different reads in the optimal chain, right?  In this case, how does minimap2 split the chain for the pair into 2 separate (consistent) read chains where each contains only hits from a single read?  Any insight you could provide into that algorithm would be greatly appreciated.

Thanks!
Rob

**Comment by lh3** [comment]
> I believe the code to do that is here

Yes.

> However, if the paired-end reads are overlapping, then there might be multiple transitions between the hits for the different reads in the optimal chain, right?

Yes.

> In this case, how does minimap2 split the chain for the pair into 2 separate (consistent) read chains where each contains only hits from a single read?

Minimap2 will only find one of these chains. After seed extensions, these multiple chains will end up with the same alignments.

**Comment by rob-p** [comment]
> Minimap2 will only find one of these chains. After seed extensions, these multiple chains will end up with the same alignments.

So if I had a chain that looked like, for example:

[hit1, read1], [hit1, read2], [hit2, read1], [hit2, read2]

because the original paired-end reads were overlapping, then minimap2 would find only one chain for this read pair?  Presumably, the alignments for read 1 and read 2 would be different, since they have different starting positions, right?  Please let me know if my example is unclear.

**Comment by lh3** [comment]
Two possibilities, both end up with two chains. Possibility 1:

* [hit1, read1], [hit1, read2], [hit2, read2]
* [hit2, read1]

Possibility 2:

* [hit1, read1], [hit2, read1], [hit2, read2]
* [hit1, read2]

In both cases, the shorter chain is likely to be filtered out later.

**Comment by rob-p** [comment]
Ok, I think I understand.  So, basically, you don't worry when scoring the optimal chain if you switch back and forth between read 1 and read 2.  When you split the chain later, you apply an algorithm / heuristic<sup>*</sup> for splitting the chain at _some transition_ between reads 1 and 2, but for the purposes of generating the chain that will be used for alignment, you don't care if the seeds come from distinct reads.  Is this correct?

<sup>*</sup> Regarding this splitting algorithm heuristic; is it something easy to explain?  Is there some "maximal" score that you use to determine where to split the joint chain?

**Comment by lh3** [comment]
> Is this correct?

Yes

> Regarding this splitting algorithm heuristic; is it something easy to explain? Is there some "maximal" score that you use to determine where to split the joint chain?

Section 2.1.2 in the paper gives the full explanation. The two possibilities are the immediate consequence of the following sentence: "this way we find all chains with no anchors used in more than one chains".

**Comment by lh3** [comment]
Prior-to-release issue cleanup. If you have more questions, you may reopen the issue or add another comment. I will be notified by email. Thanks.
