### ISSUE TITLE
Is it proper of filter seed of HPC

### ISSUE THREAD

**Issue by chrisju** [lh3/minimap2#199]
Hi @lh3.
When use HPC, the intact seq of the  matched kmer may not matched, if filter them in skip_seed function,  can it get less seed and then less chain and reg? Can it get better performance and correct result?
For example, the matched kmer is ATCG, in ref the intact seq is AAATTTCG, in read is ATCCCGG.

**Comment by lh3** [comment]
If errors are independent of homopolymers, using HPC will result in fewer seeds and lower sensitivity. However, errors in PacBio data are associated with homopolymers. You end up with higher sensitivity with HPC seeds, at the cost of inaccurate seed placement in low-complexity regions. skip_seed() actually has little to do with HPC, though.
