### ISSUE TITLE
Nanopore read mapping to reference

### ISSUE THREAD

**Issue by michieitel** [lh3/minimap2#200]
I am wondering what would be the best way to map Nanopore reads to a reference and keeping only best and full-length matches? I try to get only reads that map with their entire length but allowing a specified (say 40) softmasked bases at both ends.

Could you please help me to identify the best settings in minimap2?

Thank you very much for your help.

**Comment by lh3** [comment]
You should use `-a -x map-ont` and filter the results with your own script.
