### ISSUE TITLE
Snps and indels calling tools from Minimap2 bam

### ISSUE THREAD

**Issue by herrroaa** [lh3/minimap2#202]
Hi
I used minimap to align my minion sequences. Now I want to call snps and indels, what would be the suggested tools for minumap2 generated bam
Thanks

**Comment by lh3** [comment]
There are no good tools. You may try Clairvoyante, but the accuracy would be much lower than calling from Illumina data.

**Comment by herrroaa** [comment]
I have designed the experiment to get  high depth of coverage >1000x to compensate for the Nanopore error rate. So, I believe I can call SNPs with enuogh confidence. The problem is that variant calling tools for Nanopore reads designed to work with bam files generated by specific aligner. I was wondering if there is one that is well known to work with minimap2

**Comment by lh3** [comment]
> I have designed the experiment to get high depth of coverage >1000x to compensate for the Nanopore error rate.

Nanopore errors are correlated. I doubt 1000x is sufficient.

> The problem is that variant calling tools for Nanopore reads designed to work with bam files generated by specific aligner.

What tools? I am not aware of those. A reasonable variant caller should work with any bam, not mapper specific.

> I was wondering if there is one that is well known to work

It is well known that it is nearly impossible to achieve the illumina level of accuracy with nanopore data alone. It is not the right data type for variant calling.
