### ISSUE TITLE
 Segmentation fault when overlapping long pacbio reads

### ISSUE THREAD

**Issue by MargauxAlison** [lh3/minimap2#206]
Hello,
 
I encounter a segmentation fault when trying to overlap Pacbio reads using **minimap2-2.5**.

My code is : 
`minimap2 -x ava-pb CDD2.fastq CDD2.fastq > CDD2ovlp.paf`

The error message : 

```
[M::mm_idx_gen::3.127*0.91] collected minimizers
[M::mm_idx_gen::4.487*0.94] sorted minimizers
[M::main::4.487*0.94] loaded/built the index for 7077 target sequence(s)
[M::mm_mapopt_update::4.653*0.94] mid_occ = 336
[M::mm_idx_stat] kmer size: 19; skip: 5; is_HPC: 1; #seq: 7077
[M::mm_idx_stat::4.770*0.94] distinct minimizers: 8513846 (85.45% are singletons); average occurrences: 1.721; average spacing: 4.301
/var/spool/slurm/d/job670332/slurm_script: line 9: 120019 Segmentation fault      minimap2 -x ava-pb minimap2 -x ava-pb CDD2.fastq CDD2.fastq > CDD2ovlp.paf
```
Just to tell, I mapped the same reads to a reference genome without troubles using minimap2.

Thanks

**Comment by lh3** [comment]
Try the latest version.

**Comment by MargauxAlison** [comment]
Thanks for your reply, indeed it is working well on the latest version.
(Sorry for the delay, I do not own the rights on the machine and I was waiting the uploading)

**Comment by lh3** [comment]
Thanks for confirming this is not an issue in the latest version.
