### ISSUE TITLE
Primary vs secondary alignments 

### ISSUE THREAD

**Issue by npavlovikj** [lh3/minimap2#208]
Dear,

For some of my sequences, I get multiple alignments when using "minimap2" (which is fine). However, I would like to know how an alignment is defined as a primary, and how as a secondary one. **In my case, I have two alignments that have the same cigar output and scores, both start at different reference positions, and one is a primary and one not.** Moreover, since I work with simulated data, I know the correct reference position where the alignment should start, and **usually the one reported as secondary is the correct one**.

For an example, please look at the "sam" file below. The reference position where the alignment should occur is "**3619448**". Both reported alignments below have the same cigar output and the same scores; **however, the first one (which is the primary one) starts at position "3762439" of the reference, and the second one (which is the secondary one) starts at position "3619448" and should be reported as the correct, primary one**:
```
@SQ     SN:U00096.3     LN:4641652
@PG     ID:minimap2     PN:minimap2     VN:2.10-r761    CL:minimap2 -t 1 -ax map-ont --MD ecoli_K12_MG1655.fasta 11724.fasta
U00096.3_3619447_aligned_11007_F_62_854_8       0       U00096.3        3762439 0       23M3I28M1I21M5D4M1D22M4D10M1D3M3D18M1I2M2I22M1I13M6D8M2D22M11D1M1D34M3D99M1I4M1D6M3D4M1D10M1D41M2D9M1D15M3I30M1I4M1I12M1I20M1D20M1I7M1D8M1I24M2I3M2D15M1D8M1I9M1D9M1D5M2D4M1I41M2D29M1I11M3D5M3D8M1D30M2I39M3I8M1I22M   *       0       0       CCGCGCCGGCGCGGAGCCTCGACTTACCCGGCTGGAAAATGCCTGCTTATATCCAGCTTACAGCTGCGCGCTACCAATACCAGTGATAACGGCGGCAGAAGCATTTTGACCACGGCCCGGTGAGGAATGTTACGAGCACCGCAGCGAGTCACAGTGGCTGTGTGCGCGGCGGCGAACTGGATAGGTCACCGGCTGGCCGCACTCGCGGAAGAACTCTCCTTAAGTCCGCATCATTATCTGACAAACAGTCCGCAGGGGCCGTGCTGGCTGGTCGGTTGGTGTGAACGGGTGCCGGAAGCGGATGAGGTGCTGCCTGCGCCGCTCCCGCGTTACCGGGTGACTGCCGGGCCGGACGCTTCGGGCTACACAGACAATCCACCGCGAAGCCGCCGGTGAATTCAGCGGAAATCACCGCGTGACGGATGTTGACCCCTGGCGTCACTTCCGGCATGTACTGACCATCGTATGGCGCAGCGGGCAAGCAGAAGCCCGGCAGCAGGCATTTCCGGCGGGACGGAACACGTCCGCTTTCCTGACTTTCTAGCCGGGTTACGAAGAATATCTGGGGGACAACGGCATCCTCTGTCTGCCCGTGTGGCGTCGCACGACCGGACCCCAGGAGAATTCAGTTGCCTTGCCGCTGGTGCGCTATGGCTGGACCACGCGGCGTACTGGCGGTGGTGTATGATCCGTAGTGGCAAGGTGAGCTTTACTACGATGATAAATACCGGGGCCGGATGGTGAAGCGCACCGTCACAGAGGCCGGCCGGAAATCCGTGACCGTTTATACGACAGTCGCCGGGCGGGTGACAGAACAG      *       NM:i:141 ms:i:918        AS:i:918        nn:i:0  tp:A:P  cm:i:15 s1:i:159        s2:i:159        dv:f:0.1429  MD:Z:9T1G9G21G0G21A2A2^CACTG4^T22^CTGT7G2^C1T1^TTT11C0G21T20^TGGCGA8^GA22^TGGCAGGCGCT1^C11C0G14G6^GGC24G6C13G38G4C0G12^A6^TGG0T3^C10^G0C8G0T30^GC9^G12G20T0G12C15A17^C27^T9A0C1C0T10A0C0C8^CC15^G17^T1A7^C5^AT0A11T1C0C4G0C23^CG10A29^AAC5^CGC8^T43C0G18T15A19
U00096.3_3619447_aligned_11007_F_62_854_8       256     U00096.3        3619448 0       23M3I28M1I21M5D4M1D22M4D10M1D3M3D18M1I2M2I22M1I13M6D8M2D22M11D1M1D34M3D99M1I4M1D6M3D4M1D10M1D41M2D9M1D15M3I30M1I4M1I12M1I20M1D20M1I7M1D8M1I24M2I3M2D15M1D8M1I9M1D9M1D5M2D4M1I41M2D29M1I11M3D5M3D8M1D30M2I39M3I8M1I22M   *       0       0      *     *       NM:i:141        ms:i:918        AS:i:918        nn:i:0  tp:A:S  cm:i:15 s1:i:159        dv:f:0.1429     MD:Z:9T1G9G21G0G21A2A2^CACTG4^T22^CTGT7G2^C1T1^TTT11C0G21T20^TGGCGA8^GA22^TGGCAGGCGCT1^C11C0G14G6^GGC24G6C13G38G4C0G12^A6^TGG0T3^C10^G0C8G0T30^GC9^G12G20T0G12C15A17^C27^T9A0C1C0T10A0C0C8^CC15^G17^T1A7^C5^AT0A11T1C0C4G0C23^CG10A29^AAC5^CGC8^T43C0G18T15A19
```

This "sam" file is just an example - I have observed the same occurrence in other files of mine with multiple  alignments. Therefore, I would appreciate if you can help me understand this behavior or let me know if there is an option I should use to avoid this.

Thank you,
Natasha

**Comment by lh3** [comment]
The two alignments are equally good. Which one gets flagged as "primary" is entirely random.

**Comment by npavlovikj** [comment]
Thanks @lh3 , I didn't know that.

**Comment by sejmodha** [comment]
Hi 
I came across this as I noticed a similar trend in a dataset. So in a case such as the one described above, where reads map to two locations that are identical, the MAPQ would be 0 for both alignments as the query region is not unique?

Thanks

**Comment by pre-mRNA** [comment]
Yes, the mapq would be 0 for both
