### ISSUE TITLE
Best 2(+) hits for genome vs genome alignment

### ISSUE THREAD

**Issue by cabbagesofdoom** [lh3/minimap2#209]
**Question.** When using minimap2 for full genome/assembly alignment, is it possible to get it to always return the top 2 hits (assuming the parameters give 2+ hits), even when the second hit is considerably worse than the first? Alternatively, would it be possible to add a flag that will ignore self hits (query and hit with matching names) so that an assembly could be searched against itself for similar non-self regions? If not, can you suggest a way to do this efficiently? I'm primarily interested in identifying potential primary and alternative assembly regions from non-diploid-aware assembler output, but struggling to find anything that will do it. Thanks!

PS. Great tool!

**Comment by lh3** [comment]
See #106.
