### ISSUE TITLE
Unalbe to do alignment on Ubuntu

### ISSUE THREAD

**Issue by peterbrucelee** [lh3/minimap2#21]
There are three servers in our LAB 
(1)Ubuntu 5.4.0-6ubuntu1~16.04.4 (2)Ubuntu 4.8.2-19ubuntu1 (3)Red Hat 4.8.5-11
minimap works sucessfully on the 3rd ,but not on the others.
I'm not sure whether it's due to different OS-version or something else.
Below is the content in core dump

-----------------------------------------------------------------------------------------------------------------
(1)
...
[New LWP 25220]
[New LWP 25224]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./minimap2/minimap2 -a -x map-ont /big7_disk/kuanwei105/homo-sapiens/ref.mmi /b'.
Program terminated with signal SIGILL, Illegal instruction.
#0  _mm_set_epi8 (__q00=<optimized out>, __q01=<optimized out>, __q02=<optimized out>, __q03=<optimized out>,
    __q04=<optimized out>, __q05=<optimized out>, __q06=<optimized out>, __q07=<optimized out>, __q08=<optimized out>,
    __q09=<optimized out>, __q10=<optimized out>, __q11=<optimized out>, __q12=<optimized out>, __q13=<optimized out>,
    __q14=<optimized out>, __q15=<optimized out>) at /usr/lib/gcc/x86_64-linux-gnu/6/include/emmintrin.h:616
616       return __extension__ (__m128i)(__v16qi){
[Current thread is 1 (Thread 0x7ff56e7fc700 (LWP 25223))]

------------------------------------------------------------------------------------------------------------------
(2)
...
[New LWP 27644]
[New LWP 27653]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./minimap2/minimap2 -a -x map-ont /big7_disk/kuanwei105/homo-sapiens/ref.mmi /b'.
Program terminated with signal SIGILL, Illegal instruction.
#0  0x000000000041267e in _mm_set_epi8 (__q00=<optimized out>, __q01=<optimized out>, __q02=<optimized out>, __q03=<optimized out>,
    __q04=<optimized out>, __q05=<optimized out>, __q06=<optimized out>, __q07=<optimized out>, __q08=<optimized out>,
    __q09=<optimized out>, __q10=<optimized out>, __q11=<optimized out>, __q12=<optimized out>, __q13=<optimized out>,
    __q14=<optimized out>, __q15=<optimized out>) at /usr/lib/gcc/x86_64-linux-gnu/5/include/emmintrin.h:616
616       return __extension__ (__m128i)(__v16qi){

**Comment by peterbrucelee** [comment]
(1)&(2)AMD Opteron(tm) Processor 6134
[http://www.cpu-world.com/CPUs/K10/AMD-Opteron%206134%20-%20OS6134WKT8EGO%20(OS6134WKT8EGOWOF).html](url)
(3)AMD Opteron(tm) Processor 6344
[http://www.cpu-world.com/CPUs/Bulldozer/AMD-Opteron%206344%20-%20OS6344WKTCGHK.html](url)
The first two seems to support SSE4a only, but the third support both SSE4/SSEa.
According you suggestion, switching to SSE2 make minimap work successfully; it looks like two of our server are becoming out-of-date to support modern programs.(!?)
Thank for you reply!

**Comment by tseemann** [comment]
SSE4 is a bit confusing - see https://en.wikipedia.org/wiki/SSE4#New_instructions
There are two Intel flags `sse4_1 sse4_2` in Linux (or `SSE4.1 SSE4.2` on MacOS.
Plus there is an AMD only `sse4a`...

The "4.1" version has 47 instructions, and "4.2" adds another 5 or so.

@lh3 in terms of specific instructions, do you use any of the SSE4_2 ones?

Will you be supporting AVX or AVX2 (aka AVX512) ever?

**Comment by lh3** [comment]
The next release of minimap2 v2.1.1 will support [CPU dispatch](https://attractivechaos.wordpress.com/2017/09/04/on-cpu-dispatch/). This will allow you to compile minimap2 on server (3) and run it on (1) and (2) without segfault.

> it looks like two of our server are becoming out-of-date to support modern programs.

I wouldn't say they are out-of-date, but they are old. SSE4 is ten years old.

> in terms of specific instructions, do you use any of the SSE4_2 ones?

Minimap2 doesn't use SSE4.2.

> Will you be supporting AVX or AVX2 (aka AVX512) ever?

AVX mostly supports floating point operations. It is useless to alignment. I don't see AVX2 often. I may consider when it gets more widely available. AVX512 (which is different from 256-bit AVX/AVX2) is brand new. No plan to support it in the next few years.

**Comment by lh3** [comment]
@peterbrucelee v2.1.1 is released with the support of CPU dispatch. You can use the [binary release](https://github.com/lh3/minimap2/releases/tag/v2.1.1) or compile on your server (3). The compiled binary will seamlessly work on (1) and (2) as well.
