### ISSUE TITLE
Even-length indel bias?

### ISSUE THREAD

**Issue by apregier** [lh3/minimap2#211]
We are aligning (human) assembly contigs to the reference sequence and have noticed a pattern that indel lengths seem to be biased toward even numbers.  We are using the asm5 preset.
This happens even if only looking at indels in coding sequence - we noticed it because we were trying to impress some students with a real-life demonstration of in-frame indel bias, but instead it looked like 4 bp indels are more prevalent than 3 bp, 6 bp are more prevalent than 5, 8 bp are more prevalent than 7, and so on.
Is this explainable as an alignment artifact based on the heuristics?  Could you suggest ways to tweak parameters to minimize the artifact?  It could also be an assembly artifact, but it occurs across assembly types (PacBio/Falcon and linked read/Supernova).  We've seen it across three different samples.

**Comment by lh3** [comment]
It is known that there are more 4bp indels than 3bp in the human genome. In CDS, my results are different from yours. In the syndip VCF, which was derived from the pacbio CHM1/CHM13 alignment against hg38, there are clearly more 3bp indels than 2bp or 4bp (the first column is the count; the second column is the indel length – negative for deletions):
```
     15 -12
      1 -11
      1 -10
     20 -9
      1 -8
      1 -7
     33 -6
      5 -5
     13 -4
     88 -3
     26 -2
    165 -1
     82 1
     17 2
     96 3
      9 4
      6 5
     31 6
      3 7
      3 8
     19 9
      1 10
      2 11
      6 12
```

**Comment by lh3** [comment]
I am closing this. If you still see a bias towards even-length indels in CDS, you may reopen the issue or add another comment. I will be notified by email. Thanks.
