### ISSUE TITLE
New Coder - how to install mappy on Windows 10 (64 bit)

### ISSUE THREAD

**Issue by amy1847** [lh3/minimap2#212]
I am trying to install mappy on a windows 10 (64 bit computer) however the code doesn't work. Do I need to install linux or is there another way?

<img width="280" alt="capture" src="https://user-images.githubusercontent.com/42104210/43682093-f8e09fe4-98ab-11e8-9929-b86e2cd0dbfb.PNG">

**Comment by lh3** [comment]
I *guess* you can use the [linux subsystem](https://docs.microsoft.com/en-us/windows/wsl/install-win10).
