### ISSUE TITLE
Soft-clipping at contig ends

### ISSUE THREAD

**Issue by Adamtaranto** [lh3/minimap2#215]
Hi Heng Li, 

I'm trying to find long-reads whose primary alignment overhangs the end of a contig, and that might provide useful information to extend the contig or bridge two split contigs. I see that mm2 supports soft clipping in supplementary alignments, but I am wondering how it will handle reads where the best match potentially has a large fraction of its length dangling off a contig end?

Are there any other settings that you would advise tweaking to help recover these kinds of reads?

Thanks for your help.

**Comment by lh3** [comment]
> how it will handle reads where the best match potentially has a large fraction of its length dangling off a contig end?

That is just soft clip.

**Comment by tseemann** [comment]
@Adamtaranto `samclip` might be useful for you (maybe) 
https://github.com/tseemann/samclip

**Comment by Adamtaranto** [comment]
Update: In case anyone needs to fish out Minimap2 alignments that are soft-clipped at contig ends, I've written a tool called [Teloclip](https://github.com/Adamtaranto/teloclip) to do just that. 

It also includes an option to test reads for telomeric repeat motifs.

**Comment by tseemann** [comment]
That README.md looks very familiar @Adamtaranto  :-P
