### ISSUE TITLE
Can I replace the qname and refname comparsion with two unique ids(uint64_t) comparision in global?

### ISSUE THREAD

**Issue by lqx8090** [lh3/minimap2#216]
Can I replace the qname and refname comparsion with two unique ids(uint64_t) comparision in global?
CODE:(IN function "skip_seed")
		cmp = strcmp(qname, s->name);
BUT this change will bring some differences to the sam/paf, while the performance will be improved.

**Comment by lh3** [comment]
You can, but performance will largely stay the same because that string comparison takes little time.
