### ISSUE TITLE
PAF / SAM output, equivalence?

### ISSUE THREAD

**Issue by MargauxAlison** [lh3/minimap2#218]
Hi,

I am mapping pacbio reads using minimap2-2.11.
I mapped my read using the -c / -a option for obtaining the same alignment, but with a different format for the output. 
I did : 
```
minimap2 -cx map-pb --secondary=no $Ref $FilteredFastq > $Name.paf   
minimap2 -ax map-pb --secondary=no $Ref $FilteredFastq > $Name.sam  
```
And I checked the result using paftools stat for PAF and samtools stats for SAM : 

```
paftools.js stat test_$Name.paf 
samtools stats $Name.sam >
```
Info for paftools : 
> Number of mapped sequences: 6813
> [...]
> Number of bases in mapped sequences: 61663168
> Number of mapped bases: 53369454

Info from samtools stats: 
> reads mapped:   6813
> [...]
> bases mapped:   61663168        # ignores clipping
> bases mapped (cigar):   53663329        # more accurate

I was thinking that "Number of mapped bases" was equivalent to "bases mapped (cigar)" but it is not the case.
Could you tell me if there is a problem or if I misunderstand the two values?

Thanks,

**Comment by lh3** [comment]
PAF and SAM are equivalent. You see different numbers because paftools.js stat and samtools stats are different. When there are supplementary alignments and they have overlaps, samtools will count bases in the overlap twice or more. paftools.js doesn't. It arguably gives you more accurate numbers.
