### ISSUE TITLE
Interpreting mapping score?

### ISSUE THREAD

**Issue by dvanic** [lh3/minimap2#219]
Hi! Thanks for developing such an awesome mapper! 

This is not an issue, just two questions I can't seem to figure out the answer to from the manuscript/documentation:

1. How does one interpret the mapping score (range 0-60) in the sam format? /apart from higher is better/
2. The PAF format contains a field which reports "Number of matching bases in the mapping" - there is not tag that reflects this in the sam, is there? 

Thanks in advance!

**Comment by lh3** [comment]
1. See SAM spec section 1.4 on the definition of MAPQ.

2. There isn't.
