### ISSUE TITLE
incremental self-alignment

### ISSUE THREAD

**Issue by viehwegerlib** [lh3/minimap2#22]
Is it possible somehow to use minimap2 to "add" a set of reads to an existing self-alignment?

like:

```bash
minimap2 file1.fq file1.fq > overlap
minimap2 overlap file2.fq > overlap
```

Thank you!

**Comment by lh3** [comment]
Sorry, minimap2 does not have this feature. When you have all the input reads in two files, you have to do something like this:
```sh
minimap2 -x ava-pb file1.fq file1.fq file2.fq > against-file1.paf
minimap2 -x ava-pb file2.fq file1.fq file2.fq > against-file2.paf
```
