### ISSUE TITLE
Mapping contigs to duplications

### ISSUE THREAD

**Issue by mvollger** [lh3/minimap2#221]
Hello, 

This is just a question and not an issue. Do you have any parameters you would suggest for mapping contigs to highly identical duplications (98-99% identical over 50-200 kbp)? I have tried asm5/10/20, but I have found that the best alignment is often not found (i.e. Blasr will find a better alignment to a different copy of the duplication).

Thanks!

**Comment by lh3** [comment]
You should use asm5 or asm10.

How do you know what is "the best alignment"? If you are sure it is minimap2 that is making the mistake, it would be great to send me an example such that you can improve it. Thank you.

**Comment by lh3** [comment]
> such that you can improve it.

Sorry. I mean "such that I can improve it". Thank you.

**Comment by mvollger** [comment]
Immediately after writing this I realized there was an error in my comparison script between blasr and minimap and I was just about to delete this comment when you responded. 

Thanks for responding so quickly and sorry for bothering you unnecessarily.

**Comment by tseemann** [comment]
@mvollger can you please close the issue?
