### ISSUE TITLE
PAF2delta conversion

### ISSUE THREAD

**Issue by jelber2** [lh3/minimap2#222]
Hi,

I am trying to replace a nucmer step (whole genome alignment) in a pipeline with minimap2, where the original pipeline uses the delta file from nucmer4, which is taking far too long [75 cores, 378GB ram, over 4 days]. Is it possible to convert the PAF format from minimap2 to delta format?

**Comment by lh3** [comment]
> Is it possible to convert the PAF format from minimap2 to delta format?

It is technically possible but will need some work. I am not going to write it. If that is your pipeline, it would be good to change it to work with minimap2's PAF format.

**Comment by jelber2** [comment]
Thank you. The part of the pipeline is from casm-layout of the AMOScmp package (https://sourceforge.net/projects/amos/). I am struggling to find more information about the delta format - I can't seem to find a formal definition of the output. Do you know of any?

**Comment by jelber2** [comment]
Thank you. It would be rather difficult to modify this pipeline as it uses AMOScmp (http://amos.sourceforge.net/wiki/index.php?title=AMOScmp), but I will look into writing a PAF2delta converter.

**Comment by songtaogui** [comment]
Hi, @jelber2 
I was also looking for a PAF2delta converter.
Have you successfully convert PAF to delta and could you share the scripts?
Thank you very much.

**Comment by jelber2** [comment]
Sorry @songtaogui, I was able to optimize nucmer and didn’t write any scripts.

**Comment by songtaogui** [comment]
@jelber2 Thank you for the reply. I will find another way.

**Comment by harish0201** [comment]
@jelber2 @songtaogui 

Currently the easiest way to obtain a delta file is to get the mapping in SAM and then using sam2delta from RaGoo repo. (Shoutout to @malonge) 

The only issue is that the sam might take lots of space, but that's the tradeoff :)

**Comment by malonge** [comment]
Yes I have a [python script](https://github.com/malonge/RaGOO/blob/master/sam2delta.py) that goes from SAM to delta. It is tested and should work.

I also have a script that goes from [PAF to delta](https://gist.github.com/malonge/d347a0061eab77d9ebeb9181b7a9ff31), though it failed my tests and I am not sure why. For the most part, it looks fine, but I think I am having problems with the number of mismatches.

Maybe you can use that as a starting point.

**Comment by gorliver** [comment]
@harish0201 @jelber2 @songtaogui 
I have a perl script can convert paf to delta, it requires the "cs" tags in the paf file.
https://github.com/gorliver/paf2delta

**Comment by malonge** [comment]
Hi - I forgot about this thread. I now have tested utilities for  paf <--> delta as a part of [RagTag](https://github.com/malonge/RagTag/wiki/file-utilities#paf2delta)
