### ISSUE TITLE
MapQ = 0

### ISSUE THREAD

**Issue by a-89** [lh3/minimap2#223]
Hi,

I am using Minimap2 for mapping full-length 16S rRNA amplicons obtained with nanopore to a reference database. The mapping quality obtained is 0 for the majority of the alignments, only a few of them present higher values. I was wondering which parameters should I tune to improve that (I am using the default, map-ont) or at least understand why I am getting these values.

`minimap2 operons.100.fa BC04.fastq > BC04_align.paf`

Thank you for your attention.
Best,
Anna

**Comment by tseemann** [comment]
Any read that aligns equally well to more than one database sequence will have MAPQ=0 because it is "multi-mapping".

This is exactly what will happen in your 16S example because there are lots of identical (or near identical) sequences in the database.

**Comment by a-89** [comment]
Thanks, Torsten for your answer! I see MAPQ is not meaningful in this scenario... Which parameter/filters should I apply to keep the most valid results? For all the entries within a single sequence, the alignment that presents a longer "alignment block," for example?

**Comment by lh3** [comment]
Look at the `AS` tag, which is the Smith-Waterman alignment score. However, this tag alone won't give you "the most valid results". Taxonomy identification is more than just alignment.

**Comment by tseemann** [comment]
You should look at the RDP website. They have a Java application which uses a kmer matching scoring system, not alignment. In my tests it works better than alignment for 16s. My experiments based on code here: https://github.com/tseemann/sixess (which uses minimap2)

**Comment by a-89** [comment]
Great, thank you so much for both suggestions! I will have a look at both of them. I also have some whole operon sequences that I would like to assign taxonomy (16S-ITS-23S). For the moment, alignment alone is giving me the expected results with a mock community. For discovering new diversity of uncharacterized environment, sure it is not the best approach just aligning...
I am also trying Centrifuge, which is kmer based. I will have a look at sixess, too! Thanks again!

**Comment by a-89** [comment]
@lh3 how could I force minimap2 to output the AS tag? By default in my .paf files, it does not output me this tag. Thanks again!
