### ISSUE TITLE
Spliced mapping of short reads?

### ISSUE THREAD

**Issue by Shellfishgene** [lh3/minimap2#224]
Does minmap2 do spliced mapping of short reads (100-150 bp pe) to replace TopHat/HISAT for RNASeq?

**Comment by wdecoster** [comment]
From the README.md:

> Minimap2 does not work well with short spliced reads. There are many capable RNA-seq mappers for short reads.

**Comment by Shellfishgene** [comment]
Thanks, I missed that sentence.
