### ISSUE TITLE
Lifting over annotation for a fungal genome -- is paftools the way to go?

### ISSUE THREAD

**Issue by lfaller** [lh3/minimap2#227]
Hello all,

I generated a de novo assembly of a fungus and would like to lift over annotations from a previously sequenced strain (same species).

I noticed that paftools has a `liftover` command:

```
minimap2 -c test/MT-human.fa test/MT-orang.fa \
  | paftools.js liftover -l10000 - <(echo -e "MT_orang\t2000\t5000")     # liftOver
```

Would this be an appropriate use case? The reference genome is 29 Mb in length.

Thanks for any advice!

**Comment by lh3** [comment]
You can try. I have only lifted small variants between human PacBio assemblies. Lifting annotations may be harder, though.

**Comment by tseemann** [comment]
One challenge will be the introns in the annotated genes. Could extract spliced CDS from the reference and use `minimap2 -x splice`.  Or this could make it worse.

**Comment by lfaller** [comment]
Thanks for the feedback -- I will play around with it a little bit!

**Comment by baoxingsong** [comment]
> Thanks for the feedback -- I will play around with it a little bit!
I have a little bit of idea about how to do that. If you that problem is still pending, you could contact me. song@mpipz.mpg.de

**Comment by lh3** [comment]
I am closing this. paftools.js liftover is probably not the right tool. @tseemann's approach should be better. For more distant species, there are genewise and exonerate.
