### ISSUE TITLE
Parameter for corrected PacBio reads ?

### ISSUE THREAD

**Issue by ptranvan** [lh3/minimap2#230]
Hi,

What would be your recommended parameters to map corrected pacbio reads (after 1 step of canu for example) against a genome ?

**Comment by lh3** [comment]
Don't really know.  Perhaps `asm20`. In general, good results should be robust to the parameters in use.

**Comment by armintoepfer** [comment]
If someone finds a good set, please let me know. We currently use
```
minimap2 -x map-pb -a --eqx -L -O 5,56 -E 4,1 -B 5 --secondary=no -z 400,50 -r 2k -Y
```
for subread mapping.

**Comment by lh3** [comment]
Oh, I was chatting online with Jason Chin about this yesterday. "map-pb" applies homopolymer compressed (HPC) seeds. While using HPC seeds greatly helps pacbio read overlap, it leads to lower base-level accuracy in rare cases. Jason found several cases where HPC seeds lead to suboptimal alignments. When base-level accuracy matters, it would be good to replace "-x map-pb" with "-x asm20" or specify the seeding scheme explicitly with something like "-k15 -w10" or "-k19 -w10".

**Comment by armintoepfer** [comment]
I heard of that conversation and we are testing the effect of HP compression on indel prediction.

**Comment by lh3** [comment]
> I heard of that conversation

:-)

> we are testing the effect of HP compression on indel prediction

There are a few angles to evaluate the effect. One of them is alignment score, the "AS" tag. You will sometimes see "AS" generated by "-k15 -w10" is a tiny bit higher than by "-Hk19". This happens more often for noisy long reads. Seed misplacement is a major limitation of minimap2 and may occasionally affect long indel calling.

**Comment by armintoepfer** [comment]
Ok, this is what we do now, no `-x map-pb`, instead use `-k 19 -w 10` omitting `-H`
