### ISSUE TITLE
Intra Species Comparison

### ISSUE THREAD

**Issue by Michelledemers** [lh3/minimap2#237]
I used minimap2 to compare two closely related species and got the respective paf file, using the code below. I want to know the overall similarity or identity between the two genomes. Is there a code or script that I can use to get an overall number to report? Thank you.

`./minimap2 -cx asm20 pgt.fa pgs.fa > aln.paf             # intra-species asm-to-asm alignment`

Best Regards,

Michelle

**Comment by lh3** [comment]
A naive way to estimate similarity:
```sh
awk '/tp:A:P/&&$10>=10000{x+=$10;y+=$11}END{print x/y}' aln.paf
```
A more accurate but more complex way (see the [cookbook](https://github.com/lh3/minimap2/blob/master/cookbook.md#calling-variants-from-assembly-to-reference-alignment)):
```sh
minimap2 -cx asm5 --cs genome1.fa genome2.fa \
  | sort -k6,6 -k8,8n \
  | paftools.js call - > out.var
```
You need to install paftools.js and k8 first, which is also explained in the cookbook. You may also need to change some "paftools.js call" parameters depending on your data.

BTW, `asm5` or `asm10` may be better for intra-species alignment.
