### ISSUE TITLE
Best options to map transcripts on a genome

### ISSUE THREAD

**Issue by chklopp** [lh3/minimap2#238]
I would like to use minimap2 -splice option to map transcripts (RNA-Seq de novo assembled contigs) on the corresponding genome.

I've tested this using the Ensembl medaka genome, GTF and mRNA fasta files. The mRNA fasta file was aligned with minimap2 -splice option to produce a sam file from which the exons location were extracted to produce a GTF file which was then compared to the original GTF with (gffcompare-0.10.4). The same analysis was performed with blat.

Minimap2 results 
<pre>
#= Summary for dataset: Miniannotator/annotations.gtf 
#     Query mRNAs :   25534 in   20598 loci  (23521 multi-exon transcripts)
#            (3731 multi-transcript loci, ~1.2 transcripts per locus)
# Reference mRNAs :   25431 in   20453 loci  (23889 multi-exon)
# Super-loci w/ reference transcripts:    10046
#-----------------| Sensitivity | Precision  |
		Base level:    49.6     |    48.0    |
		Exon level:    43.2     |    45.2    |
	     Intron level:    43.5     |    46.1    |
      Intron chain level:    29.0     |    29.5    |
        Transcript level:    30.2     |    30.1    |
	      Locus level:    33.0     |    32.8    |

	       Matching intron chains:    6929
	         Matching transcripts:    7674
			  Matching loci:    6750

		  Missed exons:  113498/218887	( 51.9%)
		   Novel exons:  105219/209305	( 50.3%)
		Missed introns:   99382/194041	( 51.2%)
		 Novel introns:   90713/183268	( 49.5%)
		   Missed loci:   10172/20453	( 49.7%)
			Novel loci:    9959/20598	( 48.3%)

 Total union super-loci across all input datasets: 20578 
25534 out of 25534 consensus transcripts written in gffcmp.annotated.gtf (0 discarded as redundant)
</pre>

Blat results 

<pre>
#= Summary for dataset: Oryzias_latipes.MEDAKA1.cdna.all.fa.psl.gtf 
#     Query mRNAs :  125857 in   47226 loci  (87603 multi-exon transcripts)
#            (15048 multi-transcript loci, ~2.7 transcripts per locus)
# Reference mRNAs :   25431 in   20453 loci  (23889 multi-exon)
# Super-loci w/ reference transcripts:    12321
#-----------------| Sensitivity | Precision  |
        Base level:    99.5     |    72.1    |
        Exon level:    96.4     |    51.5    |
      Intron level:    97.1     |    62.5    |
Intron chain level:    84.6     |    23.1    |
  Transcript level:    82.6     |    16.7    |
       Locus level:    84.0     |    36.1    |

     Matching intron chains:   20212
       Matching transcripts:   20995
              Matching loci:   17187

          Missed exons:    3034/218887	(  1.4%)
           Novel exons:  179860/410984	( 43.8%)
        Missed introns:     806/194041	(  0.4%)
         Novel introns:   85849/301556	( 28.5%)
           Missed loci:     405/20453	(  2.0%)
            Novel loci:   21997/47226	( 46.6%)

 Total union super-loci across all input datasets: 47176 
125857 out of 125857 consensus transcripts written in gffcmp.annotated.gtf (0 discarded as redundant)
</pre>

Blat results are much better when comparing missed introns and exons.
Which parameters should I use to improve minimap2 sensitivity and precision.

**Comment by lh3** [comment]
> Base level:    99.5
> Missed introns:     806/194041	(  0.4%)

I don't think RNA-seq experiment can reach this sensitivity.

Also:

> \#     Query mRNAs :   25534 in   20598 loci
> \#     Query mRNAs :  125857 in   47226 loci

Are the first numbers give you the number of sequences in the query files? Why are they different?

If you are sure that your processing is correct, please send me the RNA-seq contigs. Thanks.

**Comment by chklopp** [comment]
It is not really RNA-Seq. For my first test, I have used reference data given by Ensembl, in order to be able to check the results with the reference GTF file (ftp://ftp.ensembl.org/pub/release-93/gtf/oryzias_latipes/Oryzias_latipes.MEDAKA1.93.gtf.gz).

I've aligned the cDNA fasta file 
ftp://ftp.ensembl.org/pub/release-93/fasta/oryzias_latipes/cdna/Oryzias_latipes.MEDAKA1.cdna.all.fa.gz

On the genome
ftp://ftp.ensembl.org/pub/release-93/fasta/oryzias_latipes/dna/Oryzias_latipes.MEDAKA1.dna.toplevel.fa.gz

The numbers give the alignments found by each software package (minimap2 and blat) which were then turned into GTF. 

NB. For the blat results I have kept only alignments for which the cdna coverage was > 0.95. Blat produces a lot of small alignments.

**Comment by lh3** [comment]
```sh
# see README
minimap2 -ax splice -C5 -t8 Oryzias_latipes.MEDAKA1.dna.toplevel.fa.gz Oryzias_latipes.MEDAKA1.cdna.all.fa.gz > mm2.sam
# see cookbook.md
paftools.js junceval Oryzias_latipes.MEDAKA1.93.gtf.gz mm2.sam
```
gives
```txt
# unmapped reads: 4
# mapped reads: 24671
# primary alignments: 24682
# singletons: 1029
# predicted introns: 215825
# non-overlapping introns: 22
# correct introns: 207501 (96.14%)
```
`junceval` is not as sophisticated as gffcompare, but on the numbers it reports, minimap2 does much better. I guess your sam-to-gff conversion is wrong. Also, you are counting multiple mappings with blat. That is not the right way.

**Comment by chklopp** [comment]
Thank you for this quick feedback. 
I'll check my sam-to-gff and remove blat multiple maps.

**Comment by chklopp** [comment]
I've check my code and did not find the error.
When I use -C 5 and remove all 0 quality alignments I get the following results which are good 

<pre>

#= Summary for dataset: MiniannotatorC5q2/annotations.gtf 
#     Query mRNAs :   24005 in   19571 loci  (23031 multi-exon transcripts)
#            (3483 multi-transcript loci, ~1.2 transcripts per locus)
# Reference mRNAs :   25431 in   20453 loci  (23889 multi-exon)
# Super-loci w/ reference transcripts:    19402
#-----------------| Sensitivity | Precision  |
        Base level:    98.9     |    99.5    |
        Exon level:    88.6     |    93.3    |
      Intron level:    90.0     |    95.1    |
Intron chain level:    65.5     |    67.9    |
  Transcript level:    64.5     |    68.3    |
       Locus level:    69.1     |    72.3    |

     Matching intron chains:   15640
       Matching transcripts:   16406
              Matching loci:   14139

          Missed exons:    8324/218887	(  3.8%)
           Novel exons:     153/208080	(  0.1%)
        Missed introns:    4095/194041	(  2.1%)
         Novel introns:      14/183530	(  0.0%)
           Missed loci:     722/20453	(  3.5%)
            Novel loci:       8/19571	(  0.0%)

 Total union super-loci across all input datasets: 19551 
24005 out of 24005 consensus transcripts written in gffcmp.annotated.gtf (0 discarded as redundant)
</pre>

Screening the alignments I found a case in which minimap2 missed a small exon.
Here is the IGV screenshot 
http://genoweb.toulouse.inra.fr/~klopp/e7WEIHpfSFfHNY02bcgK/minimap2_missed_exon.png

The screenshot presents the minimap2 alignment, the reference model and the alignment extracted model from top to bottom.

Is there an option which would help/improve small exons discovery?

**Comment by lh3** [comment]
> When I use -C 5 and remove all 0 quality alignments I get the following results which are good

Then why are the previous results so bad? `-C5` only affects the accuracy by a couple of percent. There should be few mapQ=0 alignments. You can see that from the "# Query mRNAs" line – 25534 vs 24005. And even now, your results still look quite different from mine. There are 24675 transcripts in Ensembl r93. I don't think minimap2 will miss 670 of them entirely.

> Is there an option which would help/improve small exons discovery?

`-x splice` is designed to tolerate ~10% sequencing error rate. Playing with the scoring may increase the overall accuracy a little bit in your case. I haven't tried, though. The real data is much worse anyway.

**Comment by chklopp** [comment]
> Then why are the previous results so bad? 

This could come from the secondary alignments of genes families members which are numerous in the genome. These secondary alignments have null alignment quality and different start and stop positions because the different family members differ from just some base pairs. 

> There are 24675 transcripts in Ensembl r93. I don't think minimap2 will miss 670 of them entirely.

This originates from the same cases but for families in which the members are exact copies. Minimap2 aligns them all but with 0 quality because they have multiple possible locations.

I have tested this with a set of 19,699 Oryzias latipes unique cDNAs (1 transcript per gene).
- with -C 5 all 19,699 are aligned producing 21,859 alignments (2,150 secondary + 10 supplementary) 
- when filtered with samtools -q 2 only 19,570 are remaining producing 19,580 alignments (0 secondary + 10 supplementary) 

> The real data is much worse anyway.

RNA-Seq de novo assembled contigs produced by trinity or Oases are quite accurate. And they represent very good material to annotate genomes. Minimap could be very useful alternative to exonerate which is very slow.

**Comment by lh3** [comment]
You have given me data (thanks for that) and I have given you the command line, so I can do the counting on my side. The main issue is your count is too low, in particular this line:
```txt
#     Query mRNAs :   24005
```
You can count easily with
```sh
grep tp:A:P aln.sam | awk '$5>2' | cut -f1 | uniq | wc
```
This gives you 24530. Also, your first- and second-round numbers also don't match up. In the first round, there are 25534 minimap2 alignments. In the second round, there are 24005. It is not possible for 25534-24005 alignments to explain the huge sensitivity difference 49.6% vs 98.9%.
