### ISSUE TITLE
Using minimap2 in realtime

### ISSUE THREAD

**Issue by lcmmichielsen** [lh3/minimap2#239]
Hi,

I would like to use minimap2 to map incoming nanopore reads in realtime. Do you know whether it is possible to use minimap2 with stdin or with a growing file of reads?

Thanks!

**Comment by lh3** [comment]
> whether it is possible to use minimap2 with stdin

Yes. Use `-` as the input file name, or a [named pipe](https://en.wikipedia.org/wiki/Named_pipe). You can also use the C or the python APIs. That will give you more control.

**Comment by lcmmichielsen** [comment]
Unfortunately this is not working. I tried the following:

jsa.np.npreader -realtime -folder /workspace/pass/0 -output - | jsa.np.filter -input - -lenMin 5000 -qualMin 12 -output - | minimap2 -ax map-ont ref_seeds.mmi - > test_stdin.sam

If I replace minimap2 by bwa mem, however, it is working.

**Comment by lh3** [comment]
That is the design and it is working for me. If it is not working for you, it should be a bug. What's output?

**Comment by lh3** [comment]
What's the stderr output?

I can't fix the issue unless I reproduce it on my side.

**Comment by lcmmichielsen** [comment]
I only get:

[M::main::0.064*1.01] loaded/built the index for 2300 target sequence(s)
[M::mm_mapopt_update::0.074*0.97] mid_occ = 5
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 2300
[M::mm_idx_stat::0.082*0.98] distinct minimizers: 403396 (95.97% are singletons); average occurrences: 1.045; average spacing: 5.456

so no real errors. I seems like it doesn't see that there are reads coming in?

**Comment by tseemann** [comment]
@lcmmichielsen do you know how many reads per second are produced, and what their average length is?  That would help you to choose `-K` the minimum bp total of reads before mapping is performed.
