### ISSUE TITLE
segmentation fault when using an index file

### ISSUE THREAD

**Issue by simonrharris** [lh3/minimap2#24]
When using an index file as the target input I get segmentation faults caused by main.c attempting to check the kmer and minimizer lengths in the index agree with those set on the command line. The seg fault occurs on the second pass through the loop when the index is not loaded. I've sent a pull request with a simple fix, but it may be worth checking this isn't causing any other issues, particulalry if there are multiple query files.

**Comment by lh3** [comment]
Thanks! PR #23 was merged.
