### ISSUE TITLE
minimap2 produces an alignment, where minimap2 -c does not

### ISSUE THREAD

**Issue by sjackman** [lh3/minimap2#240]
Hi, Heng.

I get an alignment when I align two sequences with `-xasm20`.
I do not get an alignment when I align two sequences with `-c -xasm20`.
I do get an alignment when I align two sequences with `-c`.

This behaviour is surprising to me. If `-xasm20` yields an alignment, I'd expect `-xasm20 -c` to also yield an alignment. Is this behaviour expected? The test case follows below.

```
❯❯❯ minimap2 -xasm20 hsapiens-mt.fa NC_005278.1.fa 2>/dev/null | wc
       1      17     105
❯❯❯ minimap2 -c -xasm20 hsapiens-mt.fa NC_005278.1.fa 2>/dev/null | wc
       0       0       0
❯❯❯ minimap2 -c hsapiens-mt.fa NC_005278.fa 2>/dev/null | wc
       1      22    2148
❯❯❯ minimap2 --version
2.12-r827
```

Sequences:
ftp://ftp.ensembl.org/pub/release-93/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.chromosome.MT.fa.gz
https://www.ncbi.nlm.nih.gov/nuccore/NC_005278.1?report=fasta&format=text

**Comment by lh3** [comment]
Expected. Base-level alignment may drop low-quality hits. What are "low-quality" is largely determined by the scoring system.

**Comment by sjackman** [comment]
Okay. Thanks for the explanation, Heng.

```
- asm5/asm10/asm20: asm-to-ref mapping, for ~0.1/1/5% sequence divergence
```

What sequence divergence are the default parameters good for?

**Comment by sjackman** [comment]
Thanks, Heng.
