### ISSUE TITLE
Number of mapped and unmapped reads mismatch total reads

### ISSUE THREAD

**Issue by pradyumnasagar** [lh3/minimap2#242]
I'm trying to map our nanopore data to two different references, the number of reads in the fastq file is 151415. When I map these reads with the following command, I got 257229( 251184 mapped + 6045 unmapped) reads. 
> minimap2 -a -x map-ont  HG_noMito.fa barcode01.fastq | samtools sort -T tmp -o BC01.Nuc.bam

When I try to map the same with a different reference, I got 151581(908 mapped+150673 unmapped) 

> minimap2 -a -x  map-ont RCRS.fa barcode01.fastq | samtools sort -T tmp -o BC01.mit_test.bam

Why don't the total reads after mapping is more than the total number reads in fastq? 

If a single read is matched multiple times what is the optimization parameter I can give to get only one best match?

**Comment by mp15** [comment]
Look up "supplementary" reads (also depending on your parameters "secondary" reads)  in the SAM spec, there is not a 1:1 relationship between input reads and output reads unless you filter non-primary reads from your count. For example, when your reference sequence has an partial inversion relative to part of your mapped read, you cannot represent the mapping of your read with a single SAM line so you must include a supplementary.

**Comment by Github-Yilei** [comment]
I also got the mismatch results while using `samtools flagstat` to counts the output of `minimap2 -ax map-hifi`. However, the total number of reads will match if I extracting the reads by `-F 4` and `-f 4`.
