### ISSUE TITLE
different assembly quality from minimap/minimap2

### ISSUE THREAD

**Issue by njaupan** [lh3/minimap2#243]
Dear heng, 
I have got different asssembly quality for a 50X plant genome from minimap+miniasm and minimap2+miniasm,here is script:
$minimap -Sw5 -L100 -m0 raw.fasta raw.fasta | gzip -1 > old.minimap.overlap.paf.gz
$minimap2 -x ava-ont -r 10000  raw.fasta raw.fasta | gzip -1 > minimap2.overlap.paf.gz

then build an assembly graph by the same miniasm paramater,
miniasm -f  raw.fasta  *.paf.gz > *.paf.gfa
awk '/^S/{print ">"$2"\n"$3}'   *.paf.gfa >  *.paf.gfa.utg.fa

for minimap, it output 99.9M with 98 contigs, longest 11.3 M, N50 4.6M:
for minimap2, it output 101.2M with 133 contigs, logest 8.9M, N50 3.0M. It looks minimap2 performed worse N50 but longer length in this case. How should I adjust to perform similar result as minimap? 
Best,
panpan

**Comment by lh3** [comment]
First, minimap and minimap2 don't promise identical results. Sometimes minimap2 is better; sometimes it is contrary. Second, the assembler-overlapper interaction is complex. Better N50 doesn't necessarily mean better overlapping. Third, N50 is not sufficient to evaluate an assembly. You have to check the number of misassemblies as well.

**Comment by lh3** [comment]
Closing. The goal is to stay similar to minimap. It is nearly impossible to always match minimap in all cases.
