### ISSUE TITLE
Overlapping supplementary alignments?

### ISSUE THREAD

**Issue by armintoepfer** [lh3/minimap2#244]
My understanding was that query intervals of primary and supplementary alignments of the same read never overlap. But it looks like I'm mistaken, because they are overlapping...is there an option to force non-overlapping intervals?

```
$ minimap2 ref.fasta tiny.fasta --cs --secondary=no 2> /dev/null | cut -f 3,4,6,8,9
4378	16658	ENA|CP002685|CP002685.1:5190000-5210000	8050	20000
13615	22038	ENA|CP002685|CP002685.1:5190000-5210000	8174	15881
```
Data: [Archive.zip](https://github.com/lh3/minimap2/files/2424876/Archive.zip)

Thank you,
Armin

**Comment by lh3** [comment]
Segments on a query may overlap by up to 50%. The threshold is controlled by -M/--mask-level.

In this particular example, you would assume the second half of the read to be a novel sequence if minimap2 didn't report it.

**Comment by armintoepfer** [comment]
Can I force it to be non-overlapping? Setting `-M 0` changes numbers, but still overlapping:

```
$ minimap2 ref.fasta tiny.fasta --cs --secondary=no -M 0 2> /dev/null | cut -f 3,4,6,8,9
4378	16658	ENA|CP002685|CP002685.1:5190000-5210000	8050	20000
14623	22090	ENA|CP002685|CP002685.1:5190000-5210000	8870	15858
```

**Comment by lh3** [comment]
Minimap2 has another heuristic hard coded to avoid leaving long query sequences unmapped. It will override mask level. So far, it is not possible to force the results to be non-overlapping.

**Comment by armintoepfer** [comment]
Looks like solved to me. Will reopen, if I find additional problems with this new feature. Thanks Heng!
