### ISSUE TITLE
-X and --secondary=no

### ISSUE THREAD

**Issue by zeeev** [lh3/minimap2#245]
Dear @lh3,

Are the --secondary=no and -X flags not compatible? If I set both flags I receive no output, whereas each flag works alone. 

~/tools/minimap2/minimap2 -X -x asm5 --secondary=no same.fasta same.fasta

**Comment by lh3** [comment]
No, they don't work together. -X makes all alignments secondary.

**Comment by zeeev** [comment]
Thank you @lh3.
