### ISSUE TITLE
Gene fusion not detected

### ISSUE THREAD

**Issue by twrzes** [lh3/minimap2#246]
Hi Heng,

First of all I would like to thank you for creating such a great software!

I have problem with minimap2 (I tested versions 2.7, 2.11 and r847) for detection of fusion genes. I generated some Nanopore cDNA sequencing on some human samples. I have a read which sequence can be found below:

`>read1
TTGAAATTGCTTCGTTCGAATCAATTCCCAGATTGTTTTATGGTTCTTTACCTGTCACTCTATCTTCTTTTTTTTTTTTTTCCTTTTTTTTTTTTTTTGTTAATTAATTAATGCTTTTAGGACATAATAATAACAATTGAATGTCTGCACAACCCTTTGTTGACCATAAGCACCCCATGCAGCCAGTCACTGCACCTCCATCTACCACTCCTACCATGTTCCTCTACACAGCCGACTAGTTATGATCAGAGCAGTTACTCTCAGCCACCTATGGGCAACCGAGCAGCTATGGACAGCAGAGTAGCTATAGTCGCTCGAAGCAGCTATGGGCAGCAGCCTCCTAGTTACCACCCAAACTGGATCCTACAGCCAAGCTCCAAGTCAGCCAGCCAACAGAGCAGCAGCTACGGGCATGGGGAGTTCCTGCTGGCCTATATTAACCTCCACACCGACCAATCCCTCGCGATTGAGTGTCAAAGAAGACCCTTCTTATGACTCAGTCAGAAGAGACTTGGGGCAATAACACTTCTGGCCTCAACAAAGTCCTCCTTGGAGACACAAACGATCATTAGATACAGAGCACC`

I am trying to align it against the reference genome (ENSEMBL v93). When I used BLAST or BLAT, I can see that this read overlaps EWSR1 (read positions 169-429, genomic location of the gene chr22:29,268,009-29,300,525) and FLI1 (read positions 419-582, genomic location of the gene chr11:128,686,535-128,813,267). However, when I aligned this read with minimap2, the output of SAM file is:

`
@PG     ID:minimap2     PN:minimap2     VN:2.11-r797    CL:minimap2 -t 15 -p 0 -N 100 -ax splice hg38_genome.fa test.fa
`
`
read1    0       chr22   29282512        60      171S30M1D5M1I9M1D4365N1D49M4D47M1I27M3D7M1D3M1D33M1D30M171S     *       0       0       TTGAAATTGCTTCGTTCGAATCAATTCCCAGATTGTTTTATGGTTCTTTACCTGTCACTCTATCTTCTTTTTTTTTTTTTTCCTTTTTTTTTTTTTTTGTTAATTAATTAATGCTTTTAGGACATAATAATAACAATTGAATGTCTGCACAACCCTTTGTTGACCATAAGCACCCCATGCAGCCAGTCACTGCACCTCCATCTACCACTCCTACCATGTTCCTCTACACAGCCGACTAGTTATGATCAGAGCAGTTACTCTCAGCCACCTATGGGCAACCGAGCAGCTATGGACAGCAGAGTAGCTATAGTCGCTCGAAGCAGCTATGGGCAGCAGCCTCCTAGTTACCACCCAAACTGGATCCTACAGCCAAGCTCCAAGTCAGCCAGCCAACAGAGCAGCAGCTACGGGCATGGGGAGTTCCTGCTGGCCTATATTAACCTCCACACCGACCAATCCCTCGCGATTGAGTGTCAAAGAAGACCCTTCTTATGACTCAGTCAGAAGAGACTTGGGGCAATAACACTTCTGGCCTCAACAAAGTCCTCCTTGGAGACACAAACGATCATTAGATACAGAGCACC *       NM:i:23 ms:i:181        AS:i:145        nn:i:0  ts:A:+  tp:A:P  cm:i:37 s1:i:168  s2:i:100 dv:f:0.0453
`
`
read1    272     chr1    166276810       0       171S26M1D34M1D4M1D8M3D26M1I49M4D49M2D9M1I4M1D28M174S    *       0       0       *       *       NM:i:28 ms:i:165        AS:i:165  nn:i:0   tp:A:S  cm:i:18 s1:i:100        dv:f:0.0694
`
`
read1    256     chr14   35881529        0       171S30M1D5M1I7M14I4M8I25M4D47M1I27M3D9M1D1M1D26M208S    *       0       0       *       *       NM:i:48 ms:i:87 AS:i:87 nn:i:0  tp:A:S     cm:i:11 s1:i:57 dv:f:0.0909
`

So as you can see the alignment to EWSR1 is there, bit the alignment to FLI1 is missing. Is there any parameter I can change (apart from -p 0  which I guess doesn't change much in terms of splitted alignments) or it isn't just possible to identify gene fusions in minimap2 alignments?

Thank you very much for all your help, I am very grateful for it.

Kind regards,
Tomasz Wrzesinski

**Comment by lh3** [comment]
Sorry for the late response.

The hits to FLI1 are too small and introns are quite long. Minimap2 has low sensitivity to such short hits. You can find actually find hits to FLI1 with `-x splice -k13`, but probably it will be slow.

**Comment by lh3** [comment]
I am closing this for now. If you have followup questions, please reopen or post it to this thread. I will be notified.
