### ISSUE TITLE
Diferent result with diferent output format

### ISSUE THREAD

**Issue by ceslobfer** [lh3/minimap2#247]
Hi Heng,
`minimap2 -a $REF $QUERY > AllAssembly1.sam`
`minimap2 $REF $QUERY > AllAssembly1.paf`
Example result with SAM output:
pp_2	16	scaffold22882	3190	4	(Cigar)*	0	0	(Seq)	*	NM:i:142	ms:i:866	AS:i:866	nn:i:0	tp:A:P	cm:i:13	s1:i:143	s2:i:140	dv:f:0.1393
Example result with PAF output:
pp_2	1371	101	708	-	scaffold22882	270530	3342	3953	144	612	3	tp:A:P	cm:i:13	s1:i:143	s2:i:140	dv:f:0.1393

The SAM format tells me that it starts at position 3190 and the PAF format at position 3342.

I have checked the alignments manually and the alignment returned by the PAF format seems incorrect with respect to the alignment in SAM format.

**Comment by lh3** [comment]
See #158.

See also #218, #102, #161 if you want to learn more.
