### ISSUE TITLE
document about the SSE parallelization algorithm

### ISSUE THREAD

**Issue by baoxingsong** [lh3/minimap2#249]
Hello Heng,
I am very interested in the SSE code you used to parallelize the sequence alignment. It seems your algorithm is not an implementation of Farrar, 2007. Where could I find the document to explain the parallelization part of your SSE code, please?

**Comment by lh3** [comment]
Read the paper.

**Comment by tseemann** [comment]
@baoxingsong paper link is in the README: https://github.com/lh3/minimap2#citing-minimap2

**Comment by tseemann** [comment]
@lh3 one problem is that it is not open access ?

![image](https://user-images.githubusercontent.com/453972/47127281-452ac580-d2d8-11e8-9596-0e1079e7618a.png)

**Comment by lh3** [comment]
The preprint is nearly the same.

**Comment by tseemann** [comment]
Here is the link to the pre-print: https://arxiv.org/abs/1708.01492

**Comment by baoxingsong** [comment]
Thank you, I got it.
