### ISSUE TITLE
Question about SAM output tags

### ISSUE THREAD

**Issue by npavlovikj** [lh3/minimap2#25]
Hi,

I generated "sam" file using "minimap2", and I noticed there are some additional tags in the output compared to the standard "sam" format, e.g. "tp:A:P cm:i:8 s1:i:46 s2:i:0 NM:i:264 ms:i:194 AS:i:194 nn:i:0". I was wondering if you can tell me what do the tags "tp", "cm", "ms" and "nn" mean.
Next, I want to extract the number of matches and mismatches from the cigar alignment. However, the "sam" file contains only the tag M, which stands for both matches and mismatches, so I was wondering if any of these additional tags can help me differentiate between the both. If not, can you please suggest me a way to do that ?

Thank you,
Natasha

**Comment by lh3** [comment]
For tags, see the table at the bottom of `man ./minimap2.1`.

NM gives the number of mismatches and gaps. You can count the number of gaps from CIGAR. The difference gives the number of mismatches.

**Comment by npavlovikj** [comment]
Thank you @lh3 , that worked perfectly!

**Comment by Blosberg** [comment]
Hi Dr. Li:

> You can count the **number of gaps** from CIGAR

I initially assumed this meant `N` from the CIGAR, however, when I took `NM-N` I obtained an array with negative values, so clearly I had been mistaken. I am now assuming that you are referring to `D` from the CIGAR ('Deletion', in which the nucleotide is present in the reference but not in the read), 

This would imply that `# mismatches = NM-D`

If that's incorrect, could you please set me straight? Thank you.

**Comment by npavlovikj** [comment]
@Blosberg , according my understanding, the number of gaps is the number of insertions and deletions from the CIGAR output, so I ended up using #mismatches=NM-I-D.

**Comment by lh3** [comment]
I forgot what the SAM spec says, but for minimap2:
```
NM = #mismatches + #I + #D
```
NM does not count reference skip `N`.

**Comment by Blosberg** [comment]
@npavlovikj , @lh3 ,
ok. Thank you both very much for your help.

**Comment by armintoepfer** [comment]
Tag dv:f:
>Approximately estimate per-base sequence divergence (i.e. 1-identity) without performing base-level alignment, using a MashMap-like method. The estimate is written to a new dv:f tag.

**Comment by lh3** [comment]
Just added "dv" to the man page via aef7b07. BTW, you can also find the table [here](https://lh3.github.io/minimap2/minimap2.html#10).

**Comment by stopalopa** [comment]
Hi, 
I noticed that some alignments don't have the dv tag. Under what circumstances will this tag not be present?  

Thanks, 
Natasha

**Comment by aaronphillips7493** [comment]
I also cannot see the dv tag in my whole-genome alignments. Have there been any updates on why this occurs?

Thanks,
Aaron

**Comment by lh3** [comment]
dv is approximate. It is only outputted when you don't perform base alignment.

**Comment by Raanaroohanitaziani** [comment]
how to decode a sma file output?  what this header means? there was no explanation in the manual. 

15e6db9f-7f75-400a-9e8e-a49e5892710d	256	gi|253771435|ref|NC_012947.1|	3013928	0

I hope someone can help me.

**Comment by lh3** [comment]
@Raanaroohanitaziani please read the SAM spec.

**Comment by Raanaroohanitaziani** [comment]
> 


> @Raanaroohanitaziani please read the SAM spec.

thanks for your reply. I am not sure how I can find the SAM spec for minimap2. I appreciate it if you can help me with this.

**Comment by chucknordy** [comment]
I just noticed that there is a mysterious SAM annotation tag ("**zd:i**", with small integer values) present in some of my alignments, which doesn't seem to be documented in the man page.  (I have minimap 2.24)  What does this "zd" tag represent?

**Comment by jdmontenegro** [comment]
I just noticed this today too, cannot seem to find the "zd" flag anywhere. mybe something to do with the z-drop score?

**Comment by CharlesARoy** [comment]
@lh3 is there a way to disable the output of the Minimap2-specific tags? They can cause issues in other tools such as GATK, e.g.:
https://gatk.broadinstitute.org/hc/en-us/community/posts/11440622639387-Unable-to-trim-uncertain-bases-without-flow-order-information

**Comment by lh3** [comment]
That was a GATK bug and [has been fixed](https://github.com/broadinstitute/gatk/pull/8337).

**Comment by CharlesARoy** [comment]
Thank you @lh3, I had seen that that was a GATK bug that had been fixed -- I mostly provided that example to illustrate one reason why someone might want to disable the minimap2-specific tags in the output. I take it that's not an option?

**Comment by lh3** [comment]
Not an option. It is not worth increasing tech debt for such rare bugs in downstream tools. Complicating the code base for these will make minimap2 harder to maintain in future.

**Comment by alisamatisse** [comment]
Hello, sorry for this question, but how is supplementary alignment determined (the algorithm)? I know it is chimeric reads, but I was really surprised to have 60% of chimeric reads in my samples 🤔
