### ISSUE TITLE
optimizing whole genome all vs. all alignment

### ISSUE THREAD

**Issue by ekg** [lh3/minimap2#251]
> @lh3lh3 : I'm running an all vs all alignment of ten 1Gbp genomes (fish), and finding that it's taking a long time. Using `-X -c -x asm20 -t 32`. I'm interested in making it quicker as I'm estimating many days (10-20) on a 32-core system.

https://twitter.com/lh3lh3/status/1052548379975315456

> Briefly, -X is culprit. Increasing -m/-s to thousands will help.

I've tried `-c -X -t 32 -x asm20 -m 4000 -s 8000` and find that this is between one and two orders of magnitude faster. I do also see that short sequences no longer align, which I think makes sense given the parameter. Would you please describe what they do?

The help documentation suggests to me that they prune low-quality chains and also throw out alignments that don't reach a given peak score, which would occur if they are short or if they have low identity.

**Comment by lh3** [comment]
> Would you please describe what they do?

`-m` sets the min chaining score. Weaker chains are discarded and won't go through base-level alignment. `-s` sets the min SW score. It is more like a post-filter. It doesn't affect performance much.

Generally, I don't recommend to use `-X` for whole-genome alignment as you will end up with many shorter hits contained in much long hits. I think the following procedure is better:
```sh
# self-alignment
minimap2 -DP -cx asm20 genome1.fa genome1.fa > 1-1.paf
minimap2 -DP -cx asm20 genome2.fa genome2.fa > 2-2.paf
minimap2 -DP -cx asm20 genome3.fa genome3.fa > 3-3.paf
# cross-alignment
minimap2 -cx asm20 genome1.fa genome2.fa genome3.fa > 1-c.paf
minimap2 -cx asm20 genome2.fa genome3.fa > 2-c.paf
```

**Comment by ekg** [comment]
Thanks for the tip @lh3. This could be a useful pattern to have available via one of the `-x` settings.

I'll script it out and see how things go.

**Comment by tseemann** [comment]
If not a new preset, at least add to the cookbook: https://github.com/lh3/minimap2/blob/master/cookbook.md

**Comment by lh3** [comment]
A preset has to be an often used case. This is not, unfortunately.

**Comment by ekg** [comment]
@lh3 what does `-DP` do? I don't see it in the output of `minimap -DP`.

**Comment by lh3** [comment]
https://lh3.github.io/minimap2/minimap2.html#5
