### ISSUE TITLE
2 error inducing reads from 48 million!

### ISSUE THREAD

**Issue by andrewstephenmason** [lh3/minimap2#259]
I've been using minimap2 (v2.12) with the splice preset on an Oxford Nanopore PromethION cDNA run mapping to the human genome (Ensembl GRCh38-p12). The dataset contains a total of 48781530 reads - average length of 1.2kbp (sd ~800bp). I was giving it decent memory on our linux cluster - 12 threads with 4G RAM per thread, but the mapping kept on failing "[morecore] insufficent memory"

I tried splitting the file up, and two of the smaller files gave the same error (and so on with multiple splits down to FASTQ fles with 2000 reads). I eventually identified that two reads caused these memory issues, and running minimap with just these reads individually causes the same memory issue and the program fails. I've attached these two reads for you to take a look at.

Both reads are very AT rich with long sections of AATAAT etc. (supporting a transcript stuck in a pore) and were long reads (45kb and 43kb). However, there were very similar reads in my dataset (for AT% and length) which did not cause memory problems (some mapped, some didn't). 

Can you advise on why specifically these two reads caused a problem, and whether there would be a way to filter out such reads before mapping? I was working on the basis of not filtering at all before attempting to map (on read length, quality etc.) as I didn't have any good reason to do any specific filtering (before now!).

Thanks in advance - any comments would be great.
[promethION_long_read_error_forcing_reads.fastq.gz](https://github.com/lh3/minimap2/files/2519926/promethION_long_read_error_forcing_reads.fastq.gz)

**Comment by lh3** [comment]
What command line are you using? With the default `-x splice`, these two sequences don't take too much memory. Anyway, I have added a new option`--cap-sw-mem`. With `--cap-sw-mem=4g`, for example, minimap2 will avoid doing alignment if the Smith-Waterman matrix is larger than 4GB.

**Comment by andrewstephenmason** [comment]
Hi Heng, thanks for getting back to me (apologies for my delayed response, notifications going to the wrong email account). 
My command is: `minimap2 -ax splice --split-prefix foo -L -t 12 -2 ref.fa reads.fq.gz`
I gave 4G RAM per thread and it failed for me. An issue in that command?
Thanks anyway for the new flag. I'll get our IT to perform a new pull.

**Comment by lh3** [comment]
Which version of GRCh38 are you using? What is the file size?

**Comment by andrewstephenmason** [comment]
I'm using the patch12 from Ensembl, soft masked - it's the big one with everything in. 54G uncompressed.
That includes all the scaffolds, some haplotypes _etc_. So pretty massive. Is this the major problem?

**Comment by lh3** [comment]
*Never* use Ensembl's toplevel FASTA. That is by far the worst human reference genome. The memory issue may be caused by that. Probably 12*4GB won't be enough.

**Comment by andrewstephenmason** [comment]
Ok, thanks. I'll do some testing with the RefSeq version (GCF_000001405.38). I was using the Ensembl assembly for a direct comparison with the Ensembl-annotated transcripts and hadn't realised the differences in reference quality (or file size...)
Thanks for your help and comments!

**Comment by lh3** [comment]
See also:

https://lh3.github.io/2017/11/13/which-human-reference-genome-to-use

**Comment by andrewstephenmason** [comment]
Have you any comment on how much has changed with the more recent patches?
I can't find any alternate analysis directories for later releases.
