### ISSUE TITLE
All but one alignment pieces disappear 

### ISSUE THREAD

**Issue by peterbrucelee** [lh3/minimap2#26]
According to  [#16](urlhttps://github.com/lh3/minimap2/issues/16) , I use `htsbox samview` to convert SAM produced from minimap2 since CIGAR are too long.

However there is only one local alignment on IGV (igv version 2.3.97).

Below is the content in SAM
(CIGAR and subsequent columns are hidden for convinience)
(The final piece of alignment is the only one shown on IGV)

@ PG     ID:minimap2     PN:minimap2     VN:2.1.1-r341   CL:minimap2 -a -x splice result/ref.mmi result/out.fa
@ SQ     SN:gi|732682658|gb|CP009685.1|  LN:4636831
utg000001c      16      gi|732682658|gb|CP009685.1|     143874  60      21M1D34M . . .
utg000001c      2064    gi|732682658|gb|CP009685.1|     2384241 60      2316725H5 . . .
_**utg000001c      2064    gi|732682658|gb|CP009685.1|      1       60      4645502H . . .**_

I also use bwa-mem to do alignment , using `samtools view` to convert SAM , and there is no problem at all.
(You can download mentioned files below)
[ref](https://drive.google.com/open?id=0B1JxKd14ey73OEhmR1ZjbFAzWUU)
[query](https://drive.google.com/open?id=0B1JxKd14ey73dlpKcXNkRVBvcjg)
[sam : minimap2](https://drive.google.com/open?id=0B1JxKd14ey73NEZGa2pLYXRqUXM)
[sam : bwa-mem](https://drive.google.com/open?id=0B1JxKd14ey73eExKYkhtcHhNb2M)

It seems there are some problems in  `htsbox samview` (?) ; are there any other options to handle with long CIGAR?

**Comment by lh3** [comment]
BAMs with long cigars are different from typical BAMs. IGV doesn't support BAMs with long cigars, so can't display them properly. You may consider to use CRAM.

**Comment by MichaelsGITIGIT** [comment]
How to convert SAM to CRAM and view it in IGV:
https://thvd.net/index.php/2017/12/03/how-to-map-long-oxford-nanopore-reads-to-reference-genome-and-view-in-igv/
