### ISSUE TITLE
Structural variants from variant calling after assembly to reference alignment

### ISSUE THREAD

**Issue by wdecoster** [lh3/minimap2#268]
I have a [diploid human assembly](https://www.pacb.com/press_releases/pacific-biosciences-releases-highest-quality-most-contiguous-individual-human-genome-assembly-to-date/)  which I would like to use to call SVs by alignment to GRCh38. I followed the cookbook on [Calling variants from assembly-to-reference alignment](https://github.com/lh3/minimap2/blob/master/cookbook.md#asm-var), but I do get a rather low number of (larger) SVs.

Would some parameter tweaking help or is this not the right approach? Is the diploid structure of the assembly causing issues?

Thanks,
Wouter

**Comment by wdecoster** [comment]
Thanks, seems to work better!

**Comment by lh3** [comment]
I have documented the syndip procedure [here](https://github.com/lh3/CHM-eval/tree/master/dip-call).

**Comment by lh3** [comment]
Thanks. Fixed.
