### ISSUE TITLE
minimap2.sh: line 34: 17631 Illegal instruction     (core dumped)

### ISSUE THREAD

**Issue by abayega** [lh3/minimap2#27]
Hi,

just can't figure out why minimap2 keeps failing, kindly assist me. The command am running is shown in the last line. Thanks
```
[M::mm_idx_gen::28.344*1.30] collected minimizers
[M::mm_idx_gen::32.368*2.39] sorted minimizers
[M::main::32.368*2.39] loaded/built the index for 55494 target sequence(s)
[M::mm_mapopt_update::37.048*2.21] mid_occ = 266; max_occ = 1612
[M::mm_idx_stat] kmer size: 15; skip: 5; is_HPC: 0; #seq: 55494
[M::mm_idx_stat::38.676*2.16] distinct minimizers: 63186547 (65.76% are singletons); average occurrences: 2.262; average spacing: 3.042
minimap2.sh: line 34: 17631 Illegal instruction     (core dumped) minimap2 -ax splice -t 23 olivefly_supernova_v1p1_corrvalid_group_gt10_500000bc_74X_seed0.pseudohap.1.fasta Cc.E.5H_all_rnaseq_combined_pass.trimmed_stranded.fasta > Ccap01172013-genome-Cc.E.5H_all_rnaseq_combined_pass.trimmed_stranded.sam
```

**Comment by lh3** [comment]
Supernova assembly won't be very useful for long-read rna-seq mapping because it is too fragmented. That said, as long as minimap2 segfaults, it is a bug. Could you send me a sample file that can trigger segfault? Due to the specialty of your reference genome, I can't reproduce it on my data and without reproducing the segfault, I am unable to fix it. Thanks.

**Comment by abayega** [comment]
Hi, another genome giving the same error is downloaded from 

https://i5k.nal.usda.gov/sites/default/files/data/Arthropoda/cercap-%28Ceratitis_capitata%29/Current%20Genome%20Assembly/1.Genome%20Assembly/BCM-After-Atlas/Contigs/Ccap01172013-contigs.fa.gz. Its 490Mb and if this is too big let me know and I will try to get you a smaller file.

**Comment by lh3** [comment]
Thanks a lot. I have downloaded the genome. Do you have a small fastq that leads to segfault when mapping against this genome? Thanks.

**Comment by abayega** [comment]
[1.fasta.txt](https://github.com/lh3/minimap2/files/1323202/1.fasta.txt)
I have attached a file, just five reads. Got the same error aligning those reads to the reference in the link.

Many thanks for the help

**Comment by lh3** [comment]
I could not reproduce the bug.

Which minimap2 version are you using? You can see this from `minimap2 --version`. Also, could you run
```
grep sse2 /proc/cpuinfo | head -1
```
and give me the output? Thanks.

**Comment by abayega** [comment]
Ah, I just downloaded the latest release from github less than 4 hours ago.

minimap2 --version
2.1-r311

uname -a
Linux cp2055 2.6.32-642.6.2.el6.x86_64 #1 SMP Wed Oct 26 06:52:09 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Currently Loaded Modules:
  1) ccstools        3) torque   5) StdEnv               7) pgi64/11.10          9) bioinformatics/samtools/1.3.2
  2) bqtools/4.2.3   4) maui     6) intel64/12.0.5.220   8) pathscale/4.0.12.1  10) python64/3.5.2

grep sse2 /proc/cpuinfo | head -1
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm 3dnowext 3dnow constant_tsc rep_good nonstop_tsc extd_apicid amd_dcm pni monitor cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt nodeid_msr npt lbrv svm_lock nrip_save pausefilter

**Comment by lh3** [comment]
This is a known issue with minimap2 v2.1 or earlier. This happens when you compile minimap2 on a recent CPU with SSE4 but run on an older CPU without SSE4. See also #21.

Please download the latest version v2.2-r409. You can also consider to use the binary release.

**Comment by abayega** [comment]
Not to re-open this issue, just want to mention that v2.2-r409 worked well. Thanks for your quick help...

**Comment by lh3** [comment]
Good to know. Thanks for the report anyway, so I know the new feature is useful.
