### ISSUE TITLE
Align through LINEs

### ISSUE THREAD

**Issue by armintoepfer** [lh3/minimap2#270]
Hi!

Is there any way to align through LINEs as long insertions instead of breaking the mapping and aligning the LINE somewhere else in the human genome?

Thank you!

**Comment by lh3** [comment]
Try something like `--lj-min-ratio=0.2`.

**Comment by chocotwig** [comment]
Hi, if the reference genome is poorly assembled, and long reads are longer than the ref. genome, would --lj-min-ratio still be capped by the % of long read aligned to the ref genome?
Thanks!
