### ISSUE TITLE
Mask level question

### ISSUE THREAD

**Issue by armintoepfer** [lh3/minimap2#271]
Hi Heng,

I know you added `--hard-mask-level` to honor `-M 0` to avoid overlapping chains. This has the side effect that following genome events won't get aligned.

Original reference has three blocks 
```
|A|B|C|
```
Genome of interest underwent a duplication of B and a LINE insertion
```
|A|B|L|B|C|
```

The alignment with default parameters looks like this:
![image](https://user-images.githubusercontent.com/1433286/48410908-4963ca80-e740-11e8-84c9-2ffc43935195.png)

If I use `--hard-mask-level -M 0 --secondary=no`, only the second part gets aligned.

Do you have any idea how I could align such events, while not allowing the same query interval being aligned twice? Is there maybe a trim query overlaps feature, while keeping overlaps in reference space?

```
minimap2 -d hg19.mmi -x map-pb human_hs37d5.fasta
minimap2 --secondary=no hg19.mmi y.fasta -a | samtools sort > a.bam && samtools index a.bam
minimap2 --hard-mask-level -M 0 --secondary=no hg19.mmi y.fasta -a | samtools sort > b.bam && samtools index b.bam
```

[y.fasta.gz](https://github.com/lh3/minimap2/files/2576082/y.fasta.gz)

Thank you!
Armin

**Comment by armintoepfer** [comment]
Any idea, otherwise I need to start post-processing the alignments...which will be very ugly :/

**Comment by lh3** [comment]
Sorry. I don't have a good solution to that.

**Comment by armintoepfer** [comment]
Would you be willing to implement a repeated matches algorithm that splits overlapping query intervals? I understand that this is nothing that can be implemented in short term, but my understanding is that this would enable more people using mm2.

The nanopore SV paper uses LAST over BWA-MEM to explicitly handle this issue: https://www.nature.com/articles/s41467-017-01343-4

> The NanoSV algorithm developed here uses LAST BAM files as input. We did not use BWA-MEM alignments as NanoSV input, because the reads are not always split in non-overlapping segments. More precisely, we observed that the following two (oversimplified) CIGAR strings may be produced, for two aligned segments originating from the same sequencing read: 6M4S and 4S6M, respectively. While at least some of these alignments are marked as secondary by BWA and can be simply discarded from the analysis, we found that the LAST alignment splitting of the same reads leads, in some cases, to identification of otherwise high-confidence structural variants. This observation was not further investigated for the purpose of this project. See Supplementary Fig. 25 for a real example extracted from our data.

![image](https://user-images.githubusercontent.com/1433286/48700640-c97cab00-ebec-11e8-9efd-fde7bc644dd8.png)

Here is the actual method described: https://genomebiology.biomedcentral.com/articles/10.1186/s13059-015-0670-9

**Comment by lh3** [comment]
Generating non-overlapping alignment is a good feature to have. A simple heuristic could be to walk through two CIGARs and find the max scoring split. This will still take time to implement.

In the context of long INDEL calling, the direction in #270 is generally preferable over the nanosv approach. Nanosv is not as good as sniffles according to a [recent study](https://www.biorxiv.org/content/early/2018/10/14/434118).

**Comment by armintoepfer** [comment]
I agree that one should try to align through the SV. But sometimes it just won't work if sequences flanking the SV are due to a duplication event.

At the end of the day, I want to give customers one parametrization that will align SVs properly and at the same time not inflate the number of bases mapped. We are at the stage at which more non-domain experts look at alignments and they can be easily confused if they count more mapped bases than the actual sequencing run provided.

**Comment by armintoepfer** [comment]
For what it's worth, in `pbmm2` I've implemented a basic version that keeps one alignment maximal and trims all other alignments' cigar strings using clips. I'll put it online beginning of 2019, unless you have a better version by then ;)

**Comment by chocotwig** [comment]
Hi, have there been any updates to the feature requested here? Thanks!
