### ISSUE TITLE
Python API for generating SAM file

### ISSUE THREAD

**Issue by obsh** [lh3/minimap2#273]
Hi,
I'm working on python HTTP service that uses Mappy.
The service is initialized with fasta file and should respond with SAM file text when requested with fastq over HTTP.

I wonder if there are a python API methods that could help me to build SAM file content with headers etc, as it's done by CLI utility?

Thank you!

**Comment by lh3** [comment]
It is not possible right now. Adding the feature is a bit complicated.

**Comment by lh3** [comment]
I had a look at the source code. Adding SAM output mappy is too complicated. I developed mappy to avoid SAM parsing. If you want to generate SAM, best to use the command-line tool.

I am afraid that I will decline this feature request. Sorry.

**Comment by obsh** [comment]
Ok, thank you. I'm very interested in using mappy inside web server, so I'll check if I can avoid using SAM files as well)
