### ISSUE TITLE
Illegal instruction(python)

### ISSUE THREAD

**Issue by jacka87164** [lh3/minimap2#275]
Hi,

just can't figure out why mappy have fIllegal instruction (core dumped), 
kindly assist me. The command am running as follows shown. Thanks

```
a = mappy.Aligner('MT-human.fa')
for name, seq, qual in mappy.fastx_read('MT-orang.fa'):
    for hit in a.map(seq):
        print(hit)
```
Illegal instruction (core dumped)

$ head MT-human.fa

\>MT_human
GATCACAGGTCTATCACCCTATTAACCACTCACGGGAGCTCTCCATGCATTTGGTATTTT
CGTCTGGGGGGTATGCACGCGATAGCATTGCGAGACGCTGGAGCCGGAGCACCCTATGTC
GCAGTATCTGTCTTTGATTCCTGCCTCATCCTATTATTTATCGCACCTACGTTCAATATT
ACAGGCGAACATACTTACTAAAGTGTGTTAATTAATTAATGCTTGTAGGACATAATAATA
ACAATTGAATGTCTGCACAGCCACTTTCCACACAGACATCATAACAAAAAATTTCCACCA
AACCCCCCCTCCCCCGCTTCTGGCCACAGCACTTAAACACATCTCTGCCAAACCCCAAAA
ACAAAGAACCCTAACACCAGCCTAACCAGATTTCAAATTTTATCTTTTGGCGGTATGCAC
TTTTAACAGTCACCCCCCAACTAACACATTATTTTCCCCTCCCACTCCCATACTACTAAT
CTCATCAATACAACCCCCGCCCATCCTACCCAGCACACACACACCGCTGCTAACCCCATA

$ head MT-orang.fa
\>MT_orang
GTTTATGTAGCTTATTCTATCCAAAGCAATGCACTGAAAATGTCTCGACGGGCCCACACG
CCCCATAAACAAATAGGTTTGGTCCTAGCCTTTCTATTAGCTCTTAGTGAGGTTACACAT
GCAAGCATCCCCGCCCCAGTGAGTCGCCCTCCAAGTCACTCTGACTAAGAGGAGCAAGCA
TCAAGCACGCAACAGCGCAGCTCAAGACGCTCAGCCTAGCCACACCCCCACGGGAGACAG
CAGTGATAAGTCTTTAGCAATAAACGAAAGTTCAACTAAGCTACACTAACCCCAGGGTTG
GTCAACTTCGTGCCAGCCACCGCGGTCACACGATTAGCCCAAGTTAATAGAGATCGGCGT
AGAGAGTGTTTTAGATTCTTTTTCTCCCCAATAAAGCTAAAATTTACCTGAGTTGTAGAA
AACTTAAGCTAATACAAAATAAACTACGAAAGTGGCTTTAATATATCTGAACACACAATA
GCTAAGGCCCAAACTGGGATTAGATACCCCACTATGCTTAGCCCTAAACTTTAACAGTTA

**Comment by armintoepfer** [comment]
Likely guess, your system does not support the necessary SSE instructions.

**Comment by jacka87164** [comment]
What can i do

**Comment by armintoepfer** [comment]
Maybe for starters, what machine are you using, which OS, and how did you install minimap2?

**Comment by armintoepfer** [comment]
There you go. Your system does not support the necessary SSE instructions. You need to compile minimap2 on your own. Or rather, use a CPU that is not ancient :)

**Comment by lh3** [comment]
Exactly as @armintoepfer said.

You have to modify [setup.py:28](https://github.com/lh3/minimap2/blob/master/setup.py#L28) to:
```python
extra_compile_args.append('-DKSW_SSE2_ONLY')
```
and manually compile from the source with:
```sh
python setup.py build_ext
python setup.py install
```

**Comment by jacka87164** [comment]
thank you very much
