### ISSUE TITLE
constraining minimap2 in homopolymeric regions to improve polishing

### ISSUE THREAD

**Issue by chklopp** [lh3/minimap2#276]
When aligning long reads with a smaller homopolymeric stretch, with minimap2, on a longer homopolymeric genome region, most of the alignments have the deletion on the left (start of the homopolymer) but some have it on the right. 

[screenshot](http://genoweb.toulouse.inra.fr/~klopp/Homopolymers/homopolymer_alignment_example.png)

Is there a way to constrain minimap2 to put the deletion on the left in all cases. This would help for homopolymer region polishing.

**Comment by lh3** [comment]
Those right aligned gaps can't be shifted without reducing SW alignment scores. That is the consequence of high sequencing error rate. That can't be solved within minimap2.

**Comment by armintoepfer** [comment]
I bet it depends on the strand, color the reads by strand

**Comment by fangli08** [comment]
How about reducing SW alignment score and shift the gaps to the left? this would help to cluster the reads with insertions/deletions.
