### ISSUE TITLE
Unable to use paftools

### ISSUE THREAD

**Issue by wyzhangMPI** [lh3/minimap2#277]
Hi,
   I am not able to use paftools.js, the error info is like:
/home/wyzhang/opt/biosoftware/minimap2/misc/paftools.js:1: SyntaxError: Unexpected token ILLEGAL
#!/usr/bin/env k8
^
SyntaxError: Unexpected token ILLEGAL.

I have my K8 in the path:
-bash-4.2$ k8 -v
V8: 3.16.14
K8: 0.2.1-r57

Could you help to take a look at what is wrong there?

**Comment by lh3** [comment]
You need the latest k8.
