### ISSUE TITLE
About strand information in spliced alignment

### ISSUE THREAD

**Issue by lauraht** [lh3/minimap2#28]
Hi Heng,

I just used minimap2 (version 2.2) for spliced alignment of PacBio reads to human genome.
I used “-ax splice” option.

For some reason, the minimap2 output alignments do not contain strand information. We expected that spliced reads would contain the XS tag, but my minimap2 output does not contain any XS tag. 

I am guessing that “-u b” option may be able to provide the XS tag for the spliced read. But the “-x splice” option already includes the -ub option according to the minimap2 2.2 manual. So maybe I was missing something else here?

I’d greatly appreciate your advice.

Thank you very much!

**Comment by lh3** [comment]
Minimap2 uses `ts` for the transcript strand. Note that not all reads have the tag.

**Comment by lauraht** [comment]
So you mean in minimap2 output, “ts” tag will be the replacement of the XS tag for the spliced read, is that right?

Thank you very much for your help!

**Comment by lh3** [comment]
I am closing this issue for now. If you have further questions, please feel free to reopen it or create new issues.
