### ISSUE TITLE
Paftools junceval output file

### ISSUE THREAD

**Issue by kathrinjansen** [lh3/minimap2#280]
Hi,
thanks a lot for this great tool! I've run paftools junceval using the -p and -e options but couldn't find any information on the columns in the output file. My guess is that column 1 indicates  some class of intron (N/P or C), Column 2 is the read name. Column 3 could be the number of overlaps found for the read and column 4 definitely the chromosome name (here Ensembl chromosome names). The range could be the intron and then I’m not sure, if the list of ranges indicates the other overlaps for that read?

An example row is below. This is ONT-data mapped with minimap2, deduplicated and using an assembly as the GTF in the paftools command:
``` paftools.js junceval -e -p <gtf> <sam> ```

Line from output file:
``` P       ec0d33d1-96fc-47f1-aa9d-60ddd6c2e91f    1       1       3211416 3211494 [(3207317,3213438), (3207317,3213608)] ```

Could you clarify or add to the documentation, what the output of paftools.js junceval is?

Thanks a lot for clarifying,
Kathrin

**Comment by lh3** [comment]
This output is mostly for me to debug minimap2, so it is not documented. Briefly, a C-line corresponds to a correct intron, P-line for a false positive and N-line for a false negative. On these lines, the first few fields are:

1. C/P/N
2. read name
3. intron number on the read (i.e. the 1st intron on the reads, etc)
4. mapped chr
5. mapped intron start
6. mapped intron end

For C/P lines, the last column shows the list of annotated introns that overlap with the mapped intron.

**Comment by kathrinjansen** [comment]
Thanks for the quick reply and explanation. This is very helpful! Could I ask another (maybe obvious) question:  Is it generally possible that introns classified as “false-positive” could be introns of a novel transcripts (= transcript not in the annotation)? I guess it would only be likely, if that read had another intron which matches the annotation (=“C intron”).

**Comment by lh3** [comment]
Yes. junceval assumes the GTF file is accurate and complete.

**Comment by kathrinjansen** [comment]
Okay, that makes sense. Thanks for your help!
