### ISSUE TITLE
Alignment identity

### ISSUE THREAD

**Issue by XMTian** [lh3/minimap2#281]
Hi,
    I use this tool for assembly vs assembly alignment, it's really run so fast. And I find the output format is sam. So could convert the sam file to other format witch can report alignment identity.Because I need use identity to filter my fasta set. 
    Thanks in advance.

**Comment by wdecoster** [comment]
Are you perhaps looking for the NM tag?

**Comment by XMTian** [comment]
I need use the identity information to get the low identity sequences to construct an animal pan-genome.
I afraid that NM tag is not for my case.
The NM tag is the abbreviation of number of mismatches. But if I use this tag, I must to calculate the identity by myself. So I wonder if there are any downstream software could convert the alignment information to other format. Just like the Blast, mummer's output format.
Like this:
Query-name Query-start Query-end Target-name Target-start Target-end Identity Coverage Direction 

Because I need use this information to filter sequences whose identity below 90%, 95% and so on from my query set.
Thanks for your reply!

**Comment by lh3** [comment]
Use the [PAF](https://github.com/lh3/miniasm/blob/master/PAF.md) output (option `-c` instead of `-a`).

Note that the definition of "identity" varies. It is still recommended to write your own script for precise filtering.

**Comment by lh3** [comment]
The master branch outputs a new tag `de:f`, which gives an estimate of sequence divergence. Identity equals "1-divergence".

**Comment by lh3** [comment]
It counts mismatches. See

https://lh3.github.io/2018/11/25/on-the-definition-of-sequence-identity
