### ISSUE TITLE
Confusion about the description of perset asm-to-ref mapping in 2.14-r883

### ISSUE THREAD

**Issue by MinngLi** [lh3/minimap2#282]
Hi @lh3 ,
I download the latest version minimap2 (2.14-r883) from bioconda. And I found the description 
 of the option "-x" in command-line as follow:
`- asm5/asm10/asm20: asm-to-ref mapping, for ~0.1/1/5% sequence divergence`

But, when I read the detailed description of the command-line options in website (https://lh3.github.io/minimap2/minimap2.html). I found the explain as follow:

asm5 | Long assembly to reference mapping (-k19 -w19 -A1 -B19 -O39,81 -E3,1 -s200 -z200 --min-occ-floor=100). Typically, the alignment will not extend to regions with 5% or higher sequence divergence. Only use this preset if the average divergence is far below 5%.
-- | --
asm10 | Long assembly to reference mapping (-k19 -w19 -A1 -B9 -O16,41 -E2,1 -s200 -z200 --min-occ-floor=100). Up to 10% sequence divergence.
asm20 | Long assembly to reference mapping (-k19 -w10 -A1 -B6 -O6,26 -E2,1 -s200 -z200 --min-occ-floor=100). Up to 20% sequence divergence.

I have a little confusion about the different description of sequence divergence. For the asm10, does it means the average sequence divergence should be less than 1% when I use "asm10" to do asm-to-ref mapping and it will be unmapped when the sequence divergence is more than 10% in some regions?

Best,
Ming

**Comment by lh3** [comment]
> For the asm10, does it means the average sequence divergence should be less than 1% when I use "asm10" to do asm-to-ref mapping and it will be unmapped when the sequence divergence is more than 10% in some regions?

Yes.
