### ISSUE TITLE
-x asm5 assembly to genome mapping, MAP=60 alignment to more than one genome chrs

### ISSUE THREAD

**Issue by liuxl18-hku** [lh3/minimap2#283]
Dear Heng,

I tried to map our assembly (scaffolds) to GRCh38 genome for sanity check.

The below is the records of the query assembly scaffold (there is one of them which is not with MAP=60, I removed it):

```
Scaffold_1278;HRSCAF=4794	224847	103106	224830	+	chr21	46709983	9527151	9649244	89154	122569	60	tp:A:P	cm:i:8417	s1:i:88985	s2:i:23883	dv:f:0.0093
Scaffold_1278;HRSCAF=4794	224847	72568	192589	+	chrUn_KI270750v1	148850	7	120495	88606	120998	60	tp:A:P	cm:i:8323	s1:i:88414	s2:i:6934	dv:f:0.0101
Scaffold_1278;HRSCAF=4794	224847	3092	26763	-	chr17	83257441	22135157	22159048	11210	24253	60	tp:A:P	cm:i:867	s1:i:11027	s2:i:7864	dv:f:0.0478
Scaffold_1278;HRSCAF=4794	224847	60863	78558	+	chr13	114364328	63056766	63074855	5105	18414	60	tp:A:P	cm:i:354	s1:i:4903	s2:i:2816	dv:f:0.0785
Scaffold_1278;HRSCAF=4794	224847	57737	60715	-	chr20	64444167	26165865	26169101	1335	3311	28	tp:A:P	cm:i:98	s1:i:1254	s2:i:1127	dv:f:0.0571
```

I was wondering, is it possible that this is a chimeric alignment case? Or it's due to bad quality sequences (self-alignment was done using both minimap2 -x asm5 and nucmer --mum, but didn't find repeat pattern)

The sequence fasta file was attached: [tmp.fa.gz](https://github.com/lh3/minimap2/files/2627497/tmp.fa.gz)

Thank you!

**Comment by lh3** [comment]
> I was wondering, is it possible that this is a chimeric alignment case?

Yes. Such alignments happen all the time. They don't have to do with tandem repeats.
