### ISSUE TITLE
Proposition for the propagating back the "a" array length

### ISSUE THREAD

**Issue by ungsik** [lh3/minimap2#284]
In 
https://github.com/lh3/minimap2/blob/2c52364527268358448e6552923bb12d6f994025/chain.c#L154
"a" array is truncated to the length of k, but the n_a is not updated or propagated back.
The length information for the newly created "a" is lost.

By passing the n_a as a pointer and updating the value,
the information for the length of "a" array can be cosistently maintained.

**Comment by lh3** [comment]
The new length of `a[]` can be inferred from `u[]`.

**Comment by lh3** [comment]
PS: note how `k` is computed from `u[]` [here](https://github.com/lh3/minimap2/blob/2c52364527268358448e6552923bb12d6f994025/chain.c#L148-L151).
