### ISSUE TITLE
expected file size

### ISSUE THREAD

**Issue by dcopetti** [lh3/minimap2#285]
Hello,

I am doing the overlap stage for a miniasm assembly, and I wonder if there is a way to estimate the size of the minimap2 file I will get.
The command I am using is
`minimap2 -x ava-ont -t 18 -K 1000M ONT_181026.fa ONT_181026.fa | gzip -1 >ONT_overlaps.paf.gz`
and the fasta file is 100 GB in size, 19.5M PromethION reads, N50 10 kb, median quality 6.6.

Also, approximate run time of minimap2 and miniasm could be useful to know, given 20 cpus and 128 GB of RAM.
thanks

**Comment by lh3** [comment]
Sorry. I don't know. That may vary a lot with your genome.
