### ISSUE TITLE
nanopore with -k option

### ISSUE THREAD

**Issue by MDsc09** [lh3/minimap2#288]
It would be very grateful if I have your advice on my related questions:

Q1) ‘-x map-ont’ option could be applied to ONT-data, and you mentioned -k 15.
I’m wondering why you set ’15’ and what this actually mean. 
if my data has 21nt ONT-adapter sequence, and do I need to apply -k 21? any other options would be required for better performance?
OR, can I do like this: manual adapter trimming (according to my design), and applying without -x map-ont and -k 0?

Q2) Actually, there are additional indexing sequences prior to actual RNA sequences.
(ONT-adapter-21nt — other-manual-index-20nt — (variable sized RNA sequences))
in this case, do I need to apply -k 42 ?

Many thank in advance!

**Comment by lh3** [comment]
You should learn the blast algorithm first. `-k` changes the seed length.

For ONT reads, just use `-x map-ont`. Usually you would like to use `-a` to generate SAM.
