### ISSUE TITLE
Core dump during alignment with long reads

### ISSUE THREAD

**Issue by pvikman** [lh3/minimap2#290]
Hi

I've had an issue during alignment with core-dumps. This only happends with -k 7 set, minimap2 works fine when aligning all my data set with k 11 or 15. The alignment is done versus a premade human genome index.  I have two kinds of data, PCR amplified data of a few genes and whole transcriptome data. The whole transcriptome data aligns fine but the PCR amplified data causes core dumps everytime I try to run. I use the flag -splice. I have one PCR based run that works but it is only 30Mb worth of fastq.

The whole transcriptome data is by far the largest with a fastq file of 1.7 Gb, the PCR data between 300-700 Mb. The nodes I've been running it on have up to 200Gb worth of RAM. The core dump files are from 30-80Gb files. I've used three cores for the run. When looking at the data after k11 alignments I have up to ~17-18000 worth of coverage in the most data dense positions.

So I know that the data is ok since it aligns with other settings. It does not appear to be a data amount issue since the 1.7Gb file works fine. There's no other jobs affecting the alignments since I've used nodes dedicated for my jobs. So no competition for resources. I've thought about dividing the fastq file into several, aligning and then mergin the sam files but it seems like a lot of work.

**Comment by lh3** [comment]
There are probably integer overflow somewhere. However, I don't think it makes sense to use -k7 for human data. I won't make changes unless this recurs in a more realistic setting.
