### ISSUE TITLE
settings for minimap2 for denovo assembly a large heterozygous plant genome

### ISSUE THREAD

**Issue by JifengTang** [lh3/minimap2#291]
Hello,
I am doing a nanopore assembly for a large heterozygous plant genome using minimap2 and miniasm.
The haploid genome size is about 2.5G and input data about 100x. Besides, top long 50x input data is selected.
1) which input data do you recommend to use, all data or top long 50x input data?
2) which settings of minimap2 should be used to align the input data?

I appreciate any related information.

**Comment by lh3** [comment]
For minimap2, use the right preset. I don't recommend to use miniasm for large genomes.

**Comment by JifengTang** [comment]
Thank you very much for the quick reply. 
Which tool do you recommend to assemble a large genome using minimap2 output?
which input data do you recommend to use all data or top long 50x?

Thanks a lot.

**Comment by lh3** [comment]
Canu or wtdbg2

**Comment by lh3** [comment]
They come with their own overlappers and don't use minimap2 by default.
