### ISSUE TITLE
How to get long cs tag in python?

### ISSUE THREAD

**Issue by OmegaNJU** [lh3/minimap2#292]
I really appreciate the python extension of minimap2, but how could I get the long style cs tag (which could be outputted by --cs=long in command) via `aligner.map` function? the API of Aligner.map I could see only have a trigger of whether calculate cs tag.

**Comment by lh3** [comment]
Not possible, but as you know the query sequence, you can reconstruct the long form easily.

**Comment by OmegaNJU** [comment]
Thanks for your reply! Reconstruction seems feasible but I am a beginner in DNA sequencing research. I think I should write these basic parsers gradually, although it may be a long process.:smile:
