### ISSUE TITLE
Canonical splice site

### ISSUE THREAD

**Issue by sjackman** [lh3/minimap2#293]
I'm aligning ESTs to a plant mitochondrial genome where the canonical splice sites are
`5' - GYGYG … ANNNNAY - 3'`
where Y is C or T. Is it possible to specify the canonical splice site sequence?

**Comment by sjackman** [comment]
Here's the relevant code. Seems like the canonical splice sequence is hard coded.
https://github.com/lh3/minimap2/blob/c63a33904f9c28a2005d10246e3d51a810bd1b14/ksw2_exts2_sse.c#L113-L131

**Comment by lh3** [comment]
Yes, this is hard coded. The general solution would be a position specific matrix, but I don't see I will implement that in a foreseeable future unfortunately.

**Comment by sjackman** [comment]
No worries. Thanks for the response, Heng. For future readers, Exonerate supports a position-specific matrix with its `--splice5` and `--splice3` options. See *Splice site prediction options* in 
https://www.ebi.ac.uk/about/vertebrate-genomics/software/exonerate-manual

Do you know of any other spliced aligners that support changing the canonical splice motif? Even changing it to the simplified motif `GB-AY` would help, though the full motif would be better. I may try hacking up minimap2 and see what happens.
