### ISSUE TITLE
paftools.js call for ref that is missing in query?

### ISSUE THREAD

**Issue by nextgenusfs** [lh3/minimap2#294]
It seems that regions of the reference that do not have an alignment, are not called variants by `paftools.js call ` -- this is also stated in the docs.  I have a region on end of chromosome missing in the query compared to the reference (~ 50 kb) -- in this case (a terminal mismatch), would be nice of `paftools.js call` also called this a variant. Is there a workaround for identifying these regions from within `paftools.js call`?  I knew about this particular one -- but wondering if I'm missing others.

**Comment by lh3** [comment]
What you described is not a variant by typical definition.
