### ISSUE TITLE
7849 Segmentation fault

### ISSUE THREAD

**Issue by pomidorku** [lh3/minimap2#295]
I am running Minimap2 in an Intel cluster. I am trying to remove some "contaminants" from my pacbio reads (converted to fastq). I downloaded the reference sequence from NCBI.
I submitted the job and the cluster returned a "job successfully finished" message. However, there is a core file in the output directory and the last line of the stderr file reads  "7849 Segmentation fault   (core dump)". The output file has size 0 (empty?).

I cannot attach the stdout file because it is empty (0 kb size). I am attaching the and the job submitted to the cluster, showing the command line and the parameters I used.

[stderr.txt](https://github.com/lh3/minimap2/files/2673111/stderr.txt)
[minimap2KurthiaVsMoell5pcJOB.txt](https://github.com/lh3/minimap2/files/2673112/minimap2KurthiaVsMoell5pcJOB.txt)

Thank you in advance for your help.

Pomidorku

**Comment by lh3** [comment]
Please don't run under LSF.

**Comment by pomidorku** [comment]
lh3,

Thank you for your answer. I did run minimap2 for other sequences in a similar fashion, with different options (e.g., -ax map-pb) and it worked fine in the cluster.

Do you mean that the particular option(s) "-ax asm5" should not be run in lsf, or minimap2 should not be run in lsf at all?

Regards,
pomidorek

**Comment by lh3** [comment]
LSF adds an extra layer which makes it difficult to tell the source of the problem. When debugging, we have to peel off those extra layers as much as possible. I can't move forward without concrete examples. Your current report helps little, I am afraid.

**Comment by pomidorku** [comment]
I will try to install minimap2 locally (in my laptop) so I will have screenshots of the run that I could offer you to help find out the problem. I may be able to get back to you by Friday or Monday.
Thank you fro your help.
Regards,
pomidorku
