### ISSUE TITLE
bam file income

### ISSUE THREAD

**Issue by drehertw** [lh3/minimap2#296]
Minimap2 is producing sam files that when converted to bam by Samtools are incompatible with the gene analysis software Geneious. 
The error report is:
Failed to import minimap_alignment.bam (SAM/BAM alignments importer): Cannot parse read m54080_180314_232731/5309163/ccs (reversed): Trailing soft trim exceeds length of whole sequence 

Are you aware of this problem and is there a patch available?

Thanks.

**Comment by lh3** [comment]
Please provide sample data to produce the issue. This seems more like errors on your end, tbh.

**Comment by drehertw** [comment]
Dear Heng,

If you go to
http://files.cgrb.oregonstate.edu/Dreher_Lab/
you’ll see the sam file generated by minimap2 and then the sort.bam file created from it by Samtools.

Thanks for responding so quickly.

Perhaps you can also give advice on using minimap2 to map raw PacBio fastq subreads to bridge the contigs from an assembly that hasn’t completed a genome.

Thanks,

Theo

Theo Dreher
Professor of Microbiology
226 Nash Hall
Oregon State University
Corvallis, OR 97331
541-737-1795

**Comment by drehertw** [comment]
1.817u 12.649s 0:34.95 41.3%           0+0k 24700568+0io 0pf+0w


Theo Dreher
Professor of Microbiology
226 Nash Hall
Oregon State University
Corvallis, OR 97331
541-737-1795
