### ISSUE TITLE
Parameters for minimizers in minimap2

### ISSUE THREAD

**Issue by arlamng74** [lh3/minimap2#298]
Dear Heng,

I am reading your paper about minimap2 and testing the program using samples from Genome in a Bottle Project.  I have a question related to the parameters settings.  For the minimizers variables k and w, what was the criteria or rationale to set those particular default numbers I see in the preset options for each different scenario?   

Any reference that I can take a look?  Any suggestion is greatly appreciated. 
Thanks a lot
Alfonso

**Comment by lh3** [comment]
> Any reference that I can take a look? Any suggestion is greatly appreciated.

No. Mostly heuristic. Generally, you would like to use longer and fewer k-mers for performance, as long as you can sufficiently seed alignments in the presence of sequencing errors and variants.
