### ISSUE TITLE
-bash: minimap2: command not found

### ISSUE THREAD

**Issue by Alahmadoz** [lh3/minimap2#300]
Hello,

After installing the software minimap2 successfully, and type the command ‘minmap2'.... its saying ‘command not found’. Could you please help me in sorting out this?

Kind regards

**Comment by wdecoster** [comment]
Did you install using conda? Is the executable in $PATH?

**Comment by Alahmadoz** [comment]
Thanks for your reply.

I installed it using two different computers: 1) Ubuntu and 2) Mac, and I faced the same problem with both of them saying 'command not found' after installing the software using the command: Curl -L https://github.com/lh3/minimap2/releases/download/v2.14/minimap2-2.14_x64-linux.tar.bz2 | tar -jxvf -./minimap2-2.14_x64-linux/minimap2


Could you please clarify more what’s it Conda and how can I know if the executable in $PATH?

Also, when I type 'echo $minimap2’ nothing or no path appears!

Kind regards


Ahmad

**Comment by lh3** [comment]
See:

https://www.cyberciti.biz/faq/linux-unix-command-not-found-error-and-how-to-get-rid-of-it/

Or use the full path.
