### ISSUE TITLE
NM tag for supplementary alignment

### ISSUE THREAD

**Issue by wdecoster** [lh3/minimap2#302]
I see reads with a supplementary alignment of which the NM tag is suspiciously large. I don't know if this is expected or could be a bug. It might be a misunderstanding on my side of how the NM tag is calculated in this case, but I see reads having a higher NM value than the aligned read length, using v2.14-r883 and aligning to the GRCh38 genome (ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/001/405/GCA_000001405.15_GRCh38/seqs_for_alignment_pipelines.ucsc_ids/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz)

You can find the fastq of a few reads with this behavior here: https://www.dropbox.com/s/kho5tkosxcwfxis/NM-issues.fastq.gz?dl=0
The corresponding bam of these reads can be found here: https://www.dropbox.com/s/ykhltzuh4sjq6q5/NM-issues-realigned.bam?dl=0

**Comment by lh3** [comment]
Those are poor alignments and should be filtered out. It is hard to find a threshold working well in all scenarios. Minimap2 just outputs them all and lets users deal with them.

**Comment by wdecoster** [comment]
I see, thanks!
