### ISSUE TITLE
Inconsistent result when exchange query and target?

### ISSUE THREAD

**Issue by moold** [lh3/minimap2#305]
Hi Heng,
I found a weird result when I exchanged the order of query and target with parameter:  -x ava-ont.

When I used 131072.fa as target and 131118.fa as query, there was no mapped block.
`minimap2 -x ava-ont 131072.fa 131118.fa`

> [M::mm_idx_gen::0.003*1.19] collected minimizers
[M::mm_idx_gen::0.006*2.04] sorted minimizers
[M::main::0.006*2.04] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.006*1.96] mid_occ = 5
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.007*1.90] distinct minimizers: 11940 (99.15% are singletons); average occurrences: 1.012; average spacing: 2.937
[M::worker_pipeline::0.010*1.56] mapped 1 sequences
[M::main] Version: 2.14-r894-dirty
[M::main] CMD: ../../test/minimap2/minimap2 -x ava-ont 131072.fa 131118.fa
[M::main] Real time: 0.011 sec; CPU: 0.017 sec; Peak RSS: 0.004 GB

but when I exchanged the order of query and target, it came out  a mapped block.
`minimap2 -x ava-ont 131118.fa 131072.fa`

> [M::mm_idx_gen::0.004*1.13] collected minimizers
[M::mm_idx_gen::0.007*2.02] sorted minimizers
[M::main::0.007*2.02] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.008*1.94] mid_occ = 7
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.008*1.88] distinct minimizers: 17665 (98.88% are singletons); average occurrences: 1.019; average spacing: 2.929
131072_1_35470	35470	6802	35247	+	131118_1_52717	52717	67	28568	10264	29182	0	tp:A:S	cm:i:1557	s1:i:10060	dv:f:0.1217
[M::worker_pipeline::0.012*1.58] mapped 1 sequences
[M::main] Version: 2.14-r894-dirty
[M::main] CMD: ../../test/minimap2/minimap2 -x ava-ont 131118.fa 131072.fa
[M::main] Real time: 0.013 sec; CPU: 0.020 sec; Peak RSS: 0.005 GB

But when I used 131072.fa as target and 131118.fa as query and without parameter:  -x ava-ont. It also had mapped blocks.
`minimap2  131072.fa 131118.fa`

> [M::mm_idx_gen::0.003*1.20] collected minimizers
[M::mm_idx_gen::0.005*1.90] sorted minimizers
[M::main::0.005*1.90] loaded/built the index for 1 target sequence(s)
[M::mm_mapopt_update::0.005*1.84] mid_occ = 5
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1
[M::mm_idx_stat::0.005*1.80] distinct minimizers: 6550 (99.16% are singletons); average occurrences: 1.011; average spacing: 5.356
131118_1_52717	52717	68	28546	+	131072_1_35470	35470	6803	35226	7453	29064	60	tp:A:P	cm:i:771	s1:i:7265	s2:i:73	dv:f:0.1282
131118_1_52717	52717	50051	50274	+	131072_1_35470	35470	11299	11527	50	230	12	tp:A:P	cm:i:5	s1:i:48	s2:i:0	dv:f:0.1435
[M::worker_pipeline::0.009*1.42] mapped 1 sequences
[M::main] Version: 2.14-r894-dirty
[M::main] CMD: ../../test/minimap2/minimap2 131072.fa 131118.fa
[M::main] Real time: 0.010 sec; CPU: 0.013 sec; Peak RSS: 0.003 GB

The input files has been attached and Could you give me some suggestions to avoid this when using -x ava-ont. Thanks.

[131072.zip](https://github.com/lh3/minimap2/files/2734934/131072.zip)
[131118.zip](https://github.com/lh3/minimap2/files/2734935/131118.zip)

**Comment by lh3** [comment]
`ava-ont` only performs alignment when the name of read1 is lexicographically smaller than the name of read2.

**Comment by lh3** [comment]
PS: you can add option `--dual=yes` to change the default `ava-ont` behavior.

**Comment by moold** [comment]
Thank you very much.

**Comment by wjyzidane** [comment]
I found the same phenomena. When you say the name of read1, do you mean the name of each read in the file? For example, here is the one read in my file:
@ab754073-739e-4938-8be0-3d57eebc4f35 
ATCGGTGGCGCTGGATTCAGTTACGTATTGCTAGGTTAAGAGGGACAAGGTTTCAACGCTTC

the name is "@ab754073-739e-4938-8be0-3d57eebc4f35"? If that is the case, does that mean minimap will ignore some read in file1 if the name is bigger than name of read in file2 even if there is a real overlap?

**Comment by lh3** [comment]
> If that is the case, does that mean minimap will ignore some read in file1 if the name is bigger than name of read in file2 even if there is a real overlap?

This is right, as long as you use `ava-*`.

**Comment by wjyzidane** [comment]
But I did not use any ava-*. I use only “minimap2 a.fa b.fa”. Do I still miss some overlap? Is there a way I can capture all the overlap?

**Comment by lh3** [comment]
> Do I still miss some overlap?

No.

**Comment by lh3** [comment]
Well, the answer is complicated. Without ava-*, minimap2 only output top few hits. As my previous answer said, use `-x ava-ont --dual=yes` together.

**Comment by wjyzidane** [comment]
Got you. Thanks!
