### ISSUE TITLE
Question about PAF format

### ISSUE THREAD

**Issue by JoseCorCab** [lh3/minimap2#308]
Hi, I'm using Minimap2 to align a transcriptome assembly against a draft genome of the same species for discard assembly artifacts and no-spliced transcripts. I have used the default command for cDNA against ref but only reporting primary alignments.

`minimap2 -x splice -uf -N0 -C5 genome.fasta transcriptome.fasta > alignment.paf`

I thought that each line in the PAF were equivalent to a BLAST Hit, but when I analyzed it I found the same query aligned more than once, and all these alingments labeled as primary. 

`new_standard_name_0000189506    3741    197     1846    +       Sosen1_s1076    185891  13710   16684   1626    2974    60      tp:A:P  cm:i:490        s1:i:1556       s2:i:0  dv:f:0.0073

new_standard_name_0000189506    3741    1847    3438    +       Sosen1_s1076    185891  16794   19677   1569    2883    60      tp:A:P  cm:i:493        s1:i:1499       s2:i:0  dv:f:0.0068

new_standard_name_0000189506    3741    0       193     +       Sosen1_s1076    185891  16642   16835   193     193     60      tp:A:P  cm:i:66 s1:i:193        s2:i:0  dv:f:0.0010

new_standard_name_0000189506    3741    3484    3738    +       Sosen1_s1076    185891  17564   17818   251     254     60      tp:A:P  cm:i:78 s1:i:78 s2:i:0  dv:f:0.0017

new_standard_name_0000189506    3741    3440    3482    +       Sosen1_s1076    185891  19595   19637   42      42      2       tp:A:P  cm:i:10 s1:i:42 s2:i:0  dv:f:0.0122
`
Furthermore I found the same query aligned in differents scaffolds.
Can you explain me what it means? What is a line exactly?

Thanks you!

**Comment by lh3** [comment]
You should add option `-c` to enable base alignment. Try that first and show me the results. Thanks.

**Comment by JoseCorCab** [comment]
> You should add option `-c` to enable base alignment. Try that first and show me the results. Thanks.

I have run the same command -c option added, here you have the resuts.

```
new_standard_name_0000189506    3741    995     3440    +       Sosen1_s1076    185891  15149   19679   2443    2451    60      NM:i:8  ms:i:2428       AS:i:1756       nn:i:0  ts:A:+  tp:A:P  cm:i:493        s1:i:1499       s2:i:0  dv:f:0.0068     cg:Z:118M97N102M1I2M73N137M264N162M82N119M169N212M109N154M80N107M74N3M4D101M98N146M215N191M74N93M80N118M135N141M217N130M144N2D131M84N186M85N91M

new_standard_name_0000189506    3741    194     1848    +       Sosen1_s1076    185891  13707   16686   1652    1656    60      NM:i:4  ms:i:1644       AS:i:1192       nn:i:0  ts:A:+  tp:A:P  cm:i:490        s1:i:1556       s2:i:0  dv:f:0.0073     cg:Z:27M71N152M89N133M181N153M117N155M78N2D181M103N116M97N103M72N139M264N164M82N116M169N215M

new_standard_name_0000189506    3741    3482    3741    +       Sosen1_s1076    185891  17562   17821   259     259     60      NM:i:0  ms:i:259        AS:i:259        nn:i:0  ts:A:+  tp:A:P  cm:i:78 s1:i:78 s2:i:0  dv:f:0.0017     cg:Z:259M

new_standard_name_0000189506    3741    0       194     +       Sosen1_s1076    185891  16642   16836   194     194     60      NM:i:0  ms:i:194        AS:i:194        nn:i:0  ts:A:+  tp:A:P  cm:i:66 s1:i:193        s2:i:0  dv:f:0.0010     cg:Z:194M
```


I interpret N as introns like in SAM format, then a line may be equivalent to a hit. If I'm not wrong there should not be hits in different scaffolds. I'm trying to understand it by myself but I can't. 

Thanks you!

**Comment by lh3** [comment]
> If I'm not wrong there should not be hits in different scaffolds.

No. There can be multiple local hits between a single pair of sequences. Blast/blat/gmap all do the same.
