### ISSUE TITLE
cs string lost in sam2paf

### ISSUE THREAD

**Issue by malonge** [lh3/minimap2#310]
Hi There,

I got my SAM file with the following command:

`minimap2 -ax asm5 --cs -t1` 

And I see the cs tag in the resulting SAM file. However, when I convert to paf with paftools.js, I seem to lose that cs string. Is there a way to retain the cs string when converting to paf? 

Thanks

**Comment by lh3** [comment]
Just implemented on github HEAD.

**Comment by malonge** [comment]
Awesome thank you so much!

**Comment by ArielSSchwartz** [comment]
This seems to be working only for primary alignments. Probably because of [this line](https://github.com/lh3/minimap2/blob/master/misc/paftools.js#L1688), since `t[9] == "*"` for secondary alignments.
