### ISSUE TITLE
map short sequence to nanopore sequencing result

### ISSUE THREAD

**Issue by wjyzidane** [lh3/minimap2#313]
Hello,

I try to detect multiple sequences (eg. A.fa) in my nanopore sequencing result (eg B.fq) and see how whether they are included and where is the position in the reads. Which parameter you would recommend using?

Previously, I tried to use only "minimap2 A.fa B.fq" and get a result like this:
![image](https://user-images.githubusercontent.com/34944811/51220533-9b24fe80-1903-11e9-87d3-87b446966423.png)

But I can not tell the meaning of each column. Where I can find a document for the explanation of output like this? Thanks!

**Comment by lh3** [comment]
README has the link: it is [PAF format](https://github.com/lh3/miniasm/blob/master/PAF.md). The [manpage](https://lh3.github.io/minimap2/minimap2.html#10) has the description as well. Please briefly read the documentations.

You can also get SAM with option `-a`.
