### ISSUE TITLE
mappy interface doesn't work with short reference sequences?

### ISSUE THREAD

**Issue by ayaanhossain** [lh3/minimap2#316]
Hi Dr. Li,

I have a reference file with a few thousand really short sequences like the following.

```
>1
CTCTGGCTCGTGATGCCAAG
>2
TAGTTGTGACAACAAGGCGA
>3
TAAGACGACGCGGTTAGCCC
>4
ATATGTTGTCCATGCGCGGC
>5
TAACTAACTCATCAGGCCAC
...
```

Unfortunately, after initializing a `mappy.Aligner(reference_file)`, I am unable to map sequences to the reference. I tried printing out the sequences in the index, using

```
for i in xrange(1, 6):
    print a.seq(str(i))
```
and encountered `Segmentation fault (core dumped)`.

I understand that minimap2 is primarily designed for long reads, and the short sequences as reference is not a trivial case, but is there a way I can make mappy work? Maybe fiddle with the `k` and `w` or something? I tried `k=11` and `w=1` but fault still persists.

**Comment by armintoepfer** [comment]
I wasn't able to align reads below 200 bp or so. Why don't you use bwa? You are actively misusing minimap2.

**Comment by ayaanhossain** [comment]
I can use bwa, but the issue is different here. According to "3.3 Aligning short genomic reads" of the minimap2 paper - "Minimap2 is 3–4 times as fast as Bowtie2 and BWA-MEM [...]" and "Minimap2 is broadly comparable to BWA-MEM in the context of small variant calling.", so minimap2 should be a good replacement for bwa right? I understand I am close to an edge case here, but this my regular use case - these really short references as well as really long references (not shown here), and I thought minimap2 could do both with decent accuracy.

**Comment by lh3** [comment]
Segfault is always bad. I will have a look at that later.

However, as @armintoepfer said, minimap2 is not intended for this use case. What are you query sequences?

**Comment by lh3** [comment]
I am looking at this. I have a FASTA `1.fa`:
```txt
>1
CTCTGGCTCGTGATGCCAAG
>2
TAGTTGTGACAACAAGGCGA
>3
TAAGACGACGCGGTTAGCCC
>4
ATATGTTGTCCATGCGCGGC
>5
TAACTAACTCATCAGGCCAC
```
and a script
```python
import sys
import mappy as mp
a = mp.Aligner(sys.argv[1])
print(a.seq("1"))
```
I can see the correct output. How can I reproduce your segfault? Thanks.

**Comment by ayaanhossain** [comment]
Thank you, I'll check this on my system and let you know shortly.
