### ISSUE TITLE
Could python sdk remove 'cg' tag information so that it can perform much faster?

### ISSUE THREAD

**Issue by huboqiang** [lh3/minimap2#317]
Hi, 
 I first tried to run the binary minimap directly:
```
minimap2  -x ava-ont f1.fa f2.fa
```

The cg tag would not generated.

Then I tried to remove 'cg' tag in Python SDK, and met some trouble. Here, why it must be 0x004 below?
```
		self.map_opt.flag |= 4 # always perform alignment
```

I noticed that 0x004 indicates `MM_F_CIGAR`,  and it would not be set as 1 in the `minimap2  -x ava-ont` command. So why it must be 4 here?  What should I do so that the SDK would not generate 'cg'? Thanks.

**Comment by lh3** [comment]
Mappy always computes the `cg` tag. Some other information depends on it. This won't be changed. Sorry.
