### ISSUE TITLE
Tune alignment parameters to align against a consensus

### ISSUE THREAD

**Issue by brguez** [lh3/minimap2#318]
Hello, 

I am interested into identifying L1 retrotransposition insertions from long-read alignments. To do this, I scan the bam searching for insertions and then I realign the inserted sequences against a L1 consensus sequence with minimap2. 

L1 inserted sequences are usually inverted at their 5' end, so I would expect minimap2 to align the sequence in two pieces: 5' end reversed (supplementary) and the remaining piece in forward (primary as usually longer) . However, although minimap2 correctly aligns the forward, it seems not able to align the other piece of the read. 

I would really appreciate some suggestion about how I could **tune the alignment parameters to get both pieces of the sequence aligned into the consensus**. 

The command I used is the following (I decreased k and w to be more sensitive): 
minimap2 -Y -k 11 -w 5 -a L1_consensus.txt insert.txt

Please see attached both the L1 consensus sequence (L1_consensus.txt) and one example of a L1 inserted sequence (insert.txt). It is 1899 bp long and its first 759 bp are inverted. 

[L1_consensus.txt](https://github.com/lh3/minimap2/files/2799426/L1_consensus.txt)
[insert.txt](https://github.com/lh3/minimap2/files/2799427/insert.txt)

Thanks in advance, 
Berni

**Comment by lh3** [comment]
I am not sure what is happening to github, but these days I often have troubles to download files attached to issues. Could you put the two files elsewhere for me to download? Thanks!

**Comment by brguez** [comment]
Thanks for your quick response! Yes sure, you can download the sequences from these links:

https://drive.google.com/file/d/1cKnV2Mt8Vg5woIwCNDLmKBX9Y8e6jAgS/view?usp=sharing
https://drive.google.com/file/d/1gIwJ2IbfU6v5p6thlZA1UG1nW7wicS5s/view?usp=sharing

**Comment by lh3** [comment]
Your command line currently gives (in the PAF output format):
```
L1_seq  1899    759     1831    +       L1:L1HS 6020    4944    6020    1023    1100    60
L1_seq  1899    13      760     -       L1:L1HS 6020    4179    4931    705     768     60
```
What alignments are you expecting?

**Comment by brguez** [comment]
Hi! I was expecting exactly this, first piece in reverse and second in forward. Ohhh sorry, my mistake.. I got confused interpreting the clipping orientation in the sam. I didn't realise that as the sequence got reversed the cigar is reversed as well. Thanks a lot for your feedback! I close the issue
