### ISSUE TITLE
temporary file location on cluster

### ISSUE THREAD

**Issue by dcopetti** [lh3/minimap2#319]
Hello,
I am running minimap2 (for a all-vs-all alignment for miniasm) on a cluster, but the computation gets interrupted because a file (/cluster/home/copettid/.lsbatch/1545907179.81562844.out) gets deleted. This is unfortunately expected, since the cluster management deletes files older than 2 weeks in the home directory (/cluster/home/copettid). I am running minimap2 in a scratch directory where this problem does not exist (so the .paf.gz file is fine), is there a way to point that .out file to a different location (e.g. the same folder where I am running it, with almost no space constraint?)
Thanks,
Dario

**Comment by lh3** [comment]
When you submit, redirect to a file like
```sh
echo 'minimap2 -c ref.fa query.fa | gzip > output.paf.gz' | bsub
```

**Comment by lh3** [comment]
Github master adds a new option `-o` to write the output to a specified file.

**Comment by dcopetti** [comment]
Hi,

Sorry for my lack of details: I am able to redirect the output file of the alignment to the position I want, but I found that the /cluster/home/copettid/.lsbatch/1545907179.81562844.out was a temporary file written by the minimap2 run and that, once it was deleted, the computation stopped. It is this latter file that I would like to be able to control the location of.
Thanks!

**Comment by lh3** [comment]
No. That file is not generated by minimap2.

**Comment by dcopetti** [comment]
OK then, I will find out who made it.
thanks!
