### ISSUE TITLE
Assertion 'fp' failed

### ISSUE THREAD

**Issue by leleory** [lh3/minimap2#320]
Hi Heng,
I am mapping pacbio reads to a merged genome of primary contigs and haplotigs. 
Commandline: minimap2 --secondary=no --split-prefix $splitfile -ax map-pb $refseq $1.fa
Version 2.15-r905. 
For some of the input files minimap2 is failing with the output: 
minimap2: splitidx.c:15: mm_split_init: Assertion `fp' failed.
Any suggestions why this is happening and how can I avoid it?

Full output is below:
[M::mm_idx_gen::92.701*1.57] collected minimizers
[M::mm_idx_gen::111.126*1.73] sorted minimizers
[M::main::111.127*1.73] loaded/built the index for 9876 target sequence(s)
[M::mm_mapopt_update::112.960*1.72] mid_occ = 541
[M::mm_idx_stat] kmer size: 19; skip: 10; is_hpc: 1; #seq: 9876
[M::mm_idx_stat::113.887*1.72] distinct minimizers: 88473480 (19.50% are singletons); average occurrences: 5.811; average spacing: 7.862
minimap2: splitidx.c:15: mm_split_init: Assertion `fp' failed.
Thank you,
Lel

**Comment by lh3** [comment]
This means minimap2 failed to create temporary file(s). What's your `$splitfile`?

**Comment by lh3** [comment]
The github HEAD should output more meaningful error message when minimap2 can't create this temporary file.
