### ISSUE TITLE
Understanding Relationship Between Primary/Secondary Alignments and Primary/Secondary Mappings

### ISSUE THREAD

**Issue by stopalopa** [lh3/minimap2#323]
Hi, 
I’m trying to better understand how minimap2 assigns the primary and secondary alignments and how these relate to the primary and secondary mapping.  

Questions
1)	You can have one primary alignment in the SAM file format. How does minimap determine this primary alignment? Is this based on the highest alignment score? 
2)	Do the secondary alignments reported in Samtools (the 256 flag) represent all alignments from alignments of all primary mappings and up to the **-N** top secondary mappings that did not have the highest alignment score? 
3)	Are there scenarios where the primary mapped chain does not result in the primary alignment? 

Thank you,
Natasha

**Comment by lh3** [comment]
> 1. You can have one primary alignment in the SAM file format. How does minimap determine this primary alignment? Is this based on the highest alignment score?

Yes.

> 2. Do the secondary alignments reported in Samtools (the 256 flag) represent all alignments from alignments of all primary mappings and up to the **-N** top secondary mappings that did not have the highest alignment score?

Yes.

> 3. Are there scenarios where the primary mapped chain does not result in the primary alignment?

This may happen if after base-level alignment, a secondary chain turns out to be better. Base-level alignment may also join or split chains.

**Comment by stopalopa** [comment]
Thank you for your response. I have a few more questions. 

1. If a chain is split, is the chaining score in the s1 tag the original chaining score before the split or the chaining score of the split chains?

2. What determines if a read is unmapped? Is it if the read has no minimizers in common with the reference?

-Natasha

**Comment by stopalopa** [comment]
3. If a chain is split in two, that would mean that there is an additional secondary mapping in the output bam file, correct?

**Comment by lh3** [comment]
> 1. If a chain is split, is the chaining score in the s1 tag the original chaining score before the split or the chaining score of the split chains?

Forgot.

> 2. What determines if a read is unmapped? Is it if the read has no minimizers in common with the reference?

See `-n`, `-m` and `-s`.

> If a chain is split in two, that would mean that there is an additional secondary mapping in the output bam file, correct?

No. You get a supplementary alignment.
