### ISSUE TITLE
How to map ccs reads (fasta or fastq files) to a reference sequence using minimap2?

### ISSUE THREAD

**Issue by xzhang2016** [lh3/minimap2#325]
Hi there,

I have several fasta (or fastq) files containing ccs reads for a gene under different conditions (different samples). I'd like to map these ccs reads to the reference sequence. How to set the parameters of minimap2? 

From the readme.md, I only find this example relating to ccs reads but there's no detail interpretation for such case.
./minimap2 -ax asm20 ref.fa pacbio-ccs.fq.gz > aln.sam    # PacBio CCS genomic reads

I am wondering if this setting is suitable for my case?

Thanks,
Xue

**Comment by lh3** [comment]
If these are iso-seq reads, use the iso-seq option in readme. If these are genomic reads, use the ccs option.

**Comment by xzhang2016** [comment]
I am new to this. What's the difference between iso-seq reads and genomic reads? 

From the email, I only know it's ccs reads for a targeted gene.
"Happy to pass along your SDHB PacBio data! The CCS (highly accurate circular consensus sequences) reads below are what you should use for comparative analysis/variant analysis. "

Thanks,
Xue

**Comment by lh3** [comment]
Iso-seq reads are sequenced from spliced mRNAs, i.e. without introns. They are CCS reads. Genomic CCS reads are sequenced from the genome. You say "ccs reads for a gene". I am not sure if they are genomic or transcriptomic.

**Comment by xzhang2016** [comment]
For transcriptomic CCS reads, the following setting is good, right?
minimap2 -ax splice -uf -C5 ref.fa iso-seq.fq > aln.sam

**Comment by lh3** [comment]
Yes

**Comment by xzhang2016** [comment]
I just got confirmed that it's genomic sequence. So I need to use the following setting, right?
./minimap2 -ax asm20 ref.fa pacbio-ccs.fq.gz > aln.sam    # PacBio CCS genomic reads

Thanks,
Xue

**Comment by xzhang2016** [comment]
Another question: can minimap2 handle .fq.zip file?

**Comment by lh3** [comment]
If genomic, use `-ax asm20`.

> can minimap2 handle .fq.zip file?

No. It works with .gz, but not .zip or .tar.gz.

**Comment by xzhang2016** [comment]
Ok. Thank you!

**Comment by linshengnan2020** [comment]
Hi ,
minimap2 alignment ccs reads to the reference sequence using -x asm20, when run Split an assembly and do a self-self alignment, how to set the minimap2 options, should the change -x asm5 to -x asm20 ?

Thanks
