### ISSUE TITLE
Keep Z bases as Z instead of transforming to N

### ISSUE THREAD

**Issue by avilella** [lh3/minimap2#327]
Would it be possible for minimap2 to Keep Z bases as Z instead of transforming to N?

The nanopore flappie basecaller can call ZG bases in methylated CG (ZpG of methylated CpGs).

If minimap2 / samtools had the ability to preserve the Z bases, we could preserve this information after alignment.

I presume extending the alphabet for DNA modifications is something that may have been discussed in the past, so whichever way works best, I would like to know.

**Comment by jmarshall** [comment]
How to store base modifications in SAM/BAM/CRAM is something that's under discussion at the moment — see samtools/hts-specs#362.

**Comment by lh3** [comment]
> Would it be possible for minimap2 to Keep Z bases as Z instead of transforming to N?

Minimap2 doesn't convert Z to N.

**Comment by ahcm** [comment]
Doesn't it need something like this?

diff --git a/sdust.c b/sdust.c
index 176dcb0..25a3f1b 100644
--- a/sdust.c
+++ b/sdust.c
@@ -27,9 +27,9 @@ unsigned char seq_nt4_table[256] = {
        4, 4, 4, 4,  4, 4, 4, 4,  4, 4, 4, 4,  4, 4, 4, 4,
        4, 4, 4, 4,  4, 4, 4, 4,  4, 4, 4, 4,  4, 4, 4, 4, 
        4, 0, 4, 1,  4, 4, 4, 2,  4, 4, 4, 4,  4, 4, 4, 4, 
-       4, 4, 4, 4,  3, 4, 4, 4,  4, 4, 4, 4,  4, 4, 4, 4, 
+       4, 4, 4, 4,  3, 4, 4, 4,  4, 4, 1, 4,  4, 4, 4, 4, 
        4, 0, 4, 1,  4, 4, 4, 2,  4, 4, 4, 4,  4, 4, 4, 4, 
-       4, 4, 4, 4,  3, 4, 4, 4,  4, 4, 4, 4,  4, 4, 4, 4, 
+       4, 4, 4, 4,  3, 4, 4, 4,  4, 4, 1, 4,  4, 4, 4, 4, 
        4, 4, 4, 4,  4, 4, 4, 4,  4, 4, 4, 4,  4, 4, 4, 4, 
        4, 4, 4, 4,  4, 4, 4, 4,  4, 4, 4, 4,  4, 4, 4, 4, 
        4, 4, 4, 4,  4, 4, 4, 4,  4, 4, 4, 4,  4, 4, 4, 4, 
diff --git a/sketch.c b/sketch.c
index f830693..cc5a8c4 100644
--- a/sketch.c
+++ b/sketch.c
@@ -12,9 +12,9 @@ unsigned char seq_nt4_table[256] = {
        4, 4, 4, 4,  4, 4, 4, 4,  4, 4, 4, 4,  4, 4, 4, 4,
        4, 4, 4, 4,  4, 4, 4, 4,  4, 4, 4, 4,  4, 4, 4, 4,
        4, 0, 4, 1,  4, 4, 4, 2,  4, 4, 4, 4,  4, 4, 4, 4,
-       4, 4, 4, 4,  3, 3, 4, 4,  4, 4, 4, 4,  4, 4, 4, 4,
+       4, 4, 4, 4,  3, 4, 4, 4,  4, 4, 1, 4,  4, 4, 4, 4, 
        4, 0, 4, 1,  4, 4, 4, 2,  4, 4, 4, 4,  4, 4, 4, 4,
-       4, 4, 4, 4,  3, 3, 4, 4,  4, 4, 4, 4,  4, 4, 4, 4,
+       4, 4, 4, 4,  3, 4, 4, 4,  4, 4, 1, 4,  4, 4, 4, 4, 
        4, 4, 4, 4,  4, 4, 4, 4,  4, 4, 4, 4,  4, 4, 4, 4,
        4, 4, 4, 4,  4, 4, 4, 4,  4, 4, 4, 4,  4, 4, 4, 4,
        4, 4, 4, 4,  4, 4, 4, 4,  4, 4, 4, 4,  4, 4, 4, 4,

**Comment by lh3** [comment]
No, that is irrelevant to the request. Also, introducing additional bases requires the coordination of the ecosystem. Minimap2 only plays a small part in this.

I am closing this issue.
