### ISSUE TITLE
Compute #mismatches using NM tag

### ISSUE THREAD

**Issue by LucoLab** [lh3/minimap2#328]
Minimap was launched without --eqx parameter. 
So we tried to compute number of mismatches using formula given in #25 

```
#mismatches =  NM  - #I - #D - #ambiguous_bases
```

Sometimes we have -1 values for #mismatches . 
So maybe there is a bug somewhere we wanted to report.

**Comment by lh3** [comment]
An example?

**Comment by wdecoster** [comment]
Potentially related to https://github.com/lh3/minimap2/issues/302

**Comment by LucoLab** [comment]
For example, these are two sam lines where we the problem occured. 

> ffab5748-0b45-4f04-9e71-1c88bcc829d4	0	MT	3084	60	23M1D148M28S	*	0	0	AATCCAGGTCGGTTTCTATCTACTTCAAATTCCTCCCTGTACGAAAGGACAAGAGAAATAAGGCCTACTTCACAAAGCGCCTTCCCCCGTAAATGATATCATCTCAACTTAGTATTATACCCACACCCACCCAAGAACAGGGTTTGTTAAGATGGCAGAGCCCGGTAATCGTTTATCAACACCATCTTAAATCTTCTAG	*	NM:i:1	ms:i:168	AS:i:168	nn:i:1	ts:A:+	tp:A:P	cm:i:46	s1:i:160	s2:i:70	dv:f:0.0088	cs:Z::23-n:148
> da9f5f47-15e6-41c8-a2ad-10e85f022a5c	0	MT	3073	60	2S34M1D176M	*	0	0	CGCAGACCGGAGTAATCCAGGTCGGTTTCTATCTACTTCAAATTCCTCCCTGTACGAAAGGACAAGAGAAATAAGGCCTACTTCACAAAGCGCCTTCCCCCGTAAATGATATCATCTCAACTTAGTATTATACCCACACCCACCCAAGAACAGGGTTTGTTAAGATGGCAGAGCCCGGTAATCGCATAAAACTTAAAACTTTACAGTCAGAG	*	NM:i:1	ms:i:207	AS:i:207	nn:i:1	ts:A:+	tp:A:P	cm:i:57	s1:i:199	s2:i:90	dv:f:0.0071	cs:Z::34-n:176

**Comment by lh3** [comment]
@LucoLab has deleted the example which is
```
ffab5748-0b45-4f04-9e71-1c88bcc829d4	0	MT	3084	60	23M1D148M28S	*	0	0 AATCCAGGTCGGTTTCTATCTACTTCAAATTCCTCCCTGTACGAAAGGACAAGAGAAATAAGGCCTACTTCACAAAGCGCCTTCCCCCGTAAATGATATCATCTCAACTTAGTATTATACCCACACCCACCCAAGAACAGGGTTTGTTAAGATGGCAGAGCCCGGTAATCGTTTATCAACACCATCTTAAATCTTCTAG	* NM:i:1	ms:i:168	AS:i:168	nn:i:1	ts:A:+	tp:A:P	cm:i:46	s1:i:160	s2:i:70	dv:f:0.0088	cs:Z::23-n:148
da9f5f47-15e6-41c8-a2ad-10e85f022a5c	0	MT	3073	60	2S34M1D176M	*	0	0 CGCAGACCGGAGTAATCCAGGTCGGTTTCTATCTACTTCAAATTCCTCCCTGTACGAAAGGACAAGAGAAATAAGGCCTACTTCACAAAGCGCCTTCCCCCGTAAATGATATCATCTCAACTTAGTATTATACCCACACCCACCCAAGAACAGGGTTTGTTAAGATGGCAGAGCCCGGTAATCGCATAAAACTTAAAACTTTACAGTCAGAG	*	NM:i:1	ms:i:207	AS:i:207	nn:i:1	ts:A:+	tp:A:P	cm:i:57	s1:i:199	s2:i:90	dv:f:0.0071	cs:Z::34-n:176
```
In both cases, the deleted base is the ambiguous base on rCRS (see the `cs` tag). This suggests `#mismatches =  NM  - #I - #D - #ambiguous_bases` is not always correct.
