### ISSUE TITLE
Support for RNA

### ISSUE THREAD

**Issue by jts** [lh3/minimap2#33]
Hi @lh3,

I'd like to add support for direct RNA nanopore reads to minimap2. These reads have Us in their basecalled sequence rather than Ts. I'm happy to provide a PR but wanted to run the proposed solution by you first - is it enough to convert Us to Ts after reading the sequence [here](https://github.com/lh3/minimap2/blob/de2fcc1bf310c1af0361d6f006b243348197cc5b/bseq.c#L76) or would you prefer I do something else?

Jared

**Comment by lh3** [comment]
Implemented via bf2d4f7. For the minimap2 command line, one change to sequence reading is sufficient. However, for API users who don't use bseq.c, we also need to change the char to base table `seq_nt4_table[]` in sketch.c.

**Comment by jts** [comment]
Ah, right. Thanks for the quick implementation!

**Comment by lh3** [comment]
I am closing this for now. Let me if you have issues with this change. Thanks for the info. Didn't know RNA reads use "U".

**Comment by jts** [comment]
No problem, thanks. I didn't have time to test it today but I'll reopen if
I run into any problems.

Jared
