### ISSUE TITLE
Reads with headers starting from @

### ISSUE THREAD

**Issue by fenderglass** [lh3/minimap2#330]
Hi,

More of a question, than an issue. Sometimes read headers in FASTA start from the '@' symbol - I think mostly due to an incorrect FASTQ -> FASTA correction. This leads to SAM parsing issues (e.g https://github.com/fenderglass/Flye/issues/48). It could be resolved (by counting the number of tab-delimited fields in a line for example) - on the other hand SAM specification does not allow read headers to be started from '@'. So formally, minimap2 is producing an incorrect SAM, given those reads as input. 

What do you think should happen in this case? Perhaps, a warning should be issued? Alternatively, the '@' symbol could be cut / substituted..

Best,
Mikhail

**Comment by lh3** [comment]
Do you have an example to reproduce the issue? Minimap2 should parse
```
@foo
CAGTAGCTAGCATC
```
as a FASTA record.

**Comment by fenderglass** [comment]
It's a bit different:

```
>@foo
ACGATCG
```

I also attach a set of E.coli reads as an example.

[ecoli.reads.example.fasta.gz](https://github.com/lh3/minimap2/files/2866648/ecoli.reads.example.fasta.gz)

**Comment by lh3** [comment]
I will close this. The issue occurs very rarely, but properly handling the error will take quite a bit code. Thanks for raising this anyway.
