### ISSUE TITLE
Assertion `kmst.n_blocks == kmst.n_cores' failed

### ISSUE THREAD

**Issue by ethering** [lh3/minimap2#332]
Hi,
I'm having trouble assembling my nanopore reads. I've installed minimap2 successfully and can run the test data. When I try to align my ONT reads, I get the following error:

Command line:
`minimap2 -x ava-ont  reads.fastq reads.fastq | gzip -1 > reads.paf.gz`

Error:

```
[M::mm_idx_gen::241.408*1.47] collected minimizers
[M::mm_idx_gen::290.896*1.70] sorted minimizers
[M::main::290.896*1.70] loaded/built the index for 269380 target sequence(s)
[M::mm_mapopt_update::296.754*1.69] mid_occ = 538
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 269380
[M::mm_idx_stat::301.225*1.68] distinct minimizers: 234601514 (31.75% are singletons); average occurrences: 5.825; average spacing: 2.928
minimap2: map.c:381: mm_map_frag: Assertion `kmst.n_blocks == kmst.n_cores' failed.
```
The source code suggests this is a memory leak. I was initially using `-t` to supply 16 cores, but have tried leaving that out and just providing default 3 cores in slurm submission script. I also thought it might by my data, so I took the first 1000 reads, used bioawk to turn them into fasta and ran it again (directly from the command line), but got the same error.
I've allocated up to 1TB of RAM, but get the same error.
I'm using r914, but I also get this error using r847.
Any suggestions?
Many thanks,
Graham

**Comment by lh3** [comment]
First time see this. Could you give me your reads? Just first 1000 if those can trigger the assertion failure.

**Comment by ethering** [comment]
Hi,
I've forwarded you the first 1000 reads to your git contact email address.
Additionally, I've also tried running with the most recent release that we have installed on our cluster (v2.11) and it (so far) hasn't terminated and is producing output.
Many thanks,
Graham

**Comment by lh3** [comment]
Thanks a lot for the report. This is a bug introduced by a recent change 32ab6ce. I have now fixed the bug on github HEAD. Thanks again.

**Comment by ethering** [comment]
Wonderful! I've installed the latest commit and it's running without errors.
Many thanks for your quick responses.
Graham

**Comment by lh3** [comment]
A bug on github HEAD is bad. Thanks a lot for reporting it in time!
