### ISSUE TITLE
-x STR gets overwritten but does it overwrite ?

### ISSUE THREAD

**Issue by TaylorDennisLee** [lh3/minimap2#333]
In the manual you say that `-x` should always be applied before other options because other options  applied later will overwrite the values set by `-x`. If `-x` is applied later, will it overwrite the user's flags set before it? For instance, will `minimap2 -w 7 -k 10 -t 3 -ax sr` overwrite the user's flags `-w 7 -k 10`?

**Comment by lh3** [comment]
The behavior was changed. The manpage described the old behavior, which is not correct. The current minimap2 always applies -x before other parameters, regardless of the position of -x on the command line. In other words, `minimap2 -w 7 -k 10 -t 3 -ax sr` is equivalent to `minimap2 -x sr -w 7 -k 10 -t 3 -a`.

**Comment by TaylorDennisLee** [comment]
Do you have a version number this change was reflected in? Thank you.

**Comment by lh3** [comment]
I don't remember.

**Comment by TaylorDennisLee** [comment]
@lh3 could you give me your best guess off the top of your head how long ago this happened? Is it in the release notes?

**Comment by TaylorDennisLee** [comment]
I believe this is the commit where it changed:

https://github.com/lh3/minimap2/commit/1554149158c123ac2806e9f2ae25c0c72c5486c1

Thank you!
