### ISSUE TITLE
Is there a problem in my mapping results?

### ISSUE THREAD

**Issue by pomidorku** [lh3/minimap2#335]
Hi,

I have a draft assembly of a bacterial genome (13 contigs). The genome was sequenced with the pacbio platform on May 2018 and assembled with Canu 1.8.

Kraken2 classifies the draft genome contigs as follows:

10 contigs to Moellerella wisconsesis
1 contig to Proteus vulgaris
1 contig to Klebsiella oxytoca
1 contig to Salmonella enterica

I used minimap2 to align the draft genome to several reference sequences from NCBI:

minimap2 -ax asm5 Ref.fasta DraftAssembly.fasta > DraftAssemblyMapped_asm5.sam

*****************************************************************************

The reports from minimap look like this (grouped for clarity):

Group 1. Draft assembly vs. Kraken-classified-taxa:

samtools flagstat MoellerellaWisconsensisReference_Vs_DraftAssemblyMapped_asm5.sam
159 + 0 in total (QC-passed reads + QC-failed reads)
5 + 0 secondary
141 + 0 supplementary
0 + 0 duplicates
157 + 0 mapped (98.74% : N/A)

samtools flagstat ProteusVulgarisReference_VS_DraftAssemblyMapped_asm5.sam			
36 + 0 in total (QC-passed reads + QC-failed reads)			
0 + 0 secondary			
23 + 0 supplementary			
0 + 0 duplicates			
24 + 0 mapped (66.67% : N/A)		

samtools flagstat KlebsiellaOxytocaReference_VS_DraftAssemblyMapped_asm5.sam						
83 + 0 in total (QC-passed reads + QC-failed reads)						
50 + 0 secondary						
20 + 0 supplementary
0 + 0 duplicates						
71 + 0 mapped (85.54% : N/A)

---------------------------------------------------------------------------------------

Group 2. Draft assembly vs. Tentative identity of the bacteria (lab tests), but "not seen" by kraken (I confirmed the presence of Providencia rettgeri it the Kraken2 database)

samtools flagstat ProvidenciaRettgeriReference_Vs_DraftAssemblyMapped_asm5.sam			
79 + 0 in total (QC-passed reads + QC-failed reads)			
13 + 0 secondary			
53 + 0 supplementary			
0 + 0 duplicates			
67 + 0 mapped (84.81% : N/A)		

------------------------------------------------------------------------------------

Group 3. Draft assembly vs. Other tentative identities of the bacteria:

samtools flagstat KurthiaSpReference_VS_DraftAssemblyMapped_asm5.sam			
13 + 0 in total (QC-passed reads + QC-failed reads)			
0 + 0 secondary			
0 + 0 supplementary			
0 + 0 duplicates			
0 + 0 mapped (0.00% : N/A)

samtools flagstat IgnatzschineriaUreiclasticaReference_Vs_DraftAssemblyMapped_asm5.sam			
13 + 0 in total (QC-passed reads + QC-failed reads)			
0 + 0 secondary			
0 + 0 supplementary			
0 + 0 duplicates			
0 + 0 mapped (0.00% : N/A)			

********************************************************************************

For groups 1. and 2.
Observations:
Most of the mapped "reads" are made up of secondary and supplementary alignments
The draft genome maps not only to the taxa identified by Kraken (group 1.), but also to another bacteria (group 2.) 

Questions
If supplementary and secondary alignments have higher scores for groups 1. and 2., do these mappings can be relied upon to assign identities to species present in the draft genome?
Do the mapping results indicate that I have contamination issues with the draft genome assembly?

Please, if you can guide to solve my questions I will be much obliged to you.

Regards,

**Comment by lh3** [comment]
Before anything, don't use asm5 for cross-species alignment.

**Comment by pomidorku** [comment]
Thank you for your suggestion.
__________________________________________________________________
According t the manual:

Full genome/assembly alignment

minimap2 -ax asm5 ref.fa asm.fa > aln.sam       # assembly to assembly/ref alignment

For cross-species full-genome alignment, the scoring system needs to be tuned according to the sequence divergence.
_______________________________________________________________________

If not asm5, what is the option for cross-species alignment?

Regards,

**Comment by lh3** [comment]
You may start with asm20, but the best option really depends on the sequence divergence:

> For cross-species full-genome alignment, the scoring system needs to be tuned according to the sequence divergence.
