### ISSUE TITLE
For computing minimizers, k=15 and w=10 for ONT data, does this window have a stride of 1?

### ISSUE THREAD

**Issue by harisankarsadasivan** [lh3/minimap2#337]
It is clear that for ONT data, to compute minimizer, minimap2 takes 10 adjacent 15-mers. So, does 2 adjacent windows have an overlap of 23bp or is this overlap=0? If so, pls point me to the code portion.

**Comment by lh3** [comment]
The distance between two adjacent k-mers are not fixed. The average distance is below 10. Please have a look at the miniasm paper or the original minimizer paper for details.
