### ISSUE TITLE
mapping on nanopore data Error: killed

### ISSUE THREAD

**Issue by shashibioinfo** [lh3/minimap2#338]
we have Nanopore metagenome data from MinION platforms which was mapped to Nucleotide sequence database(nt.gz) using minimap2 tool on 15GB RAM and after few minutes the process stops with error message "**Killed**". even after trying multiple times. 

minimap2 -ax map-ont nt.fa /home/ubuntu/Leucine_rawdata/barcode3_5.fastq > barcode3_5_aligned.sam  

If you can please help us to resolve this issue.

Thank you

**Comment by lh3** [comment]
15GB is not enough. Better find a machine with more RAM. You can reduce `-I` to `-I2g`, but on nt, it will be slow.
