### ISSUE TITLE
Mappy produces multiple primary alignments for a read

### ISSUE THREAD

**Issue by llevar** [lh3/minimap2#339]
```
import mappy as mp

#Generated using GRCh37d5 reference with default settings
reference = mp.Aligner('genome.mmi, preset='sr')

#This is read 'HISEQ1:9:H8962ADXX:1:2212:2769:69495/2' from GIAB NA12878 30x downsample
my_read = 'CTCTCTGTACCTTTCCCTGTTCCCTTTGCGTTCTTGCTTCTTCTTTTTTTTTTTTTTTTTTCTTTGGGCGATCGTTTTTAGTTCTGGTCACGTTGTTGAGGTAAGGCGCTAATGGCCGGCGCGGGAGGACAGCAGCGCAGAAAACCAG'

for hit in reference.map(my_read):
	print(f"Hit - {hit}, Read Number - {hit.read_num}, Is Primary - {hit.is_primary}")

```
Output:

```
Hit - 121	148	-	14	107349540	104135139	104135166	25	27	0	tp:A:P	ts:A:.	cg:Z:27M, Read Number - 1, Is Primary - True
Hit - 121	148	-	15	102531392	52347737	52347764	25	27	0	tp:A:S	ts:A:.	cg:Z:27M, Read Number - 1, Is Primary - False
Hit - 34	148	-	16	90354753	68998494	68998608	88	114	2	tp:A:P	ts:A:.	cg:Z:114M, Read Number - 1, Is Primary - True
Hit - 36	148	-	2	243199373	32854526	32854638	86	112	0	tp:A:S	ts:A:.	cg:Z:112M, Read Number - 1, Is Primary - False
```

I was not expecting to see two primary alignments for this read.

FYI, the other read in this pair:
'HISEQ1:9:H8962ADXX:1:2212:2769:69495/1' 
'CAAAAATTAGCTGGGCACAGTGGCAGGAGACTGTAATCCCAGCTACTCGGGGGGTTGAGGCCAGAGGAATACTTGAACCCCCGTAGCAGACATTGCATGGAGCCGAGATTGTGCCACCGGCCTCCAGCCTAGGCGACAGAGAGAGAGT'

is unmapped.

Thanks.

**Comment by lh3** [comment]
What's the command line you used to produce `genome.mmi`? I couldn't reproduce the issue. Thanks.

**Comment by ksahlin** [comment]
Could this happen when splitting the mmi index in chunks (using `-I` parameter)?

I'm not using mappy but minimap2 as standalone from terminal.  I'm also seeing reads with multiple "best mappings" (samflag 0). I'm wondering whether this is because I built the mmi index of hg38 using -I 1Gb so that it has a best mapping in each of the indexes?
