### ISSUE TITLE
Best practice for aligning ONT RNASeq reads (cDNA/directRNA) to Reference Transcriptome

### ISSUE THREAD

**Issue by SaberHQ** [lh3/minimap2#340]
Dear Heng,

Would you please comment on the best practice for aligning **ONT RNA-Seq** reads to **reference transcriptome**? Is there any need for -splice option or not? Are there any differences when dealing with cDNA and directRNA reads? (when aligning to ref transcriptome)

Thanks for the great work.

**Comment by lh3** [comment]
Sorry. I don't have good suggestions. You may try `-x map-ont` and see if that is good enough.

**Comment by SaberHQ** [comment]
Thanks for the quick reply. I will stick with that for now and evaluate the results. One more question though, should we use `-uf -k14` options for directRNA when aligning to reference transcript as we do when alingning to reference genome?

**Comment by lh3** [comment]
Don't use `-uf`. You may choose a smaller `-k` for higher sensitivity.

**Comment by lh3** [comment]
Another issue #346 reminds me of option `-N`. This controls how many hits to reports. Because cDNA sequences have lots of redundancies, you probably want to use a large `-N` like 50 or more.

**Comment by skchronicles** [comment]
Hello @lh3,

I am just wondering if you still recommend this set of options for aligning ONT direct RNA-sequencing data against the transcriptome.

Thank you for this awesome tool, and thank you for the help!

Best Regards,
@skchronicles
