### ISSUE TITLE
Mapping concatenated cDNAs

### ISSUE THREAD

**Issue by FlorianBrnrd** [lh3/minimap2#343]
Hi,
Assuming I have reads that originate from cDNAs ligated together before the sequencing experiment. 
- Would minimap2 split those reads into different reads (respective to the original cDNAs) or should I use a specific parameters ?
- If it does, is there a way to detect those reads that were splitted ?
Thanks in advance.

**Comment by lh3** [comment]
> Would minimap2 split those reads into different reads (respective to the original cDNAs)

Yes

> * If it does, is there a way to detect those reads that were splitted?

Minimap2 effectively does local alignment. You just look at individual hits. I think you will prefer the PAF output (option `-c`) over SAM (option `-a`).
