### ISSUE TITLE
Enabling splice option

### ISSUE THREAD

**Issue by Mach-2** [lh3/minimap2#344]
When I try to run minimap2 in splice mode using --splice, I get ```[ERROR] unknown option in "--splice" ```.

If I write -splice instead of --splice, it seems to run, but I'm a bit concerned as that's not how splice mode is specified in the manual. 

Does --splice have to be followed by other options? Is it supposed to be -splice instead of --splice? Thank you.

**Comment by lh3** [comment]
This is a bug. Let me know if the github HEAD still has the issue. Thanks for reporting!
