### ISSUE TITLE
PAF records truncated?

### ISSUE THREAD

**Issue by nhansen** [lh3/minimap2#345]
I'm running minimap2 version 2.15-r905 on polished and unpolished contigs produced by wtdbg2. For sequences that are mostly or entirely lower case, minimap2 is writing paf alignment records with only two fields (the readname and the read length). Is this expected behavior? When I attempt to analyze the file with paftools.js, I get an error because the quality field is not an integer.

> minimap2 --paf-no-hit -cx asm20 -r2k -z1000,500 -t 2 hg19.fa myseq.fasta > output.paf

<Attaching an example fasta file that exhibits this behavior>

Thanks!
--Nancy

**Comment by lh3** [comment]
PAF normally doesn't contain unmapped reads. The undocumented option `--paf-no-hit` output these reads in a shorter format. What paftools.js command line are you using?

**Comment by nhansen** [comment]
Ah--I was attempting to do assembly statistics as in the wtdbg2 preprint, but didn't realize I could only use the output with "paftools.js asmstat -q50000 -d.1". Thanks!

--Nancy

**Comment by lh3** [comment]
What is the paftools.js command line that triggers the error? I hope all paftools.js functionality to work with such truncated lines.

**Comment by nhansen** [comment]
I was just running "paftools.js stat" on the resulting paf file, and got the following error:

[nhansen@biowulf consensus_seqs]$ paftools.js stat HG00732.wtdbg_contigs.minimap.asm20r2kz1k500.hg19.paf
/usr/local/apps/minimap2/2.15/misc/paftools.js:999: TypeError: Cannot read property 'length' of undefined
				aqlen = t[9].length;
                ^
TypeError: Cannot read property 'length' of undefined
    at paf_stat (/usr/local/apps/minimap2/2.15/misc/paftools.js:999:17)
    at main (/usr/local/apps/minimap2/2.15/misc/paftools.js:2496:26)
    at /usr/local/apps/minimap2/2.15/misc/paftools.js:2512:1

**Comment by lh3** [comment]
This will be addressed in the next release I am working on. Thanks a lot for the report.

**Comment by lh3** [comment]
The new release doesn't output such truncated lines any more. It instead outputs a line like
```txt
LKHW01002830.1  34387  0     0     *     *     0     0     0     0     0     0     rl:i:33513
```
The `stat` and `asmstat` have been modified to recognize both truncated lines and such a full line, though other paftools.js commands haven't been updated. If you have new problems, please create a new issue or reopen this. Thanks.

**Comment by wenjunchen0423** [comment]
Hi, I also encountered a similar problem, 
my command is:
winnowmap -ax asm20 -t 20 -H –MD $ref $qurey > out.sam
paftools.js sam2paf -p out.sam > out.paf

The error is:
/home/yangld/yangld_new/00.project/chenwenjun/01.software/minimap2/minimap2/misc/paftools.js:1775: TypeError: Cannot read property 'length' of undefined
		if (t[9] != '*' && t[10] != '*' && t[9].length != t[10].length)
                                         ^
TypeError: Cannot read property 'length' of undefined
    at paf_sam2paf (/home/yangld/yangld_new/00.project/chenwenjun/01.software/minimap2/minimap2/misc/paftools.js:1775:42)
    at main (/home/yangld/yangld_new/00.project/chenwenjun/01.software/minimap2/minimap2/misc/paftools.js:3693:29)
    at /home/yangld/yangld_new/00.project/chenwenjun/01.software/minimap2/minimap2/misc/paftools.js:3722:1

The versions I use are: 2.28-r1221-dirty
