### ISSUE TITLE
problem with installing minimap

### ISSUE THREAD

**Issue by maorkn** [lh3/minimap2#347]
hi,
once I clone the project I type make and get the following:
cc -c -g -Wall -O2 -Wc++-compat  -DHAVE_KALLOC  main.c -o main.o
process_begin: CreateProcess(NULL, cc -c -g -Wall -O2 -Wc++-compat -DHAVE_KALLOC main.c -o main.o, ...) failed.
make (e=2): The system cannot find the file specified.
Makefile:29: recipe for target 'main.o' failed
mingw32-make.exe: *** [main.o] Error 2

any ideas?

**Comment by lh3** [comment]
It seems that you are using Windows, which minimap2 doesn't support. You may use linux subsystem.
