### ISSUE TITLE
Give in known splice sites to MiniMap2 (as in STAR/HISAT2/TopHat2)

### ISSUE THREAD

**Issue by lucventurini** [lh3/minimap2#348]
Dear @lh3 ,
                     we are starting to use MiniMap2 for aligning NanoPore RNA reads against the genome. We are seeing wobbliness on the position of the splice sites, which is reminiscent of what happens with (already more precise) short-read data. In the years, it has been found independently multiple times that providing the aligner with a set of known splice sites and/or performing a two-pass alignment can dramatically increase splice site accuracy. 
Do you think it would be feasible to introduce an option to pass known splice sites to MiniMap2? 
Kind regards

**Comment by lh3** [comment]
See also #197. I will consider, but probably not very soon.

**Comment by lh3** [comment]
This has been implemented on the github HEAD. Please see my last comment in #197 for usage. The new functionality seems to work, but probably needs more testing.

I am closing this issue. If you see bugs, please create a new one. Thanks!

**Comment by lucventurini** [comment]
Thank you for this! We will test it as soon as possible.

Thanks

Luca
