### ISSUE TITLE
Still issues with multi-maps despite using "--secondary=no"

### ISSUE THREAD

**Issue by GenomeRIK** [lh3/minimap2#351]
Hello,

I am still getting multiple mapping loci when running minimap2 (2.15-r915-dirty) with the "--secondary=no" parameter. This is what my command looks like:
${minimap2} --secondary=no -ax splice -uf -C5 -t 8 ${ref} ${query} > ${outfile}

Is there a way to force only one mapping loci per sequence?

Thank you,
Richard

**Comment by lh3** [comment]
Please read the SAM spec. You are probably seeing supplementary/chimeric alignments, which are different from secondary alignments.
