### ISSUE TITLE
Too many S and H in CIGAR sequencing?

### ISSUE THREAD

**Issue by luckylyw** [lh3/minimap2#352]
Dear @lh3 ,
We are evaluating the error-correction results of third-generation RNA reads. In the alignment results (RNA), there are too many S and H at the beginning or end of the CIGAR string. This phenomenon is not found in DNA alignment result.

Is the parameter I set wrong? Or is it a certain property of RNA that makes the CIGAR sequence like this?Can cDNA sequences skip the intron region and align to the exon regions?

`minimap2 -ax splice -t 20 --eqx -uf -C5 ref.fa iso-seq.fq > aln.sam`
result of cDNA PacBio to reference genome: 2685S25=1D23=1D38=1I28=1X169=1X298=1D200=1D97=1X6=1X583=1D304=1D197=1X293=1X187=1X60=1D183=1D15=1D34=53S
SRR7533628.3	2048	NC_000913.3	2247567	60 1168H10=1D163=1D290=1D32=1I21=1D81=1I20=1D32=1I274=1D67=59H	*	0	0

In addition, when we align cDNA to genome reference, does the N in CIGAR sequence also represent intron?

Kind regards

**Comment by lh3** [comment]
What are the input data? Are these E. coli cDNA?

**Comment by luckylyw** [comment]
Yes, I aligned E.coli cDNA (SRR7533628, SRR7533629) to reference NC_000913.3.

**Comment by lh3** [comment]
> does the N in CIGAR sequence also represent intron?

I don't think you will see `N` in E. coli.

There could be multiple reasons why you see clipping: chimera in reads, "structural variations" between strains and mapping errors. For raw pacbio reads, I think the first is more common.
