### ISSUE TITLE
self alignment of assembly containing N* segments

### ISSUE THREAD

**Issue by brunocontrerasmoreira** [lh3/minimap2#354]
This is related https://github.com/lh3/minimap2/issues/194. After cloning and compiling version 2.16-r922 I ran:

minimap2/minimap2 -cx asm5 GCA_000263155.2_chr6.fna GCA_000263155.2_chr6.fna > chr6self.paf

I was expecting an end-to-end alignment but I get instead a long list of aligned fragments. I also tried -cx asm20 with same results. Might this be because this assembled chromosome has a few N* segments, likely joining scaffolds? Is there a way around this to get an end-to-end alignment in this case?

**Comment by lh3** [comment]
What do the first few alignments look like? Could you paste the results? Thanks.

**Comment by brunocontrerasmoreira** [comment]
Hi, the sequence is 36,014,550b long. Here's the first two:

ENA|CM003533|CM003533.1	36014550	14684815	16326992	+	ENA|CM003533|CM003533.1	36014550	14684815	163269921641066	1641066	60	NM:i:1111	ms:i:1639955	AS:i:1639955	nn:i:1111	tp:A:P	cm:i:281640	s1:i:1581485	s2:i:10457	d
e:f:0	zd:i:2	rl:i:1372801	cg:Z:1642177M
ENA|CM003533|CM003533.1	36014550	12587683	13569573	+	ENA|CM003533|CM003533.1	36014550	12587683	13569573981207	981207	60	NM:i:683	ms:i:980524	AS:i:980524	nn:i:683	tp:A:P	cm:i:163004	s1:i:915312	s2:i:10457	d
e:f:0	zd:i:3	rl:i:1372801	cg:Z:981890M
E

**Comment by lh3** [comment]
These two lines are on the diagonal. They don't have the issue you were talking about.

I guess the assembly is highly fragmented. Minimap2 won't align through long assembly gaps.

**Comment by lh3** [comment]
You may try `--score-N=0`. Not sure if that works.

**Comment by brunocontrerasmoreira** [comment]
It does make the alignment longer, but not end to end yet, thanks for your help

**Comment by lh3** [comment]
Minimap2 won't align assembly gaps at the ends.
