### ISSUE TITLE
minimap2-2.15/paftools.js asmgene <ref-splice.paf> <asm-splice.paf>

### ISSUE THREAD

**Issue by sbilobram** [lh3/minimap2#355]
Trying out asmgene to find alignment identitys vs BUSCO scores.  But cannot find documnetation as to what the inputs should be.  I have a reads-to-ref.paf file as generated from
minimap2-2.15/minimap2 -c -t 64 ref.fa fasta.fa | sort -k6,6 -k8,8n > reads-to-ref.paf
and i am trying/waiting on 
k8 paftools.js asmgene ref.fa reads-to-ref.paf 

So otherwise is that correct or do I need  <ref-splice.paf> <asm-splice.paf> instaed and what are they??

**Comment by lh3** [comment]
Something like this:

```sh
minimap2 -cxsplice -C5 ref.fa cdna.fa > reads-to-ref.paf
minimap2 -cxsplice -C5 asm.fa cdna.fa > reads-to-asm.paf
paftools.js asmgene reads-to-ref.paf reads-to-asm.paf
```

`cdna.fa` contains all annotated cDNA sequences.

**Comment by sbilobram** [comment]
I am not familiar with cDNA librarys and definately do not know how to create one with the info I have.

I have an assembly and a ref. 
Is this documented somewhere?

**Comment by lh3** [comment]
`cdna.fa` refers to annotated gene sequences. You can create it from gff or download [from Ensembl](http://ftp.ensembl.org/pub/release-95/fasta/), if the species has been annotated by ensembl.

**Comment by sbilobram** [comment]
Thanks Ih3

Your suggestion worked for me and I have some output but also more questions:
1. For the command we have -C5 as a parameter and value.  I cannot find what -C is for?
I think the asmgene scores coincide with my previous BUSCO scores to within 0.1% but unsure still.  My Output looks like this:

H	Metric	reads-to-ref	reads-to-asm
X	full_sgl	36437	16056
X	full_dup	0	20
X	frag	0	11118
X	part50+	0	6064
X	part10+	0	1967
X	part10-	0	1212

Can you help to explain this, Please??

**Comment by lh3** [comment]
On -C, see [minimap2 manpage](https://lh3.github.io/minimap2/minimap2.html).

**Comment by sbilobram** [comment]
Thanks got it...
-C INT | Cost for a non-canonical GT-AG splicing (effective with --splice)
AND 

splice | Long-read spliced alignment [.... ]In the splice mode, 1) long deletions are taken as introns and represented as the ‘N’ CIGAR operator; 2) long insertions are disabled; 3) deletion and insertion gap costs are different....

Will try a parameter sweep for values of C to see effect...as I don't know what the 'cost' refers to.
More Important I cannot find documentation explaining output of asmgene

**Comment by lh3** [comment]
There are 36437 genes single copy in the reference genome. 16056 of them (44%) are mapped as intact single-copy gene in the assembly. 20 are duplicated. 11118 (31%) are mapped fully, but fragmented into pieces. 6064 genes are mapped over 50% of their gene lengths. 1967 over 10% and 1212 are below 10% or unmapped.

Basically, your assembly is highly fragmented. Over half of genes are missing.
