### ISSUE TITLE
mappy.Aligner not reporting soft-clipping in CIGAR

### ISSUE THREAD

**Issue by kyrubas** [lh3/minimap2#356]
I'm currently using mappy to align a shorter query sequence to my reference sequence. I'm using the follow:
```
x = mappy.Aligner(seq=SHORTQUERYSEQ, preset="map-ont", best_n=8)
y = x.map(LONGREFSEQ)
```
When I look at `y.q_st` it doesn't start a index 0, but when I look at `y.cigar_str` the first thing I see is some number of matches rather than what I thought I would see, which is some number of softclipped bases.

Is this the correct behavior? If so, is there an option that I'm missing that I should be using to get the number of soft-clipped bases?
Thanks

**Comment by lh3** [comment]
Mappy never produce clippings.

**Comment by btrspg** [comment]
hi @lh3,

I've gotten the same issue. There are missing soft-clips in the cigar from the mappy results.  As in this situation, I may not know the exact mapping location of my read, and if I wrote the results to a bam file, it will also report the lengths are inconsistent in sequence and cigar. 

Here is the example, one is from the minimap2 command line and the other one is coming from mappy.

```
minimap2 cml: 8S30M1I5---40M2S
mappy            :     30M1I5---40M
```

Thanks,

**Comment by silvewheat** [comment]
I also met this problem.
The cigar reported by mappy not contain soft or hard clip.
