### ISSUE TITLE
blasr format

### ISSUE THREAD

**Issue by francicco** [lh3/minimap2#357]
Hi,

I would like to substitute blasr to a couple of pipeline, such as SSpace and PBJelly, the problem is trying to convert any of the output format of minimap into the blasr [formats](https://github.com/PacificBiosciences/blasr/wiki/Blasr-Output-Format), mainly -m1 and -m4.

Any idea on ho to do it?
Thank
F

**Comment by lh3** [comment]
You will have to write a script to convert format, which is a very common task.

**Comment by francicco** [comment]
I tried, but there are some fields which I don't know how to calculate, such as the score, nCelles and others. : /

I guess I'll use other alternatives.
Thanks
F

**Comment by lh3** [comment]
Then this is more of a blasr question...

**Comment by francicco** [comment]
I tried.

**Comment by matryoskina** [comment]
> I tried.

Hi @francicco , did you find a solution? I would like to do the same to use the output of minimap2 for SSPACE
