### ISSUE TITLE
incomplete multi-part index 

### ISSUE THREAD

**Issue by LipengKang** [lh3/minimap2#358]
Dear @lh3 ,I used minimap2 to align PacBio reads to wheat reference genome(~15G). I manually split each wheat chromosomes into 2 pieces (for bwa), so I split 21 chromosomes to 42 chromosomes.
But when I used minimap, the output said index 12 target sequences? why? Here are my split table and output header.
ChrID	StartIndex(inclusive)	EndIndex(exclusive)	OriChrName	StartIndexOnOriChr(inclusive)	EndIndexOnOriChr(exclusive)
1	0	471304005	chr1A	0	471304005
2	0	122798051	chr1A	471304005	594102056
3	0	438720154	chr1B	0	438720154
4	0	251131716	chr1B	438720154	689851870
5	0	452179604	chr1D	0	452179604
6	0	43273582	chr1D	452179604	495453186
7	0	462376173	chr2A	0	462376173
8	0	318422384	chr2A	462376173	780798557
9	0	453218924	chr2B	0	453218924
10	0	348037791	chr2B	453218924	801256715
11	0	462216879	chr2D	0	462216879
12	0	189635730	chr2D	462216879	651852609
13	0	454103970	chr3A	0	454103970
14	0	296739669	chr3A	454103970	750843639
15	0	448155269	chr3B	0	448155269
.............

**[M::mm_idx_gen::144.271*1.74] collected minimizers
[M::mm_idx_gen::173.547*1.90] sorted minimizers
[WARNING] For a multi-part index, no @SQ lines will be outputted. Please use --split-prefix.
[M::main::173.547*1.90] loaded/built the index for 12 target sequence(s)
[M::mm_mapopt_update::177.879*1.88] mid_occ = 1689
[M::mm_idx_stat] kmer size: 19; skip: 10; is_hpc: 1; #seq: 12
[M::mm_idx_stat::180.478*1.87] distinct minimizers: 97619927 (51.03% are singletons); average occurrences: 5.663; average spacing: 7.786**

**Comment by lh3** [comment]
Minimap2 is mapping part of your ref. If you have enough RAM, use a large `-I16g`. If you don't, run minimap2 with
```sh
minimap2 ... --split-prefix=pre ref.fa query.fa
```
