### ISSUE TITLE
minimap2 for aDNA short reads?

### ISSUE THREAD

**Issue by hsiehph** [lh3/minimap2#363]
Hi minimap2 experts,

I wonder if it makes any sense to use minimap2 for aDNA short read mapping. For a long time, people have been using bwa for aDNA mapping, with the following parameters -l 16500 -n 0.01 and -o 2, to deactivate seeding, allow more substitutions and up to 2 gaps. Given the performance of minimap2, is there any suggestion on advantage/disadvantage using it over bwa for aDNA?

Thanks!

**Comment by lh3** [comment]
Minimap2 won't work well for reads shorter than 100bp. Bwa-aln is still the best for that.
