### ISSUE TITLE
-p filter not working for short queries

### ISSUE THREAD

**Issue by thackl** [lh3/minimap2#364]
With `-p1` I would expect to only get secondary alignments if their score is equal to that of the primary alignment. However, this does not seem to work with short queries:

```sh
# -p .5   expected behaviour
minimap2 -c -p.5 -m30 B.fa.gz A.fa.gz | cut -f1,2,6,15,17-20 | tsv-pretty
A1   74  B1  AS:i:148  tp:A:P  cm:i:8   s1:i:66   s2:i:36
A1   74  B2  AS:i:92   tp:A:S  cm:i:4   s1:i:36   de:f:0
A3  200  B3  AS:i:400  tp:A:P  cm:i:33  s1:i:186  s2:i:127
A3  200  B4  AS:i:282  tp:A:S  cm:i:22  s1:i:127  de:f:0


# -p 1   unexpected behaviour
minimap2 -c -p1 -m30 B.fa.gz A.fa.gz | cut -f1,2,6,15,17-20 | tsv-pretty
A1   74  B1  AS:i:148  tp:A:P  cm:i:8   s1:i:66   s2:i:36
A1   74  B2  AS:i:92   tp:A:S  cm:i:4   s1:i:36   de:f:0 # << UNEXPECTED
A3  200  B3  AS:i:400  tp:A:P  cm:i:33  s1:i:186  s2:i:127
```

[A.fa.gz](https://github.com/lh3/minimap2/files/2974035/A.fa.gz)
[B.fa.gz](https://github.com/lh3/minimap2/files/2974036/B.fa.gz)

Any idea why this happens?

**Comment by lh3** [comment]
`-p` fine tunes the mapping algorithm. It interplays with other heuristics. It should not be thought as a way to control the output.
