### ISSUE TITLE
ERROR: failed to open file

### ISSUE THREAD

**Issue by ysf39039** [lh3/minimap2#367]
I am getting the following error using minimap2 for iso-seq alignment 

[M::mm_idx_gen::98.765*1.78] collected minimizers
[M::mm_idx_gen::117.929*3.42] sorted minimizers
[M::main::117.929*3.42] loaded/built the index for 66 target sequence(s)
[M::mm_mapopt_update::121.668*3.34] mid_occ = 650
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 66
[M::mm_idx_stat::124.169*3.30] distinct minimizers: 163912986 (36.46% are singletons); average occurrences: 5.535; average spacing: 3.010
ERROR: failed to open file '/sc/orga/projects/sumo/IsoSeq-20190313/Iso_minimap2/fasta/PBG-1963.TD_00552_WT_Isoseq3_nopolyA.IsoSeq3.004998.hq_transcripts.fasta'
[M::main] Version: 2.12-r827
[M::main] CMD: minimap2 -t 24 -ax splice -uf --secondary=no -C5 /sc/orga/projects/sumo/IsoSeq-20190313/Iso_minimap2/fasta/mini_index_genome/GRCm38.primary_assembly.genome.fa /sc/orga/projects/sumo/IsoSeq-20190313/Iso_minimap2/fasta/PBG-1963.TD_00552_WT_Isoseq3_nopolyA.IsoSeq3.004998.hq_transcripts.fasta
[M::main] Real time: 124.439 sec; CPU: 409.644 sec
PBG-1963.TD_00552_WT_CL_39_TAM_mESC_Rep_1_Isoseq3_nopolyA.IsoSeq3.004998.hq_transcripts.sam.log (END) 

Any suggestions on a fix?

**Comment by lh3** [comment]
Please check file permission.
