### ISSUE TITLE
Parameters to determine splitted reads

### ISSUE THREAD

**Issue by StanislasF** [lh3/minimap2#369]
Hi,

I'm sorry for the basics question but :
I'm using Minimap2 and I'm interesting for split reads. How Minimap2 determine when a read is split ? Can we modify this parameters ?  How ? It is related to the -z option ? How ? (I'm not use to DP)

Thank you in advance

**Comment by lh3** [comment]
Without base-level DP, read splitting is determined by chaining. If you want to tune the chaining behavior, you may have a look at -g and -r. -z is only effective with base-level DP.
