### ISSUE TITLE
No SQ lines

### ISSUE THREAD

**Issue by ahcm** [lh3/minimap2#37]
14b85349 (Heng Li 2017-09-14 22:44:10 -0400 258)        while ((mi = mm_idx_reader_read(idx_rdr, n_threads)) != 0) {
7d50e646 (Heng Li 2017-10-04 17:32:58 -0400 259)                if ((opt.flag & MM_F_OUT_SAM) && idx_rdr->n_parts == 1) {
7d50e646 (Heng Li 2017-10-04 17:32:58 -0400 260)                        if (mm_idx_reader_eof(idx_rdr)) {
7d50e646 (Heng Li 2017-10-04 17:32:58 -0400 261)                                mm_write_sam_hdr(mi, rg, MM_VERSION, argc, argv);
7d50e646 (Heng Li 2017-10-04 17:32:58 -0400 262)                        } else {
7d50e646 (Heng Li 2017-10-04 17:32:58 -0400 263)                                mm_write_sam_hdr(0, rg, MM_VERSION, argc, argv);
7d50e646 (Heng Li 2017-10-04 17:32:58 -0400 264)                                if (mm_verbose >= 2)
f4a5d3a6 (Heng Li 2017-10-05 15:03:03 -0400 265)                                        fprintf(stderr, "[WARNING]\033[1;31m For a multi-part index, no @
7d50e646 (Heng Li 2017-10-04 17:32:58 -0400 266)                        }
7d50e646 (Heng Li 2017-10-04 17:32:58 -0400 267)                }

This suppresses all SQ lines for mappings against references with more than one sequence, right?
Samtools can't work with the output. How is that supposed to be used? 

Thanks
Andy

**Comment by lh3** [comment]
> This suppresses all SQ lines for mappings against references with more than one sequence, right?

No. This suppresses all SQ lines if the index is too large to be hold in RAM (e.g. nt). This is called a multi-part index.

> Samtools can't work with the output.

Samtools *always* works with SAM without SQ lines. Use option -t or -T on SAM->BAM conversion. You can also easily create a SAM stream like:
```sh
(cat my-sq-lines; cat minimap2.sam) | blabla
```

**Comment by ahcm** [comment]
This was with Mus_musculus.GRCm38.dna.toplevel.fa on a 1TB RAM machine.
Works fine changing the part of the code.

**Comment by lh3** [comment]
Which part of the code were you changing? What was the exact command line?

**Comment by ahcm** [comment]
@PG     ID:minimap2     PN:minimap2     VN:2.2-r511-dirty       CL:minimap2 -x splice -a -t 8 -N 0 /data/blum-hn02/user/andy/ref/Mus_Musculus/Mus_musculus.GRCm38.dna.toplevel.fa 20170921_0719_cDNA_mESC_TetKO-pass-albacore-2.0.2.porechop.wo_polyAT.fastq

@@ -260,7 +260,7 @@ int main(int argc, char *argv[])
                        if (mm_idx_reader_eof(idx_rdr)) {
                                mm_write_sam_hdr(mi, rg, MM_VERSION, argc, argv);
                        } else {
-                               mm_write_sam_hdr(0, rg, MM_VERSION, argc, argv);
+                               mm_write_sam_hdr(mi, rg, MM_VERSION, argc, argv);
                                if (mm_verbose >= 2)
                                        fprintf(stderr, "[WARNING]\033[1;31m For a multi-part index, no @SQ lines will be outputted.\033[0m\n");
                        }

**Comment by lh3** [comment]
Minimap2 is properly behaving. The root of the problem is you are using a wrong reference genome. The "toplevel" mouse genome is ~8GB in size. It is so large because it includes alternate haplotypes with sequences identical to the primary assembly hard masked as "N". For this 8GB genome, minimap2 will create a multi-part index. With your change, you will see SQ lines inside the alignment section. Samtools will report an error.

You should use "primary_assembly" instead. "Top_level" assembly is worse for almost everything. If I were Ensembl, I wouldn't put this confusing file on FTP.

**Comment by lh3** [comment]
Thanks for reporting anyway. I haven't looked at mouse top-level FASTA before, and didn't know it is that bad.

**Comment by lh3** [comment]
By the way, it is not recommended to use "-N 0". This will reduce the alignment accuracy. The new version at github will throw a wanring:
```
[WARNING] `-N 0' reduces alignment accuracy. Please use --print-2nd=no to suppress secondary alignments.
```
if you use it.

**Comment by lh3** [comment]
Use `--split-prefix=foo`.

**Comment by jianshu93** [comment]
After using --split-prefix=foo for a big reference file (13G), sam file (~16G)is much smaller than without --split-prefix=foo (~60G)
