### ISSUE TITLE
Multi-mapping handling of Minimap2

### ISSUE THREAD

**Issue by tetedange13** [lh3/minimap2#370]
Hi,
<br>
**First, thanks for developing Minimap2, it is a great tool.**
Then, I don't really have any issues, but rather some questions about **how Minimap2 is dealing with multimapping** (_i.e._ "secondary alignments").
My scientific context is a **long-reads (ONT 16S amplicons) mapping against different databases** (SILVA for eg.), **to identify their taxonomy** (which is known as I am working with a mock community).

Looking closely at the default parameters of Minimap2 (`-x map-ont`), I saw:
* that secondary alignments are outputted (`--secondary=yes`) ;
* with at most 5 of them (`-N5`) ;
* and only secondaries with ratio=primary_score/secondary_score > 0.8 can be outputted (`-p0.8`)

So my first question is the following: **Can we safely considerer this 5 secondaries alignments equivalent to the primary one** (as it should be the case in a multimapping situation), **when they are selected based on a ratio of scores ?**

Then my second question: **Is it possible, by setting the 'p' parameter to 1, to be sure that all secondary alignments outputted are equivalent to the primary one ?** If yes, how can I choose wisely the value of the '-N' parameter, in order to be sure to capture all equivalent alignments for a given read ?

Indeed, my problem is that, **most of the time I have coherent taxonomies among all secondary alignments of a given read**, but for some reads (about 20%), almost all secondaries have coherent taxonomy between each others, **except for a couple of secondaries, mapping on a completely different (unexpected) species**.
<br>
Thanks in advance for you answer.
Best regards.
Felix.

**Comment by lh3** [comment]
> Can we safely considerer this 5 secondaries alignments equivalent to the primary one (as it should be the case in a multimapping situation), when they are selected based on a ratio of scores?

What do you mean by "equivalent"? Exact alignment, exact score, similar alignment/score?

> Is it possible, by setting the 'p' parameter to 1, to be sure that all secondary alignments outputted are equivalent to the primary one? 

No. The right way is to check the mapping score at the `AS` tag.
