### ISSUE TITLE
Unexpected sequence mapping output?

### ISSUE THREAD

**Issue by CrMallard** [lh3/minimap2#371]
I'm working with a data set of 685,954 ONT MinION reads and mapping it to a database of sequences using : 
` ~/minimap2/minimap2 --secondary=no -a ~/DBs/v15.1/clustered/clustered_db.fasta G2_30.fastq > G2_30.sam
`
However, the resulting output consists of 744266 primary and 82380 supplementary alignments. From what I've read in the SAM file spec and minimap2.1 I can't find an exact reason for why there would be more output alignments than there were input reads. Is there something I am missing?

**Comment by lh3** [comment]
Example? Thanks.
