### ISSUE TITLE
non-overlapping alignment

### ISSUE THREAD

**Issue by LipengKang** [lh3/minimap2#374]
Hi, Heng
I am trying to align wtdbg2 contigs to self-reference or interspecific references. I want to one to one hits finding function, like axtChain from lastz, single_cov from TBA or last-split from last aligner. I mean one best alignment is retained in one reference region.
minimap2 -ax asm5 --secondary=no  gives me alignments which seems one to many.  Can any parameters work for it? -Y or --hard-mask-level?

Any advice? 
Thanks,
lipeng

**Comment by lh3** [comment]
Duplicate of #271. Unfortunately, minimap2 doesn't have this feature. I will think about that, but probably that won't happen soon.

**Comment by LipengKang** [comment]
Thank you, Heng.
