### ISSUE TITLE
How many threads does mappy.Aligner.map use? 

### ISSUE THREAD

**Issue by DrQuestion** [lh3/minimap2#375]
Hi Doctor Li,
Since I'm using mappy, I would like to know if Aligner.map() supports multi-threading, and if it does how many threads it uses by default and if we have control on their number. 
I read in minimap2 documentation that usually alignment uses the number of threads given to indexing process + 1. Is it so also for mappy?
Thank you a lot in advance for your help,
Alessio

**Comment by lh3** [comment]
mappy uses one thread only. You need to manage multi-threading in python by yourself. Extra care needs to be paid in that case, though.

**Comment by DrQuestion** [comment]
Thank you for your fast answer!
But now, given what you've said, may I ask what is the use of the parameter n_threads? Is it limited to indexing only?

**Comment by lh3** [comment]
> Is it limited to indexing only?

Yes.

**Comment by DrQuestion** [comment]
Again, thank you a lot!

**Comment by DrQuestion** [comment]
> mappy uses one thread only. You need to manage multi-threading in python by yourself. Extra care needs to be paid in that case, though.

I managed eventually to develop a multi-threaded alignment, even if a little rude. I create in the preceding step the index. By using `multiprocess.dummy` I give to each thread the same index (itertools.repeat(index)) and I map on it a different query file.

Until now everything seems to work well, though missing some testing with already studied datasets, but I've just remembered about your answer quoted above. What did you mean by extra care? Were you thinking about a particular application that could be impaired?

**Comment by lh3** [comment]
> What did you mean by extra care?

Sorry for the late reply. I was not accurate. You only need "extra care" if you want to achieve the best performance. Your script should work without special attention.

If you want to achieve the best multi-threading performance, you need to

```python
# load/build the index before all threads:
a = mp.Aligner("ref.fa")

# then in each thread
buf = new ThreadBuffer()
for seq in seq_array:
  for hit in a.map(seq, buf=buf):
    # blabla
```

This will reduce unnecessary memory allocations and thus make mappy faster.
