### ISSUE TITLE
Segmentation fault (core dumped) when mapping 1500 bp nanopore reads

### ISSUE THREAD

**Issue by ebbebak** [lh3/minimap2#376]
Hi,
I'm trying to map 16S rRNA nanopore reads of about 1500 bp to the SILVA ssu132 database. It works when I only map a small subset of the reads or if I use a very simple database, but the combination of the many reads and the full database leads to a Segmentation fault (core dumped) error. I have had a successfull run with up to 87427 sequences and a reported Peak RSS: 58.899 GB.
I'm running the newest version of minimap2 on Ubuntu 1804.2018.817.0 on WSL.
I suspect that it might be due to memory limitations. When I monitor the memory usage it seems to utilize all of the available memory (64 GB) after a few minutes, but it continues to run for 10-15 min. before failing. 

minimap2 -ax map-ont --secondary=no SILVA_SSU132_Nr99_Minimap2Mod.fasta.gz mock_filt_re.fq > minimap2_alignment.sam
[M::mm_idx_gen::22.837*1.73] collected minimizers
[M::mm_idx_gen::27.258*1.93] sorted minimizers
[M::main::27.563*1.92] loaded/built the index for 695171 target sequence(s)
[M::mm_mapopt_update::27.732*1.92] mid_occ = 16535
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 695171
[M::mm_idx_stat::27.831*1.91] distinct minimizers: 7165551 (60.20% are singletons); average occurrences: 25.429; average spacing: 5.537
Segmentation fault (core dumped)

**Comment by lh3** [comment]
This is probably because you don't have enough memory. You may try to reduce "-K" to a smaller number.

**Comment by ebbebak** [comment]
Hi Heng Li,
Thank you very much for the fast reply. 
When I reduce -K to 80M it levels out at about 95% memory usage and runs fine.

**Comment by mahmad37** [comment]
I am having the same issue. I am using all the available memory 512GB.
I tried the following command and got this error:

```
minimap2 -B 15 --MD -ax map-ont ref.fasta all.fastq > allfiles.sam
[M::mm_idx_gen::0.065*0.81] collected minimizers
[M::mm_idx_gen::0.084*1.29] sorted minimizers
[M::main::0.086*1.26] loaded/built the index for 1094 target sequence(s)
[M::mm_mapopt_update::0.087*1.26] mid_occ = 1084
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1094
[M::mm_idx_stat::0.088*1.25] distinct minimizers: 17779 (29.01% are singletons); average occurrences: 12.873; average spacing: 5.226
Segmentation fault (core dumped)
```

Then I tried different values of the -K reducing from 500M to even 1M. It didn't work either.

**Comment by lh3** [comment]
A segfault is always an issue. I will have a look later. That said, there are constraints in SW scoring. When mismatch penalty is too large, there will be no mismatches. It will also affect other heuristics. Generally, don't change scoring unless you understand the effect.

**Comment by mahmad37** [comment]
Thanks alot.
I am having some alignments that have mismatches. I am trying to get rid of those particular alignments from SAM file. Is there any other way to do it? 
The minimap generally does not produce the XM tag which tells about the number of mismatches in each alignment. I tried to pull out the cigar operators using --eqx, but after this, I am not sure about any command line that I can use to put a threshold on mismatches and discard mismatched alignments according to a certain threshold.

**Comment by lh3** [comment]
> Is there any other way to do it?

Write a program

**Comment by mahmad37** [comment]
That is really helpful, thanks.

**Comment by lh3** [comment]
You may add --eqx and use pysam to parse cigar to get the number of mismatches.
