### ISSUE TITLE
The memory of running the Minimap2 is too large to get the result

### ISSUE THREAD

**Issue by cym0304** [lh3/minimap2#378]
I used the minimap2 to find the overlap of Nanopore data, but the memory of this command is larger and larger. When the memory is 125G, my job was killed. The size of my data which is uncompressed is 58G, and my command is:

/softwarePath/minimap2 -a -x ava-ont -t 8 query.fq.gz query.fq.gz > query.sam

Could you give me some suggestions to reduce the running memory? Thank you.

**Comment by lh3** [comment]
What's the coverage?

**Comment by cym0304** [comment]
Hello, 
I'm sorry that I don't understand what the coverage mean. Could you give me more information? 
And I also try to output a .paf file. But the result file is too large. This output file is 6.1T now but the command is still running. Is this normal?

**Comment by lh3** [comment]
How many times the sample genome is covered by reads?

**Comment by cym0304** [comment]
I don't know the exact coverage of my data. But the species is mouse, and the fastq file which is got by basecalling is 58G, and the reads number is 29014555.

**Comment by lh3** [comment]
A huge PAF is expected for mammalian genomes. If you want to assemble the reads, you should use wtdbg2 or flye these days.
