### ISSUE TITLE
slight discrepancy between Algorithm 1 pseudocode and mm_sketch

### ISSUE THREAD

**Issue by mlin** [lh3/minimap2#379]
Hi @lh3 to exactly match the Algorithm 1 pseudocode in the minimap paper, shouldn't this line compare `hash64(kmer[0])` and `hash64(kmer[1])`?

https://github.com/lh3/minimap2/blob/371bc9513a543951aab114e2cd1cbd89bd5e985e/sketch.c#L109

I convinced myself it doesn't matter, because the k-mer total ordering gets scrambled anyway so it only matters that the choice between a k-mer and its RC is made deterministically. True? But it would be nice to match the pseudocode of course.

Side question, does hash64 remain invertible with the bitwise mask?

**Comment by lh3** [comment]
> shouldn't this line compare hash64(kmer[0]) and hash64(kmer[1])?

They are different, but this doesn't matter. Algorithm 1 is distinct from the actual implementation anyway.

> does hash64 remain invertible with the bitwise mask?

Yes.
