### ISSUE TITLE
--cs=long    not accepted;  cs='long'   not accepted   want cs tag operating for sam output

### ISSUE THREAD

**Issue by cjwoodruff50** [lh3/minimap2#38]
The call:- 
% minimap2 -c --cs=long -a -t8 /home/users/allstaff/gouil.q/genomes/Mus_musculus/GRCm38/CAST_EiJ_full_sequence/CAST_EiJ_full_sequence_SNPs_introduced.mmi albacore2.fastq.fa.gz > /home/users/allstaff/woodruff.c/lab_speed/cjw/genomes/Mus_musculus/GRCm38/CAST_EiJ_full_sequence/CAST_EiJ_full_sequence_SNPs_introduced_cslong.sam

The error message:-
minimap2: unrecognized option: cs=long

**Comment by lh3** [comment]
Version? This is a new feature from master branch only, not present in v2.2 yet. Will appear in v2.3.

**Comment by cjwoodruff50** [comment]
Heng, Thanks for quick response. I am using version 2.2(r409). So for the time being I'll use .paf files data.  Your code is a good step forward - thanks for that.
Chris
