### ISSUE TITLE
minimap2 finds max. 51 occurences of  marker sequence in about 500 genomes

### ISSUE THREAD

**Issue by ms-gx** [lh3/minimap2#380]
I am searching a specific sequence in about 500 bact. genomes which should occur in all of them with very slight variations. That means the genomic region has a similarity of >99.5%.
Length of the region is about 500 bp.

My call is:
`minimap2 -cx asm20 all_genomes.fasta marker_sequence.fasta > result1.minimap2`

Version: 2.16-r922

Is there some specific parameter causing this?

**Comment by lh3** [comment]
Option `-N`, which is set to 50 with `-x asm20`.

**Comment by ms-gx** [comment]
Uhhh... that easy. Thanks a lot!
Although, if I am not mistaken, the manpage does not mention this. Maybe adding this to manpage would be helpful.

Thank you!

**Comment by lh3** [comment]
It is in the manpage, as well as the command-line help.

**Comment by ms-gx** [comment]
What I meant is the fact that `-x asm20` sets `N=50`. Or is this really on the manpage and on the command-line help?

**Comment by tseemann** [comment]
@ms-gx I agree with you, I have filed a separate issue.
