### ISSUE TITLE
A bug in PAF format?

### ISSUE THREAD

**Issue by moold** [lh3/minimap2#382]
Hi,
The [doc.](https://github.com/lh3/miniasm/blob/master/PAF.md) of paf shows Query end and Target end  is 0-based. Query sequence length and Target sequence length should be 1-based? But why many blocks of minimap2 with paf format show aligned end == Query length/Target length, such as:
p4023   *61100*   36420   *61100*   -       tig00001.174.0.p1270    44246   11126   35812   24669   24696   0 ...

should it be aligned end == Query length/Target length - 1?

3ks.

**Comment by lh3** [comment]
That is exactly what 0-based is meaning.

**Comment by muffato** [comment]
I've got the same question. If both coordinates are included, it doesn't matter if they're 0-based or 1-based, the length is end-start+1. I've got this output:
```
HLA:HLA00001	3503	0	3503	+	HLA-A.ref	14625	5994	9496	3461	3503	60	NM:i:42	ms:i:6752	AS:i:6752	nn:i:0	tp:A:P	cm:i:566	s1:i:3192	s2:i:0	de:f:0.0120	rl:i:0	cg:Z:1427M1I2075M
```
and I can only match the coordinates of HLA:HLA00001 by assuming that the end coordinate is excluded and 0-based, which is the same nomenclature as BED files

**Comment by jmarshall** [comment]
Yes, that's why since lh3/miniasm@cdcb49dc8aed7fd823359f2b91ab1cc4539e9794 that documentation says

> Col | Type | Description
> -- | -- | --
> 3 | int | Query start (0-based; BED-like; closed)
> 4 | int | Query end (0-based; BED-like; open)

**Comment by muffato** [comment]
Great, thank you for clarifying this so quickly. That change is not yet in the version I'm using.
