### ISSUE TITLE
Multiple primary alignments per query 

### ISSUE THREAD

**Issue by sarahhp** [lh3/minimap2#384]
Hi, 
Using minimap 2 (version 2.16-r922) I found multiple alignments for the same query that had the primary tag "tp:A:P", in both the .paf and the .sam output. 

e.g. paf output
![image](https://user-images.githubusercontent.com/43327001/56174372-7b51c380-6035-11e9-85dc-8ec600916d36.png)

I was doing a spliced alignment of some custom transcripts to the ensembl human genome with the command: 
`minimap2 -t 8 -x splice -p 0.95 path/primary_assembly.mmi ../SuperDuper.fa > superT_primary.paf`

I'm wondering if this expected behaviour based on the parameters I've set (my bad), or if this is a bug?

**Comment by lh3** [comment]
Expected. Have a look at the SAM spec on supplementary alignments.

**Comment by sarahhp** [comment]
Right! 
So the "tp:A" flag shows primary vs secondary status; secondary alignment being with relation to the same query and same target a.k.a. multimapping?
Whilst supplementary alignments (shown in the sam bitwise FLAG) relate to the same query and different targets a.k.a describing chimeric alignment?  

Thanks for the fast response.

**Comment by TimD1** [comment]
For anyone else that lands here, minimap2 doesn't verify that input FASTQ files have unique sequence identifiers. For an input FASTQ with such an issue, minimap2 will happily map multiple reads with the same identifier, all as primary alignments.
