### ISSUE TITLE
Missing 1 base on each alignment for "perfect" simulated reads

### ISSUE THREAD

**Issue by pb-cdunn** [lh3/minimap2#385]
I detected an off-by-one error in minimap2. Well, it doesn't provide false information, but it fails to align the final base on overlapping reads. This is consistent, and for both A->B and B->A overlaps. However, it doesn't happen for fully contained overlaps.

I have generated a synthetic genome, circular so non-contained reads overlap on both ends. Below I display `>readname [start .. stop] CIGAR`.:
```
>TestMovie/18/0_2000 [759 .. 2759] 2000=
>TestMovie/19/0_2000 [537 .. 2537] 2000=
```

Those are fully contained overlaps. The reference is exactly 5000 bases, and the reads are each 2000 bases, "simulated" with a 0% error rate. Hence, cigar is `2000=`. But look at these alignments, for a single read across both ends of the circular reference: 
```
>TestMovie/21/0_2000 [0 .. 1105] 894S1105=1S
>TestMovie/21/0_2000 [4106 .. 4999] 893=1107S
```
Note that both cigars add up to `2000`. But `1105=` + `893=` is only `1998`. The `1S` above shows the error clearly.

I understand that minimap2 does not produce dovetail overlaps anyway, but that can be blamed on errors in the input data. In this case, the missing base is _always_ correct. And this is totally consistent, always missing 1 base for each non-contained overlap.

I have not pored over the source-code looking for an error, only providing this information. Again, it's not a false alignment, but I think it's worth double-checking the code in case this extra base could be included efficiently.

**Comment by lh3** [comment]
Do you have an example?

**Comment by pb-cdunn** [comment]
https://downloads.pacbcloud.com/public/data/git-sym/synth5k.2016-11-02.tgz

```
ref.fasta synth5k.bam
```

**Comment by lh3** [comment]
I couldn't reproduce the issue. With `-ax map-pb --eqx`, I get
```
TestMovie/21/0_2000 0       synthetic/0/0_5000  1       60  894S1106=
TestMovie/21/0_2000 2048    synthetic/0/0_5000  4107    60  894=1106H
```

**Comment by pb-cdunn** [comment]
I don't remember how I generated that data 19 days ago, but it's working for me now. I wish I had recorded the exact command-line...

Oh, I see now.

    T=/pbi/dept/secondary/siv/testdata/hgap/synth5k  # or .
    pbmm2 align $T/ref.fasta $T/synth5k.bam | samtools view

That is a PacBio wrapper around minimap2. That must be our bug, not yours. Sorry.

**Comment by lh3** [comment]
Thank you very much for reporting this anyway. I appreciate.
