### ISSUE TITLE
position is wrong

### ISSUE THREAD

**Issue by wjyzidane** [lh3/minimap2#389]
I mapped 2 short sequences to one long sequence from nanopore by:
minimap2 short_1.fa long.fa
minimap2 short_2.fa long.fa
but the position in paf files does not match to what I see in snapgene:

Here is the result of minimap:
54411d1a-e7cd-4266-9aa9-aecb955cbd27    660    366    435    -    short_1    74    7    70    58    69    27    tp:A:P    cm:i:6    s1:i:57    s2:i:0    dv:f:0.0341
54411d1a-e7cd-4266-9aa9-aecb955cbd27    660    462    546    -    short_2    104    8    93    78    85    60    tp:A:P    cm:i:11    s1:i:78    s2:i:0    dv:f:0.0161

Here is the result of snapgene:

The actual position should be 363-442 and 453-554. As it is shown in snapgene and according to my design, there is only 10bp between 2 short sequences.

**Comment by wjyzidane** [comment]
<img width="1331" alt="QQ20190426-120208@2x" src="https://user-images.githubusercontent.com/34944811/56823584-4d813180-6822-11e9-8f78-5d195fa856bb.png">

Here is snapgene results

**Comment by ksahlin** [comment]
My guess: 
The "mapped" positions in the PAF file are inferred from minimizer chains, and are therefore approximate. If you want exact positions you need to do alignment with the `-a` option, at the cost of being computationally slower.

**Comment by wjyzidane** [comment]
Ok. I will try -a. Thanks!

**Comment by wjyzidane** [comment]
when I try:
minimap2 -a long.fa short.fa 
I lost most reads which can be mapped before.
when I try:
minimap2 -a short.fa long.fa 
I got the position on short reads, which is not useful

**Comment by lh3** [comment]
Then use -c. -a has the same information, but you need to learn how to parse the results in SAM.

**Comment by wjyzidane** [comment]
"minimap2 -c short.fa long.fa" gives the correct position. Thanks a lot.
