### ISSUE TITLE
SAM header interspersed through file (not a duplicate of #15)

### ISSUE THREAD

**Issue by jblachly** [lh3/minimap2#39]
Not a duplicate of issue https://github.com/lh3/minimap2/issues/15

Similar problem, but different cause (and far more duplicated headers)

When passing multiple FASTQ files on the command line, a new SAM header is inserted in the output stream once (AFAICT) for each input FASTA/FASTQ.

Version: `2.2-r409`

**Comment by lh3** [comment]
Yes, I am aware of the issue. The github HEAD has fixed it. The next release is coming soon and will of course have this fix, too.

**Comment by lh3** [comment]
I will close this for now as it should have been fixed on github. Please feel free to reopen it or create a new issue if you there is still this problem. Thanks for reporting. I appreciate.
