### ISSUE TITLE
Python Pickle out of a mappy.Aligner object error

### ISSUE THREAD

**Issue by DrQuestion** [lh3/minimap2#390]
Hello Doctor Li,
In the python app I'm designing, some kind of user is expected to use frequently the same index created with the same parameters. So, I thought that I had to find a way to save the index, and I'm trying to do so by saving the mappy.Aligner object within a Pickle object.
When I try to do so, I receive the following error:
```
...
    pickle.dump(index, open(INDEX_PICKLE, 'w'))
  File "stringsource", line 2, in mappy.Aligner.__reduce_cython__
TypeError: no default __reduce__ due to non-trivial __cinit__
```
I humbly guess it may lack the implementation to allow this possibility, which if present could be a great functionality.
Thank you so much for your attention,
Alessio Albanese.

**Comment by lh3** [comment]
Sorry that I don't have plans to support Pickle because I don't use it, so won't be able to maintain the related code in future. I have made some changes for your other ticket #372. I hope that works.
