### ISSUE TITLE
match+intro>reads_sum

### ISSUE THREAD

**Issue by luckylyw** [lh3/minimap2#391]
Hi, Heng!
I am trying to align Pacbio data(RNA) of ecoli and A.thalian to its reference. In each read of the sam file, i regard match(=) + intron(N) as the total match number of this read. However, I found that match+intron > the length of this seq?
`$minimap2 -ax splice -t 40 --eqx -uf -C5 NC_000913.3.fasta corrected_reads.fastq > aln.sam &`
The issues are:
1. Why match+intron>the length of seq?
2. I wonder if the first read is the highest quality when this read is aligned to multiple positions of the reference genome.

**Comment by lh3** [comment]
Introns are not part of reads.
