### ISSUE TITLE
Chopping long reference names with --split-prefix

### ISSUE THREAD

**Issue by aroelo** [lh3/minimap2#394]
While using minimap2 with the --split-prefix parameter I found that long reference names randomly get chopped in the header of the resulting sam file.

This is obviously a problem, because the reference names sometimes get chopped after even the first character and therefore it is impossible to tell for reads to which reference they were actually mapped. This problem doesn't occur when leaving out the --split-prefix option.

For me it would be great to be able to use the long reference names, since I want to include a species description in the name.

I added an example reference, reads and resulting sam file below.
The sam file was created with minimap2 version 2.14-r883:  
`minimap2 -ax map-ont long_ref_headers.fa seq_C11737035 --split-prefix string > long_headers.sam `

[long_ref_headers](https://github.com/lh3/minimap2/files/3157523/long_ref_headers.txt)
[seq_C11737035](https://github.com/lh3/minimap2/files/3157522/seq_C11737035.txt)
[long_headers](https://github.com/lh3/minimap2/files/3157524/long_headers_sam.txt)

**Comment by lh3** [comment]
Do you have test data?

**Comment by aroelo** [comment]
Yes, please see the example files attached.

**Comment by lh3** [comment]
Thanks! I overlooked that.
