### ISSUE TITLE
How to understand output alignments

### ISSUE THREAD

**Issue by souzaems** [lh3/minimap2#397]
Hi I'm new in this area and I have this issue:

I have scaffolds from a genome and I would like to mapping the mtDNA from a reference in this genome. So I used this command:

Minimap2 -ax asm5 myscaffold.fa mtref.fa > aln.sam

I didn't understand how to interpret the output, and when I blast the fragments that the program select is the same from the mtref.fa

I also try do to

minimap2 -ax asm5 mtref.fa myscaffold.fa > aln2.sam

But the output seems to be the whole scaffold file.

So I'm doing something wrong?

I'm sorry for the silly question

**Comment by lh3** [comment]
You may use option `-c` to get the [PAF](https://github.com/lh3/miniasm/blob/master/PAF.md) format, which might be easier to understand. You need to find a tutorial on how to work with the SAM format.
