### ISSUE TITLE
Mappy with multi-part index 'best' primary hit

### ISSUE THREAD

**Issue by DrQuestion** [lh3/minimap2#399]
Hello Doctor Li.
I've solved the problem of indexing a very large database by splitting it into chunks and generating many indexes, thus generating a multi-part index. I'm interested now in assigning unambiguously a single read to a single reference. With an uni-part index, this problem may be solved with the is_primary property of the best hit. Now it's not enough, since I could, in the worst case, have a primary hit for each index. 
**How would you suggest to distinguish that hit that would be flagged as primary when mapped on an uni-part index?**

**Comment by lh3** [comment]
Sorry for the late reply. Mappy doesn't properly support multi-part index.
