### ISSUE TITLE
mm_align1: Assertion `qs1 >= 0 && rs1 >= 0' failed

### ISSUE THREAD

**Issue by zkstewart** [lh3/minimap2#40]
Hi,

I tried using the latest commit (r525) today and have run into issues. Below is the stderr.

```
[M::mm_idx_gen::82.657*1.82] collected minimizers
[M::mm_idx_gen::91.379*2.39] sorted minimizers
[WARNING]^[[1;31m For a multi-part index, no @SQ lines will be outputted.^[[0m
[M::main::91.381*2.39] loaded/built the index for 527123 target sequence(s)
[M::mm_mapopt_update::98.263*2.29] mid_occ = 229
[M::mm_idx_stat] kmer size: 19; skip: 5; is_HPC: 1; #seq: 527123
[M::mm_idx_stat::102.392*2.24] distinct minimizers: 273877548 (41.74% are singletons); average occurrences: 3.321; average spacing: 4.398
minimap2: align.c:470: mm_align1: Assertion `qs1 >= 0 && rs1 >= 0' failed.
/var/spool/PBS/mom_priv/jobs/2440842.pbs.SC: line 29: 36242 Aborted                 (core dumped) minimap2 -x ava-pb -t $THREADS -a $FILEDIR/$FILENAME $FILEDIR/$FILENAME > genome_asm2.raw.sam
```

I don't encounter this issue using the latest release (2.2 r409). I'm running the program on a HPC which uses SUSE as the OS and PBS as job manager. There should be no issues with memory requirements or file space. If you want more information I'd be happy to provide.

Zac.

**Comment by lh3** [comment]
There have been quite a lot of changes between github HEAD and v2.2. Could you help to run the following
```sh
minimap2 [options] -t1 --print-qname ref.fa query.fa > /dev/null 2> run.log
```
This asks minimap2 to run on single thread and print query name to stderr. The last read name in stderr should be the one that led to the assertion failure. You can extract that read for debugging. If your reference genome is publicly available, I will debug on my side. If not, probably I need your help. It will take a few rounds.

I have run r525 on quite a lot of reads but haven't caught this assertion failure. Your help will be much appreciated. Thank you!

**Comment by lh3** [comment]
I have identified the bug and fixed it on the github HEAD. Please try r526.

Thank you very much for reporting this. I was mostly using human genome which is fairly complete in comparison to other species. Using a fragmented assembly is much more likely to trigger this bug. I need to test on fragmented assembly often in future. Thanks again!

**Comment by zkstewart** [comment]
The genome data is still private, but it wouldn't be a problem to share a few reads that cause the issue with you if that helps to get to the bottom of it.

I ran two tests following your suggestion, one with the -a tag to produce SAM output, and one without, just to see if this mattered. The commands are below:

```
minimap2 -x ava-pb -t 1 --print-qname -a $FILEDIR/$FILENAME $FILEDIR/$FILENAME > /dev/null 2> run1.log
minimap2 -x ava-pb -t 1 --print-qname $FILEDIR/$FILENAME $FILEDIR/$FILENAME > /dev/null 2> run2.log
```

This seems to have made a difference, since the run with the -a tag failed with the assertion error, whereas the run without the -a tag has made it past this point and is still running as of now. The run that failed had this as the last two lines:

```
QR      m000_000/16037/0_17464  0
minimap2: align.c:470: mm_align1: Assertion `qs1 >= 0 && rs1 >= 0' failed.
```

Do you want me to send this m000_000/16037/0_17464 read (or the one immediately after it)? Let me know anything else you'd like me to try as well.

**Comment by lh3** [comment]
See my last comment an hour ago. I believe I have fixed this problem. Please checkout the latest github HEAD and try the new version r526. Thank you.

**Comment by zkstewart** [comment]
Yep, program doesn't crash at this point anymore. Thanks for sorting it out so quickly.

**Comment by DeadlineWasYesterday** [comment]
Hi @lh3 Heng, I'm getting the same issue on 2.26-r1175, with an asm5 all v. all alignment of the 2019 Svevo assembly. 

![image](https://github.com/lh3/minimap2/assets/55690046/3aa4eb06-e309-4f2a-9191-64151ba40bcd)
