### ISSUE TITLE
Repeat at @SQ

### ISSUE THREAD

**Issue by yuntwang** [lh3/minimap2#400]
Hi,
When I use the command line:
minimap2 -t 10 -ax splice --split-prefix -uf --secondary=no sequences.fa data.fastq > data.sam
The header of my sam:

> @SQ	SN:Chr1	LN:43270923
> @SQ	SN:Chr2	LN:35937250
> @SQ	SN:Chr3	LN:36413819
> @SQ	SN:Chr4	LN:35502694
> @SQ	SN:Chr5	LN:29958434
> @SQ	SN:Chr6	LN:31248787
> @SQ	SN:Chr7	LN:29697621
> @SQ	SN:Chr8	LN:28443022
> @SQ	SN:Chr9	LN:23012720
> @SQ	SN:Chr10	LN:23207287
> @SQ	SN:Chr11	LN:29021106
> @SQ	SN:Chr12	LN:27531856
> @SQ	SN:ChrUn	LN:633585
> @SQ	SN:ChrSy	LN:592136
> @PG	ID:minimap2	PN:minimap2	VN:2.16-r922	CL:minimap2 -t 10 -ax splice --split-prefix -uf -N0 /share/nas1/chengxc/database/rice.RGAP7/sequences.fa /share/nas1/wangyt/workdir/project/flnc_nanopore/data/Result/05.cut_rRNA/data.fastq
> @ SQ	SN:Chr1	LN:43270923
> @SQ	SN:Chr2	LN:35937250
> @SQ	SN:Chr3	LN:36413819
> @SQ	SN:Chr4	LN:35502694
> @SQ	SN:Chr5	LN:29958434
> @SQ	SN:Chr6	LN:31248787
> @SQ	SN:Chr7	LN:29697621
> @SQ	SN:Chr8	LN:28443022
> @SQ	SN:Chr9	LN:23012720
> @SQ	SN:Chr10	LN:23207287
> @SQ	SN:Chr11	LN:29021106
> @SQ	SN:Chr12	LN:27531856
> @SQ	SN:ChrUn	LN:633585
> @SQ	SN:ChrSy	LN:592136

why?
Hope to get your reply.
Thanks

**Comment by lh3** [comment]
Remove `--split-prefix`.

**Comment by lh3** [comment]
Minimap2 shouldn't have this issue any more.
