### ISSUE TITLE
minimap2 results to DESEQ2

### ISSUE THREAD

**Issue by uhlkatie** [lh3/minimap2#401]
Does anyone have experience with taking the resulting .sam/.bam files from minimap2 and funneling them into a differential analysis package? Specifically, I am looking to take reads from Direct RNA sequencing on the Oxford Nanopore Technology MinION to something similar to DESeq2. I chose minimap2 because the parameters can be tailored to fit the noisy long-reads from the MinION. I was able to run minimap2 successfully, but from there I have hit a wall.  I attempted to follow the document:  https://bioc.ism.ac.jp/packages/2.14/bioc/vignettes/DESeq2/inst/doc/beginner.pdf

But when it comes to the sample table, I am confused as to how to find/generate it.  Any help  or advice for a first time RNA-seq analysis would be greatly appreciated.

**Comment by lh3** [comment]
I am afraid you have to ask the DESeq2 developers.

cc @mikelove

**Comment by mikelove** [comment]
There was a recent thread on the support site:

https://support.bioconductor.org/p/120764/

**Comment by lh3** [comment]
Thanks, @mikelove! I am closing the issue here.
