### ISSUE TITLE
Weird PacBio Mapping Results of Minimap2

### ISSUE THREAD

**Issue by b524198065** [lh3/minimap2#402]
Dear Dr. Li,

When I mapped PacBio noisy reads to reference genome where a deletion exists (see the figure below), I found coverages of some regions were abnormally high because a large number of clipped reads (usually leave very short length of original reads) were mapped to the deletion regions. Actually there were a few normally mapped reads that could encompass the variants.

Is there any solution for this situation? By adjusting the program parameters or trying another aligner? Thanks.
<img width="1219" alt="A24683F5-7F02-430A-A3B2-56DCB7C1B3EA" src="https://user-images.githubusercontent.com/39608290/57697980-0cdd4100-7687-11e9-95ac-af00b54f5c0f.png">

**Comment by lh3** [comment]
This is probably an L1. Using `-r7k` may alleviate the issue, but won't fix everything. You have to learn to deal with it.
