### ISSUE TITLE
Computation time spend on modules in minimap2

### ISSUE THREAD

**Issue by cherubzhen** [lh3/minimap2#403]
Can sombody give an estimate how much computation time is spent on hashing, chaining,  final alignment construction and quality score estimating for human data? I need those weight numbers to consider potential acceleration.

**Comment by armintoepfer** [comment]
Why would you consider acceleration, if you can't even benchmark it on your own?

**Comment by lh3** [comment]
Exact numbers vary with data sets. You should use a profiler like linux perf, gprof or Intel vTune.
