### ISSUE TITLE
Exon consisting of long insertion (1170bp)

### ISSUE THREAD

**Issue by juheon** [lh3/minimap2#404]
Using minimap2 2.17-r941 for PacBio cDNA library, I found one of the exons solely consists of long insertion (1170bp). CIGAR string for that exon and flanking introns is 482N1170I410N. I want to understand how do you determine what is exon and intron in this case.

My minimap2 command:
`minimap2 -ax splice -uf --secondary=no -C5 --MD hg19.fa test_24511341.fasta`

The manual of minimap2 (https://lh3.github.io/minimap2/minimap2.html) says that 
* long deletions are regarded as intron
* long insertions are disabled

Here are my questions:
1) How long insertions are disabled with 'splice' argument? Is 1170bp not long enough?
2) For the exon and flanking introns (CIGAR string: 482N1170I410N), How does minimap2 tell the boundaries of exons and introns? The exon (1170I) does not map to hg19 at all. How does minimap2 estimate the size of introns?
3) Does MAPQ consider the size of the inserted sequence? 1170I containing read has MAPQ 60 which is the best MAPQ score of minimap2.

@PG     ID:minimap2     PN:minimap2     VN:2.17-r941    CL:minimap2 -t 20 -ax splice -uf --secondary=no -C5 --MD ~/genomes/hg19/minimap2/hg19.fa test_24511341.fasta
test/24511341/ccs       0       chr2    27353624        60      19S12M1D18M2I3M1D15M1D4M1I8M1D13M1I5M1I6M1I3M1I2M1I4M1D6M1I1M3I3M3I9M1I9M1I5M1I8M1D4M3I1M2I11M1I7M1I6M1I4M3I12M2I3M2I2M1I3M1I3M1D7M1D10M1I2M6I9M4I5M1I18M3I8M1I4M2I6M1I7M2I4M1D11M1I6M2I10M1D11M1I3M5I10M2D5M2I9M1I12M1I1M1I2M2I3M1I11M1D34M1I9M1I12M1I3M3I1M2I2M2I6M1I5M1I8M1I5M1I13M1I10M3I4M1I9M1I6M1I16M2D16M1I2M2D27M482N1170I410N4M3D5M2D24M1D6M1I4M1I3M1D28M1I18M1I5M1I19M1D4M1D52M1I4M199N18M1I10M1I5M1D54M1I9M1D7M1I22M115N39M1D7M1D8M1D18M1D7M193N3M1D5M1D3M1D28M1D86M1D33M1D24M1D11M1D20M196N47M2D39M1D16M1D22M1D22M1D21M1D13M1D564N3M1D2M1D26M1D29M1D65M1D14M1D15M1I7M1I3M1D17M1D4M1D10M1I29M1D8M1D47M1D39M1D5M     *       0       0       CCTTTTTTCTCTTCCTTTTTTTAGGGTCGCATTCACTCTTTCCTTGTTTACAGTAATATCACCTTTTCCGCCTCAATGGGCTAGCTTCATTTGCCACATTCGCTCAAGCCTACCGCGGTATCCACCATGGCAGGCACACCTTATTGACATCTTTAGCGCCAGTCTGGCTTATGCTCAAACTCCCATCTGAACTCCCCAGACTTACTACCCCACATAGTCTTCCTTTTGGGCCCACCTTTCGCTGCCTAACACAGATACCGGTGCGTCCGGCAGTCCCGTGACACCCCATGAAACTGCCAGAGGCTTCACGATGTGAAGCAGGAAGACTGGCACACAACGTACTGAGGGAGAAGGAGCAAACTGTTTTTCTCCCGGATGACATCAGTAGCCGCACATCCAGGCTCTGTCATAAATTCACATGTTTTCCATCTAAGCGTACAGAAGTCTCAACTCTGGGCCTCTGGTTAGCAGAAAACAGGAGGCAGGGAGTAATGGCCTGGCGCTTCAGATACCGGCTTACGTCTTGACTGGATCTGATCTCACAGATGAACGAATGGCGCAGTTCCTGAGTACCCTGAGACATCACTACAGGGCCACTAGCCACAGCCTTTTCACTAGAAGCAGGCAGTGCCCATTCCATTCTCAGAGGCAACCTCATCTGTGGACTGGGCCTATGAAGAGTGAGGCAAGGGGGTCGGTGGGGGGGGGGGGGGGGGGAGGTCCAGGGCCTCGCACAGGGGGCTCCCTGCACCCCCCCCCGGTGCTCATACCGACCTCGGAGACACAGAGCTGATGTGCAGATAGTAGTCCTCCAGGTTTACCGCAACGCTCCCGTAGATGATCTCTGATTCCTAGCCCTCAACCACAGGAAGCGGTTGACATGCCCTAGGAACAAAACTCGAGCTACGGCACTCGATCAGCAGCGTCAGGATGGCCTGACGTTGTCCCCCCTAAAAATTACAACACTCCACCTATAGCGCCATCAAGAGGGGTAAGGGGTTCCCCGATCTCCACACATACCAACATGCAGCTAGGACGTGCGTACGCTCGACAACTAGCCTCCATGGAAGCCCCTACATGTATCCCTTCACGACCTGGTGCCTCAATGAGGGGTCCGCCACAATCTCACCCCAATCAGATCATGGAGAGACCACCTGATCGCGCTACCTGGGCGGAAGAGGGGTCTCTCAATTCAAGTGAGACCCCCTGATGCCTCACCCGATGGGCTCCCAAGAGGGACCTGACCTCAGGGAGGACCACCGGTCCACCCACTGCCTGAGCCAATAAGGGCGGTCCCCAATCTCAGTGGAGTCACCTGATTCCTCGCACCTGGGCCCAATTGAGGGTCCCAACCTCAGTCCACCACTCATGACCACCTGAATCCAACACCATGACGGCCAGAAGGTCCCAATCCTCCTGGACACCACCATAACAGTGCAGCTTTGATCCTCACTTCACTTGGCCAAGAGGTGTCTCGTATCTGCGACAGGAGACCACATGATCCTCCCAAGGACACGGCCTGGTGCCATGGAAAGAGGGTCGACGACCTGCCAACCCGGGATACCACTCAACTGAAGAGCACAAAGAGAACACCTCAGAGTAGAAAGGTGCCTAAGATCGGTCCCACACTTCACAGCTATGAGCGAACCACCCGTCACCTGATCCCCACTGAGAGATGCCATGGGCCTCCCATCACAGAACTAGGCGACCTGAGGCCCACATCCCTGTAAGAGCAGTAACCGCGATGAATGTAGCCAACGAGGGGTGGCAGGAATCCAGCCAACAGCACAGCAGATCAGCAGTGTGACCGCACGTATCTCCTCCTAGGAAGGTCCGGAATTCACATGACATCGAGGCAGGAGACGACTTATGGCCAACAGAGACTGGTTCGAAGGGGCAAGAGGTCTGAGCCAAACCCAGGCTGTGAGGTACGCAGGTGAGGGGGCTGGCGCAGGCGTTGTGGGAATTTGCACTGTGAAGAGTCGCAGGCCAGCAGGCTGGTCTGGAACCTGCACCAAACCTGCAGGCCTGGTAGCGGGTAAGGTGTGGCTGGAAAGGTGGGTCCATTTTCTTGCCAGTGCAGCTGTGTCACCAGCTGATCCTTCTGACCACACAGAGCCTTAAGGGTCCCGGCCCACGGTTACCAACTTGCCATCAGGCCCTAAAGCCAGGTTTTCAATCTCCCCTCGTGGGTTTGAACTCAGAACCTTCTCCAGGCTGGCACCTTCCGACACGACTAGCCATCTGTTCCTCCAGTGGCAAGCAGGTATTATCGTGGTTGAAGCACACAACTTTCTGCAGTGGATCGGAGCTAAAGTCTGTCTGCACCGCCTGCAAATTCTCTACCCTGATTCTAGCCCCTCGTGCTGGGTTTCCGCTCCACATTCTTCTCTGCTGGGGCTGCTCCCTCCTTTGTCGAGCCCCTGCTCCTTGGAACGGCTTCTCTGCCTTGTTGCCCTGCTGTTGATGTGCCTGGAAGCGCAGGATGACAGTGGGCATCCTGCCCTGCAGCAAGGATGTCACCACAAGTGCCAAGTTCATGTGGCCCGTGTCTCTGTGTCATGGAGTGCAGCAAGGAGGCACTCAGCGCCCATTAATCAGCTCTACTGCAGAAAGTGCACGCATCTTTATGCCTGTCTTGGCGGCGCCTCTCCGACCGCAGCGATGAGCAGCCCAGTGTGGGGTCGACCTGAAGCGCGTACAACGGGAACGGAGCCCGGTACAGCTCTGGCGCCCGGCGCCGGCCATCCCGCCCGGCCGCGTTCACTGCCCGCCACCGCGCGCACCAGGACATGCCGCGCCGGCCTCGACTACTGACCCCGTCGGCTGGTGAACTCGGCCCCGTCCCGCCGGGGCACTCCCTACCCCTCTCACACCGGGGAGTTGCCAAAACCCTGACCACAGCAGGAAGCCGAGCCTCAGCTCGGCTCCGTCCAAGTCGTCTC       *       NM:i:1394       ms:i:901        AS:i:736        nn:i:0  ts:A:+  tp:A:P  cm:i:154        s1:i:729        s2:i:0  de:f:0.1020     MD:Z:3G5T2^G19T1^A7A7^T12^G2G7T13G2A5^G0A1T8A29^G56^C7^G2A0G4A10T7C2A6G29G5^G5G16G1A2^A1G4G17^TG1G3C12T1G0A21^A9A0G6G1A47G20A0A0G8G3T0G38^GG18^TC2G4C10G8C3^GTC5^CC24^C13^T4C13A2T0G6T40^C4^G89^A63^G55C12^T7^C8^C18^G10^A5^G3^G28^G86^G33^T24^T11^G18C0T47^GC39^G1C14^G22^G22^A21^G13^T3^C2^T26^C5C23^C65^C14^G25^C17^G4^T15G23^G8^A47^T39^G5  rl:i:33

**Comment by lh3** [comment]
This sounds a bug. I will have a look at some point. Thanks.

**Comment by lh3** [comment]
In the end, I wouldn't say this as a bug. It is a very rare corner case that leads to misalignment. There is not a fix other than break the alignment at the false long insertion.
