### ISSUE TITLE
reducing the cost of generating cigars

### ISSUE THREAD

**Issue by ekg** [lh3/minimap2#405]
I have use of the precise traceback of the alignment, so I'm using option `-c`. However, it seems that this is very slow in many cases.

Is there a better way to get access to the traceback information? What different operations is minimap2 doing that could be avoided.

My goal is to obtain at least the best alignment in the set of possible all vs. all alignments for each position in all of the given input sequences. I need the traceback information though.

**Comment by lh3** [comment]
If you want base-level alignment, `-c` is the only solution unfortunately. Base alignment is slow by nature.

**Comment by ekg** [comment]
I only want it for the "best" N alignments for each given region of each input sequence.

To me, this suggests that I need to drive the alignment in two steps. In the first, I get approximate alignments as standard. In the second, I force base level alignment for the best N of these.

**Comment by lh3** [comment]
Minimap2 only does base-alignment for up to `-N` secondary chains (supplementary alignments don't count).
