### ISSUE TITLE
SA tag

### ISSUE THREAD

**Issue by woodoo46** [lh3/minimap2#406]
Hi Heng,

I am just wondering if SA tag is matched to the cigar string. For example, a contig is split and mapped to location at A and B. At record A, is SA tag should contain location B's cigar; and at record B, its SA tag should contain record A's cigar. Is this true? 

Thanks.

George

**Comment by lh3** [comment]
> Is this true?

Unfortunately not true for minimap2. Cigars in an SA tag do not show detailed base alignment. Minimap2 does this to reduce the size of output.
