### ISSUE TITLE
how to map Illumina paired-end reads to nanopore reads

### ISSUE THREAD

**Issue by dangchenyuan** [lh3/minimap2#407]
I have mapped Illumina paired-end reads to nanopore reads by using bwa-mem and minimap2, but I find the results are quite different, and the bwa result is much larger than minimap2 result, I mean I find more Illumina reads can map to nanopore reads using bwa-mem.
the bwa script is: 	
bwa mem  -x ont2d nanopore.fasta illumina_R1.fq illumina_R2.fq > NGS_map_nanopore.sam
the minimap2 script is :
minimap2 -ax sr nanopore.fasta illumina_R1.fq illumina_R2.fq > minimap.sam
Whether I use the wrong parameters to result in the bad results ?

**Comment by lh3** [comment]
With the default setting for short reads, bwa-mem is more sensitive than minimap2.

**Comment by dangchenyuan** [comment]
@lh3 thank you.  I found the '-ax sr' and '-ax ava-ont' can't use together, when I want to map  Illumina paired-end reads to nanopore reads  which one I should choose?

**Comment by lh3** [comment]
I don't have good suggestions. See also #90 and #214.
