### ISSUE TITLE
Process termination memory issue

### ISSUE THREAD

**Issue by AlexZambon** [lh3/minimap2#408]
Hello,
I'm running into memory issues with the following system:

Dell Precision T7500 workstation with Dual Quad Core Intel Xeon Processor X5647, 2.93GHz,12M L3, 5 .86GT/s,FPWS T7500
6GB of memory plenty of Hard Drive space. 

I've pre-indexed the human genome (hg38.fa) so that it should run less memory intensive using: > minimap2 -d hg38.mmi 
this worked ok but when I try to map oxford nanopore reads  (14GB .fastq file) with the following: >minimap2 -ax map-ont hg38.mmi -t 3 -2 --MD mcf.fastq > mcf.sam the process gets killed after about 12 hours and only a partial sam file is produced with no mapping data, just what looks like info from the pre-indexed file that looks like this:
@SQ SN:Chr1 LN:24956422
@SQ SN:chr10 LN133797422
and so on... Any help if it is possible to set some other arguments (maybe -K) to enable this to run without maxing out my memory? Thank you very much in advance.

**Comment by lh3** [comment]
6GB RAM is too small You may use split index with:
```sh
minimap2 -ax map-ont -I1G --split-prefix=tmp hs38.fa reads.fq
```
This however will be much slower.

**Comment by AlexZambon** [comment]
Thank you so much for your response. I have ordered more memory. What is ideal?

**Comment by lh3** [comment]
I would get at least 32GB. It is not expensive these days.
