### ISSUE TITLE
Mapping CCS from circular DNA to reference genome

### ISSUE THREAD

**Issue by SentientFish** [lh3/minimap2#409]
Hello,

I am new to bioinformatics and looking for some advice on which parameters to use in minimap2 for my project.

I am using pbmm2 to map PacBio CCSs onto a reference genome. These PacBio reads come from sequencing circular DNA and therefore include many chimeric reads.

I would like to know:
1) If minimap2 is the right mapper to use for my project
2) Which parameters should I use so that my chimeric reads aren't filtered out

Any advice is appreciated.

Thank you,
Pierre

**Comment by lh3** [comment]
See "Getting Started" in README on mapping CCS reads.
