### ISSUE TITLE
Example of --frag=yes

### ISSUE THREAD

**Issue by sjackman** [lh3/minimap2#41]
Is `-x sr --sr --frag=yes` intended for paired-end short reads? Could you please give an example of its use?

**Comment by lh3** [comment]
See examples [here](https://github.com/lh3/minimap2#short-genomic):
```sh
minimap2 -ax sr ref.fa reads-se.fq > aln.sam           # single-end alignment
minimap2 -ax sr ref.fa read1.fq read2.fq > aln.sam     # paired-end alignment
minimap2 -ax sr ref.fa reads-interleaved.fq > aln.sam  # paired-end alignment
```
`-x sr` automatically applies both `--frag=yes` and `--sr`.

**Comment by sjackman** [comment]
Thanks for the explanation, Heng.
