### ISSUE TITLE
Different alignments reported if CIGAR enabled for PAF output

### ISSUE THREAD

**Issue by Adamtaranto** [lh3/minimap2#411]
Hi Heng, 

I'm trying to identify somewhat diverged duplications within a genome by using -D to suppress self alignments and only reporting the best set of non-overlapping alignments for each query contig.
 
`minimap2 -D -k19 -w10 -A1 -B4 -O6,26 -E2,1 -s40 -z400,200 --secondary=no --min-occ-
floor=100 contigs.fasta contigs.fasta`

I want to pull out query contigs where >80% of the contig aligns with >80% identity within a target contig.

Query coverage is easy enough from the PAF records:  ($4 - $3) / $2

However, calculating BLAST-like identity from PAF [ col $10 / $11 ] gives very low alignment scores for near identical duplicated segments that have lots of alignment gaps (from TE insertions etc). 

I've tried the method for calculating Gap-compressed Identity that you [described here](https://lh3.github.io/2018/11/25/on-the-definition-of-sequence-identity) and it does a much better job!

The only thing I've changed in my search strategy to enable this is to add the -c flag to so that the CIGAR string and NM:i tag are included in the PAF output.

`minimap2 -D -c  -k19 -w10 -A1 -B4 -O6,26 -E2,1 -s40 -z400,200 --secondary=no --min-occ-
floor=100 contigs.fasta contigs.fasta`

But I now get a completely different set of alignments reported! Most seem to cover approximately the same target site as before but the alignments are now split into multiple segments.

Does Minimap2 handle chaining of alignments differently if CIGAR output is enabled?

**Comment by lh3** [comment]
Duplicates of #186, #161 and #102.
