### ISSUE TITLE
Keep only one (best) hit for each read

### ISSUE THREAD

**Issue by willemdek11** [lh3/minimap2#416]
Hi @lh3 ,

Is it possible to keep only one (best) primary alignment? (for example based on the MAPQ?)

Thanks,
Willem

**Comment by lh3** [comment]
This is best achieved with downstream filtering:
```sh
minimap2 -ax map-ont ref.fa reads.fq | samtools view -F0x900
```
I would *highly* recommend to retain chimeric hits. For that purpose, you can
```sh
minimap2 -ax map-ont ref.fa reads.fq | samtools view -F0x900
```
which is equivalent to:
```sh
minimap2 -ax map-ont --secondary=no ref.fa reads.fq
```

**Comment by willemdek11** [comment]
Thanks for the answer!

Is it also possible to keep the best hit based on the Smith-Waterman score from the PAF output?
Or if not possible with the SAM output?

Willem

**Comment by lh3** [comment]
I am afraid that you have to write a script by yourself.
