### ISSUE TITLE
A question  about mappy

### ISSUE THREAD

**Issue by versarchey** [lh3/minimap2#417]
Mr Li，May I ask you why the Python module does not support all-vs-all read overlapping? Is it caused by technical problems?

**Comment by lh3** [comment]
Implementing all-vs-all overlapping just needs more time. However, I see few users would need this functionality.

**Comment by versarchey** [comment]
> Implementing all-vs-all overlapping just needs more time. However, I see few users would need this functionality.
Good, thank you very much

**Comment by versarchey** [comment]
OK，I understand, thank you.


 
---Original---

**Comment by lh3** [comment]
Thanks for understanding. Generally, mappy only implements the basic/typical use cases. The C APIs are more powerful.

**Comment by versarchey** [comment]
Yes, the reason we have this problem is that we want to let minimap2 run on  a spark cluster by Python API.




------------------ 原始邮件 ------------------
发件人: "Heng Li"<notifications@github.com>; 
发送时间: 2019年6月5日(星期三) 晚上10:06
收件人: "lh3/minimap2"<minimap2@noreply.github.com>; 
抄送: "王振吉"<1023961658@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [lh3/minimap2] A question  about mappy (#417)




Thanks for understanding. Generally, mappy only implements the basic/typical use cases. The C APIs are more powerful.

**Comment by ctl43** [comment]
Hi @lh3, any chance that you will implement the all-vs-all overlap in mappy in the near future?

**Comment by lh3** [comment]
No plan.
