### ISSUE TITLE
definition of smallest k-mer?

### ISSUE THREAD

**Issue by evanrrees** [lh3/minimap2#418]
Hi,

I am wondering how minimap2 defines what is the 'smallest k-mer' in a given window. Is this simply comparison by lexicographical order (e.g. A>C>G>T) or is there something more complex going on? [Roberts et al.](https://doi.org/10.1093/bioinformatics/bth408) discuss the implications of various ordering schemes, but I haven't been able to figure out from the documentation or source code which is implemented by minimap2.

I'm working with a large, highly repetitive plant genome assembly (~3Gbp, >90% repetitive), mapping both short and long read data. I want to understand the distribution of minimizers in the assembly and per contig (given `-k` and `-w`) so that I can adjust `-f` accordingly (e.g. how much of the assembly does minimap2 ignore, given `-k -w -f`?). I'd like to write a script to do so but would need this key piece of information.

Thank you!
Evan

**Comment by lh3** [comment]
> I am wondering how minimap2 defines what is the 'smallest k-mer' in a given window.

Please read the [minimap paper](https://academic.oup.com/bioinformatics/article/32/14/2103/1742895). Questions like this are best found in papers.

> how much of the assembly does minimap2 ignore

Minimap2 ignores `-f` fraction of assembly.

**Comment by evanrrees** [comment]
Thanks for the prompt reply! I had read through the minimap2 publication but not the original minimap/miniasm publication - this is exactly the information I was looking for, thank you for pointing it out.

So, if I'm understanding correctly,  the k-mers in a given window are sorted by the return value of the invertable hash function, and the minimizer for that window is the k-mer with the numerically smallest of these values? Is this the `hash64()` function defined in [sketch.c](https://github.com/lh3/minimap2/blob/50dae10421ff033b1b2222867ade44cb27f052bb/sketch.c)?

**Comment by evanrrees** [comment]
Also, to clarify the `-f` parameter - I understood this to refer to a fraction of **minimizers** rather than a fraction of the **assembly**. In practice, wouldn't the proportion of the assembly ignored at a given `-f` vary substantially depending on the minimizer frequency distribution (which would itself be a function of assembly complexity)?

**Comment by lh3** [comment]
> Is this the hash64() function defined in sketch.c?

Yes.

> to clarify the -f parameter

I was wrong about `-f`. It is not the fraction of assembly. It is the fraction of distinct minimizers. It is not possible to set a threshold on the fraction of reference.

If you know C, the better way to achieve your goal is to adapt this function:

https://github.com/lh3/minimap2/blob/c16a1742a3a13e9f2a64d7c633eeac93c9211b38/index.c#L164-L185

At line 182, `n` is the number of distinct minimizers and `a[]` holds the count of each distinct minimizer.

**Comment by evanrrees** [comment]
Thanks for clarifying. I will see if I can adapt `mm_idx_cal_max_occ()` for my purposes.
