### ISSUE TITLE
Inquiry about Alignment of assembly data to Reference 

### ISSUE THREAD

**Issue by motto7** [lh3/minimap2#420]
Dear lh3, 

I have been using minimap2 to align my assembly data to Reference genome for finding structural variations and reconstruct my assembly data based on Reference genome (By ordering, i think some scaffolds could be grouped using chromosomes).

my assembly's scaffold N50 is about 40M, so when mapping this to Reference, I found that about 200 scaffolds are multi-mapped to other chromosomes.

(eg scaffold_0 --> CHR1, 
      scaffold_0 --> CHR2,
      scaffold_0 --> CHR12,
,,,,
)

However, my assembled data is very close to Reference genome, so I think this could not be happened.
I would like to conserve my assembled sequence in order to order my scaffold and find structural variations.

So the issue is,
    1. Is there any options to mapping 1to1 (1scaffold -> 1chromosome) ?

    2. Is there any options to just ordering my scaffold based on mapping data ? 

Thank you for developing good tools.

Best regards,
JH.

**Comment by lh3** [comment]
> so I think this could not be happened.

This happens all the time to larger genomes.

1. No. You need to write your own script. Minimap2 is only one step. It can't solve all problems.

2. I don't know what you mean by "order".

Generally, to call SVs, read the [cookbook](https://github.com/lh3/minimap2/blob/master/cookbook.md#asm-var).
