### ISSUE TITLE
alignment score error when -w1

### ISSUE THREAD

**Issue by wangyugui** [lh3/minimap2#421]
Hi,

There is an alignment score error when -w1.

test case:
[test.zip](https://github.com/lh3/minimap2/files/3269111/test.zip)

There are 2 alignment position in ref.3bp.in.fa for query_SE_150.fq.
one is full match. and another is with 3bp insert.

command line:
```
# minimap2 --version
2.17-r943-dirty
#minimap2 -a -x sr --MD -t 40 -k15 -w1 -d ref.3bp.in.fa.sr.mmi ref.3bp.in.fa
#minimap2 -a -x sr --MD -t 40 -k15 -w1 --secondary=yes ref.3bp.in.fa.sr.mmi query_SE_150.fq
```

when '-k15 -w1', the score value is 150 vs 150.(bug?)
when '-k15 -w3', the score value is 147 vs 143.(OK)

checking score value by mm_select_sub function:
```
# git diff
diff --git a/hit.c b/hit.c
index f43b0d6..3b17b20 100644
--- a/hit.c
+++ b/hit.c
@@ -244,6 +244,7 @@ void mm_select_sub(void *km, float pri_ratio, int min_diff, int best_n, int *n_,
                        if (p == i || r[i].inv) { // primary or inversion
                                r[k++] = r[i];
                        } else if ((r[i].score >= r[p].score * pri_ratio || r[i].score + min_diff >= r[p].score) && n_2nd < best_n) {
+                               fprintf(stderr,"DEBUG:%d\t%d\t%d\t%f\n",r[p].score,r[i].score,min_diff,pri_ratio);
                                if (!(r[i].qs == r[p].qs && r[i].qe == r[p].qe && r[i].rid == r[p].rid && r[i].rs == r[p].rs && r[i].re == r[p].re)) // not identical hits
                                        r[k++] = r[i], ++n_2nd;
                                else if (r[i].p) free(r[i].p);
```

**Comment by lh3** [comment]
This is not a bug. There can be redundant hits in intermediate steps, but most of them get removed later. This is evident from the non-zero mapping quality in the final output.

**Comment by wangyugui** [comment]
@lh3 

This result in error usage of  'pri_ratio'(-p FLOAT param) ?

Can we move the step to remove some hit forward, so we can get a more accurate score?

Best Regards
