### ISSUE TITLE
error rate per read

### ISSUE THREAD

**Issue by aspitaleri** [lh3/minimap2#425]
Hi all,
related to #424 I have a similar question. 
@lh3 
"The error rate of these reads is something around 15-5%."  

Is there any reference where is from this value? The error rate is related to the number of reads aligned to the wrong place? I mean, having an average coverage of 100 reads, 5-15 reads should be considered aligned wrongly?
I am using minimap2 to align amplicon (average 800bp) to a reference genome with a coverage about 4000 reads per amplicon. Considering an error rate of 15-5%, ca. 400 reads should be considered wrongly mapped? 
Thanks for any help

**Comment by lh3** [comment]
> The error rate is related to the number of reads aligned to the wrong place?

Please read the context. It is about "percent identity". "Error rate" here clearly means base error rate.
