### ISSUE TITLE
No alignment result when using multimapping option

### ISSUE THREAD

**Issue by rberrens** [lh3/minimap2#428]
We are simulating reads for repetitive regions but if we use the default options with no additional parameters (-ax map-ont) we do not get any output. If we use secondary = no or the splice option we get alignments. The issue comes when we use a [larger input file](https://github.com/lh3/minimap2/files/3291252/simulated_reads_all_1000bp.fastq.gz) but not if we use a 
[small input file](https://github.com/lh3/minimap2/files/3291270/simulated_reads_1000bp.fastq.gz).

**Comment by lh3** [comment]
What's the reference genome? The default preset is `map-ont`, but most likely you will want to add `-a` or `-c`.

**Comment by rberrens** [comment]
thanks for the quick reply. The -a fixed the issue.
