### ISSUE TITLE
wrong FASTA/FASTQ record. Continue anyway.

### ISSUE THREAD

**Issue by ardakdemir** [lh3/minimap2#429]
I keep getting wrong fastq/fasta format error and could not figure out whats wrong with the formats. 

I am calling 

minimap2 -x ava-ont  my.fastq my.fastq   > read1.paf

The program works successfully for other fastq files which look identical so I am quite confused.

Here is the example data from my input .fastq file which contains multiple basecalls:

```text
@ecoli_eval_0001.
AGAGATTTTT.......
+
++++++++++++ (equal length with the basecalled sequence)
```

**Comment by lh3** [comment]
Unfortunately, minimap2 doesn't keep line numbers. It is tricky to know the offending line. You may use biopython or other fastq readers to identify the problem.

**Comment by lucyintheskyzzz** [comment]
@ardakdemir did you end up figuring this out?
