### ISSUE TITLE
Nanopore 1D adaptors ligated to full-length cDNA library prep

### ISSUE THREAD

**Issue by callumparr** [lh3/minimap2#431]
I am confused as to whether -uf flag should be deployed for Nanopore 1D reads coming from cDNA library. 

Should I expect a gene's reads being tagged with both ts:+ and ts:-? 

I could orientate the reads based on the 5' and 3' PCR handles before minimap2 and use -uf?

**Comment by lh3** [comment]
> Should I expect a gene's reads being tagged with both ts:+ and ts:-?

Yes. Generally, if unsure, use `-ub`.
