### ISSUE TITLE
Aligning to a Large Allopolyploid Reference

### ISSUE THREAD

**Issue by malonge** [lh3/minimap2#432]
Hi there,

I am aligning contigs/error-correcting long reads to a 15 Gbp allohexaploid reference genome.

For the contig alignments, I tried both `-k 19 -w 19` and `-x asm5`. The alignments seemed relatively ambiguous, and there were many alignments with mapq=0 (65% of them). I ultimately switched to nucmer, and with parameters `-l 500 -c 1000`, the alignments looked good.

Now, I would like to align error corrected long reads. If my assumption about ambiguity is correct, I will need to favor specificity just like I did with my nucmer alignments. Do you have any suggestions for minimap2 parameters? Alternatively, should I use `bwa mem` and increase the seed size?

Alternatively, do you think my ambiguous alignments could have been caused by something else?

Thank you

**Comment by lh3** [comment]
You should use `-c -xasm5` or maybe add `-r2k`. You may use `--secondary=no` to suppress secondary mappings.

At least for human, I am certain that minimap2 does a better alignment than nucmer.
