### ISSUE TITLE
segmentation fault for nanopore reads

### ISSUE THREAD

**Issue by huangnengCSU** [lh3/minimap2#433]
Hi:
I have done mapping twice using the same command and the same file. It success at first time and reported segmentation fault at second time.
OS: Ubuntu 16.04
Memory: 1T
FAF04090_0_1.fasta size: 523M

![0](https://user-images.githubusercontent.com/28866823/60002256-e30e3580-969a-11e9-9cbc-66845413d305.png)

**Comment by lh3** [comment]
Could you compile with `make CFLAGS="-g -O2 -fsanitize=address"` and rerun? I need more information to tell what's happening. Thanks

**Comment by huangnengCSU** [comment]
@lh3 
thank you for your response. the new error report is:
![4](https://user-images.githubusercontent.com/28866823/60024155-da812380-96c9-11e9-8f84-ad417e9b21c0.png)

**Comment by lh3** [comment]
This is weird. This is not an ordinary memory violation. If there is an invalid memory access at ksw2_ll_sse.c:112, there should be an invalid access at line 101. Furthermore, the first segfault occurred to the first batch of input reads, but asan doesn't report an issue for the first batch. It crashed in the second batch. I don't know what's happening here.

**Comment by huangnengCSU** [comment]
@lh3 
I am also confused. If I split the fasta file into 2 files, then align them to reference. it didn't report error.

**Comment by lh3** [comment]
I will close this issue as I am unable to provide a solution. I'll see if others have a similar problem.
