### ISSUE TITLE
Finding overlaps between long RNA reads

### ISSUE THREAD

**Issue by PengNi** [lh3/minimap2#434]
Hi Heng,

Can minimap2 be used to find overlaps between long RNA reads (_e.g._ PacBio Iso-seq, Nanopore 2D cDNA-seq and Direct RNA-seq reads)? Should I consider splice/junctions when I do this?

Thank you in advance!
Peng

**Comment by lh3** [comment]
You should consider junction motif. The preferred setting depends on your goal. Do you want to cluster different isoforms or not?

**Comment by armintoepfer** [comment]
Fwiw, I don't consider junction motifs in IsoSeq3 cluster.

**Comment by PengNi** [comment]
@lh3 , I just intend to use pairwise alignment to do self-correction of the raw reads.

**Comment by lh3** [comment]
@PengNi I think you can use a setting similar to IsoSeq3. @armintoepfer what setting are you using?

**Comment by armintoepfer** [comment]
Just use defaults with -k 15 -w 5. Make sure you don't cluster anything that has larger gaps.

**Comment by PengNi** [comment]
Okay, thank you. I'll have a try.
