### ISSUE TITLE
Align multiple illumina PE reads at once with minimap2

### ISSUE THREAD

**Issue by xbarvazx** [lh3/minimap2#435]
Hi,

How can I align multiple Illumina PE reads at once using minimap2?

I tried something like this:
minimap2 -x sr *_1.fq.gz *_2.fq.gz | gzip > prefix.paf.gz 

But it did not work.

Thanks,
Raz

**Comment by tseemann** [comment]
@xbarvazx you can use subshells in bash like this:
```
minimap2 -x sr ref.fa <(zcat *_1.fq.gz) <(zcat *_2.fq.gz)
```
