### ISSUE TITLE
SA tag not in man file

### ISSUE THREAD

**Issue by Koeng101** [lh3/minimap2#439]
In the man page at https://lh3.github.io/minimap2/minimap2.html, (and in the git itself) there is no mention of the SA tag. However, minimap2 sometimes includes this tag (I found this as I tried to parse output SAM files into a SQL database). 

It would be great if the documentation included that minimap2 may output the SA tag.

**Comment by lh3** [comment]
Just added. See e026e184.

For details, please read the SAM spec.
