### ISSUE TITLE
Visualizing MINIMAP2 Output

### ISSUE THREAD

**Issue by tramaraj** [lh3/minimap2#44]
Dear Users: 

I have used MINIMAP2 to generate alignments between two genome assemblies. I have a sorted and indexed BAM file. Is there a way to generate plots to visualize the whole genome alignments generated.

ThankS!

**Comment by lh3** [comment]
[Ribbon](http://genomeribbon.com/)?

CC @MariaNattestad

**Comment by lh3** [comment]
Another approach is to use minidot from [miniasm](https://github.com/lh3/miniasm). You need to output in the PAF format though like:
```sh
minimap2 -c -x??? asm1.fa asm2.fa > out.paf
minidot out.paf > out.eps && epstopdf out.eps
```

**Comment by tramaraj** [comment]
Thanks for the recommendations!
