### ISSUE TITLE
What preset should I use for two draft genome comparison?

### ISSUE THREAD

**Issue by tayabsoomro** [lh3/minimap2#441]
I have two draft genomes, one sequenced using 454, and another sequenced through nanopore. I am not sure what preset to use, should I use asm5 (as it is mentioned in the README for draft genome comparisons) or should I use map-ont since I have ONT data?

**Comment by lh3** [comment]
Try asm5, asm10 and asm20 and see what works the best.

**Comment by tayabsoomro** [comment]
I ran the all of the three presets and I got the following results.

asm5:
- 843,144 umapped reads
- 56,840 mapped reads

asm10: 
- 838,765 unmapped reads
- 83,606 mapped reads

asm20:
- 836,948 unmapped reads
- 100,746 mapped reads

It makes sense now that as I go from 5 to 10 to 20, it increases the allowance for divergence in the alignment and hence becoming less and less stringent.

Thank you.
