### ISSUE TITLE
mappy unexhausted `aligner.map` memory leak

### ISSUE THREAD

**Issue by marcus1487** [lh3/minimap2#445]
I have recently come across a memory leak when the `mappy.aligner.map` function generator is not exhausted. In several packages and scripts I use mappy via the following command: 
```
try:
    alignment = next(aligner.map(seq))
except StopIteration:
    pass
```

I have recently tracked this structure down to the source of a memory leak in long running commands. In order to test for this as the definitive source of the memory leak I have run the following code with this structure.
```
import sys
from time import time

import mappy
from memory_profiler import profile

REF_FN = 'yeast_ecoli_human.fasta'
MAX_ITERS = 50000
NEXT_ALIGNMENT = True
REG_LEN = 10000

def get_ref_names_and_lens(aligner):
    ref_names, ref_lens = [], []
    for ref_name in aligner.seq_names:
        ref_names.append(ref_name)
        ref_lens.append(len(aligner.seq(ref_name)))
    return ref_names, ref_lens

@profile
def main():
    t0 = time()
    aligner = mappy.Aligner(REF_FN)
    print('loaded aligner: {}'.format(time() - t0))

    ref_names, ref_lens = get_ref_names_and_lens(aligner)
    print('got ref lens: {}'.format(time() - t0))

    map_thr_buf = mappy.ThreadBuffer()
    iters = 0
    for ref_name, ref_len in zip(ref_names, ref_lens):
        for start in range(0, ref_len - REG_LEN, REG_LEN):
            ref_seq = aligner.seq(ref_name, start, start + REG_LEN)
            if NEXT_ALIGNMENT:
                try:
                    alignment = next(aligner.map(ref_seq, buf=map_thr_buf))
                except StopIteration:
                    # some ref seqs don't map back (probably lots of N's)
                    pass
            else:
                try:
                    alignment = list(aligner.map(ref_seq, buf=map_thr_buf))[0]
                except IndexError:
                    # some ref seqs don't map back (probably lots of N's)
                    pass
            iters += 1
            if iters >= MAX_ITERS: sys.exit()

    return

if __name__ == '__main__':
    main()
```

Running this with the `NEXT_ALIGNMENT` variable set to `True` and `False` gives the "Next Method" and "List Method" lines respectively in the below figure. This figure is visualizing the memory consumption over time produced from the above script. The two vertical lines indicate the approximate time when the reference finished loading and when the sequence lengths have been computed. 

![image](https://user-images.githubusercontent.com/13755444/60742530-9809e300-9f22-11e9-95af-9a295ed589a0.png)

I tracked this memory leak behavior to [these `free` calls](https://github.com/lh3/minimap2/blob/master/python/mappy.pyx#L206) which are not completed when the generator is not exhausted. I have also completed a potential fix for the mappy cython code. Running with the "next method" using this cython fix gives the third line ("Mappy Finally Method"). I have submitted a pull request (#444) though more testing might be needed as the memory consumption is interesting from the bug fixed run in the above graph.

**Comment by lh3** [comment]
Thanks a lot, @marcus1487! I don't write python often, let alone cython. I trust you on this and have merged #444.
