### ISSUE TITLE
Minimap2 suitable for synteny?

### ISSUE THREAD

**Issue by morphos30** [lh3/minimap2#446]
Dear Pr Heng Li,

I just found I can use your recent program minimap2 for full-genome alignment between two closely related species with divergence below ~15%.

I am thinking about using minimap2 output for identifying synteny blocks between 2 species. Do you think it is suitable?

Regards
Raphaël

**Comment by lh3** [comment]
> Do you think it is suitable?

I think minimap2 should work, but so far no presets are appropriate for genomes at 15% divergence. You may try the following:
```sh
minimap2 -s100 -z200 -N50 --min-occ-floor=100 -c -t16 genome1.fa genome2.fa > out.paf
```
This command line is a mixture between the `map-ont` and the `asm20` preset. Let me if it works or not. Thanks.

**Comment by morphos30** [comment]
thank you a lot!

**Comment by Puumanamana** [comment]
Hi Heng,
Is it possible to do that in `mappy` as well? I can't find a way to set some of those arguments (e.g. `-z`).
Cédric

**Comment by lh3** [comment]
No, you can't. Many parameters are not exposed to mappy.
