### ISSUE TITLE
MAPQ = 60 meaning 

### ISSUE THREAD

**Issue by smf96** [lh3/minimap2#447]
Hello,

Is it correct in understanding the mapQ score to mean:

0 = multimapper
60 = uniquely mapped?

Or does a mapQ of 60 just mean it aligned very well?

Any information regarding what the mapQ scores exactly mean for minimap2 would be very much appreciated!

**Comment by lh3** [comment]
> a mapQ of 60 just mean it aligned very well?

Yes.

> Any information regarding what the mapQ scores exactly mean for minimap2 would be very much appreciated!

Ideally, mapQ is the phred-scaled probability of the alignment being wrong. In practice, the estimate can be off.

**Comment by zhijunzhang123** [comment]
When doing quality control of bam files, what should be the threshold of MAPQ?
