### ISSUE TITLE
Reporting all hits

### ISSUE THREAD

**Issue by aderzelle** [lh3/minimap2#448]
Hello,

I was wondering if it was possible for minimap2 to report in its sam output all the mappings for long reads? I am looking for something similar to bowtie2 -a options (report all alignments) or -k (report multiple hits per reads).  I have found that minimap2 flags multiple alignments as seconday (picking the best scoring one as the primary). I realize most people want to see uniquely mapped reads but I have a very specific case where I would like to visualize the mapping coverage allowing for multiple hits per read to be taken into account. In other words, is read K has 3 targets, I would love the 3 targets to be reported as primary alignment. 

Thanks a lot

**Comment by lh3** [comment]
> In other words, is read K has 3 targets, I would love the 3 targets to be reported as primary alignment.

This is against the definition of primary alignment. Minimap2 won't do that.

You can change the setting of alignment viewer to show secondary mappings. Or you can modify the SAM flag for your own purpose.
