### ISSUE TITLE
provide binary python wheels

### ISSUE THREAD

**Issue by graingert** [lh3/minimap2#449]

**Comment by lh3** [comment]
Do you see compiling errors?

**Comment by graingert** [comment]
@lh3 no, it just takes time. If binary wheels were provided I'd be able to save time on every CI job - and so would every other user

**Comment by lh3** [comment]
Compiling mappy takes <10 seconds. Network latency and compilation of other tools in the pipeline are probably much worse than that. Sorry, I won't provide binary wheels.

**Comment by iiSeymour** [comment]
> DEPRECATION: mappy is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559

@lh3 could you reconsider given that pip is deprecating legacy setup.py install methods.

**Comment by lh3** [comment]
Someone has added a pyproject.toml file. Would that work?
