### ISSUE TITLE
mapping illumina reads *to* minION reads

### ISSUE THREAD

**Issue by dougwyu** [lh3/minimap2#45]
i would like to map Illumina (query) reads to minION (reference) reads.  
Which preset would you recommend:  sr or map-ont?  

(or some other set of parameters?)

My use-case is metagenomics.  I have 0.5X coverage genome skims of 50 plant species (Illumina).  Assembling genomes is not currently feasible, but skims are easy and cheapish. 

We then use minION to sequence pollen (thus, multiple species).  i want to see if Illumina mapped reads can be used to identify *each/any* of the minION reads to plant species.

**Comment by lh3** [comment]
I don't think that will work well, not with minimap2. If you want to try anyway, use
```sh
minimap2 -a -k14 -w5 -n2 -m20 -s 40
```
FP and FN rates will be very high.

**Comment by dougwyu** [comment]
thanks for the suggested parameters.  i have just finished running the job, and the initial results look quite promising (lots of filtering still to do). 

Not sure if i should raise this issue here or separately, but with my larger Illumina query files (> 1 GB per PE, gzipped), minimap2 required rather huge amounts of allocated RAM (190GB), or otherwise, the program would hang. The confusing thing is that my job output file reported that the job only used 3-4 GB max RAM.

**Comment by lh3** [comment]
What is the exact command line? How many minion reads are there?

**Comment by dougwyu** [comment]
minimap2 -k14 -w5 -n2 -m20 -s 40 barcode${m}_all_pass.fasta Plate1_${i}_*_bfc_R1_val_1.fq.gz Plate1_${i}_*_bfc_R2_val_2.fq.gz | gzip > Illumina${i}_to_Barcode${m}_alignment.paf.gz

i loop through 50 Illumina PE query files and 10 minION reference files. 

the 10 minION files range between 1112 to 16196 reads.

**Comment by lh3** [comment]
Are you using SLURM? I have seen similar before for other programs. I don't have an answer, unfortunately. It is beyond algorithm. I will leave this open until I come back to the issue some day.

BTW, you can change the command line to:
```sh
minimap2 -a -k14 -w5 -n2 -m20 -s 40 --sr --frag
```
This will help short-read mapping, but it wouldn't resolve the memory issue.

**Comment by dougwyu** [comment]
I'm using LSF scheduler.  

thanks for the revised parameters.  fortunately, i have a workaround for the memory issue.
