### ISSUE TITLE
Trying to concatenate alignments to generate pseudo-contig

### ISSUE THREAD

**Issue by chocotwig** [lh3/minimap2#450]
Hi,

Im trying to get at the rough structure of a genomic region. I dont have high enough coverage to perform local assembly. What would be a good way to stitch together a bunch of sequences that I known align to each other to generate a rough contig?
Thus far, I've been doing it manually, using PAF output coordinates and just appending once sequence to the other. 

Thanks!

**Comment by lh3** [comment]
You should first try a standard assembler like flye or canu. You may also try miniasm on the PAF output.

**Comment by chocotwig** [comment]
I've tried miniasm and wtdbg2, but they haven't been good at producing the expected contigs. My coverage is ~1.5x, and I do not have a reference genome either.

Thanks

**Comment by lh3** [comment]
At 1.5x, you will get very short contigs. I don't think it is worth trying to do assembly. Anyway, this is more about assembly, not about minimap2.

**Comment by chocotwig** [comment]
Thanks for your inputs. I guess my question was -- what do you reckon is the easiest way to pull out the N hits that map to a given read query X, and to then subset these by the PAF mapping information (i.e. start position & end position).
