### ISSUE TITLE
minimap2 with large pacbio dataset

### ISSUE THREAD

**Issue by Malabady** [lh3/minimap2#451]
Hi,
I am running minimap2 on a large pacbio dataset (over 22 million reads). here is the command:

$minimap2 -x ava-pb -t 23 -H all.subreads.min1kb.fastq all.subreads.min1kb.fastq  > all.subreads.minimap2.paf

The run is taking too long and the paf file is becoming huge (over 8TB). 

Does this seem normal? is there any particular flags that I can use to make run faster and reduce the paf file size? 

I will use the paf file with miniasm to do an assembly. 

Thanks for the help. 

Magdy

**Comment by lh3** [comment]
You should use flye, wtdbg2 or shasta to assemble large genomes. Miniasm is not the right tool these days.
