### ISSUE TITLE
[ERROR] failed to write the results

### ISSUE THREAD

**Issue by cchd0001** [lh3/minimap2#452]
Hi , 

currently we are running minimap2 with pacbio reads for a huge gemome size ( ~10G ）,and    got below log :

```
[M::mm_idx_gen::33788.288*26.34] sorted minimizers
[M::main::33788.288*26.34] loaded/built the index for 351875 target sequence(s)
[M::mm_mapopt_update::33788.288*26.34] mid_occ = 389
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 351875
[M::mm_idx_stat::33793.239*26.34] distinct minimizers: 217961533 (33.67% are singletons); average occurrences: 6.276; average spacing: 2.925
[M::worker_pipeline::33959.682*26.36] mapped 26446 sequences
[M::worker_pipeline::34051.017*26.37] mapped 27084 sequences
[M::worker_pipeline::34136.312*26.38] mapped 26989 sequences
[M::worker_pipeline::34226.981*26.39] mapped 26890 sequences
[ERROR] failed to write the results
```

we try to re-run but it is  stll there . 

we use the pacbio reads as reference and use a NGS contig as querys. 
       
 command is : ` minimap2  -x ava-pb -H -t 32 pacbio.reads  ngs.contig`

it always abort when the file size of output.paf is 900+G , we check the disk and there is enough space left .

**Comment by lh3** [comment]
> we check the disk and there is enough space left.

This is what I was going to say. You typically see this error when there is not enough space. Have you checked disk quota?

**Comment by lh3** [comment]
BTW, it is not recommended to use minimap2+miniasm for huge genomes. Flye, wtdbg2 and shasta will be much faster.

**Comment by cchd0001** [comment]
We delete about 2T files to empty the space before re-run, but it still happened.  
We are try to split the input files into small trunks now.

**Comment by cchd0001** [comment]
By spliting data into small chunk and re-running , we can get the output paf now.

**Comment by lh3** [comment]
Could you try the GitHub HEAD? With #454 merged, you may get more informative error messages. Thanks.

**Comment by cchd0001** [comment]
Sorry for the delay , after all those spliting-running-merging jobs, we update minimap2 and re-run the latest code, here is the tail of logs :

`[M::mm_mapopt_update::12108.641*16.67] mid_occ = 335
[M::mm_idx_stat] kmer size: 19; skip: 5; is_hpc: 1; #seq: 350362
[M::mm_idx_stat::12113.419*16.67] distinct minimizers: 210396822 (43.84% are singletons); average occurrences: 4.405; average spacing: 4.317
[M::worker_pipeline::12261.910*16.68] mapped 26446 sequences
[M::worker_pipeline::12323.168*16.70] mapped 27084 sequences
[M::worker_pipeline::12404.861*16.71] mapped 26989 sequences
[M::worker_pipeline::12474.461*16.73] mapped 26890 sequences
[M::worker_pipeline::12540.755*16.74] mapped 27392 sequences
[M::worker_pipeline::12617.769*16.75] mapped 27563 sequences
[ERROR] failed to write the results: No space left on device
`
May be all I need is to discuss it this with IT fellows.

Thanks  a lot .

**Comment by twang15** [comment]
I came across a similar situation. The error message is not informative to triage the issue. Any idea how to make it work is appreciated.

Sequencing read dataset: ~700GB.
Minimap2 version: 2.24-r1122

Error message: 
[M::worker_pipeline::34878.114*23.93] mapped 163343 sequences
[M::worker_pipeline::34926.848*23.93] mapped 163089 sequences
[M::worker_pipeline::34976.946*23.93] mapped 163340 sequences
[M::worker_pipeline::35023.444*23.93] mapped 165103 sequences
[M::worker_pipeline::35040.902*23.93] mapped 70784 sequences
[ERROR] failed to write the results: Input/output error
