### ISSUE TITLE
Increasing callable regions

### ISSUE THREAD

**Issue by JennyHTLee** [lh3/minimap2#453]
Hi Heng Li,

I am using the call command from paftools.js to call variants between two long read assemblies.

Only about 15% of all chromosomes are considered callable regions (with ^R). This is probably reasonable as they are plant genomes and one assembly is diploid, another an allotetraploid. The fact that these variants can be reproduced using raw long reads mapping method (ngmlr + sniffles) means that they are likely real. 

My question is do you have suggestions on the parameters to increase callable regions? Is it possible by increasing alignment stringency? 

Current parameters:
`~/programs/bin/minimap2  --secondary=no -cx asm5 --cs $G1 $G2 | sort -k 6,6 -k 8,8n | ~/programs/minimap2/misc/paftools.js call -f $G1 -`

Thank you very much

Best regards,
Jenny

**Comment by lh3** [comment]
You may consider to change `asm5` to `asm10` or `asm20`.
