### ISSUE TITLE
GFF output

### ISSUE THREAD

**Issue by iminkin** [lh3/minimap2#455]
Hi,

Is there a straightforward way to convert PAF to GFF format?

**Comment by lh3** [comment]
Sorry. You have to write a converter by yourself. minimap2 won't support GFF output.

**Comment by gbdias** [comment]
For future googlers,

An option to convert spliced alignments from SAM/BAM to gff/gtf:

1. Align sequences and convert to BAM
`
minimap2 -ax splice --cs target.fa query.fa | samtools sort -O BAM - > alignments.bam
`
2. Convert to BED12 using BEDtools
`
bedtools bamtobed -bed12 -i alignments.bam > alignments.bed 
`
3. Convert to genePred using UCSC tools
`
bedToGenePred alignments.bed alignments.genepred
`
4. Convert to GTF2 using UCSC tools
`
genePredToGtf "file" alignments.genepred alignments.gtf
`

- `genePredToGtf` has additional options that might be useful in specific use cases.
- All of these tools are available in Bioconda.

**Comment by xiekunwhy** [comment]
more commonly,

minimap2 -t 10 -ax splice:hq -uf ref.fa cdna.fa |/Bio/bin/samtools-1.14 view -b > minimap2.tr.bam
perl bam2gff.pl -b minimap2.tr.bam -o minimap2.tr.gff -s /Bio/bin/samtools-1.14
gffread minimap2.tr.gff -T -o minimap2.tr.gtf
perl fixGffread.pl -i minimap2.tr.gtf -o minimap2.tr.fix.gtf
[bam2gff_fixGffread.zip](https://github.com/lh3/minimap2/files/9591008/bam2gff_fixGffread.zip)

**Comment by sanyalab** [comment]
Hi xiekunwhy
> more commonly,
> 
> minimap2 -t 10 -ax splice:hq -uf ref.fa cdna.fa |/Bio/bin/samtools-1.14 view -b > minimap2.tr.bam 
> perl bam2gff.pl -b minimap2.tr.bam -o minimap2.tr.gff -s /Bio/bin/samtools-1.14
> gffread minimap2.tr.gff -T -o minimap2.tr.gtf
> perl fixGffread.pl -i minimap2.tr.gtf -o minimap2.tr.fix.gtf [bam2gff_fixGffread.zip](https://github.com/lh3/minimap2/files/9591008/bam2gff_fixGffread.zip)

I had a question on the bam2gff.pl script. What does the `-d distance to merge` parameter do? If two reads have an indel between them upto 10 bp, then the indel is ignored and the read with the insertion is considered? Is my understanding correct?

Thanks
Abhijit
