### ISSUE TITLE
Mapping transcripts to nanopore reads

### ISSUE THREAD

**Issue by chocotwig** [lh3/minimap2#457]
Hi,

I have been trying to map RNA-seq transcripts to nanopore reads. If I use minimap2  -x splice -uf -C5, I have noticed sub-optimal mapping. Mappings that get picked up by LASTZ do not get picked up by minimap2 when the same transcript is repeated twice on the same nanopore read. Could you please suggest how I could modify my parameters to fix this?

**Comment by lh3** [comment]
Do you have an example?

**Comment by lh3** [comment]
Also you should use -c or -a if you haven’t done that.

**Comment by chocotwig** [comment]
TranscriptX and TranscriptY are closely related at the nucleotide level. Minimap2 maps transcriptX to two locations, one around 52kbp and the other around 79kbp. It doesn't map transcript Y. LASTZ and bowtie2 both map trasncriptX and transcriptY to the 52kbp region, and only transcriptX to the 79kb region. Do you think this could be because secondary alignments aren't reported?
Also, in general, when seeing which transcript maps best, should the transcripts with the highest #matching bases, including gaps be selected as best hits or should the # matching bases without gaps be used? I have been using -x splice -uf -C5 for mapping assembled transcripts to nanopore reads. Do you have recommendations for settings I should use when mapping assembled transcripts to nanopore reads (i.e. -r, -F, -G etc?)

I've been working with the PAF format in my workflow, so I don't use the -c or -a options. If needed, I can send over the actual mapping info to you by email.

**Comment by lh3** [comment]
Please provide actual transcript sequences and the reference genome. That is only way to investigate cases like this.

Just in general, seeing local hits doesn’t mean the transcript should be mapped there. You expect full length alignment.

**Comment by lh3** [comment]
Also, please use -c as I said.
