### ISSUE TITLE
QUAL for secondary alignments

### ISSUE THREAD

**Issue by sjin09** [lh3/minimap2#458]
Dear @lh3 

I was wondering if minimap2 could have the option to include QUAL for secondary alignments. I am aware from #17 issue that this is currently not implemented. We generated HiFi reads from a cancer genome with many genomic rearrangements. If HiFi read contains the genomic rearrangement, it will have multiple secondary/supplementary alignments. The absence of QUAL for secondary/supplementary alignments create problems for downstream analysis.

deepvariant cannot accept alignments without QUAL score for mutation detection. deepvariant, hence, cannot use the secondary alignments for mutation detection. 

Regards,
Sangjin Lee

**Comment by lh3** [comment]
By definition, secondary alignments always have mapping quality 0.

**Comment by sjin09** [comment]
I was referring to the QUAL:ASCII of Phred-scaled base QUALity+33 and not the MAPQ. In this case, would you suggest extracting the phred-quality score from the fastq and appending it to the secondary alignments?

**Comment by lh3** [comment]
Then, no. Minimap2 doesn't and won't output sequences or qualities for secondary mappings. Sorry.

**Comment by lh3** [comment]
Minimap2 already outputs SEQ and QUAL for supplementary alignments.

**Comment by cmdcolin** [comment]
late to the thread here but I made a little program that fetches the SEQ/QUAL from the primary alignment and adds it to the secondary mappings. hope that helps!

 https://github.com/cmdcolin/secondary_rewriter

**Comment by jambler24** [comment]
Found my way here due to the following error:
```
Error in .normarg_at2(at, x) : 
  some ranges in 'at' are off-limits with respect to their corresponding
  sequence in 'x'
```
Seems like it is still causing issues with downstream analysis in places.

**Comment by enc-wmatern** [comment]
You should be able to get the sequences for secondary alignments written to the output bamfile using "-Y": https://github.com/lh3/minimap2/issues/526

"-Y" also appears to output the Phred scores for each secondary alignment - tested with version 2.26-r1175.

This behavior appears to be undocumented.
