### ISSUE TITLE
iso-seq soft clip and polyA

### ISSUE THREAD

**Issue by niehu2018** [lh3/minimap2#459]
Hi,
 
I have poly(A)+ mRNA sequenced by Sequel, and aligned the iso-seq ccs reads (without polyA tail removed but with adapter removed) to the mouse reference genome. Can I consider the soft clipped sequence at the 3'-end as the poly(A) sequences?  What is the accuracy at the end of the alignment? Can we trust the end position of the mapping?

I looked at the closed issue: https://github.com/lh3/minimap2/issues/70
You said both nanopore and pacbio may produce garbage sequences and chimeric reads that are technical artifacts. What kind of garbage sequences may be generated by pacbio in the clipped sequence? Sequence like 5'-cDN =>3UTR=> AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACATTTTCTCCTCCCCCTCCCCGCCAAAAAAAAAAAGAAA-3'?

Best,
Hu

**Comment by armintoepfer** [comment]
Have you tried running PacBio's poly(A)-tail and chimeric read removal first and then map them like most Iso-Seq users do? They work with the FLNCs.

**Comment by niehu2018** [comment]
> Have you tried running PacBio's poly(A)-tail and chimeric read removal first and then map them like most Iso-Seq users do? They work with the FLNCs.

No, I want to recycle polyA sequence withour artifacts, so the iso-seq3 pipeline does not fit me.

**Comment by armintoepfer** [comment]
But you are aware that you don't know if those artifacts are due to true biology, RT, PCR, or sequencing errors?

**Comment by niehu2018** [comment]
> But you are aware that you don't know if those artifacts are due to true biology, RT, PCR, or sequencing errors?

I can select CCS reads with pass larger than 8 or 10 to filter artifacts caused by sequencing errors. Filter chimeric reads may solve some artifacts caused by RT or PCR. 
The trim_isoseq_polyA from pacbio seems to only take account of sequence feature. Is there any other method to recycle polyA sequence at the 3'-end of mRNA/cDNA?

**Comment by lh3** [comment]
> Can I consider the soft clipped sequence at the 3'-end as the poly(A) sequences?

No. If the read is not full length and 3'-end hits to a partial exon, minimap2 may miss it. You have to look at the sequences to decide whether the soft clippings are due to poly-A.
