### ISSUE TITLE
Accelerating minimap2 using GPU

### ISSUE THREAD

**Issue by ZekunYin** [lh3/minimap2#461]
Hi,

Is it possible to accelerate the long-read alignment in minimap2 using GPU? It seems that the ksw_extd2_sse is a computing intensive kernel. What's your opinion about it? The chain-dp kernel has already been mapped to GPU and FPGA see [minimap2-acceleration](https://github.com/UCLA-VAST/minimap2-acceleration).

Best,
Zekun

**Comment by lh3** [comment]
Thanks, but I have no interest in GPU support.
