### ISSUE TITLE
cutoff value of deletion size to be judged as D or S in cigar value

### ISSUE THREAD

**Issue by SiwenZhang521** [lh3/minimap2#462]
Hi heng,

I wonder the cutoff value of deletion size to be judged as D or S in cigar value.
For instance, figure A shows a small deletion in a read, and it is determined to be deletion in the read and alignment information is stored in cigar as 100M XD 100M, so there is only one alignment result in bam file. 
In figure B, a large deletion occurs in genome and a read is splited and mapped to two regions, considered as softclipped read. Hence, there are two alignment results in bam file, and stored in cigar as 100M100S seperately. 
![image](https://user-images.githubusercontent.com/53420795/62264302-f5c21a00-b451-11e9-9c9f-e97a706ac2b6.png)

So I wonder hong long is the deletion to be decided as softclip in cigar value in alignment. Pardon me if you clairified the issue previously and I didn't  find it. 
Thanks.

Siwen

**Comment by lh3** [comment]
Bandwidth `-r` partially controls the max gap size. Scoring, the long-join heuristics and repeats can all affect the decision between D and S. There is not an exact cutoff.
