### ISSUE TITLE
How to best map assembled transcripts to raw nanopore genomic reads

### ISSUE THREAD

**Issue by nirajehta1996** [lh3/minimap2#464]
Hi,

I'm wondering -- what is the best way to map a transcript (assembled) onto raw nanopore genomic reads? Would -splice be appropriate? I expect huge introns (3-10kbp, maybe even more).

Thanks

**Comment by lh3** [comment]
I would try best to avoid such alignment. If you have to do that, the best strategy highly depends on the specific questions you want to answer.

**Comment by nirajehta1996** [comment]
It is important for me to do that -- I am trying to pull out reads that contain a certain transcript of interest, where a genome isn't available. The transcripts themselves are about 1-1.5 kb large, and have, on average, 1-2 introns. I have noticed that using splice mode allows me to identify candidates in reference genomes with decent accuracy.

**Comment by lh3** [comment]
Why do you want to pull out these reads? What is the next step? What is the ultimate goal?

**Comment by nirajehta1996** [comment]
Need to look at the genomic context of certain transcripts. Reads that these transcripts to will be mapped to other reads. Essentially, want to pull out information about the neighborhood of these transcripts.

**Comment by lh3** [comment]
If `-x splice` works for you, I am closing this issue. Thanks for the explanation.
