### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by lappazos** [lh3/minimap2#466]
im trying to run this
minimap -c map-ont rna.idx fastq_0.fastq > test.paf
and get this
Segmentation fault (core dumped)

**Comment by lappazos** [comment]
when i used 
./minimap2 -ax map-ont ref.fa ont.fq.gz > aln.sam   
it worked,
but i received mapping quality of 255 to all reads (which is bad to my understanding)

**Comment by lh3** [comment]
Please provide an example and also the version number.

**Comment by lappazos** [comment]
version 0.2-r123
attached the fastq and ref and results
 ref - GRCh38_latest_rna.fna


[fastq_1.fastq.gz](https://github.com/lh3/minimap2/files/3501155/fastq_1.fastq.gz)

**Comment by lh3** [comment]
> version 0.2-r123

That is minimap, not minimap2.

**Comment by lappazos** [comment]
thx. and could u explain me the difference between the 2 commands? using idx against the ref itself?
