### ISSUE TITLE
-x asm5 left identical overhangs

### ISSUE THREAD

**Issue by cgjosephlee** [lh3/minimap2#467]
Hi,

I'm aligning polished assembly to raw assembly to see any difference, and I noticed a weird behavior that an alignment did not extend to the end of identical portion.

Example:
```
$ minimap2 -x asm5 subject.fasta query.fasta
tig00000001     6810638 11      6810622 +       tig00000001     6794464 339     6794200 6631421 6811396 60      tp:A:P  cm:i:652863     s1:i:6630956    s2:i:6558     dv:f:0.0022
```
however, 
```
$ samtools faidx subject.fasta tig00000001:329-339
>tig00000001:329-339
CCCTGACCTCA
$ samtools faidx query.fasta tig00000001:1-11
>tig00000001:1-11
CCCTGACCTCA
```
the overhangs are identical and not extended in an alignment.

This is not a single case, I'm not sure if I missed something. Would you please give an explanation?
If you need a sample I can send you by email.

Best,
Joseph

**Comment by lh3** [comment]
use -c.

**Comment by cgjosephlee** [comment]
The cigar string is pretty long.
```
tig00000001     6810638 0       6810624 +       tig00000001     6794464 328     6794202 6792094 6811499 60      NM:i:19405      ms:i:6152378    AS:i:6152378    nn:i:0  tp:A:P  cm:i:652863     s1:i:6630956    s2:i:6558       de:f:0.0023     cg:Z:85M1I27M2I35M1I398M1I112M1I165M1I5M1I129M1I26M1I111M4I89M1I43M2I28M1I53M3...
```
It behaved differently while toggling cigar output? I don't expect this to happen...

**Comment by lh3** [comment]
See FAQ:

https://github.com/lh3/minimap2/blob/master/FAQ.md#1-alignment-different-with-option--a-or--c
