### ISSUE TITLE
Mapping based on unique k-mers

### ISSUE THREAD

**Issue by almiheenko** [lh3/minimap2#468]
Hi Heng,

I need to align reads to a sequence using only unique k-mers as minimizers. According to minimap2 manual, it can be done using `-f2` so all minimizers occurring 2 times or more will be ignored. Is that correct? I'm trying to get positions of used minimizers using a `--print-seeds `option, and it seems that not all of the minimizers in chains are unique k-mers.

Thanks,
Alla

**Comment by lh3** [comment]
Please don't do that. You are likely to get unexpected results.
