### ISSUE TITLE
mappy how to use extra_flags

### ISSUE THREAD

**Issue by hliu47** [lh3/minimap2#469]
Hi Heng

May I ask how to use extra_flags in the mappy, e.g. I want to use end_bonus.

mappy.Aligner("test/MT-human.fa", k=15, best_n=10, extra_flags=???end_bonus??) 

Thanks a lot

Haipeng

**Comment by lh3** [comment]
Flags are defined in minimap.h. I don't expect common users to use those. End_bonus is described in the bwa-mem preprint.

**Comment by hliu47** [comment]
Hi Heng

I'm sorry to bother you again but I'm not familiar with C and can not figure it out, I really need the end_bonus flag in mappy, can you please guide explicitly. If it's very complicated I'll then find ways around.

Thanks a lot
Haipeng

**Comment by lpryszcz** [comment]
Hi Heng, same question here, I'd like to change     `-s INT       minimal peak DP alignment score [80]` (`min_dp_max` in minimap.h). 
Could you please explain how to do it with `extra_flags` in mappy?

**Comment by lh3** [comment]
@lpryszcz you can change that with Aligner(min_dp_score=80).

**Comment by lpryszcz** [comment]
Hi Heng, I've noticed that in the mappy.pyx, that's why removed the comment. Thanks for the reply anyway :)
