### ISSUE TITLE
Fasta files are completely unable to map to the reference transcriptome sequence.

### ISSUE THREAD

**Issue by weir12** [lh3/minimap2#471]
Hi:
When I execute the following command
`minimap2 -ax splice -uf -k14 ref.fa reads.fa > aln.sam`

I found that reads could not be mapped to my reference sequence at all.
I have uploaded a demo of reads and reference transcriptome(11 M file size)
[reads_fasta_and_ref_seq.zip](https://github.com/lh3/minimap2/files/3523557/reads_fasta_and_ref_seq.zip)

```
147274 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
0 + 0 mapped (0.00% : N/A)
0 + 0 paired in sequencing
0 + 0 read1
0 + 0 read2
0 + 0 properly paired (N/A : N/A)
0 + 0 with itself and mate mapped
0 + 0 singletons (N/A : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)
```
I want to know what happened and how to resolve it.
many thanks
weir

**Comment by tseemann** [comment]
1. There doesn't seem to be very mich identity between those 6 queries and your reference transcriptome. Longest match is about 17 nt.

```
% blastn -task blastn-short -query fasta_reads_demo.fa -subject GCF_000002945.1_ASM294v2_rna.fna | less

> NM_001356190.1 Schizosaccharomyces pombe putative GTP-binding
protein Nog1 (nog1), mRNA
Length=2217

 Score = 36.2 bits (18),  Expect = 0.35
 Identities = 18/18 (100%), Gaps = 0/18 (0%)
 Strand=Plus/Minus

Query  350  ATCGAATCCAGCTTTTCA  367
            ||||||||||||||||||
Sbjct  269  ATCGAATCCAGCTTTTCA  252
```

2. Given your reference is a transcriptome, are you sure `-x splice` is correct?

**Comment by lh3** [comment]
As @tseemann said (thank you!), minimap2 is not supposed to find such short hits.
