### ISSUE TITLE
Call all aligning base pairs instead of only variants

### ISSUE THREAD

**Issue by Jungal10** [lh3/minimap2#472]
I have been using minimap in the last few days to perform whole-genome alignments.
Subsequently, I used the _paftools.js call_ function to call variants.

Although, I am interested also in the regions where there is a match with my reference genome and not only when variants are present. Is there any workaround for achieving this purpose? If not, it might be a good add-on feature. 

Thank you

**Comment by lh3** [comment]
In the `paftools.js call` [output](https://github.com/lh3/minimap2/tree/master/misc#calling-variants-from-haploid-assemblies). R-lines give you the regions where variants can be called. I am not sure if that is what you want, but it is as far as you can get so far.

**Comment by Jungal10** [comment]
Thank you for the fast response.

Since for these alining regions, it is possible to call the mismatches(variants) will it no be possible to extract in some way the matches (concordant alleles) for these regions?

Maybe you can also help to interpret these R-lines in the output. I understood that the R-lines would indicate the regions where the next variants shown in the list (V-lines) would be found. In other words, the coordinates for the variant calls would be within the coordinates of the region defined in R-lines. But as you can see, I have in my output a different situation. My R-line indicates me 500-522, but next rows calling variants are without this range. Maybe I misunderstood the meaning for this row?

```

R	Contig116|quiver|	500	522
V	Contig116|quiver|	604	605	4	60	t	a	SpoScf_26019	1254	1255	-
V	Contig116|quiver|	760	761	13	60	g	a	SpoScf_26019	1098	1099	-
V	Contig116|quiver|	879	880	20	60	g	a	SpoScf_26019	979	980	-
V	Contig116|quiver|	912	913	20	60	t	g	SpoScf_26019	946	947	-
V	Contig116|quiver|	974	975	20	60	c	t	SpoScf_26019	884	885	-
V	Contig116|quiver|	1013	1014	20	60	a	g	SpoScf_26019	845	846	-
V	Contig116|quiver|	1015	1016	20	60	a	c	SpoScf_26019	843	844	-
```

Thank you.

**Comment by lh3** [comment]
Ignore anything outside R-lines.

**Comment by Jungal10** [comment]
I will then only use the regions within the R-coordinates.
One more question, 
In the variant calling, you state to use only variants with value "1" in the fifth column (query depth). What does this value represent? And how is it calculated?
Thank you

**Comment by lh3** [comment]
Covered by one contig.
