### ISSUE TITLE
Setting minimum intron length

### ISSUE THREAD

**Issue by ksahlin** [lh3/minimap2#473]
I'm assuming minimap2 sets N for deletions >= 50bp (?). Is there:

1. A way to customize this length threshold?
2. Or a combined way: If junctions in the potential intron are canonical and the length is over X bases: Output N in cigar, otherwise output D?

Thanks!

**Comment by lh3** [comment]
> I'm assuming minimap2 sets N for deletions >= 50bp (?).

That is not correct. Deletions and introns are two distinct concepts in the splice mode. You can't simply turn a deletion to an intron or vice versa. The minimum size is indirectly controlled by the second parameter of `-O`. Increasing this parameter will increase the minimum exon length.
