### ISSUE TITLE
Whether positive/negative strand should be considered when direct RNA sequencing reads are mapped to transcriptome?

### ISSUE THREAD

**Issue by weir12** [lh3/minimap2#474]
Hi Heng :

Whether positive/negative strand should be considered when direct RNA sequencing reads are mapped to transcriptome(cDNA)?In my view, cDNA library is produced by reverse transcription of mRNA.So each cDNA sequence is like a template strand in genome.However,the result of minimap2 shown mappings to both reverse strand and forward strand.

Thanks!

**Comment by lh3** [comment]
What do you mean by "transcriptome"? Annotated genes or sequencing reads? If the former, on positive strand only; if the latter, both strands.
