### ISSUE TITLE
de novo genome reconstruction

### ISSUE THREAD

**Issue by BioRB** [lh3/minimap2#477]
Dear developers,
I've used minimap to see how my reads represent the reference genome ( a virus of 8000 bp) . Thanks to minimap  I managed to produce both coverage and a similarity plot. than I've reconstructed the genome using other de novo reconstruction tools.
the question is: if the plots generated using minimap show that "ideally" we have the whole genome and "ideally" we can imagine to get the 100% of identity (looking at those plots),  why then when I use de novo tools I have to struggle to get a draft genome and never getting the 100% of identity?
If minimap gives you the alignment info you should be able then to use this info to reconstruct the genome, right? 
but consider one last thing: Normally we don't know the real sequence of this virus but we have only a reference genome that is the closest one so the goal is to identify the new virus and not just to see the alignment vs the reference one.
minimap can do all this or in this context, we need other assembling tools (de novo)?

**Comment by lh3** [comment]
Not sure about your question, but generally, there are variations between individual virus sequences. You can't get 100% identity in a virus population.
