### ISSUE TITLE
Big Mismatching penalty

### ISSUE THREAD

**Issue by xdudiagnoa** [lh3/minimap2#479]
1. Indexing the target sequences
`minimap2 -t 44 -x map-pb -d hg38_map_pd.mmi hg38.fa`

2. Aligning
`minimap2 -t 44 -c -A 15 -B 22 -O 8,24 -E 2,1 hg38_map_pd.mmi ccs1.fastq > 16wayQ20_test.paf`

With big  `-B` options, minimap2 will be crashed
**'minimap2 -t 44 -c -A 15 -B...' terminated by signal SIGSEGV (Address boundary error)**
if `-B` less than 21, minimap2 works well.

In your Paper
> Li, H. (2018). Minimap2: pairwise alignment for nucleotide sequences. Bioinformatics, 34:3094-3100.

equation (5), zij to be bounded above by M, is M exists? I can't understand, and  didn't  see the proof.

---

minimap2 version 2.17-r954-dirty, hg38 is GRCh38.

test fastq file [ccs1.fastq.gz](https://github.com/lh3/minimap2/files/3599379/ccs1.fastq.gz)

**Comment by lh3** [comment]
Your scoring disallows mismatches. If you are not familiar with SW scoring, please don't modify it.
