### ISSUE TITLE
segfault on pacbio data

### ISSUE THREAD

**Issue by tpesout** [lh3/minimap2#48]
I'm trying to align pacbio reads to hg38 and I'm experiencing a segfault which appears to happen in almost the same location every time I run it.  Out of five runs, all but one occurred during output of the same read: 84377bee_1744_0.  Running minimap on this read and the 3 reads before and after it does NOT cause a segfault.

The data I'm running it on was generated with these commands:
>samtools view -b ftp://ftp-trace.ncbi.nlm.nih.gov/giab/ftp/data/NA12878/NA12878_PacBio_MtSinai/sorted_final_merged.bam chr22 >NA12878.hg19.pacbio.chr22.bam
>samtools fasta -0 NA12878.pacbio.chr22.fa NA12878.hg19.pacbio.chr22.bam

Then I run minimap2 with this command:
>minimap2 -ax map-pb hg38.chr22.fa NA12878.pacbio.chr22.fa >NA12878.hg38.pacbio.chr22.sam

I've made the input data (reference and fasta) available here (I believe that it is publicly available):
s3://minimap2-data/NA12878.pacbio.chr22.fa
s3://minimap2-data/hg38.chr22.fa

I observe this segfault on many of the chromosomes in this MtSinai PacBio dataset, and on the code in master, the r2.3 release, and r2.0 release.   For this particular input, the map-ont flag does not segfault, but on some of the other "bad" chromosomes, the nanopore flag segfaults also.  I'm running this on a "G4" Azure instance.

**Comment by lh3** [comment]
Please try the latest github HEAD. I speculate that this is the same bug as #47. Let me know if you still get a segfault. Thank you.

**Comment by tpesout** [comment]
It worked!  Looks like I checked out the code a few days too early.  Thanks for the quick response!
