### ISSUE TITLE
SAM output without unmapped reads

### ISSUE THREAD

**Issue by slimsuite** [lh3/minimap2#481]
I'd like to use minimap2 to generate SAM output that only includes the mapped reads. Following the docs, I have tried `--sam-hit-only` but get:

```
[ERROR] unknown option in "--sam-hit-only"
```

Is it still possible to run minimap2 with this function? (Most of my many reads do not map, so it is very tedious and disk-consuming to have to post-filter them, unless piping through `samtools view` solves the problem.)

**Comment by armintoepfer** [comment]
You actually did not bother to google :+1: https://lmgtfy.com/?q=samtools+filter+mapped+reads
First google hit: `samtools view -F 4`

**Comment by slimsuite** [comment]
I actually did not bother to Google because I already knew this (hence suggesting piping through samtools). Indeed, this is what I did, but it seems like a very inefficient solution so would like to know if it is unnecessary.(At the time of posting it had not completed and I have had performance issues piping big files through samtools in the past, so did not want to presume it would be ok.) I’d still like to know if minimap2 retains that functionality, perhaps under a different parameter name. Why filter data if you can suppress its production?

Thanks for the attempt to help, but I’d appreciate less misplaced snarkiness next time you wish to state the obvious rather than answer the actual question being asked, please.

**Comment by armintoepfer** [comment]
Are you sure you are using the correct version? It's only supported in v2.17 according to release notes: https://github.com/lh3/minimap2/releases

```
$ minimap2 -a --sam-hit-only ecoli.fasta read.fa 2> /dev/null
@SQ	SN:ecoli	LN:4642522
@PG	ID:minimap2	PN:minimap2	VN:2.17-r954-dirty	CL:minimap2 -a --sam-hit-only ecoli.fasta read.fa

$ minimap2 -a ecoli.fasta read.fa 2> /dev/null
@SQ	SN:ecoli	LN:4642522
@PG	ID:minimap2	PN:minimap2	VN:2.17-r954-dirty	CL:minimap2 -a ecoli.fasta read.fa
read	4	*	0	0	*	*	0	0	ACTCTTACGGGCGAGC...	*	rl:i:0
```

**Comment by slimsuite** [comment]
Good point. Looks like we're still on 2.16. I'll ask my Sys Admin to upgrade. I misunderstood the reference to "minimap2.1" man page to mean that the details of the options were several versions behind - I did not realise it was version 2.1x. Thanks!
