### ISSUE TITLE
Treatment of Ambiguous Bases

### ISSUE THREAD

**Issue by Ellis-Anderson** [lh3/minimap2#484]
I was hoping I could get some info from you on how Minimap2 treats ambiguous bases. I'm working on a de novo assembly project and I'm trying to better understand how the inclusion of N nucleotides between contigs, and the number of Ns included affects the mapping of those contigs and scaffolds.

**Comment by lh3** [comment]
Minimizers around `N` will be ignored. In base-alignment, `N` is like a 5th base. A mismatch involving `N` gets a penalty of gap extension.

**Comment by harish0201** [comment]
Hi,

As a followup question to this, since I'm gapfilling a genome, I would like to extract reads that are aligning partially around the N's flanks (thus leading to a partial overlap with the Ns). How should I be setting up the gap-penalty in this case?

**Comment by lh3** [comment]
Try to use a larger number with `--score-N`.

**Comment by tseemann** [comment]
@Ellis-Anderson default score for match is +2

**Comment by humbleflowers** [comment]
I have a similar doubt, i have a reference fasta file containing primer-barcode-primer sequence which i want to map on fastq file.
I plan to mask the barcode so my reference fasta will be ATGATGCTCACCNNNNNNNNNCTACGTCGACTGAT
I want alignment file where, the primers are matched to fastq file but the N bases are soft clipped so cigar can look like 12M10S12M. Any help will be appreciated. Thank you.

**Comment by lh3** [comment]
Use `--cs` to get the cs tag.

**Comment by humbleflowers** [comment]
`minimap2 -t 4 -ax map-ont --cs --sam-hit-only barcode_masked_N.fa all_pass_files.fastq > P5_masked_aln_reads.sam`
i used both short and long option of --cs, the sam file is empty.
Pls help. 
Thank you.

**Comment by humbleflowers** [comment]
`minimap2 -t 4 -ax map-ont --sam-hit-only barcode_masked.fa all_pass_files.fastq > P5_masked_aln_reads.sam
`
i used --cs tag, both long and short, but i see an empty sam file.
do i need to change the way i'm representing my fasta sequence with N letters.
