### ISSUE TITLE
lift over ref.bed to their query positions without re-aligning

### ISSUE THREAD

**Issue by songtaogui** [lh3/minimap2#485]
Hi,

paftools liftover provides a convenient way to change query regions to ref positions according to query-to-ref.paf. I was wondering that is there an easy way to change ref.bed to their query positions without re-aligning using former-query as ref and former-ref as query?
Or is their an easier way to build a chain file from PAF alignment?

Thank you

**Comment by lh3** [comment]
paftools doesn't support these features.
