### ISSUE TITLE
Question about mapping multiple files at the same time.

### ISSUE THREAD

**Issue by slbai01** [lh3/minimap2#487]
Hi,

I have encountered a weird problem and I will try to describe it, although it seems difficult to describe in my opinion.

I have some `pacbio subreads` files that need to be mapped to the same genome. 

My working environment is on the cluster. Each node has 64Gb memory, 20 cpu, and a total of 14 such nodes. Submit the task with the following command. 

```shell
for x in `ls $base_dir/00.database/$comp_reads/*.subreads.fasta.gz`; do
    filename=$(echo $(basename $x) | sed 's/.subreads.fasta.gz//g')
    thread=19 #
    bsub -q normal -n $thread -R "span[hosts=1]" -e lsf.err -o lsf.out -J $filename "/share/home/baishenglong/programs/minimap2-2.17_x64-linux/minimap2 -t $thread -ax map-pb -Y --MD $base_dir/00.database/$comp_genome/ref.mmi $x | samtools sort -@ $thread -o $filename.sort.bam"
done
```

I tried it several times, but only one minimum input file can output bam (tens of minutes) normally, and other files are not output normally for one to two days. The displayed log information is as follows. 

```text
$bpeek 575593
<< output from stdout >>

<< output from stderr >>
[WARNING] For a multi-part index, no @SQ lines will be outputted. Please use --split-prefix.
[M::main::7.756*0.96] loaded/built the index for 7 target sequence(s)
[M::mm_mapopt_update::9.427*0.97] mid_occ = 1884
[M::mm_idx_stat] kmer size: 19; skip: 10; is_hpc: 1; #seq: 7
[M::mm_idx_stat::10.370*0.97] distinct minimizers: 93159088 (54.43% are singletons); average occurrences: 5.666; average spacing: 7.621
```

After killing these tasks, random pick one  and run it on the mgt node. It can actually produce normal output(about one hour). This made me confused. 

I am not sure if it is an I/O problem. I asked the engineers to test the I/O of the cluster a few months ago. They said that there is no problem.

Thanks for your help.

Shenglong

**Comment by slbai01** [comment]
Update: 
When I run the task using a 512GB memory node, there is still no output, but when I use the 3T memory node, the program looks normal. 

The above 64GB and 512GB memory nodes use Red Hat （4.4.7-16）, 3T nodes use CentOS （release 7.3.1611） system, I am not sure if this affects.

The good news is that it can output results no matter what the reason. :)

**Comment by tseemann** [comment]
`samtools sort` uses 768M ram per thread by default. Is that causing problems?

`  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]`
