### ISSUE TITLE
more "potent" -X option? 

### ISSUE THREAD

**Issue by aderzelle** [lh3/minimap2#488]
Hello,
I was wondering if there is a way in minimap2 to have a different -X. What I mean is that not only it wouldn't report the trivial complete self-mapping of seq1 against itself, but it would neither report mapping of seq:10000-50000 to seq1:100000-150000. Basically, if query name = target name, just skip any alignment attempts on that target. It could be useful to look for non collapsed allelic pairs in haploid assemblies. I have tried the -DP option but it can still report things like
`scaffold00137   7480    4820    6573    +       scaffold00137   7480    5090    7292    1182    2292    0       tp:A:S  cm:i:181        s1:i:1073       dv:f:0.0392     rl:i:0`

Thank you

**Comment by lh3** [comment]
That is a feature and allows you to identify problems or homology. It is easy to filter these hits out if you don't want them.
