### ISSUE TITLE
chimeric alignment

### ISSUE THREAD

**Issue by mcieslik-mctp** [lh3/minimap2#49]
Great project!

Are there any plans to support chimeric alignment (similar to GMAP) in addition to spliced long-sequence alignment? This would be great, as GMAP (and to some extent STAR) is to my knowledge the only aligner that can do this currently.

**Comment by lh3** [comment]
Yes. I defined how to report chimeric alignment in SAM.

> GMAP (and to some extent STAR) is to my knowledge the only aligner that can do this currently.

For long sequences, doing chimeric alignment is very common. BLAT allows to find chimeric alignment, for example. The short-read world is an exception.

**Comment by lh3** [comment]
To clarify: minimap2 gives chimeric alignment for all types of sequences.

**Comment by mcieslik-mctp** [comment]
Thanks for the clarification. After some initial testing minimap2 seems to perform very well. Might be worth mentioning in the word "chimeric cDNA alignment" in the documentation and the pre-print, to improve discoverability of minimap2 for this application.

**Comment by lh3** [comment]
Thanks for the suggestion!
