### ISSUE TITLE
Decoding minimizers

### ISSUE THREAD

**Issue by sdwfrost** [lh3/minimap2#494]
Hi @lh3 

I'm trying to output minimizers, for both a sequence directly (using `mm_sketch`) as well as for an index (by iterating though the buckets as you do in `mm_idx_stat`). How can I get the uint64 as well as the ASCII representation of the minimizers - I assume that I have to use an inverse hash (e.g. using code from [https://github.com/lh3/bfc/blob/master/kmer.h]) along the way. In the documentation in `sketch.c`:

```
@param p      minimizers
               p->a[i].x = kMer<<8 | kmerSpan
               p->a[i].y = rid<<32 | lastPos<<1 | strand
               where lastPos is the position of the last base of the i-th minimizer,
               and strand indicates whether the minimizer comes from the top or the bottom strand.
               Callers may want to set "p->n = 0"; otherwise results are appended to p
```

I tried doing a right shift (`>>8`) on the `x` field of the minimizer, then using an inverse hash, but somewhere I seem to have got it wrong.

**Comment by lh3** [comment]
> I tried doing a right shift (>>8) on the x field of the minimizer, then using an inverse hash, but somewhere I seem to have got it wrong.

This should work for minimizers you get from `mm_sketch()`. The k-mer encoding in the hash table is different.

**Comment by sdwfrost** [comment]
Thanks for the clarification, I didn't realise the encodings were different. I'll take a closer look. 

Assuming that what I'm doing to get the uint64 representation of the kmer is correct, can you let me know how you decode the kmer? I saw that you have this code in `bfc`, but the encoding is different there too:

```
static inline char *bfc_kmer_2str(int k, const uint64_t y[2], char *buf)
{
	int l;
	for (l = 0; l < k; ++l)
		buf[k - 1 - l] = "ACGT"[(y[1]>>l&1)<<1 | (y[0]>>l&1)];
	buf[k] = 0;
	return buf;
}
```

**Comment by lh3** [comment]
Sorry for the late response. Was busy with a manuscript submission.

For a k-mer hash generated by `mm_sketch()`, you may use `bfc_hash_64_inv(a.x>>8, (1ULL<<k)-1)` to get the 2-bit encoded k-mer. `bfc_hash_64_inv()` can be found at:

https://github.com/lh3/yak/blob/c0461c50c425831bae4c0ff8e4041a8aa958951e/kmer.h#L42-L77
