### ISSUE TITLE
cs string missing in secondary alignment after conversion with sam2paf

### ISSUE THREAD

**Issue by ArielSSchwartz** [lh3/minimap2#496]
This seems to be working only for primary alignments. Probably because of [this line](https://github.com/lh3/minimap2/blob/master/misc/paftools.js#L1652), since `t[9] == "*"` for secondary alignments.

_Originally posted by @ArielSSchwartz in https://github.com/lh3/minimap2/issues/310#issuecomment-537286264_

**Comment by lh3** [comment]
Generating the cs tag requires the query sequence. `t[9]` corresponds to the query sequence.
