### ISSUE TITLE
use minimap2 to pick up plant mitochondrial reads

### ISSUE THREAD

**Issue by Yunxia-li** [lh3/minimap2#498]
Hi:
      I had a question about minimap long reads to reference genomes:
I had about **323,815,888kb** long nanopore reads. 
I am not going to assemble whole genome, actually, I am going to assemble mitochondrial genome in a plant. 
The mitochondrial genome in plants are only conserved in 38~41CDS. There are about 15 CDS with exons and intons. Also，inton regions are also largely variable between individuals even in the same species.

I first try to use  one ralative species (they belong to one family ) whole mitochondrial genome as reference to pich up the MT_reads,
`minimap2 -ax map-ont reference_genome ont_reads -o output `
But I got **321,436,467kb**.  (almost near to the raw_reads).
Is that true? Or there is something wrong I understood?
Should I use only the conserved region(**only the exon regions**) as a reference? 

Hope for your reply.
Sincerely

**Comment by tseemann** [comment]
`-a` produces a SAM output file. It probably includes the _unmapped_ reads too. Use `samtools fastq` with the `-F`/`-f` options to filter for only the _mapped_ reads.
eg. https://www.biostars.org/p/56246/

**Comment by Yunxia-li** [comment]
Thanks for your kondly reply.
        I used samtools and I got the mapped reads.
Alternatively, I use all of the raw reads (306G ) to assemble the neclear genome, the command is below:  
Actually, I followed the [https://github.com/fbemm/onefc-oneasm/wiki/Assembly-Generation](url)

` minimap2 -x ava-ont -t 25 raw_reads raw_reads > ovlp.paf   （670G）
  miniasm -f  raw_reads ovlp.paf > asb.gfa    （52M）
  awk '/^S/{print ">"$2"\n"$3}' asb.gfa  | fold > asb.fasta`  **（52M）**

That means this neclear genome is about 52M? I don't think so, because it was about 2.9G based on other methods(k-mer estimate genome size)

Back to the last step, I got the overlap between these raw reads, noe I need to assemble them:
in minimap2 **README file**, there is one command:

 `minimap2 -ax asm5 ref.fa asm.fa > aln.sam       # assembly to assembly/ref alignment`

Can  I use the  relatively far away species as a **ref.fa**? Or can I use contigs from SPAdes as a **asm.fa** to complish the genome assemble?

**Comment by tseemann** [comment]
Your original question was about mitochondria.
I would just use the mitochondrial reads you baited, and assemble using Spades.

**Comment by lh3** [comment]
For assembly of large genomes, try Flye, wtdbg2 or shasta.

**Comment by Yunxia-li** [comment]
Hi:
     I have a question about the assemble process. I konw the aligner use  both the read and it's reverse complement to align sequences. 
But I am wonder if the assembler use  both the input reads and it's reverse complement to assemlbe?
If  there was a sam file, do I need to pick up the reversed complementary mapped reads ( in the secend colume flag : the number is 16 ) and then assemble them?


Hope for your reply.
Yun




At 2019-10-23 20:41:54, "Heng Li" <notifications@github.com> wrote:


For assembly of large genomes, try Flye, wtdbg2 or shasta.

**Comment by tseemann** [comment]
@Yunxia-li yes, the genome assembler will look at fwd and revcom versions of the reads. if it did not, then _de novo_ genome assembly would be impossible.

**Comment by Yunxia-li** [comment]
Thanks for your kindly reply.


 I used to  pick up the mapped reads from sam file ignoring if the reads were forword or reversed mapped. But I didn't get a draft assemble of mito_genome.
Thanks for your reply, I will try other assembler and methods or combine them to assemble my object genome.


Thanks again







At 2019-11-15 05:13:14, "Torsten Seemann" <notifications@github.com> wrote:


@Yunxia-li yes, the genome assembler will look at fwd and revcom versions of the reads. if it did not, then de novo genome assembly would be impossible.
