### ISSUE TITLE
 index.c:246: worker_pipeline: Assertion `strlen(s->seq[i].name) <= 254' failed

### ISSUE THREAD

**Issue by aderzelle** [lh3/minimap2#499]
Hello, 
I am getting this error trying to map ont reads on an assembly. I found out the error comes from the fasta headers, which in my case look like this:
`>NODE_ch83_read377_template_pass_FAH42885_length_19418_cov_5.14986e-05`
renaming the header 
`awk '/^>/{print ">" ++i; next}{print}'`
solved the issue, 
just thought you might like to know. 

thanks for minimap2!

**Comment by tseemann** [comment]
@aderzelle may i ask which version of `minimap2` you used?
```
% minimap2 --version
2.17-r941
```

**Comment by aderzelle** [comment]
2.0-r191-dirty

yes some IDs are much longer than the one I posted.

**Comment by tseemann** [comment]
That version is _very_ old and I thing the limitation of 254 has been removed now. Please upgrade.

**Comment by aderzelle** [comment]
Ok,
it was the bioconda release, it seems there is no more recent version on bioconda (that's not a problem for me to install it using github instead).

**Comment by aderzelle** [comment]
Sorry, the culprit is actually Platanus that installs an outdated version in the $PATH variable O_O

**Comment by lh3** [comment]
This assertion is anyway necessary as in BAM, you can't have a read name longer than 254 characters.

**Comment by lh3** [comment]
I was wrong. Reference name in BAM can be very long. This issue has been fixed via #42.
