### ISSUE TITLE
Please make a release (+ ideas to make this easier)

### ISSUE THREAD

**Issue by tseemann** [lh3/minimap2#5]
Heng, 

I know this annoying, especially in rapid development, but it would help all the packaging teams (Homebrew, Conda, Galaxy) if you could make releases (even labelled as pre-release) regularly, or even just run `git tag r189` when you update to your `r189` version.

@sjackman or others might have smarter ways to achieve this via the command line in a way that isn't too onerous.

Torsten

**Comment by lh3** [comment]
I would wait for a week. The project is too young. Serge found a critical bug (#3) a few hours after I made the source code public. There might be more coming.

**Comment by lh3** [comment]
I have tagged the first minimap2 release [r191](https://github.com/lh3/minimap2/releases/tag/r191).

**Comment by sjackman** [comment]
Thanks, Heng!

**Comment by chgibb** [comment]
I would strongly suggest using CI/CD services such as [Travis](https://docs.travis-ci.com/) to do automatic Linux building and testing as well as [Appveyor](https://www.appveyor.com/) for the same for Windows. Both are completely free. I have a lot of experience working with both and would be happy to open a PR integrating support if there is interest.

**Comment by lh3** [comment]
I have just tagged v2.0 and added a very basic Travis config file.

**Comment by tseemann** [comment]
Awesome Heng!
