### ISSUE TITLE
minimap2 suitable for Iso-Seq CCS all-vs-all?

### ISSUE THREAD

**Issue by ksahlin** [lh3/minimap2#50]
Hi,

Thanks for the great tool. Would you recommend using minimap2 for all vs all alignments of CCS reads? In that case, what would be a recommended parameter combination?

If you think minimap2 has potential to do well in this setting, I could test different parameters and give you feedback on this analysis. 

Best,
K

**Comment by lh3** [comment]
What do you want to achieve? Cluster different isoforms, or transcripts from the same isoform?

**Comment by ksahlin** [comment]
Transcrips from the same isoform.

**Comment by lh3** [comment]
Minimap2 might work, but you have to tune the parameters. No presets will work well. You may start with something like
```
-Xp0 -g1000 -m100 --no-long-join -r50
```

**Comment by ksahlin** [comment]
Great, thanks!

**Comment by ksahlin** [comment]
I will get back with analysis once I get the time to test this to a satisfactory level.
