### ISSUE TITLE
The meaning of '-C0' and '-un'

### ISSUE THREAD

**Issue by zhenLiuExplr** [lh3/minimap2#501]
I have question about the `-u` and `-C`. Should I get two identical alignment results if I set one with `-un` and another with `-C0`? I test some nanopore reads with one set parameters `-x splice -un -C9` and another `-x splice -ub -C0`. They get similar alignment results but not identical. What cause the difference?

**Comment by lh3** [comment]
`-un` and `-ub -C0` are similar but not equivalent. Their behaviors are actually quite different internally. `-ub -C0` does two rounds of alignments, one for each strand, and then choose the better strand. `-un` does one round of alignment and ignores `-C`. When there are ties in scores, the two options may choose different alignments. This is expected.

**Comment by zhenLiuExplr** [comment]
I'm not pretty sure whether I get it correctly. Do you mean the `-ub -C0` have two rounds of alignments, one is for "GT-AG" and the other is "CT-AC"? `-un` does not try to match  any of them. Both `-un` and `-ub -C0` do not give extra bonus or penlty on canonical splice sites, but they might choose different alignments when the alignment scores are equal. Is that right?

Will `-ub -C0` choose the canonical splice sites if there are two alignments with equal scores (one is canonical splice sites, the other is noncanonical splice sites)?
