### ISSUE TITLE
[morecore] insufficient memory

### ISSUE THREAD

**Issue by mictadlo** [lh3/minimap2#503]
Hi,
I used minimap2 (2.17-r941). The `NbV1ChF.fasta` and `ragoo.fasta` are 2.8 G and 3.4 G. However, I ran out of memory on 2 TB machine.

```
minimap2 -ax asm5 --cs -t8 ../../NbV1ChF.fasta ../ragoo.fasta > pm_against_ref.sam 2> pm_contigs_against_ref.sam.log
/bin/bash: line 1: 10389 Aborted                 (core dumped) minimap2 -ax asm5 --cs -t8 ../../NbV1ChF.fasta ../ragoo.fasta > pm_against_ref.sam 2> pm_contigs_against_ref.sam.log
```

```
less pm_contigs_against_ref.sam.log 
[M::mm_idx_gen::55.511*1.79] collected minimizers
[M::mm_idx_gen::60.192*2.17] sorted minimizers
[M::main::60.192*2.17] loaded/built the index for 19 target sequence(s)
[M::mm_mapopt_update::64.517*2.10] mid_occ = 342
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 19
[M::mm_idx_stat::69.857*2.01] distinct minimizers: 143929053 (83.21% are singletons); average occurrences: 1.928; average spacing: 9.884
[M::worker_pipeline::3024.805*3.40] mapped 5 sequences
[M::worker_pipeline::4921.171*3.81] mapped 6 sequences
[M::worker_pipeline::7761.560*3.75] mapped 4 sequences
[morecore] insufficient memory
```
What could cause such a high memory consumption? 
How much more memory do I need?

Thank you in advance,

Michal

**Comment by lh3** [comment]
That may be caused by integer overflow. I may need to reproduce the issue to fix it...

**Comment by mbhall88** [comment]
I am seeing a similar issue with a reference fasta that is 1.1Gb and reads around 2Gb. However, I am not seeing the `[morecore] insufficient memory` error, I am just getting kicked off my interactive job, or the job is failing, hitting memory limits in excess of 24Gb.

Of possible note, my reference file does have some ambiguous bases (N) in it. Not sure if that makes a difference?

I am using version `2.15-r905`

**Comment by lh3** [comment]
For whole mammal genome alignment, using >20Gb memory is expected especially when you have chromosome assemblies and request many threads. However, there must be something going wrong if 2TB is still "insufficient".

**Comment by mbhall88** [comment]
In my use case, the reference is a 16S rRNA database (sequence all around 1.5Kb).  

For one or two of the samples, I was still hitting memory limits with 64Gb of memory.

**Comment by lh3** [comment]
High memory usage is expected given the repetitiveness of the reference data.

**Comment by tseemann** [comment]
@mbhall88  you might want to check if your account is limited in RAM quote too:
```
% ulimit -a

data seg size           (kbytes, -d) unlimited
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
etc
```

**Comment by andrem01** [comment]
@mbhall88 are mapping to "pick" OTUs or classify (taxonomy) reads?

You may want to try using the feature-classifier within q2. You can train the classifier using information based on your specific sample preparation (e.g., primers used etc). 
More information here: https://docs.qiime2.org/2019.7/data-resources/

**Comment by mbhall88** [comment]
> High memory usage is expected, given the repetitiveness of the reference data.

Another example. I have a sample that is (compressed) 311MB in size, mapping to the database I previously mentioned, and 150Gb RAM is still not enough (same for 10s of other samples of the same size). This is the stderr I get

```
[M::mm_idx_gen::30.581*1.57] collected minimizers
[M::mm_idx_gen::33.309*2.16] sorted minimizers
[M::main::33.486*2.15] loaded/built the index for 695171 target sequence(s)
[M::mm_mapopt_update::33.701*2.14] mid_occ = 16535
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 695171
[M::mm_idx_stat::33.842*2.14] distinct minimizers: 7165551 (60.20% are singletons); average occurrences: 25.429; average spacing: 5.537
```

@lh3 if you are saying that this high memory is expected then that's fine, but I think you should clarify this in the documentation because that is crazy high memory usage for mapping a small sample to a seemingly small reference database.

**Comment by lh3** [comment]
> [M::mm_mapopt_update::33.701*2.14] mid_occ = 16535

The repetitiveness is really high here. The peak memory will depend on what sequences are being mapped at the same time across threads. It can vary a lot. One way is to reduce the number of threads.

**Comment by SamStudio8** [comment]
We're seeing something similar with one of our PhD students too. She's aligning a ~1.6 GB FASTQ to a set of 16S references (n=~21000, 50Mb). The job slowly but surely consumes the 64 GB of RAM on her machine and then gets killed by the OOM killer. We've overcome it temporarily by setting the minibatch size to something lower than the `500M` default with `-K`.

**Comment by mbhall88** [comment]
I tried running with a single thread and all 20 samples still use more than 150Gb memory....

**Comment by mbhall88** [comment]
> We're seeing something similar with one of our PhD students too. She's aligning a ~1.6 GB FASTQ to a set of 16S references (n=~21000, 50Mb). The job slowly but surely consumes the 64 GB of RAM on her machine and then gets killed by the OOM killer. We've overcome it temporarily by setting the minibatch size to something lower than the `500M` default with `-K`. I tried to diagnose by running minimap2 on one thread, the `strace` of the child alignment process shows it's just running `mprotect` and `mmap` until all the RAM is consumed.

I will give the minibatch approach a go. Thanks @SamStudio8

**Comment by lh3** [comment]
Also, could you try `--no-kalloc --print-qname`? Thanks.

**Comment by mbhall88** [comment]
I was able to get 20/22 samples to complete within 100Gb RAM with the following options
```sh
minimap2 -K 100M --no-kalloc --print-qname -aLx map-ont -t 1 <target> <query>
```
I am trying `-K 50M` to see if I can get the last two to finish.

**Comment by fbemm** [comment]
I think this is related to https://github.com/lh3/minigraph/issues/7.

I am trying to align to chromosomes which are both ~800Mb.

Testing with K100 now.

**Comment by fbemm** [comment]
Crashed again with Segmentation fault (core dumped).

**Comment by mbhall88** [comment]
Ok, so to get my samples to all run in under 50Gb RAM I had to use the following options

```sh
minimap2 -t 1 -K 25M --no-kalloc --print-qname -aLx map-ont <target> <query>
```

Although I don't necessarily think the `--print-qname` options makes an impact on the memory footprint.

**Comment by shehongbing** [comment]
I met the same error too. I want to do a alignment between two genome. The command is following:
minimap2 -ax asm5 --cs -t 20 $ref $query > query2ref.sam

And the size of  my genome is about 960 Mb.

I do not know how to address it. Is there anyone solve it.

**Comment by xiekunwhy** [comment]
I met the same error too, when doing self mapping, the size of genome is 850M.

/minimap2 -t 4 -x asm5 -o Bupleurum_chinense.Bupleurum_chinense.paf Bupleurum_chinense.genome.fa Bupleurum_chinense.genome.fa

Best,
Kun

**Comment by lucyintheskyzzz** [comment]
I was getting this error: "slurmstepd: error: Detected 102 oom_kill events in StepId=14937.batch. Some of the step tasks have been OOM Killed. "

until I bumped my memory up to 200G, but now minimap2 is running slow at producing the fastq file from the sam file. Is there anyway to speed it up? 

For my project I am trying to align all my blank reads as the reference to my environmental samples, then saving an updated environmental .fastq file without the blank reads. 

Minimap2 was able to create the .sam files fast, but is there any recommentation on the sam --> fastq time? It seems like this is taking a long time. 



Below is my code:

#!/bin/bash
#SBATCH --job-name=blankfilter_onr.test
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=4
#SBATCH --mem=200G  # Adjust this based on available resources and your system's capabilities
#SBATCH --time=7-00:00:00
#SBATCH --output=slurm-%j.out-%N
#SBATCH --error=slurm-%j.err-%N
#SBATCH -A loni_admintest0    ### Allocation name
#SBATCH --partition=single           # the partition

# Path to minimap2 executable
MINIMAP2=/work/kvigil/Programs/minimap2/minimap2

# Path to your blank fastq files directory
BLANK_DIR=/ddnB/work/kvigil/onr.raw.data.sup.trim/rawdata/results/trimmed

# Path to your environmental fastq files directory
ENVIRONMENTAL_DIR=/ddnB/work/kvigil/onr.raw.data.sup.trim/rawdata/results/trimmed

# Path to store index reference file
INDEX_REF=/ddnB/work/kvigil/onr.raw.data.sup.trim/rawdata/index_reference

# Path to store aligned sam files
ALIGNED_SAM_DIR=/ddnB/work/kvigil/onr.raw.data.sup.trim/rawdata/aligned_sam/

# Path to store new fastq.gz files without sequences aligned with blank
NEW_FASTQ_DIR=/ddnB/work/kvigil/onr.raw.data.sup.trim/rawdata/minimap2_fastq/

# Path to store temporary files
TMP_DIR=/ddnB/work/kvigil/onr.raw.data.sup.trim/rawdata/tmp

# Path to store minimap2 log files
LOG_DIR=/ddnB/work/kvigil/onr.raw.data.sup.trim/rawdata/logs

# Create necessary directories if they don't exist
mkdir -p $ALIGNED_SAM_DIR $NEW_FASTQ_DIR $TMP_DIR $LOG_DIR

# Print the directory content for debugging
echo "Listing contents of the blank directory:"
ls -l $BLANK_DIR

# Checkpoint 1: Check if index reference file exists
if [ ! -f "${INDEX_REF}.idx" ]; then
    echo "Creating index reference file..."
    $MINIMAP2 -d $INDEX_REF --split-prefix $INDEX_REF.idx $BLANK_DIR/blanks_concatenated.fastq 2> $LOG_DIR/index_reference.log
    if [ $? -ne 0 ]; then
        echo "Error: Failed to create index reference file. Check $LOG_DIR/index_reference.log for details."
        exit 1
    fi
else
    echo "Index reference file already exists."
fi

# Checkpoint 2: Check if aligned sam files exist
if [ ! -f "${ALIGNED_SAM_DIR}merged_aligned.sam" ]; then
    echo "Aligning environmental fastq.gz files..."
    for file in $ENVIRONMENTAL_DIR/*.fastq; do
        filename=$(basename "$file" .fastq)
        $MINIMAP2 -a $INDEX_REF $file > "${ALIGNED_SAM_DIR}${filename}_aligned.sam" 2> "${LOG_DIR}${filename}_alignment.log"
        if [ $? -ne 0 ]; then
            echo "Error: Alignment failed for $file. Check ${LOG_DIR}${filename}_alignment.log for details."
            exit 1
        fi
    done

    echo "Combining aligned sam files..."
    cat ${ALIGNED_SAM_DIR}*_aligned.sam > ${ALIGNED_SAM_DIR}merged_aligned.sam
else
    echo "Aligned sam files already exist."
fi

# Checkpoint 3: Check if new fastq.gz files without blank exist
if [ ! -f "${NEW_FASTQ_DIR}merged_without_blank.fastq" ]; then
    echo "Extracting read IDs aligned with blank..."
    awk '{if($3=="*")print$1}' ${ALIGNED_SAM_DIR}merged_aligned.sam > ${ALIGNED_SAM_DIR}aligned_with_blank.txt

    echo "Excluding sequences aligned with blank from environmental fastq.gz files..."
    for file in $ENVIRONMENTAL_DIR/*.fastq; do
        filename=$(basename "$file" .fastq)
        grep -Fvf ${ALIGNED_SAM_DIR}aligned_with_blank.txt $file > "${NEW_FASTQ_DIR}${filename}_without_blank.fastq"
    done

    echo "Combining new fastq files into a single file..."
    cat ${NEW_FASTQ_DIR}*_without_blank.fastq > ${NEW_FASTQ_DIR}merged_without_blank.fastq

    echo "Compressing the new combined fastq file..."
    gzip ${NEW_FASTQ_DIR}merged_without_blank.fastq

    echo "Cleaning up temporary files..."
    rm ${ALIGNED_SAM_DIR}merged_aligned.sam ${ALIGNED_SAM_DIR}aligned_with_blank.txt
else
    echo "New fastq files without blank already exist."
fi

# Verification step: Ensure blank sequences are excluded
echo "Verifying exclusion of blank sequences..."
verification_log="${NEW_FASTQ_DIR}verification_log.txt"
touch $verification_log

for file in ${NEW_FASTQ_DIR}*_without_blank.fastq; do
    grep -F "$(cat ${ALIGNED_SAM_DIR}aligned_with_blank.txt)" $file > ${TMP_DIR}sequences_from_blank.txt

    if [ -s ${TMP_DIR}sequences_from_blank.txt ]; then
        echo "Error: Sequences from blank found in $file" >> $verification_log
    else
        echo "No sequences from blank found in $file" >> $verification_log
    fi
done

echo "Verification log:"
cat $verification_log

echo "Script completed successfully."
