### ISSUE TITLE
Same line in the Sam result of minimmap2

### ISSUE THREAD

**Issue by huandna** [lh3/minimap2#507]
Hi
When I used minimap2(v2.17) to align transcript sequences from pacbio to the human reference genome,I found that there are some exactly record in the sam file：
code is as follows：
```
minimap2 -ax splice:hq -uf -t $NPROC $refgenome $fq > full.sam
samtools view -bS full.sam > full.bam
samtools sort -@ $NPROC full.bam > full.sorted.bam
samtools index full.sorted.bam
```
For I want to get unique record for each transcript sequences ,I  used the code to delete the UNMAP,SECONDARY,SUPPLEMENTARY 
`samtools flags -F 0x904 ./full.sorted.bam > full.sam2`
statistics of duplication
```
awk '{print $1}' ./full.sam2 | sort | uniq -c | sort -nrk 1,1 > dup_full
head dup_full
```
>       2  m64048_190717_101331/112461545/ccs_646_2220
>       2  m64048_190717_101331/112461545/ccs_2327_3143
>       2  m64048_190717_101331/112461535/ccs_67_928
>       2  m64048_190717_101331/112461535/ccs_3250_4035
>       2  m64048_190717_101331/112461535/ccs_1015_2119
>       2  m64048_190717_101331/112461534/ccs_3051_3884
`$ grep -n "m64048_190717_101331/112461545/ccs_646_2220" ./full.sam2`

> 1306960:m64048_190717_101331/112461545/ccs_646_2220     0       15      42273596        60      1S234M568N113M1837N63M2071N109M2326N217M2477N806M2S     *       0     0GATCCTGTTGGAACCTGGTCAGCTGGGTTAGAGAGATCGCTACATGCCAGCCTGGCCTGAGTCTTTTCTGTCTCCCAGCCGTTAAAGGTTTTAGGACCAGGCAGGCACCCCGTGCAGGATTTGGCTCTCTACTTCCGCTCGCCCCAGCCCTTCATCCCTTCTAAGTCAATGTCAGACTTTGGGGCCAGAAAGTCTGGAAAAGCCCTAAGCCTGGCTGCCCAAGTGGCGTCTAGTAAAAGACACCCAATCGGCTTTTTTAAAAGATCGCCCAGGGCCCTTGTCCTGAGAGCTGGGAGCTGGTCGGAGTGACAGAGAAGCCATGGAAGCAGCAGTGAAAGAGGAAATAAGTGTTGAAGATGAAGCTGTAGATAAAAACATTTTCAGAGACTGTAACAAGATCGCATTTTACAGGCGTCAGAAACAGTGGCTTTCCAAGAAGTCCACCTATCAGGCATTATTGGATTCAGTCACAACAGATGAAGACAGCACCAGGTTCCAAATCATCAATGAAGCAAGTAAGGTCAGGTGCCAGGACCAGAGCCCAACAACTCTGGATGCCTTCAAAGGCAAAGAAACCACAGTCCAGGAGGAGACACAGGATCTCAGCACAAGACAGCACCTGGCTCAAAAGGAAGCTGAGGAGCCTGATAAACAAGGACAAATTACCTGGGACATCAGCAACGTAGCTCCCAAGACTGAGAACTTTGAGGACCTCTTGGAACAAACTCCATGCTCAGCCTGTTTGCAAGGTTTCACCAGAGACAACACTTCCAGCAGCTTCTCCGAGGATGCAGGAATATCTCTGAGCACCTCTGTGAAGTTACCCCTTGCCTCTTCATCTAAGCCTAATGAAAATGAAGCTTTGCCCAACCAGCCACCTTCTCAGCAGATGAGGCACAACTACCGCTTATTAGCCAGTACTGTGTCTGCAGAAATGGCCAGGAACAGGCAGCTAATTTGGGAACTGGCCAGACAATCAGAAGCACACCTGGACAGGCCAGTTGTCCTTGGGGAACAGGCCAGTGCCCAGCGTGAGGTTGCCAGTATTCTTTGTAGAAAATCAGTGCTTGCAATAAACCAACTGGCTGCAACTGTAGAAGGGACAATTAGTGTCCTACAGCAATTTAATGAACTATTAGACCATCCTCTGGATCCCGGGAGGTCTTGATCACAGCTGGTAGAGGTGGCCACTCACTGTTCTATGTCTTTTAGGTTAACAGTTCTTTACATAACAGTGAAGAGTCCTGGTGCCTCAGGAAAAGCAAGATCAACCTACCAAGGAAGAGTTGATGGAGTCATAATTTTCCTACTTAACACCCACTGCAAATTTAAATATGTGTTCTAGGGCTGTTTGTTAATTCTATTATGGTCTTTACTAATTGTGATTCCCAGTTCTGGGTGAATAAAAAGTTTTTGTTTTAATGTAATTGTGATCAACACTATGCTTGAAGACATAGACAAAGCTATTTCTACCACCATGATGTTTACAAAATATCTGGTATTTTCGCCTATATAGCCATTAAAAAAACTAGATTTGTGGATAGC      *       NM:i:3  ms:i:1527       AS:i:1407       nn:i:0  ts:A:+  tp:A:P  cm:i:483        s1:i:1463       s2:i:0  de:f:0.0019    rl:i:0
> 1306961:m64048_190717_101331/112461545/ccs_646_2220     0       15      42273596        60      1S234M568N113M1837N63M2071N109M2326N217M2477N806M2S     *       0     0GATCCTGTTGGAACCTGGTCAGCTGGGTTAGAGAGATCGCTACATGCCAGCCTGGCCTGAGTCTTTTCTGTCTCCCAGCCGTTAAAGGTTTTAGGACCAGGCAGGCACCCCGTGCAGGATTTGGCTCTCTACTTCCGCTCGCCCCAGCCCTTCATCCCTTCTAAGTCAATGTCAGACTTTGGGGCCAGAAAGTCTGGAAAAGCCCTAAGCCTGGCTGCCCAAGTGGCGTCTAGTAAAAGACACCCAATCGGCTTTTTTAAAAGATCGCCCAGGGCCCTTGTCCTGAGAGCTGGGAGCTGGTCGGAGTGACAGAGAAGCCATGGAAGCAGCAGTGAAAGAGGAAATAAGTGTTGAAGATGAAGCTGTAGATAAAAACATTTTCAGAGACTGTAACAAGATCGCATTTTACAGGCGTCAGAAACAGTGGCTTTCCAAGAAGTCCACCTATCAGGCATTATTGGATTCAGTCACAACAGATGAAGACAGCACCAGGTTCCAAATCATCAATGAAGCAAGTAAGGTCAGGTGCCAGGACCAGAGCCCAACAACTCTGGATGCCTTCAAAGGCAAAGAAACCACAGTCCAGGAGGAGACACAGGATCTCAGCACAAGACAGCACCTGGCTCAAAAGGAAGCTGAGGAGCCTGATAAACAAGGACAAATTACCTGGGACATCAGCAACGTAGCTCCCAAGACTGAGAACTTTGAGGACCTCTTGGAACAAACTCCATGCTCAGCCTGTTTGCAAGGTTTCACCAGAGACAACACTTCCAGCAGCTTCTCCGAGGATGCAGGAATATCTCTGAGCACCTCTGTGAAGTTACCCCTTGCCTCTTCATCTAAGCCTAATGAAAATGAAGCTTTGCCCAACCAGCCACCTTCTCAGCAGATGAGGCACAACTACCGCTTATTAGCCAGTACTGTGTCTGCAGAAATGGCCAGGAACAGGCAGCTAATTTGGGAACTGGCCAGACAATCAGAAGCACACCTGGACAGGCCAGTTGTCCTTGGGGAACAGGCCAGTGCCCAGCGTGAGGTTGCCAGTATTCTTTGTAGAAAATCAGTGCTTGCAATAAACCAACTGGCTGCAACTGTAGAAGGGACAATTAGTGTCCTACAGCAATTTAATGAACTATTAGACCATCCTCTGGATCCCGGGAGGTCTTGATCACAGCTGGTAGAGGTGGCCACTCACTGTTCTATGTCTTTTAGGTTAACAGTTCTTTACATAACAGTGAAGAGTCCTGGTGCCTCAGGAAAAGCAAGATCAACCTACCAAGGAAGAGTTGATGGAGTCATAATTTTCCTACTTAACACCCACTGCAAATTTAAATATGTGTTCTAGGGCTGTTTGTTAATTCTATTATGGTCTTTACTAATTGTGATTCCCAGTTCTGGGTGAATAAAAAGTTTTTGTTTTAATGTAATTGTGATCAACACTATGCTTGAAGACATAGACAAAGCTATTTCTACCACCATGATGTTTACAAAATATCTGGTATTTTCGCCTATATAGCCATTAAAAAAACTAGATTTGTGGATAGC      *       NM:i:3  ms:i:1527       AS:i:1407       nn:i:0  ts:A:+  tp:A:P  cm:i:483        s1:i:1463       s2:i:0  de:f:0.0019    rl:i:0

The ratio of duplicate records to all records is   516/4373842, I want to know why some records appear twice.Could you please recommend something to fix this issue ?

**Comment by lh3** [comment]
Could you reproduce it with a small file? And have you checked if your input file has identical records?

**Comment by huandna** [comment]
Sorry,I rechecked the raw fasta file and found there are duplicate IDs  in it, Thank you for your reminding
