### ISSUE TITLE
Can I get the "original" MAPQ of non-unique alignments?

### ISSUE THREAD

**Issue by soungalo** [lh3/minimap2#509]
Hello,
Might be a bit of a strange question, but I was wondering...
Non-unique alignments get a MAPQ of 0. Is there a way for me to get the MAPQ of such alignments **had they not been non-unique**? That is, ignore the fact that there are several possible mappings, and output the relevant MAPQ to some field, so the MAPQ field would still say 0, but the other field would say e.g. 25.
I am aware of the AS tag - is there a way to derive the MAPQ from it?
Thanks!

**Comment by lh3** [comment]
There is no such MAPQ.
