### ISSUE TITLE
pysam aligned length after aligning with -L

### ISSUE THREAD

**Issue by wdecoster** [lh3/minimap2#51]
This issue is maybe more appropriate at the pysam repo, but I'm not sure.

I noticed that after aligning reads with the -L option for ultra long reads the aligned read length (read.query_alignment_length) in pysam is 0 for some of those ultra-long reads since it uses the CIGAR to determine the aligned read length. I encounter the issue for 3 reads in the ultra long [e.coli dataset from Josh Quick and Nick Loman](http://lab.loman.net/2017/03/09/ultrareads-for-nanopore/). 

The (clipped) cigar strings are 744361S, 760365S and 408232S derived from reads with 744432bp, 760436bp and 408303bp. This is probably a corner case, but sufficient to crash a script I wrote due to a division by zero error. Due to the very short alignment, I'm inclined to drop this read entirely from the dataset but that's a drastic solution tailored to this scripts.

What would be the recommended workaround here to get the aligned read length, without using the CIGAR?

Is the -L solution for long CIGARs temporary until the bam format is adapted? If so, perhaps no changes have to be made to pysam.

Cheers,
Wouter

**Comment by lh3** [comment]
`-L` just lets these older tools to ignore these three reads without abruptly aborting. It can't magically make them work with ultra-long reads. Nonetheless, future tools including pysam will recognize the `-L` output you are having now.
