### ISSUE TITLE
How to reserve the best alignment record of each read into sam file?

### ISSUE THREAD

**Issue by weir12** [lh3/minimap2#511]
Hi:
  I wanted direct RNA reads to be aligned to the transcriptome, with only the best alignment record for each read.I have set `--secondary=no`  and  deliberately disabled `--splice` due to I want to get the alignment of the full read, not the fragments.
  Are these Settings effective enough?

**Comment by lh3** [comment]
> Are these Settings effective enough?

Most of time, but when there are chimeric alignments (check the SAM spec), you will still see multiple records.
