### ISSUE TITLE
Impact of the -I (index size) parameter on the results

### ISSUE THREAD

**Issue by morispi** [lh3/minimap2#514]
Hello,

I am currently using minimap2 in my long read self-correction tool.
With default parameters, it tends to use quite a lot of memory on relatively large datasets (about 30Go for a 30x coverage of chr1 human genome reads).

To overcome that, I modified the -I option, to load less bases into memory, and thus perform mapping on several distinct batches. This part actually works pretty well, memory consumption drastically drops, and runtime is barely affected.

However, I get highly different mapping results when fixing, say, -I 1G, instead of the default -I 4G. Using the -I 1G option indeed results in way more mappings, and thus in a much, much larger PAF output file.

Now, the problem is that this much larger PAF file obviously makes my correction step much slower, and unfortunately does not improve the results nor allows to correct more reads.

I'd thus like to know if there is any way to get similar mapping results, regardless of the -I value used?

I believe modifying the minimizer parameters, or maybe setting a max number of overlaps for each batch could maybe work out? But I don't really know where to go from that, nor which parameters to tune.

Thank you very much.

Regards,
Pierre

**Comment by tseemann** [comment]
What are all the extra mappings that occur when you use `-I 1G` compared to `-I 4G` ?
Can you post-filter (possibly in a pipe) ?

**Comment by morispi** [comment]
Hi,

Not sure what you mean by "what" are those extra mappings exactly? Minimap2 just basically finds more overlaps for each read.

I can post-filter obviously, yes, but I'm not sure about which mappings to keep and which to drop. Trying to only keep those having the highest "number of residue matches" (column 10) didn't help much. I also tried to fool around with the other columns a bit, but I couldn't seem to find any very satisfying filter.

I don't use the mapping quality field though, as I only perform overlapping, and not alignment. So I don't think it being incorrect is an issue.

Pierre

**Comment by tseemann** [comment]
You stated

> the -I 1G option indeed results in way more mappings

So I assumed the `-l 4G` gave N mappings, and `-l 1G` gave M >> N mappings.
If you sort `1G.paf` and `4G.paf` and run `diff 4G.paf 1G.paf` you can see what the "extra" mappings you are getting are?

**Comment by colinbrislawn** [comment]
I'm also having this issue!

For me, `-I 4G` gave 28.6 million mappings,
while `-I 12G` gave 19.8 million mappings,
and I queried 9 million mappings. 

Is there an elegant way to get 1 mapping per read? Thanks!

**Comment by lh3** [comment]
I thought you were doing read overlapping. For reference mapping, use `--split-prefix`.
