### ISSUE TITLE
choosing k-mer length and index size during indexing

### ISSUE THREAD

**Issue by sandipmkale** [lh3/minimap2#515]
Hello,
I have a very big genome of 15G size and would like to use it for mapping 150 bp PE reads. I wanted to index it before. 
when I used -k 31 and -I 50G, I got following  error:
minimap2: sketch.c:84: mm_sketch: Assertion `len > 0 && (w > 0 && w < 256) && (k > 0 && k <= 28)' failed.
Aborted
Please help to select optimum parameters.

Thanks and regards

Sandip

**Comment by tseemann** [comment]
The error says that only `k` values up to 28 are supported.
The `--help` also says `    -k INT       k-mer size (no larger than 28) [15]`
Try `-k 28` ?

**Comment by lh3** [comment]
As @tseemann said (thank you!)
