### ISSUE TITLE
RNA seq alignment

### ISSUE THREAD

**Issue by valery-shap** [lh3/minimap2#519]
Hello,

I have rna-based(with U) reads from Nanopore kit RNA002(direct rna) after default Guppy basecalling.
I'd like to align these reads to the human transcriptome(there is no U bases). Should I convert my reads? 
I didn't find any information about this and if smb converted reads before alignment. Maybe I'm doing smth wrong.

A lot of thanks.

**Comment by lh3** [comment]
See #33.

**Comment by valery-shap** [comment]
Thank you very much for the answer. Sorry for missing this post.
