### ISSUE TITLE
chromosome extraction through the python API

### ISSUE THREAD

**Issue by lappazos** [lh3/minimap2#520]
Hi, i'm interested to detect on which chromosome each of the sequences is located. is there an easy way to know it be the r_st and r_en?

**Comment by lh3** [comment]
Not sure which part of the code you are referring to.

**Comment by lappazos** [comment]
python mappy.Alignment - how can i use that object to understand which chromosome the query belongs to, and where exactly?

**Comment by lh3** [comment]
`ctg`. Please be specific next time. Thanks.

**Comment by lappazos** [comment]
ctg gives me output in the format ''NC_000004.12'
How can i get the chromosome?

**Comment by lappazos** [comment]
?
