### ISSUE TITLE
Mapping Illumina sr on Closely related species

### ISSUE THREAD

**Issue by francicco** [lh3/minimap2#521]
Hi,

I was wondering is there's a good way to align Illumina reads on a closely related genome.

Thanks
F

**Comment by tseemann** [comment]
For short reads, `bwa mem` is still preferred.
But `minimap2 -x sr -a | samtools sort > reads.bam` will do it too.
```
    -x STR       preset (always applied before other options; see minimap2.1 for details) []
                 - map-pb/map-ont: PacBio/Nanopore vs reference mapping
                 - ava-pb/ava-ont: PacBio/Nanopore read overlap
                 - asm5/asm10/asm20: asm-to-ref mapping, for ~0.1/1/5% sequence divergence
                 - splice: long-read spliced alignment
                 - sr: genomic short-read mapping
```

**Comment by francicco** [comment]
Hi,

I'm aware of that, I was thinking to a way to reduce the stringency in the alignment and overcome the nucleotide diversity among the two species. What if I reduce the -B flag and take only the properly pared reads? Would it introduce a lot of false mapping?

Thanks a lot
F

**Comment by tseemann** [comment]
If you are aligning to a closely related genome, don't you want to _increase_ stringency? 
ie. be more strict, allow less mappings.

**Comment by francicco** [comment]
I want to me more relaxed in order to deal with SNPs, right?
Best
F

**Comment by lh3** [comment]
Please define "closely related". What's the sequence divergence?

**Comment by francicco** [comment]
Between 5% and 20%. Can't be more precise since I don't have data to
correctly measure it. The divergent time is something around 10 million
years
Thanks
F

**Comment by lh3** [comment]
Minimap2 won't work well in this case unfortunately. There are short-read mappers designed for diverged sequences, though I forget their names.

**Comment by lh3** [comment]
Stampy is one of the mappers designed for high divergence.

**Comment by francicco** [comment]
I tried stampy, apart from being extremely slow, days, It's not mapping
more that minimap2 with default setting.
There are any problem if I use minimap with a low value of -B and filter
for properly mapped reads?

Thanks a lot
F

**Comment by lh3** [comment]
If you want to give minimap2 a try anyway, you can use the following setting:
```sh
minimap2 -axsr -A2 -B4 -O4,24 -E2,1
```
If minimap2 is not sensitive enough, reduce `-k` and `-w` at the cost of mapping speed. Reducing `-w` should have relatively lower impact of speed, but reducing `-k` should be more sensitive.

**Comment by francicco** [comment]
Thank you very much!!!
F

**Comment by francicco** [comment]
>
>
> If you want to give minimap2 a try anyway, you can use the following
> setting:
>
> minimap2 -axsr -A2 -B4 -O4,24 -E2,1
>
> These look like the default, don't they?
F

**Comment by francicco** [comment]
If I use:

minimap2 -ax sr -A2 -B1 -O4,24 -E2,1 -k10 -w8

I can increase of 13% the properly mapped read compared to the default
settings

minimap2 -ax sr -A2 -B4 -O4,24 -E2,1 -k15 -w10

Am I doing anything wrong here?
Thanks
F

**Comment by tseemann** [comment]
> Am I doing anything wrong here?

You are just allowing more and more differences to be accepted as an alignment.
But given you think they are ` properly mapped` then it is fine?
It ultimately comes down to what you think is "related" for your purposes.
