### ISSUE TITLE
Computing all-against-all mappings for N genomes

### ISSUE THREAD

**Issue by iminkin** [lh3/minimap2#522]
Hi,

Suppose that I have N long genomes (e.g. primates) and want to compute mappings between all pairs of the genomes. What is the best way to do so using minimap2? For example, is it a good idea to cat everything into a single FASTA file and then align it against itself, or it is the best to run the comparisons separately? And how would one adjust the parameters in such a case?

**Comment by lh3** [comment]
If you have whole-genome assemblies, do the comparisons separately.

**Comment by lh3** [comment]
Missing this part:

> then align it against itself

Normally you will only get boring alignments when aligning a sequence to itself. Please check #106.
