### ISSUE TITLE
Report Time Per Read

### ISSUE THREAD

**Issue by Mosjava** [lh3/minimap2#523]
Hi,

I want to perform performance analyses on minimap2. Is there any way (any arguments) that I can see the processing time of each read? for instance, in an optional field (tag) in the .SAM file.

Thanks

**Comment by lh3** [comment]
Unfortunately, not possible.

**Comment by Mosjava** [comment]
Can I add this feature? Where should I start from (which file)?

**Comment by lh3** [comment]
I only add a feature when it is needed by many users. I wouldn't add this feature. Sorry.
