### ISSUE TITLE
Deletion at the end of cigar

### ISSUE THREAD

**Issue by ebioman** [lh3/minimap2#524]
I encountered a strange results which I believe might be a bug in the cigar generation.

Aligning a cDNA sequence against 2 targets which is supposed to give a fusion transcript results as expected in a primary alignment with a supplementary one in the `SA` string.
The supplementary alignment has though at the end a deletion added which I cant explain:

NODE_1_length_906_cov_22.883314_g0_i0   16      CHS.55128.33    2810    60      427M479S        *       0       0       TGGAAGGGGATGAGCACATTCACAGCGAAGTGAGTGAAAAAGTCCTGATGAATAGTGAGAGGCCTGATGAGAACCACAGTGAGCCCTCTCACCAGGACGTCATCAAGGTGAAGGAAGAATTTACAGACCCCACTTACGACATGTTTTACATGAGCCAGTATGGACTGTACAATGGTGGGGGTGCCAGCATGGCCGCCTTGCATGAGAGCTTTACATCGTCTCTGAATTATGGCAGCCCTCAAAAGTTCTCCCCAGAAGGTGACCTATGTTCTAGCCCAGACCCCAAAATCTGTTATGTGTGCAAGAAGAGTTTCAAAAGCTCCTACAGTGTGAAACTTCACTACAGGAACGTTCACTTGAAAGAGATGCACGTCTGCACAGTGGCTGGTTGCAATGCTGCATTCCCCTCTCGCCGAAGCCGAGACAGGTACCTGGTCCCTGAGCGCGGGCCTGAGCGAGGCCTGGGCAGCAAGTCCCTGCGCGCCTTCGTGGGGGAGGTGGGTGCCCGCTCTGCGGCCCCCGGGGGCGGCTCGGTGGCGGCGGCCGCTGCGGCCATGGGTGCGGCGCTGGGCTCCATGGTGGGCCTCATGACCTACGGGCGGCGCCAATTCCAGTCCCTGGACACGACGATGCGGCGCCTGATCCCGCCCTTCCGCGAGGCTTCGGCCAAGCTAACCACGCTGGTGGATGCCGACGCCGAGGCCTTCACCGCCTACCTGGCGCACGGCGGCCCTACAGGAGGGTCTGAGGCGGGCAGTCTCTGTGCCGCTGACGCTGGCGGAGACGGTGGCCTCGCTGTGGCCGGCCCTGCAGGAACTGGCCCGGTGTGGGAACCTGGCCTGCCGGTCAGACCTCCAGGTGGCGGCCAAAGCCCTGGAGATGGGCGTGTTTGGCGCATATTTCAAC  *       NM:i:0  ms:i:427  AS:i:427 nn:i:0  tp:A:P  cm:i:80 s1:i:415        s2:i:0  de:f:0  SA:Z:CHS.35042.9,1311,-,427S479M44D,60,44;      cs:Z::427       rl:i:0

So the cigar is `427S479M44D` which is really bizarre with the 44 Deletions at the end.
The complementary alignment is

NODE_1_length_906_cov_22.883314_g0_i0   2064    CHS.35042.9     1311    60      427H291M44D188M *       0       0       GTACCTGGTCCCTGAGCGCGGGCCTGAGCGAGGCCTGGGCAGCAAGTCCCTGCGCGCCTTCGTGGGGGAGGTGGGTGCCCGCTCTGCGGCCCCCGGGGGCGGCTCGGTGGCGGCGGCCGCTGCGGCCATGGGTGCGGCGCTGGGCTCCATGGTGGGCCTCATGACCTACGGGCGGCGCCAATTCCAGTCCCTGGACACGACGATGCGGCGCCTGATCCCGCCCTTCCGCGAGGCTTCGGCCAAGCTAACCACGCTGGTGGATGCCGACGCCGAGGCCTTCACCGCCTACCTGGCGCACGGCGGCCCTACAGGAGGGTCTGAGGCGGGCAGTCTCTGTGCCGCTGACGCTGGCGGAGACGGTGGCCTCGCTGTGGCCGGCCCTGCAGGAACTGGCCCGGTGTGGGAACCTGGCCTGCCGGTCAGACCTCCAGGTGGCGGCCAAAGCCCTGGAGATGGGCGTGTTTGGCGCATATTTCAAC       *       NM:i:44 ms:i:308  AS:i:354 nn:i:0  tp:A:P  cm:i:45 s1:i:413        s2:i:0  de:f:0.0021     SA:Z:CHS.55128.33,2810,-,427M479S,60,0; rl:i:0

Here, the deletion seems to be not towards the edge but internal. I guess it might be a bug in the reporting of supplementary alignments

I tried this with the original command I was using

```bash 
 minimap2 -ac -k19 -w10 -A1 -B19 -O39,82 -E3,1 -s30 -z200 -N1 -t 5 --min-occ-floor=100 --cs ref.fasta query.fasta
```
but as well with the  `-ax asm5` flag which both generate that pattern
I verified that the 2 reference sequences have no `N` somewhere and the version is Minimap2-2.17 (r941)

**Comment by lh3** [comment]
SA doesn't give the right CIGAR. It only intends to show the coordinate.
