### ISSUE TITLE
What is the 5-column bed format for `--junc-bed`

### ISSUE THREAD

**Issue by vkkodali** [lh3/minimap2#525]
From the manual:
```
--junc-bed FILE
  Gene annotations in the BED12 format (aka 12-column BED), or intron positions in 5-column BED.
  With this option, minimap2 prefers splicing in annotations. BED12 file can be converted from 
  GTF/GFF3 with ‘paftools.js gff2bed anno.gtf’ [].
```
What are the required fields in the 5-column BED? Could somone please give an example?

**Comment by lh3** [comment]
Actually this is a typo. It should be 6-column BED. It is just the first 6 column of BED12. The name and the score columns (4th and 5th) are ignored. Minimap2 needs the strand from the 6th column.

**Comment by vkkodali** [comment]
Thank you. 
Just to confirm, in the 6-column BED file, each row represents a single intron feature, right? 

Does it matter if the BED file has introns for chromosomes that are not present in the index? Say, can I create a single BED file with all known introns for human and mouse and use it with indexes generated for human or mouse?
