### ISSUE TITLE
multi-part indices / unknown reference size / samtools 1.10

### ISSUE THREAD

**Issue by wwood** [lh3/minimap2#527]
Hi there,

I'm using minimap2 as part of a metagenomics coverage calculation tool ([CoverM](https://github.com/wwood/CoverM), to be concrete).

The tool takes a reference fasta and reads, and outputs coverage, using minimap2 to do the mapping. The issue is that because the target fasta is of unknown size (and may even be streamed), `--split-prefix` must always specified. Unfortunately, as in #400 `@SQ` lines are duplicated when the number of bases is less than 4G. Piping `minimap2 -a` to `samtools sort` worked previously, but as of 1.10 samtools now croaks because duplicate sequence names are encountered.

Assuming I'm understanding correctly and there's no other workarounds, would it be possible to not output the duplicated `@SQ` lines when `--split-prefix` is specified with a small target fasta please?

Thanks in advance. ben

**Comment by lh3** [comment]
Added in 24f50f3.

**Comment by wwood** [comment]
I'll wait for a release to test it but thanks for addressing this.
