### ISSUE TITLE
Uniquely mapped reads

### ISSUE THREAD

**Issue by juheon** [lh3/minimap2#528]
I am aligning human ISO-seq to hg38 using "minimap2 -ax splice --secondary=no -C5 --MD -uf -t [thread] [hg38] [fastq]"

Could I extract uniquely mapped reads?

With the "--secondary=no", minimap2 returns only primary alignment of which some are multimappers. 

To extract uniquely mapped reads, I tried using MAPQ=60 but it seemed inappropriate according to https://github.com/lh3/minimap2/issues/447 and https://github.com/lh3/minimap2/issues/223.
As far as I understand, MAPQ=0 is multimappers. MAP=1~60 is either uniquely mapped reads or multimappers. Is it correct?

Another alternative is "s2" tag. Does "s2:i:0" indicate "uniquely mapped reads"?

**Comment by lh3** [comment]
Use MAPQ.

**Comment by HYsxe** [comment]
Hi! This is very helpful! Is MAPQ >= 1 a good threshold to filter out multi-mapper reads? Thank you!

**Comment by juheon** [comment]
@HYsxe That is what I used for my project. 
For a given read, minimap2 finds multiple candidates of genomic loci.
MAPQ>0 indicates that minimap2 concludes one genomic locus has a better alignment score than its second best genomic locus. MAPQ=0 means that there are two genomic loci with the same alignment score.
