### ISSUE TITLE
minimap2 completely freezes server

### ISSUE THREAD

**Issue by michaeljmetzger** [lh3/minimap2#529]
I ran minimap2 as a precursor to purge_haplotigs (https://bitbucket.org/mroachawri/purge_haplotigs/src/master/).

I installed through: 
conda install -c bioconda -c conda-forge purge_haplotigs
And when I ran the following command, it ran for a few minutes, then froze up the entire server to the point that it had to be manually shut down and restarted. 

minimap2 -t 16 -ax map-pb ~/MELC-2E11/4-polish/cns-output/cns_p_ctg.fasta ~/MELC-2E11/Marenaria.3.2.fasta.gz --secondary=no | samtools sort -m 1G -o MELC-2E11-PBaligned.bam -T tmp.ali

Has anyone had a similar issue? This is not something that I can easily spend a long time troubleshooting without severely affecting a lot of people.

Thanks.

**Comment by lh3** [comment]
Make sure you have enough memory.

**Comment by michaeljmetzger** [comment]
Only using 12GB out of 256GB.

Any other ideas?

**Comment by lh3** [comment]
There are other processes running taking lots of resources. Anyway, this has nothing to do with minimap2.
