### ISSUE TITLE
mappy Python 2 vs Python 3 strings

### ISSUE THREAD

**Issue by martinghunt** [lh3/minimap2#53]
Is mappy intended for both Python2 and Python3? If so there is a bug with Python 3. It handles byte strings differently, so fastx_read is yielding strings with `b'` at the start and `'` at the end, because of the conversion using str(foo). It probably needs a foo.decode() in there instead for python 3.

This also means that when mapping, the coords are off. eg:

```
$ cat tmp.ref.fa
>ref
GACCTAGGGTAACGTATCGTCGCCCTCGCGGCCGACTCATGGGCTTGCGTACAAACTTGA
CTAACGGTCATAGTGACAGAATCATATACTTTCTGCTTAAGTGATCTAAATGCACGGTCT
ATCACAAGTGGAACGTGCCTAGGAGGATGTTTGCCGAATGAAGCTTCGAATTCAGCTATT
TATAAGTTACACACTTTTAG
$ cat tmp.read.fq
@read
AGGGTAACGTATCGTCGCCCTCGCGGCCGACTCATGGGCTTGCGTACAAACT
+
IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIGGGGH
```

Code:
```
a = mappy.Aligner('tmp.ref.fa')
for name, seq, qual in mappy.fastx_read('tmp.read.fa'):
    for hit in a.map(seq):
        print(hit)
```

Python2 output:
```0	52	+	ref	200	5	57	52	52	6	tp:A:P	ts:A:.	cg:Z:52M```

Python3 output:
```2	54	+	b'ref'	200	5	57	52	52	6	tp:A:P	ts:A:.	cg:Z:52M```

**Comment by lh3** [comment]
Mappy is intended for both python2 and python3. This `b` prefix is a bug, probably because strings are handled differently. I need the help from someone more familiar with python. I rarely use python to be honest.

**Comment by martinghunt** [comment]
OK, I'm happy to fix it. Will have a go in the next couple of days. I'm not so familiar with Python2, but will make sure whatever I do works for 2 and 3.

**Comment by lh3** [comment]
Thanks! No hurry.

**Comment by martinghunt** [comment]
Pull request #55. Thanks for the Python support - it's really useful!

**Comment by lh3** [comment]
Thanks a lot! #55 is merged now.
