### ISSUE TITLE
paf file not sorted by query 

### ISSUE THREAD

**Issue by xamiiii** [lh3/minimap2#530]
Hi!

I am using minimap2 to map nanopores with the command:
minimap2 -k15 -DP --dual=yes --no-long-join -w5 -m100 -g10000 -r2000 --max-chain-skip 25 file1.fastq file2.fastq > output.paf

I assumed that the paf file would always be sorted by query. So that the mapping hits of one query sequence on the reference are listed in one block. 
But when I use big files (reference 65 GB, query 2 GB) the hits are split in multipe blocks within the paf file. 
Is there an option to have the output sorted by query even for large input files?

Thanks in advance!
Sarah

**Comment by lh3** [comment]
You may try to add `--split-prefix=foo`.
