### ISSUE TITLE
Mapping quality in PAF file differs from that in SAM file with  the same query 

### ISSUE THREAD

**Issue by tenlives** [lh3/minimap2#531]
Hello !
       When I use a simulated sequence to align the ref. I use the command `minimap2 -ax map-pb ref.fasta query.fastq >aln.sam`  and `minimap2  -x map-pb ref.fasta query.fastq>aln.paf ` . While  the result of mapping quality in PAF file differs from that in SAM file with the same query . Could you help solve the problem ? Thank you very much!

[sequence.zip](https://github.com/lh3/minimap2/files/3958967/sequence.zip)
[maq.zip](https://github.com/lh3/minimap2/files/3958980/maq.zip)

**Comment by lh3** [comment]
See [FAQ](https://github.com/lh3/minimap2/blob/master/FAQ.md#1-alignment-different-with-option--a-or--c).

**Comment by tenlives** [comment]
> See [FAQ](https://github.com/lh3/minimap2/blob/master/FAQ.md#1-alignment-different-with-option--a-or--c).

Thank you very much !
