### ISSUE TITLE
silent failure using multi-part index with process substitution input

### ISSUE THREAD

**Issue by apregier** [lh3/minimap2#532]
I saw some surprising behavior:
minimap2 -8 -x sr large_target.fa <(generate_query_input.sh)
*target is over 4Gb, so minimap2 used a multi-part index
*I was using process substitution for the query input file `<(some_command)`
*The alignment appeared to complete successfully, but I noticed it was missing a bunch of alignments
*Looking in the logs, it aligns all sequences to the first part of the index and then generates the second part, but it doesn't align any sequences to the second part.
Just superficially looking through the code, it seems like the problem is that it tries to open the file again, which it can't do for a process substitution.  It would be nice if this caused the program to terminate with an error.  It looks like `mm_map_file` returns -1 if the file can't be opened, but the return value is never looked at anywhere.

There are plenty of workarounds (don't use process substitution, or use `-I` with a large enough value to get the whole target), but it would be nice to get an error thrown rather than thinking it is successful.

**Comment by lh3** [comment]
I now ask minimap2 to throw non-zero return code if the query file is non-existent. However, opening a closed FIFO pipe doesn't trigger an error. It is possible to detect FIFO but it will make code logic more complicated. I would rather let users deal with this. I have to decline this request. Sorry.
