### ISSUE TITLE
exit code 127, /scratch/1576751576.660534: line 8: minimap2: command not found

### ISSUE THREAD

**Issue by reutnuri** [lh3/minimap2#533]
Hi,
I used minimap2 with the following command and it was fine:
minimap2 -x ava-pb  reads.fq reads.fq > ovlp.paf
When trying to run in the following format: 
./minimap2 -ax splice:hq -uf ref.fa query.fa > aln.sam 

I got an exit code 127, and "/scratch/1576751576.660534: line 8: minimap2: command not found" 
I will appreciate any help!

**Comment by lh3** [comment]
If you use `./minimap2`, please make sure the minimap2 executable is in the current directory.
