### ISSUE TITLE
Why traditional full-length cDNA is recommanded to apply -uf

### ISSUE THREAD

**Issue by zhenLiuExplr** [lh3/minimap2#534]
Hi Heng

I have a question about the *"Map long mRNA/cDNA reads"* section in README.md. Why traditional full-length cDNA is recommanded to use `-uf` and force minimap2 to consider the forward transcript strand only? As traditional cDNA sequencing is usually strand-unspecific, is it more suitable to use `-ub` here?

**Comment by lh3** [comment]
You know the strand when you do full-length cDNA sequencing.
