### ISSUE TITLE
ts:A tag not present for all alignments

### ISSUE THREAD

**Issue by vkkodali** [lh3/minimap2#535]
I understand that the `ts:A:` tag indicates the transcript strand but I noticed that it is not present for all of the alignments in a SAM file. What determines whether this tag is present or not? Is there a way to force it to be present for all alignments? If not, how can I determine the reference strand to which the read aligns?

**Comment by lh3** [comment]
Minimap2 doesn't know the strand for reads not bridging splice junctions.
