### ISSUE TITLE
paftools do not call large SV

### ISSUE THREAD

**Issue by PeterWu-Biomath** [lh3/minimap2#537]
I'm using minimap and paftools to call SVs from alignments of de novo assemblies and ref genome, all with default parameters. And I found that a large deletion(~50K) is missing from VCF results. Am I using paftools in wrong way or it's not designed for large SVs?

**Comment by lh3** [comment]
It is more of a minimap2 issue. Minimap2 doesn't work well with very long INDELs.

**Comment by tmartial** [comment]
Hello,
I'm reopening this issue
I was wondering what do you mean by very long indels ? Is 9kb is a long one and would it be detected by minimap2 ?
Thank you
