### ISSUE TITLE
logic inconsistency in mm_est_err()

### ISSUE THREAD

**Issue by cjain7** [lh3/minimap2#538]
Hi,

I am experimenting with minimap2's minimizer sampling algorithm. I wish to try alternate sampling mechanism where ties (i.e., equal minimum k-mers) are handled differently from the current implementation. My modified implementation is equivalent to the `robust winnowing` idea defined in by [Schleimer et al.](https://www.cs.princeton.edu/courses/archive/spring05/cos598E/bib/p76-schleimer.pdf).

```
(ROBUST WINNOWING). In each window select the minimum hash value. If 
possible break ties by selecting the same hash as the window 
one position to the left. If not, select the rightmost minimal hash.
```

To accomplish the above, I made minor changes in the function `mm_sketch`. After these changes, the code seems to run file, and the output mappings look reasonable. The only thing I am not able to understand is the following warning 

```
[WARNING] logic inconsistency in mm_est_err(). Please contact the developer.
```

My guess is it has to do something with how minimizers are stored in the index (and their relative order), but not sure what's going on. My modifications to the function `mm_sketch` are below:

<del>if (info.x <= min.x) { // a new minimum; then write the old min</del>
if (info.x < min.x) { // a new minimum; then write the old min

and following statements have been commented out as there is no need to handle identical k-mers anymore.

~~if (l >= w + k - 1 && min.x != UINT64_MAX) { // write identical k-mers~~
~~for (j = buf_pos + 1; j < w; ++j) // these two loops make sure the output is sorted~~
~~if (min.x == buf[j].x && min.y != buf[j].y) kv_push(mm128_t, km, *p, buf[j]);~~
~~for (j = 0; j <= buf_pos; ++j)~~
~~if (min.x == buf[j].x && min.y != buf[j].y) kv_push(mm128_t, km, *p, buf[j]);~~

Here is the complete output log
```
[M::mm_idx_gen::35.289*1.29] collected minimizers
[M::mm_idx_gen::36.355*1.61] sorted minimizers
[M::main::36.355*1.61] loaded/built the index for 455 target sequence(s)
[M::mm_mapopt_update::36.355*1.61] mid_occ = 2147483647
[M::mm_idx_stat] kmer size: 19; skip: 75; is_hpc: 1; #seq: 455
[M::mm_idx_stat::36.576*1.60] distinct minimizers: 13692083 (46.63% are singletons); average occurrences: 4.106; average spacing: 57.083
[WARNING] logic inconsistency in mm_est_err(). Please contact the developer.
[WARNING] logic inconsistency in mm_est_err(). Please contact the developer.
[M::worker_pipeline::64.512*7.46] mapped 21526 sequences
[M::worker_pipeline::68.736*7.92] mapped 4782 sequences
[M::main] Version: 2.17-r954-dirty
[M::main] CMD: minimap2 -w 75 -f 0 -x map-pb -t 16 ref/hg38/hg38.fa seq/pbsim_hg38_0.2x_90/depth0.2_combined.annotated.fasta
[M::main] Real time: 68.813 sec; CPU: 544.689 sec; Peak RSS: 5.310 GB
```

Could you please suggest what might be the reason of the above warning? I believe the function `mm_est_err` is computing estimated alignment identity from the count of minimizers matched.  I'd be happy to send you the code and input data if needed.

Thanks in advance!

**Comment by cjain7** [comment]
Hi, Please ignore the above question.

I learnt that I had introduced inconsistency in the minimizer order in the first window after doing the above edits. After fixing this issue, I'm able to execute the `robust winnowing` idea without any warnings now.

**Comment by lh3** [comment]
Thank you for reporting this anyway. And sorry for the late response.

Minimap2 minimizer selection is implemented this way to make sure that we choose the same set of minimizers regardless of strand. In practice, though, the strand symmetry is probably not important.

**Comment by tiramisutes** [comment]
Hi,
What parameters can I adjust to eliminate this warning `[WARNING] logic inconsistency in mm_est_err(). Please contact the developer`?

**Comment by htianc** [comment]
> 

hi,,
I had the same issue, did you fix it?

**Comment by gunjanpandey** [comment]
I am getting the same error.
How to fix it ?

`[WARNING] logic inconsistency in mm_est_err(). Please contact the developer.`
