### ISSUE TITLE
What parameters best resmble blastn

### ISSUE THREAD

**Issue by jregalad-o** [lh3/minimap2#54]
I built a minimap2 index of the NCBI NT database. 

I have a series of metagenomic contigs I want to align against said database. Using blast (megablast), around 40% of my sequences have mappings against the nt reference. 

Using minimap2 with -x asm10, I only get ~20% contigs with mappings to my reference. 

What parameters in minimap2 would best fit this task? I've tried reducing mismatch and gap penalties without success.

**Comment by lh3** [comment]
What is the exact command line? I would use something close to the default setting like:
```sh
minimap2 -c nt.gz contigs.fa
```
Note that you need to rebuild the index as `asm10` uses different -k and -w.

Let me know what you get. Thanks.

**Comment by lh3** [comment]
PS: `asm10` uses `-k 19 -w 19`. The default uses `-k 15 -w 10`. It will be much more sensitive to divergent hits. If sensitivity is still an issue, try `-k 15 -w 5`.

**Comment by jregalad-o** [comment]
Command line was:
index building:
minimap2 -x asm10 -d nt.mmi nt.gz

mapping
minimap2 -x asm10 -t 64 -K 10G -N 25 nt.mmi contigs.fa.gz > contigs.paf

Trying with default and  -k 15 -w 5

**Comment by lh3** [comment]
Just curious: how is your experiment going? Can minimap2 achieve acceptable sensitivity?

**Comment by jregalad-o** [comment]
Hi, 
Have had some parsing problems with downstream visualization and MD tags, but so far I have had excellent results. Much faster than blast, last,lastz, and malt(http://ab.inf.uni-tuebingen.de/data/software/malt/download/welcome.html). 

In terms of mappability, results are consistent with short reads. Now I'm checking if taxonomic profiles are also the same. Will let you know asap

**Comment by lh3** [comment]
I am closing this for now. When you have more information to share, feel free to post new information here or create a new issue. I will be notified either way. Thanks!
