### ISSUE TITLE
Chaining gap cost v/s minimizer window size 

### ISSUE THREAD

**Issue by cjain7** [lh3/minimap2#540]
Hi,

I noted that the gap cost function (during chaining) depends only on the gap length, and does not use minimizer window size as its parameter. As `- w` window size parameter is exposed to users, increasing window size would increase gap costs, leading to low chaining scores. At my end, I noticed much higher fraction of unmapped reads due to this issue (e.g., when using `-w 75`), which is partly resolved if I modify the code and set gap-cost to zero. 

I've two questions:

- Is the current gap cost function tuned for default minimizer window sizes (i.e., 10 for mapping, and 5 for overlapping) ?
- Would you recommend using a different gap cost function that would charge gaps less severely with increasing window sizes?

**Comment by lh3** [comment]
I am mostly using a small window size, so haven't carefully thought about this potential issue.

There are two types of "gaps". Say we have two anchors at `(x1,y1)` and `(x2,y2)` with `x2>x1` and `y2>y1`. Let `s := min(y2-y1,x2-x1)` and `g := max(y2-y1,x2-x1)-s`. `s` is sensitive to the minimizer window size `-w`; `g` is not. The gap cost minimap2 only considers `g`, not `s`. Sparser minimizer sampling still indirectly affects local chaining (e.g. `-s` and `-n`), but I believe the effect shouldn't be very big. I haven't done any experiment myself.

**Comment by cjain7** [comment]
Thank you for the quick response, this is good to know. 

I'm still thinking about the observed issue of more unmapped reads with increasing window size, and how it (partly) got fixed at my end by removing gap penalty. Here is my explanation of why the scoring function is causing this issue:

In my experiment, I'm using hg38 reads from pbsim (10% error-rate), and it appears that insertion errors occur more frequently than deletion errors using its default CLR error profile. This is also evident from the mapping coordinates of reads on the reference. Due to this, the scoring function (explained by you above) will charge a certain gap penalty even in a correct chain, which it probably should. However, the +ve reward scores obtained by counting of matching bases will be much lower for sparse sampling vs. dense sampling.
A potential work-around for this could be to add a multiplier to _alpha_ parameter in the scoring fn, where the value of multiplier linearly increases with increasing window size.

**Comment by lh3** [comment]
> A potential work-around for this could be to add a multiplier to alpha parameter in the scoring fn, where the value of multiplier linearly increases with increasing window size.

This is what I did in minigraph. I will consider to add an option such that users can tune this parameter.

**Comment by lh3** [comment]
I have added a new option `--chain-gap-scale`. It scales the gap cost during chaining. Could you have a look and check if it is working? Thanks.

**Comment by cjain7** [comment]
Apologies for the delay. 

I just tested this new option. It helps in reducing fraction of unmapped reads with increasing window lengths. In my experiment, I'm reducing the `--chain-gap-scale` value for longer window lengths. 

Thanks!

**Comment by lh3** [comment]
Good to know. I am closing this now.
