### ISSUE TITLE
Minimap2 Termination - Continue Option

### ISSUE THREAD

**Issue by chocotwig** [lh3/minimap2#542]
Hi,

If my minimap2 job was terminated due to external reasons, is there any way to continue it from where it was left off? or to only have to re-do part of the job, rather than everything all over?

Thanks!

**Comment by lh3** [comment]
I wouldn't say impossible, but starting again is probably easier for you.

**Comment by chocotwig** [comment]
How would one resume it?

Thanks

**Comment by lh3** [comment]
No, you can't resume multi-part. Start over.
