### ISSUE TITLE
Why isn't minimap2 correctly reporting alignment ID?

### ISSUE THREAD

**Issue by chocotwig** [lh3/minimap2#545]
I used -x ava-ont to do an all-vs-all mapping of my reads.

My PAF output for a certain read is as follows:

![image](https://user-images.githubusercontent.com/52871301/72483104-bba4c480-37b4-11ea-9180-6462bc6756d9.png)

This corresponds to a %ID (no gaps align length/ with gaps align length) of around 36%. 

When I do the same mapping in geneious, I get a %ID of 77%.

![image](https://user-images.githubusercontent.com/52871301/72483012-6d8fc100-37b4-11ea-9f4c-e9b7261a700c.png)

I want to pre-filter my PAF file based on %ID mappings, but the minimap2 PAF mapping doesn't seem to reflect actual %ID. What calculation do you think is appropriate to get a reliable %ID from a PAF file, given that the blast-like ID calculation isn't seeming even come close to actual %ID?

Thanks!

**Comment by lh3** [comment]
See FAQ.

> What calculation do you think is appropriate to get a reliable %ID from a PAF file

The dv tag.

**Comment by tseemann** [comment]
No mention of `DV` tag in FAQ?
https://github.com/lh3/minimap2/blob/master/FAQ.md

**Comment by lh3** [comment]
FAQ explains the first half of the question. dv is described in man page.
