### ISSUE TITLE
different mapping with/without --split-prefix

### ISSUE THREAD

**Issue by hughcross** [lh3/minimap2#548]
I am mapping metagenomic reads against large reference of bacterial genomes (> 8,000). When I mapped without --split-prefix, it mapped about 5x as many reads as with this option. When I checked, it looked like it was mapping the same reads 5  times. I need the MD tag, so would prefer to map without --split-prefix, but do not want the same reads mapped again and again. I can add the MD tag after with samtools calmd, but it takes a long time. 

Any suggestions would be helpful

**Comment by lh3** [comment]
--split-prefix is almost always preferred.

**Comment by hughcross** [comment]
Hello again,

After comparing the mappings of a few random reads, it seems that when not using --split-prefix, it is adding up to five secondary alignments (default of -N parameter). Whereas, when using --split-prefix, it seems to only report one alignment per read (though have not checked exhaustively). I did not use the -N parameter in either case, so not sure why. The only other difference is that running the first time I used the -d option to create the index, then the second time I used that index (and --split-prefix).  Here are the commands used:

```
minimap2 -ax sr --sam-hit-only --MD -t 8 \
  myco_combined.fna.gz \
  -d all_myco.mmi \
  sample1.assembled.fastq.gz \
  > sample1_allMyco_aln1.sam


minimap2 -ax sr --sam-hit-only -t 8 \
  all_myco.mmi \
  --split-prefix temp_sam_ \
  sample1.assembled.fastq.gz \
  > sample1_allMyco_aln1wRef.sam
```

Obviously, winnowing down the reference used will make it more efficient, so not so many identical sequences across closely related genomes, but I do want good representation. 

I am mapping short reads

**Comment by hughcross** [comment]
Thank you for getting back so fast. If --split-prefix is preferred, is there any good way to add the MD tag? Should I use the -N parameter to make sure it is getting secondary alignments?

**Comment by lh3** [comment]
> If --split-prefix is preferred, is there any good way to add the MD tag?

Unfortunately, it is non-trivial to generate MD with --split-prefix. One possible solution is to run samtools calmd after bam sorting.

**Comment by hughcross** [comment]
Great. thank you!
