### ISSUE TITLE
New format for CIGAR string

### ISSUE THREAD

**Issue by sagnikbanerjee15** [lh3/minimap2#550]
Hello,

Is there any option to produce cigar strings in minimap2 in the new format which contains 'X' and '='?

Thank you.

**Comment by lh3** [comment]
--eqx. Please see the [man page](https://lh3.github.io/minimap2/minimap2.html).

**Comment by sagnikbanerjee15** [comment]
Hello,

I remapped the transcripts using --eqx but it did not produce the cigar string in extended format. Here is the command I used:

./minimap2 -ax splice --eqx <genome.fasta> <transcripts.fasta> > <output.sam>

I also checked the output.sam file and I found that minimap was run with --eqx but it did not produce alignments with mismatches, i.e. No cigar strings had 'X' or '='.

Thank you.
