### ISSUE TITLE
Cigar in extended format

### ISSUE THREAD

**Issue by sagnikbanerjee15** [lh3/minimap2#552]
Hello,

Not sure if commenting on closed issues notifies the collaborators. So I creating a new issue which is linked to #550. 

I remapped the transcripts using --eqx but it did not produce the cigar string in extended format. Here is the command I used:

./minimap2 -ax splice --eqx <genome.fasta> <transcripts.fasta> > <output.sam>

I also checked the output.sam file and I found that minimap was run with --eqx but it did not produce alignments with mismatches, i.e. No cigar strings had 'X' or '='.

Thank you.

**Comment by lh3** [comment]
You don't need to create new tickets. Please use the latest version.
