### ISSUE TITLE
filter alignments in c api

### ISSUE THREAD

**Issue by vkkodali** [lh3/minimap2#553]
The application I wrote, using the minimap2 C API, produces very different results from the minimap2 command line, producing several times more alignments on the same inputs. I need your help in figuring out why, and what I can do to get the results to be the same.

I attached some files that provide a small-scale example. When I run the command:
```
minimap2 -x splice --eqx --MD --cs -Y --sam-hit-only -G 1300000 -a -o app.align.sam ont_index.mmi reads.fa
```
it produces file `app.align.sam`, finding 6 alignments for these 99 reads. But when I run code using the C API, on the same index file and the same reads, and then convert the alignments to SAM, the result is file `api.align.sam`, with 60 alignments.

The code I use, which is modeled after [example.c](https://github.com/lh3/minimap2/blob/master/example.c), is shown below:
```
    mm_idxopt_t s_Iopt;
    mm_mapopt_t s_Mopt;

    mm_set_opt("splice", &s_Iopt, &s_Mopt);
    s_Mopt.flag |= MM_F_OUT_CS | MM_F_OUT_MD | MM_F_OUT_SAM | MM_F_CIGAR
                 | MM_F_SOFTCLIP | MM_F_EQX | MM_F_SAM_HIT_ONLY;
    mm_mapopt_max_intron_len(&s_Mopt, 1300000)

    mm_idx_reader_t *r = mm_idx_reader_open("ont_index.mmu", &s_Iopt, 0);
    mm_idx_t *mi;
    while ((mi = mm_idx_reader_read(r, 1)) != 0) {
        mm_mapopt_update(&s_Mopt, mi);
        mm_tbuf_t *tbuf = mm_tbuf_init();
        for (<iterating over reads>) {
            string query = <code to get read sequence>;
            int n_reg;
            mm_reg1_t *reg = mm_map(mi, (int)query.size(),
                                    query.c_str(), &n_reg, tbuf, &s_Mopt, 0);            
            for (int j = 0; j < n_reg; ++j) {
                <generate alignment>
            }
        }    
    }                                 
```
Looking at the SAM files, I can tell that the logic to mark certain alignments as primary vs secondary/supplementary needs to be added to my code. Presumably, after the generation of alignments, minimap2 has additional logic that will examine the alignment scores and decide which ones to keep as primary, secondary and supplementary, or throw them out entirely. Could you please guide me how such logic can be implemented?

**Comment by vkkodali** [comment]
[minimap_c.tar.gz](https://github.com/lh3/minimap2/files/4165687/minimap_c.tar.gz) contains the example files I have mentioned above.

**Comment by lh3** [comment]
Internally minimap2 generates more alignments than the outputted ones. You should control what alignments to output.

> Could you please guide me how such logic can be implemented?

Read the source code and compare yours and minimap2 output.
