### ISSUE TITLE
Assembly to assembly comparisons

### ISSUE THREAD

**Issue by psur9757** [lh3/minimap2#554]
Hello

I align my assembly (asmb.fa) against the published reference (ref.fa). My assembly is quiet fragmented. Is it possible to get a new scaffolded assembly fasta file from the sam output? I want my contigs to be put in scaffolds based on the alignment to the reference. 

```
mininmap -ax asm5 ref.fa asmb.fa > aln.sam
samtools sort aln.sam > aln.sorted.sam
```

I also tried 
```
minimap2 -c --cs 1.data/Pgt210.fa 1.data/wsr210.fa | sort -k6,6 -k8,8n | k8 /usr/local/minimap2/2.17/paftools.js call -L20000 - > var.vcf
```
from https://github.com/lh3/minimap2/issues/109 but got nothing
```
0 reference bases covered by exactly one contig
0 substitutions; ts/tv = NaN
0 1bp deletions
0 1bp insertions
0 2bp deletions
0 2bp insertions
0 [3,50) deletions
0 [3,50) insertions
0 [50,1000) deletions
0 [50,1000) insertions
0 >=1000 deletions
0 >=1000 insertions
```

The reference and my assembly are the same fungal isolate, sequenced and assembled using different techniques. There should not be very many differences.

**Comment by tseemann** [comment]
paftools only calls variants in aligned blocks longer than 50kbp by default
```
  -L INT    min alignment length to call variants [50000]
```
if your genomes re that divergent, then you won't get 50kbp alignments.
Might need to use `-x asm10` or reduce `-L`

PS. you can do `minimap2 -a  ref r1 r1 | samtools sort > out.bam` in one line.

**Comment by psur9757** [comment]
@tseemann They are supposed to be from the same fungal isolate, so they should not be divergent at all. One is just more fragmented than the other. Do you think I still need to use `-x asm10` or is there some other issue causing me to get nothing?

**Comment by lh3** [comment]
> sequenced and assembled using different techniques

paftools only works with high-quality long-read assembly.
