### ISSUE TITLE
nohup makes minimap2 throw its messages inside the alignemnt output file!

### ISSUE THREAD

**Issue by alphahmed** [lh3/minimap2#555]
I tried to prefix my minimap2 with nohup, and end it with bg's '&' symbol, the output sam had the minimap2 progress messages thrown all over the place inside the sam file, instead of making a companion nohup.txt file.

**Comment by lh3** [comment]
Duplicate of #350 and #359. In brief, use "-o" or avoid nohup.

**Comment by alphahmed** [comment]
Thanks!

**Comment by moriarais** [comment]
It is better to add a comment to avoid using `nohup ` in the read.me file. Thanks
