### ISSUE TITLE
Mapping RNA data to the different species

### ISSUE THREAD

**Issue by a40129a** [lh3/minimap2#556]
Hello, I used the Nanopore direct sequencing Kit to generate RNA sequence of a spider species, and then I tried to map my data with the whole genome by minimap2. Unfortunately, there is no genome sequence of the same species I'm interested in, so I mapped my data to the different sqecies in the same order. But only 10~20% data is mapped. Does anyone know how to adjust the parameters to get better results?

**Comment by tseemann** [comment]
Are you sure all the sequences are spider RNA?
Could there be bacterial or other contamination?

**Comment by lh3** [comment]
As @tseemann said. Also, what is the divergence between the reference genome and the sample being sequenced? If the divergence is high, minimap2 is not going to work.
