### ISSUE TITLE
htslib and minimap2 have different definitions of kstring_t

### ISSUE THREAD

**Issue by jts** [lh3/minimap2#558]
Hi @lh3,

I'm trying to use minimap2 as a library in a C++ program. This program also uses htslib, which causes a bad interaction with minimap2 since the definitions of `kstring_t` are not the same. Minimap2 uses `unsigned` to store the length and capacity, but htslib uses `size_t`:

https://github.com/samtools/htslib/blob/master/htslib/kstring.h#L81
https://github.com/lh3/minimap2/blob/master/mmpriv.h#L38

Can these definitions be reconciled?

Thanks
Jared

**Comment by lh3** [comment]
Yes, in principle. You can change the minimap2 one to `size_t`.

**Comment by jts** [comment]
Thanks, I have just opened PR #563

**Comment by lh3** [comment]
#563 has been merged.
