### ISSUE TITLE
map-ont aligns only 83% of all the WGS human reads (1.7M) to hg38 reference.

### ISSUE THREAD

**Issue by harisankarsadasivan** [lh3/minimap2#559]
@lh3 When using map-ont, Minimap2 aligns only 83% of the 350bp long ONT reads. I therefore changed w=1, f=0 and -H to increases this number to 90%. I also noticed that 90% reads aligned is like kind of an upper limit even on 4kbp long ONT reads. Why do you think this is so?

**Comment by tseemann** [comment]
Contamination?
Novel regions of DNA not in the human reference genome?
Garbage nanopore reads?

**Comment by lh3** [comment]
Minimap2 wouldn't work well for noisy reads <1000bp in length. For 4kb reads, contamination is the mostly likely explanation.
