### ISSUE TITLE
Interpreting MAPQ scoring

### ISSUE THREAD

**Issue by smf96** [lh3/minimap2#564]
Hello,

Please could you provide some more information on the meaning behind the MAPQ scores assigned and the decisions made regarding primary/secondary alignments?

If a read aligns to 2 different places equally well, will one of them be assigned a primary mapping randomly? Or does one of the alignments have to better than the other for it to be assigned primary? 

Does a MAPQ of 0 mean the read multimaps or just it doesn't align as well as the primary alignment? Similarly for a MAPQ of 60, does this mean it maps uniquely or just it aligns much better than any other alignment? 

I have performed nanopore human WGS and am focusing on a 200kb region at the moment that has vast sequence homology from ancestral segmental duplications. There is a region within that has no reads covering it with a MAPQ of 60, however there are a couple of reads that are secondary alignments with a MAPQ of 1 and 13. I am struggling to know how to interpret these MAPQ scores.

Any further clarity you can provide is much appreciated.

All the best

**Comment by lh3** [comment]
Please check the SAM spec for the meaning for MAPQ. Briefly, it is `-10*log10 P(mapping is wrong)`

**Comment by smf96** [comment]
Hi. 

I have and I still don't have a clear answer to my questions.

Say I have a read of 20kb that has 2 alignments. My region arose from segmental duplication so in IGV I can see both alignments in one 100kb span aligning to the regions of homology where the ref sequence is very similar. One of them is grey, has a TP flag of P and a mapq of 60 and the other if white, a TP flag of S and has a MAPQ of 0.

The SAM spec says typically the alignment designated primary is the best alignment, but the decision may be arbitrary.

IGV user guide says the interpretation of mapping quality depends on the mapping aligner as some commonly used aligners use a mapq of 0 to mark a read with multiple alignments. In such a case, the read also maps to another location with equally good placement. It is also possible the read could not be uniquely placed but the other placements do not necessarily give equally good quality hits. 

Is the read with a mapq of 60 the best alignment or does minimap2 make an arbitrary decision?
