### ISSUE TITLE
Question: BWA mem vs minimap2

### ISSUE THREAD

**Issue by harish0201** [lh3/minimap2#565]
Hi!

I was reading your blog: https://lh3.github.io/2018/04/02/minimap2-and-the-future-of-bwa

and I ended up being curious since this is nearly two years old and minimap2 has improved leaps and bounds.

So, what would you recommend with the improvements now? Does minimap2 give similar outputs and have any impact on variant calling; compared with BWA mem?

Thank you!

**Comment by lh3** [comment]
The conclusion in the blog post largely stays the same.
