### ISSUE TITLE
Low mapping results on Illumina transcriptome

### ISSUE THREAD

**Issue by ilisem** [lh3/minimap2#568]
Hello, 

I am trying to map RNA seq reads (direct RNA seq reads) of an arthropod generated with the MinIon on a high quality and 'complete' (according to BUSCO standards) transcriptome using minimap2.

I noticed however, very low mapping percentages (e.g. only 5,000 out of 200,000 reads mapped) for my samples. I saw similar problems addressed on this page, although I am confident that contamination is not a problem here. What could be the reason? I played around with different settings, but with limited effect.
Could read length be an issue?

I filtered out less quality reads with Nanofilt, only retaining reads with a quality score > 10.
The minimap script I used:

minimap2 -ax splice -uf -k8 Trinity.fasta sample.fasta > sample.sam

Thanks in advance.

**Comment by lh3** [comment]
You should use map-ont, not splice, but it would not affect mapping rate much. I guess your trinity assembly is of lower quality than nanopore reads.
