### ISSUE TITLE
Minimap .bam in IGV blank

### ISSUE THREAD

**Issue by jasperverwilt** [lh3/minimap2#569]
I would like to load a .bam file that was outputted as .sam by minimap2 and converted by `samtools view`.  I created a .bai file using `samtools index`.  However, when I load this file into IGV, there are no reads. I looked at some of the reads in the .bam file, navigated to the genes that have mapped reads, but no succes. I zoomed in enough. I am probably overlooking something easy, but I don't know what. Thanks so much for your help.

**Comment by lh3** [comment]
If you can see alignments with "samtools view", this is mostly an IGV question, I guess.

**Comment by tseemann** [comment]
@jasperverwilt to confirm you actually have ANY mapped reads use `samtools flagstat`

**Comment by jasperverwilt** [comment]
Yes, you are right. I'm sorry, wrong place. Thanks for reacting so swiftly.

Have you experienced such issues before?

**Comment by jasperverwilt** [comment]
This is the output of `samtools flagstat`: 

`3957692 + 0 in total (QC-passed reads + QC-failed reads)
1847418 + 0 secondary
18066 + 0 supplementary
0 + 0 duplicates
2674481 + 0 mapped (67.58% : N/A)
0 + 0 paired in sequencing
0 + 0 read1
0 + 0 read2
0 + 0 properly paired (N/A : N/A)
0 + 0 with itself and mate mapped
0 + 0 singletons (N/A : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)`

**Comment by lh3** [comment]
> Have you experienced such issues before?

No. IGV is fairly stable.

Make sure you use the right reference, by the way.

**Comment by tseemann** [comment]
Yes, this is wrong place but i was going to say make sure the reference matches the one you used for the BAM. if the sequence IDs don't match then you will see nothing.
