### ISSUE TITLE
A weird bug when computing pacbio HiFi reads overlaps

### ISSUE THREAD

**Issue by vincentluo91** [lh3/minimap2#571]
Hi, there,

I was using minimap2 for computing overlaps of Pacbio HiFi reads, and found a weird bug when processing some particular reads. For example, I chose 5000 HiFi reads from sample HG00733(real data), and run this command `minimap2 -x ava-pb -Hk19 -Xw5 -m100 -g10000 --max-chain-skip 25  -t48 test.fa test.fa >test.paf`

normally, it output 151279 overlaps, here is the log info:

[M::mm_idx_gen::2.572*1.04] collected minimizers
[M::mm_idx_gen::3.272*1.28] sorted minimizers
[M::main::3.272*1.28] loaded/built the index for 5000 target sequence(s)
[M::mm_mapopt_update::3.503*1.26] mid_occ = 110
[M::mm_idx_stat] kmer size: 19; skip: 5; is_hpc: 1; #seq: 5000
[M::mm_idx_stat::3.647*1.25] distinct minimizers: 9763648 (89.01% are singletons); average occurrences: 1.274; average spacing: 4.290
[M::worker_pipeline::7.999*3.48] mapped 5000 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -x ava-pb -Hk19 -Xw5 -m100 -g10000 --max-chain-skip 25 -t48 test.fa test.fa
[M::main] Real time: 8.016 sec; CPU: 27.854 sec; Peak RSS: 0.709 GB

However, when I chose other 5000 reads from the same fastq file of HG00733 and run with the same command, the weird thing happened:
It costs 54Gb memory and 41653 seconds cpu time which is much slower than the above one. 
Here is the log info:

[M::mm_idx_gen::2.325*1.03] collected minimizers
[M::mm_idx_gen::2.743*1.56] sorted minimizers
[M::main::2.743*1.56] loaded/built the index for 5000 target sequence(s)
[M::mm_mapopt_update::2.754*1.56] mid_occ = 11176
[M::mm_idx_stat] kmer size: 19; skip: 5; is_hpc: 1; #seq: 5000
[M::mm_idx_stat::2.763*1.56] distinct minimizers: 308610 (45.01% are singletons); average occurrences: 41.036; average spacing: 4.224
[M::worker_pipeline::2303.989*18.08] mapped 5000 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -x ava-pb -Hk19 -Xw5 -m100 -g10000 --max-chain-skip 25 -t48 test.fa test.fa
[M::main] Real time: 2304.059 sec; CPU: 41653.083 sec; Peak RSS: 54.319 GB

Also, I collected the overlaps computed by HiFiasm but could not found using minimap2, for example, these lost overlaps contains 210696 reads(HG00733, 30x coverage). Then I run minimap2 for computing the overlaps for these reads, and it costs 156Gb memory and still running after 15h (cpu time). Here is the log info:

[M::mm_idx_gen::82.889*1.61] collected minimizers
[M::mm_idx_gen::118.462*1.99] sorted minimizers
[M::main::118.462*1.99] loaded/built the index for 210696 target sequence(s)
[M::mm_mapopt_update::118.577*1.99] mid_occ = 158406
[M::mm_idx_stat] kmer size: 19; skip: 5; is_hpc: 1; #seq: 210696
[M::mm_idx_stat::118.638*1.99] distinct minimizers: 3607742 (75.86% are singletons); average occurrences: 189.827; average spacing: 4.231

Could you please look into it, what could be the possible reason for this ? Many thanks in advance!

**Comment by lh3** [comment]
Your reads are highly correlated. Look at these lines:
```
[M::mm_mapopt_update::3.503*1.26] mid_occ = 110
[M::mm_mapopt_update::2.754*1.56] mid_occ = 11176
[M::mm_mapopt_update::118.577*1.99] mid_occ = 158406
```
The last batch of reads probably come from centromeres and are highly repetitive. It will take much much longer if you want to find hits. You can use `-f200` to make minimap2 faster, but you will miss *most* hits.

Also in general, don't say you find a bug for something you don't understand. Thank you.

**Comment by vincentluo91** [comment]
I understand. Thank you!
