### ISSUE TITLE
output statistics on mapped PacBio reads

### ISSUE THREAD

**Issue by AgustinPardo** [lh3/minimap2#577]
Hello I am running this command over PacBio SMRT-cells tecnología RSII reads:

> minimap2 -ax map-pb final.contigs.fa merged1.fastq > mm_hitP7.sam

There is some flags to retrieve statistics of the number (percentage) of unmapped/mapped reads in the input contig?

Regards

**Comment by lh3** [comment]
Unfortunately, no. Use samtools stats or write a script by yourself.
