### ISSUE TITLE
Paf Confliction with SAM format

### ISSUE THREAD

**Issue by JackTATStraw** [lh3/minimap2#578]
Dear Dr Li,

I converted aligned SAM to PAF format with paftools.js. I observed some contradictory point concerning the CIGAR. For instance, one of the reverse complement alignment from SAM have the CIGAR:
`31S62M1D24M3I5M2I16M1I55M1D14M1D15M1D9M4I53M1D17M1D21M2D33M1D6M1D44M1I29M3D9M1D41M2I8M4D6M1D16M1D10M1D3M1D5M2D38M1I4M1I7M1D4M1I5M1I3M8I4M3I6M5I6M1D6M1I6M3I1M2I2M5I10M6I2M2I1M1I26M8I1M2I8M3I7M3I4M1I4M5I2M16I8M2I2M2I7M4I3M2I3M11I38M1D3M1D25M1D4M2I11M1I47M404S`

The CIGAR suggest 31bp softclip at the start and 404bp softclip at the end. Since the read is 1359bp long, the query should start from 31bp to 955bp. However, in the converted PAF file, the query start is 404bp and the query end is 1328bp. I am wondering whether this is a bug since reverse complement alignment does't mean you need to reverse all the stats for the query sequence.

I re-run the minimap2 with direct paf output and the problem is still there.

**Comment by lh3** [comment]
Coordinates are always on the forward strand, but clipping is computed on the alignment strand.
