### ISSUE TITLE
Can Minimap2 show its progress on demand?

### ISSUE THREAD

**Issue by hengjwj** [lh3/minimap2#580]
Hi,

I'm pretty new to computational work so please pardon me if I'm unclear. 

I'm trying to figure out the amount of resources to request from the cluster for FASTQs of different  sizes. To increase the sensitivity of mapping, I'm relaxing the -k parameter when mapping ONT direct RNA-seq data to HG19. However, that results in Minimap2 taking very long and a lot of ram to run. In some cases, it doesn't finish processing because either the amount of time or ram requested is too low. I'm able to find out the amount of resources used at the time the job is terminated but I'm not sure how much more is required.

Is there a way to find out how close Minimap2 is to finishing a job?

**Comment by lh3** [comment]
Minimap2 prints the number of sequences that have been processed.

**Comment by hengjwj** [comment]
Just to clarify: is that with the --print-q-name option or is it supposed to print automatically?

Thanks!
