### ISSUE TITLE
About paftools.js asmgene output

### ISSUE THREAD

**Issue by fsnibs10** [lh3/minimap2#581]
Hi, 

Recently, I want to use paftools.js asmgene to evaluate the gene completeness for assembly. 
My command is below:
 `paftools.js asmgene -e ref-to-cdna.paf cdna.paf > asmgene_e_output.txt`

I find one problem. According to issues/355 [https://github.com/lh3/minimap2/issues/355](url)  , "part10-" should equal to "below 10% (0)" plus "unmapped (M)".
But for your script, the "unmapped (M)" is added to "part10+".

**Comment by lh3** [comment]
Thanks. It is a bug.
