### ISSUE TITLE
number of matches differs for paf format with and without cigar

### ISSUE THREAD

**Issue by MaKuzman** [lh3/minimap2#583]
Hello, I am using minimap (2.17-r941)

when mapping with and without -c tag the output differes in paf format. Number of matches seems to be way off without -c tag. I attached examples i used.

```
minimap -x map-ont -Y -o nanoOnContig_nocigar.paf onecontig.fasta onenanopore.fasta
minimap -x map-ont -c -Y -o nanoOnContig_cigar.paf onecontig.fasta onenanopore.fasta
cat nanoOnContig_cigar.paf
cat nanoOnContig_nocigar.paf
```
output:

>cat nanoOnContig_cigar.paf
5b9c1545-c8b5-409b-adf4-b68e2fdbd72f    7918    7       7885    -       contig_999_pilon        70785   36277   44576   7039    8641    60      NM:i:1602    ms:i:7928       AS:i:7950       nn:i:0  tp:A:P  cm:i:303        s1:i:2600       s2:i:0  de:f:0.1228     rl:i:0  cg:Z:<cigar removed from output>

>cat nanoOnContig_nocigar.paf
5b9c1545-c8b5-409b-adf4-b68e2fdbd72f    7918    43      7829    -       contig_999_pilon        70785   36345   44541   2705    8284    60      tp:A:P       cm:i:303        s1:i:2600       s2:i:0  dv:f:0.1047     rl:i:0

>minimap --version 
2.17-r941

[example.zip](https://github.com/lh3/minimap2/files/4420293/example.zip)

**Comment by MaKuzman** [comment]
Update: 
I see it is in documantation, but I had no idea it is THIS approximate !! (why not set -c as default and only give cigar string when -c is requested by user? )
When alignment is available, column 11 gives the total number of sequence matches, mismatches and gaps in the alignment; column 10 divided by column 11 gives the BLAST-like alignment identity. When alignment is unavailable, these two columns are approximate.

**Comment by lh3** [comment]
See FAQ.

**Comment by nettanetta** [comment]
Hi, 
I am looking for a way to calculate the % of identity (basically, [BLAST's pident](https://www.biorxiv.org/content/biorxiv/suppl/2018/06/16/214288.DC2/214288-7.pdf)) 
Is the statement "column 10 divided by column 11 gives the BLAST-like alignment identity" correct? (assuming that -c flag was used and minimap performed detailed base alignment)
thanks
Netta
