### ISSUE TITLE
How to graph a ".paf" file?

### ISSUE THREAD

**Issue by AgustinPardo** [lh3/minimap2#584]
Hello,
I run this command in a cluster:
> minimap2 -DP -k19 -w19 -m200 alga.fa alga_ref.fa> out.paf

Because of the execution in the cluster I could not get the window output graph.

Do you how I could get the graph in my local desktop computer using the ".paf" file output?

Regards

**Comment by lh3** [comment]
If by "graph" you mean a dotter plot, check out miniasm and
```sh
cd miniasm
make minidot
./minidot in.paf > out.eps
```

**Comment by lh3** [comment]
Or try D-GENIES

**Comment by AgustinPardo** [comment]
thanks!
