### ISSUE TITLE
Duplicate lines in output file

### ISSUE THREAD

**Issue by FraPria** [lh3/minimap2#585]
Hello,
I'm using minimap2 to align Nanopore reads to genome. I've run:

minimap2 -ax splice -uf -k14 $index $FASTQ > aln.sam

where $index is the genome index Ch37, and $FASTQ are long reads of direct RNA from Nanopore sequencing.

"aln" file has 1,457,194 rows but if I apply unique function it returns 1,301,831 lines, therefore 155,363 are duplicated (10% of the total).
So there are many reads that have 2 identical rows in the alignment file, and they are not secondary alignment because the coordinates in the genome are the same.

Also, the reads related to duplicate rows appear just once in the fastq and in the guppy summary file, so it seems not to be a sequencing problem. 
Same results with the option --secondary=no.

I don’t understand the precence of this lines and whether they should be removed or kept.
Thank you in advance for your help.

Have a nice day

**Comment by lh3** [comment]
Show an example.

It could be duplicated entries in reference.

**Comment by FraPria** [comment]
Hello, sorry it turned out it was an error in the input fasta file.
Sorry for opening the issue.

Thank you

**Comment by lh3** [comment]
No problem. Thanks for reporting anyway.
