### ISSUE TITLE
CIGAR + MD to cs tag

### ISSUE THREAD

**Issue by Juke34** [lh3/minimap2#586]
Hi, I have read with interest your [blog page ](http://lh3.github.io/2018/03/27/the-history-the-cigar-x-operator-and-the-md-tag).
I was wondering if you have a script of piece of code that would create the `cs` string based on a basic sam format (containing CIGAR + MD tags). I would love that `cs` becomes a standards, it sounds so more obvious to use.

**Comment by lh3** [comment]
See [this](https://github.com/lh3/minimap2/blob/cb56fb762a5a397785acd5e9781146ba96b97094/misc/paftools.js#L1685-L1724).
