### ISSUE TITLE
Minimap doesn't work after two iteration with Racon

### ISSUE THREAD

**Issue by matryoskina** [lh3/minimap2#587]
Hi, 

I'm polishing a 5Gb genome with Minimap2/Racon. I run it for two iteration and everything work fine. Paf file are ~23 Gb size. As I run the third round of Minimap2, when the file reaches ~7 Gb I get the following message in the log.file

[M::worker_pipeline::36146.991*34.62] mapped 48635 sequences
[M::worker_pipeline::36175.152*34.63] mapped 18499 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: /home/minimap2-2.17_x64-linux/minimap2 -t 60 -I 8G racon2.corr.fasta /home/canu/results/canu_assembly.correctedReads.fasta.gz
[M::main] Real time: 36177.700 sec; CPU: 1252768.364 sec; Peak RSS: 59.944 GB
terminate called after throwing an instance of 'std::invalid_argument'
  what():  [bioparser::createParser] error: unable to open file home/canu/results/canu_assembly.correctedReads.fasta.gz!

And then it tryes to run again.
What that could be? Thanks

**Comment by lh3** [comment]
> terminate called after throwing an instance of 'std::invalid_argument'
what(): [bioparser::createParser] error: unable to open file

This is not a minimap2 error message.
