### ISSUE TITLE
got disagree between single sequence align to single  and multi sequences align to multi

### ISSUE THREAD

**Issue by orangeSi** [lh3/minimap2#59]
Hi Li~
the multil sequences file A contain a sequence ID: 000130F_002|quiver|quiver|pilon ,when align file A to ref，get ：

000130F_002|quiver|quiver|pilon	6708	196	6692	+	Contig44	6708	196	6692	3781	6496	60	tp:A:P	cm:i:329	s1:i:3781	s2:i:1648 ,  the identity is 3781/6496

but when I extract 000130F_002|quiver|quiver|pilon to single sequence file B,and align file B to ref,get:

000130F_002|quiver|quiver|pilon	6708	9	6692	+	Contig44	6708	9	6692	6683	6683	60	tp:A:P	cm:i:661	s1:i:6683	s2:i:0,   the identity is 6683/6683=1

so the both identity is not equal, so why ?

Thank~
Si

**Comment by lh3** [comment]
Were you using different command lines? Could you reproduce the issue on a smaller dataset such that I can debug? I can't do much without the actual examples. Thanks.

**Comment by orangeSi** [comment]
I use the same command: minimap2 -k19 -w19 -A1 -B9 -O16,41 -E2,1 -s200 -z200, I am trying to get a smaller dataset~

**Comment by lh3** [comment]
Could you reproduce the issue on a smaller data set?

**Comment by lh3** [comment]
I am closing this issue for now. When you find a smaller dataset that triggers the issue, I can reopen it. Thank you.
