### ISSUE TITLE
mappy.fastx_read don't output all the reads from big fastq files

### ISSUE THREAD

**Issue by hennion** [lh3/minimap2#594]
I try to get sequences from a fastq (long ONT reads, 12 Go file) containing 291853 reads, and mappy.fastx_read outputs only the first 83434 reads. If I split my fastq into 80 000 read files, I can get all the reads with mappy.fastx_read. I don't get any error message. Is there a limit in file size / number of reads that mappy.fastx_read can process at once?

**Comment by lh3** [comment]
Are these the first 83434 reads? If so, your file may be malformatted in the middle. The parser doesn't report errors.

**Comment by hennion** [comment]
You're right, I'm sorry, I don't know where it came from but there was an entry with 2 lines instead of 4. Thank you for your help!

**Comment by lh3** [comment]
Thanks for reporting. It is still mappy's fault for not reporting errors. The underlying C code does check errors, but the error code is not passed to Python.

**Comment by zooniikayler** [comment]
Is there a limit to the size of fq files that fastx_read can parse?

**Comment by lh3** [comment]
No. Please see the comment. It was not because of the file size, but because malformatted FASTQ.
