### ISSUE TITLE
comparing .mmi files

### ISSUE THREAD

**Issue by sandipmkale** [lh3/minimap2#596]
Hello, 
I have generated two index files from the same assembly. Unfortunately I don't remember the "-I" parameters used. Is there way to compare two .mmi files whether they are same or different. 

Thanks and regards

**Comment by lh3** [comment]
You can compare the file size first. If the file size is identical, compute md5sum with
```sh
md5sum index1.mmi index2.mmi
```
If the checksum are identical, the two files are almost certainly identical. Minimap2 doesn't keep parameter `-I`, so it is not easy to know what value was used.
