### ISSUE TITLE
vcf from paftools has dash on ref/alt column

### ISSUE THREAD

**Issue by PeterWu-Biomath** [lh3/minimap2#598]
vcf from paftools use "-" in ref/alt column when representing indel. But most tools(say vcftools, bcftools, etc. ) do not support such representation, they need at least one base in those column. For example:  
> V       1       1296369 1296371 1       60      ac      -       841     1254426 1254426 -

Have you considered change it?
Peter.

**Comment by lh3** [comment]
This is not vcf output. You need to use -f.
