### ISSUE TITLE
Understanding the Minimap2 algorithm

### ISSUE THREAD

**Issue by kanchanhole** [lh3/minimap2#60]
Hello Dr. Li,

I am trying to understand the algorithm of Minimap2. Here, so far I understand follows a typical seed-chain-align procedure. However, I did not understand for seeding how the k-mers are selected and how long are they?
Could you help me understand it?

Thank you very much in advance.

**Comment by lh3** [comment]
You need to read the minimap/miniasm paper on k-mer selection. With normal k-mer, the k-mer size is specified on the command line. It varies with presets.
