### ISSUE TITLE
.TH:, .SH: and  .PP: command not found

### ISSUE THREAD

**Issue by l-yampolsky** [lh3/minimap2#600]
Dear Colleagues,
When trying to run minmap2.1 I am getting
line 1: .TH: command not found
line 2: .SH: command not found
line 3: .PP: command not found

And then nothing happened.
On MacOS 10.13.6. Installation by conda completed without errors. Any idea what I may be doing wrong?

Thanks,
L.Yampolsky

**Comment by lh3** [comment]
You don't run minimap2.1. That's manpage. Following the step in README.

**Comment by l-yampolsky** [comment]
Dear Heng,

Thanks!
Sorry, but this was not obvious at all - because


./minimap2

-bash: ./minimap2: No such file or directory

So I decided that I need to run minimap2.1

Best regards,

L. Yampolsky
