### ISSUE TITLE
non-canonical splicing (donor/acceptor)

### ISSUE THREAD

**Issue by dandepledge** [lh3/minimap2#601]
I'm trying to use minimap2 to align nanopore sequence data from an (un)popular virus that creates transcripts that, for all intents and purposes, are spliced. However, it does not obey standard splicing rules (AG|GT). Is there a way to run minimap2 in splicing mode without having it default toward preferred splice donor/acceptor motifs?

**Comment by lh3** [comment]
Add option `-un`.
