### ISSUE TITLE
Summary statistics for minimap2

### ISSUE THREAD

**Issue by tfiskur** [lh3/minimap2#602]
Hello!

Is it possible to obtain the summary statistics for the minimap2?
I have obtained more mapped reads than there were in the initial fastq file, and try to understand the reason.
I used PacBio reads, and mapped them to a genome with the next parameters:
minimap2 -ax splice -t 30 -uf --secondary=no -C5 recommended by the Cupcake tutorial ( https://github.com/Magdoll/cDNA_Cupcake/wiki/Cupcake:-supporting-scripts-for-Iso-Seq-after-clustering-step )

Thank you a lot in advance!

**Comment by lh3** [comment]
Please use samtools.
