### ISSUE TITLE
-N and --secondary=no

### ISSUE THREAD

**Issue by zc312** [lh3/minimap2#603]
Hi,
What happens if I set `-N 1` and `--secondary=no`? 1) Will this still output the single best alignment per read and will this alignment be a primary alignment? 

I also noticed in issue #98 that "The difference between `-N0` and `--secondary=no` should be very small (with `--secondary=no` generally better)." 2) Why is `--secondary=no` better and 3) should `-N 0` and `--secondary=no` be equivalent? 

For context, I'm hoping to exclude all secondary alignments and eventually filter out supplementary alignments to leave me with the single "best" primary alignment. Thank you!

**Comment by lh3** [comment]
See FAQ, question 5.

**Comment by lh3** [comment]
*Never* use -N1 or -N0.

**Comment by zc312** [comment]
Thank you! The faq says --secondary=no excludes secondary alignments, so is the reason for never using -N1 or -N0 because it falsely adds a restriction on the number of secondary alignments outputted? And, to confirm, does -N only refer to number of secondary (not supplementary) alignments produced?

**Comment by lh3** [comment]
I should probably add this to FAQ. There have been multiple questions on the same topic. Short answer: -N1 and -N0 significantly reduce alignment accuracy.
