### ISSUE TITLE
primary/supplementary designation

### ISSUE THREAD

**Issue by zc312** [lh3/minimap2#605]
Hi,

I saw in the[ SAM alignment specs](https://samtools.github.io/hts-specs/SAMv1.pdf) that in the case of a chimeric alignment, the "decision regarding which linear alignment is representative is arbitrary." 

Does this mean that minimap2 will always arbitrarily designate one portion of an aligned chimeric read as "primary alignment" and the other as "supplementary" or will the primary alignment be whichever portion has a higher alignment score? 

For ex., if there's a translocation between chr 1 and chr 5 and I have a 10 kb read split evenly (5 kb/5 kb) between the two sites, will one of the alignments be randomly designated primary while the other is designated supplementary?

**Comment by lh3** [comment]
If alignment scores are identical, the assignment will be random.
