### ISSUE TITLE
Ambiguous nucleotides 

### ISSUE THREAD

**Issue by wyim-pgl** [lh3/minimap2#606]
Hi!
Does minimap2 support ambiguous nucleotides (r, y, w, s, k, m, d, v, h, b; IUPAC-IUB codes)?
I couldn't find any clue.
Thanks!
Won

**Comment by lh3** [comment]
Minimap2 doesn't support IUB codes.

**Comment by tseemann** [comment]
@lh3 how do they get treated exactly? as Ns?  and how does N get treated? does it 'match' with a AGTC or mismatch? does it count in gap extension?
