### ISSUE TITLE
Can't seem to get flag de:f to show

### ISSUE THREAD

**Issue by btemperton** [lh3/minimap2#614]
Can you tell me what flag I need to set for minimap2  in order to output the `de:f`  flag for gap-compressed per-base sequence divergence when mapping ont-reads to a reference? Using versiomn 2.17 (r941), but only getting the following flags: `tp:a:P cm:i:12 s1:i:75 s2:i:0 dv:f:0.0803   rl:i:0`

**Comment by lh3** [comment]
Use option `-a` or `-c`. See also FAQ.
