### ISSUE TITLE
Minimap2 mapping of 'ancient RSII P5C3' reads to a final assembly

### ISSUE THREAD

**Issue by splaisan** [lh3/minimap2#615]
I wish to accurately map the original PB reads (used to assemble) to the final assembly to look for coverage biases and assembly hotspots.

Should I add -H to compress homopolymers (as proposed in the indexing part of the man) when I map reads against the fasta reference directly like below or create a .idx reference first (with which extra parameters)?

Are N-stretches in the final assembly coming from the scaffolding posing a problem for the mapping?

Finally, should I tune more parameters for mapping more accurately or is the preset map-pb enough?

Thanks for your advice
Stephane

```
minimap2 \
-H \
-x map-pb \
-a \
-o mappings/run2_mappings.sam \
-t 88 \
-R @RG\tID:RSII_run2\tSM:mylib \
reference/1.2GB_reference.fasta \
reads/*.fastq.gz
```

**Comment by lh3** [comment]
Use -xmap-pb is fine. The latest CLR is not much different P5C3.
