### ISSUE TITLE
Using -p 0.99 argument still outputs secondary alignments with lower scores

### ISSUE THREAD

**Issue by josiegleeson** [lh3/minimap2#619]
I've used minimap2 as follows:
minimap2 -ax map-ont -p 0.99 

I'm still getting secondary alignments output that have an alignment score of 519 when the primary alignment score is 670. 

Am I misunderstanding what this parameter should be doing? Thanks.

**Comment by lh3** [comment]
Use `--secondary=no`. -p is not intended for this purpose.

**Comment by josiegleeson** [comment]
Hi, I am using minimap2 on direct RNA sequencing where the primary alignment may not be the correct transcript. I want to keep all secondary alignments with the same or very close alignment score to the primary alignment.

**Comment by lh3** [comment]
Write a script and filter by yourself. Minimap2 doesn't provide this functionality.

**Comment by josiegleeson** [comment]
Ok no problem. Do you mind clarifying what this parameter does? I am not sure what score ratio is referring to here. Thanks.

-p FLOAT  Minimal secondary-to-primary score ratio to output secondary mappings [0.8].
