### ISSUE TITLE
All vs all mapping of contigs in a multifasta

### ISSUE THREAD

**Issue by sxh1136** [lh3/minimap2#620]
Hi there,

I have some viral metagenomic bins that I've noticed have a large amount of overlap between each other. I was wondering if it was suitable to use minimap to merge these contigs together, and if so, how would i go about this since there's no reference sequence (just want to map all contigs in a multifasta to each other)

Thanks for the help in advance!

**Comment by tseemann** [comment]
Maybe https://github.com/mahulchak/quickmerge
