### ISSUE TITLE
Mapping paired-end collections in galaxy

### ISSUE THREAD

**Issue by jsalemq** [lh3/minimap2#627]
I am mapping paired-end data using minimap2 on a local instance of galaxy. I can process individual paired-end samples just fine. However, when I uploaded multiple pairs into a collection and try to run a collection through minimap2, only 1 sample maps. All other samples give the following error:

_Could not display BAM file, error was:file has no sequences defined (mode=‘rb’) - is it SAM/BAM format? Consider opening with check_sq=False_

Is this a bug or something in my parameters?

**Comment by lh3** [comment]
This seems a galaxy question?

**Comment by daydream-boost** [comment]
It seems like that from pysam，maybe your sam file is invalid for pysam。

**Comment by jsalemq** [comment]
Thank you for your replies. It is indeed an issue with galaxy. They said that I might be running out of memory (I currently use 20 GB). Are they any command line options to aid in this problem?

**Comment by daydream-boost** [comment]
Maybe your sam  doesn't have header, you just use samtools to add it.
