### ISSUE TITLE
How to identify mRNAs, transcription start/stop sites and regulatory elements from MinION data

### ISSUE THREAD

**Issue by sekhwal** [lh3/minimap2#628]
I am looking to analyze minION data for identifying  mRNAs, transcription start/stop sites and regulatory elements. I have .sam files produced from minimap2 . I am not sure how to process these files to identify transcription start/stop sites, regulatory elements and mRNAs. 

Do I need to use IGV for visualization ? else any pipeline for identifying regulatory elements.

**Comment by lh3** [comment]
You need separate tools.
