### ISSUE TITLE
How does minimap2 infer transcript strand from read sequence?

### ISSUE THREAD

**Issue by Kyung-TaeLee** [lh3/minimap2#629]
From what I've seen in other feed, "ts" flag stands for transcript strand and it is the strand of the read relative to transcript. Can you explain how does minimap2 infer the transcript strand from raw read when library preparations from different platforms (PacBio, nanopore cDNA, nanopore direct RNA-seq) are conducted in different way?
And if we assume that "ts" flag is very accurate, can we directly find out the sequence of actual RNA from which the mapped read came from (and structure) ?
For example, when read is mapped to positive strand (forward strand) and "ts" flag is "ts:A:-", actual RNA sequence is the reverse-complementary of the read or sth like that.

Thank you!

**Comment by lh3** [comment]
Based on the GT-AG signal.

**Comment by chilampoon** [comment]
> Based on the GT-AG signal.

Hi @lh3, for those mono-exonic (mRNA/cDNA) reads without splice sites, how does minimap2 infer the strand corresponding to the genome (not the transcript)? thank you.

**Comment by lh3** [comment]
minimap2 can't infer in that case

**Comment by chilampoon** [comment]
> minimap2 can't infer in that case

Thanks for the quick response! does it mean the directions of these reads without splice sites are random? 
because I saw some of them mapped to a similar position but with opposite strands quite often
