### ISSUE TITLE
MD tag

### ISSUE THREAD

**Issue by fritzsedlazeck** [lh3/minimap2#63]
Hi,
are you planing to provide the MD tag at some point? Or should I rely on samtools to reconstruct this information?

Thanks
Fritz

**Comment by lh3** [comment]
My current plan is to ditch MD and introduce a [new cs tag](https://github.com/lh3/minimap2#cs) instead. The problem with MD is that it is not a standalone tag. You have to parse query sequence, cigar and MD at the same time. In comparison, cs encodes cigar. You can parse cs alone.

**Comment by fritzsedlazeck** [comment]
Interesting, would make life easier for sure.
Thanks
Fritz

**Comment by alexiswl** [comment]
Hi Fritz,
Working with Pysam I also found this particularly frustrating, 
methods such as get_reference_sequence() rely on the MD tag, I'm sure it's only a matter of time before they can incorporate the cs tag as a substitute.

I found that running
`samtools calmd bam_file reference_file > new_bam_file` would add in the md tag as needed.

Cheers,
Alexis.

**Comment by fritzsedlazeck** [comment]
Hi Alexis,
This is certainly true but very slow. Minimap2 has all the information during the running time since it writes it out in the cs string.

I will incorporate the cs string soon into my program to support the necessary step to replace cigar and MD string with it.

Cheers
Fritz

**Comment by lh3** [comment]
Oh, I forgot that you had requested the MD tag, @fritzsedlazeck. There have been a few independent requests on MD recently, so I have decided to implement it in minimap2. The next release will support MD.

**Comment by fritzsedlazeck** [comment]
Are you still pushing for the cs string? I think it would make things easier for us compared to MD + cigar...

**Comment by lh3** [comment]
cs will certainly stay in minimap2. The PAF output needs this tag anyway as PAF doesn't store the query sequence like SAM. My assembly-to-assembly variant caller is unable to work MD, either.

**Comment by gevro** [comment]
Is there a plan to make a tool similar to calmd to add the cs tag to any BAM file?
