### ISSUE TITLE
Missing sam header minimap2 for long reads assembly

### ISSUE THREAD

**Issue by AG-Run** [lh3/minimap2#633]
Hi, I would like to know why the output of minimap2 in sam file is not getting the @SQ header. Im aligning a query of 200kb against a genome of 4Gb.

Thanks

**Comment by lh3** [comment]
Add option `-I8g` when running minimap2.

**Comment by sjclare** [comment]
Hi, I am getting a similar issue when I attempted to align 139Gb of raw fasta reads to our reference genome of 5.1Gb. I tried setting -I 11G and -I 1000G since I read it would just go to the max it needed but neither worked.

Thanks for any help
