### ISSUE TITLE
Some reads couldn't be alignmented when using minimap2

### ISSUE THREAD

**Issue by YulinzhangSia** [lh3/minimap2#634]
Hello, I found an alignment issue when using minimap2.
The data was MinION sequencing results of 16S rRNA, and the code is:
_minimap2 -x ava-ont -a ref10.fasta reads10.fasta > mapping10.sam_

I aligned five reads with the ref., while one read couldn't be aligned.
![image](https://user-images.githubusercontent.com/51396070/87111091-1ff39d00-c29b-11ea-919b-fda69ddf6a6f.png)

Do you have some advice? Thanks!

**Comment by lh3** [comment]
Not all reads can be aligned.
