### ISSUE TITLE
Add -R to minimap2 do not extract @RD headers in the sam file

### ISSUE THREAD

**Issue by AG-Run** [lh3/minimap2#635]
Hello

Im using next command

minimap2 -ax **-R** map-pb -I8g -d 5Gb_genomefile.fasta query_sequence.fasta > output.sam

In the manual is used to add @RG format

-R STR | SAM read group line in a format like @RG\\tID:foo\\tSM:bar [].

Thanks for the help

**Comment by lh3** [comment]
The help message already gives you an example. It is `-R'@RG\tID:foo\tSM:bar'`.

**Comment by AG-Run** [comment]
> The help message already gives you an example. It is `-R'@RG\tID:foo\tSM:bar'`.

The minimap do not recongnize the -R parameter, why? the code I used is
minimap2 -ax -R '@RG\tID:foo\tSM:bar' map-pb -I8g -d 5Gb_genomefile.fasta query_sequence.fasta > output.sam

Thanks
