### ISSUE TITLE
Documentation for API in mmpriv.h 

### ISSUE THREAD

**Issue by cgroza** [lh3/minimap2#637]
Hi,

I want to use a function form the `mmpriv.h` header, but the arguments are not documented.
For example, how do I use `mm_write_paf3`?
The signature is
```
void mm_write_paf3(kstring_t *s, const mm_idx_t *mi, const mm_bseq1_t *t, const mm_reg1_t *r, void *km, int opt_flag, int rep_len)
```
I looked at the definitions of `ksring_t` and `mm_bseq`_t`, but it's not clear to me what they are and how to create them.
Also `km` has a void type and I have no idea what I should pass there.

Is any documentation available somewhere else?

Thanks.

**Comment by lh3** [comment]
You can initialize a kstring_t object with `kstring_t str = {0,0,0};` and free `free(str.s);` at the end. You have to fill `mm_bseq_t` manually.
