### ISSUE TITLE
ASM presets

### ISSUE THREAD

**Issue by brettChapman** [lh3/minimap2#638]
Hi

I've been looking at using the asm presets with minimap2.

In version 2.17-r941 I noticed that in the usage printout for -x it says the following:

- asm5/asm10/asm20: asm-to-ref mapping, for ~0.1/1/5% sequence divergence

However, when I go to this page:
http://manpages.ubuntu.com/manpages/disco/man1/minimap2.1.html

It explains the asm options differently:

asm5    Long assembly to reference mapping (-k19 -w19  -A1  -B19  -O39,81  -E3,1
                         -s200  -z200  --min-occ-floor=100).   Typically,  the alignment will not
                         extend to regions with 5% or higher sequence divergence. Only  use  this
                         preset if the average divergence is far below 5%.

                 asm10   Long  assembly  to  reference  mapping  (-k19 -w19 -A1 -B9 -O16,41 -E2,1
                         -s200 -z200 --min-occ-floor=100).  Up to 10% sequence divergence.

                 asm20   Long assembly to reference mapping (-k19 -w10 -A1 -B4 -O6,26 -E2,1 -s200
                         -z200 --min-occ-floor=100).  Up to 20% sequence divergence.

I'm not sure which preset option to go with. I'm looking at multiple different Barley varieties (~20) of the same species. The estimated divergence time is <10,000 years particularly with wild varieties I'm looking at, and with some varieties the divergence time is very recent, as these varieties have been crossed multiple times by growers over the last decade or two. Since the divergence may vary so much, perhaps I should really be using asm20?

However, with the latest build the usage says asm5 is <0.1% and asm20 is <5% divergence. Which usage information is correct?

Thanks.

**Comment by lh3** [comment]
Both are correct. The help message doesn't say asm5 for <0.1%; it says asm5 for ~0.1%. Just follow the help message.
