### ISSUE TITLE
Using single or multi-part/split indexes with or without saving them to disk

### ISSUE THREAD

**Issue by andreaswallberg** [lh3/minimap2#639]
Dear developers,

I wonder if the -I and --split-prefix parameters work the same and should be used the same, regardless of whether one works with a saved mmi index file, or uses two fasta files as query and targets.

Cheers!

**Comment by lh3** [comment]
`-I` is applied to the indexing step. It is overridden by the saved index file. `--split-prefix` is applied to the mapping step.
