### ISSUE TITLE
Cannot open minimap2-created sam file in Geneious

### ISSUE THREAD

**Issue by ameliahaj** [lh3/minimap2#64]
Hello,

I recently attempted to open a sam file I created using Minimap2 in Geneious and was not able to open it. I tried to validate the file using picard ValidateSamFile, and received the following errors:

> ## HISTOGRAM java.lang.String
> Error Type Count
> ERROR:MISMATCH_CIGAR_SEQ_LENGTH 50105
> ERROR:MISSING_READ_GROUP 1
> WARNING:ADJACENT_INDEL_IN_CIGAR 1
> WARNING:RECORD_MISSING_READ_GROUP 939614

I can provide the files I used if necessary, but is this a known issue or more likely something to do with my specific data? Is there a way to resolve it?

Thank you!

Amelia

**Comment by lh3** [comment]
What version are you using? Missing read group is not an error. Like bwa, bowtie or any other mappers, you need to run with something like:
```
minimap2 -R'@RG\tID:foo\tSM:bar'
```
`MISMATCH_CIGAR_SEQ_LENGTH` could be a bug. Picard show report read names having this problem. Could you show me the violating record? Thanks.

**Comment by lh3** [comment]
It seems that picard validatesam doesn't work with secondary alignments without sequences. This is really the problem with picard, not minimap2. Anyway, you can get validatesam compatible output with:
```sh
minimap2 -a --secondary=no -R'@RG\tID:foo\tSM:bar\tPL:pacbio'
```
I am closing this issue. Feel free to add more messages if picard/geneious still has problems.
