### ISSUE TITLE
[Question] Is minimap2 using sdust ?

### ISSUE THREAD

**Issue by maxibor** [lh3/minimap2#642]
Is minimap2 using [sdust](https://github.com/lh3/sdust) @lh3 ? 
If so, how is it using it ? 
Masking before mapping (at indexing stage), or masking after mapping (by not writting the alignments at low-complexity regions masked coordinates) ?
It seems that in `minimap`, there was the `-T` flag to control the masking, does it still exist it `minimap2` ?

**Comment by lh3** [comment]
> It seems that in minimap, there was the -T flag to control the masking, does it still exist it minimap2 ?

Yes. The same.

**Comment by alephreish** [comment]
[Not anymore](https://github.com/lh3/minimap2/blob/618d33515e5853c4576d5a3d126fdcda28f0e8a4/main.c#L352C1-L353C1):

`//		fprintf(fp_help, "    -T INT       SDUST threshold; 0 to disable SDUST [%d]\n", opt.sdust_thres); // TODO: this option is never used; might be buggy`

**Comment by lh3** [comment]
The code is still there
