### ISSUE TITLE
The confused meaning of -L parameter in paftools

### ISSUE THREAD

**Issue by XuewenWangUGA** [lh3/minimap2#644]
It is a little confused on the -L parameter in paftools. There two possible meaning of the -L INT 
1. -L INT means the minimum length of alignment block in PAF output (collumn 11th) 
2. For two aligned sequences e.g ref vs a contig,   there are many aligned blocks. -L INT means the total aligned length of two long sequences? 
background: 
Tool:  paftools.js 
Tool  parameter: 
#  -L INT    min alignment length to call variants [50000]

PAF output collum 11: 
11 | int | Alignment block length 

Which one do you mean? Could you make it clear?
Thanks.

**Comment by lh3** [comment]
Alignment block length.
