### ISSUE TITLE
-N20 and --secondary=no

### ISSUE THREAD

**Issue by MarieLataretu** [lh3/minimap2#645]
Hey,

can you explain how ```-N20 --secondary=no``` (as pre-set in ```-x sr```) makes sense?

The manual says:

```-N```
> Output at most INT secondary alignments [5]. This option has no effect when -X is applied.

```--secondary```
> Whether to output secondary alignments [yes]

The FAQs and other issues didn't help.

Thanks!

**Comment by lh3** [comment]
-N is an internal algorithm option. It controls how many candidates alignment to extend. --secondary is an output option.
