### ISSUE TITLE
mapq between bwa vs minimap2

### ISSUE THREAD

**Issue by ruolin** [lh3/minimap2#648]
When I compared bwa vs minimap2.17 for illumina short reads (variable length 50-250, single-end), I saw a lot of reads with much lower mapq in minimap2. I have even seen a few fold alignment coverage differences at least in one region with mapq cutoff at 60. This paper also mentioned that bwa tends to overestimate the mapq and recommend to use minimap2 for recalibrating mapq. https://bmcgenomics.biomedcentral.com/articles/10.1186/s12864-020-6685-y I am wondering if you have any general comments about the difference of mapq between the two?

**Comment by lh3** [comment]
Don't take a threshold 60.

**Comment by iqbal-lab** [comment]
Cc @leoisl @martinghunt

**Comment by ruolin** [comment]
60 is just an example
