### ISSUE TITLE
Overrepresentation of negative strand alignments

### ISSUE THREAD

**Issue by cihanerkut** [lh3/minimap2#649]
Dear Prof. Li,

We are confused with something and need your insight.

We are aligning ONT direct cDNA seq data to human genome using minimap2. In PAF output, the 5th column shows whether the segment was aligned to the positive or negative strand of the reference. We see that the number of lines with + on column 5 is twice as much as those with -. The trend is the same when we output as SAM and look into flag 0x10. We would expect that to be roughly 1:1, not 2:1, since there are roughly equal number of genes on each strand, and there is no biological reason for higher expression of genes from the negative strand.

Then we summarise reads at the gene level using featureCounts providing the GTF file corresponding to this genome, and the bias is gone: total number of counted reads are roughly 1:1 between both strands. This suggests that the bias is happening due to alignments to intergenic regions. However, no intergenic region should be sequenced with direct cDNA sequencing.

We run version 2.17-r941 as:

```
minimap2 -x splice -L --cs=long --sam-hit-only -2 --MD -t32 hs37d5_PhiX.fa pass.fastq
```

What do you think could be the reason?

Best regards,

Cihan

**Comment by lh3** [comment]
Depending on your protocol, some RNA-seq runs sequence excessive ribosome related genes like RPL/RPS/etc. What if you exclude these genes?

**Comment by cihanerkut** [comment]
Can we exclude genes at the level of alignment?

Also, we just checked. featureCounts counts RP genes from + and - strands equally. They are not expressed at very high levels and not biased towards one strand or the other.

Could it be due to -ub which comes as default from -x splice? I mean, something happening during the second pass?

**Comment by lh3** [comment]
-ub is not doing a second pass. Basically, I think this is more related to your data and has little to do with minimap2. If you think this is a minimap2 issue, you need to find the case where minimap2 chooses the wrong strand.

**Comment by cihanerkut** [comment]
I don't think it chooses the wrong strand because the effect is gone when you provide strand information during read summarisation. But initially, it places a lot of alignments with SAM flag 0x100 set. We were curious if it could be a bug.

Thanks a lot for your help.

**Comment by callumparr** [comment]
I've seen this as well.
