### ISSUE TITLE
Chain two overlapping alignments

### ISSUE THREAD

**Issue by sjackman** [lh3/minimap2#65]
I aligned Nanopore reads to a draft assembly with `minimap2 -x map-ont`. The following two alignments overlap on the query, 53–2232 (2179 bp) and 1538–5823 (4285 bp). I'd like these two alignments two be chained into a single alignment. Is there a parameter that I can tweak to achieve that behaviour?
```
53993a10-2ef9-4007-85ee-ebb8017078e9	5846	1538	5823	+	8003	154229	28014	32336	2578	4391	60	tp:A:P	cm:i:318	s1:i:2562	s2:i:437
53993a10-2ef9-4007-85ee-ebb8017078e9	5846	53	2232	+	8003	154229	25732	27940	1282	2241	60	tp:A:P	cm:i:168	s1:i:1271	s2:i:0
```

**Comment by sjackman** [comment]
Figured it out.
```
-r NUM       bandwidth used in chaining and DP-based alignment [500]
```
`minimap2 -x map-ont -r 1000` worked. Thanks for minimap2, Heng! It's working out pretty well for me.

**Comment by lh3** [comment]
If you generate base-alignment with `-c` or `-a`, minimap2 may align through the gap with another "long-join" heuristic that allows longer gaps. You can disable this heuristic with `--no-long-join`.

**Comment by sjackman** [comment]
Thanks, Heng. I'll try that.
