### ISSUE TITLE
Mapping RNA long reads to internal repeat regions in virus 

### ISSUE THREAD

**Issue by OscarChou211** [lh3/minimap2#650]
Hi there, 

I am trying to use minimap2 to map the direct RNA reads by ONT MINION onto a virus reference genome. 
The virus reference genome contain 6 repeats, which each repeat contains 2 exon. All the repeat contains the same bases, same sequence and the same arrangement. 

As such, given that I have RNA reads from this region, and I would like to conduct a splice aware direct RNA ONT mapping using the setting minimap2 -ax splice -uf -k14 ref.fa direct-rna.fq. 

Given that some reads are spliced such that it only contains 3/4/5 of the 6 repeats in the reference. I wonder how would the mapper decide which position would that reads being mapped into? Would it be random? Or would the mapper have certain preference (for example putting the reads from the last repeat first and fill up the last available position)? 

Thank you very much for helping!

**Comment by OscarChou211** [comment]
I realise that the mapper tends to put the repeat at the 3' end of the CDS, for example most of the repeat are putted to the later repeats in the 3' end. I wonder is that the case of the algorithm? Thank you!

**Comment by lh3** [comment]
I believe it is not the mapper. It is the protocol that tends to sequence from the 3'-end.

**Comment by OscarChou211** [comment]
I thought the reads in the fastq files are still in a continuous contig? As such, wouldn't it bases on the mapper to determine which repeat the sequence rest on during the aligning process?

**Comment by lh3** [comment]
I actually don't understand your question. Virus doesn't have splicing as I remember. Why do you talk about splicing and exons? Minimap2 places exact repeats randomly. Your observation has little to do with minimap2.

**Comment by OscarChou211** [comment]
Hmm there are splicing in DNA herpesvirus indeed, for example the EBV use different exon in different combinations to express its protein. But I see thank you very much for letting me know that it place the repeats randomly! Thank you!

**Comment by lh3** [comment]
Thank you. I stand corrected.

**Comment by OscarChou211** [comment]
Thank you very much for helping! And thank you so much for inventing all those amazing tools!
