### ISSUE TITLE
Mapping a bacterial draft genome assembly to a completed genome

### ISSUE THREAD

**Issue by ryotag** [lh3/minimap2#652]
Hello,
I have a draft genome assembly which was assembled using Illumina short reads.
I'd like to align this draft genome to a completed genome (both draft and completed genomes are from the same strain), and hoping to get correct alignments for contigs longer than 1000bp.
Can I use `minimap2 -cx asm5 completed.fasta draft.fasta` in this case?
In other words, can I use `-cx asm5` for the alignment of short-read assemblies to completed genomes?  According to the manual, this option is for long assemblies, and I'm not sure whether short contigs, i.e. between 1000bp and a few kilobases, can correctly be aligned.

Thanks!

**Comment by ryotag** [comment]
Probably solved.
There is a setting (probably) optimized for short-read assemblies in QUAST (`-c -x asm5 -B5 -O4,16 --no-long-join -r 85 -N 50 -s 65 -z 200 --mask-level 0.9 --min-occ 200 -g 2500 --score-N 2 --cs -t 3`).
Moreover, the mapping results using `-cx asm5` returned almost same results for my dataset and for my purpose.

**Comment by lh3** [comment]
Sorry for the late response. The right setting depends on the estimated divergence between your contigs and the reference genome. QUAST's setting is something between asm10 and asm20.
