### ISSUE TITLE
PAF cannot be converted to MAF

### ISSUE THREAD

**Issue by weiwFu** [lh3/minimap2#653]
Hi

I use MUMmer4 to perform alignments like this (nucmer -t 6 --mum -D 5 -p 26695.J99 H_pylori26695_Eslice.fasta H_pyloriJ99_Eslice.fasta). Now, I convert the delta file to paf, then to MAF format. PAF format can be converted successfully, but when PAF is converted to MAF, the following error is reported （WARNING: converting to MAF requires the 'cs' tag, which is absent on line 41）. How should I solve this 'CS' tag error ?

Thank you in advance
Weiwei Fu

**Comment by lh3** [comment]
paf2maf only works with PAF generated by minimap2.

**Comment by atongsa** [comment]
where can i get the paf2maf  script

**Comment by lh3** [comment]
```
paftools.js view -f maf
```

**Comment by atongsa** [comment]
thank you sir

**Comment by erika-r-moore** [comment]
Hello,

I am receiving this error, though I generated the paf files through minimap2. Here is an example command:
`~/minimap2-2.26_x64-linux/minimap2 -t26 -ax asm20 -k 21 --cs ./Helianthus_decontaminated.fasta.SOFTmasked ./acicarphahap1decontaminated.fasta.SOFTmasked > Helianthus_Acicarpha-cs.paf`

I tried with the --cs flag and without and get the following error:
`WARNING: converting to MAF requires the 'cs' tag, which is absent on line 1`

Below are the first few lines of one of my paf files:
```
head -n 20 Helianthus_Acicarpha.paf
@HD     VN:1.6  SO:unsorted     GO:query
@SQ     SN:Ha412HOChr01 LN:159217232
@SQ     SN:Ha412HOChr02 LN:184765313
@SQ     SN:Ha412HOChr03 LN:182121094
@SQ     SN:Ha412HOChr04 LN:221926752
@SQ     SN:Ha412HOChr05 LN:187413619
@SQ     SN:Ha412HOChr06 LN:157516673
@SQ     SN:Ha412HOChr07 LN:162054088
@SQ     SN:Ha412HOChr08 LN:177936428
@SQ     SN:Ha412HOChr09 LN:200254352
@SQ     SN:Ha412HOChr10 LN:190919061
@SQ     SN:Ha412HOChr11 LN:199477616
@SQ     SN:Ha412HOChr12 LN:179008902
@SQ     SN:Ha412HOChr13 LN:175682153
@SQ     SN:Ha412HOChr14 LN:189916084
@SQ     SN:Ha412HOChr15 LN:186609792
@SQ     SN:Ha412HOChr16 LN:218409126
@SQ     SN:Ha412HOChr17 LN:205797941
@PG     ID:minimap2     PN:minimap2     VN:2.26-r1175   CL:minimap2 -t26 -ax asm20 -k 21 ./Helianthus_decontaminated.fasta.SOFTmasked ./acicarphahap1decontaminated.fasta.SOFTmasked
scaffold_1      0       Ha412HOChr11    194203897       12      182120944S801M1D160M498D1522M5D397M5D115M47447616S      *     00       CCCAaaaccctaaaccctaaaccctaaccctaaaccctaaaccctaaaccctaaacccta
```

Do you know why this may be happening? Please let me know if you need any additional information!

Thanks!
Erika
