### ISSUE TITLE
Minimap2 and repeat masking

### ISSUE THREAD

**Issue by brettChapman** [lh3/minimap2#654]
Hi

I have a question in regards to how Minimap2 handles repeats, both hard-masked and soft-masked. Does it skip over masked regions, either soft-masked or hard-masked or only if its hard-masked? I'm aligning closely related sequences of the same species (different cultivars) using the asm5 parameter. I intend to produce PAF files, and later generate GFA files using Seqwish and then VG. My intention is to produce VCF files as well. I was wondering if using soft-masking would be picked up by Minimap2, or if hard-masking is the preferred masking method. 

Thanks.

**Comment by lh3** [comment]
Minimap2 ignores letter case. "ACGT" is treated the same way as "acgt". Please don't mask genomes. Masking leads to worse alignment.

**Comment by jingydz** [comment]
So how the Minimap2 deals with the highly repeat sequences?
