### ISSUE TITLE
Problem in indexing

### ISSUE THREAD

**Issue by code-acc** [lh3/minimap2#656]
Hello,

I am facing indexing problems on different versions of minimap2. When I git cloned minimap2, it installed v2.17-r974 dirty and gave the following warning for alignment and indexing:
"failed to parse the FASTA/FASTQ record next to "###" (some binary letters), Continue anyway"
Column 6 of a PAF output file is corrupted (since reference is not indexed properly) and displays some binary letters instead of reference chromosome names.

When I used conda, it installed v2.17-r941 and gave warning for indexing as:
wrong FASTA/FASTQ record. Continue anyway.

I then used minimap2 from a different server, which has version 2.17-r963-dirty (was installed sometime in the past by someone else). It didn't give any indexing or alignment warning. And surprisingly, it finished within an hour (as opposed to 4 days with v2.17-r974 dirty). The sizes of output files produced by these two versions are very different. 

Can you please help me in getting non-corrupt alignment/indexing and explain the time/size differences for two outputs. I am aligning HiFi reads to 785Mb reference genome.

Thank you,
Minal

**Comment by lh3** [comment]
r974 added more error checking. It is likely that your input is corrupted.

**Comment by rsharris** [comment]
@lh3 I assume you meant the input fasta or fastq file, right? The OP seems to think it was a corrupt index file.
