### ISSUE TITLE
asm and map-pb

### ISSUE THREAD

**Issue by code-acc** [lh3/minimap2#657]
Hello again,

1. In issue #638 you mentioned that both asm presets from help and manual are correct although different. I don't understand this correctly. Is it that help asm presets are for aligning reads to reference, and manual asm presets are for aligning assembly to the reference? If not, what's the correct interpretation?

2. I understand that asm20 preset is advised to align HiFi data to the reference genome. Does that mean map-pb is not an applicable option for HiFi reads alignment to the reference?  

3. The sequence divergence for my study organism is 0.3%. Since help asm presets are only for ~0.1/1/5% divergence, which preset is suitable for organisms not falling under defined divergence categories and which preset you think is suitable for my study organism?

**Comment by code-acc** [comment]
Hi Heng,

Could you please suggest a way to evaulate which alignment options (asm presets) work best for (1) genome to genome alignment and (2) HiFi reads to genome alignment?

Thank you,
Minal

**Comment by lh3** [comment]
Please just follow README.
