### ISSUE TITLE
Valid FASTQ file is read correctly by version 2.12 but gives error with version 2.13+

### ISSUE THREAD

**Issue by benwbooth** [lh3/minimap2#658]
I have a pair of paired-end FASTQ files that are read correctly by minimap version 2.12 and earlier, but fail with version 2.13+, including the newest version 2.17 and minimap2 built from master. The error message I get is:

`wrong FASTA/FASTQ record. Continue anyway.` on older minimap2 versions, and `failed to parse the FASTA/FASTQ record next to ''. Continue anyway.` on the git master version of minimap2.

I have run FASTQ validator and can confirm that the FASTQ files are valid.

Here are google drive links to the FASTQ files:

read1: https://drive.google.com/file/d/1W8Q7pGvOKX3hRl9jBkz9jP0CqFry6TvA/view?usp=sharing
read2: https://drive.google.com/file/d/1lE5pT6lh6lvF1N0nkGsT-mDC-W-nFVUR/view?usp=sharing

**Comment by benwbooth** [comment]
OK, I think I figured it out. This was my command:

minimap2 -aYx sr -t 64 assembly.fasta illumina_original_1.fastq.gz illumina_original_2.fastq.gz

The assembly.fasta file I was using was corrupted. I was looking at the FASTQ files and didn't check the FASTA subject file. Thanks!

**Comment by lh3** [comment]
Thanks for reporting anyway.
