### ISSUE TITLE
aligning gene annotation to genome

### ISSUE THREAD

**Issue by xbarvazx** [lh3/minimap2#661]
Hi,

What would be the best setup to align gene annotation as CDS to a relative genome assembly?

Thanks,
Raz

**Comment by lh3** [comment]
You can do that. I know some people are using minimap2 as a traditional cDNA-to-genome mapper.

**Comment by xbarvazx** [comment]
Yes but how?
Should I use 'asm' preset?

**Comment by lh3** [comment]
See Getting Started in README:

```sh
./minimap2 -ax splice:hq -uf ref.fa query.fa > aln.sam    # Final PacBio Iso-seq or traditional cDNA
```
