### ISSUE TITLE
Splice-aware alignment with up to 10% divergence

### ISSUE THREAD

**Issue by CIWa** [lh3/minimap2#662]
Hi,

I would like to map transcripts to a reference genome from the same species, but allowing for up to 10% divergence between transcript and genomic sequence. I was wondering how to tweak -x splice:hq for this? Or would you recommend to use -x splice instead, which I assume allows for up to 15% divergence, due to the sequencing quality of the long reads?

Thanks,
and best wishes,
Isabel

**Comment by lh3** [comment]
For 10% divergence, please use `-x splice`, not `-x splice:hq`. `splice:hq` is for divergence below a couple of percent.

**Comment by CIWa** [comment]
Hi Mr Li,

Thanks a lot for the fast help! Then I'll do that. But just for my records: How much divergence does -x splice approximately allow for?

Best wishes,
Isabel

**Comment by lh3** [comment]
The max divergence in theory is 33%. However, due to statistical fluctuation in divergence between regions, `-x splice` typically works with up to ~15% divergence in practice.

**Comment by CIWa** [comment]
All right, thank you!
