### ISSUE TITLE
Unmapped sequences are successfully mapped in another context

### ISSUE THREAD

**Issue by soungalo** [lh3/minimap2#663]
Hello,
I encountered a strange behavior and would appreciate some help understanding what's going on.
I am using minimap2 to align a whole genome assembly I created to the reference assembly of the same species, and then use the result to extract sequences present in the query, but not in the reference assembly - "novel sequences".
To validate my results, I took all novel sequences and re-mapped them to the reference using the same command. Surprisingly, a considerable proportion of the novel sequences could be mapped successfully.
**Example:**
I mapped my assembly to the reference by running:
`minimap2 -x asm5 -L -t 10 ref.fasta assembly.fasta -o result.paf -c`
and here is an excerpt from `result.paf`:
```
1_RagTag        28914594        3126344 3129434 +       1       30427671        3132840 3135960 3033    3121    60      NM:i:88 ms:i:1639       AS:i:1639       nn:i:0  tp:A:P  cm:i:201        s1:i:2054       s2:i:87 de:f:0.0200     zd:i:3  rl:i:20593      cg:Z:75M7D161M4D472M5D150M1I78M14D129M1D2024M
1_RagTag        28914594        3129513 3130750 +       1       30427671        3136052 3137289 1225    1237    60      NM:i:12 ms:i:1040       AS:i:997        nn:i:0  tp:A:P  cm:i:109        s1:i:1114       s2:i:87 de:f:0.0097     zd:i:2  rl:i:20593      cg:Z:1237M
1_RagTag        28914594        3131595 3155941 +       1       30427671        3137107 3161638 24028   24625   60      NM:i:697        ms:i:19523      AS:i:19899      nn:i:100        tp:A:P  cm:i:2164       s1:i:22420      s2:i:2166       e:f:0.0020     zd:i:3  rl:i:20593      cg:Z:22M3D843M336D1749M9D103M12I39M2D75M1D23M3D178M117I772M4D5881M2D3114M10I1441M2D156M1I730M1D673M1D5384M1I376M17I80M12D192M1I59M1D146M33I39M1D113M2I592M1D1372M
```
As you can see, the region between 3,130,750 and 3,131,595 on chromosome 1_RagTag is unmapped. I extracted the sequence and used the same minimap2 command to map it again to the reference, which resulted in:
```
1_RagTag_3130750-3131595        845     100     825     -       1       30427671        3106888 3107613 724     725     60      NM:i:1  ms:i:705        AS:i:705        nn:i:0  tp:A:P  cm:i:71 s1:i:698        s2:i:194        de:f:0.0014     rl:i:0  cg:Z:725M
```
So this region maps to a different place in the reference, but why wasn't this alignment found in the first run? Can you please help me understand why this is happening and suggest ways to improve results?
Thanks!

**Comment by lh3** [comment]
See #659

**Comment by soungalo** [comment]
Interesting. I wasn't aware that using `-c` can actually change the results - I was under the impression it simply adds the CIGAR information to the output. Maybe it should be indicated in the documentation.
I ran the same command without `-c`, and got:
```
1_RagTag        28914594        3060920 3130731 +       1       30427671        3065895 3137270 61922   72322   60      tp:A:P  cm:i:6040       s1:i:61716      s2:i:87 dv:f:0.0065     rl:i:12523
1_RagTag        28914594        3130911 3487045 +       1       30427671        3136460 3497738 307970  367631  60      tp:A:P  cm:i:29639      s1:i:307060     s2:i:943        dv:f:0.0083     rl:i:12523
```
So now the unmapped region is smaller: 3,130,731-3,130,911.
Using `-c -M0` doesn't seem to have any effect though. I need the CIGAR output because it allows me to extract unmapped regions from within alignments (long `I` operations in the CIGAR string). Can you please advice on how to proceed?
