### ISSUE TITLE
weird results in very simple case

### ISSUE THREAD

**Issue by aduclert** [lh3/minimap2#665]
Hello,

Having strange results on real Nanopore data, I tried to set up a very simple case. I created 2 fasta files with the same sequence :

tmpSeq.fas : 
>seq
ACGGACGTAGTCGATCACGATGAGCTATGTGCTAGAGCTAGCATTTTGGATCGATGTCATGGTACTAGCGTATCGAGCATCGAGTATGGTTAGC

and tmpRef.fas : 
>ref
ACGGACGTAGTCGATCACGATGAGCTATGTGCTAGAGCTAGCATTTTGGATCGATGTCATGGTACTAGCGTATCGAGCATCGAGTATGGTTAGC

1/ `minimap2 -a tmpRef.fas tmpSeq.fas`
gives me the following sam line : 

seq	0	ref	1	60	94M	*	0	0	ACGGACGTAGTCGATCACGATGAGCTATGTGCTAGAGCTAGCATTTTGGATCGATGTCATGGTACTAGCGTATCGAGCATCGAGTATGGTTAGC	*	NM:i:0	ms:i:188	AS:i:188nn:i:0	tp:A:P	cm:i:18	s1:i:89	s2:i:0	de:f:0	rl:i:0

a CIGAR of 94M which seems coherent to me since the seq is 94 bp and perfectly matching, but positions on ref sequence that are 1-60

Is there something I missed ?

Thanks

**Comment by lh3** [comment]
Read the SAM spec. 60 is mapping quality.

**Comment by aduclert** [comment]
_Very sorry_ for this careless mistake (I'm often using sam/bam ...), but it started from a real issue (at least I think) : 
if I get paf with above seq, I have : 

seq	94	1	90	+	ref	94	1	90	89	89	60	tp:A:P	cm:i:18	s1:i:89	s2:i:0	dv:f:0	rl:i:0

The  alignment does not extend on the whole sequence ?

More strangely, with another sequence (GAGGCTTGTGGAGGCGGTTTGAGCGTTGGGAGGCGGGCGGATGTGCTTATTGCTAGGGAGGGGCATTTAGGCGGATTGCGGGGCTATGGCATGC),

* if I get the paf, I have : 
seq	94	5	88	+	ref	94	5	88	83	83	60	tp:A:P	cm:i:13	s1:i:83	s2:i:0	dv:f:0	rl:i:0
(partial alignment from 5 to 88, BED-file convention)

* but with -c option to get the CIGAR, the alignment is full length this time : 
seq	94	0	94	+	ref	94	0	94	94	94	60	NM:i:0	ms:i:188	AS:i:188	nn:i:0	tp:A:P	cm:i:13	s1:i:83	s2:i:0	de:f:0	rl:i:0	cg:Z:94M

thanks for your time and sorry again for the first stupid submission.

**Comment by lh3** [comment]
Never mind. See the first item in [FAQ](https://github.com/lh3/minimap2/blob/master/FAQ.md).

**Comment by aduclert** [comment]
thanks a lot for your quick and clear answer.
