### ISSUE TITLE
Force Minimap2 to output 1 hit for each read?

### ISSUE THREAD

**Issue by niemasd** [lh3/minimap2#666]
In my tool called [ViralMSA](https://github.com/niemasd/ViralMSA), I'm wrapping around Minimap2 to perform reference-guided multiple sequence alignment for viral genomes, and the results have been excellent. Basically, I am using Minimap2 to map the assembled viral genomes against a reference, and then I'm merging the individual pairwise alignments into a multiple sequence alignment by using the positions of the reference genome as anchors (basically just parsing the CIGAR strings).

Things work fine on real datasets, in which we don't expect many large indels, but on simulated datasets, Minimap2 sometimes fails to align a genome with a lot of indels with respect to the reference genome, and as a result, those genomes are omitted from my output. Is there any way to force Minimap2 to output 1 hit for every read? I read the [manual page](https://lh3.github.io/minimap2/minimap2.html), but I didn't see anything that looked like what I want to do

**Comment by lh3** [comment]
Not possible. You have to filter out hits by yourself.
