### ISSUE TITLE
Piping minimap2 result to samtools sort in order to skip SAM file generation

### ISSUE THREAD

**Issue by ury** [lh3/minimap2#667]
Hi,
I'm using minimap2 for WGS with the GRCh38 reference.  I would like to skip the SAM file generation for performance and resource considerations, and pipe the minimap2 result to samtools sort in order to directly generate a BAM file.  Unfortunately, samtools sort issue the `failed to read header from "-"` error message.

I've read several references regarding this issue and I assume this is caused by minimap2 using a multi-part index, but I don't understand why this is the case and what would be a solution for my case.

First, I have counted the number of bases in reference:

`grep -v ">" GRCh38_full_analysis_set_plus_decoy_hla.fa | wc | awk '{print $3-$1}'                                                                                               `

Which resulted with 3217346917

Then I generated the index:

`minimap2 -x sr -d GRCh38_full_analysis_set_plus_decoy_hla.mmi GRCh38_full_analysis_set_plus_decoy_hla.fa`

I also tested the above with `-I 10G`, `-I 15G` etc. - all resulted with an identical mmi file.

The next step was performing alignment and SAM to BAM conversion:

`minimap2 -t 12 -2 -K 15G -R '@RG\tID:1\tSM:xxx\tPL:ILLUMINA\tLB:xxx\tPU:xxx:1' GRCh38_full_analysis_set_plus_decoy_hla.mmi xxx.READ1.fastq.gz 4874-xxx.READ2.fastq.gz | samtools sort -@ 2 -l 9 -o xxx.bam`

The output is as follows:
```
[WARNING] Indexing parameters (-k, -w or -H) overridden by parameters used in the prebuilt index.
[M::main::17.491*1.00] loaded/built the index for 3366 target sequence(s)
[M::mm_mapopt_update::21.992*1.00] mid_occ = 124
[M::mm_idx_stat] kmer size: 21; skip: 11; is_hpc: 0; #seq: 3366
[M::mm_idx_stat::24.867*1.00] distinct minimizers: 382142233 (93.76% are singletons); average occurrences: 1.331; average spacing: 6.325
samtools sort: failed to read header from "-"
```

I also tried the last command with various values for -K, but 15G seems to be optimal with my 32GB memory.

As I said, my goal is to skip the SAM file generation - any solution will do!

Relating to the process describe above, my more specific question is how to avoid multi-part index, which apparently causes samtools sort to fail due to the well-known reasons concerning multi-part index and the headers.

A following question is, if multi-part index cannot be avoided, how can the BAM file be created using pipe (for example, by suppressing the samtools sort error and generating the header later)?

Please let me know if anything is unclear or missing.

Thanks in advance,
  Ury

**Comment by lh3** [comment]
You are not generating SAM output. For short reads, add `-axsr`.

**Comment by ury** [comment]
So simple :)
Thank you very much!
