### ISSUE TITLE
How to calculate the value of the -t and -K parameters

### ISSUE THREAD

**Issue by ury** [lh3/minimap2#668]
Hi,
I'm trying to optimize the performance of minimap2 in terms of running time and resource utilization (without decreasing result 'quality').  Please assume that the result is not written to a file but rather piped into samtools sort in order to create a BAM file.

1. Is there a way to calculate an optimal value for the -K parameter, based on the available memory and threads, index/FASTQ file sizes and/or number of bases, or any other parameters?
2. Specifically, can I configure the parameters to ensure that index/FASTQ files are loaded in whole to the memory in the beginning of the execution, so no further blocking I/O operation will occur?
3. If the index and FASTQ files reside in a RAM drive (so reading them is extremely fast), how should the -K parameter be configured?
4. Is there a practical limit on the number of threads which can be utilized to provide significant performance boost?
5. Any other optimization considerations I can utilize?

Thanks,
  Ury

**Comment by lh3** [comment]
Typically you don't need to change -K. Set -t to the number of available CPU threads on your machine.
