### ISSUE TITLE
Left and right DP extension for long reads

### ISSUE THREAD

**Issue by cjain7** [lh3/minimap2#669]
Hi Heng,

This is just a question to better understand minimap2 heuristics for right and left DP extension used during long read alignment.

The minimap2 publication says: _If base-level alignment is requested, minimap2 applies dynamic programming (DP) to extend from the ends of chains and to close regions between adjacent anchors in chains._  Could you please share more information about the extension step done at both ends? In particular, I'd like to know whether the complete un-aligned read segment is tested using z-drop heuristic; or just a small region decided based on minimizer window length? Can this length be tuned by users from command line or by adjusting the code?

I'm able to spot the code in align.c [(this line)](https://github.com/lh3/minimap2/blob/c9874e2dc50e32bbff4ded01cf5ec0e9be0a53dd/align.c#L690) but the code there is quite dense, and I failed to understand.

Thanks in advance!

**Comment by lh3** [comment]
Mostly up to option `-g`, but there are other heuristics. See ~30 lines above your quoted line.

**Comment by cjain7** [comment]
Got it!
