### ISSUE TITLE
TLEN not correctly output in SAM

### ISSUE THREAD

**Issue by haotianteng** [lh3/minimap2#67]
Just use minimap2 to align a Nanopore sequence, it seems like the TLEN is always 0 in the output SAM file. Is there any flag to be used so that minimap2 can write this information to the SAM file?
command I used:
./minimap2 -ax map-ont ref.fa some.fastq > aln.sam

**Comment by lh3** [comment]
TLEN is always 0 for single-end reads. This conforms to the SAM spec.

**Comment by lh3** [comment]
BTW, PAF (option -c) is usually more convenient for long reads.

**Comment by haotianteng** [comment]
Thanks a lot. Got it from the python interface mappy.

**Comment by lh3** [comment]
Good, as long as you find a solution. Thanks.
