### ISSUE TITLE
Reproducing results in Table 1

### ISSUE THREAD

**Issue by christian-lanius** [lh3/minimap2#671]
Hi everyone,
I am attempting to reproduce some of the findings of the minimap2 paper in order to have a way to analyze the impact of modifications of the algorithm. I assume that the values presented in Table 1 are a good metric to use. Unfortunately, I am not a biologist, so I am unsure on how to exactly obtain these values. Can someone point me in a direction where I can find an example implementation of the metrics or a different way I can quantify the algorithms alignment performance?

Kind regards,
Christian

**Comment by lh3** [comment]
Are you dealing with genomic reads or RNA-seq reads? If genomic, Fig 1 is more relevant. Read the cookbook. If RNA-seq, download the data and run `paftools.js junceval` against known annotations.

**Comment by christian-lanius** [comment]
Thank you very much for your help, I mdid not realize that the cookbook contains this information.
