### ISSUE TITLE
question regarding soft trimming

### ISSUE THREAD

**Issue by jsalemq** [lh3/minimap2#673]
I am using minimap2 for mapping targeted PE NGS data. The NGS reads were generated from reference material where all of the variants are known and confirmed by Sanger sequencing.

These particular reads have a 84-bp deletion variant. However, but my variant caller doesn't see it because most of the reads containing the deletion are soft-clipped. You can see in the IGV image that 2 reads show the correct alignment, but the others were clipped. How can I adjust minimap2 settings to force the clipped reads to align correctly?

![image](https://user-images.githubusercontent.com/66969568/94309786-9de44d80-ff46-11ea-9fb6-862785847ed3.png)

**Comment by lh3** [comment]
Run indel realignment.
