### ISSUE TITLE
Mapping Pacbio CCS long read to cyclic reference genome

### ISSUE THREAD

**Issue by lindongdo** [lh3/minimap2#676]
Hi Heng,
I am using minimap2 to align CCS reads from cyclic DNA to a reference genome which is linearized.  Here is my command:
minimap2 -a -x map-ont --eqx -L -O 5,56 -E 4,1 -B 5 -z 400,50 -r 2k 
I have a lot of supplementary alignments from those reads across the origin and end of reference genome, which is not desired. Do you have any suggestion in setting minimap2 to enable the alignment directly to cyclic reference genome?

Thanks
Dongdong

**Comment by chucknordy** [comment]
I also am interested in this question.  Is there a way to index or flag a genomic reference as being circular, so that mappings across the origin show up as single alignments rather than being chimeric?

**Comment by lh3** [comment]
Won't be supported in a foreseeable future. SAM doesn't support such alignment, either.
