### ISSUE TITLE
different (better) mapping results with option -c for CIGAR output

### ISSUE THREAD

**Issue by MarkusHaak** [lh3/minimap2#679]
The manual describes the effect of giving option -c as follows:

`Generate CIGAR. In PAF, the CIGAR is written to the ‘cg’ custom tag.`

I was therefore surprised to find that minimap2 not only takes much longer to run if option -c is given (5-10x in my case) but also produces a different mapping result. At first sight, the quality of the produced alignments seems to be substancially worse if no CIGAR string is written to the paf file, in the sense that alignments are often shorter than the ones produced if option -c is given. The mapping quality of alignments written to .bam files seems to be equivalent to writing the output to .paf files with CIGAR output.

I double checked my minimap2 version, it's 2.17-r941. The described effects were observed mapping nanopore reads to a referece with option -x map-ont.

Do you have an explanation for this behaviour?

Thanks a lot,
Markus

**Comment by lh3** [comment]
See FAQ.
