### ISSUE TITLE
question on "mappy" python binding usage

### ISSUE THREAD

**Issue by phiweger** [lh3/minimap2#68]
I am interested in excising the mapped subsequence of a given read from it.

Is the following code doing this (irrespective of the strand a read was mapped to, I assume):

```python
# i is of type <mappy.Alignment>
excision = seq[:i.q_st] + seq[i.q_en+1:]
```

Thank you very much.

**Comment by lh3** [comment]
You extracted unaligned part and concatenated them together. If you want to get aligned part, you should
```python
subseq = seq[i.q_st:i.q_en]
```

**Comment by phiweger** [comment]
Perfect, thank you!

**Comment by lh3** [comment]
Actually, to excise aligned regions, you should use
```python
excision = seq[:i.q_st] + seq[i.q_en:]
```
without "+1".

**Comment by phiweger** [comment]
Oh, indeed, thanks for spotting this.
