### ISSUE TITLE
Long insertion penalties for -xsplice

### ISSUE THREAD

**Issue by dbobr** [lh3/minimap2#682]
Hello,

I am performing some alignments with `-xsplice` parameters with direct RNA nanopore seq data. In that preset description it says that "long insertions are disabled". However, even after tweaking some more parameters (like gap open/extension penalties and chain elongation parameters) I still get alignments that have large insertions followed by similar sized introns. This isn't surprising as I am aligning some transcripts that have repetitive sequences. But I am wondering how the `-xsplice` mode disables long insertions and if there is any way for me to penalize those long insertions even more to reduce the likelihood of getting introns followed by long insertions.

On the same note, I am wondering if `INT2` does anything for the `-O` option in splicing alignments, considering that the documentation says `INT2` doesn't do anything in the `-E` option when in splice mode.

Any info on this appreciated! Thanks a lot

Dmitriy

**Comment by bellpepper91** [comment]
Hi,

I'm looking for more information on this aspect of the -x splice preset also.

If I understand correctly, the -g option may specify what a "long insertion" is limited to. -g is set to 10000 by default, but is set to 2000 in the splice preset. This may mean that the maximum insertion length in splice mode is 2000bp, or I may be interpreting this parameter wrong.

Thoughts?
Sam

**Comment by lh3** [comment]
It is on command-line prompt:

```sh
-G NUM       max intron length (effective with -xsplice; changing -r) [200k]
```
