### ISSUE TITLE
Query start and end positions in SAM output

### ISSUE THREAD

**Issue by franrodalg** [lh3/minimap2#683]
Hi @lh3. Great work!

As far as I'm aware, SAM alignments don't include the query start and end information that PAF output does. Is there any reason for this? Would it be possible to do so as additional SAM tags?

Cheers,
Fran

**Comment by lh3** [comment]
You get the coordinate by parsing the CIGAR. Nearly all NGS aligners work this way.

**Comment by franrodalg** [comment]
So when there are multiple alignments per read, the CIGARs reflect the shift in the start location in each case, perhaps with a number of Ss? In other words, do the CIGARs always span the entirety of the read, not only the particular alignment itself?

Generally, NGS aligners don't deal with long reads, so the entirety of the read (or at least the great majority of the read) should correspond to a single alignment, so I understand why it's not necessary in that case. Here, I find it a really useful information in PAF, that I think SAM would also benefit from.

**Comment by GenomeRIK** [comment]
Hi Fran,
This explanation of cigar strings might clarify things:
https://drive5.com/usearch/manual/cigar.html

Basically it shows exactly how the sequence is aligned to the reference.

Cheers,
Richard

**Comment by franrodalg** [comment]
Hi Richard, thanks so much for this. Yes, I'm aware of how CIGAR strings work and I've parsed them in the past. I just wasn't aware if for reads with multiple alignments you would get information about the entire read or just about the particular alignment in that entry.

**Comment by GenomeRIK** [comment]
Hi Fran, 

Ok I think I understand what you are asking now. When you say a read with multiple alignments, do you mean chimeric alignments? If so, the ends which may be mapped elsewhere are usually represented as hard clips "H".

So if you have a 1000bp sequence and half maps to Chrom1 and the other half to Chrom2 then the CIGAR for the first half would be 500M500H and for the second half would be 500H500M. These would be represented in 2 SAM lines using the same read ID.

Is that what you mean?

Cheers,
Richard

**Comment by franrodalg** [comment]
Not really chimeric, but I suppose it would be treated similarly. I think that I've seen Ss in previous alignments, but not Hs, though. 

In our case, we deal with the ribosomal DNA, a highly repetitive region, in which multiple units appear in tandem (and its consensus reference is not included in the genome assemblies, so we append it as a separate chromosome). Sufficiently long reads will thus show multiple consecutive alignments to that same consensus reference, and its important to easily identify each throughout the read (so the start and end positions of the alignment are key).

Thanks so much for your help, Richard.

**Comment by lh3** [comment]
The bottomline is: you can get all PAF information from the SAM output.
