### ISSUE TITLE
Reads mapped outside of header range?

### ISSUE THREAD

**Issue by Maillinia** [lh3/minimap2#684]
Hi,
I have mapped my data to a large genome. 
I used the following command:
minimap2 -ax map-ont -t 20 Hordeum_vulgare.IBSC_v2.dna.toplevel.fa.gz input.fastq.gz -I8g > output.sam

I  had to use the -I8g to get any output with sam header. I can sort the sam/bam file fine, but I cannot index the bam file afterwards.

I get the following error when I run
samtools index output.bam
[E::hts_idx_push] Region 536914232..536915093 cannot be stored in a bai index. Try using a csi index with min_shift = 14, n_lvls >= 6
samtools index: failed to create index for "output.bam": Numerical result out of range

How come my reads are falling outside of the header range? Or what else is going on?

Here is some information about the headers and values:
LN headers in bam file:
@SQ     SN:chr1H        LN:558535432
@SQ     SN:chr2H        LN:768075024
@SQ     SN:chr3H        LN:699711114
@SQ     SN:chr4H        LN:647060158
@SQ     SN:chr5H        LN:670030160
@SQ     SN:chr6H        LN:583380513
@SQ     SN:chr7H        LN:657224000
@SQ     SN:chrUn        LN:249774706
@SQ     SN:Mt   LN:525599
@SQ     SN:Pt   LN:115974

minimum and maximum starting coordinates of the reads:
0 768054506

Maximum LN value:
768075024

**Comment by Maillinia** [comment]
I found the issue. 
My chromosome lengths are longer than allowed for bai index.
Issue solved by creating a csi index instead.
samtools index -c output.bam

**Comment by lh3** [comment]
Sorry for the late response and thank you for the update!
