### ISSUE TITLE
How to set the minimum percentage of read length which could still map to reference?

### ISSUE THREAD

**Issue by APZPM** [lh3/minimap2#688]
Hello everyone?
I am wondering if I could set the mapping options in a way which would allow mapping also reads which would map to reference in only 50% of their length?

So when you have small circular DNA/RNA fragments and the contigs of those fragments assembled in longer fragments than the original circular molecule was long,  I would like to "detect/map" also those longer contigs.

Many thanks!

**Comment by lh3** [comment]
Post-filter the output with a script.

**Comment by APZPM** [comment]
Thank you lh3. Do you maybe know how to write it? I don't have so much skils. So, for example, I have contig which is long 2000 bp since it assembled 2 1000bp long reads. Originally the reference is long just 1000 bp. I would like that also the contig of 2000 bp (so is just doubled the same sequences) will map to the reference.


Many thanks if you could help!
