### ISSUE TITLE
Error mapping long reads, core dumped

### ISSUE THREAD

**Issue by aderzelle** [lh3/minimap2#69]
Hello, I am trying to map a set of Oxford nanopore reads with minimap2 

```
minimap2 all_p_ctg.fa BXQ_F_ONT_1_FAH31515_A.fastq
minimap2: sketch.c:83: mm_sketch: Assertion `len > 0 && (w > 0 && w < 256) && (k > 0 && k <= 28)' failed.
zsh: abort (core dumped)  minimap2 all_p_ctg.fa BXQ_F_ONT_1_FAH31515_A.fastq
```

Does this mean the indexing assumptions are not met by my reference genome? 

Thanks a lot

**Comment by lh3** [comment]
You have a sequence of zero length, either in your reference genome or in reads.

**Comment by lh3** [comment]
At least one of your contigs has zero length. I could make the error message more informative, but this is really the problem with your data.

**Comment by aderzelle** [comment]
thanks for the really fast answer. Indeed ... I used the bbmap script "reformat" to reformat the reference fasta and it's working now. 

thanks!

**Comment by lh3** [comment]
I will leave this issue until I make the error message more informative to future users. Thanks a lot for the confirmation.

**Comment by lh3** [comment]
Added with fec7bd7. Thanks.
