### ISSUE TITLE
segfault mapping huge dataset (acontigs to pcontigs)

### ISSUE THREAD

**Issue by gconcepcion** [lh3/minimap2#692]
Hi Heng,

I'm experiencing a segfault trying to map the Redwood a-contigs to the p-contigs.

I'm running on an 80 core machine w/ 790Gb RAM.

I realize trying to map 16Gb of contigs to a 33Gb reference is going to be challenging and compute/memory intensive. Are there any parameters I should optimize for a mapping of this magnitude?

I'm assuming it's failing because it's hitting a memory limit?

```minimap2 --split-prefix temp --eqx -t 80 -ax asm5 redwood_pcontigs.fa.gz redwood_acontigs.fa.gz > redwood_acontigs_mapped.sam```

```
[M::mm_idx_stat::8325.467*43.37] distinct minimizers: 187645488 (74.76% are singletons); average occurrences: 2.149; average spacing: 9.967
[M::worker_pipeline::8376.213*43.39] mapped 233 sequences
[M::worker_pipeline::8433.389*43.38] mapped 245 sequences
[M::worker_pipeline::8529.882*43.18] mapped 247 sequences
[M::worker_pipeline::8586.676*43.18] mapped 256 sequences
[M::worker_pipeline::8626.602*43.26] mapped 262 sequences
[M::worker_pipeline::8672.520*43.30] mapped 252 sequences
/var/spool/gridengine/execd/mp2022-sge/job_scripts/5654841: line 15: 235030 Segmentation fault      (core dumped) minimap2 --split-prefix ${PREFIX} --eqx -t ${THREADS} -ax asm5 ${REFERENCE} ${QUERY} > ${OUTPUT}.sam
```

**Comment by gconcepcion** [comment]
To answer my own question - setting a very large index `-I36g` solved the problem.

**Comment by lh3** [comment]
Thank you and sorry for the late response. There is probably still something going wrong with the `--split-prefix` mode. Nonetheless, as you don't have the problem for now, I will investigate at a later time.
