### ISSUE TITLE
Minimap2 index in shared memory

### ISSUE THREAD

**Issue by lpryszcz** [lh3/minimap2#693]
Hi, first of all, fantastic tool @lh3 !  
Would it be possible to share minimap2 index among multiple instances of the mapper? Something of the sort was available in STAR-mapper.  
It'd be super beneficial for applications with on-the-fly mapping (ie. data coming from the sequencer in small batches) or where multiple instances of the mapper need to be launched simultaneously (my case). Creating/loading index for each instance is waste of time and resources, especially for larger references. 
Cheers,

**Comment by lh3** [comment]
I fully understand why you prefer a shared index – that's why bwa-mem has this feature. Unfortunately, it is technically challenging to implement shared index in minimap2 as the index has many components. I may not have the time to implement it soon.

**Comment by lpryszcz** [comment]
@lh3 is there a way of running minimap2 as a service? Let say I'd spawn a dedicated process just for basecalling that would read a batch of sequences from `stdin` and spit SAM to `stdout`?  

I know roughly how to set it up, but how to make sure that minimap2 processes all reads from given job / batch? 
I'm aware of `-K NUM       minibatch size for mapping [500M]`.

**Comment by lh3** [comment]
Closing. You can implement a server in pythhon with mappy.
