### ISSUE TITLE
sam/bam transform into paf

### ISSUE THREAD

**Issue by zhoudreames** [lh3/minimap2#698]
if the sam/bam data can transform into paf formate data ?

**Comment by zhoudreames** [comment]
@jmarshall @junaruga @jts @tseemann

**Comment by lh3** [comment]
paftools.js sam2paf

Always check paftools.js first.

**Comment by zhoudreames** [comment]
> paftools.js sam2paf
> 
> Always check paftools.js first.
if you could sent me a mannual about paftools usage,i cant find it on websites,
