### ISSUE TITLE
incorrect sam output for large genomes > 4G

### ISSUE THREAD

**Issue by grendon** [lh3/minimap2#699]
I have the latest version of minimap2 installed. I ran minimap2 with a large genome assembly and HiFi reads. The output sam file seems useless because samtools complains that the file is truncated. 

This is my cmd: 

minimap2 -ax asm20  -t 12 -a hifiasm.contigs.fa   HiFi.fastq > HiFi_aln2_hifiasm.sam

Is there anything that I can change in  my cmd to produce a correct sam file?  

Your help will be greatly appreciated.

**Comment by lh3** [comment]
Use `-I100g` or `--split-prefix`. See FAQ.
