### ISSUE TITLE
PAF output

### ISSUE THREAD

**Issue by fbemm** [lh3/minimap2#7]
Am I right that the lastest commit does not produce PAF output anymore?

**Comment by lh3** [comment]
Still the same: PAF by default; `-a` enables SAM output.

**Comment by fbemm** [comment]
`minimap2 -asm10 TAIR10.fasta Can-0.fasta > Can-0.paf`

`Chr1    0       Chr1    26371669        60      26803084S743M1I1136M1I874M1D855M1I141M1I217M7I618M14D493M1D874M3D168M1I1610M1D624M10I515M3D170M1I77M2I201M1I38M1D100M2I2M4I1764M1D252M1I253M1D2485M1D6420M1I112M3D1M3D342M51D268M4D10M1D225M1D888M1D143M1I722M18D2809M1I
Chr1    2048    Chr1    29300709        60      29750704H232M1I171M15D173M1D14M12I202M2D1M1D2M2D54M3D4M1I26M1I4044M1D2M1D1200M2D922M1D967M1D839M1D1052M3D207M1I1537M6I46M6D18M6D338M5D333M22D274M1I30M1D237M1I433M3D283M4I343M3I211M1D403M1I1055M7D198M1D216M2I13M1I843M
Chr1    2048    Chr1    27635958        60      28067805H90M6I71M4I10M1D163M1D26M8D2M1D289M2D25M1I115M1I247M12I89M1I247M1D1M263D26M27I245M24D83M3D132M1D24M2I4M1I66M3D1M1D275M4I19M1I25M9I88M2I22M1I71M2D2M1D54M10D36M1D63M1D64M1D70M1D1M1D2M1D186M1D5M5I77M5I1079M12I11
Chr1    2048    Chr1    7028045 60      7057878H157M10D394M1D44M3D12M1D34M2D18M1I276M1D1M1D97M1D133M11I39M9I228M1I52M1I407M3D1384M1I27M16D131M1D27M1I57M6D1M5D25M3D7M1D60M5D16M5D6M4I2M1D31M1D844M6D873M5D57M5D230M6D84M5I31M5I1172M8D73M2D19M2098D383M2D31M25D42M28D175
Chr1    2048    Chr1    28527673        60      28958659H224M5D82M1D1169M2I3695M3I78M2D17M27I920M16D3603M105D1380M4I7M3D1M1I502M1I672M1D333M3D1260M1I3148M26I158M1D43M20D209M1D482M1I37M1I204M1I511M1D1053M2D8951M1D138M1I805M1D8630M3I642M1I858M1D2970M1D237M35D92M1D46
C`

Output is the same with -a. Looks like a sam file to me.

**Comment by lh3** [comment]
You need to use `-x asm10`. `-asm10` is equivalent to `-a -sm10`.

**Comment by fbemm** [comment]
Dammit ... blind here! Thanks
