### ISSUE TITLE
soft clipped reads

### ISSUE THREAD

**Issue by kanchanhole** [lh3/minimap2#70]
Hello,

I have used Minimap2 for mapping ONT reads with the human genome. The resulting bam file contains alignment with soft-clipped reads. Is there any in  minimap2 way where I get aligned reads without the soft clipped reads. ?

**Comment by lh3** [comment]
No, that is not possible. Both nanopore and pacbio may produce garbage sequences and chimeric reads that are technical artifacts. Clipping is the only right way to report them.

**Comment by kanchanhole** [comment]
Thank you. In the alignment file, I am looking at a specific region which is 2000 bp long and few reads show mapping which is below the length of 2000 bp, however, few reads are above 2000 bp. 

Does this mean this is ONT long reads technical artifact? and I should discard such reads?

**Comment by lh3** [comment]
Not necessarily. It could be caused by misassemblies in your reference genome or larger structural variations.
