### ISSUE TITLE
The first read only gets one hit.

### ISSUE THREAD

**Issue by c2997108** [lh3/minimap2#703]
I used latest minimap2 with the following command.

./minimap2/minimap2 -x asm20 -t 10 c.fa d.fa

[c.zip](https://github.com/lh3/minimap2/files/5888819/c.zip)

The columns 1-9 of the output is 
```
d1      306542  1       306539  +       c1      306542  1       306539
d2      207229  0       207227  +       c2      207229  0       207227
d2      207229  24      207208  +       c3      207147  4       207146
d2      207229  0       203560  +       c1      306542  102979  306539
d3      207147  4       207146  +       c3      207147  4       207146
d3      207147  4       207146  +       c2      207229  24      207208
d3      207147  4       203498  +       c1      306542  103003  306539
...
```

The sequences of "c" is same as the sequences of "d". However, the hits do not contrast between c and d. 
d1 only hits c1, but c1 hits all d1-d9. (d1 should hit all c1-c9.)
c2-c9 and d2-d9 contrast with each other.

**Comment by lh3** [comment]
> d1 should hit all c1-c9

The output is expected. d1-d2 hit is too weak in comparison to d1-c1.

**Comment by c2997108** [comment]
Thank you! I didn't know what was causing the problem and was panicking. I understood this is due to the specification that minimap2 tries to pick up the best alignment.

**Comment by lh3** [comment]
You need -xava-ont, -xava-pb, -X or -P if you want to output all hits. It will be slower and can be a lot slower if you need base alignment.
