### ISSUE TITLE
Does the -uf tag work when using hg38 as reference?

### ISSUE THREAD

**Issue by hukai916** [lh3/minimap2#706]
I came across this question when I was trying to leverage the Minimap2 package to map direct-RNA reads with the -uf tag. Since the -uf forces Minimap2 to map reads to the forward transcript strand only, does that work using hg38 as a reference rather than the transcriptome given that hg38 has transcripts in both orientations?

Any input will be highly appreciated.

**Comment by lh3** [comment]
Yes, `-uf` works with hs38 as the reference genome. The option mostly regulates how minimap2 looks for the GT-AG splicing signal. If a gene is on the forward strand of hs38, minimap2 looks for GT-AG. If on the reverse strand, minimap2 looks for CT-AC.
