### ISSUE TITLE
paftools call missing variants in the assembly flanks

### ISSUE THREAD

**Issue by elcortegano** [lh3/minimap2#708]
I am using `paftools call` to call variants in an assembly-to-reference alignment, with the recommended command line instruction:

    minimap2 -cx asm10 --cs reference.fa assembly.fa | sort -k6,6 -k8,8n | paftools.js call -f reference.fa -

The resulting analysis however, seems to start calling variants only after the first ~3 Mb of sequence, and similarly seems to ignore the last Mbs. My first thought was that these regions are not well aligned, but the following command does the job an I can see these regions aligned in IGV.

    minimap2 -ax asm10 -t6 reference.fa assembly.fa | samtools sort -@6 -T tmp -O bam -o assembly.bam -

I also have previous knowledge of variants that should be present in these flaking sequences. When I go to the coordinates in IGV to visualize the alignment, they are present. However, they are missing from paftools output. Why could this happen? Thank you.

**EDIT** In case it helps, the data comes from PacBio HiFi.

**Comment by lh3** [comment]
paftools.js call thinks alignments there are not reliable and filters them out.
