### ISSUE TITLE
Why it gives different result when sequence files are flipped? 

### ISSUE THREAD

**Issue by jnarayan81** [lh3/minimap2#71]
[qseq.fa.tar.gz](https://github.com/lh3/minimap2/files/1518552/qseq.fa.tar.gz)
[seq1.fa.tar.gz](https://github.com/lh3/minimap2/files/1518553/seq1.fa.tar.gz)

minimap2 -c qseq.fa seq1.fa > aln.paf

chr1	76	0	76	+	seq2	76	0	76	76	76	40	NM:i:0	ms:i:152	AS:i:152	nn:i:0	tp:A:P	cm:i:9	s1:i:70	s2:i:70	cg:Z:76M
chr1	76	0	76	+	seq4	78	0	78	72	78	0	NM:i:6	ms:i:120	AS:i:120	nn:i:0	tp:A:S	cm:i:5	s1:i:52	cg:Z:29M2D47M	
chr2	76	0	76	+	seq3	76	0	76	76	76	40	NM:i:0	ms:i:152	AS:i:152	nn:i:0	tp:A:P	cm:i:9	s1:i:70	s2:i:70	cg:Z:76M
chr2	76	0	76	+	seq4	78	0	78	72	78	0	NM:i:6	ms:i:120	AS:i:120	nn:i:0	tp:A:S	cm:i:5	s1:i:52	cg:Z:29M2D47M	
																				
minimap2 -c seq1.fa qseq.fa > aln.paf
																		
seq1	76	0	76	+	chr1	76	0	76	76	76	1	NM:i:0	ms:i:152	AS:i:152	nn:i:0	tp:A:P	cm:i:9	s1:i:70	s2:i:70	cg:Z:76M
seq2	76	0	76	+	chr2	76	0	76	76	76	1	NM:i:0	ms:i:152	AS:i:152	nn:i:0	tp:A:P	cm:i:9	s1:i:70	s2:i:70	cg:Z:76M
seq3	76	0	76	+	chr1	76	0	76	76	76	1	NM:i:0	ms:i:152	AS:i:152	nn:i:0	tp:A:P	cm:i:9	s1:i:70	s2:i:70	cg:Z:76M
seq4	78	0	78	+	chr2	76	0	76	72	78	1	NM:i:6	ms:i:120	AS:i:120	nn:i:0	tp:A:P	cm:i:5	s1:i:52	s2:i:52	cg:Z:29M2I47M

It did miss alignment between chr1-vs-seq4 !!

**Comment by lh3** [comment]
This is a bug. Fixed via af1d6af. Thanks a lot!
