### ISSUE TITLE
Extract unmapped reads

### ISSUE THREAD

**Issue by desmodus1984** [lh3/minimap2#710]
Hi,
I have ONT reads and I would like to know how to extract those reads that map to either the Y or the X chromosome.
I am doing genome assembly and I would like to differentiate the autosomes from the sexual chromosomes.
Also, my main goal is to separate the autosomes from the sexual chromosomes of a genome assembly - using the Y and X chromosomes. I used pomoxis to assemble the genome using a reference genome from a related species, and got 92 long scaffolds/fragments. I would like to just get only the autosomes to do a PSMC analysis, which otherwise will be biased by including the Y and X - since I sequenced a male.

Thank you very much;

**Comment by lh3** [comment]
You can write a python/perl script to do that.
