### ISSUE TITLE
truncated file of the output SAM

### ISSUE THREAD

**Issue by btrainee** [lh3/minimap2#712]
Hello,everyone:
     I have used minimap2 to map pb ccs reads to a genome assembly by hifiasm. I used the following command:
`minimap2 -t 20 -ayYL --MD --eqx -x asm20  ref.hifiasm.fa reads.fq > aln2self.sam`
Minimap2 works perfectly fine and ends with no error at all. However when I try to convert the sam file to a bam file, I can't , an error reported, the sam file is a truncated file. 
`[M::main] Real time: 4155.933 sec; CPU: 82250.736 sec; Peak RSS: 24.994 GB
[E::sam_parse1] unrecognized type e
[W::sam_read1] Parse error at line 831
[main_samview] truncated file.`
line 831 is the first line in addition to the title：
`t00000001       16      ptg000010l      119320595       60      17S98=1D10=1D48=1D166=1D74=1X438=1I211=1I6=1D73=1D134=1I98=1X115=1I129=1I181=1
D58=1X1=1X239=1D65=1D114=1I134=1X144=1D211=1I249=1I50=1D113=1I39=1I89=1I10=1X57=2D1X26=1I149=1I77=1D4=1D114=1D51=1D282=1I53=1I60=1X55=1I239=1D
46=3X269=1D138=1I92=1I32=1I531=3I213=1I47=1X51=1I52=1I396=2I87=1X49=1D24=2I163=1D71=1X101=4D24=1D21=1D168=1D19=1D34=1D31=1I100=1I349=1D162=1D4
4=1X75=3X39=1D11=2X13=1D149=1I165=1D45=1I7=1I19=1I451=3D71=1X127=1D498=1X52=1D200=1D47=1I22=1X166=1I331=2D112=1I106=1D75=1X63=1D15=1X87=1D173=
1X8=1X223=      *       0       0`
then I converted the fq file to a fa file ti align use minimap2 , but the same error !

I have no clue what is happening about this align.

Many thanks for your help!

**Comment by lh3** [comment]
Are your reads named like `t00000001`? Is the input correctly formatted?

**Comment by abdo3a** [comment]
Hey guys, Any solution for this issue yet?

i had similar problem, Minimap2 works fine and ends with no error. when I try to convert the sam file to a bam file, I had an error that the sam file is a truncated file.

[bam_header_read] EOF marker is absent. The input is probably truncated.
[bam_header_read] invalid BAM binary header (this is not a BAM file).
Segmentation fault

**Comment by RNieuwenhuis** [comment]
Bump, just had the same issue. Same command as OP. The command is mentioned on the GATK forums (https://gatk.broadinstitute.org/hc/en-us/community/posts/360072716972-Variant-calling-with-PacBio-HiFi-reads)
```
minimap2 --version
2.17-r941
```
`minimap2 -t 16 --MD --eqx -ayYLx asm20 ref.fasta reads.fastq.gz > output.sam`
```
samtools -@6 output.sam > output.bam

[E::sam_parse1] unrecognized type 7
[W::sam_read1] Parse error at line 23240381
samtools sort: truncated file. Aborting
```
```
samtools --version
samtools 1.9
Using htslib 1.9
Copyright (C) 2018 Genome Research Ltd.
```
```
wc -l output.sam
24503490
```
Line 23240381 in output.sam
[Line_23240381.txt](https://github.com/lh3/minimap2/files/6208009/Line_23240381.txt)

I don't see anything wrong with it. Hope this helps to solve it or maybe we can find a useful default command for using minimap2 and GATK with HIFI reads.

**Comment by lh3** [comment]
Thanks, @RNieuwenhuis. As there is no follow-up from OP, I am closing this.
