### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by aberaslop** [lh3/minimap2#716]
Hi,

I am analyzing around 60 fungal genomes (21-60Mb) with funannotate, which uses minimap2. For most of the genomes everything has worked fine, but for a small fraction, minimap2 fails. I contacted the funannotate developers, but we didn't find the problem. 
I then tried to run minimap2 outside of funannotate for all of those genomes that failed, and all were successful except one.

This is the script I have run: 
minimap2 -ax splice -t 16 --cs -u b -G 3000 /home/aberas2/data/Esco-predict/done/ETZET_predict/predict_misc/genome.softmasked.fa ETZET_predict/predict_misc/transcripts.combined.fa | samtools sort --reference /home/aberas2/data/Esco-predict/done/ETZET_predict/predict_misc/genome.softmasked.fa -@ 4 -o ETZET_predict/predict_misc/transcripts.minimap2.bam

And this is the error:

[M::mm_idx_gen::1.944*1.00] collected minimizers
[M::mm_idx_gen::2.431*1.93] sorted minimizers
[M::main::2.431*1.93] loaded/built the index for 336 target sequence(s)
[M::mm_mapopt_update::2.599*1.87] mid_occ = 111
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 336
[M::mm_idx_stat::2.723*1.83] distinct minimizers: 8486809 (91.03% are singletons); average occurrences: 1.289; average spacing: 2.938
Segmentation fault

I am running minimap2 v 2.17-r941 within a conda environment, in a Debian GNU/Linux 10, 24 cores, ~ 264 GB RAM. Python: 3.7.9

Any help is greatly appreciated!

**Comment by aberaslop** [comment]
Hi, 

Actually, I have found a second genome that hasn't worked:

minimap2 -ax splice -t 16 --cs -u b -G 3000 /home/aberas2/data/EAECHR_predict/predict_misc/genome.softmasked.fa EAECHR_predict/predict_misc/transcripts.combined.fa | samtools sort --reference /home/aberas2/data/EAECHR_predict/predict_misc/genome.softmasked.fa -@ 4 -o EAECHR_predict/predict_misc/transcripts.minimap2.bam

[M::mm_idx_gen::2.421*1.00] collected minimizers
[M::mm_idx_gen::3.146*1.49] sorted minimizers
[M::main::3.146*1.49] loaded/built the index for 25 target sequence(s)
[M::mm_mapopt_update::3.377*1.46] mid_occ = 45
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 25
[M::mm_idx_stat::3.536*1.44] distinct minimizers: 8590064 (91.76% are singletons); average occurrences: 1.185; average spacing: 2.946
Segmentation fault

Any idea of how to fix this? Thank you so much!

**Comment by lh3** [comment]
Do you have a sample to trigger the issue? It is nearly impossible to debug without data. Thanks.

**Comment by aberaslop** [comment]
Would send you the two files work?

**Comment by lh3** [comment]
That would be good. Thanks.

**Comment by aberaslop** [comment]
Please, find the files in this link (they were too big to paste here): https://drive.google.com/drive/folders/1JnVvPJdfSCzXylbee0HJNCKcsaL9eIFs?usp=sharing 
Thanks!

**Comment by lh3** [comment]
I didn't see any segfaults on your first file. Could you separate minimap2 and samtools command line?

**Comment by aberaslop** [comment]
Hi,
I followed your instructions and that solved the segmentation fault problem for both genomes. Thank you very much! 

For future reference, or if it helps anybody, this is what I did: 

minimap2 -ax splice -t 16 --cs -u b -G 3000 /home/aberas2/data/still-working/ETZET_predict/predict_misc/genome.softmasked.fa ETZET_predict/predict_misc/transcripts.combined.fa > output.sam

The terminal output was:

[M::mm_idx_gen::6.308*0.44] collected minimizers
[M::mm_idx_gen::8.170*0.60] sorted minimizers
[M::main::8.171*0.60] loaded/built the index for 336 target sequence(s)
[M::mm_mapopt_update::8.716*0.59] mid_occ = 111
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 336
[M::mm_idx_stat::8.943*0.59] distinct minimizers: 8486809 (91.03% are singletons); average occurrences: 1.289; average spacing: 2.938
[M::worker_pipeline::106.393*2.60] mapped 24626 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -ax splice -t 16 --cs -u b -G 3000 /home/aberas2/data/still-working/ETZET_predict/predict_misc/genome.softmasked.fa ETZET_predict/predict_misc/transcripts.combined.fa
[M::main] Real time: 106.682 sec; CPU: 276.540 sec; Peak RSS: 2.331 GB

Then I did:

samtools sort --reference /home/aberas2/data/still-working/ETZET_predict/predict_misc/genome.softmasked.fa -o ETZET_predict/predict_misc/transcripts.minimap2.bam -@ 4 output.sam

The terminal output was: [bam_sort_core] merging from 0 files and 4 in-memory blocks...

I have since then provided the resulting bam file to the pipeline I was using (funannotate) and it worked perfectly. 

Thanks again for your time and help!

**Comment by lh3** [comment]
Thanks for the confirmation. I don't see anything wrong with your original command line, but usually during debugging, it is usually better to avoid unix pipes.
