### ISSUE TITLE
Forcing a single long match

### ISSUE THREAD

**Issue by tnn111** [lh3/minimap2#717]
I'm trying to align bacterial genomes that are quite close to each other. I'm finding that minimap2 breaks the alignments at gaps of 100-200 nucleotides. I've played with -r and setting it to 1,000 seems to help but not quite enough. I still get some that break more than I'd like. The command I have been using is 

minimap2 -t 20 -c -x asm5 -r 1000 target query > align.paf

Are there other ways of tweaking this?

Thanks.

**Comment by lh3** [comment]
Try larger -z.
