### ISSUE TITLE
how to get around the base limitation when working with Nanopore whole genome sequencing data?

### ISSUE THREAD

**Issue by lentil824** [lh3/minimap2#718]
Hi there,

I noticed this in github "Minimap2 does not work with a single query or database sequence ~2 billion bases or longer (2,147,483,647 to be exact). The total length of all sequences can well exceed this threshold.". My file would exceed this for sure. So, I was wondering what would be a better way to get around this? 

Thanks,
Susan

**Comment by rob-p** [comment]
This restriction corresponds to an individual contig / chromosome, not the entire _genome_.  Are you saying you have a case where your individual contigs / chromosomes are > 2Gbp?

**Comment by lentil824** [comment]
Thank you for the reply! My misunderstanding apparently.
