### ISSUE TITLE
Merge supplementary alignments with main alignment in SAM output?

### ISSUE THREAD

**Issue by niemasd** [lh3/minimap2#720]
I am mapping viral consensus sequences against the viral reference genome as follows:

```bash
minimap2 -t 8 --secondary=no --sam-hit-only -a -o OUTPUT.sam REFERENCE.fa.mmi INPUT.fas
```

Normally, I get a single line in the SAM for each consensus sequence. However, on 
[this consensus sequence](https://github.com/lh3/minimap2/files/6199086/orig.fas.txt), I get 2 lines in the [output SAM file](https://github.com/lh3/minimap2/files/6199098/orig.fas.sam.txt): one primary alignment and one supplementary alignment:

```
@SQ	SN:MN908947.3	LN:29903
@PG	ID:minimap2	PN:minimap2	VN:2.17-r941	CL:minimap2 -t 8 --secondary=no --sam-hit-only -a -o OUTPUT.sam REFERENCE.fa.mmi INPUT.fas
original	0	MN908947.3	7326	60	7286S22371M	*	0	0	CTTTCGA...
original	2048	MN908947.3	40	60	6747M22910H	*	0	0	CTTTCGA...
```

As can be seen, these two segments are completely non-overlapping. What exists between them in the original sequence is a long sequence of `N`s (which I imagine is why Minimap2 split them up). Is there any way to have Minimap2 merge these two into a single alignment in the SAM output? E.g. ideally the following (because all of the letters between the two alignments are the `N`s that were in the input, which I'd like to keep in the output):

```
original	0	MN908947.3	40	60	29657M	*	0	0	CTTTCGA...
```

**Comment by lh3** [comment]
Did you introduce the gap?

**Comment by niemasd** [comment]
Yes, the `NNNNNN...` is in the input sequence before it gets sent to Minimap2 (the input sequences are SARS-CoV-2 genome consensus sequences, which generally have `NNNNN...` in stretches that were too low-coverage during amplicon sequencing)

**Comment by lh3** [comment]
Make sense. You may try `--score-N=0`. Not sure if it works.

**Comment by niemasd** [comment]
That worked perfectly! Thank you so much!

**Comment by lh3** [comment]
Great. Sorry for the late response.

**Comment by niemasd** [comment]
No worries at all! I appreciate the help :-)
