### ISSUE TITLE
Segmentation fault (core dumped) when align ccs transcript to reference genome

### ISSUE THREAD

**Issue by niehu2018** [lh3/minimap2#721]
Hi,

minimap2 return Segmentation fault (core dumped)  when align ccs transcript to reference genome with junction-bed option:

GTF file:
wget -c ftp://ftp.ensemblgenomes.org/pub/release-50/plants/gtf/arabidopsis_thaliana/Arabidopsis_thaliana.TAIR10.50.gtf.gz

Genome file
wget -c ftp://ftp.ensemblgenomes.org/pub/release-50/plants/fasta/arabidopsis_thaliana/dna/Arabidopsis_thaliana.TAIR10.dna.toplevel.fa.gz

unizp
gzip -dc Arabidopsis_thaliana.TAIR10.dna.toplevel.fa.gz >Arabidopsis_thaliana.TAIR10.dna.toplevel.fa
gzip -dc Arabidopsis_thaliana.TAIR10.50.gtf.gz >Arabidopsis_thaliana.TAIR10.50.gtf

junction bed
paftools.js gff2bed Arabidopsis_thaliana.TAIR10.50.gtf >Arabidopsis_thaliana.TAIR10.50.gtf.bed

create index
minimap2 -x splice -t 20 -d Arabidopsis_thaliana.mmi Arabidopsis_thaliana.TAIR10.dna.toplevel.fa

align
Command 1:
minimap2 -ax splice -uf --secondary=no -t 7 -L --MD --cs Arabidopsis_thaliana.mmi input.fastq.gz

Command 2:
minimap2 -ax splice -uf --secondary=no -t 7 -L --MD --cs --junc-bed Arabidopsis_thaliana.TAIR10.50.gtf.bed Arabidopsis_thaliana.mmi input.fastq.gz

[input.fastq.gz](https://github.com/lh3/minimap2/files/6204810/input.fastq.gz)

I succeed to run command 1 and failed to run command 2.
Command 2 returned no alignment and reported Segmentation fault (core dumped).
![report](https://user-images.githubusercontent.com/6246674/112479217-c8a54680-8daf-11eb-8a11-b8cfbbe182d2.png)
![report2](https://user-images.githubusercontent.com/6246674/112479545-1d48c180-8db0-11eb-8f5a-a023edbe820c.png)

minimap2 and paftools.js version
2.17-r941

**Comment by niehu2018** [comment]
I found the problem. There are spaces in the gene name.
5       1919079 1921425 AT5G06290.1|protein_coding|2 Cys Prx B  1000    +       1919379 1921208 0,128,255       7       528,75,82,80,126,114,331,      0,928,1120,1291,1545,1790,2015,
5       1919178 1921425 AT5G06290.2|protein_coding|2 Cys Prx B  1000    +       1919379 1921013 0,128,255       6       429,75,82,80,126,556,  0,829,1021,1192,1446,1691,

I replaced the spaces with - in the gene name, then the command 2 succeed.
5       1919079 1921425 AT5G06290.1|protein_coding|2-Cys-Prx-B  1000    +       1919379 1921208 0,128,255       7       528,75,82,80,126,114,331,      0,928,1120,1291,1545,1790,2015,
5       1919178 1921425 AT5G06290.2|protein_coding|2-Cys-Prx-B  1000    +       1919379 1921013 0,128,255       6       429,75,82,80,126,556,  0,829,1021,1192,1446,1691,

**Comment by niehu2018** [comment]
I found the problem. There are spaces in the gene name.
5       1919079 1921425 AT5G06290.1|protein_coding|2 Cys Prx B  1000    +       1919379 1921208 0,128,255       7       528,75,82,80,126,114,331,      0,928,1120,1291,1545,1790,2015,
5       1919178 1921425 AT5G06290.2|protein_coding|2 Cys Prx B  1000    +       1919379 1921013 0,128,255       6       429,75,82,80,126,556,  0,829,1021,1192,1446,1691,

I replaced the spaces with - in the gene name, then the command 2 succeed.
5       1919079 1921425 AT5G06290.1|protein_coding|2-Cys-Prx-B  1000    +       1919379 1921208 0,128,255       7       528,75,82,80,126,114,331,      0,928,1120,1291,1545,1790,2015,
5       1919178 1921425 AT5G06290.2|protein_coding|2-Cys-Prx-B  1000    +       1919379 1921013 0,128,255       6       429,75,82,80,126,556,  0,829,1021,1192,1446,1691,

**Comment by psur9757** [comment]
@niehu2018 I am getting a similar error. Can you please share the code that you used to fix the error? Thank you.

Command: `minimap2 -t 8 -ax map-pb $ref $data --secondary=no > aln.sam`

Error:
```
[M::mm_idx_gen::32.491*1.59] collected minimizers
[M::mm_idx_gen::34.917*2.02] sorted minimizers
[M::main::34.942*2.02] loaded/built the index for 7374 target sequence(s)
[M::mm_mapopt_update::35.769*1.99] mid_occ = 2495
[M::mm_idx_stat] kmer size: 19; skip: 10; is_hpc: 1; #seq: 7374
[M::mm_idx_stat::36.289*1.98] distinct minimizers: 34096848 (47.86% are singletons); average occurrences: 5.592; average spacing: 8.155
[M::worker_pipeline::358.096*7.25] mapped 22026 sequences
[M::worker_pipeline::676.182*7.58] mapped 21602 sequences
[M::worker_pipeline::1003.322*7.63] mapped 21679 sequences
/var/spool/PBS/mom_priv/jobs/5357521.pbsserver.SC: line 27: 91905 Segmentation fault      (core dumped) minimap2 -t 8 -ax map-pb $ref $data --secondary=no > aln.sam
[W::sam_read1] Parse error at line 99314
```

**Comment by lh3** [comment]
This a bug. Minimap2 takes both spaces and tabs as field separators. TAIR10 puts spaces in gene names, which breaks minimap2. Now fixed at github HEAD. Thanks.
