### ISSUE TITLE
Questions about finding overlaps between RNA-seq long reads

### ISSUE THREAD

**Issue by lauraht** [lh3/minimap2#725]
Hi Heng,

I have some quick questions about finding overlaps between RNA-seq long reads and would appreciate your advice:

(1) When using minimap2 to find overlaps between RNA-seq long reads, is there any difference (in terms of command-line options) from using minimap2 to find overlaps between DNA long reads?

Does finding read-to-read overlaps of RNA-seq reads involve any “splice-awareness”?

(2) When finding read-to-read overlaps, in the output PAF format, the query read’s start/end coordinates are measured from its own first base (not related to the reference read’s coordinate system), right?

(3) In minimap2, is a minimizer’s position its ending position (i.e. the position of the last base of the minimizer)?

Thank you very much!

**Comment by lh3** [comment]
1. DNA reads don't have alternative splicing.
2. Both. See the [PAF format](https://github.com/lh3/miniasm/blob/master/PAF.md).
3. Yes.

**Comment by lauraht** [comment]
Thank you so much Heng!

About my first question, what I mean is, when using minimap2 to find overlaps between RNA-seq long reads, do we need to add any specific command-line option (i.e.  -x splice ) in addition to our options used for finding overlaps between DNA long reads?

Thank you very much for your help!
