### ISSUE TITLE
Should we use the “-x splice” option for all-vs-all overlap mapping of ONT RNA-seq reads?

### ISSUE THREAD

**Issue by lauraht** [lh3/minimap2#728]
Hi Heng,

I just wanted to know, for all-vs-all overlap mapping of ONT RNA-seq reads, should we use the “-x splice” option?

I read that with the “-x splice” option, long deletions are taken as introns, and long insertions are disabled. But for all-vs-all overlap mapping, long deletions for one read would be the long insertions for the other read, so I am not sure if we should still use the “-x splice” option.

Also, for all-vs-all overlap mapping of ONT reads, we need to use the “-x ava-ont” option. In this case, should we put “-x splice” before or after “-x ava-ont” (since they have different -g values)?

Thank you very much!

**Comment by lh3** [comment]
Sorry, minimap2 doesn't work that way. You should use ava-ont and postprocess results by yourself.

**Comment by lauraht** [comment]
Thanks Heng!

I was wondering if you could give me some suggestions on what postprocessing we would need for all-vs-all overlap mapping of ONT RNA-seq reads?

The output PAF file from minimap2 gives the overlapping region (start/end coordinates) on each read of the read-pair. So what kind of postprocessing would we need on this PAF file when overlapping the RNA-seq reads?

Thank you so much!

**Comment by lh3** [comment]
I don't know for sure as I haven't analyzed such data. I guess the key is to identify whether two reads come from the same isoform. There are long-read transcript assembly papers you can read to get ideas.

**Comment by lauraht** [comment]
Thank you Heng for your suggestion!

I would like to confirm one thing with you about minimap2.
When using the “-x ava-ont” option to get all-vs-all overlap mapping of RNA-seq reads: 
Suppose we have two RNA-seq reads _r1_ and _r2_ which come from different isoforms. The region-1 [10, 20] plus region-2 [40-50] on _r1_ overlap with the region-3 [10, 30] on _r2_. That is, there is a 20-bp splice junction between region-1 and region-2 on _r1_, while _r2_ does not have this splice junction. In this case, does minimap2 report the matching minimizers only inside region-1 [10, 20] and region-2 [40-50] on _r1_ even though the reported overall overlap region on _r1_ is [10, 50]?

If the answer is “yes,” I think we may define a minimum splice junction size (for example, 50). For a pair of reads,  if all distances between the identified matching minimizers < 50 on each of the two reads, we may consider that these two reads come from the same isoform. I was wondering if you think this makes sense?

However, the large gaps between matching minimizers might still be due to sequencing errors rather than alternative splicing. In this case, it would be difficult to know whether a large gap is a true splice junction or not. For example, I got the matching minimizers’ positions for two reads (both are RNA-seq ONT reads) from minimap2 as follows:
Query read:
 (length, starting/ending positions of overlap region): 1270    195     1232
matching minimizers’ positions: 209,210,218,220,224,524,525,530,532,535,703,705,706,707,708,1097,1162,1210,1231
Target read:
(length, starting/ending positions of overlap region): 1081    21      1048
matching minimizers’ positions: 35,36,44,46,50,348,349,354,356,359,526,528,529,530,531,920,982,1027,1047
Both reads have 3 consistent large gaps between their matching minimizers.

Another thing I would like to confirm with you:  although minimap2 shows the percentage of singletons among distinct minimizers, the reported minimizers in the overlap regions between two reads are not singletons and they are the matching minimizers of the two reads, right?

Thank you very much for your help!
