### ISSUE TITLE
too long soft-clip for asm5?

### ISSUE THREAD

**Issue by wangyugui** [lh3/minimap2#73]
Hi.

An 1000M1000D135674M is reported as 1000S135674M when -x asm5.
this soft-clip is OK for raw pacbio, but too long for asm5?

An 1999M1999D133675M is reported well.

mapping:
minimap2 -a -x asm5 /usr/bio-ref/GRCh38.p11.dnaref/dnaref.fa.asm5.mmi DEL.fa

index:
minimap2 -x asm5

```
# minimap2 --version
2.5-r601-dirty
```

**Comment by lh3** [comment]
Soft-clipping is never "too long". In full-genome alignment, megabase-long clipping is common.
