### ISSUE TITLE
[Question] Does Minimap2 facilitate split-read alignment across multiple reference sequences (i.e. chromosomes)?

### ISSUE THREAD

**Issue by majorkazer** [lh3/minimap2#730]
Hello,

This is really a question rather than an issue or bug: is minimap2 capable of aligning reads across multiple reference sequences (i.e. chromosomes)? In other words, is minimap2 capable of aligning chimeric/fusion reads when using the splice argument that are likely from trans-fusion events? If so, are these reported in the chimeric reads in the output SAM, and if not, would these reads be unmapped?

Thanks!

**Comment by lh3** [comment]
Yes. Read the sam spec for output.

**Comment by majorkazer** [comment]
Hi, thanks for getting back to me.

Yes - I followed the other issues as to how to find chimeric reads from the output BAMs. Does the -G intron size parameter have a strong effect on trans-fusion mapping, or is that restricted to gaps in cis?
