### ISSUE TITLE
Error on installation in Ubuntu

### ISSUE THREAD

**Issue by davezing** [lh3/minimap2#733]
I am trying to install Minimap2 on Ubuntu using the instructions in Getting Started:

git clone https://github.com/lh3/minimap2
cd minimap2 && make

When I run the make command, I get the following error:

cc -c -g -Wall -O2 -Wc++-compat -DHAVE_KALLOC main.c -o main.o
cc -c -g -Wall -O2 -Wc++-compat -DHAVE_KALLOC kthread.c -o kthread.o
cc -c -g -Wall -O2 -Wc++-compat -DHAVE_KALLOC kalloc.c -o kalloc.o
cc -c -g -Wall -O2 -Wc++-compat -DHAVE_KALLOC misc.c -o misc.o
cc -c -g -Wall -O2 -Wc++-compat -DHAVE_KALLOC bseq.c -o bseq.o
bseq.c:1:10: fatal error: zlib.h: No such file or directory
#include <zlib.h>
^~~~~~~~
compilation terminated.
Makefile:39: recipe for target 'bseq.o' failed
make: *** [bseq.o] Error 1

Am I doing something wrong?
Thanks,
Dave

**Comment by davezing** [comment]
I figured it out.  It works if you install libz-dev.
Also, this was on Ubuntu 18.  The apt install for Ubuntu 20 gets a later version of minimap2.

**Comment by helan-1997** [comment]
> I figured it out. It works if you install libz-dev. Also, this was on Ubuntu 18. The apt install for Ubuntu 20 gets a later version of minimap2.

Is libz-dev or zlib-dev ?
