### ISSUE TITLE
long introns despite using max intron length using -G option

### ISSUE THREAD

**Issue by vkkodali** [lh3/minimap2#735]
I am running `minimap2` using the `-G 1300000` option but I still see introns that are longer than 1.3Mbp. Is that expected? #701 asks the same question but it was closed by the reporter without any comments.

**Comment by bellpepper91** [comment]
Might be trivial but are you putting the -G option before or after other options? Order matters, and I believe you want your -G option after whichever presets you are working with.

**Comment by lh3** [comment]
-G is approximate.

@bellpepper91 Order doesn't matter. Please create a new issue. Yours is different.
