### ISSUE TITLE
map-hifi preset missing

### ISSUE THREAD

**Issue by harisankarsadasivan** [lh3/minimap2#739]
@lh3 
https://github.com/lh3/minimap2/releases/tag/v2.18

Pls note the map-hifi preset is missing in the latest release. Was this intentional? How do I align https://storage.googleapis.com/pepper-deepvariant-public/sequencing_data/PacBio_HiFi/HG002/HG002_35x_PacBio_14kb-15kb.fastq.gz

**Comment by lh3** [comment]
Use the HEAD.

**Comment by sashulkaSh** [comment]
@shelkmike , why do you think so? manual does not have this information
