### ISSUE TITLE
Filtering assembly to ref alignement

### ISSUE THREAD

**Issue by aureliendejode** [lh3/minimap2#743]
Hello,

I am building a new reference genome from long and I 'd like to compare that with a previous reference.
I'd like to see how contigs in the reference correspond to contigs in the new assembly.
I used the following command line: minimap2 -cx asm5 ref_assembly new_assembly > aln.paf.

Do you have recommendations to filter the aln.paf file ?

Thanks

**Comment by lh3** [comment]
This depends on your goal and downstream steps. Filtering is mostly a trial-and-error thing: try something, see the result and then tune.
