### ISSUE TITLE
paf file is too big

### ISSUE THREAD

**Issue by ardy20** [lh3/minimap2#746]
I am running Rala to layout the overlaps of pacbio (CLR) reads. However, the paf file generated by minimap2 is too large and needs a huge memory (I guess 1 TB).

Is there anyway that we can reduce the size of paf file. I used the following command to generate paf (overlap file):

minimap2 -x ava-pb -t 24 pb-WRB.fasta pb-WRB.fasta | gzip -1 > WRB.paf.gz

**Comment by lh3** [comment]
Minimap2 overlapping is discouraged now. Use a dedicated assembler such as Raven, wtdbg2, flye and shasta.
