### ISSUE TITLE
Map PacBio HiFi/CCS genomic reads

### ISSUE THREAD

**Issue by Jiangyuan-Liu** [lh3/minimap2#747]
Hi, I would like to map CCS reads (.fastq) to my reference genome (.fa) by using -x **map-hifi**. However, the minimap2.1 does not support "map-hifi". I installed minimap2 using conda (https://anaconda.org/bioconda/minimap2). Could you help me to deal with PacBio CCS reads? Thanks.

  Preset:
    -x STR       preset (always applied before other options; see minimap2.1 for details) []
                 - map-pb/map-ont - PacBio/Nanopore vs reference mapping
                 - ava-pb/ava-ont - PacBio/Nanopore read overlap
                 - asm5/asm10/asm20 - asm-to-ref mapping, for ~0.1/1/5% sequence divergence
                 - splice/splice:hq - long-read/Pacbio-CCS spliced alignment
                 - sr - genomic short-read mapping

**Comment by Anna-pro** [comment]
Hi, I have actually the same question: want to run "map-hifi" with my PacBio-HiFi sequencing data, but ended up with an error "[ERROR] unknown preset 'map-hifi'". How can I fix that? Thank you!
