### ISSUE TITLE
What is the difference between splice and map-ont ?

### ISSUE THREAD

**Issue by Ayse1006** [lh3/minimap2#750]
Hi, so I'm trying to find the best mapping condition for my data. 

I have to do whole genome mapping (human) using a mix of long read and short read. So what I did was to take 10000 reads (random) from each fastq file and merge them together and then map them to reference (only chromosome21) and check quality (qualimap).

I tried both splice and map-ont for mapping but I don't really understand the result I'm getting. The values are already low because 30000 random reads mapped on chr21 is already low but:
For map-ont I have a mean coverage of 0.0486 and mean mapping quality of 12.98.
While for splice I have a mean coverage of 13.9762  and mean mapping quality of 0.2.
I don't understant why there is that much difference.

I would love to have a feedback about that. I'm new to this kind of process.

**Comment by lh3** [comment]
splice for long-read RNA-seq against a reference genome.
