### ISSUE TITLE
Sequences are not mapped completely with default output

### ISSUE THREAD

**Issue by TorHou** [lh3/minimap2#751]
Hello minimap2 team,

I tried mapping specific genes to an assembly and found a problem when using minimap2 in its default mode:
The coordinates in the PAF-output indicate that the gene does not map completely to the assembly, i.e. a few bases are missing in the beginning and the end.
`minimap2 -x asm10 assembly.fasta genes.fasta`
```
DPA2*02:01	5543	7	5540	-	contig_1	5037124	4597659	4603206	5276	5549	60	tp:A:P	cm:i:506	s1:i:5276	s2:i:231	dv:f:0.0034	rl:i:53
```
This would of course not necessarily be a problem, but I checked the sequences and found that the ends of the gene and the assembly match perfectly.
I then tried to understand why minimap2 thought they don't match and wanted to look at the CIGAR string of the SAM output... and found that the problem disappeared.
`minimap2 -x asm10 -a assembly.fasta genes.fasta`
```
DPA2*02:01	16	contig_1	4597657	60	405M1D238M1D126M1D922M1D723M1D62M2D1263M1D121M1D184M1D181M1D208M1D524M1D458M1D128M	*	0	0	<>	*	NM:i:22	ms:i:5227	AS:i:5227	nn:i:0	tp:A:P	cm:i:506	s1:i:5276	s2:i:231	de:f:0.0038	rl:i:53
```
I checked several different settings for `-x` and versions 2.17 and 2.20 of minimap2. And found this problem consistently. Interestingly the problem also disappears when outputting the CIGAR in the PAF output.
`minimap2 -x asm10 -c assembly.fasta genes.fasta`
```
DPA2*02:01	5543	0	5543	-	contig_1	5037124	4597656	4603213	5535	5557	60	NM:i:22	ms:i:5227	AS:i:5227	nn:i:0	tp:A:P	cm:i:506	s1:i:5276	s2:i:231	de:f:0.0038	rl:i:53	cg:Z:405M1D238M1D126M1D922M1D723M1D62M2D1263M1D121M1D184M1D181M1D208M1D524M1D458M1D128M
```

This seems to be unwanted behavior of minimap2 to me. Please let me know if you need more details or some data files for reproducing this output.

**Comment by lh3** [comment]
See [FAQ](https://github.com/lh3/minimap2/blob/master/FAQ.md#1-alignment-different-with-option--a-or--c).
