### ISSUE TITLE
Use Minimap2 for alignment to reference transcriptome

### ISSUE THREAD

**Issue by EOrput** [lh3/minimap2#757]
Hello. I have a question in regards to using minimap2 to align Nanopore direct cDNA reads to a reference transcriptome as opposed to a genome. Is this something that is possible or is minimap2 for use with whole genomes references only? If it is possible, what would be the optimal options to use for the indexing and for the alignment. I have looked in the manual but feel a bit overwhelmed with how many options there are. Any advice you have on this topic would be greatly appreciated. Thanks!

**Comment by EOrput** [comment]
I apologize for commenting again, but I could really use some help regarding this matter, thanks.

**Comment by lh3** [comment]
If unsure, use the default and then tune when you see problems.
