### ISSUE TITLE
Cut new release

### ISSUE THREAD

**Issue by armintoepfer** [lh3/minimap2#76]
Could you please cut a new release from HEAD that I can use to create an external wrapper?

Thank you!

**Comment by armintoepfer** [comment]
Version 2.5 can already be used: https://github.com/armintoepfer/minimap2-meson

**Comment by lh3** [comment]
v2.5 is good for now. v2.6 will take a few more weeks. I need to test the current HEAD more thoroughly before cutting a new release.

**Comment by lh3** [comment]
v2.6 is released.
