### ISSUE TITLE
Unexpected chromosome coverage on large genomes

### ISSUE THREAD

**Issue by auryjm** [lh3/minimap2#762]
Hi, 

I used minimap2.20 to align illumina short-reads on a 15Gb genome with the following parameters : "-t 32 -2 --sam-hit-only -a -ax sr" and observed a weird coverage on two chromosomes (50% higher than the others), which was not expected.

I ran minimap2.20 using a higher value for the -I parameter : "-I 17G -t 32 -2 --sam-hit-only -a -ax sr" and observed, this time, consistent coverage across all chromosomes.

I didn't expect the -I parameter to impact output alignments, right ?

Thank you,

**Comment by lh3** [comment]
To get more consistent results for large genomes, you need to use `--split-prefix`. If you have enough memory, a large `-I` is always preferred.
