### ISSUE TITLE
-ax map-ont output.sam analysis 

### ISSUE THREAD

**Issue by khush876** [lh3/minimap2#767]
Hi, 

I have assembled a plant genome using HIFIASM from PACBIO raw reads. Later, I cleaned haplotype (.gfa/fasta) using RACON and have PACBIO.polished.fasta file. Now I am polishing my reads PACBIO cleaned assembly with Nanopore using Minimap2 command below

minimap2 -ax map-ont PACBIO.polished.fasta ONT.fastq -o PACBIO.ONT.sam

later using SAMTOOLS and converted them to .bam and sorted.bam. I did SAMTOOL stat

However, I have few questions 
1. How can I check if my PACBIO.ONT.sam generated by Minimap2 is correctly done? Are there any stat to be performed to see whether the assembly is correct?
2. Do you recommend any software other than SAMTOOLs which can accept .sam format from Minimap2 and perform some basic stat?
3. What else can I look into this data?

Thank you

**Comment by lh3** [comment]
Import with samtools is probably the simplest solution to you.

> Later, I cleaned haplotype (.gfa/fasta) using RACON and have PACBIO.polished.fasta file.

Please don't polish with racon. That only reduces consensus accuracy.
