### ISSUE TITLE
Are the end positions (col 4 and 9 in paf) 1-based?

### ISSUE THREAD

**Issue by YongLiedu** [lh3/minimap2#77]
The query end (column 4) and target end (column 9) in paf file are 1-based, not 0-based as described in https://github.com/lh3/miniasm/blob/master/PAF.md, is this right?

> DN9090_c0_g1_i1	407	0	**407**	-	tig00008355	785960	22655	**23062**	406	407	7	NM:i:1	ms:i:404	AS:i:404	nn:i:0	tp:A:P	cm:i:134	s1:i:398	s2:i:397	cg:Z:407M

**Comment by lh3** [comment]
By convention, "0-based" also implies half-close-half-open. In your example, the coordinate of the matched region is [0,407). This is exactly like BED.
