### ISSUE TITLE
Exact meaning of --cs=none

### ISSUE THREAD

**Issue by wm75** [lh3/minimap2#770]
From the manual I would expect `--cs=none` to be equivalent to not specifying `--cs` at all.
However, it seems that with PAF format the outputs are not identical. Is this intended or a bug?

**Comment by lh3** [comment]
See FAQ.

**Comment by wm75** [comment]
Hmm, so you're saying `--cs=none` is interpreted as explicitly asking for imprecise, fast mode, while not specifying `--cs` at all gives you accurate mode?

**Comment by lh3** [comment]
Looking at code, I think you are right that `--cs=none` is not equivalent to no `--cs`. Just avoid `--cs=none`.
