### ISSUE TITLE
Append extra Tag from fastq sequence name

### ISSUE THREAD

**Issue by ruqianl** [lh3/minimap2#772]
Hi,

is there any way to tell minimap2 to grab the tags in fastq sequence headers and append them to the alignment records?

Such as 
@J00137:172:H5L2LBBXY:3:1125:23937:11636        CB:Z:TAAACCGGTTAGTCAC-1

Thanks
Ruqian

**Comment by lh3** [comment]
```
-y        Copy input FASTA/Q comments to output.
```
