### ISSUE TITLE
Total alignments : 0 / Minimap2 Rna-Seq

### ISSUE THREAD

**Issue by cagataykos** [lh3/minimap2#773]
I have human RNA-Seq dataset it has two different barcodes in the different folder. I aligned with that command
 `minimap2 -ax splice -uf -k14 ref.fa direct-rna.fq > aln.sam`
I try to quantify and counts using with Subread featureCounts function. In the subread results, there is a problem with one of the bam files. I downloaded reference and gtf files from GENCODE. 
I checked the bam file with  `samtools view -H first.bam-second.bam`  I saw that I followed the same steps for each bam file.
In the IGV results, I saw matches and alignment for all bam files.

Do you have any suggestions the solve this problem? What am I doing wrong?
 
`featureCounts -T 8 -a gencode.v38.chr_patch_hapl_scaff.annotation.gtf -g 'transcript_id' -o readcouts.txt bam/*.bam `

||    Total alignments : 11214480                                             ||
||    Successfully assigned alignments : 4051945 (36.1%)                      ||
||    Running time : 2.67 minutes

||    Total alignments : 0                                                    ||
||    Successfully assigned alignments : 0                                    ||
||    Running time : 2.89 minutes  

I also tried with Salmon in the salmon alignment-based quantification results bam file has huge differences between each other.
`salmon quant  --ont -t reference.fa -l A -a first.bam -o salmon_quant1`
Total # of mapped reads : 5465357

of uniquely mapped reads : 328808350000000

ambiguously mapped reads : 2177274
`salmon quant  --ont -t reference.fa -l A -a second.bam -o salmon_quant2`
Completed first pass through the alignment file.

Total # of mapped reads : 3843632

of uniquely mapped reads : 2552463

ambiguously mapped reads : 1291169

**Comment by lh3** [comment]
> In the IGV results, I saw matches and alignment for all bam files.

Then this is not a minimap2 problem.

**Comment by lh3** [comment]
You need to ask salmon or featureCount developers.

**Comment by Sasakawamiwa** [comment]
Have you solved this problem?

**Comment by cagataykos** [comment]
I solved the problem using pychopper trimming tools.
