### ISSUE TITLE
some compare result of minimap2 '-x sr' mode of v2.18 and v2.20

### ISSUE THREAD

**Issue by wangyugui** [lh3/minimap2#776]
some compare result of minimap2 '-x sr' mode of v2.18 and v2.20

genome: GRCh38.p13
data: Illumina PE150

a) performance: big change in runtime.
v2.18
  real	213.72(3:33.72), user	12295.66,  sys	169.28
v2.20
  real	323.90(5:23.90), user	17924.58, sys	225.08
but memory usage is almost same.

b) mapping result: big change in 'properly paired %' and 'singletons %'

v2.18
	mapped %	97.16%
	mapq>=1 %	92.69%
	properly paired %	95.98%
	singletons %	0.30%
v2.20
	mapped %	96.34%
	mapq>=1 %	92.01%
	properly paired %	92.63%
	singletons %	1.07%

c) misc
   in man file, '-r50' is in '-x sr' mode,
   but '-r100' is in source(mo->bw = mo->bw_long = 100;).

**Comment by lh3** [comment]
Thanks. On my dataset, I didn't see this. v2.20 is slightly more accurate on the contrary. Perhaps a difference between datasets. Either way, you may try to add `-xsr -e0`.

**Comment by wangyugui** [comment]
in this dataset, '-xsr -e0' help the a) performance, but few changes in the b) mapping result.

v2.20 with -xsr -e0
a)performance:
 real	291.60(4:51.60) user	17970.39 sys	224.20
b)mapping result:
mapped %	96.33%
mapq >=1 %	92.01%
properly paired %	92.62%
singletons %	1.07%

There is no '-e0' option in minimap2 v2.18, so no test result of v2.18 with -e0 option.

**Comment by lh3** [comment]
Could you check the github HEAD to see if this is fixed on your data? Thanks.

**Comment by lh3** [comment]
PS: if it is ok on your data, I will release v2.21 for this bug fix.

**Comment by wangyugui** [comment]
Very good result with this fix.

minimap2  2.20 r1069 without -e0
a) performance 
real	204.98(3:24.98) user	11504.85 sys	183.21
b) mapping result
mapped %	97.17%
mapq>=1 %	92.70%
properly paired %	96.00%
singletons %	0.29%

minimap2  2.20 r1069 with -e0
a) performance 
real	202.34(3:22.34); user	11614.83; sys	188.57
b) mapping result
mapped %	97.17%
mapq>=1 %	92.69%
properly paired %	95.98%
singletons %	0.30%

By the way, in the coming 2.21 release, please change the man file too?
c) in man file, '-r50' is in '-x sr' mode,
but '-r100' is in source(mo->bw = mo->bw_long = 100;).

Best regards

**Comment by jmarshall** [comment]
> PS: if it is ok on your data, I will release v2.21 for this bug fix.

@lh3: I am about to send you a (better) fix for #573 (CIGAR stuff) if you would like to wait a moment to consider adding that.

**Comment by lh3** [comment]
Thanks, @jmarshall. I will wait. I need to run some large-scale tests anyway before each release. It will take some time.
