### ISSUE TITLE
What parameters are recommended for CCS read alignment?

### ISSUE THREAD

**Issue by FrankFeng** [lh3/minimap2#78]
Hello, I have the PacBio circular consensus (CCS) reads, which are long and highly accurate (typically 8kb of length with ~99% base accuracy). It is human whole genome data, and I am going to use Minimap2 to map them to the hg38 reference. What parameters are recommended? Thanks.

**Comment by lh3** [comment]
I would just use `map-pb` and filter out low-identity alignment later. The quality of CCS reads varies.
