### ISSUE TITLE
Problem with alignment of two sequences, one with lots of Ns

### ISSUE THREAD

**Issue by monsanto-pinheiro** [lh3/minimap2#782]
The sequences attached are from same chromosome of same specie, but the alignment it is a bit messi.
[S01.chrI_0_100000.fasta.gz](https://github.com/lh3/minimap2/files/6794239/S01.chrI_0_100000.fasta.gz)
[S288C.chrI_0_100000.fasta.gz](https://github.com/lh3/minimap2/files/6794240/S288C.chrI_0_100000.fasta.gz)

Command line: minimap2 -L -a -o temp.sam S288C.chrI_0_100000.fasta S01.chrI_0_100000.fasta
Cigar result: 14S13M4I12M1D4M1I3M1I15M2I24M1D12.....

Result of alignment, parsed from CIGAR result:
chrI_from                           --------------CCACACCACACCC----ACACACCCACACACCAC-A        31
chrI                                CACCCACACACCCACACACCACACCCACCACCACACCCACACA-CACACC        49
                                                  *    *    **          **      *     

chrI_from                           CC-ACACACCACACCACA--CCCACACACACACATCCTAACACTACCCTA        78
chrI                                CACCACACCACACCACACCACCACACACACACATCCTAACACTA-CCTAA        98
                                    *       *    *      **             *  *      **  *

chrI_from                           ACACAGCCCTAATCTAACCCTGGCCAACCTGTCTCTCAACTTACCCTCCA       128
chrI                                CACAGCCCTAATCTAACCCTGGCCAACCTGTCTCTCAACTTACCCTCCAT       148
                                          **  *    * **  * * * *         *  *  **  *  

chrI_from                           TTACCCTGCCTCCACTCGTTACCCTGTCCCATTCAACCATACCACTCCGA       178
chrI                                TACCCTGCCTCCACTCGTTACCCTGTCCCATTCAACCATACCACTCCGAA       198
                                    *  **   *  *      *  **    **  *  * *    *    *  *

**Comment by lh3** [comment]
Probably your CIGAR is wrong. This the alignment at the beginning:
```
Ref+:          2 =============----============c====-===-===============--======================== 73
                 |||||||||||||    |||||||||||| |||| ||| |||||||||||||||  ||||||||||||||||||||||||
Qry+:         15 =============ccac============-====c===c===============ca======================== 93

Ref+:         74 c=============================================================================== 153
                  |||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
Qry+:         94 -=============================================================================== 172

Ref+:        154 ================================================================================ 233
                 ||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
Qry+:        173 ================================================================================ 252
```

**Comment by monsanto-pinheiro** [comment]
Thank you, you are right. In sam file the alignment starts at position 2, in the Ref. I was expecting that the alignment was starting at first position, that was a wrong assumption.

**Comment by lh3** [comment]
Thanks for the confirmation. Off-by-one errors are common in this field.
