### ISSUE TITLE
asm preset values sequence divergence

### ISSUE THREAD

**Issue by zuzanahalenkova** [lh3/minimap2#783]
Hello,
I would like to use minimap2 for alignment of assemblies from two closely related species. However I am not quite sure which `asm` option I should use, as the info provided for the sequence divergence values seems a bit ambiguous:

- in `minimap2 --help` there is `asm5/asm10/asm20 - asm-to-ref mapping, for ~0.1/1/5% sequence divergence`
- in manual page ([https://lh3.github.io/minimap2/minimap2.html](url)) there are values of "far below 5%"/"up to 10%"/"up to 20%" for asm5/asm10/asm20 respectivelly

**Comment by lh3** [comment]
In asmX, X indicates the upper limit. The average divergence has to be much smaller than that limit. In practice, which is better depends on your data and your goal. Try and test by yourself.
