### ISSUE TITLE
Making additions to the mmi files / concatenating mmi files

### ISSUE THREAD

**Issue by jackgoza** [lh3/minimap2#784]
Good afternoon!
     We're using minimap2 in a project that requires a large amount of reference data. Creating the mmi references from that data works brilliantly on our main development machine, but on a normal machine we encounter OOMs very quickly. To overcome that, we were hoping to do a simple concatenation of two mmi files if we need to supplement our indexes in the future. 

I've reviewed the documentation and have not seen much about the mmi files; I've also looked at our mmi files via some hex->ascii editors, and from what I've seen a simple concatenation will not work as all of the metadata per file precedes the reference sequence data.

Has anyone merged mmi references like this in the past and if so, what is the best way to do it? Are there functions in this library that I've missed that can accomplish this goal?

I greatly appreciate any assistance here! This is an awesome library; I'm personally very grateful for all the effort that's gone into it. Thank you!

**Comment by lh3** [comment]
You can use `--split-prefix=prefix -I2G` to make tradeoff between performance and peak memory footprint.
