### ISSUE TITLE
Are there parameters that can get r2.19+ to emit alignments more like r2.18?

### ISSUE THREAD

**Issue by bhandsaker** [lh3/minimap2#785]
With the changes in r2.19, when aligning large high-quality contigs using -x asm5 the alignments around large VNTRs have changed. I have some pipelines that worked well with the old alignments, but less well with the new ones, so I am wondering if you can suggest some parameters I could experiment with to change the alignment behavior to be more like r2.18 and prior versions or perhaps even to disable the enhancements in r2.19 altogether.

In particular, I am observing that when there is a large VNTR expansion in the query relative to the reference, r2.18 would generate several alignments of the query to the reference that would make it pretty easy to locate all of the expanded copies on the query sequence. With r2.19, I find examples where the alignment cigar includes a large (e.g. 38kb) insertion in the
query with no other alignment for this section of the query to the reference. I would like to get minimap to emit more supplementary alignments where more of the query is mapped to some location on the reference.

I can send an example if that would be helpful.

**Comment by lh3** [comment]
You can reduce the bandwidth to break alignments more often at long indels. With asm5, the new minimap2 uses `-r100k,100k` by default. The old minimap2 is roughly (not exactly as the algorithm is different now) equivalent to `-r500,20k`. You may start with `-r20k,20k` or `-r7k,7k` and see what the result looks like.

**Comment by bhandsaker** [comment]
Thank you! That worked, except that I had to turn it down to `-r5k,5k` to get the same result as r2.18 in this particular example.

**Comment by lh3** [comment]
While minimap2-2.18 is supposed to align through 20kb indels, in practice it often can't due to the long-join heuristic that works for simple INDELs but at times fails around VNTRs. That heuristic has been removed. With v2.19+, if you tell minimap2 to align through 20kb indels, most of time it can achieve that. As you are working on VNTRs, be careful of this difference.
