### ISSUE TITLE
Reference fasta for ONT data alignment

### ISSUE THREAD

**Issue by sumin5784** [lh3/minimap2#788]
Hello,

I'm trying to align nanopore direct RNA sequencing data.
But I'm a bit confused, could you answer following questions?

`minimap2 -ax map-ont ref.fa ont.fq.gz > aln.sam         # Oxford Nanopore genomic reads`
=> Does this option is only for DNA sequencing?
=> Does the ref.fa is genome fasta file or transcript fasta file?

`minimap2 -ax splice -uf -k14 ref.fa direct-rna.fq > aln.sam  # Nanopore Direct RNA-seq`
=> Does the ref.fa is genome refernece fasta file or transcript (mRNA) fasta file?

Thank you,
Sumin

**Comment by lh3** [comment]
> Does this option is only for DNA sequencing?

Yes

> Does the ref.fa is genome fasta file or transcript fasta file?

genome

> Does the ref.fa is genome refernece fasta file or transcript (mRNA) fasta file?

genome
