### ISSUE TITLE
--rev-only/--for-only in mappy?

### ISSUE THREAD

**Issue by ollenordesjo** [lh3/minimap2#792]
Hi!

I'm wondering if it's possible to support the --rev-only and --for-only flags in mappy? Would there any complications with supporting it?

Cheers!

**Comment by lh3** [comment]
You may use
```python
mappy.Aligner(fn, extra_flag=0x100000);  # forward only
mappy.Aligner(fn, extra_flag=0x200000);  # reverse only
```

**Comment by Rasinj** [comment]
Thanks a lot!
