### ISSUE TITLE
Format of cs SAM/PAF tag

### ISSUE THREAD

**Issue by brunocontrerasmoreira** [lh3/minimap2#795]
Hi, after running 

    minimap2 --cs -x asm20 Osativa.fna Onivara.fna 

I got the following output:

    1 17470 20751 ONIVA01G00010.1 1574 1 3331 33993 + 6 26020714  26051403 29819 60  cs:Z::303*ag:30*ga:32*ga:27+ctattcta*ag*ca:20*ag:3*ga:...

Note the aligned segment 

    27+ctattcta*ag*ca 

how can you have a substitution (*ag*) in an insertion? Please help me understand it,
Bruno

**Comment by lh3** [comment]
That is after ins.

**Comment by brunocontrerasmoreira** [comment]
So in this segment you have 27 identical bases, followed by an insertion (ctattcta) and then two mismatches, is that it?
