### ISSUE TITLE
Assessing the sensitivity of mapping (with ONT data)

### ISSUE THREAD

**Issue by kaltinel** [lh3/minimap2#796]
Hi,

I am about to nanopore sequence a mix of oligos, which are 1-5 bases are different from each other (total length is 120 bp).

If I were to use `minimap2 -ax map-ont`, would I be able to differ them from each other?
Is it sensitive enough?

Can I use AS score to rank the sequences from 'most similar to reference genome' to 'least'?
And, may I learn the range of AS score?

I would appreciate your insights, thank you!

**Comment by lh3** [comment]
You can start with the setting. If doesn't work well, reduce `-w`. You can use AS to rank hits.
