### ISSUE TITLE
Index from char*?

### ISSUE THREAD

**Issue by armintoepfer** [lh3/minimap2#80]
Would it be possible to provide a function that generates mm_idx_t* from char*?
I'm using minimap2 from C++ and it would be helpful, if I don't have to write out the index as fasta, but feed the fasta char* directly to generate an index.

Thank you!
 - Armin

**Comment by lh3** [comment]
I was thinking about this, but didn't have an immediate use case myself at that time. As you mentioned it, I will have a look at some point. It requires some code refactoring.

**Comment by armintoepfer** [comment]
Great! This is currently my main bottleneck, as minimap2 itself is blazing fast.

**Comment by lh3** [comment]
The HEAD implements a new API `mm_idx_str()` that construct an index from a set of strings in memory. You can find an example at the end that demonstrates how to use the new API.

I am closing this issue. Feel free to open a new one if it has bugs.

```c
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "minimap.h"

int main(int argc, char *argv[])
{
	mm_idx_t *mi;
	mm_mapopt_t mopt;
	mm_idxopt_t iopt;
	mm_tbuf_t *tbuf;
	int i, j, n_reg, qlen;
	mm_reg1_t *reg;

	if (argc < 2) {
		fprintf(stderr, "Usage: mm-test <target1> [...] <query>\n");
		return 1;
	}
	mm_set_opt(0, &iopt, &mopt);
	mopt.mid_occ = 1000;
	mopt.min_cnt = 2;
	mopt.flag |= MM_F_CIGAR;
	mi = mm_idx_str(11, 5, 0, 8, argc - 2, (const char**)&argv[1], 0);
	tbuf = mm_tbuf_init();
	qlen = strlen(argv[argc-1]);
	reg = mm_map(mi, qlen, argv[argc-1], &n_reg, tbuf, &mopt, 0);
	for (j = 0; j < n_reg; ++j) { // traverse hits and print them out
		mm_reg1_t *r = &reg[j];
		printf("query\t%d\t%d\t%d\t%c\t", qlen, r->qs, r->qe, "+-"[r->rev]);
		printf("%d\t%d\t%d\t%d\t%d\t%d\t%d\tcg:Z:", r->rid, mi->seq[r->rid].len, r->rs, r->re, r->mlen, r->blen, r->mapq);
		for (i = 0; i < r->p->n_cigar; ++i)
			printf("%d%c", r->p->cigar[i]>>4, "MIDSHN"[r->p->cigar[i]&0xf]);
		putchar('\n');
		free(r->p);
	}
	free(reg);
	mm_tbuf_destroy(tbuf);
	mm_idx_destroy(mi);
	return 0;
}
```

**Comment by armintoepfer** [comment]
Works so far!
