### ISSUE TITLE
Unimap much faster (at least 100x) than minimap2 2.22 for reference with same flanking sequences

### ISSUE THREAD

**Issue by ghuls** [lh3/minimap2#811]
Unimap is much faster than minimap2 2.22 for Nanopore reads when mapping to an index with 12000 sequences (plasmid with 12000 different inserted sequences):
```
layout of ref.fa: 12000 seqeunces in the following format:
100 bp constant region
270 bp different sequence (12000 different sequences)
17 bp variable sequence (Ns in reference FASTA file)
2176 bp contant region
```

# Minimap2 parameters:
```
minimap2 -ax map-ont \
    -t 12 \
    --secondary=no \
    -N 1 \
    -L ref.fa \
   *.fastq.gz
```

# Unimap paramters:
```
/staging/leuven/stg_00002/lcb/ghuls/software/unimap/unimap \
    -a \
    -x ont \
    -t 12 \
    --cs \
    ref.umi \
    *.fastq.gz
```

Are there parameters that can be added to minimap2 to run get similiar running time as with unimap (I assumed all unimap changes were now incorporated in minimap2)?

**Comment by lh3** [comment]
Minimap2 has some unimap features but they are still different. In your case, you can try a smaller `-f` such as `-f500`.

**Comment by ghuls** [comment]
Thanks that worked.
