### ISSUE TITLE
Does minimap2 consider the alphabet case while aligning?

### ISSUE THREAD

**Issue by sanyalab** [lh3/minimap2#812]
Hello,

This is not an issue. 

I wanted to know if minimap2 considers the case of the nucleotide while performing evidence alignment. Some annotation protocols and aligners avoid smaller case characters, if they are present in the genome.fasta file, as these regions are interpreted as repetitive by the aligner. (Example BLAT in MAKER). Does minimap2 avoid regions of the genome if they are in small case? OR it does not matter.

Thanks
Abhijit

**Comment by lh3** [comment]
> OR it does not matter.

Letter case doesn't matter.
