### ISSUE TITLE
Has anyone succeeded doing asm20 alignments with wheat genomes?

### ISSUE THREAD

**Issue by brunocontrerasmoreira** [lh3/minimap2#813]
Hi, I have been exploring the use of minimap2 (versions 2.17-r941) to align plant genome assemblies and so far my benchmarks indicate it's pretty good and fast. But then I tried hexaploid wheat (_Triticum aestivum_), which is large (uncompressed FASTA file is 14G) and very repetitive (~80%). As I always ran out of memory, I took only the A subgenome (about of third of the size) with the following command:

    minimap2 -x asm20 --secondary=no --cs triticum_aestivum.mmi Tae_julius.A.fa.gz -o wheat.paf

This is still running after 9h and requires more than 300GB of RAM, which is not practical. Note that the indexing step chose k-mer=19 (also with version 2.22-r1105).

Can anybody recommend parameters or tricks to compute such alignments faster/with less RAM? 

I have tried a smaller k-mer (16) but the size on the index is only reduced from 12G to 11G.
I have also tried to cut the query genome in 100Kbp chunks and that seems to speed the search a bit, but anyway it's still running after 6hr.

Thanks for your thoughts,
Bruno

**Comment by lh3** [comment]
Yes, it is hard. There are a few things you could try:

* `--cap-kalloc=1g`. For contig alignment, this effectively reallocates thread-local buffer.
* `-f100`. This reduces k-mer occurrences.
* `-e0`. This disables the new seed-rescue heuristics in v2.19+. This heuristic improves read mapping accuracy at the cost of performance and memory.

You may apply all three options at the same time. If you can get alignments in reasonable time/memory, see which one affects the result most. Nonetheless, I would expect a couple of days of running time over ~32 CPUs for aligning 14Gb repetitive genomes.

Also, for performance, it is better to add `-I20g`, but that will use more memory.

**Comment by brunocontrerasmoreira** [comment]
Thanks @lh3 , isn't -f expecting a FLOAT?

**Comment by lh3** [comment]
Could you get alignment done in reasonable time/RAM in the end?

**Comment by brunocontrerasmoreira** [comment]
I managed to do it only with 100Kb chunks of the sequence, as explained above, I did not have enough RAM on my tests

**Comment by brunocontrerasmoreira** [comment]
I'll update this thread if I manage to do it on another machine, thanks for your help

**Comment by brunocontrerasmoreira** [comment]
Hi, I am revisiting this, now using a single chromosome, as the same RAM problem is seen there.
I can see that -f100 reduces the memory footprint (from 95% to 15% of available RAM) and can still be used with minimap v2-2.17. On my small genome test case (rice chr1), using -f100 has a modest negative effect on the number of gene models aligned (2964 vs 2949). In all cases it seems minimap keeps using only 1 CPU core though (as seen with top).

With version 2-2.24 the rice gene models are further reduced to 2898.

**Comment by brunocontrerasmoreira** [comment]
Thanks for your comments, I respond to them:

1) The same problem is the amount of RAM taken even if you are aligning a pair of chromosomes. In my case, that was over 120GB.

2) I am using collinear gene models to estimate the quality of a whole-genome alignment (WGA). Briefly, for each gene pairs I check whether there's a genomic range (start, end) in the WGA that covers 50% of  each model in the pair.

**Comment by lh3** [comment]
About 1, you said the memory is reduced from 95% to 15%. You mentioned 300GB in your original post. Then with -f100, the memory would be 50GB. Where does 120GB come from?

On 2, as I said, that is not the best way to transfer gene annotations and thus not the best way to evaluate WGA.

**Comment by brunocontrerasmoreira** [comment]
1) The 120GB comes from the alignment of one chr only (1H from barley) as opposed to the complete wheat genome. 

2) For gene space that's a reasonable approach I believe, but I am aware that this leaves out most of the genome in highly repetitive species.

**Comment by lh3** [comment]
I am still not sure what is the RAM problem. Have you applied -f100? Could you get an alignment in reasonable RAM with the parameters I was suggesting?

Whether your approach is a good one depends on the downstream applications. Your approach generally favors tight fragmented alignment without long INDELs. If that is what you want, you can add something like -1k,5k. The default setting tends to produce long alignment with large INDELs.

**Comment by brunocontrerasmoreira** [comment]
Sorry, my bad, I'll try to explain it better now:

> I am still not sure what is the RAM problem. Have you applied -f100? Could you get an alignment in reasonable RAM with the parameters I was suggesting?

Using -f100 I can align a single chr using a reasonable amount of RAM (38G as we speak). It would be nice to have a rationale for the choice of -f, is that related to Kmer observations?
 
> Whether your approach is a good one depends on the downstream applications. Your approach generally favors tight fragmented alignment without long INDELs. If that is what you want, you can add something like -1k,5k. The default setting tends to produce long contiguous alignment with large INDELs but your approach will miss genes in long insertions.

I was using -asm20, so no split aligments to be sure, as I don't need precise exon boundaries currently. I do however want most gene bodies to be recovered. Are you suggesting a different parameter combination to increase that?

**Comment by lh3** [comment]
> It would be nice to have a rationale for the choice of -f, is that related to Kmer observations?

It is a tradeoff between performance and accuracy. Like many parameters, there is not a clear cut.

> I do however want most gene bodies to be recovered.

Then add -r1k,5k (or even -r1k,2k).
