### ISSUE TITLE
Can not get Minimap2 to run

### ISSUE THREAD

**Issue by Albertus3** [lh3/minimap2#814]
I have installed minimap2 and having difficulty getting it to run. I need this aligner for my current college course (use to bwa) input would be greatly appreciated. I am currently running a 15 inch MacBook Pro 2017

<img width="1680" alt="Screen Shot 2021-09-08 at 4 59 49 PM" src="https://user-images.githubusercontent.com/57456446/132584999-67902547-72e7-4f20-92ac-4ded59b942e9.png">

**Comment by janxkoci** [comment]
You have a typo in your command. There is a space between `Users/Albert3/test` and `minimap2` which I believe should not be there.

**Comment by Lilalbertus** [comment]
My system will not recognize minimap2 at all. If I type bwa it shows, but not minimap2.

**Comment by janxkoci** [comment]
Have you tried installing `minimap2` with a package manager, such as `brew` or `conda`? I used `conda` to install `minimap2` from the Bioconda channel on our linux server and the binary works fine.

**Comment by Albertus3** [comment]
I got it 

you have to used "brew install brewsci/bio/minimap2" to get it to function on a MacBook Pro.

**Comment by janxkoci** [comment]
Yes, something like that 🙂️
