### ISSUE TITLE
The sam file cannot transfered to bam after minimap2 alignment

### ISSUE THREAD

**Issue by putianhuizi** [lh3/minimap2#815]
Hi, I followwd  the instruction `minimap2 -ax map-ont ref.fa ont-reads.fq > aln.sam      # for Oxford Nanopore reads` for my nanopore data and produced the sam file. However, when I started the next step use samtools view to transfer sam to bam file, it failed and showed the error as "[W::sam_hdr_create] Ignored @SQ SN:ori[M::main::5.178*1.00] loaded/built the index for 1897 target sequence(s) : bad or missing LN tag
[E::sam_hrecs_update_hashes] Header includes @SQ line "ori[M::main::5.178*1.00] loaded/built the index for 1897 target sequence(s)" with no LN: tag
samtools view: failed to add PG line to the header". 
I am wonder the sam file produced by minimap2 has differenct characters or other reasons? 
Thank you!

**Comment by lh3** [comment]
You are mixing stderr with stdout. Don't use nohup. If not sure, use option -o.

**Comment by putianhuizi** [comment]
> You are mixing stderr with stdout. Don't use nohup. If not sure, use option -o.

Thank you! I just noticed it after I posted the question.
