### ISSUE TITLE
mapping inversion problem

### ISSUE THREAD

**Issue by shiyi-pan** [lh3/minimap2#821]
Hi, I want to use minimap2 to map reference genome for  SV detection  but when I map an inversion to reference genome, it don't work well . I hope you can give some advise to fix this.Here is what I did:

First I generated an genome include some inversions based on reference genome.
then I used minimap to map the genome include some inversions to reference genome.
I checkd one inversion from my fasta file and it indeed existed . Here is part of fasta files :
ref:
Chr01:17237000-17239000
TTCAAGGTCTAACAGCCACTGTTTACAACCTTCTCACCTAACCACTACCCGTGCGACCTCTACCTAAGAGCCACTCTTAGATATGAGAACCCCTCTCACTCCCTCTCAATCACACTCCCGTGTTTACAATCAAATCAAAAACACACCAGAGATTGCTCTCTGAACAAAAGAGATCAACTCTACACACTAGAGATCAACTCTACACACAAGAGATCAACTCTACACACAAGAGATCAACTCTACACACTCAGGTCCAACACTTGATGTTAGGGTACCATCAAGGTGGCTCACAAAAGACTCAAGTCCCAAAACTCACAAAATAACTCTTCAATCCCGGACTTGGTGCAGAACTCGTGCAGCCTTCATGTTTATATAGCAGTGTGCGTATCTGGGCTGCAACTTCTTGATGCTGGATGAGATCTATCATTTTCCTGAAAATCTGCACTTAAAGATCTAAAAGATACAGTTTGATCTTTTAGTTTTTATCTTTAATCTTTAATCCCTGAACGAACTATTCAAGTTTGTAATTCGAACTTTAATTATCTTTTAATTCGTTCCAAGAGATAGATCGTCTAATCTGTTGCTAACTGCACAATAATCTGTTAAAGAGATAACAGATTTATGTGTCCAGTATTTTCGGGCCGGATGTCAGGACATCGTGGATCCTGCACACTCTGTTAAAGATATAACAGATTTATGTGTCCAGTATTTTCGAGCCGGATGTCAGGACATCGTATCCGACATCGTGGATCCTGCAGCTTCAATTCTTCATTTGACATTTTATCTTGCCTTGTGCATTGTGCAGCCCGATCTGATTCCTTGACATAACGTTGGACATCATGTGCAGCAACTCCAGCTTTCCTTCATTGTCTAAGTGCTTATGTTTTAACAAAATCTTAGCCAATCTTTTAAACACTCAGTAGAGCTAAGCACTAACAAAATGTTTTATGAATGACCATCAAAGGTGACTTGGAAACACGAACTTAAAGGGAGTTTCATTGCCCAAAAACTTTTTATCCTTTCAAAAGATTAAGAGTTTTTTCTGAACTGAACTGTCTTATCCTCTCAAAAAGATTCTTTGGTCAACCACTTGCATATTCAATAAGGAATTTTGATTGACCTTCATTGTACAATCTATCTCTTTTAAGAGAGATTTCTTCTTCTCTTCTTCTTATTTCTGAAAAGGGATTAAGAGACCGTGGGTTTCTTGTTGTAGAGGATTCTTGAACACAAGGGAAGGGTTGTCCCTGTGTGGTTCAGACTTTGTTAAAAGAGTTTTACAAAGAGGATGGAAAATTTCAAGTGGGTTGCTTGAGGACTGGACGTAGGCACGGGAAGTGGCCGAACCAGTATAAATCAAGTTTGCATTCCTCTCTTCCCTTAAACTTCTTTTATTTATAGCTATTTATCTTTTGCTTTAAAGAAGTTTATTTTGAATTATCTTTTGAGTAATTCATGTTAAGGGTGCATTGTTAATCCGAAGAGAGTGAAAGTTTAATTGGGGAATAGTCTTCGTATCTTAATTCCACCCCCCCTTTTTTTTCTTAAGGTAACTTAGGCCATTTATCCAACATCCTATTCTTGATAACTCACTTCTCTCTAAAAAGACAAACTTTCCGGAATGATGAAATGAGGACACATGAACGTCTTGAAAACACAGTCAATCAAATGCTTTTTTTTTCTTTTTGAACTCTTTTTTTTTATTTTTTTATTTTGAAAATTATTTGTTTTGAACTTTACTCGTTGTTTTACGGCACCCCCACCAACGTGCAAGACGAGTAATCTCTGATTGAACAGTCTTGGAAGTCCAAACTCAGGAGCACAGGTCGCTTGAGCAAACAAACCAATGGCTTGCACCCACATCCCAGTGGAAGCAAAGATGTAATTACGAGAGGATGAGGGACAAAGATGTCAAATTTATCCATCTATTTAGCGTTGTAACTGTGGTTTACAATAATGGTATAAACTTGAAAATCCTGATGAGTCATTAGAGACATCTA

inversion:

Chr01:17237000-17239000
TTCAAGGTCTAACAGCCACTGTTTACAACCTTCTCACCTAACCACTACCCGTGCGACCTCTACCTAAGAGCCACTCTTAGATATGAGAACCCCTCTCACTCCCTCTCAATCACACTCCCGTGTTTACAATCAAATCAAAAACACACCAGAGATTGCTCTCTGAACAAAAGAGATCAACTCTACACACTAGAGATCAACTCTACACACAAGAGATCAACTCTACACACAAGAGATCAACTCTACACACTCAGGTCCAACACTTGATGTTAGGGTACCATCAAGGTGGCTCACAAAAGACTCAAGTCCCAAAACTCACAAAATAACTCTTCAATCCCGGACTTGGTGCAGAACTCGTGCAGCCTTCATGTTTATATAGCAGTGTGCGTATCTGGGCTGCAACTTCTTGATGCTGGATGAGATCTATCATTTTCCTGAAAATCTGCACTTAAAGATCTAAAAGATACAGTTTGATCTTTTAGTTTTTATCTTTAATCTTTAATCCCTGAACGAACTATTCAAGTTTGTAATTCGAACTTTAATTATCTTTTAATTCGTTCCAAGAGATAGATCGTCTAATCTGTTGCTAACTGCACAATAATCTGTTAAAGAGATAACAGATTTATGTGTCCAGTATTTTCGGGCCGGATGTCAGGACATCGTGGATCCTGCACACTCTGTTAAAGATATAACAGATTTATGTGTCCAGTATTTTCGAGCCGGATGTCAGGACATCGTATCCGACATCGTGGATCCTGCAGCTTCAATTCTTCATTTGACATTTTATCTTGCCTTGTGCATTGTGCAGCCCGATCTGATTCCTTGACATAACGTTGGACATCATGTGCAGCAACTCCAGCTTTCCTTCATTGTCTAAGTGCTTATGTTTTAACAAAATCTTAGCCAATCTTTTAAACACTCAGTAGAGCTAAGCACTAAGAAGGGCACGGATGCAGGTCAGGAGTTCGTTGGGTGAACTTTAAAAGGTAGGAGAAACATTTTGAGAAAATTGTTTCAGACTTGGTGTGTCCCTGTTGGGAAGGGAACACAAGTTCTTAGGAGATGTTGTTCTTTGGGTGCCAGAGAATTAGGGAAAAGTCTTTATTCTTCTTCTCTTCTTCTTTAGAGAGAATTTTCTCTATCTAACATGTTACTTCCAGTTAGTTTTAAGGAATAACTTATACGTTCACCAACTGGTTTCTTAGAAAAACTCTCCTATTCTGTCAAGTCAAGTCTTTTTTGAGAATTAGAAAACTTTCCTATTTTTCAAAAACCCGTTACTTTGAGGGAAATTCAAGCACAAAGGTTCAGTGGAAACTACCAGTAAGTATTTTGTAAAACTGGCCGAACCAGTATAAATCAAGTTTGCATTCCTCTCTTCCCTTAAACTTCTTTTATTTATAGCTATTTATCTTTTGCTTTAAAGAAGTTTATTTTGAATTATCTTTTGAGTAATTCATGTTAAGGGTGCATTGTTAATCCGAAGAGAGTGAAAGTTTAATTGGGGAATAGTCTTCGTATCTTAATTCCACCCCCCCTTTTTTTTCTTAAGGTAACTTAGGCCATTTATCCAACATCCTATTCTTGATAACTCACTTCTCTCTAAAAAGACAAACTTTCCGGAATGATGAAATGAGGACACATGAACGTCTTGAAAACACAGTCAATCAAATGCTTTTTTTTTCTTTTTGAACTCTTTTTTTTTATTTTTTTATTTTGAAAATTATTTGTTTTGAACTTTACTCGTTGTTTTACGGCACCCCCACCAACGTGCAAGACGAGTAATCTCTGATTGAACAGTCTTGGAAGTCCAAACTCAGGAGCACAGGTCGCTTGAGCAAACAAACCAATGGCTTGCACCCACATCCCAGTGGAAGCAAAGATGTAATTACGAGAGGATGAGGGACAAAGATGTCAAATTTATCCATCTATTTAGCGTTGTAACTGTGGTTTACAATAATGGTATAAACTTGAAAATCCTGATGAGTCATTAGAGACATCTA

I check one of the inversion  in IGV and the flanking sequences,it seems didn't mapped correctly . the flanking sequences mapped well and the inversion where I marked in red line didn't align to the reference genome. here is the picture I export from IGV. 

![Inkedigv_snapshot_LI](https://user-images.githubusercontent.com/58731075/135700446-227ec1d7-52e1-4f9a-beea-c8b4b583382e.jpg)

here is my code:
minimap2 -t 4 -ax asm20 --eqx Reference.fa InversionReference.fa > Reference2Inversion.sam

the version I tried include 2.13, 2.17, 2.18. The -ax parameter I  tried include asm5, asm10 and asm20.

**Comment by lh3** [comment]
What are the exact input sequences?

**Comment by shiyi-pan** [comment]
Thank you for reply me . The  input sequences are soybean gennome and the  soybean gennome with 900 inversion I generate using python script. what I paste it's one of the inversions I generate.

**Comment by lh3** [comment]
The flanking sequences are far too short.

**Comment by shiyi-pan** [comment]
Thank you for your reply. I don't think it's the key point that the flanking sequences are far too short. I offer a short flanking sequence just for display. The whole sequence is long enough, I can upload the  flanking 1 Mb sequence. Here is the sequeces with  flanking 1 Mb sequence and its' bam file. 
[minimap_INV.zip](https://github.com/lh3/minimap2/files/7270825/minimap_INV.zip)
