### ISSUE TITLE
mapping a 77 bps duplication to reference with 150 bps reads

### ISSUE THREAD

**Issue by husamia** [lh3/minimap2#826]
I have short read data that is about 150bps. There is an insertion of 77bps. I can't get BWA or Minimap2 to create the insertion properly to human genome with the default settings. Is there a certain settings that I can use to get the aligner properly insert the duplication? either bwa or minimap2.

What is the operational max limit of the size of InDel to the read size? I thought it's around the 30%. In my case it's close to 51%.

here is snapshot of what it looks like. It's coverage is high. also it's targeted data.

![image](https://user-images.githubusercontent.com/13439952/137011025-f2a500d8-21c7-4947-9f95-08ec2992d320.png)

**Comment by lh3** [comment]
Kistoffer brought this up on twitter. Could you provide reads here? It is possible.

**Comment by husamia** [comment]
@lh3 here chr1(hg19):209,802,899-209,803,539

[LAMB3_EX.fastq.zip](https://github.com/lh3/minimap2/files/7750074/LAMB3_EX.fastq.zip)

**Comment by lh3** [comment]
I could get ~12 reads aligned with the 77bp insertion with:
```sh
# turn to interleaved fastq and remove short fragments
bioawk -cfastx '{print $name"\t"$seq}' LAMB3_EX.fastq|sort|awk 'length($2)>=140{print ">"$1;print $2}' > LAMB3_EX.srt.fq
minimap2 -cxsr --cs -w5 -A7 ref.fa LAMB3_EX.srt.fq | grep 77I
```

A potentially better solution is to do a local assembly, where fml-asm is part of [fermi-lite](https://github.com/lh3/fermi-lite):
```sh
seqtk sample LAMB3_EX.srt.fq 1000 | fml-asm - | minimap2 -c ref.fa -
```
Here we sample 1000 reads as the fml-asm assembler is not designed for ultra-high depth in your data. If this is a cancer sample, somatic mutations will fragment the assembly as well. Another tricky part is how many reads to sample. Although the 77bp insertion can often be recovered, the assembly quality differs a lot.

**Comment by husamia** [comment]
@lh3 to visualize the alignment output alongside the original in IGV. I am having trouble getting the output in BAM format and generating an index. I tried this and didn't work when I tried to create the index

`minimap2 -axsr -w5 -A7 /mnt/e/ref/human_g1k_v37.fasta LAMB3_EX.srt.fq -o LAMB3_EX.srt.fq.sam
`

Error
[E::bam_write_idx1] Read 'NS500492:207:HTKNFAFX2:1:11101:15048:14693' with ref_name='1', ref_length=249250621, flags=65, pos=209803050 cannot be indexed
