### ISSUE TITLE
Cannot run minimap

### ISSUE THREAD

**Issue by jiguan** [lh3/minimap2#83]
Follow the instruction to install, I cannot run it by minimap2: command not found: minimap2

**Comment by wdecoster** [comment]
Hi jiguan,

This is a general problem, not specific to minimap2. You need to make sure that the executable is in your $PATH. You can, for example, read about this here: https://askubuntu.com/questions/322772/how-do-i-add-an-executable-to-my-search-path

Googling about $PATH should help you to solve this problem. If not, you can look for help on e.g. https://www.biostars.org/

Cheers,
Wouter
