### ISSUE TITLE
[ERROR] dual gap penalties violating E1>E2 and O1+E1<O2+E2

### ISSUE THREAD

**Issue by AMPByrne** [lh3/minimap2#833]
Hi,

I'm trying to run minimap2 to assemble Oxford Nanopore reads to a reference but I keep getting the following error: `[ERROR] dual gap penalties violating E1>E2 and O1+E1<O2+E2. `

Here is the command I'm running:
`minimap2 -s 10 -t 4 -k 19 -B 4 -O 6 -R '"@RG\tID:"$samplename"\tSM:"$samplename"\tLB:"$samplename""' '/home/alexbyrne/mnt/VI6Storage/Raw_NGS_Data/MinION_Data/1353_Test_Run/FAO54735_SPAdes_Influenza_Database_26-10-21/top_matches.fa' '/home/alexbyrne/mnt/VI6Storage/Raw_NGS_Data/MinION_Data/1353_Test_Run/FAO54735_pass_c4ec9f31_merged.fastq' | samtools view -@ 4 -u - | samtools sort -@ 4 -o '/home/alexbyrne/mnt/VI6Storage/Raw_NGS_Data/MinION_Data/1353_Test_Run/FAO54735_pass_c4ec9f31_map_sorted.bam' `

I have tried altering the values for the different flags (-s, -k, -B and -O) but I keep getting the same error. 

Do you know what could be causing this issue?

**Comment by lh3** [comment]
Sorry for the late response. You can't mix dual gap penalty and single gap penalty. If you want to change -O, you have to change -E accordingly.
