### ISSUE TITLE
missing sequence information in sam output

### ISSUE THREAD

**Issue by lucacozzuto** [lh3/minimap2#834]
Dear developers, I found that the secondary alignments are often missing read information in the SAM format. This will make other tools complaining (like htseq for instance, see here: https://github.com/htseq/htseq/issues/33).

**Comment by olechnwin** [comment]
Is there any way to keep sequences for secondary alignments? I am trying to figure out whether sequences of a specific intron is in my assembled genome. So, I aligned the sequences of the specific intron to my custom genome. It aligns to multiple places and I'm trying to figure out all the sequences where it aligns. Thank you!
