### ISSUE TITLE
Circular reference

### ISSUE THREAD

**Issue by Sumsarium** [lh3/minimap2#835]
Mapping of linear reads to a circular reference (e.g. plasmids) is a bit problematic unless both start and end at the same position. We need a Minimap2/Samtools extension that allows one to specify that the reference is circular and allow reads to "double-back" from end to start position of the reference.

I have seen quite a few threads discussing this issue but it seems that it still remains unsolved. I hope that it can be solved.

**Comment by lh3** [comment]
I have no plan to support circular genomes.

**Comment by jmarshall** [comment]
FYI since samtools/hts-specs#403 SAM has `@SQ … TP:circular` for specifying that a reference sequence is circular. (At present, samtools doesn't do anything in particular with it either.)
