### ISSUE TITLE
Nothing in RNAME field after aligning FASTQs to contigs.fasta file 

### ISSUE THREAD

**Issue by sagrant** [lh3/minimap2#836]
I've been making _de novo_ assemblies with SPAdes and then aligning the resulting contigs back to the original FASTQs. This has worked for me several times so far, but in my latest attempts, the resulting SAM file looks like this: 
<img width="1345" alt="6merged_assembly_view" src="https://user-images.githubusercontent.com/75453911/139880822-7a61930e-23ee-498f-9eb3-d0d2e8c9ad1a.png">
Where there are only "*" in the RNAME field. I looked at the contigs file input to minimap2 and there are names there, so I'm inclined to think there's something wrong with how I'm running minimap2. 

here is the command I used to run it:
`minimap2 -ax sr -t 40 -m 500 6merged_contigs.fasta 6merged_1.fastq 6merged_2.fastq > 6merged`

Does anyone know what I'm doing wrong?

**Comment by lh3** [comment]
Don't apply -m500. It is not possible for short reads to reach that large threshold. Generally, if unsure, try the default.
