### ISSUE TITLE
Get secondary alignments in mappy python API

### ISSUE THREAD

**Issue by nettanetta** [lh3/minimap2#837]
Hi! 
I use the mappy API to map contigs to multiple reference genomes. 
I want to get all the mappings of each contig to all the genomes (a contig might appear in more than one genome).
I noticed that I get different results when the bacteria is in a single fasta file or in seperate fasta files (one per genome). 
My questions are:
1. Do we expect aligner.map() to work differently when I generate one Aligner object to all genomes or separate Aligner object per genome?
2. Is the number of matches returned affected by best_n? (that's what I understood from the manual, but It seems to make no difference when I change it)
3. how can I make sure that I get all the possible alignments of the contig to the reference genome when I use the API?

**More details**
I use the 'asm20' preset
My code:
````
def get_matches_using_mappy(query, targets, preset):
    matches = []
    for target in targets:
        aligner = mp.Aligner(target, preset=preset, best_n=1000)
        if not aligner:
            raise Exception(f"ERROR: failed to load/build index file {target}")
        for name, seq, qual in mp.fastx_read(query):  # read one sequence
            for h in aligner.map(seq):  # traverse hits
                matches.append((name,qual,str(h)))
    return matches
````
Can also upload the data I use if it helps
thank you very much!
Netta

**Comment by lh3** [comment]
Mappy by default gives you secondary alignments.

> Do we expect aligner.map() to work differently when I generate one Aligner object to all genomes or separate Aligner object per genome?

The two modes are different.

> Is the number of matches returned affected by best_n?

Yes, "affected", but there are other parameters in the play.

> how can I make sure that I get all the possible alignments of the contig to the reference genome when I use the API?

Not possible with the current implementation, as not all parameters are exposed in mappy.

**Comment by nettaba** [comment]
Thanks for the quick response!
Can you please elaborate on why I get more results when I generate a separate Aligner object per genome rather than one Aligner object for the entire reference?  Is there a way where I could get all the matches without generating many separate Aligner objects?

**Comment by lh3** [comment]
minimap2 discards short alignments or chains before they reach the final step. If you have one weak hit to reference A and a much stronger hit to ref B, the weak hit will be "shadowed" by the strong hit. You can control the threshold with -p on the command line, but this option is not exposed to mappy.
