### ISSUE TITLE
[Question] Explanation on a variable used in chaining function

### ISSUE THREAD

**Issue by kisarur** [lh3/minimap2#838]
Hi,

I have been studying Minimap2's chaining algorithm for a research purpose. While I was going through the code for chaining function (on the latest Minimap2 version, it's `mg_lchain_dp` function in `lchain.c`), I came across the variable named "st" which tries to limit the inner loop's trip count in score computation. The following code is used to calculate the value of "st",

https://github.com/lh3/minimap2/blob/32f552957e3b6ad4e23aa5c87cc985c4acd866dc/lchain.c#L147
    
I would kindly like to know what "st" stands for. Also, I would be really grateful if I could get a brief explanation on how the above calculation works.

Thank you very much!

**Comment by lh3** [comment]
`st` is the starting index in the inner loop on line 149. You can merge this line to the loop on 149.

**Comment by kisarur** [comment]
Okay, I see. Thank you very much for providing me this information!

Best,
Kisaru
