### ISSUE TITLE
minimap appears to be fragmenting reads

### ISSUE THREAD

**Issue by HISD-Colindale** [lh3/minimap2#839]
Hi all, 

I have used minimap2 to align ONT reads to a reference. Reads contained within FASTQ files were first filtered for min and max read lengths (6000-14000bp). When I plot the distribution of these (please see the distribution below), you can see everything is as expected and within the range of the filtering thresholds. 

![filtered_distribution_BEFORE_alignment](https://user-images.githubusercontent.com/87140315/141322343-a3b2bd8a-615b-4a42-88d5-2262ec2755bd.png)

However, **after** I align and plot the distribution of the read lengths (please see the distribution below), you can see reads shorter than 6000bp now appear, and the total number of reads has increased from 26,421 before, to 28,117 after alignment, respectively. It doesn't make sense to me that minimap2 would be fragmenting reads and then aligning. But am I missing something? Is this behaviour expected? What would be the cause?

![filtered_distribution_AFTER_alignment](https://user-images.githubusercontent.com/87140315/141322348-2ed66c10-62a6-4628-8e1f-e52cac15f19f.png)

This is the command for read lengths from the FASTQ file:
`cat data/filtlong_out/HISD_0190_ONT_2/filtered_barcode01.fastq | awk '{if(NR%4==2) print length($1)}' | sort -n`

This is the command for read lengths from the bam file:
`samtools view data/bam_files_sorted/HISD_0190_ONT_2/barcode01_sorted.bam | cut -f 10 | perl -ne 'chomp;print length($_) . "\n"' | sort -n`

This is the command to align:
`minimap2 -ax map-ont ${REFERENCE_INDEX} ${i} -t ${THREADS} -o ${OUTPUT_DIR}/${BARCODE}.sam`

Any help would be much appreciated!

Rohan :)

**Comment by lh3** [comment]
There are SVs, centromeres and poorly called reads. You can't expect full-length alignment for every read.

**Comment by HISD-Colindale** [comment]
These were amplicons of genes far from a centromeric region, hence the very specific read length thresholds. Also, if the reads were of poor mapping quality would they then not be discarded rather than partially aligned?

**Comment by lh3** [comment]
Part of a read can have poor quality. It has nothing to do with mapping quality.

**Comment by HISD-Colindale** [comment]
Thank you for your responses!! It is more clear now :)

**Comment by lh3** [comment]
Welcome. BTW, you may consider to apply `--secondary=no`.

**Comment by HISD-Colindale** [comment]
I will... thank you again! It's very helpful!
