### ISSUE TITLE
Mapping ONT reads to very similar reference sequences 

### ISSUE THREAD

**Issue by cliu32** [lh3/minimap2#84]
Hi, Dr. Li,
I used "-ax map-ont" to map nanopore reads (generated using PCR amplicons from the HLA-C locus) to a reference file containing sequences for all HLA-C alleles. Some of these alleles are really similar with only 1-base differences, for example HLA-C\*03:03 and HLA-C\*03:04 (see attached image), and the variant is located at the end of exon2. Although this particular dataset is supposed to be HLA\*03:04, for reason unclear to me, the reads are mapped to both HLA-C\*03:03 and HLA-C\*03:04, with a slight advantage for HLA-C\*03:03. In contrast, if I use BLASR for read mapping (default settings), there will be much less reads mapped to the references, but the majority of reads are mapped to the correct allele HLA-C\*03:04. Is there an explanation for this observation? 
I would love to make minimap2 work for my pipeline because I can get more reads mapped. But is there a trade-off between accuracy and number of reads mapped? Overall, for 28 out of 30 samples, the minmap2 worked very well except for the example mentioned above and anther sample involving HLA-A\*33:01 versus 33:03. Thank you so much for the great tool and your help! 
![screenshot from 2017-12-24 17-38-22](https://user-images.githubusercontent.com/10225753/34329741-6fcf8cd6-e8d1-11e7-9116-fe1e9d865008.png)

**Comment by lh3** [comment]
Could you send me your reads and your HLA-C reference file? It is hard to say what's going on to a single-base difference, especially when it is at the boundary.

**Comment by lh3** [comment]
Also, are you mapping reads to exon 2 only, or to the full mRNA?

**Comment by cliu32** [comment]
Thanks for the quick reply. The reference includes exon2+gap+exon3. ONT reads are from the full gene. Here is the link to the data and reference (https://drive.google.com/open?id=11Ye4MVdL_ZDh46yzqI7id_aSE_gc3b8D) 
Thanks again and happy holidays!!!

**Comment by lh3** [comment]
You may try the following command line:
```sh
minimap2 --cs -c -k13 -N50 -t8 exon2_3.fasta reads.fastq > aln.paf
```
This uses shorter seeds and does more alignment for accuracy. When counting, you need to account for equally best alignments. From what I see, C\*03:04 appears much more frequently than C\*03:03 as the top hits. You can find a small script at the end. You need k8 (available from minimap2 binary packages) to run. It gives you top alleles. The script just gives you a rough idea.

```js
var min_frac = 0.97;
if (arguments.length == 0) {
    print("Usage: k8 naive-type.js <in.paf>");
    exit(1);
}

var buf = new Bytes();
var file = new File(arguments[0]);

function process_a(a, h) { // a[] keeps the list of alignments for the same read
    var m, max = 0, n_max = 0, b = []; 
    for (var i = 0; i < a.length; ++i) { // parse alignment score (AS)
        var ai = a[i];
        for (var j = 11; j < ai.length; ++j)
            if ((m = /AS:i:(\d+)/.exec(ai[j])) != null)
                b[i] = parseInt(m[1]);
    }   
    for (var i = 0; i < a.length; ++i) // find the max score
        if (b[i] != null)
            max = max > b[i]? max : b[i];
    for (var i = 0; i < a.length; ++i) // count the number of alignments having the max score
        if (b[i] == max)
            ++n_max;
    for (var i = 0; i < a.length; ++i) { // count best alleles
        if (b[i] != max) continue;
        var g = a[i][5];
        if (h[g] == null) h[g] = 1 / n_max;
        else h[g] += 1 / n_max;
    }   
    a.length = 0;
}

var a = [], h = {}; 
while (file.readline(buf) >= 0) {
    var t = buf.toString().split("\t");
    for (var i = 6; i <= 8; ++i)
        t[i] = parseInt(t[i]);
    if (t[8] - t[7] < t[6] * min_frac) continue; // skip poor alignments
    if (a.length && t[0] != a[0][0]) // now we come to a new read
        process_a(a, h); 
    a.push(t);
}
process_a(a, h); 

file.close();
buf.destroy();

var c = []; 
for (var g in h) // get the list of alleles and counts
    c.push([g, h[g]]);
c.sort(function(a,b) {return b[1]-a[1]}); // sort by counts, in the descending order
for (var i = 0; i < c.length; ++i) // print them out
    print(c[i].join("\t"));
```

**Comment by cliu32** [comment]
Thank you for getting back so quickly. k13 worked very well indeed. I also noticed that the number of reads mapped also decreased dramatically while significantly more reads were mapped to 03:04. How did you arrive at k13? I see the default for map-ont is k15.

**Comment by lh3** [comment]
I saw missing hits to exon 2 because sometimes minimap2 can't find 15bp seeds. Reducing seed length usually helps sensitivity at the cost of performance, but you have a tiny reference anyway, performance wouldn't be a big concern. Option "-N50" also helps when you have many highly similar reference sequences.

I am closing this issue now as your key issue has been resolved. You can still post questions in this thread or create new issues. I will be notified by emails.
