### ISSUE TITLE
The index difference between  with and without preset

### ISSUE THREAD

**Issue by lipidong** [lh3/minimap2#841]
with preset splice
```
minimap2 -x splice -d mm10_rmchr.splice.mmi mm10_rmchr.fa
```
the filesize of mm10_rmchr.splice.mmi  is 11GB

without splice
```
minimap2  -d mm10_rmchr.splice.mmi mm10_rmchr.fa
```
the filesize of mm10_rmchr.splice.mmi  is 6.2GB

what is the difference between  with preset and without ?

Is it the essential to align the cDNA read to reference using the preset?

**Comment by lh3** [comment]
The index is affected by command line options including presets. If unsure, don't use prebuilt indices.
