### ISSUE TITLE
Cannot add coverage data due to mismatched ID's.

### ISSUE THREAD

**Issue by ngroberts** [lh3/minimap2#842]
"UserWarning: Contig names in the coverage file did not match dataset identifiers."

Hello,
I am attempting to add coverage based on a bam file generated from minimap2. However regardless of if I use sed and change the id's to be correct or not I still get this error when using blobtools add --cov.

The reads are HiFi and were assembled with hifiasm.

I generated the mapping data using:
`minimap2 -ax map-hifi -t 16 my_assembly.fasta my_reads.fasta`
`samtools sort -@48 -O BAM output_bam -o output_sorted.bam`

However I still get the above error. If I were to change the contig names in a sam file first > convert to bam > sort. I still get this error. The progress bar reaches about 20-30% and gives me:

> Traceback (most recent call last):
>   File "/home/mysystem/bin/blobtools2/lib/add.py", line 194, in <module>
>     main()
>   File "/home/mysystem/bin/blobtools2/lib/add.py", line 147, in main
>     parsed = field["module"].parse(
>   File "/home/mysystem/bin/blobtools2/lib/cov.py", line 244, in parse
>     fields = parse_bam(
>   File "/home/mysystem/bin/blobtools2/lib/cov.py", line 72, in parse_bam
>     raise UserWarning(
> UserWarning: Contig names in the coverage file did not match dataset identifiers.

I am not sure how else to fix this, I am curious if it is perhaps the way I generated this data. I am not sure. 
A potential workaround could be to instead make a coverage txt file using:
`samtools coverage`
and then adding it as text? I am unsure.

Thank you in advance.

**Comment by lh3** [comment]
This seems a blobtools issue.
