### ISSUE TITLE
failed to parse the first FASTA/FASTQ record

### ISSUE THREAD

**Issue by chaoyyyy** [lh3/minimap2#843]
Dear Mr. Li

Recently, I used the minimap2 to align two genomes sequences.
But I encountered an  error of minimap2 as following: "[WARNING] failed to parse the first FASTA/FASTQ record. Continue anyway."
And other chromosome sequences can conduct alignment successfully, except the first sequence.
The first fasta sequence is very long and more than 3 Gb.  Whether the error caused by the long sequence？
How can I solve the problem by adjust some parameters of minimap2? Or other suggestions?

**Comment by lh3** [comment]
See Limitations in readme.
