### ISSUE TITLE
Overflow error - chromosome > 2Gb

### ISSUE THREAD

**Issue by tbrown91** [lh3/minimap2#844]
Hello,

I am working with a genome that has a few chromosomes larger than 2Gb and am running into signed int errors based on the chromosome size. Is there a version of minimap which allows these large chromosomes, or is there a quick fix I could make in the code and recompile?

Many thanks,

Tom

**Comment by slw287r** [comment]
The `--split-prefix` parameter may help you out
```
       --split-prefix STR
                 Prefix to create temporary files. Typically used for a multi-part index.
```

**Comment by lh3** [comment]
Unfortunately, minimap2 won't work for a single chromosome longer than 2GB. See the Limitations section.
