### ISSUE TITLE
no SQ lines present in the header

### ISSUE THREAD

**Issue by Estherrr1997** [lh3/minimap2#845]
Hey there,

I am using minimap2 to align reads to a genome, both in fasta format.
This is the .slurm script I use:

#!/bin/bash

#SBATCH --job-name=alignment_blueshark_hifiasm
#SBATCH --partition="cpu-long"
#SBATCH --ntasks=8
#SBATCH --time=18:00:00
#SBATCH --mem-per-cpu=4g

/home/software/minimap2-2.22_x64-linux/minimap2 -ax map-hifi --secondary=no -I64g \
/home/data/reads_fasta/*reads.bam.fa \
/home/data/genome_files/bluesharkhifiasm.fa > /home/data/alignment_blue_shark/alignment_bs.sam

# to include the SQ headers in the alignment:
# use: -I64g

But when I try to convert the sam file to a bam file I get:
[E::sam_parse1] no SQ lines present in the header
[W::sam_read1] Parse error at line 2
[main_samview] truncated file.
[E::hts_open_format] Failed to open file "alignment_bs.sorted.bam" : No such file or directory
samtools index: failed to open "alignment_bs.sorted.bam": No such file or directory

The sam file seems to have headers like "@PG" and not "@SQ". I don't know how to fix this. I want to use the converted bam file to analyze the data with qualimap. 

I tried both the -I 64g and the --split-prefix options but the error still occurs.
Do you know how I can fix this error?

Kind regards,
Esther

**Comment by lh3** [comment]
If you want to map reads to an assembly, you should switch the order of the two files.

**Comment by Estherrr1997** [comment]
Thank you, this worked!
