### ISSUE TITLE
Filtering of secondary alignments based on alignment score

### ISSUE THREAD

**Issue by dparks1134** [lh3/minimap2#848]
Hi,

I'm attempting to filter secondary alignments using the secondary-to-primary score ratio (`-p`) option in minimap2 2.23-r1117-dirty:
```
minimap2 -ax sr ref.fna query.fna -p 1.0 --secondary=yes
```

In my simple test case, I get the following results for the first query read:
```
q1      0       ref1A   161     3       80M     *       0       0       TGGAATACAGAGGCTATGACTCAGTGGGCATGGCAACGCTCAATGGTAGCAAAATATACATTAAAAAAGACAGTGGCAAA        *       NM:i:0  ms:i:160        AS:i:160      nn:i:0   tp:A:P  cm:i:9  s1:i:50 s2:i:50 de:f:0  rl:i:0
q1      256     ref1B   161     0       80M     *       0       0       *       *       NM:i:1  ms:i:154        AS:i:154        nn:i:0  tp:A:S  cm:i:9  s1:i:50 de:f:0.0125     rl:i:0
```

The second alignment is marked as secondary, but I'm surprised that it is reported. It has an alignment score of 154 compared to 160 for the primary alignment due to the presence of a single mismatch (NM:i:1). Is this not sufficiently worse of an alignment to be filter out when `-p` is set to 1.0? Is the score used by `-p` the alignment score or a different internally used scoring function?

Thanks for any insights you can provide.

Cheers,
Donovan

**Comment by lh3** [comment]
There are other parameters that control alignment. Applying `-p 1.0` will lead to worse alignment and is strongly discouraged. Please filter alignment downstream.
