### ISSUE TITLE
Typos in manual for default parameter settings

### ISSUE THREAD

**Issue by eboyden** [lh3/minimap2#851]
I was tinkering with minimap2 (2.23) `-x sr` settings on Illumina PE150 data, and was not able to recapitulate output using the default settings when I overwrote the `-m` setting with the specified default of 20 in the manual.  Some testing showed that the actual default setting is 25.

I also noticed that some of the specified default settings in the manual do not match the specified defaults in the help message (e.g. `-s` is 80 in the help but 40 in the manual; I think there may be others).  In the manual the `-w` default is specified as "2/3 of k-mer length" (which is 15 by default), but in the help it's specified simply as "10"; the latter description is less confusing if `-w` doesn't actually scale with `-k` when not overwritten (which I assume is not the case).

**Comment by lh3** [comment]
Thanks. Manpage updated.
