### ISSUE TITLE
Cookbook recipe for ONT long-read overlaps generates errors

### ISSUE THREAD

**Issue by plattsad** [lh3/minimap2#852]
Hi.  In the cookbook the advice to set -r to 10000 seems to conflict with -x ava-ont option that sets 
bw_long to 2000: https://github.com/lh3/minimap2/blob/ac334639ce74a2e0133ab6c64ba7c0cdec6d49f5/options.c#L97 

This combination causes mo->bw_long to be less than mo->bw that in turn seems to trigger the error
"[ERROR] with '-rNUM1,NUM2', NUM1 (10000) can't be larger than NUM2 (2000)"

Any suggestions for an appropriate value of NUM2 (bw_long) here, also 10,000 maybe?

```
# For Nanopore reads (ava-ont also works with PacBio but not as good):
minimap2 -x ava-ont -r 10000 ecoli_p6_25x_canu.fa ecoli_p6_25x_canu.fa > overlap.paf
```

**Comment by lh3** [comment]
Thanks!
