### ISSUE TITLE
unequal mapping length between minimap2 and the online ncbi blast

### ISSUE THREAD

**Issue by ShannonDaddy** [lh3/minimap2#853]
Hi, I found a mapping length difference between minimap2 and ncbi-blast for the same query and reference sequences, which results in totally different sequence identities. 

my minimap2 version is 2.17-r941 with the following running command:
minimap2 -x map-ont ref.fa query.fa -t 1 --cs > test.paf

the content of test.paf:
![image](https://user-images.githubusercontent.com/6656888/146322679-d26b0a92-9934-4180-8910-3e870d060b49.png)

however, the online ncbi blast result looks like:
![image](https://user-images.githubusercontent.com/6656888/146323188-16e86fb8-20a8-45b8-a35b-e3ba2d1cd996.png)

my sequence files are attached.
[seq.zip](https://github.com/lh3/minimap2/files/7725152/seq.zip)

please help me out, thanks a lot!

**Comment by ShannonDaddy** [comment]
Hi, I added an argument to the command, the result seems to be fine.

the new command is:
minimap2 -cx map-ont ref.fa query.fa -t 1 --cs > test.paf

![image](https://user-images.githubusercontent.com/6656888/146706856-2de09e7f-e849-4fe1-b14b-4e6331bfce16.png)

I check the manual of minimap2, I find the meaning of '-c' argument is: 
-c           output CIGAR in PAF

But I don't know why. In my understanding, the identities should be identical no matter the '-c' argument is added or not.

Looking forward to your reply, thanks!

**Comment by lh3** [comment]
See FAQ.
