### ISSUE TITLE
Adding specific sam tags to the paf file

### ISSUE THREAD

**Issue by rezenman** [lh3/minimap2#854]
Hey all,
I have a really simple question that I can't find the answer for,
In the documentation, you write: "PAF may optionally have additional fields in the SAM-like typed key-value format. Minimap2 may output the following tags:"
I want to add to my PAF file the AS tag (DP alignment score),
So, is there a way to do it directly when creating the PAF file? or do I have to go through the SAM file and extract it separately?
Thank u very much

**Comment by lh3** [comment]
You need option `-c`.
