### ISSUE TITLE
how is minimap2 selecting output hit between equally good hits (mapq=0)?

### ISSUE THREAD

**Issue by katrinakalantar** [lh3/minimap2#857]
Hello,

Thanks for maintaining this great tool! I'm running into a question that seems similar to one posted previously here ( https://github.com/lh3/minimap2/issues/370) and hoping to get a bit more clarity.

When running minimap2, it seems that it can output secondary mappings that are of lower alignment quality (via `--secordary=yes`). However, it seems that exact matches (multi-mappers, identified by the `mapq = 0`) are not output when using the `--secondary=yes` option. Is this correct? If so, **how is minimap2 selecting the output target when there are multiple equivalent matches?** Is it random? 

To be specific, when I see a line in the output .paf file that looks like this:
`NZ_CP006777.1-10238/1	150	0	150	-	CP000721.1	6000632	2389307	2389457	150	150	0	NM:i:0;ms:i:300;AS:i:300;nn:i:0;tp:A:P;cm:i:8;s1:i:124;s2:i:124;de:f:0;rl:i:0;cg:Z:150M`

...the read mapped to `CP000721.1`, but was a multi-mapper (`mapq=0`). How did minimap2 select `CP000721.1` amongst the other possible, equally-good, matches?

**Comment by lh3** [comment]
Random with the random seed determined by the query name.
