### ISSUE TITLE
Subread Bam File Failed to Align Using pbmm2

### ISSUE THREAD

**Issue by JiaweiShen1116** [lh3/minimap2#863]
Hi,

I am currently using the pbmm2 software to align 23 of my PacBio subreads bam files to the reference genome for further analysis. However, all of my 23 subreads bam files have been successfully aligned to the reference genome except for one, and the error message was “terminate called without an active exception” (please refer to the attached screenshot for more details). I don’t know if this error suggest some issues with the bam file that failed to align or otherwise. Since there is no “Issue” section on the pbmm2’s Github page for me to report this issue, I wonder if I should report this issue here to resolve this problem. The options I used for pbmm2 align command in this case were "--preset SUBREAD --sort --median-filter". Thank you very much.

Best,
Jiawei Shen
<img width="807" alt="Screen Shot 2022-01-27 at 09 30 40" src="https://user-images.githubusercontent.com/72170938/151413999-14c0e386-d8a4-4217-9aa5-de770eac2dc0.png">

**Comment by JiaweiShen1116** [comment]
I tried to change the --log-level option of the pbmm2 align command to "DEBUG" hoping to get a more detailed error message, but the log file still simply reports the error as "terminate called without an active exception". Should I still try other --log-level options?

**Comment by lh3** [comment]
Please create an issue at the pbmm2 repo.

**Comment by martinjvickers** [comment]
@JiaweiShen1116 PacBio have a single repository with issues enabled for you to ask your question here;

https://github.com/PacificBiosciences/pbbioconda/issues

**Comment by lh3** [comment]
Thanks for the pointer, @martinjvickers!
