### ISSUE TITLE
Reference Genome Indexing

### ISSUE THREAD

**Issue by aalkin2001** [lh3/minimap2#864]
Hi,
I want to analyze RNA-seq data from Oxford Nanopore sequencer (minion), and I was trying to generated an index for the human reference genome hg38, which I downloaded the Genome FASTA file from NCBI. I use the command below to generate an index file.

**minimap2 -d ref.mmi hg38.fa**    

I got **ref.mmi** as output file. Below are my questions:

1. Is it the generated ref.mmi file that will be used for alignment in this command? **minimap2 -a ref.mmi reads.fq > alignment.sam**
2. Aren't we going to use Genome annotation GFF File to make the index?

Thank you for your anticipated response.

**Comment by lh3** [comment]
See README
