### ISSUE TITLE
obtain homologous sequences

### ISSUE THREAD

**Issue by melodysyue** [lh3/minimap2#865]
Hi Dr. Li,

I conducted genome alignment between closely related species A and B using minimap2 (-ax asm5). I am interested in several genomic regions (with known start and end positions) in A. How should I extract homologous sequences of these regions in B based on the minimap2 alignment output?

Thanks!

**Comment by lh3** [comment]
Try `paftools.js liftover`. See the cookbook or the [misc directory](https://github.com/lh3/minimap2/tree/master/misc).
