### ISSUE TITLE
Minimap2 or BWA MEM for short DRS reads

### ISSUE THREAD

**Issue by AnWiercze** [lh3/minimap2#866]
Hi Dr. Li,

Thanks for providing this nice tool! 

I am working with short direct RNA sequencing reads (mean length = 105 bp) sequenced with ONT's MinION and I was wondering if you have any suggestion or recommendation which alignment strategy (including parameters) I should use for mapping short DRS reads onto reference fasta file with sequences of length 60-90bp?

I have already tried both the bwa mem and minimap2 mapper with the following parameters:
```
minimap2 -ax map-ont <ref> <reads>

bwa mem -x ont2d -W13 -k6 <ref> <reads> # has been used for direct tRNA sequencing reads in a paper from 2021 (Thomas et al.)

```
In my case, the two alignment strategies revealed completely different numbers of mapped reads (>40x more reads detected with BWA MEM). Now I am unsure which of these two results are more reliable. 

Thanks for your help! 

Best, 
Anna

**Comment by lh3** [comment]
bwa mem should be better.
