### ISSUE TITLE
What is the reason to use “--no-long-join” for all-vs-all read overlapping?

### ISSUE THREAD

**Issue by lauraht** [lh3/minimap2#869]
Hi Heng,

The preset ` -x ava-ont` is equivalent to ` -k15 -Xw5 -m100 -g10000 -r2000 --max-chain-skip 25`, where ` -X ` is equivalent to `-DP --dual=no --no-long-join` and is primarily used for all-vs-all read overlapping. Since I need to keep self mappings and dual mappings, I do not use the `-D` and `--dual=no` options, so I specify these options individually instead of using the preset. One thing I am not sure is whether I should use the `--no-long-join` option. I was wondering what is the reason to use `--no-long-join` for all-vs-all read overlapping?
What would be the effect on the result if using or not using the `--no-long-join` option in all-vs-all read overlapping? I would appreciate your advice.

Thank you very much!

**Comment by lh3** [comment]
The long-join heuristic aims to find SVs but read overlapping doesn't need to alignment with SVs. Using long-join in read overlapping will be slower. How much that may affect assembly depends on the behavior of the assembler in use.

Given that modern assemblers all come with overlappers, I don't think we need to use minimap2 for read overlapping.

**Comment by lauraht** [comment]
Hi Heng,

Thank you so much for your explanation!

I am actually using RNA-seq read overlapping to help downstream read clustering, rather than for assembly. 
Would using the long-join heuristic yield a bit higher accuracy in read overlapping than `--no-long-join`, or is there not much of a difference in accuracy?

Thank you very much again!

**Comment by lh3** [comment]
I don't know. Better try both.
