### ISSUE TITLE
mappy preset of paired-end short reads

### ISSUE THREAD

**Issue by lozybean** [lh3/minimap2#87]
Python api is wonderful, it wil be great if there's a preset for paired-end short reads.

How do you think of minimap2 and bwa-mem for paired-end short reads (like illumina platform) mapping? Is it the time for replacing bwa-mem with minimap2 totally?

**Comment by lh3** [comment]
> Python api is wonderful, it wil be great if there's a preset for paired-end short reads.

I will add paired-end support to mappy later.

> How do you think of minimap2 and bwa-mem for paired-end short reads (like illumina platform) mapping? Is it the time for replacing bwa-mem with minimap2 totally?

Preliminary evaluation by myself suggests minimap2 is promising for short reads as well. Broad and Illumina are independently evaluating minimap2. I think you should wait until I hear back from them.

**Comment by lozybean** [comment]
Thank you!

**Comment by lh3** [comment]
I am reopening it until I actually implement this in mappy. A reminder for myself.

**Comment by lh3** [comment]
Done via 46d6349. Here is an example script:
```python
import mappy as mp

a = mp.Aligner('test/MT-human.fa', preset='sr')
s1 = 'GGCGACAAACCTACCGAGCCTGGTGATAGCTGGTTGTCCAAGATAGAATCTTAGTTCAACTTTAAATTTGCCCACAGAACCCTCTAAAACCCCTTGTAAA';
s2 = 'GACAGTGAGGGTAATAATGACTTGTTGGTTGATTGTAGATATTGGGGTGTTAATTGTCAGTTCAGTGTTTTAATCTGACGCAGGCTTATGCGGAGGAGAA';
for h in a.map(s1, s2):
	print('foo/{}\t{}'.format(h.read_num, h))
```
Mappy still yields a single stream of hits. You have to separate them out by checking the new `read_num` field. The next mappy release, v2.8, will have this functionality.

I am closing this issue now. If you see bugs in the new code, please feel free to create new issues.
