### ISSUE TITLE
Feature request: SAM input

### ISSUE THREAD

**Issue by marcus1487** [lh3/minimap2#870]
A SAM format tag for storing methylation and modified base information has recently been officially included in the SAM specification. At nanopore, we are starting to move towards outputting basecalls in sam/bam/cram format by default in order to store the methylation information that comes along with basecalling.

One hinderance to this output is that (I believe) SAM format cannot be specified as the input to minimap2.

One possible workaround would be to use the undocumented `-y` argument and add the modified base SAM tags to the FASTA/Q input, but this feels like quite an unstable solution relying on an undocumented argument and a non-standard FASTA/Q read-header formatting.

I am aware that full SAM format support may be out of scope, but hoping we might open some discussion around the scope that might be allowed by minimap2. Specifically, I am thinking of mapped read input and multi-mapping reads as potential inputs that might not be supported. I think the core support would be to pass the sam tags forward to the minimap2 output. There may be some issues even here for conflicting tags that minimap might add. Hopefully these tags might be overwritten by minimap2, but tags not output by minimap2 would be copied from the input.

I hope that this feature request might be considered and look forward to thoughts on the feasibility of this feature request.

**Comment by lh3** [comment]
I wouldn't add SAM/BAM support. htslib is a non-trivial dependency and having it would make minimap2 harder to install.

> the undocumented -y argument

`-y` was added and documented in the manpage nearly 5 years ago with 08bd212. Many options are not shown on the command line because they may make users harder to find more common options. You can use `samtools fastq` to copy over tags
```
samtools fastq -TXX,YY aln.bam | minimap2 -y ref.fa -
```
> I am thinking of mapped read input and multi-mapping reads as potential inputs that might not be supported.

In SAM, multi-mapping is flagged with 0x100 and chimeric alignment is flagged with 0x800. `samtools fastq` by default skips these alignments – I changed the SAM spec for proper sam-to-fastq conversion. Multi-mapping is not an issue.

> There may be some issues even here for conflicting tags that minimap might add.

It is up to the user to control which tags to copy over.

**Comment by marcus1487** [comment]
I had a go at using this workaround and this does not seem to solve the issue. The `samtools fastq` command cannot handle the, `B`, array tag type (of the ML/Ml tag). Maybe this is an issue that should be logged with the samtools repo? A [SO post from 2018](https://bioinformatics.stackexchange.com/questions/4132/sam-format-does-the-bam-integer-or-numeric-array-field-no-longer-exist-why) seems to indicate that this is simply a matter of a pull request to samtools, but I'm not sure if there are larger reasons this has not been implemented there.

**Comment by jmarshall** [comment]
`samtools fastq` has handled B-arrays since samtools/samtools#1301, which landed in 1.11.

**Comment by marcus1487** [comment]
Apologies @jmarshall , I'm not sure how samtools 1.10 got into my path. I can confirm that this command works with the most recent samtools.
