### ISSUE TITLE
Amount of Memory required to build NT database

### ISSUE THREAD

**Issue by YasirKusay** [lh3/minimap2#871]
Hi,

How much memory would be required to build an index from the NCBI NT database (533 GB), and how much would be required to run a sample against that index.

**Comment by lh3** [comment]
minimap2 by default indexes 4Gb reference sequences, maps all input reads, and moves to the next 4Gb reference sequences. In this mode, it doesn't take much memory.

**Comment by YasirKusay** [comment]
Hi @lh3, thank you for your reply. So this mode will require a memory amount that is equivalent to the size of the input database? 
This mode will be slower though right? What if I want to generate the index beforehand?

**Comment by lh3** [comment]
> So this mode will require a memory amount that is equivalent to the size of the input database?

No. It is independent of the size of the database.

> This mode will be slower though right?

Yes, slower. You need `--split-prefix` to get proper sam output. Check manpage.

> What if I want to generate the index beforehand?

You can just do that.

**Comment by YasirKusay** [comment]
Hi, if I do want to build my own index, what is the expected amount of RAM required for the NCBI NT database (533 GB).

**Comment by lh3** [comment]
A few tens of GB, I guess.

**Comment by YasirKusay** [comment]
Hi @lh3 , I have attempted to build the index using 100GB of memory (gives a good idea of what memory I may need). The build failed and returned a segmentation fault, and the thread here (https://github.com/lh3/minimap2/issues/75) suggests it may be due to insufficient memory. Do you know if this is because of the input file, or because it is actually due to insufficient memory.
