### ISSUE TITLE
Read not reported in the all-vs-all read overlapping output .paf file

### ISSUE THREAD

**Issue by lauraht** [lh3/minimap2#874]
Hi Heng,

I ran minimap2 all-vs-all read overlapping for ONT RNA-seq (cDNA) reads by using the following options:
```
minimap2 --all-chain --no-long-join -k15 -w5 -e0 -m100 -g10000 -r2000 --max-chain-skip 25
```
So the output would contain self mappings.

I found that a read was not reported in the output .paf file. I thought it should at least have a self mapping reported in the .paf file if it has no overlaps with other reads. The read is kind of short (length 87) as shown below:
```
GGGGCTCTTCGGGCCTTAGCGCCATTTTGGAAACCCTGCGCTAAGGAGAGCCAAGTGGAGGAAGAAGGAATGCGCAGGCTGAAGCGC
```
I was wondering what would be the reason that this read’s self mapping was not reported in the .paf file?

I am using minimap2 version 2.21-r1071.

Thank you very much in advance!

**Comment by lauraht** [comment]
Hi Heng,

I did not use the `-D` option. Other reads have their self mappings reported (even for those reads with no overlaps with other reads, their self mappings were still reported). But this read was not reported in the .paf file at all. So I was wondering if this is related to the read length or something else?

Thank you very much!

**Comment by lh3** [comment]
Read length or repetitive seeds.
