### ISSUE TITLE
minimap2 Segmentation fault when both spliced alignment and scoring are defined

### ISSUE THREAD

**Issue by lpryszcz** [lh3/minimap2#875]
Hi, 

minimap2 fails with `Segmentation fault (core dumped)` when both spliced mode and scoring are defined: 
```
minimap2 -axspliced -A2 -B4 -O4 -E2 $fasta $fasta
minimap2 -a -uf -A2 -B4 -O4 -E2 $fasta $fasta
```  

The same works fine when either `spliced` or `scoring` is defined. 
```
minimap2 -axmap-ont -A2 -B4 -O4 -E2 $fasta $fasta
minimap2 -axspliced $fasta $fasta
```

Interestingly, when minimap2 is executed without SAM output (`-a`) it works fine as well. 
```
minimap2 -xspliced -A2 -B4 -O4 -E2 $fasta $fasta
```

I'm using v2.17-r941. The same behaviour is present in the latest version (2.24-r1122). 

Any idea?

**Comment by lh3** [comment]
You are specifying one-piece single gap penalty but the splice mode only works with 2-piece gap penalty, like `-O2,32 -E1,0`.
