### ISSUE TITLE
Read no longer has any overlaps reported like before when it is 7 bases shorter than before

### ISSUE THREAD

**Issue by lauraht** [lh3/minimap2#877]
Hi Heng,

I ran minimap2 all-vs-all read overlapping for ONT RNA-seq (cDNA) reads by using the following options:
```
minimap2 --all-chain --no-long-join -k15 -w5 -e0 -m100 -g10000 -r2000 --max-chain-skip 25
```
Previously, I used Porechop to trim adapters. For read1, minimap2 was able to find 435 reads that overlap with read1.
Now, I used Pychopper to trim adapters, and Pychopper also oriented reads to the forward strand. But now minimap2 no longer reports any overlapping reads for read1.

I checked the fastq file. Those reads overlapping with read1 reported by minimap2 in the previous Porechop-trimmed dataset still exist in the current Pychopper-trimmed dataset. So I do not understand why minimap2 no longer reports any overlapping reads for read1 in the current Pychopper-trimmed dataset.

The current Pychopper-trimmed read1 is 7 bases shorter than the previous Porechop-trimmed read1, and it is oriented from the "-" strand to the "+" strand.
The following is the previous Porechop-trimmed read1 (length 300, the "-" strand):
```
TTTCTTTTTGCGGTTTTCAAATGTTTATTTATATACAAAGAATTATCCCGTGGTTTTCATTGGTGATGCCCGGATAATCCTCTGAAGGAAGAGCAGCTGGTCCAACTTAATGAAACCGATATCGCTAGCGTACTGACGGAAACACTGGCGGCTTTATATTGAGGCCATATTCCGGATCAGACGATGCCGGTTTGAACGAACACAGAGCGAGAACCTGACCCGAATTTTCGCGGGTGAAAACCAATTGCAGCTGCTGGCAAGTGACCCATCTTGCTCCAGCAGTGCAACGAGGTAAAGCCC
```
The following is the current Pychopper-trimmed read1 (length 293, oriented to the "+" strand):
```
GGGCTTTACCTCGTTGCACTGCTGGAGCAAGATGGGTCACTTGCCAGCAGCTGCAATTGGTTTTCACCCGCGAAAATTCGGGTCAGGTTCTCGCTCTGTGTTCGTTCAAACCGGCATCGTCTGATCCGGAATATGGCCTCAATATAAAGCCGCCAGTGTTTCCGTCAGTACGCTAGCGATATCGGTTTCATTAAGTTGGACCAGCTGCTCTTCCTTCAGAGGATTATCCGGGCATCACCAATGAAAACCACGGGATAATTCTTTGTATATAAATAAACATTTGAAAACCGCAA
```
The only difference is 7 bases shorter and oriented to the forward strand.

I was wondering why minimap2 no longer reports any overlapping reads for read1, as it was able to report 435 overlapping reads for read1 before? 

I also found that there are a large percentage (~40%) of reads with no overlapping reads reported, and those reads are relatively shorter than the reads with overlaps reported. I also used isONclust to cluster the reads and found that those reads (including read1) belong to large clusters, so I think they should have overlaps with other reads.

What parameter values could I adjust in order to have minimap2 to more likely find the overlapping reads?

I would greatly appreciate your advice.

Thank you very much in advance!

**Comment by lh3** [comment]
Read overlapping only intends to find the top several overlaps. For assembly, that is good enough. Also, read overlapping only works well for ~10kb reads. 300bp is far too short.

**Comment by lauraht** [comment]
Hi Heng,

Thank you very much for your explanation!

What I do not quite understand is why minimap2 was able to find 435 overlapping reads for this length-300 read previously but now cannot find any overlapping reads when the same read became only 7 bases shorter?

Due to short transcripts, RNA-seq ONT full-length reads have many shorter reads: the median read length is 700. So for RNA-seq read overlapping, should I change some parameter values? Would reducing the k-mer length `-k` help find overlaps for RNA-seq reads? What about the window size `-w` and the chaining score `-m`?

I would really appreciate your advice.

Thank you so much!
