### ISSUE TITLE
huge number of reads aligned in a fairly small region 

### ISSUE THREAD

**Issue by PolinaSkr** [lh3/minimap2#878]
Dear Colleagues! 

We try to align Nanopore reads to a 3Mb fragment of our model object genome (it is approximately 1% of the entire genome length) using the `minimap2 -ax map-ont` command, the fragmetnt was indexed previously. As a result, about 1 million unique Nanopore reads with flags 0 and 16 (which are primary alignments as we supposed) are aligned into this fragment. This is 77% of the total number of reads obtained by whole genome sequencing. We inspected the alignments in IGB and it seems that most of the reads have a very short matching part with the huge clippings. This seemed extremely strange to us, we would like to get the reads specifically aligning to the specified genomic region, but instead we get an assortment of short unuseful alignments. 

Could you please tell what we did wrong or recommend how should we change the parameters to get more reasonable alignments?

**Comment by lh3** [comment]
Please map to the whole genome.
