### ISSUE TITLE
minimap2 aligned some reads to the opposite strand

### ISSUE THREAD

**Issue by lauraht** [lh3/minimap2#88]
Hi Heng,

Happy New Year!

We were using minimap2 (version 2.2-r409) for spliced alignment of PacBio reads to human genome. The only options we used were “-ax splice”. The command was as follows:

minimap2 -ax splice GRCh38.fa IsoSeq_MCF7_2015edition_polished.unimapped.fasta > longreads.original.sam

IsoSeq_MCF7_2015edition_polished.unimapped.fasta was publicly released by PacBio (http://datasets.pacb.com.s3.amazonaws.com/2015/IsoSeqHumanMCF7Transcriptome/list.html).

We found that minimap2 aligned quite a number of reads to the opposite strand. We ran Scallop (an accurate reference-based transcript assembler by the Kingsford Lab, https://www.nature.com/articles/nbt.4020) on the minimap2 output to assemble transcripts. When comparing the Scallop output transcripts with the GRCh38.gtf reference annotation, we found that there are a considerable number of transcripts that have a match with the reference transcript but lie on the opposite strand. We then looked into the sam file outputted by minimap2. For the “opposite strand” transcripts, we looked for their matching coordinates in the sam file to see how the reads were mapped at those coordinates. We found that the strand info of the aligned reads corresponding to the transcript coordinates is consistent with the strand info of the transcript in the Scallop output. So we concluded that Scallop did not alter the strand info outputted by minimap2. To confirm this, we also ran GMap on the same MCF-7 dataset. We found that for those reads which minimap2 mapped to the opposite strand, GMap mapped them to the correct strand.

We are not sure under what circumstances this opposite strand problem occurs. I am uploading the sam file outputted by minimap2 (longreads.original.sam, a zipped file) here. In this sam file, an example of the opposite strand info is the read starting at 124911646 for chr12. Its strand info is “ts:A:+”. Its corresponding transcript assembled by Scallop oppositely matches to a transcript in GRCh38.gtf which has a strand info “-”. And the GMap output sam file has a strand info “XS:A:- ” for the read starting at 124911646 for chr12.

For comparison, we also ran Scallop by ignoring the strand info from the minimap2 output. We found that the output precision (reported by gffcompare) of running Scallop by using the strand info from the minimap2 output dropped nearly 45% compared to the output precision of running Scallop by ignoring the strand info from the minimap2 output.

[longreads.original.zip](https://github.com/lh3/minimap2/files/1601302/longreads.original.zip)

We’d greatly appreciate it if you could locate and fix this opposite strand problem.

Thank you very much!

**Comment by lh3** [comment]
Minimap2's "ts" is different from gmap's "XS". For gmap, "XS" is the strand of the transcript (inferred from the read) relative to the reference genome. For minimap2, "ts" is the strand of the read relative to the transcript. When a read is mapped to the reverse strand of the genome, "ts" is the opposite of "XS".

In your example, the read is mapped to reverse strand of the genome. Gene UBC at chr12: 124911646 is on the reverse strand of the genome, too. This means the read is on the same strand as UBC transcripts, so you see "ts:A:+".

If you want to get gmap's XS, you need to flip minimap2's ts if the read is mapped to reverse strand of the genome.

**Comment by lh3** [comment]
I didn't know how XS is used when you raised #28. Sorry for the confusion.

**Comment by lauraht** [comment]
Thank you very much for your clarification!

I am wondering if there is a tag in the minimap2 output sam file that indicates whether a read is mapped to the reverse strand of the genome? 

When a read is mapped to the reverse strand of the genome and the gene is also on the reverse strand of the genome, the read is on the same strand as transcripts, so we got "ts:A:+". When a read is mapped to the forward strand of the genome and the gene is also on the forward strand of the genome, the read is on the same strand as transcripts, so we also got "ts:A:+". I am wondering how we could distinguish these two situations (both have "ts:A:+") from the minimap2 output sam file? 

Similarly, there are also two situations which both have "ts:A:-".

I would appreciate your advice.

Thank you very much!

**Comment by lh3** [comment]
> I am wondering if there is a tag in the minimap2 output sam file that indicates whether a read is mapped to the reverse strand of the genome?

Strand is encoded at the FLAG (2nd) field. If bit 16 is set, the read is on the reverse strand. You need to read some tutorial or use a library.

> When a read is mapped to the forward strand of the genome and the gene is also on the forward strand of the genome, the read is on the same strand as transcripts, so we also got "ts:A:+".

Yes

> I am wondering how we could distinguish these two situations (both have "ts:A:+") from the minimap2 output sam file?

Check the alignment strand of the read (i.e. bit 16 of the FLAG field in SAM).

**Comment by lauraht** [comment]
Hi Heng,

Thank you very much for your advice! This is very helpful!

I was also wondering if it might be possible that, as an enhancement, Minimap2 (in “-ax splice” mode) also adds a “XS” tag in its output sam file for the strand of the transcript? I feel that this could be very useful as the “XS” tag is outputted by other RNA-seq aligners such as STAR, GMap, etc., so the users don’t need to post-process the Minimap2 output sam file before running reference-based assemblers.

We’d really appreciate it if adding a “XS” tag could be a possible enhancement in Minimap2.

Thank you very much!

**Comment by lh3** [comment]
XS is a custom tag. I will make a proposal to the SAM spec before implementing anything. Deriving XS from ts is straightforward. This should not stop users now.

**Comment by jmarshall** [comment]
> [@lh3] XS is a custom tag. I will make a proposal to the SAM spec before implementing anything.

Your proposal (samtools/hts-specs#292) resulted in a TS tag in the SAM spec with the following text:

> `TS:A:strand` Strand (‘`+`’ or ‘`-`’) of the transcript to which the read has been mapped.

As noted in the spec's appendix, it is intended to be equivalent to the XS tag produced by several RNA aligners.

You may wish to implement the now-standard TS tag.
