### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by duhuipeng** [lh3/minimap2#880]
Dear author
my code
$minimap2 -ax asm5 -t 85 --secondary=no  /work/ref.fasta /work//allreads.fa |samtools view -Sb > reads.bam
however, it have a error:,as follow
![image](https://user-images.githubusercontent.com/58722433/154655819-a6754794-9b94-4965-9039-cc6ef876edb4.png)
How to solve it ?

Best

**Comment by lh3** [comment]
Probably because minimap2 got killed due to insufficient memory.
