### ISSUE TITLE
Question about parameter choices for splice alignment of Nanopore 1D cDNA reads

### ISSUE THREAD

**Issue by lauraht** [lh3/minimap2#881]
Hi Heng,

In minimap2 document, it is recommended to use `-ax splice` for splice alignment of Nanopore 2D cDNA reads. And the `-x splice` uses `-k15 -w5`.

I have Nanopore 1D cDNA reads basecalled by Guppy, but the error rate is ~11-12%. Is `-ax splice` sufficient for these 1D cDNA reads, or do I need to use smaller `-k` and `-w`? 
Would using smaller `-k` and `-w` increase the accuracy in general?
What choices of `-k` and `-w` would you recommend for these 1D cDNA reads?

I would greatly appreciate your advice.

Thank you very much in advance!

**Comment by lh3** [comment]
Not sure. Try different parameters and see what works.

> Would using smaller -k and -w increase the accuracy in general?

Yes.
