### ISSUE TITLE
Feature request: paftools call VCF v4.3 output

### ISSUE THREAD

**Issue by schorlton** [lh3/minimap2#882]
As per title, it would be really helpful to know which bases are not covered by an alignment vs which are covered and simply found to be the reference base. I don't think it's possible to do this now as far as I can tell and would require VCF 4.3? Thanks for your consideration!!

**Comment by lh3** [comment]
In the non-VCF output, the R-lines give GIAB-like confident regions. Or you can run dipcall.

**Comment by schorlton** [comment]
Got it, thanks! Will parse non-VCF if possible. Unfortunately haploid organism and didn't see haploid mode for dipcall (correct if wrong).

**Comment by lh3** [comment]
With dipcall, you can provide the same file twice.
