### ISSUE TITLE
paftools.js call on MERS genome

### ISSUE THREAD

**Issue by aliakeefe** [lh3/minimap2#884]
Hello, I'm performing this function on fasta file containing MERS sequences. (can be found here https://www.ncbi.nlm.nih.gov/datasets/coronavirus/genomes/ ) My reference sequence is one of the MERS sequences from the file and my query is the list of sequences in that dataset. When I run call, I get no results, but when I look at the file stats, it shows some results. Is it because they are too similar? I tried this on a covid19 sequence and I get the same results. 

Thanks!

**Comment by lh3** [comment]
paftools.js call is intended for large genomes, not for viral genomes. You may try `paftools.js call -L10000 -l5000`, though I am not sure if it works.
