### ISSUE TITLE
paired-end alignment cannot be viewed as pairs in IGV?

### ISSUE THREAD

**Issue by olechnwin** [lh3/minimap2#885]
Hello,

I aligned my short reads with the following command:
```
minimap2 -ax sr ${ref_file} ${read1} ${read2} > ${out_file}.sam
samtools view -bS ${out_file}.sam > ${out_file}.bam
```
When I viewed the bam file in IGV, it doesn't give me an option to view as pair. However, it does highlighted the pair when I press ctrl+click on the read. Is there something I missed when running the command to enable viewing the alignment as pair in IGV?

Thank you!

**Comment by lh3** [comment]
If the output SAM has paired flag set, this is more of an IGV question which I don't know the answer to.

**Comment by olechnwin** [comment]
Thank you for your reply. I'll check the sam file and ask IGV team.
