### ISSUE TITLE
Parameter settings, do not allow gaps

### ISSUE THREAD

**Issue by armintoepfer** [lh3/minimap2#89]
Do you have experience with parameter settings for not allowing any gaps larger than 10bp for pacbio vs pacbio reads? I want to use that in the non-cigar mode, as computing the cigar with its DP is too slow for my use case.

Thank you!

**Comment by lh3** [comment]
Use `-r 10` to control the max gap size during chaining. If you are not using `-X` or `-x ava-pb`, you also need to add `--no-long-join`.

**Comment by lh3** [comment]
Does `-r 10` work for you?

**Comment by armintoepfer** [comment]
Yes it does, but sometimes it breaks reads into overlapping fragments. I don't have an example by hand right now, but if I see it again, will ping you.
