### ISSUE TITLE
asmgene giving results for less genes than the cDNA input file

### ISSUE THREAD

**Issue by 0seastar0** [lh3/minimap2#890]
Hi @lh3,

I'm trying to evaluate an assembly using asmgene and having an issue. 

I'm using a subset of genes 858 of interest (GRCHG38 from Ensembl) and following the protocol you describe on your blog post.
https://lh3.github.io/2020/12/25/evaluating-assembly-quality-with-asmgene

I am aligning the genes to the HG002 reference genome and my assembly of HG002 using minimap2 and then running asmgene.
The issue is that the results only give stats for 646 out of the 858 genes.

**Commands:**
minimap2 -cxsplice:hq -t96 /home/ubuntu/data/HG002/reference/HG002.pat.cur.20211005.fasta.gz /home/ubuntu/Homo_sapiens_hg38_cdna_MRG.fasta > ref.cdna.paf

minimap2 -cxsplice:hq -t96 /home/ubuntu/data/HG002/HG002_Guppy_5.0.7_0.8.0_assembly_02012022/Assembly.fasta /home/ubuntu/Homo_sapiens_hg38_cdna_MRG.fasta > asm.cdna.paf

/home/ubuntu/software/minimap2/misc/paftools.js asmgene -e ref.cdna.paf asm.cdna.paf > MRG.asmgene.stats.txt

**Results:**
0	asm.cdna	ALDH3A2|aldehyde	28779	JAHKSD010000022.1	19445989	19474761
F	asm.cdna	OTOA|otoancorin	97728	JAHKSD010000100.1	7155216	7252951
F	asm.cdna	CHRNA7|cholinergic	65077	JAHKSD010000064.1	12880906	12946187
0	asm.cdna	FAM161A|FAM161	29239	JAHKSD010000040.1	55503227	55532268
0	asm.cdna	BCKDHB|branched	2684	JAHKSD010000016.1	20614533	20617212
5	asm.cdna	OCLN|occludin	61724	JAHKSD010000048.1	2382741	2444606
0	asm.cdna	ACTN2|actinin	77922	JAHKSD010000006.1	92111034	92191263
0	asm.cdna	ECHS1|enoyl-CoA	10870	JAHKSD010000053.1	369662	380637
0	asm.cdna	FMO3|flavin	9831	JAHKSD010000006.1	26408666	26418535
d	asm.cdna	2	CORO1A|coronin	5356	JAHKSD010000074.1	644689	650045
d	asm.cdna	2	PRRT2|proline	3516	JAHKSD010000074.1	271416	274932
d	asm.cdna	2	HYDIN|HYDIN	2866	JAHKSD010000006.1	4555780	4558647
d	asm.cdna	3	NCF1|neutrophil	2104	JAHKSD010000010.1	86451510	86453604
d	asm.cdna	2	SMN2|survival	3555	JAHKSD010000181.1	375809	379364
d	asm.cdna	2	OPN1LW|opsin	6082	JAHKSD010000078.1	28782844	28788926
d	asm.cdna	2	OPN1MW|opsin	6078	JAHKSD010000078.1	28745042	28751120
H	Metric	ref.cdna	asm.cdna
X	full_sgl	638	629
X	full_dup	0	0
X	frag	0	2
X	part50+	0	1
X	part10+	0	0
X	part10-	0	6
X	dup_cnt	8	1
X	dup_sum	17	9

Do you have any idea why this might be happening?

Thanks for you time.

Best wishes,
Sara

**Comment by lh3** [comment]
Sorry for the late response. Asmgene filters out genes overlapping on the reference genome.
