### ISSUE TITLE
About minimap2 and smartie-sv

### ISSUE THREAD

**Issue by kizzb** [lh3/minimap2#891]
Hi,
    I have some questions about minimap2:
    1). minimap2 + paftools and smartie-sv to do assembly-to-assembly mapping and calling, which is better
    2). if I want to map distant species(eg: human and macaque), how should parameters be selected?

    Looking forward to your reply. Thanks. 

Best wishes,
bin

**Comment by lh3** [comment]
1. I don't know about smartie-sv. If not sure, try both.
2. Try asm20 first.

**Comment by kizzb** [comment]
I see, thanks for your help.
