### ISSUE TITLE
FLAG 256 vs 272 in SAM files

### ISSUE THREAD

**Issue by Mmark94** [lh3/minimap2#893]
Hi,
I would like to understand the difference between the FLAG "256" and "272" in SAM files. I understood that they are both involved in "secondary alignments" (https://github.com/lh3/minimap2/issues/4). However, I could not understand the difference between the two.
Is the FLAG "272" a secondary alignment in the reverse orientation? If not, is there a way to know if the secondary alignment is in the reverse orientation compared to the reference?

By the way, I think flagging secondary alignments is a great feature.

**Comment by WenyuLiang** [comment]
I think your understanding is correct.
