### ISSUE TITLE
Rechain condition

### ISSUE THREAD

**Issue by zory95** [lh3/minimap2#894]
Hello,

I have been working with minimap2 for a while. Recently, I have realized that this line code could be incorrect:

https://github.com/lh3/minimap2/blob/e018caea3279a7e663438bfc83480e7dfcaf3099/map.c#L290

As I understand, `qlen_sum` is the length of the sequence, `en` and `st` are the end and the start of the chain with the highest score, and `rmq_rescue_size` and `rmq_rescue_ratio` are the thresholds to determine if there is needed a rechain.

I think that the second part of the condition should be like this:

`en - st < qlen_sum * opt->rmq_rescue_ratio`

With the "<" instead of ">".

I did several experiments, and in all of then the condition was always true. Changing the sign, as I mentioned, avoids the rechaining for some of the sequences.

Kind regards.

**Comment by lh3** [comment]
The intended condition is
```c
if (qlen_sum - (en - st) > opt->rmq_rescue_size || qlen_sum - (en - st) > qlen_sum * opt->rmq_rescue_ratio) {
```
This means we rechain if the longest chain doesn't span most part of the query sequence. I will leave this open until I fix it.

**Comment by cxma** [comment]
Hi, yyds Li, what is the difference between the rechaining process and the first pass DP chaining ?  Dose it mean that we use more relax distance threshold to join adjacent chains ? 

Kind regards.

**Comment by lh3** [comment]
Fewer anchors (as most are dropped after the first round) and larger bandwidth
