### ISSUE TITLE
Minimap2: same read does not perfectly map to itself

### ISSUE THREAD

**Issue by yzhang-github-pub** [lh3/minimap2#896]
I have reads in a file, say 'reads.fastq.gz'. To find out overlapped reads, I did 'minimap2 reads.fastq.gz reads.fastq.gz > map_results.paf'. In this way each query read will map to itself. But I found the mapping was not perfect. For example:

read1    2314    2       2308    +       read1    2314    2       2308    2296    2306    60

So 'read1' does not map to itself from end to end. How come? Please help. Thanks. 

BTW, the version I used is 2.22.

**Comment by lh3** [comment]
See README.
