### ISSUE TITLE
error top hits when the database becomes larger

### ISSUE THREAD

**Issue by ShannonDaddy** [lh3/minimap2#897]
Hi, I got some error mapping results with minimap2 when the database becomes larger. 

minimap2 results (align.paf): 
the top hit of the query sequence ERR4436577.1033 is AP018340.1:57116-61843, which is not correct.
![image](https://user-images.githubusercontent.com/6656888/161416922-7daa6591-90f5-4623-9a9a-4c2c1341bcd8.png)

blast results (align.m7):
the top hit of the query sequence ERR4436577.1033 is CP009565.1:3228492-3233455, which is correct.
![image](https://user-images.githubusercontent.com/6656888/161417211-8c845541-1949-47e8-988d-b528d42d378e.png)

both minimap2 and blast use the same database file: db.fasta, which contains 147078 sequences.

the running script is minimap_vs_blast.sh
![image](https://user-images.githubusercontent.com/6656888/161417084-7c95e2c0-fc7f-4ba6-bd34-aefa06172a59.png)

when I use only the hits in the alignment results as a smaller database and  run the same script, the results becomes fine.

I am quite confused now. Are there any parameters to adjust in minimap2, so I can get the correct results. Please take a look, thanks a lot!

all the testing files and scripts were uploaded to dropbox, the url for downloading is:
https://www.dropbox.com/s/c9p9z0wn7fg1sxk/all_files.zip?dl=0

**Comment by ShannonDaddy** [comment]
I found that when I set the mapping options -f to 5000, the result is fine, maybe the reference database I used is highly redundant with many 16S rRNA sequences from silva, the cutoff of minimizer occurrence has to be increased during mapping.

the -f option in minimap manual:
![image](https://user-images.githubusercontent.com/6656888/162888127-562bb3cd-3969-4cec-bc06-72920e52db32.png)

the improved results:
![image](https://user-images.githubusercontent.com/6656888/162888360-d5502fa0-6b07-4ab7-96f7-01e8d6458a18.png)

**Comment by lh3** [comment]
Sorry for the late response as I saw you have found the answer on your own. Yes, you need a high threshold when mapping against a database of 16S. The default setting is tuned for whole genome.

**Comment by ShannonDaddy** [comment]
> 

Thanks a lot!
