### ISSUE TITLE
Align short reads to an uncorrected miniasm assembly

### ISSUE THREAD

**Issue by sjackman** [lh3/minimap2#90]
Hi, Heng. Do you have a suggestion for parameters to align Illumina reads to an uncorrected miniasm assembly with minimap2?

**Comment by lh3** [comment]
I don't know. It will be hard. Minimap2 won't work well at 15% error rate on ~150bp reads. Probably stampy or bwa-mem will work better.

**Comment by sjackman** [comment]
Okay. Thanks for the info. I'll try BWA-MEM. I'll also try first correcting with Racon.

**Comment by sjackman** [comment]
To map nanopore reads to an uncorrected miniasm assembly for Racon, do you suggest `minimap2 -xmap-ont`?

**Comment by lh3** [comment]
Perhaps also add `-xmap-ont -w5` to increase sensitivity.

**Comment by sjackman** [comment]
I'll try that. Thanks, Heng.

**Comment by lh3** [comment]
Any luck with either bwa-mem or minimap2?

**Comment by sjackman** [comment]
Rather than align to the uncorrected Miniasm assembly, I used two rounds of Racon correction with the Nanopore reads alone, and then aligned the short reads to the assembly using BWA-MEM. If I try aligning to the uncorrected assembly, I'll post back here. Thanks for your help, Heng.

**Comment by jdmontenegro** [comment]
Hi guys,

I wonder if this was ever sorted. what parameters were used to map short reads to a one-round polished miniasm assembly? Currently racon developper recommends using minimap2 with -x sr parameter, but I can see here that bwa mem should work better, which one would you finally recommend and what parameters should be fine-tuned? 
Cheers,
