### ISSUE TITLE
ONT direct RNA reads are mostly unmapped to reference genome, and have gaps in alignment

### ISSUE THREAD

**Issue by kaltinel** [lh3/minimap2#901]
Hi,
I am using minimap2 to align the base called reads to reference genome, for direct RNA sequencing experiments.
My reference genome is 1950nt long. My input is a ligation product of 2 pieces of RNA : 1870nt RNA attached to 80 nt RNA.

However, I have two issues in my pipeline:
( I am posting the results of my two sequencing experiments, with the same input, done on different days and on different flow cells )
1) I have very low amount of mapped primary reads:
![newplot(10)](https://user-images.githubusercontent.com/47667755/163820682-4b558200-9c9c-4dc3-b8ea-eae25c2175fb.png)

2) My reads are starting to map in the middle of the reference (having the highest coverage in the mid side of the reference)
![q1](https://user-images.githubusercontent.com/47667755/163820831-e6b10e7e-2b5b-4492-9b9c-e601b1678a28.png)
 
The start-stop positions and read length distributions are following:
![image](https://user-images.githubusercontent.com/47667755/163822299-2f374aaf-526d-42dd-85fd-3414568d9b0f.png)

It seems like most reads start from the middle of the sequence and end very quickly.

3) After ligation (when the long RNA is attached to short one), my coverage drops significantly and then recovers itself. However, the important parts of short RNA are already having low coverage.
![wh](https://user-images.githubusercontent.com/47667755/163821141-50d8c5fe-d35d-47c4-aa22-9f50c0c950d2.png)

My command line for minimap2 is as follows:
```
minimap2 -ax map-ont -uf -k5 -t 30 ref.fa fastq_pass/input.fastq > minimap2_results.sam
samtools view -F260 -h minimap2_results.sam > Primary-Alignments_minimap2_results.sam
samtools view -S -b Primary-Alignments_minimap2_results.sam > Primary-Alignments_minimap2_results.bam
samtools sort -o sorted_Primary-Alignments_minimap2_results.bam Primary-Alignments_minimap2_results.bam
samtools index sorted_Primary-Alignments_minimap2_results.bam 

```
And I use `sorted_Primary-Alignments_minimap2_results.bam` for the IGV visualization and count mapped/unmapped reads.

I would appreciate to have your help. Thanks.

**Comment by lh3** [comment]
This seems a property of your data.

**Comment by kaltinel** [comment]
And that would be the only issue possible? 
I was considering the effect of k-mer size and minimizers and other parameters, and hoping that you could help us regarding their adjustment.

**Comment by kenneditodd** [comment]
@kaltinel How did you generate the figure on the right in your first photo?
