### ISSUE TITLE
Large gaps in alignment for ONT direct RNA sequencing

### ISSUE THREAD

**Issue by kaltinel** [lh3/minimap2#902]
Hi, 
I am aligning the output of my ONT direct RNA sequencing libraries with minimap2 to their reference genome, with the parameters of:
`minimap2 -ax map-ont -uf -k5 `. 
Unfortunately, I am observing lots of gaps in my alignment:
![image](https://user-images.githubusercontent.com/47667755/164024709-1748fe1d-791d-4634-a489-f1e478d08a2e.png)
![image](https://user-images.githubusercontent.com/47667755/164024737-a513464d-ad94-4d02-a026-299be7907cac.png)

As in my understanding, lower k size will enhance the sensitivity towards noisy reads, however, this setting seems like favoring primary alignments with the cost of gaps and insertions. (row 1)
Then, to see if less sensitive kmer size will affect the amount of gaps, I changed my parameters to `minimap2 -ax splice -uf -k14 ` , which lowered the overall throughput and gaps mostly stayed. (row 2)
I wanted to test if the default options for genomic ONT reads would be more suitable, I run minimap2 with default parameters `minimap2 -ax map-ont` . (row 3)
![ask](https://user-images.githubusercontent.com/47667755/164026314-25a1b7df-80c7-45d7-9d4f-56278e83a1dc.png)

In this line, I would like to learn:
1) Why do I have many gaps/insertions in my alignments even when k size is large? Would adjusting penalty parameters be possible (to get more throughput)?
2) The kmer size doesnt seem like having an effect on this dataset. Why would it be?

Thank you very much for your kind help.

**Comment by lh3** [comment]
As I said in #901, this seems a property of your data. In that case, tuning parameters would have little effect. If you want to confirm whether minimap2 is doing the right alignment, you can use Smith-Waterman (e.g. ssearch from the FASTA package) on your small reference and manually compared the results.

Also note that `-axsplice` is for data with introns. Avoid this preset if you don't expect introns in your reference.
