### ISSUE TITLE
Parameters for noisy dRNA ONT

### ISSUE THREAD

**Issue by kaltinel** [lh3/minimap2#903]
Hi,

I appreciate your feedback on the issues of #901 and #902.
As you stated, the issues I raised seem like a property of my data, and I would like to ask for your advice on the matter.

I am ligating two RNA pieces to each other (one without polyA tail and the other one is with polyA). Then, running ONT direct RNA seq with them. However I keep observing that my alignments are ~90% unmapped.
I consider the situation that my reference genome doesn't really represent my biological input due to SNPs and SVs.
Therefore, I made some tests with different parameters of minimap2 and I am confused by the output.

Here I compare the default genomic ont settings (`-ax -map-ont`) to large k-size mappings, to small k-size, and to `MAPQ=0`, and to small penalties for the gaps and mismatches to see what is the best coverage I can get (`-ax map-ont -O 1 -B 1 -E 1 -k 25`).
![mde](https://user-images.githubusercontent.com/47667755/164427368-9507fba2-98b4-4c06-8d8e-551a50f1b999.png)

In this line, I would like to ask:
1) What is the parameter combinations of `-ax -map-ont `(default ont genomic reads) setting?
    1.1) Can I use this parameter for my ~1950nt long 2D dRNA reads?
    1.2) Can I use this parameter for my ~100-5000nt long 2D dRNA reads?
2) How come a read can be Primary and have a `MAPQ=0`?
3) Why would be the reason that I see the gaps in my alignment: some part of the read maps and some doesn't?
  3.1) In this case, for these reads, is the end_point of the alignment the rightest point? (for ex. the gaps are ignored when calculating the width of the read)
4) What would be the parameters you can suggest to us for ambiguous reads for their reference?

I would highly appreciate your help. Thank you.

**Comment by lh3** [comment]
> I keep observing that my alignments are ~90% unmapped.

What are these unmapped sequences? Are they low-quality sequences, or other artifacts? Have you mapped to the whole genome?

**Comment by kaltinel** [comment]
The unmapped reads are the reads having QC < 7.
I am not making to the whole genome, as this experiment is specifically designed for two RNAs to ligate with each other. Therefore my reference is the ligation of two sequences that we expect.

**Comment by lh3** [comment]
This doesn't seem a minimap2 issue. I strongly suggest you map to whole genome. Also check contaminations or adapters.
