### ISSUE TITLE
Unmapped 16S HiFi read

### ISSUE THREAD

**Issue by JeanMainguy** [lh3/minimap2#908]
Hello,

I have some trouble to correctly map some 16S HiFi reads to the silva database made of 16S rRNA genes sequences.

Some of the reads appear unmapped in the minimap2 result while they have very close corresponding sequences in the database.

To get an easy and fast reproducible test of the situation, I picked one read of E.coli that was unmapped and extracted some E.coli sequences from the database:

[ecoli_unmapped_read.fasta.gz](https://github.com/lh3/minimap2/files/8630610/ecoli_unmapped_read.fasta.gz)
[silva_138.1_16S_E_coli_h1.582k.fasta.gz](https://github.com/lh3/minimap2/files/8630611/silva_138.1_16S_E_coli_h1.582k.fasta.gz)

Here is the minimap2 command I used:

`minimap2 -ax map-hifi  silva_138.1_16S_E_coli_h1.582k.fasta.gz ecoli_unmapped_read.fasta.gz | samtools view`

Log and output of the command :
```
[M::mm_idx_gen::0.062*1.05] collected minimizers
[M::mm_idx_gen::0.075*1.21] sorted minimizers
[M::main::0.076*1.21] loaded/built the index for 791 target sequence(s)
[M::mm_mapopt_update::0.076*1.21] mid_occ = 500
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 791
[M::mm_idx_stat::0.076*1.21] distinct minimizers: 2916 (80.18% are singletons); average occurrences: 40.292; average spacing: 10.160; total length: 1193758
[M::worker_pipeline::0.077*1.21] mapped 1 sequences
[M::main] Version: 2.24-r1122
[M::main] CMD: minimap2 -ax map-hifi silva_138.1_16S_E_coli_h1.582k.fasta ecoli_unmapped_read.fasta
[M::main] Real time: 0.079 sec; CPU: 0.095 sec; Peak RSS: 0.007 GB
hifi_read_16S    4    *    0    0    *    *    0    0    GCAGCAGTGGGGAATATTGCACAATGGGCGCAAGCCTGATGCAGCCATGCCGCGTGTATGAAGAAGGCCTTCGGGTTGTAAAGTACTTTCAGCGGGGAGGAAGGGAGTAAAGTTAATACCTTTGCTCATTGACGTTACCCGCAGAAGAAGCACCGGCTAACTCCGTGCCAGCAGCCGCGGTAATACGGAGGGTGCAAGCGTTAATCGGAATTACTGGGCGTAAAGCGCACGCAGGCGGTTTGTTAAGTCAGATGTGAAATCCCCGGGCTCAACCTGGGAACTGCATCTGATACTGGCAAGCTTGAGTCTCGTAGAGGGGGGTAGAATTCCAGGTGTAGCGGTGAAATGCGTAGAGATCTGGAGGAATACCGGTGGCGAAGGCGGCCCCCTGGACGAAGACTGACGCTCAGGTGCGAAAGCGTGGGGAGCAAACAGGATTAGATACCCTGGTAGTCCACGCCGTAAACGATGTCGACTTGGAGGTTGTGCCCTTGAGGCGTGGCTTCCGGAGCTAACGCGTTAAGTCGACCGCCTGGGGAGTACGGCCGCAAGGTTAAAACTCAAATGAATTGACGGGGGCCCGCACAAGCGGTGGAGCATGTGGTTTAATTCGATGCAACGCGAAGAACCTTACCTGGTCTTGACATCCACGGAAGTTTTCAGAGATGAGAATGTGCCTTCGGGAACCGTGAGACAGGTGCTGCATGGCTGTCGTCAGCTCGTGTTGTGAAATGTTGGGTTAAGTCCCGCAACGAGCGCAACCCTTATCCTTTGTTGCCAGCGGTCCGGCCGGGAACTCAAAGGAGACTGCCAGTGATAAACTGGAGGAAGGTGGGGATGACGTCAAGTCATCATGGCCCTTACGACCAGGGCTACACACGTGCTACAATGGCGCATACAAAGAGAAGCGACCTCGCGAGAGCAAGCGGACCTCATAAAGTGCGTCGTAGTCCGGATTGGAGTCTGCAACTCGACTCCATGAAGTCGGAATCGCTAGTAATCGTGGATCAGAATGCCACGGTGAATACGTTCCCGGGCCTTGTACACACCGCCCGTCACACCATGGGAGTGGGTTGCAAAAGAAGTAGGTAGCTTAACCTTCGGGAGGGCGCTTACCACTTTGTGATTCATGACTGGGGTGAAGTCGTAACAAGGTAACT    *    rl:i:1132
```

I noticed that when I decrease the size of the sequence database or when I remove the `map-hifi` profile from the command, I get a correct mapping of the read.

Do you have any idea where the problem comes from?

Thank you very much.
Jean

**Comment by JeanMainguy** [comment]
I suspect the `-U` parameter to be causing the issue as there are many very close sequences in the silva database. The upper bounds of k-mer occurrences  in the map-hifi profile is set to 500 and it is very likely that some kmer appear much more than 500 in silva. 
When I run the following command, the read map correctly to the db:

`minimap2 -ax map-hifi  -U10,1000000 silva_138.1_16S_E_coli_h1.582k.fasta.gz ecoli_unmapped_read.fasta.gz | samtools view`

**Comment by ShannonDaddy** [comment]
I have encounter the similar problem, and I resolved the problem by increasing the value of minimap2 -f option to 10000.
The detail is in the issue https://github.com/lh3/minimap2/issues/897

**Comment by lh3** [comment]
Thanks, @ShannonDaddy.
