### ISSUE TITLE
Reverse complement query

### ISSUE THREAD

**Issue by joshidhaivat** [lh3/minimap2#909]
Hello Heng Li,

I am working on some applications using Minimap2. I wanted to ask if there is a way to read the reverse complement sequence of the query from a separate file in Minimap2 rather than computing it internally. For example, in align.c
https://github.com/lh3/minimap2/blob/e018caea3279a7e663438bfc83480e7dfcaf3099/align.c#L967

`qseq0[0] = (uint8_t*)kmalloc(km, qlen * 2);`
`qseq0[1] = qseq0[0] + qlen;`
`for (i = 0; i < qlen; ++i) {`
`qseq0[0][i] = seq_nt4_table[(uint8_t)qstr[i]];`
`qseq0[1][qlen - 1 - i] = qseq0[0][i] < 4? 3 - qseq0[0][i] : 4;`
`}`

The reverse complement sequence `qseq0[1]` of the query `qseq0[0]` is computed, but instead, it could be read from another file. However, performing a separate alignment using a different query file that contains the reverse complement sequences may not detect inversions using z-drop heuristics.

Please let me know if it is possible to integrate this within the Minimap2 pipeline.

Thank you,
Dhaivat

**Comment by lh3** [comment]
Minimap2 needs to reverse complement the query in many other places, not just in align.c. It will take a lot of effort to achieve your goal.
