### ISSUE TITLE
get different PAF results, using the same data, but without -c parameter.

### ISSUE THREAD

**Issue by Youpu-Chen** [lh3/minimap2#910]
Hi, I am using minimap2 to conduct the assembly-to-assembly alignment. 

I found a interesting point, when I switched off the `-c` parameter.

At the first time I used the command: `minimap2 -cx asm5 24.HIC.genome.fa all_sub.fa > Ped_Dla.paf 2>minimap2.err.log &`

And the second time, I didn't use the `-c` parameter in order to see the original PAF format.
Like this: `minimap2 -x asm5 24.HIC.genome.fa all_sub.fa > test.Ped_Dla.paf 2>test.minimap2.err.log &`

Same data, but the results are differed in size. Ped_Dla.paf is about 4M, test.Ped_Dla.paf is about 50M. And the latter has about 362941 alignments which is way more than the former one, 20641.

The log file of the first command like:
[M::mm_idx_gen::47.045*1.74] collected minimizers
[M::mm_idx_gen::56.956*1.93] sorted minimizers
[M::main::56.956*1.93] loaded/built the index for 24 target sequence(s)
[M::mm_mapopt_update::61.109*1.87] mid_occ = 347
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 24
[M::mm_idx_stat::62.853*1.85] distinct minimizers: 84400923 (81.20% are singletons); average occurrences: 2.015; average spacing: 10.450; total length: 1777276687
[M::worker_pipeline::1164.393*2.41] mapped 11 sequences
[M::worker_pipeline::2151.122*2.54] mapped 14 sequences
[M::worker_pipeline::2943.542*2.62] mapped 10 sequences
[M::main] Version: 2.24-r1122
[M::main] CMD: minimap2 -cx asm5 24.HIC.genome.fa all_sub.fa
[M::main] Real time: 2944.653 sec; CPU: 7721.575 sec; Peak RSS: 12.182 GB

The second one:
[M::mm_idx_gen::46.816*1.63] collected minimizers
[M::mm_idx_gen::56.454*1.84] sorted minimizers
[M::main::56.454*1.84] loaded/built the index for 24 target sequence(s)
[M::mm_mapopt_update::60.877*1.78] mid_occ = 347
[M::mm_idx_stat] kmer size: 19; skip: 19; is_hpc: 0; #seq: 24
[M::mm_idx_stat::63.148*1.75] distinct minimizers: 84400923 (81.20% are singletons); average occurrences: 2.015; average spacing: 10.450; total length: 1777276687
[M::worker_pipeline::453.583*2.44] mapped 11 sequences
[M::worker_pipeline::781.295*2.60] mapped 14 sequences
[M::worker_pipeline::981.865*2.60] mapped 10 sequences
[M::main] Version: 2.24-r1122
[M::main] CMD: minimap2 -x asm5 24.HIC.genome.fa all_sub.fa
[M::main] Real time: 982.760 sec; CPU: 2556.416 sec; Peak RSS: 10.901 GB.

I'll really appreciate if you could give me a hint.
Thanks.

**Comment by lh3** [comment]
See [FAQ](https://github.com/lh3/minimap2/blob/master/FAQ.md).
