### ISSUE TITLE
minimap2.py error permission

### ISSUE THREAD

**Issue by RyotaKurimoto** [lh3/minimap2#912]
I am sequencing with modified nucleic acids by nanopore, and using tombo resquiggle command for alignment, but almost all reads give me "Alignment not produced".
I would like to set k, w, min_dp_score, min_chain_score as parameters to mappy to minimum rather than default to allow for errors. 
How should I set them?
Thank you for attention!

**Comment by lh3** [comment]
See

https://github.com/lh3/minimap2/blob/50a26a60a6586aa8d9ac314ff0502e2b2109549c/python/minimap2.py#L32
