### ISSUE TITLE
Multi-part index (no @SQ lines) with "-I 8g" and a 6.1Gbp index

### ISSUE THREAD

**Issue by thr44pw00d** [lh3/minimap2#913]
Hi,
I ran minimap2 (version 2.18-r1015) on a 6.1 Gbp index using the following command:

`minimap2 -I 8g -t 2 -N 50 -ax sr index.mmi R1.fastq.gz R2.fastq.gz -o out.sam`

With `-I 8g` I expected the index not to be treated as muli-part but I still get the following warning and no @SQ lines are outputted to the sam file.
> [WARNING] For a multi-part index, no @SQ lines will be outputted. Please use --split-prefix.

Did I use `-I` wrongly or should I maybe use the `--split-prefix` option anyway?

Thanks in advance!

Matthias

**Comment by lh3** [comment]
See this in README:

> ***Importantly***, it should be noted that once you build the index, indexing parameters such as -k, -w, -H and -I can't be changed during mapping.

You need to regenerate `index.mmi` with as a large `-I`.
