### ISSUE TITLE
error top hit problem

### ISSUE THREAD

**Issue by ShannonDaddy** [lh3/minimap2#915]
Hi, I found an error top hit problem.

There are two reference sequences in my database.
![image](https://user-images.githubusercontent.com/6656888/169995266-6122b000-d76e-4198-87b6-bd476d849523.png)

when I map the query sequence to the above database, I got the results as follows, but it is not the best hit with the highest score as the AS tag shows，the AS score is 908:
![image](https://user-images.githubusercontent.com/6656888/169995743-a1fde245-2cd5-46be-aa82-9a87b188466c.png)

when I map the query sequence to the expected right reference NC_006684.1 alone，I got higher AS score 926:
![image](https://user-images.githubusercontent.com/6656888/169996591-31cc2010-4f08-47b6-af08-02d192cf7da2.png)

why is that?  I tried both minimap2 2.17-r941 and 2.24-r1122, the results are the same. Please help me, thanks!

my scripts and data files are attached:
[test_minimap2.tar.gz](https://github.com/lh3/minimap2/files/8761313/test_minimap2.tar.gz)

**Comment by lh3** [comment]
This is an expected misalignment. Minimap2 does chaining first and then chooses top {-N}+1 chains to alignment to base resolution. The chaining score of all these chains are 405 at the `s1:i` tag. Minimap2 would randomly choose 6 chains and the best alignment is not among them by chance. You can try a large `-N`, for example
```sh
minimap2 -cx map-ont -N100 target_db.fa S_clean.fastq.gz
```
You will see the correct alignment.

This is an algorithm limitation and a tradeoff between accuracy and speed. No easy workaround.

**Comment by ShannonDaddy** [comment]
> This is an expected misalignment. Minimap2 does chaining first and then chooses top {-N}+1 chains to alignment to base resolution. The chaining score of all these chains are 405 at the `s1:i` tag. Minimap2 would randomly choose 6 chains and the best alignment is not among them by chance. You can try a large `-N`, for example
> 
> ```shell
> minimap2 -cx map-ont -N100 target_db.fa S_clean.fastq.gz
> ```
> 
> You will see the correct alignment.
> 
> This is an algorithm limitation and a tradeoff between accuracy and speed. No easy workaround.

Thanks， it’s very helpful!
