### ISSUE TITLE
Bus Error (core dumped)

### ISSUE THREAD

**Issue by hans-vg** [lh3/minimap2#916]
I am trying to run a genome to genome comparison to view synteny of a denovo assembly vs a reference. I have 256GB on a node, but minimap2 is core dumping.  Any suggestions on how to tune the parameters to get this analysis to complete?

minimap2 -t 8 Sbicolor_454_v3.0.1.fa assembly.fa > assembly_to_Sbicolorv3.default.paf
[M::mm_idx_gen::22.768*1.00] collected minimizers
[M::mm_idx_gen::34.580*1.00] sorted minimizers
[M::main::34.580*1.00] loaded/built the index for 870 target sequence(s)
[M::mm_mapopt_update::35.518*1.00] mid_occ = 851
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 870
[M::mm_idx_stat::35.964*1.00] distinct minimizers: 40422367 (66.89% are singletons); average occurrences: 3.132; average spacing: 5.599; total length: 708863705
Bus error (core dumped)

**Comment by lh3** [comment]
Try the latest version with a proper preset for assembly alignment. The default setting is for read mapping, which wouldn't work well in your case.
