### ISSUE TITLE
-x map-ont preset parameters

### ISSUE THREAD

**Issue by ZainulArifin1** [lh3/minimap2#919]
Hi Li, thanks for the fantastic tool. One question, the parameter -x map-ont is the default parameter but in the manual, it is not mentioned what are the individual parameters that constitute -x map-ont. Could you please clarify this? Thank you.

**Comment by lh3** [comment]
`map-ont` is special. With other options, a second `-x` overwrites the first `-x`. With `map-ont`, a second `-x map-ont` doesn't overwrite the first preset. The current documentation is more accurate technically. I understand this can be confusing, but I think it is a bit late to change the behavior of `-x map-ont` as this may cause incompatible changes. The better solution may be to create another preset for more recent nanopore data.
