### ISSUE TITLE
Assertion failed: (absent), function mm_idx_load, file index.c, line 547

### ISSUE THREAD

**Issue by jflot** [lh3/minimap2#921]
Dear Heng,
When I try to run minimap2 as part of the purge_haplotigs pipeline I get the error message `Assertion failed: (absent), function mm_idx_load, file index.c, line 547`. The command in the pipeline that produces the error is `minimap2 -p 1e-5 -f 0.001 -N 100000 -t 16 tmp_purge_haplotigs/assembly.4G.mmi - 2> tmp_purge_haplotigs/STDERR/minimap2.stderr > tmp_purge_haplotigs/minimap2.4G.paf.tmp` (see https://bitbucket.org/mroachawri/purge_haplotigs/issues/118/assertion-failed-absent-function for more details).
What may be the source of the problem in your opinion?
Thanks a lot in advance for your help.

**Comment by lh3** [comment]
Haven't seen this before. Could you share the "reference" genome/assembly?

**Comment by touala** [comment]
Hello @lh3,

I just got the error mentioned above. Turns out the `.mmi` was broken, likely due to the indexing job early termination (5.3Gb vs 7.1Gb for the proper index). Hope this help in the future.

Alan
