### ISSUE TITLE
use minimap2 to extract mitochondrial reads from genome assembly

### ISSUE THREAD

**Issue by cpavloud** [lh3/minimap2#928]
Hello!

I have a question, although it may not be solely related to minimap.
I have a nanopore sequenced genome and for the same species there is already available a mitogenome (produced by Illumina sequencing). 

I am using minimap2/2.17 to map the already existing mitochondrial reads to my nanopore polished genome assembly. 

`minimap2 -ax map-ont mito.fasta pilon.fasta -t 3 -2 > mito_aligned.sam`

And then I used samtools/1.9 to get the unmapped reads from the bam file, i.e. the genome
`samtools view -b -f 4 mito_aligned.sam -@ 20 > genome.bam`

as well as the mapped reads, i.e. the mitogenome
`samtools view -b -F 4 mito_aligned.sam -@ 20 > mitochondrion.bam`

However, when I convert my `mitochondrion.bam` file to a fasta file and I inspect it, I see that it includes 2 contigs and not one. Also, it is much bigger in size. 
Is this normal? Was everything done properly or is it somekind of error? 
Do you think I should have removed the mitochondrial reads before doing the assembly?

Thank you!

**Comment by lh3** [comment]
The longer one may be [NUMT](https://en.wikipedia.org/wiki/NUMT).
