### ISSUE TITLE
Inversion between tandem repeats yields misalignment

### ISSUE THREAD

**Issue by soisa001** [lh3/minimap2#929]
An inversion (3639 bp) between two tandem repeats (~550 bp each copy) yields an incorrect alignment:
the right breakpoint of the inversion varies between two locations.

The tandem repeats are in the bottom annotation track, flanking the inversion feature annotated.

Note that the left breakpoint is correctly aligned (where the supplementary alignments switch from red to blue or vice versa).
However, the right breakpoint is less clearly delineated: we have the correct breakpoint where the tandem repeat starts (995,352 bp) and the incorrect breakpoint where the tandem repeat ends (995,876 bp). The correct breakpoint is associated with three alignments (forward, reverse, forward or vice versa), whereas the incorrect breakpoint comes with two alignments (where the sequence to the right is clipped off). Is there a way to force it to align correctly (i.e. all three supplementary alignments)?

<img width="1269" alt="image" src="https://user-images.githubusercontent.com/100376518/174886220-241e327a-abfa-467e-ae68-bfbf8954b0e0.png">

**Comment by lh3** [comment]
The alignment is already fairly clean. You can't expect all reads to show the inversion when there is a repeat. Assembly will give you the best result.
