### ISSUE TITLE
Splitting PacBio reads for read overlapping

### ISSUE THREAD

**Issue by mictadlo** [lh3/minimap2#93]
Hi,
Is there a way to split PacBio reads in order to be able to run read overlapping on multiple computer clusters?

At the moment, I am running it as `minimap2 -t 8 -x ava-pb -a reads.fasta reads.fasta > reads.sam` but it is still running since 300 hours.

[Here](https://github.com/Generade-nl/EelSeeds) is a way described but only for Illumina and not for pure PacBio reads.

Thank you in advance.

Michal

**Comment by lh3** [comment]
For huge `reads.fasta`, the general strategy is to split it into smaller files and then map each part against the whole file on each node. Something like:
```sh
split -l 1000000 reads.fasta
minimap2 -t8 -x ava-pb reads.fasta xaa > xaa.paf  # on node 1
minimap2 -t8 -x ava-pb reads.fasta xab > xab.paf  # on node 2
...
```

**Comment by mictadlo** [comment]
How much memory do you think each node will require when the reads.fasta is 100GB big and in how many parts should I split the file?

**Comment by lh3** [comment]
20-30GB, I guess. You can trade between speed and space with option `-I`. A larger value leads to faster performance but increased peak memory.

**Comment by lh3** [comment]
> in how many parts should I split the file?

The optimal choice depends on your cluster configuration. Without knowing details, I would split the original file to a few hundreds pieces.

**Comment by mictadlo** [comment]
Our cluster contains around 6000 nodes  and 20 - 30 GB would be fine for minimap2 to use. This is how many lines the reads.fasta has: 
```
wc -l reads.fasta 
1338537478 reads.fasta
```
What kind of value do you think I should choose for the split command?

**Comment by lh3** [comment]
You could use something like `split -l 13385400` to split them into 100 files.

**Comment by HenrivdGeest** [comment]
> You could use something like split -l 13385400 to split them into 100 

Please do make sure you have your fasta formatted as single line. If not, the split cmd will split your sequences in the middle and you'll get an invalid fasta format. (fasta_formatter -i file.fasta -o fasta_single_line.fasta)

**Comment by lh3** [comment]
Yes, as @HenrivdGeest said. Thanks for the reminder.
