### ISSUE TITLE
ID question

### ISSUE THREAD

**Issue by ericgonzalezs** [lh3/minimap2#930]
Hi,

I am recently using minimap2 and I have a very basic question, I hope you could help me to answer it. I start using the option asm10 and after filtering for MQ >= 60, I calculated ID by dividing column 10 over column 11 from my paf file. When I did that, I was able to find alignments with a very low ID, like 0.3. I thought that asm10 can perform alignments of sequences that have 10% sequence divergence or less. How is possible to have alignments with 70% of differences using asm10? I guess that I am interpreting something wrong.

I used minimap 2 like this:
minimap2 -x asm10 -t 20 ref.fasta.gz query.fa.gz > out.paf

Many thanks,

Eric

**Comment by ericgonzalezs** [comment]
From another post, I found that minimap2 it is not very accurate to calculate cols 10 and 11. So I used minimap with the following options: -c --secondary=no -x asm10 --eqx. Now, I have the tag "de" (Gap-compressed per-base sequence divergence). Does anyone know which is the difference between the tags "de" and "dv"?

**Comment by lh3** [comment]
See [manpage](https://lh3.github.io/minimap2/minimap2.html#10).
