### ISSUE TITLE
Mapping reads against multi references. Any proposition?

### ISSUE THREAD

**Issue by inemp** [lh3/minimap2#931]
Hello, 

I have multiple ONT reads that I would like to align against multiple references.

Is there anything cleverer I could do than use the proposed in the test cases:
minimap2 -ax splice ref.fa nanopore-cdna.fa > aln.sam  
or minimap2 -ax map-ont ref.fa ont-reads.fq > aln.sam 
against every .fa reference file?

**Comment by lh3** [comment]
No other solutions.
