### ISSUE TITLE
Run terminated without error message

### ISSUE THREAD

**Issue by HaenaKwak** [lh3/minimap2#932]
Hello,

I run minimap2, and it just finished in 10 sec with the message "Terminated".

I used following commands :
minimap2 -t 24 -x sr assembly.fa Illumina_PE_1.fq Illumina_PE_2.fq | gzip -c - > ref_align.sam.gz

Do you have any idea about this problem?

Thanks,
Hannah.

**Comment by lh3** [comment]
I don't know. This is probably related to your system. Perhaps your sysadmin will know more.
