### ISSUE TITLE
Chaining Details

### ISSUE THREAD

**Issue by joydddd** [lh3/minimap2#933]
https://github.com/lh3/minimap2/blob/767556b6f0cf7f8cc8096e29a88b0ab520651ff2/lchain.c#L196

I'm working on accelerating minimap2 on GPU. I want to understand the intention of this if statement. I found that this allows current anchor (`i`) to get chained to anchor before `st`. Is this intended behavior?

**Comment by lh3** [comment]
This kicks in when the chaining heuristic is failing. No, it doesn't go beyond st.

**Comment by joydddd** [comment]
Let me paste my observations here:
Because tmp + f[max_ii] > max_f, these anchors got chained to max_ii instead of max_j. However, max_ii < st. 
I'm running on `max_skip = INT32_MAX` btw. 
```
Anchor 122956, max_f 25, max_j 119122, tmp -47, f[max_ii] 10645, max_ii 117708, st 117956
Anchor 123945, max_f 15, max_j -1, tmp -12, f[max_ii] 10645, max_ii 117708, st 118945
Anchor 525155, max_f 15, max_j -1, tmp -6, f[max_ii] 10757, max_ii 519286, st 520155
Anchor 531001, max_f 15, max_j -1, tmp -14, f[max_ii] 10756, max_ii 525209, st 526001
Anchor 701149, max_f 445, max_j 698810, tmp -33, f[max_ii] 6721, max_ii 695128, st 696149
Anchor 862088, max_f 15, max_j -1, tmp -14, f[max_ii] 6376, max_ii 856543, st 857088
Anchor 1052312, max_f 15, max_j -1, tmp 14, f[max_ii] 7034, max_ii 1046834, st 1047312
Anchor 1077380, max_f 15, max_j -1, tmp -32, f[max_ii] 3780, max_ii 1072178, st 1072380
Anchor 1342694, max_f 2641, max_j 1338579, tmp -6, f[max_ii] 2676, max_ii 1337402, st 1337694
Anchor 1709201, max_f 15, max_j -1, tmp -12, f[max_ii] 6407, max_ii 1703798, st 1704201
Anchor 1833880, max_f 8706, max_j 1833033, tmp 13, f[max_ii] 8758, max_ii 1828595, st 1828880
Anchor 1959303, max_f 15, max_j -1, tmp -28, f[max_ii] 8757, max_ii 1954237, st 1954303
Anchor 2134516, max_f 8327, max_j 2133045, tmp 10, f[max_ii] 8342, max_ii 2129206, st 2129516
Anchor 2152754, max_f 9669, max_j 2152209, tmp 5, f[max_ii] 9686, max_ii 2147217, st 2147754
Anchor 122956 score: 10598 predecessor: 117708
Anchor 123945 score: 10633 predecessor: 117708
Anchor 525155 score: 10751 predecessor: 519286
Anchor 531001 score: 10742 predecessor: 525209
Anchor 701149 score: 6688 predecessor: 695128
Anchor 862088 score: 6362 predecessor: 856543
Anchor 1052312 score: 7048 predecessor: 1046834
Anchor 1077380 score: 3748 predecessor: 1072178
Anchor 1342694 score: 2670 predecessor: 1337402
Anchor 1709201 score: 6395 predecessor: 1703798
Anchor 1833880 score: 8771 predecessor: 1828595
Anchor 1959303 score: 8729 predecessor: 1954237
Anchor 2134516 score: 8352 predecessor: 2129206
Anchor 2152754 score: 9691 predecessor: 2147217
```

**Comment by lh3** [comment]
You are right. And this is expected.

**Comment by joydddd** [comment]
Awesome. Thank you so much for making this clear! This can be difficult to implement on GPU, so we'll probably use version 2.18 as the reference instead.

**Comment by joydddd** [comment]
Sorry to disturb you again. 
I want to double confirm that  **`max_ii` tracks peak score within `max_x_dist` on the reference** so that if chaining against all the anchors within `st-i` doesn't yield the best score due to `max_iter` or `max_skip`, we can fall back to chaining to the peak score. 

However in the following code, `max_ii` doesn't always track peak score within `max_x_iter`: it gets updated whenever `max_ii` is too far away on reference but is only updated to peak score within `st-i`. Note that due to `max_iter + st >= i` limitation, peak score within `max_dist_x` might and (especially when chaining to `st-i` doesn't yield the best score)should, come before `st`. 
```
if (max_ii < 0 || a[i].x - a[max_ii].x > (int64_t)max_dist_x) {
			int32_t max = INT32_MIN;
			max_ii = -1;
			for (j = i - 1; j >= st; --j)
			if (max < f[j]) max = f[j], max_ii = j;
	}
```
Instead, if `max_ii` always tracks the peak score within `max_dist_x`:
```
		if (max_ii < 0 || a[i].x - a[max_ii].x > (int64_t)max_dist_x) {
			int32_t max = INT32_MIN;
			max_ii = -1;
			while(j = i - 1; a[j].x + (int64_t)max_dist_x < a[i].x && j>=0; --j)
				if (max < f[j]) max = f[j], max_ii = j;
		}
```
It will cause a little bit more work but hopefully gives better chaining results. When we need this fallback option, it probably means we hit `max_iter` in the first for loop in chaining and we want to try everything within `max_x_dist`.

**Comment by joydddd** [comment]
I realized this old implementation might cause a bug. Anchors with different first 32 bits of x are not supposed to get chained together. Score function would overflow if first 32 bits of x is different. But here `if (max_ii < 0 || a[i].x - a[max_ii].x > (int64_t)max_dist_x) {` the first 32 bits aren't checked, some anchors with different `tid` or `rev` actually gets chained together. 
Updated code:
```
        if (max_ii < 0 ||
            a[i].x << 32 != a[max_ii].x << 32 || a[i].x - a[max_ii].x >
                (int64_t)max_dist_x) {
            int32_t max = INT32_MIN;
			max_ii = -1;
            for (j = i - 1; j >= 0 && a[j].x << 32 == a[i].x << 32 && a[j].x + (int64_t)max_dist_x >= a[i].x ; --j)
                if (max < f[j]) max = f[j], max_ii = j;
        }
```
What's the process I need to go through to get this fix verified?
