### ISSUE TITLE
Non canonical nucleotides

### ISSUE THREAD

**Issue by F0nz0** [lh3/minimap2#936]
Hi, 
I have just a pair of curiosities that I wasn't able to solve reading the minimap2 documentation.
Is there a way to align reads with non-canonical nucleotides? I tryed with a simulated dataset, and I retrieved N where the modified nucleotide was expected. Could this lead to some issues for the aligner or this is not a problem for minimap2 during aligment procedures?

Thank you very much in advance.

**Comment by lh3** [comment]
Please read the paper for details.
