### ISSUE TITLE
Add Read Groups to Multiple Files Using Variable Name

### ISSUE THREAD

**Issue by felixm3** [lh3/minimap2#939]
I have 104 FASTQ files from 52 flow cells.

I would like to run minimap2 on all 104 files and give each a different read group header by using bash variables.

My attempt however is failing.

This is my attempt:

```
flowcell_asic_id=$(echo $1 | awk -F'[/_]' '{print $2}')
echo $flowcell_asic_id
echo ""
fastq_file=$(echo $1 | awk -F'[/_.]' '{print $5"_"$6}')
echo $fastq_file
echo ""


minimap2 \
    -t 28 \
    -R '@RG\tID:$flowcell_asic_id\tDS:$fastq_file\tSM:NA12878-nanopore-wgs' \
    -a \
    ~/tools/hg38/hg38.fa \
    ~/nanopore/rogstrix/$1 | \
    samtools view -uh | \
    samtools sort -o ./bams/$fastq_file.bam
``` 

Unfortunately this results in all my bam outputs having the same identical header:

<img width="1356" alt="image" src="https://user-images.githubusercontent.com/43228120/180281405-823bc44f-a206-4980-8bfc-84f590cc347e.png">

Kindly assist.

Best regards,

Felix

**Comment by lh3** [comment]
> -R '@RG\tID:$flowcell_asic_id\tDS:$fastq_file\tSM:NA12878-nanopore-wgs'

You may replace single quotation mark `'` to double `"`. This is mostly a shell feature.
