### ISSUE TITLE
map-ont specific flag details 

### ISSUE THREAD

**Issue by inemp** [lh3/minimap2#940]
Hello,

based on https://github.com/lh3/minimap2/issues/937 that I asked before, could you inform on what are the specific flags in map-ont?

In the manual I can see:

map-ont | Align noisy long reads of ~10% error rate to a reference genome. This is the default mode.

but for example in hifi they are mentioned in bigger detail:

map-hifi | Align PacBio high-fidelity (HiFi) reads to a reference genome (**-k19 -w19 -U50,500 -g10k -A1 -B4 -O6,26 -E2,1 -s200**).

**Comment by inemp** [comment]
Same as default means this I think: ?

void mm_idxopt_init(mm_idxopt_t *opt)
{
	memset(opt, 0, sizeof(mm_idxopt_t));
	opt->k = 15, opt->w = 10, opt->flag = 0;
	opt->bucket_bits = 14;
	opt->mini_batch_size = 50000000;
	opt->batch_size = 4000000000ULL;
}

**Comment by lh3** [comment]
Both command line instruction and the manpage give you the default values.
