### ISSUE TITLE
what circumstances a sequence does not map a reference

### ISSUE THREAD

**Issue by laingying** [lh3/minimap2#941]
Hi Heng,

I have a question about the mapping detail of minimap2 and would appreciate your help.
Is the reason some reads can't be mapped to the reference because the identity is too low? If so, what is the threshold value for identity?

**Comment by lh3** [comment]
> Is the reason some reads can't be mapped to the reference because the identity is too low?

Yes. Heuristics may be wrong and lead to unmapped reads in very rare cases.

> If so, what is the threshold value for identity?

No. This is implicitly determined by both heuristics (e.g. k-mer size) and the scoring.
