### ISSUE TITLE
Understanding the outputs of paftools

### ISSUE THREAD

**Issue by jidiaz** [lh3/minimap2#943]
Hi developer team, 

I'm trying to understand the main metrics obtained through _paftools.js asmstat_ and _paftools.js asmgene._ I have different measures (such as dup_cnt, dup_sum, full_sql, full_dup)  that i cannot understand and make hard to understand my assembly state. Do you have some documentation that i can read for this situation. Thanks in advance for all your help.

**Comment by lh3** [comment]
* full_sgl: single copy in ref, single copy in contig
* full_dup: single copy in ref, multi copy in contig
* dup_cnt: multi copy in ref, multi copy in conig
* dup_sum: number of copies of multi-copy genes

* l_cov: length of reference covered by alignments
* Rcov: percent reference covered
* Rdup: percent reference covered twice or more (potential duplications)
* Qcov: percent contig covered
