### ISSUE TITLE
[E::sam_parse1] no SQ lines present in the header

### ISSUE THREAD

**Issue by theo-allnutt-bioinformatics** [lh3/minimap2#944]
Hi, I have seen the other closed issues in this topic, but the solution does not work.. I am already putting the reference first and reads second:

minimap2 --secondary=no --sam-hit-only -t 48 -a -x map-hifi assembly.p_ctg.fa hifi.fastq > minimap.sam

Then when I try to convert the output:

samtools view -S -b minimap.sam > minimap.bam
[E::sam_parse1] no SQ lines present in the header
samtools view: error reading file "minimap.sam": No such file or directory

Using latest minimap2 release. The minimap job has 148 GB available and uses 106 GB. I do not get a warning about no headers.

Thanks,

Theo

**Comment by lh3** [comment]
Please see [FAQ](https://github.com/lh3/minimap2/blob/master/FAQ.md#3-the-output-sam-doesnt-have-a-header).
