### ISSUE TITLE
Missing tab in .paf files

### ISSUE THREAD

**Issue by YuliyaLab** [lh3/minimap2#946]
Hi, 
this may not be a big deal but some software requires equal number of tabs to rad in a tab-delimitered file (eg: R).
minimap2 produced a file where a tab was not in the file when a filed was missing. Can that be corrected please? Example below shows that filed labeled s2 is missing in 2 rows, but there is no tab to shift the rest of the columns to their correct place:

26	tp:A:P	cm:i:16	s1:i:163	s2:i:138	dv:f:0.1487	rl:i:30
0	tp:A:S	cm:i:15	s1:i:138	dv:f:0.1520	rl:i:30	
0	tp:A:S	cm:i:14	s1:i:135	dv:f:0.1559	rl:i:30	
32	tp:A:P	cm:i:6	s1:i:60	s2:i:0	dv:f:0.1460	rl:i:0

Thank you

![image](https://user-images.githubusercontent.com/17895876/181864922-060b9ca5-7083-45a2-a311-6b9accc73017.png)

**Comment by lh3** [comment]
PAF is not intended to be parsed this way.
