### ISSUE TITLE
More frequent mapping update messages during early stages?

### ISSUE THREAD

**Issue by Shians** [lh3/minimap2#947]
When mapping with minimap2, if I am interpreting the message correctly, it takes around 10+ minutes before I receive my first report about the mapping speed.

```
[M::worker_pipeline::762.410*2.99] mapped 61793 sequences
```

It also seems the reporting is tied to a specific number of mapped sequences rather than at some time interval. It would be nice to have some feedback about mapping speed within 1-3 minutes of running in order to guesstimate runtime and testing various settings for run optimisation.

What is the current reporting interval based on? And would it be possible to switch to a time based system that reports, for example, once per minute for the first 5 minutes, then once per 10 minutes after that? If it's difficult to switch to a time based system, perhaps cut the read threshold for reporting significantly for the first few reports?

**Comment by lh3** [comment]
> it takes around 10+ minutes before I receive my first report about the mapping speed.

This varies a lot with data.

> What is the current reporting interval based on?

Number of bases processed, controlled by `-K`.

> would it be possible to switch to a time based system that reports

Not possible without rewriting the multi-threading logic.
