### ISSUE TITLE
Wrong soft clipping at the end?

### ISSUE THREAD

**Issue by FrankFeng** [lh3/minimap2#950]
Hi,

Minimap2 is super fast, which is great! Thanks for your work!

I mapped a long sequence to the reference genome and expected to get a 100% match. However, the alignment result includes a very short soft-clipped part at the end, as shown in CIGAR `4S17989M`. Is there any parameter that I can use to make these four soft-clipped bases to map to the reference?

My version of minimap2 is `2.24-r1122` and the command I used is `minimap2 -a $ref $fa > out.sam` . I also tried the `-x asm5` parameter and it didn't work.

Thanks!
Frank

**Comment by lh3** [comment]
Do you have example inputs?

**Comment by FrankFeng** [comment]
Sorry for my late response.

I found out that the soft-clipping was due to the unkonwn ("N") bases in the refernece genome. There is no problem with minimap2.

I will close this issue.
