### ISSUE TITLE
paftools.js call - handling of overlaps and short contigs

### ISSUE THREAD

**Issue by schorlton** [lh3/minimap2#952]
Hi @lh3,

Thanks for minimap2 and its ecosystem. Re: `paftools.js call`, wondering:

1. How is coverage used in calling variants? In a perfect assembly, coverage should be 1, although occasionally there are containments, overlaps, etc. How are overlaps handled...take the base from the first contig aligned?
2. Any suggested alignment lengths for short-read assemblies? What edge cases do these prevent?
```
-l INT    min alignment length to compute coverage [10000]
-L INT    min alignment length to call variants [50000]
```
3. Assuming I can disable secondary alignments based on [this](https://github.com/lh3/minimap2/blob/15cade0f067f669083805e3f9f7115b5d091309f/misc/paftools.js#L454) but please confirm.

Thanks again!

**Comment by lh3** [comment]
1. You should only use regions covered by one contig. See [R-lines](https://github.com/lh3/minimap2/tree/master/misc#calling-variants-from-haploid-assemblies).

2. -l is used for calculate coverage. -L is used for calling variants.

3. Disabling secondary alignments or not will not affect the output.

**Comment by schorlton** [comment]
Thanks. Is it possible to share any more information on:
1. When outputting to VCF, does paftools only output variants in regions covered by one contig? Variants in overlap regions (even if the overlaps are concordant) are ignored?
2. Why not set -l and -L to 1?

**Comment by lh3** [comment]
1. You need to get the non-vcf output. VCF includes everything.
2. Short contigs are error prone.

**Comment by schorlton** [comment]
Thanks. I guess I'm still trying to understand:
1. How does the VCF output of paftools call handle variants in overlaps? Output everything, including contradictory variants from two contigs overlapping the same site?
2. In my experience (no hard data to support), minimap2 is fairly good at aligning contigs >1000bp to bacterial/viral genomes? If `-l 1` then no variants will be called in overlapping regions, even if one of the contigs has length 1 (extreme example). If `-l 2` with the second contig >2bp, then the variant will be called as coverage at the site will only be counted once? If `-L 1`, then all variants are called from non-overlapping 1bp contigs. Accurate?
