### ISSUE TITLE
PAF file: number of residue matches larger than query sequence length

### ISSUE THREAD

**Issue by cimendes** [lh3/minimap2#953]
Greetings,

Thank you for making minimap2! I've a question regarding the [PAF file](https://github.com/lh3/miniasm/blob/master/PAF.md) specification, particularly with columns 2, query sequence length, and 10, number of residue matches. I've observed cases where the latter is larger than the former, and I was wondering if this is a bug, or what cases such is possible.

From my understanding, the number of residue matches should, in theory, be the same as the query sequence length if every base is mapped to the target sequence. 

Thank you for your clarification!

Best,
Inês

**Comment by lh3** [comment]
Could you show an example?

**Comment by cimendes** [comment]
Nevermind, when looking at the example I had on excel the identity (nr residue matches / query size) was always <= 1. So the problem is in my parser of the PAF file. I'll be closing this issue now. Thanks for the reply!
