### ISSUE TITLE
can we trust the alignments with "[WARNING] For a multi-part index, no @SQ lines will be outputted"

### ISSUE THREAD

**Issue by ericgonzalezs** [lh3/minimap2#955]
Hi,

I am not interested in the @SQ lines. I am just wondering if you could please tell me if I can trust the alignments generated with minimap2 if I have the mentioned warning on the title. Thanks.

**Comment by ahcm** [comment]
It usually means that your reference is too large like >4GB as far as I remember.
This easily happens if you downloaded the genomic data that is not meant for general sequence mapping.

**Comment by lh3** [comment]
Oh, I missed this question. Two solutions:

1. Increase `-I` to a large number such as `-I20g`. This is preferred if your machine has enough RAM. Alternatively,
2. Add `--split-prefix=foo`.

BTW, thank you @ahcm for the reply!
