### ISSUE TITLE
Deactivation of Z-drop heuristic

### ISSUE THREAD

**Issue by ChristosMatzoros** [lh3/minimap2#959]
Hello,

Is there any option to deactivate the Z-drop heuristic when aligning with Minimap2?

**Comment by lh3** [comment]
Unfortunately, it is not possible to completely disable the Z-drop heuristic. This is something I also want to improve. If you are doing assembly alignment, you may consider minigraph. Minigraph doesn't have a Z-drop heuristic.

**Comment by ChristosMatzoros** [comment]
Thank you
