### ISSUE TITLE
different -I parameter

### ISSUE THREAD

**Issue by dzaccook** [lh3/minimap2#961]
Hi,
I have a ~20Gb primary hifiasm genome, and I want to use purge_dups to purge the genome. According to the guide in purge_dups, first I need map HiFi reads to the genome.  It has taken ~5 days for mapping one cell HiFi reads (~2000000 reads, 35Gb) to the genome (command: minimap2 -xasm20 -I -t6 asm.bp.p_ctg.fa hifi_reads.fa.gz |gzip -c - >cell1.paf.gz) and still not finished. And now the size of cell1.paf.gz is about 90 Gb.

Referring to https://github.com/lh3/minimap2/issues/813, I change the command of minimap2 to "minimap2 -xasm20 -I20g -t32 -e0 --cap-kalloc=1g -f100 asm.bp.p_ctg.fa hifi_reads.fa.gz |gzip -c - >cell1.paf.gz", and it just takes one hour and the size of cell1.paf.gz is ~2.8Gb. Even more, when I run the command with "minimap2 -xasm20 -I20g -t32  asm.bp.p_ctg.fa hifi_reads.fa.gz |gzip -c - >cell1.paf.gz", it takes seven hours and  the size of cell1.paf.gz is ~2.7Gb.

The size of cell1.paf.gz show large differences between different -I parameter (default vs -I20g). So what causes that and how  do I check it? Can I choose the results of "minimap2 -xasm20 -I20g -t32  asm.bp.p_ctg.fa hifi_reads.fa.gz |gzip -c - >cell1.paf.gz" and  feed to pbcstat? 

Thank you!

**Comment by lh3** [comment]
> `-I -t6`

You have to specify a parameter. Otherwise, this is equivalent to `-I0`. Minimap2 will run on a single thread.
