### ISSUE TITLE
mapping with input file as bam with modified bases information

### ISSUE THREAD

**Issue by AlineMuyle** [lh3/minimap2#964]
Hello,
I was wondering if it is possible to use minimap2 to map reads from a bam file as input, with information on base modifications (methylated cytocines indicated in the ML tag) ?
I have a bam file output by Bonito (ONT data) with DNA methylation inferred, but most reads are unmapped and I would like to map them again without loosing the methylation information.
Is that possible ?
Thank you for your help.
Best wishes,

**Comment by lh3** [comment]
You may use option `-y` to pass fastq comments between input and output:

```sh
samtools fastq -T MQ in.bam | minimap2 -ay ref.fa - | samtools view > out.bam
```
