### ISSUE TITLE
Mapping on GFA ?

### ISSUE THREAD

**Issue by RolandFaure** [lh3/minimap2#965]
Hello, 
Thank you for developing this great tool. I was wondering if there was any plan to adapt minimap2 to map reads directly on GFA graphs (with actual continuous mapping along the edges of the graph, not just mapping on the corresponding fasta). The tools capable of doing that out there are much slower than minimap2.
Many thanks !

**Comment by jelber2** [comment]
I think you are looking for minigraph? https://github.com/lh3/minigraph#sequence-to-graph-mapping

**Comment by RolandFaure** [comment]
Oh, thanks !
