### ISSUE TITLE
Very long reads cause the miniasm fail to assembly

### ISSUE THREAD

**Issue by haotianteng** [lh3/minimap2#97]
Got two very long reads( 105000 ~109999) in the collection, this gives a huge .paf file and cause the miniasm fail to assembly (empty output).

I found this issue in the old minimap repository,  https://github.com/lh3/miniasm/issues/32, and it is solved by passing the -e2 -n1 argument to minimap, however I can't find correspond arguments in Minimap2.

Reads distribution:
--   Read length histogram (one '*' equals 172.88 reads):
--        0   4999  12102 **********************************************************************
--     5000   9999   9900 *********************************************************
--    10000  14999   6807 ***************************************
--    15000  19999   1895 **********
--    20000  24999    366 **
--    25000  29999     75 
--    30000  34999     27 
--    35000  39999     12 
--    40000  44999      5 
--    45000  49999      6 
--    50000  54999      1 
--    55000  59999      0 
--    60000  64999      0 
--    65000  69999      2 
--    70000  74999      3 
--    75000  79999      0 
--    80000  84999      0 
--    85000  89999      0 
--    90000  94999      0 
--    95000  99999      0 
--   100000 104999      0 
--   105000 109999      2

Miniasm Log:
[M::main] ===> Step 1: reading read mappings <===
[M::ma_hit_read::1068.958*0.99] read 106692300 hits; stored 154847124 hits and 26286 sequences (224742008 bp)
[M::main] ===> Step 2: 1-pass (crude) read selection <===
[M::ma_hit_sub::1274.522*0.99] 26020 query sequences remain after sub
[M::ma_hit_cut::1292.693*0.99] 154779534 hits remain after cut
[M::ma_hit_flt::1317.395*0.99] 149689141 hits remain after filtering; crude coverage after filtering: 3632.97
[M::main] ===> Step 3: 2-pass (fine) read selection <===
[M::ma_hit_sub::1413.890*0.99] 25954 query sequences remain after sub
[M::ma_hit_cut::1432.122*0.99] 149597578 hits remain after cut
[M::ma_hit_contained::1460.549*0.99] 188 sequences and 5314 hits remain after containment removal
[M::main] ===> Step 4: graph cleaning <===
[M::ma_sg_gen] read 1926 arcs
[M::main] ===> Step 4.1: transitive reduction <===
[M::asg_arc_del_trans] transitively reduced 656 arcs
[M::asg_arc_del_multi] removed 0 multi-arcs
[M::asg_arc_del_asymm] removed 16 asymmetric arcs
[M::main] ===> Step 4.2: initial tip cutting and bubble popping <===
[M::asg_cut_tip] cut 111 tips
[M::asg_pop_bubble] popped 0 bubbles and trimmed 0 tips
[M::main] ===> Step 4.3: cutting short overlaps (3 rounds in total) <===
[M::asg_arc_del_multi] removed 0 multi-arcs
[M::asg_arc_del_asymm] removed 11 asymmetric arcs
[M::asg_arc_del_short] removed 13 short overlaps
[M::asg_cut_tip] cut 15 tips
[M::asg_pop_bubble] popped 1 bubbles and trimmed 1 tips
[M::asg_arc_del_short] removed 0 short overlaps
[M::asg_arc_del_short] removed 0 short overlaps
[M::main] ===> Step 4.4: removing short internal sequences and bi-loops <===
[M::asg_cut_internal] cut 0 internal sequences
[M::asg_cut_biloop] cut 0 small bi-loops
[M::asg_cut_tip] cut 1 tips
[M::asg_pop_bubble] popped 0 bubbles and trimmed 0 tips
[M::main] ===> Step 4.5: aggressively cutting short overlaps <===
[M::asg_arc_del_short] removed 0 short overlaps
[M::main] ===> Step 5: generating unitigs <===
[M::main] Version: 0.2-r168-dirty
[M::main] CMD: miniasm -f merge_0.fastq reads_0.paf
[M::main] Real time: 1473.948 sec; CPU: 1458.873 sec

**Comment by lh3** [comment]
`-e2 -n1` are miniasm options, not minimap.

**Comment by haotianteng** [comment]
Oh sorry, but still got size 0 .gaf output.

[M::main] ===> Step 1: reading read mappings <===
[M::ma_hit_read::11.475*0.99] read 0 hits; stored 0 hits and 0 sequences (0 bp)
[M::main] ===> Step 2: 1-pass (crude) read selection <===
[M::ma_hit_sub::11.476*0.99] 0 query sequences remain after sub
[M::ma_hit_cut::11.476*0.99] 0 hits remain after cut
[M::ma_hit_flt::11.476*0.99] 0 hits remain after filtering; crude coverage after filtering: -nan
[M::main] ===> Step 3: 2-pass (fine) read selection <===
[M::ma_hit_sub::11.476*0.99] 0 query sequences remain after sub
[M::ma_hit_cut::11.476*0.99] 0 hits remain after cut
[M::ma_hit_contained::11.476*0.99] 0 sequences and 0 hits remain after containment removal
[M::main] ===> Step 4: graph cleaning <===
[M::ma_sg_gen] read 0 arcs
[M::main] ===> Step 4.1: transitive reduction <===
[M::asg_arc_del_trans] transitively reduced 0 arcs
[M::main] ===> Step 4.2: initial tip cutting and bubble popping <===
[M::asg_cut_tip] cut 0 tips
[M::asg_arc_del_multi] removed 0 multi-arcs
[M::asg_arc_del_asymm] removed 0 asymmetric arcs
[M::asg_pop_bubble] popped 0 bubbles and trimmed 0 tips
[M::main] ===> Step 4.3: cutting short overlaps (1 rounds in total) <===
[M::asg_arc_del_short] removed 0 short overlaps
[M::main] ===> Step 4.4: removing short internal sequences and bi-loops <===
[M::asg_cut_internal] cut 0 internal sequences
[M::asg_cut_biloop] cut 0 small bi-loops
[M::asg_cut_tip] cut 0 tips
[M::asg_pop_bubble] popped 0 bubbles and trimmed 0 tips
[M::main] ===> Step 4.5: aggressively cutting short overlaps <===
[M::asg_arc_del_short] removed 0 short overlaps
[M::main] ===> Step 5: generating unitigs <===
[M::main] Version: 0.2-r168-dirty
[M::main] CMD: miniasm -f -e2 -n1 merge_0.fastq reads_0.paf
[M::main] Real time: 11.479 sec; CPU: 11.391 sec

**Comment by lh3** [comment]
This is not a minimap2 issue then. By the way, you command line is wrong. It should be
```
miniasm -e2 -n1 -f merge_0.fastq reads_0.paf
```

**Comment by lh3** [comment]
You can still reply here if you have further questions, but those will be miniasm questions. I am closing the issue for now.

**Comment by haotianteng** [comment]
Okay, I will open a Miniasm issue if there is further problem. Thanks

**Comment by haotianteng** [comment]
Problem solved. Thank you for the quick response!
