### ISSUE TITLE
feat: zstd support

### ISSUE THREAD

**Issue by j23414** [lh3/minimap2#972]
I see that minimap2 accepts gunzip files:

```
./minimap2 -ax map-pb ref.fa pacbio.fq.gz > aln.sam  
```

Wondered if there were any plans to support `zstd` compressed files?

```
./minimap2 -ax map-pb ref.fa pacbio.fq.xz > aln.sam  
```

Sorry if this is already a feature and I missed it somehow. For a different project, zstd compression benchmarks seemed very fast.

> zstd can 4-10x faster in decompressing sequences than xz with equal compression ratios.

from https://github.com/nextstrain/ncov-ingest/issues/341

Just checking, no pressure, I didn't find an answer with a quick search through issues.

**Comment by corneliusroemer** [comment]
Especially for sequence alignment files like for SARS-CoV-2 or monkeypox, where there are thousands of similar sequences with lengths >20kB, zstd is extremely good at compressing these data.

It's as good as `xz` for compression ratios but much faster at compressing and uncompressing.

@j23414 I think you may have mistyped in your second example. I see you have a `pacbio.fq.xz` file there but may have meant `pacbio.fq.zst`?

**Comment by lh3** [comment]
Please use unix pipes:
```sh
xz -dc reads.fq.xz | minimap2 -ax map-pb ref.fa - > aln.sam
```

**Comment by j23414** [comment]
ah got it, thanks:

```
zstd -d -c reads.fq.zst | minimap2 -ax map-pb ref.fa - > aln.sam
```
