### ISSUE TITLE
Unaligned BAM as input

### ISSUE THREAD

**Issue by timp0** [lh3/minimap2#977]
Newer long-read methylation callers are leveraging the MM/ML tags in bam to write modification directly from the sequencer, but this typically happens in an unaligned bam file.

To then subsequently align the data with minimap, we use a command like this:

`samtools fastq -TMM,ML ${SAMPLE_NAME} | \
minimap2 -k17 -ax map-ont -y ${reference} - | \
samtools view -Sb - | samtools sort - > ${SAMPLE_NAME}.mod.bam`

Is there a possibility or is it on the roadmap to instead take as input a bam file and retain the tags during alignment?

**Comment by lh3** [comment]
Hi Winston, do you have particular issues with the `samtools fastq -T | minimap2` piping? Native support of uBAM in minimap2 would only reduce this pipe to a single command line with no performance improvement. However, implementing this feature would bring a heavy htslib dependency, which is larger and more difficult to compile than minimap2. Unless there is a huge practical advantage, I would be cautious of adding the native uBAM support.

**Comment by timp0** [comment]
I think my issue was to make this more streamlined - if the standard output from (for example) guppy is going to be an unaligned bam - and pacbio has been using bam outputs IIRC for some time (see also this (https://github.com/pacificbiosciences/pbmm2/) - I just thought it might make sense to build native support into minimap2 for it.

Your point about dependencies is completely fair - but to be honest I find it hard to imagine a scenario where I'm using minimap2 but not . . . piping it into samtools anyway, so I had to compile that (or I guess grab a binary) to be able to work.

**Comment by rhpvorderman** [comment]
> Unless there is a huge practical advantage, I would be cautious of adding the native uBAM support.

There are practical advantages:

- Provenance. Using the PG header entry it is possible to see what has happened with the data up to this point. `samtools fastq` erases that information. 
- RG tags are already present in uBAM files provided by dorado. No RG tag needs to be provided to minimap and the original readgroup information even after merging multiple uBAMs persists. 

I work with bioinformatics data in a medical environment and the provenance matters there. 

 > However, implementing this feature would bring a heavy htslib dependency, which is larger and more difficult to compile than minimap2.
 
 Well htslib has a lot of functionality not needed for minimap2. It is not that difficult to parse a BAM stream. Simply treat it as an ordinary gzip stream, skip/read the header as is and start parsing the records. The name and qualities can simply be copied and the sequence decoding requires copying one function from htslib. Tag support is a bit of work, but nothing extraordinarily diifficult. 
 
 I have written two uBAM parsers now for [sequali](https://github.com/rhpvorderman/sequali) and [dnaio](https://github.com/marcelm/dnaio) without the need for any htslib. (In fact I found a way to speed up the sequence decoding that I contributed upstream to htslib again, where it was further refined). 
 
 So I personally feel the tradeoff is not "a heavy dependency for virtually no gain" but "a moderate amount of work for better provenance". I hereby volunteer to do the moderate amount of work.

**Comment by lh3** [comment]
I implemented the bam parser in htslib. I know what it takes to read a bam. In fact, bwa-aln has a [light-weight bam parser](https://github.com/lh3/bwa/blob/master/bamlite.c) to read sequences (not tags) but I later think it is inflexible and not worth the effort, so bwa-mem doesn't have the bam support. I still hold the same view.

Thanks for offering the bam support. However, maintenance falls on me. The long-term effort is not trivial for hundreds of lines of contributed code.

**Comment by rhpvorderman** [comment]
Thank you for your quick response.

> I implemented the bam parser in htslib. I know what it takes to read a bam. 

I hope I didn't come across as implying you did not! That was not my intention at all. I know it is a non-trivial amount of work to write a BAM parser without relying on htslib and that is also why I offered to write it myself rather than just request support.

> The long-term effort is not trivial for hundreds of lines of contributed code.

I indeed see how further changes to the BAM specification and minimap2 could indeed make this a lot of maintenance down the road. Given the comparatively small advantages I can see how that is not worth it for minimap2. Thank you for your further clarification on this.

**Comment by lh3** [comment]
Ewan Birney also asked me if uBAM could be supported. Nonetheless, I have my preference on the scope of a project, which, I recognize, may be different from others' preferences. Thank you and Tim for your understanding.

**Comment by jmarshall** [comment]
While a simple standalone BAM reader is an easy addition and I too wrote one for velvet many years ago, the same user convenience arguments would support adding unaligned CRAM reading as well — which is a much less feasible or supportable addition. So if minimap2 quite reasonably requires a format conversion to read from uCRAM, it's not much additional hardship to require one to read from uBAM as well.

OTOH IMHO @rhpvorderman has a good point about simplifying transmitting the provenance information in `@PG` and `@RG` headers. So there would be something to be said for accepting uSAM as an alternative to FASTQ.

**Comment by rhpvorderman** [comment]
In terms of scope I don't think there is that much of a difference between uBAM and uSAM to be honest. Most of the needed code in minimap2 would be handling existing header and tag information. Currently minimap2 can happily pretend that does not exist, which keeps the code much simpler. Using htslib won't change this. 

I'd prefer if all tools in the chain supported SAM/BAM to keep the provenance information, but it is going to be some effort to get there.

**Comment by jmarshall** [comment]
@rhpvorderman: You have missed my point: If uBAM were supported, users would expect uCRAM to be supported too. There certainly is an implementation difference for the latter, which is not possible without a complex implementation and/or multiple new dependencies.

**Comment by rhpvorderman** [comment]
The nanopore base caller does output BAM format by default (because tags are a standardized way to save methylation information) and minimap2 is the go-to nanopore base caller. This is the primary reason that BAM support is requested. 

Why would users expect uCRAM? CRAM compresses well because it uses reference information. This information is absent when the reads are not aligned. Are there aligners that output uCRAM format? I don't know of any, though that could be my lack of knowledge. I am a bit puzzled why uCRAM would be a thing that aligners and QC tools would use as output. Could you elaborate on this?
