### ISSUE TITLE
Bug: strand selection logic in collect_seed_hits

### ISSUE THREAD

**Issue by kaiiiz** [lh3/minimap2#978]
I'm currently reading minimizer2 source code, and I find a possible bug in `collect_seed_hits` and `collect_seed_hits_heap`.

If I understand correctly, the `const mm128_v *mv` argument in `collect_seed_hits` is a list of query minimizers' information.

`*mv` is passed to `mm_collect_matches` to collect the minimizer hits stored in the reference index, then the seed locations are stored in `m->cr` (`m` is `mm_seed_t`).

https://github.com/lh3/minimap2/blob/b0b199f5039e8da5e8d1a9a7ae130580fd33fe1f/seed.c#L98-L105

https://github.com/lh3/minimap2/blob/b0b199f5039e8da5e8d1a9a7ae130580fd33fe1f/seed.c#L30-L45

Minimizer information includes `query id`, `offset`, and `strand`. The last bit of minimizer information is used to store the forward/reverse strand information. The same information is stored in seed location information.

https://github.com/lh3/minimap2/blob/b0b199f5039e8da5e8d1a9a7ae130580fd33fe1f/sketch.c#L109-L114

The weird code I found is the following:

https://github.com/lh3/minimap2/blob/b0b199f5039e8da5e8d1a9a7ae130580fd33fe1f/map.c#L190-L200

The comment says that if `(r[k]&1) == (q->q_pos&1)` then it's forward strand case. However, if `r[k]&1 == 1` (reverse reference hit) and `q->q_pos&1 == 1` (reverse query minimizer), `(r[k]&1) == (q->q_pos&1)` is also evaluated as true. Should it be modified to `(r[k]&1 == 0) && (q->q_pos&1 == 0)`? or am I misunderstanding something?

BTW. The same code also appears in `collect_seed_hits_heap`.

**Comment by kaiiiz** [comment]
I think I understand the code. It's not a bug, `(r[k]&1) == (q->q_pos&1)` means that the reference hit and the query minimizer are on the same strand. If this is not the case, one of the minimizers requires flipping.

Maybe the comment should revise to `same strand` and `different strand` to prevent misunderstanding, just like the pseudo-code of algorithm 4 provided in "Minimap and miniasm: fast mapping and de novo assembly for noisy long sequences".

**Comment by lh3** [comment]
The code tests the same strand. It would be redundant to add a comment for that. The current comment goes a step further and points out that same strand == anchor on the forward strand.
