### ISSUE TITLE
-p 参数疑问？

### ISSUE THREAD

**Issue by liushuqing506** [lh3/minimap2#984]
请问
-p参数变化后，同一个query比对同一个ref，CIGAR表达式一样，但是MAPQ值不一样，是为什么？
After -p parameter changes, the same query matches the same ref and CIGAR expressions, but the MAPQ values are different. Why?
![image](https://user-images.githubusercontent.com/32661587/201609416-0bfa1f93-9058-4c98-873d-ee773327cd6c.png)

**Comment by lh3** [comment]
MapQ is calculated from potential alignments and lower -p may reveal more alignments.

**Comment by liushuqing506** [comment]
thanks
