### ISSUE TITLE
Problem with output .bam files 

### ISSUE THREAD

**Issue by AnaUnix** [lh3/minimap2#985]
Hello,
I'm trying to see concrete regions on my genome and see the coverage in some points.
So first I mapped the PacBio long-reads (57 Gb) to the whole genome assembly (3.1 Gb) ussing this command:

trg=genome.fasta
qry=PBreads.fastq.gz
minimap2 -ax map-pb $trg $qry -t 20 > minimap.sam

After convert .sam to .bam I got output file minimap.bam (99 Gb).
Then I tried to map the PacBio long reads just to the concrete regions of the genome to obtain an output file less heavy and more workable. So my new target genome_regions.fasta file is now 3.2 Mb. and I used the same command:

trg=genome_regions.fasta
qry=PBreads.fastq.gz
minimap2 -ax map-pb $trg $qry -t 20 > minimap.sam

But I got an output .bam file of 78 Gb. Why is this happening? Why using target files so different in size, do I get such heavy output files??

Thanks in advance

**Comment by lh3** [comment]
If your region include repeats, you will get most reads mapped. Generally, extract from whole-genome bam; don't map to local regions.
