### ISSUE TITLE
bwameth_index

### ISSUE THREAD

**Issue by antoine4ucsd** [lh3/minimap2#987]
Hello
I am trying to run my first analyses with the WGBS workflow
(I was able to analyze these samples with methyldackel)
I have my fastq.gz files in the input directory
my reference genome is in the ref directory for which bwa-meth index has been built already. 
I tried to adapt the yaml file but I think I am missing soemthing for the genome info. 
I get this error:

```
WGBS -i ./20221118/ -o ./_out  defaults1.yaml 

---- This analysis has been done using snakePipes version 2.6.1 ----
NameError in line 33 of /Users/mypath/opt/miniconda3/envs/snakePipes/lib/python3.10/site-packages/snakePipes/shared/rules/WGBS.snakefile:
name 'bwameth_index' is not defined
  File "/Users/mypath/opt/miniconda3/envs/snakePipes/lib/python3.10/site-packages/snakePipes/workflows/WGBS/Snakefile", line 140, in <module>
  File "/Users/mypath/opt/miniconda3/envs/snakePipes/lib/python3.10/site-packages/snakePipes/shared/rules/WGBS.snakefile", line 33, in <module>
Error: snakemake returned an error code of 1, so processing is incomplete!


```
I am attaching my edited yaml
thank you for your advices!
[defaults1.yaml.txt](https://github.com/lh3/minimap2/files/10047561/defaults1.yaml.txt)

**Comment by lh3** [comment]
Perhaps you should ask the bwa-meth developer.
