### ISSUE TITLE
incorrect junction mapping in minimap2 v2.7 that was correct in earlier version v.2.1.1

### ISSUE THREAD

**Issue by Magdoll** [lh3/minimap2#99]
Three particular cases of the Lexogen SIRV synthetic RNA spike in (ground truth, so every mapping junction has the correct answer) have different - and now incorrect - mapped junctions after switching from an older version of minimap2 (v.2.1.1) to the newest one (v.2.7).

The three sequences are here: https://www.dropbox.com/s/l5mue20tnavvwf6/missing_in_new.fa?dl=0

They should belong to SIRV304, SIRV403, and SIRV408, respectively. Based on BLASR mapping back to the reference transcript [blasr file](https://www.dropbox.com/s/kpa4ny2s5nw8uy8/missing_in_new.fa.blasr?dl=0), the accuracy for the three sequences are 98% (12 ins 1 del), 99% (1 insertion), and 100%. The errors are actually of no consequence here, because even when I take SIRV304, SIRV403, and SIRV408 ([fasta file here](https://www.dropbox.com/s/bl2jsn9xu4wlj95/test.fa?dl=0)) with no error, they still map incorrectly. In comparison, GMAP and an earlier version of minimap2 (v2.1.1.) both mapped the sequences correctly, so this seems to be a case of algorithmic differences.

Below I show the junction differences between the old minimap2 (which are the correct answers) vs the new minimap2. 

**For SIRV304**, the 5th and 6th exon have a different junction, shifted by 4 and 11 bp respectively.

(in old, is correct)
```
SIRV3   PacBio  transcript  1965    8935    .   +   .   gene_id "PB.5"; transcript_id "PB.5.5";
SIRV3   PacBio  exon    1965    2005    .   +   .   gene_id "PB.5"; transcript_id "PB.5.5";
SIRV3   PacBio  exon    4004    4080    .   +   .   gene_id "PB.5"; transcript_id "PB.5.5";
SIRV3   PacBio  exon    4569    4779    .   +   .   gene_id "PB.5"; transcript_id "PB.5.5";
SIRV3   PacBio  exon    6058    6333    .   +   .   gene_id "PB.5"; transcript_id "PB.5.5";
SIRV3   PacBio  exon    7271    7366    .   +   .   gene_id "PB.5"; transcript_id "PB.5.5";
SIRV3   PacBio  exon    7873    7988    .   +   .   gene_id "PB.5"; transcript_id "PB.5.5";
SIRV3   PacBio  exon    8125    8207    .   +   .   gene_id "PB.5"; transcript_id "PB.5.5";
SIRV3   PacBio  exon    8756    8935    .   +   .   gene_id "PB.5"; transcript_id "PB.5.5";
```

(in new, and is wrong)

```
SIRV3   PacBio  transcript  1965    8935    .   +   .   gene_id "PB.5"; transcript_id "PB.5.6";
SIRV3   PacBio  exon    1965    2005    .   +   .   gene_id "PB.5"; transcript_id "PB.5.6";
SIRV3   PacBio  exon    4004    4080    .   +   .   gene_id "PB.5"; transcript_id "PB.5.6";
SIRV3   PacBio  exon    4569    4779    .   +   .   gene_id "PB.5"; transcript_id "PB.5.6";
SIRV3   PacBio  exon    6058    6333    .   +   .   gene_id "PB.5"; transcript_id "PB.5.6";
SIRV3   PacBio  exon    7271    7362    .   +   .   gene_id "PB.5"; transcript_id "PB.5.6";
SIRV3   PacBio  exon    7862    7988    .   +   .   gene_id "PB.5"; transcript_id "PB.5.6";
SIRV3   PacBio  exon    8125    8207    .   +   .   gene_id "PB.5"; transcript_id "PB.5.6";
SIRV3   PacBio  exon    8756    8935    .   +   .   gene_id "PB.5"; transcript_id "PB.5.6";
```

For **SIRV403**, the 3rd and 4th junction are different and shifted by 6 bp.

(in old, is correct)
```
SIRV4   PacBio  transcript  8324    15121   .   -   .   gene_id "PB.9"; transcript_id "PB.9.1";
SIRV4   PacBio  exon    8324    8372    .   -   .   gene_id "PB.9"; transcript_id "PB.9.1";
SIRV4   PacBio  exon    8630    8990    .   -   .   gene_id "PB.9"; transcript_id "PB.9.1";
SIRV4   PacBio  exon    13673   13828   .   -   .   gene_id "PB.9"; transcript_id "PB.9.1";
SIRV4   PacBio  exon    15020   15121   .   -   .   gene_id "PB.9"; transcript_id "PB.9.1";
```

(in new, and is wrong)
```
SIRV4   PacBio  transcript  8324    15121   .   -   .   gene_id "PB.9"; transcript_id "PB.9.1";
SIRV4   PacBio  exon    8324    8372    .   -   .   gene_id "PB.9"; transcript_id "PB.9.1";
SIRV4   PacBio  exon    8630    8990    .   -   .   gene_id "PB.9"; transcript_id "PB.9.1";
SIRV4   PacBio  exon    13673   13822   .   -   .   gene_id "PB.9"; transcript_id "PB.9.1";
SIRV4   PacBio  exon    15014   15121   .   -   .   gene_id "PB.9"; transcript_id "PB.9.1";
```

For **SIRV408**, it is actually the same junction that had the same junction difference. SIRV408 shares the same exons as SIRV403, it just has one more exon.

(in old is correct)
```
SIRV4   PacBio  transcript  8326    15121   .   -   .   gene_id "PB.9"; transcript_id "PB.9.3";
SIRV4   PacBio  exon    8326    8372    .   -   .   gene_id "PB.9"; transcript_id "PB.9.3";
SIRV4   PacBio  exon    8630    8747    .   -   .   gene_id "PB.9"; transcript_id "PB.9.3";
SIRV4   PacBio  exon    8847    8990    .   -   .   gene_id "PB.9"; transcript_id "PB.9.3";
SIRV4   PacBio  exon    13673   13828   .   -   .   gene_id "PB.9"; transcript_id "PB.9.3";
SIRV4   PacBio  exon    15020   15121   .   -   .   gene_id "PB.9"; transcript_id "PB.9.3";
```
(in new and is wrong)
```
SIRV4   PacBio  transcript  8326    15121   .   -   .   gene_id "PB.9"; transcript_id "PB.9.3";
SIRV4   PacBio  exon    8326    8372    .   -   .   gene_id "PB.9"; transcript_id "PB.9.3";
SIRV4   PacBio  exon    8630    8747    .   -   .   gene_id "PB.9"; transcript_id "PB.9.3";
SIRV4   PacBio  exon    8847    8990    .   -   .   gene_id "PB.9"; transcript_id "PB.9.3";
SIRV4   PacBio  exon    13673   13822   .   -   .   gene_id "PB.9"; transcript_id "PB.9.3";
SIRV4   PacBio  exon    15014   15121   .   -   .   gene_id "PB.9"; transcript_id "PB.9.3";
```

All files may be found here: 
https://www.dropbox.com/sh/ne8afaw28o5uwr0/AAAZy2EhNqOkphJO7VmPEwK0a?dl=0

[SIRV genome fasta](https://www.dropbox.com/s/8kzcezmy0se8nno/SIRV_150601a.genome.fasta?dl=0)

[SIRV annotation  GFF](https://www.dropbox.com/s/pxk6rv0fizcwtu0/SIRV_C_150601a.transcript.truth.gff?dl=0)

[SIRV transcript fasta](https://www.dropbox.com/s/87sl2wi122m2e3u/SIRV_C_150601a.transcript.truth.fasta?dl=0)

**Comment by lh3** [comment]
This is a known complication. See the last paragraph in [this section](https://github.com/lh3/minimap2#map-long-splice) for details. The culprit is human/mouse/yeast use slightly different donor/acceptor motifs from SIRV. The default minimap2 setting is tuned for real biological data but it becomes worse for SIRV. To achieve higher accuracy on SIRV, you should use
```sh
minimap2 -ax splice --splice-flank=no --secondary=no
```
This reverts to the minmap2-2.1.1 behavior.

**Comment by Magdoll** [comment]
@lh3 would you recommend in general just always using `--splice-flank=no`? Or only for non-mammalian species? For example, virus, bacteria, and plants may use very different junctions than the well-annotated human/mouse/yeast.

**Comment by lh3** [comment]
S. cerevisiae and human [use similar signals](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2483917/figure/pgen-1000148-g001/). The evolution distance between the two species is huge. I don't know about plants, though, and even less about bacteria. Perhaps you may use `--splice-flank=yes` (the default with -xsplice) for metazoan and yeast and `--splice-flank=no` for others before I find a definitive answer in the literature. Personally, I find `--splice-flank=yes` helps human/mouse data, in particular for reads with relatively high sequencing error rate.

**Comment by lh3** [comment]
If you still worry about the bias, it should be ok to always apply `--splice-flank=no`. For high-quality iso-seq reads, having this option or not usually does not make much difference.

**Comment by Magdoll** [comment]
In general we would only be using minimap2 to map higher quality (99-100%) IsoSeq data, so I'll stick with `--splice-flank=no`. 

FYI, I ran `--splice-flank=no` on the three SIRVs and the answer remains the same. The [new sam file is here](https://www.dropbox.com/s/rvkbafn8s12lni6/test.fa.minimap.splice_flank_no.sam?dl=0)


--Liz

**Comment by lh3** [comment]
Thanks a lot for all these test cases. Extremely helpful. v2.7 applies a higher penalty on non-canonical splicing sites than v2.1.1 (i.e. v2.7 is more likely to choose canonical sites). Each of the three transcripts you show has one non-canonical splicing site: SIRV304 has an AT-AC intron and SIRV403/SIRV408 has an AA-AG intron. v2.7 is trying to find GT-AG around the three introns by introducing mismatches.

To align these three transcripts correctly, you need to reduce option `-C` (v2.1.1 uses 5):
```sh
minimap2 -ax splice --splice-flank=no --secondary=no -C5
```
Again, for high-quality data, it is usually preferred to use a small -C. The default of v2.7 is over-tuned for low-quality data.

**Comment by Magdoll** [comment]
Thanks for the help! I can confirm that with `--splice-flank=no --secondary=no -C5` I have now achieved the same SIRV mapping results as before.

I understand this is an edge case, but we use SIRV in all our in-house IsoSeq experiments and use it for validation, so it is great that we can use minimap2 and recover all the SIRVs correctly.

--Liz

**Comment by lh3** [comment]
@Magdoll just wonder if you have tried minimap2 more on isoseq data. If you think `--splice-flank=no --secondary=no -C5` works better for isoseq, I will create a `splice:isoseq` preset such that users don't need to type these many characters any more. Thanks!

**Comment by lh3** [comment]
Also, do you have a tiny iso-seq dataset against SIRV? I am thinking to provide some examples for users to try isoseq mapping. Thanks in advance!

**Comment by Magdoll** [comment]
@lh3 yes I have been using minimap2 to do most of the work but since many of my other datasets are non-human and don't contain SIRV, I use `--secondary=0` but drop `--splice-flank=no -C5` which are parameters more tuned for SIRV itself. 

tiny SIRV dataset --- I have one that is RC0 (human UHRR + SIRV), let me do some extractions so it's easier to compare just SIRV and just human without mixing the two.

**Comment by Magdoll** [comment]
Here is a tiny SIRV dataset: https://www.dropbox.com/sh/5w0go31cj7341mm/AADZCWhng1nAyxc7bDg-Q-DEa?dl=0

**Comment by lh3** [comment]
Thank you very much, @Magdoll. I have just downloaded the two datasets. Thanks!
