### ISSUE TITLE
Too many mappings?

### ISSUE THREAD

**Issue by ahcm** [lh3/minimap2#991]
Dear Heng,

mapping a whole genome nanopore sequencing to a short sequence, we are interested in leads to way more mappings than expected.
Compared to more "sane" numbers in winnowmap.

Example:
winnowmap-map-ont-no2nd.mapped.bam.sorted.bam.idxstats
1:CFAP126-201   6947    30535   0
2:FLTP-Venus_loxP       3966    11      0
3:*     0       0       0

minimap2-git-map-ont-no2nd.mapped.bam.sorted.bam.idxstats
1:CFAP126-201   6947    511908  0
2:FLTP-Venus_loxP       3966    85      0
3:*     0       0       0

minimap2-2.21-map-ont-no2nd.mapped.bam.sorted.bam.idxstats
1:CFAP126-201   6947    511908  0
2:FLTP-Venus_loxP       3966    85      0
3:*     0       0       0

Thanks!
Andreas

**Comment by lh3** [comment]
The number of mappings are dominated by filtering. They are not informative in such a use case anyway.
