### ISSUE TITLE
Multiple identical matches yields no hits

### ISSUE THREAD

**Issue by HansLorenz** [lh3/minimap2#992]
Hi Heng, thanks for this amazing tool. 

When a read maps equally well to two different sites, nothing is returned. We would like to know whether it maps anywhere, including if there is a tandem dimer, or if there are two locations on different chromosomes. Our workflow prevents us from just masking the repeat, and we currently run minimap2 multiple times with progressively longer repeats.

Is there any way to learn whether reads map in this case? 

Thanks for your help!

**Comment by lh3** [comment]
That may happen if there are too many hits, but minimap2 is not designed for that application. You may use `-f10000` to get more more seeds, but that can be very slow depending on data.

**Comment by mwbudde** [comment]
Thanks.
