### ISSUE TITLE
Whether the two genomes can be indexed and then alignment.

### ISSUE THREAD

**Issue by tiramisutes** [lh3/minimap2#994]
Dear,
When I aligned two 2G size genomes, minimap2 ran with 20 CPUs for a week and still did not finish. Therefore, is it possible to index the genomes separately and then align them to speed up this process? But I failed after trying according to the following command. So what can I do to speed up this process?
```
minimap2 -d genome1.mmi genome1.fasta
minimap2 -d genome2.mmi genome2.fasta
minimap2 -ax asm5 -t 20 --eqx genome1.mmi genome2.mmi > genome12.sam
```

**Comment by lh3** [comment]
> `minimap2 -ax asm5 -t 20 --eqx genome1.mmi genome2.mmi > genome12.sam`

Should be

```
minimap2 -ax asm5 -t 20 --eqx genome1.mmi genome2.fasta > genome12.sam
```
