### ISSUE TITLE
Minimap2 discarding too many reads after mapping and filtering

### ISSUE THREAD

**Issue by ToriannM** [lh3/minimap2#995]
Hi,

I am attempting to filter out ONT mitochondrial reads from nuclear via minimap2 for the purposes of assembling a mitochondrial genome. To do this, I have taken a mitochondrial reference from a closely related species. However, when I filter by mapped reads and move to Canu for assembly, I have too low of coverage to assemble. I think I am somehow losing mitochondrial reads during the mapping process.

This is the code I am using to map:

>minimap2 -ax map-ont ref.fasta *.fastq.gz > aln.sam #map reference to reads
>samtools sort aln.sam > sorted_aln.bam #sort reads
>samtools index sorted_aln.bam #index sorted reads
>samtools view -b -F 4 sorted_aln.bam > mapped_sorted_aln.bam #pulling out only mapped reads
>bedrolls samtofastq - mappedOnly.bam > mapped_sorted_aln.fastq #convert bam to fastq

I only get 17 fairly short reads in the final file (out of thousands of reads initially). Attached is the final file:
[mapped_sorted_aln.fastq.zip](https://github.com/lh3/minimap2/files/10106340/mapped_sorted_aln.fastq.zip)

I would appreciate any feedback on why this isn't working.

Thank you!!

**Comment by lh3** [comment]
Perhaps the divergence is too high.
