### ISSUE TITLE
parameter to control alignment mismatch rate filtering?

### ISSUE THREAD

**Issue by chucknordy** [lh3/minimap2#996]
I'm familiar with short-read mapping (in particular with STAR), but am fairly new to long-read mapping... and I'm wondering about the possibility of setting an alignment threshold with minimap2, in terms of a **rate of errors** (mismatches and/or indels) with respect to the genome reference. That is, I'd like to be able to limit the alignments I get to only those that have at least, say, a 90% exact match between the read and the reference, or only those reads with less than, say, 20 total mismatches.

With STAR, this can be controlled via the Output Filter options, such as `outFilterMismatchNoverLmax` or `outFilterMatchNminOverLread`. But I can't figure out if there is any equivalent or similar command-line parameter that can be used in minimap2.  Any ideas?

**Comment by lh3** [comment]
Please write a script to filter in your desired way.
