### ISSUE TITLE
maybe a wrong annotation?

### ISSUE THREAD

**Issue by csyourui** [lh3/minimap2#997]
hi!
The function annotation of `mg_lchain_dp()` in `lchain.c` is a little confusing
https://github.com/lh3/minimap2/blob/822ccd173358f11842b6dc54e17bbdcc2d9a0a9a/lchain.c#L140-L149
The meaning of `a[].x` should be `rev << 63 | tid << 32 | tpos` I suppose. 
Please let me know if i am misunderstanding something here, thankyou!

**Comment by lh3** [comment]
You are correct. The comment came from minigraph, which uses a different packing.
