### ISSUE TITLE
Inconsistant alignments between Mappy and Minimap2

### ISSUE THREAD

**Issue by Adoni5** [lh3/minimap2#998]
Hey,

I've recently noticed that the alignments I get back from mappy using preset map-ont are slightly different from minimap2 on the command line, and was hoping that someone could explain this to me!

**Program**|**Query start coordinate**|**Query end coordinate**|**Strand**|**Target sequence name**|**Target sequence length**|**Target start**|**Target end coordinate**|**Number of matching bases**|**Number bases (w. gaps)**|**Mapping quality**
-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----
Mappy|0|350|+|NC\_001133.9|230218|173460|173810|350|350|60
Minimap2|1|346|+|NC\_001133.9|230218|173461|173806|345|345|60

The read, index and preset are all the same. I've created a small repository with a Minimum Working example of this here - https://github.com/Adoni5/mappy_issue. As far as I can tell all mapping opts should be the same!

Any help/explanation greatly appreciated!
Many Thanks 
Rory

**Comment by lh3** [comment]
add `-c` to minimap2.
